### ISSUE TITLE
layouts can break if browser default font size isn't 16px

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1011]
The base font-size is expected to be 16px but is never set. If you change the default font-size in your browser the calculations for variables in _frameless are not the expected values.

For example, in T3 tiles, the width of a tile is expected to be cols4 (300px) which allows 3 columns of tiles on a desktop display. With a default font-size of 18px, cols4 ends up being 337.5px wide, so only two columns fit in the desktop display width. The Explore page is also a bit off if the default font-size is 18px. Note that the trending/popular/recent dropdown is cut off, although you can scroll to everything.
![Screen Shot 2016-11-09 at 9.48.26 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/4ce9961f-f5a0-4683-8b2c-382ce71ae32a/Screen+Shot+2016-11-09+at+9.48.26+PM.png)

For accessibility reasons it's probably not a great idea to set the override the default font-size set in the browser, although that does fix everything.

**Comment by rschamp** [comment]
We should override the default font-size.

**Comment by hello-smile6** [comment]
> We should override the default font-size.

Maybe something like this, at the start of the first stylesheet loaded?
```
h1 {
  font-size: 16px;
}

**Comment by hello-smile6** [comment]
Think e1cebe46db15e1fc7fa82019301c699739896d6a fixed it.
https://github.com/LLK/scratch-www/blob/e1cebe46db15e1fc7fa82019301c699739896d6a/src/main.scss#L29
@rschamp

**Comment by rschamp** [comment]
Thank you - yes this looks fixed.

**Comment by hello-smile6** [comment]
> Thank you - yes this looks fixed.

I noticed that it seemed to have been forgotten.
