### ISSUE TITLE
Creator username influencing a project's Explore category too much?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1014]
Reported by @Paddle2See.

The user Brad-Games's projects are showing up in Explore under Games. Some of them are games, but some are not. 
For example:
- Art project 127520418, although it also has "game" in the description on the Project Page.
- Story or animation project 127533381, which doesn't have anything in the description.

The user said that this is causing his projects to get reported, and suggested his username is what is causing the miss-categorization.

/cc @mewtaylor

**Comment by Paddle2See** [comment]
Thanks for making this!

Here is the original comment, in case it is useful

![image](https://cloud.githubusercontent.com/assets/3766964/20197913/cf561142-a76f-11e6-859e-bc8c3b177ba7.png)

**Comment by rschamp** [comment]
Moved to LLK/scratch-api#242
