### ISSUE TITLE
Blank share date field on a shared project

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-www#1015]
The date field that is shown on the project page below the tags is blank on a project I just observed

![image](https://cloud.githubusercontent.com/assets/3766964/20237199/ac34d448-a899-11e6-8204-f183aa84c2dc.png)

Here is the project

https://scratch.mit.edu/projects/125828206/

Looking in the project_projects table, the datetime_first_shared field has a null value - that shouldn't be happening, I don't think

![image](https://cloud.githubusercontent.com/assets/3766964/20237215/03408d22-a89a-11e6-8286-9d34f74b69a7.png)

The shared date is an important field for moderators as it is used to help determine credit complaints - it should not be blank on shared projects.

**Comment by jwzimmer** [comment]
Moved to LLK/scratchr2#4270
