### ISSUE TITLE
Navigating to the Privacy Policy Changes Language to Polish

### ISSUE THREAD

**Issue by TheGrits** [LLK/scratch-www#1019]
Seen on Chrome 54 on ChromeOS, going to test on Windows 7.

![screenshot 2016-11-15 at 7 16 04 pm](https://cloud.githubusercontent.com/assets/12952370/20329705/f8d99682-ab67-11e6-9bee-8fa706a6b326.png)

To reproduce:

1) Navigate to the Privacy Policy via the link in the footer. (Seems to work on any page)

or

2) Navigate to https://scratch.mit.edu/privacy_policy/ by typing it in the address bar.

UPDATE:
Does not occur in incognito mode, perhaps it is a caching issue...

**Comment by chrisgarrity** [comment]
@theGrits thanks for reporting. It might be related to https://github.com/LLK/scratch-www/issues/1021, we're tracking that one. If you think it's different please add more details for reproducing.
