### ISSUE TITLE
Setting interface language on About and Explore pages does not persist

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1021]
This happens on Production & Staging.

Test case:
- on the splash page change your language to Spanish
- Go to Explore page - content should be in Spanish,
- Switch language to something else, e.g., Greek, Explore page is translated to Greek,
- Go to Splash page, content should be in Greek, but has reverted to Spanish.
- Switch language to German, Splash page is in German,
- Go to Explore page, should be in German, it is still in Greek

**Comment by jwzimmer** [comment]
I ran into this when going from the Explore page to Discuss; I changed the language in Explore, but when I went to Discuss, it was in the language I had previously been using.

**Comment by jwzimmer** [comment]
I noticed this on Staging with Farsi, going from the Download Offline Editor page to the Scratch Terms of Use (the language switched back to English on the ToU page).

**Comment by jwzimmer** [comment]
Make sure the repro steps/ test case described in https://github.com/LLK/scratch-www/issues/1199 is fixed when this issue is closed. 👍

**Comment by WorldLanguages** [comment]
@thisandagain I think this was fixed with #1553, should this be closed?

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-www/pull/1553
