### ISSUE TITLE
Explore page header is not translated

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1023]
The Explore page header and the "Trending, Popular, Recent" drop down are not translated.

Should be able to use the general.explore message id for the header

![Screen Shot 2016-11-16 at 9.57.00 AM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/bff870e7-6979-4f1d-8098-b39bb9f2a7b6/Screen+Shot+2016-11-16+at+9.57.00+AM.png)

**Comment by chrisgarrity** [comment]
Check whether the Search header is translated as well

**Comment by TheGrits** [comment]
@chrisgarrity Good call, perhaps that should be a separate issue? (It isn't translated)
