### ISSUE TITLE
Language preference is not persistent between sessions

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1024]
From a user:
![image](https://cloud.githubusercontent.com/assets/747641/20357597/9872c43c-abf6-11e6-9dc9-2d8b54f54298.png)

/cc @jwzimmer @mewtaylor @chrisgarrity

**Comment by TheGrits** [comment]
Seems to be related to #1019 and #1021

**Comment by jwzimmer** [comment]
Trying to repro - in progress : )

Chrome 54, Mac OS 10.11, Production

- I set my language in System Preferences (on my mac) to Spanish
- I went to Scratch homepage while logged out
- Language is Spanish
- Cookie expires at "session" (according to network tab)
- Changed language to English (on homepage)
- Closed tab
- Reopened Scratch homepage in new tab, same browser session
- Language is English
- In new incognito window, language is Spanish
- Changed language to English
- Closed window
- In new incognito window, language is Spanish
- (So far so good)
- Signed in as jwzimmer1990
- Changed language to English
- Closed window
- In new incognito window, language is Spanish
- Signed in as jwzimmer1990
- Language is still Spanish

**Comment by jwzimmer** [comment]
I think we will be addressing this with https://github.com/LLK/scratchr2/issues/3910 in the December milestone:
> **Don't expire language cookie at browser close**
> It appears that we're setting a max age on the language cookie to expire at browser close (i.e. django's default LANGUAGE_COOKIE_AGE setting). We could extend it to persist beyond closing the browser...

We're planning to extend it to persist for 1 year.
