### ISSUE TITLE
Link for Trust & Safety Manager on Jobs page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1026]
As discussed with @mewtaylor, on the jobs page on Staging, we updated the jobs available in https://github.com/LLK/scratch-www/pull/989 (which is in the **November 14** milestone) but it looks like the link for the trust & safety manager  position will still not work.

**Comment by TheGrits** [comment]
@jwzimmer If the correct URL is available I can make a pull request ASAP.

**Comment by jwzimmer** [comment]
@TheGrits Finding the correct URL is definitely part of this issue... have to find it first. : D

**Comment by TheGrits** [comment]
@jwzimmer Found it: http://media.mit.edu/about/opportunities/trust-and-safety-manager-scratch-lifelong-kindergarten

**Comment by jwzimmer** [comment]
@TheGrits Great, let's verify with @kaschm that the link is correct first just to make sure. Thanks.

**Comment by TheGrits** [comment]
@jwzimmer Sounds good. I made a commit on my repository already, so I'm ready to make the PR when it is confirmed.

**Comment by jwzimmer** [comment]
@TheGrits The link is correct, confirmed by @kaschm 👍 
Thank you! : )
