### ISSUE TITLE
"Learn More" link extends out of element in Projects Curated By row - Mobile

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1029]
iPhone 6, Chrome 54.0.2840.91, Production

The link "Learn more" in the header of the "Projects curated by" row (on the homepage) extends out of view on my smart phone. The bottom half of the link isn't visible. The link is still clickable/ works. (Not sure if this will be true for other people - a few mobile bugs I've seen on my phone have been hard to repro on other devices.)

![img_2236](https://cloud.githubusercontent.com/assets/1320456/20391300/caa8291a-aca0-11e6-8246-56bb6cecaa6e.PNG)

**Comment by jwzimmer** [comment]
If you choose a language for which the string is longer than English, e.g. Spanish, it looks like the link gets pushed out of view by the longer string. The link shows up as expected for Chinese, so it looks like what's happening is that the link isn't in the right place when strings are too long.

**Comment by TheGrits** [comment]
Can reproduce on a Samsung Note 3 running Android 5.0:
![screenshot_2016-11-17-09-43-04](https://cloud.githubusercontent.com/assets/12952370/20393615/89953df0-acaa-11e6-831a-069c22a4dbdf.png)
