### ISSUE TITLE
Radio buttons off-center in join flow modal > gender step - Mobile

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1034]
I can't tell if this is on Production on an iPhone 6s, because I can't proceed to this step on a mobile phone on production. Staging, Chrome 54, iPhone 6s.

The radio buttons next to gender (M, F, other) are off-centered from the labels in the Join Flow modal.

![img_2249](https://cloud.githubusercontent.com/assets/1320456/20442265/0c0e0adc-ad96-11e6-9d26-b775b4f97893.PNG)

**Comment by rschamp** [comment]
Moved to LLK/scratchr2#4581
