### ISSUE TITLE
Join Flow modal > Country menu opens upwards - Firefox

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1035]
This happens on Staging & Production, Firefox 49.0.2, Mac OS 10.11.

In the Join Flow modal > Country step, when you click the dropdown menu, it opens upwards and covers up the browser bar, which looks kind of strange.

Production
<img width="747" alt="captura de pantalla 2016-11-18 a las 1 54 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/20442509/cc814bc6-ad96-11e6-999b-958ba05a97ab.png">

Staging
<img width="1076" alt="captura de pantalla 2016-11-18 a las 1 42 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/20442511/cc89bd1a-ad96-11e6-9e69-77e781e6e73f.png">

In Chrome, the menu opens downwards.
<img width="734" alt="captura de pantalla 2016-11-18 a las 1 47 56 pm" src="https://cloud.githubusercontent.com/assets/1320456/20442510/cc85a072-ad96-11e6-9698-813e2ac12fd7.png">

**Comment by rschamp** [comment]
IMO this is Firefox's bug, since it's how they've decided to render native dropdowns. Eventually we'll probably start using a custom dropdown component which would solve this issue in software. I'd be for closing this with that in mind.

**Comment by jwzimmer** [comment]
Closing for the reasons outlined by @rschamp.
