### ISSUE TITLE
Minor content differences on TTT page between spec & Staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1041]
Comparing content from https://github.com/LLK/scratch-www/issues/979#issuecomment-257947919

1) Text at top of page should say:
 > You can get started with Scratch in a variety of ways. Click an image to try the **Tutorial**. You can also download a set of **Activity Cards** and an **Educator Guide** for each theme.
 
However, it says "a Tutorial" instead of "the Tutorial".

2) The text at the top of the page says:
 > You can get started with Scratch in a variety of ways. Click an image to try a **Tutorial**. You can also download a set of **Activity Cards** and an **Educator Guide** for each theme.

However, the bolding isn't visible in every browser. For example, it's missing in IE 11 or Edge on Win 10, but visible on an iPad + Safari or Chrome + Mac OS 10.11.

3) What's referred to in the copy as "Hide and Seek" is titled "Hide-and-Seek Game" on Staging.
(The other tiles' content on Staging matches what's in the comment/ copy.)

/cc @kaschm & @chrisgarrity

**Comment by chrisgarrity** [comment]
fixed in #1056
