### ISSUE TITLE
TTT Page > Modal > "Download" buttons - should they say "Download"?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1043]
When you click “Download” for the content for the tutorial, were we envisioning that it would open the pdf, or directly download it?

In IE it was asking me if I wanted to download the file in a banner at the bottom of the page. In Chrome it opens the PDF and I can then download the PDF from there.

If we like the Chrome behaviour, or maybe even in both cases, clicking the button that says "Download" doesn't actually initiate a download... this is very minor, but I just wondered about that - maybe download was the best word for the button to have, even if it's not an exact description of the button's action?

/cc @kaschm & @carljbowman

**Comment by chrisgarrity** [comment]
Most browsers open PDFs by default, but I think it's also a browser setting that the user can change. We could think about using 'Open' or 'Open PDF' instead of Download as that's closer to the default for most people.

**Comment by jwzimmer** [comment]
@ntlrsk decided "Open" would be preferable.

**Comment by chrisgarrity** [comment]
Fixed in #1056
