### ISSUE TITLE
Shortcut URLs for Story & Fashion tutorial guides yield 403 error

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1049]
URLs listed in https://github.com/LLK/scratch-www/issues/972.

Tested in https://github.com/LLK/scratch-www/pull/1006#issuecomment-261662764.

 **Chrome 54, Mac OS 10.11, Staging**

The URLs for the cards for Story & Fashion work:
- scratch.ly/story/cards -> /pdfs/help/StoryCards.pdf
- scratch.ly/fashion/cards ->  /pdfs/help/FashionCards.pdf

However the URLs for the guides for Story & Fashion yield a 403 error:
- scratch.ly/story/guide -> /pdfs/help/StoryGuide.pdf
- scratch.ly/fashion/guide ->  /pdfs/help/FashionGuide.pdf

As discussed with @mewtaylor.
 
/cc @ntlrsk

**Comment by ntlrsk** [comment]
This is expected as the Story and Fashion guides and tutorials are being released later. Thanks for testing.
