### ISSUE TITLE
add additional shortcut for Make It Fly cards

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#1055]
Some of the Make It Fly cards that went out earlier have a longer URL so it would be good to add this redirect. 

scratch.mit.edu/makeitfly --> /scratchr2/static/pdfs/help/FlyCards.pdf

**Comment by mewtaylor** [comment]
@ntlrsk right now `/fly` points to the editor with the tutorial, and `/fly/cards` points to the pdf. Should `/makeitfly` points to the cards, or the editor?

**Comment by ntlrsk** [comment]
Point /makeitfly to the editor (same as /fly ) - thanks @mewtaylor!
