### ISSUE TITLE
HOC banner - Edges of tiles not aligned with banner title/ button

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1076]
The things to try button's right edge is not aligned with the right edge of the rightmost tile, and the "Get creative with coding" title is not aligned with the left edge of the leftmost tile.

@carljbowman said:
> ...we should look into fixing that, but certainly not a blocker.
Looks like the tutorial tiles are set to `space-around`, rather than `space-between`. That said there may be a reason for that.

**Comment by mewtaylor** [comment]
@carljbowman @jwzimmer `space-around` just happens to be the default – I can easily switch it to `space-between` sounds good to me!

**Comment by mewtaylor** [comment]
Fixes in #1079
