### ISSUE TITLE
Buttons say "ttt.open" instead of "Open" - HOC Banner > Modal

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1078]
The button text in the modals says "ttt.open". It should say "Open" as it does on the TTT page.

To repro, go to the homepage on staging, then click "See Cards & Guides" to open the modal.

<img width="776" alt="screen shot 2016-11-28 at 3 05 47 pm" src="https://cloud.githubusercontent.com/assets/1320456/20684025/467a3090-b57c-11e6-8fec-23c1356f5d97.png">

**Comment by mewtaylor** [comment]
fixed in https://github.com/LLK/scratch-www/issues/1079
