### ISSUE TITLE
HOC banner - on smaller widths, "see things to try" button & title are not centered

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1083]
Staging, IE 11 on Win 7 VM & Chrome 54 on Mac OS 10.11

According to the design specs in #981, when the window is resized to smaller than desktop width (resized window, tablet, mobile) the button and title in the banner should be centered. However, they are left-aligned.

<img width="672" alt="screen shot 2016-11-29 at 12 01 24 pm" src="https://cloud.githubusercontent.com/assets/1320456/20720210/4e6633d4-b62c-11e6-8f40-ad6d4af93689.png">

**Comment by mewtaylor** [comment]
Ha – didn't realize `space-around` is what allowed that to happen, funny.

**Comment by jwzimmer** [comment]
(Note, it does look centered at a small-enough width, so between desktop & mobile-ish size is when it's not centered.)

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/1085
