### ISSUE TITLE
Update Scratch Conference Site 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#1086]
Updating scratch.mit.edu/conference. 

Design below.

**Comment by sleggss** [comment]
Mock of the mock:

[Scratch Conf Wireframe 02.pdf](https://github.com/LLK/scratch-www/files/694399/Scratch.Conf.Wireframe.02.pdf)

**Comment by lifeinchords** [comment]
Design mockup, with 2 of the 6 events.

![Conf 2017, Sm - Alt 3.png](https://codetreeusercontent.s3.amazonaws.com/uploads/7dca7eea-4194-404f-a22a-501feb4c02db/Conf+2017%2C+Sm+-+Alt+3.png)

**Comment by kaschm** [comment]
Question for @lifeinchords - I'm guessing that the 'Learn More' buttons are the websites, where applicable, and otherwise are mailto: links? Is that right?

**Comment by lifeinchords** [comment]
Yes! My bad - I didn't annotate the designs.

**Comment by kaschm** [comment]
Edit from ST, @mewtaylor  - update title to be 'Scratch Conferences' (plural) rather than 'Scratch Conference' (singular). 

Thanks!

**Comment by mewtaylor** [comment]
Implemented in #1184
