### ISSUE TITLE
Signing in/ out in tablet causes hover effect on tile in HOC banner

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1088]
Staging, Apple iPad tablet, Safari, Name: Pao de Quejao

Clicking sign in/ out registers with tile underneath; causes hover effects. The "Try it" button appears & the sheer darker blue tint appears over the tile graphic. To repro, sign in/ out from the navbar in the homepage (over the rightmost HOC banner tile).

![img_2577](https://cloud.githubusercontent.com/assets/1320456/20735218/a0e365d8-b66c-11e6-8322-ac95483b78fe.JPG)

**Comment by mewtaylor** [comment]
Seems like perhaps the inputs are not preventing the touch events from propagating. I don't think this is a blocker for release, but @carljbowman I defer to you if you feel differently!
