### ISSUE TITLE
See things to try button slightly lower than title - HOC banner

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1089]
On Staging, Chrome Version 54.0.2840.98 (64-bit), Mac OS 10.11 & iPad, Safari & Android, Chrome

The center of the "see things to try" button is slightly lower than the center of the banner's title (in the spec they look like they're about even).

<img width="1013" alt="screen shot 2016-11-29 at 7 51 31 pm" src="https://cloud.githubusercontent.com/assets/1320456/20735334/71e6295e-b66d-11e6-93e9-8c0b42ab0773.png">

**Comment by mewtaylor** [comment]
This is a one line fix, so I'm happy to do it!

**Comment by mewtaylor** [comment]
Fixed in #1090
