### ISSUE TITLE
Missing translations: Duplicate strings in the same l10n.json file

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1102]
While working on the transifex import I discovered that the scripts that convert po files to intl/* still have a problem if there are duplicate strings in the same l10n file. Some examples:

In src/l10n.json:
"registration.studentUsernameStepTitle": "Create a Scratch Account",
"registration.usernameStepTitleScratcher": "Create a Scratch Account",

In teacherregistration/l10n.json
"teacherRegistration.phoneStepTitle": "Phone Number",
"teacherRegistration.phoneNumber": "Phone Number",
"teacherRegistration.orgStepTitle": "Organization",
"teacherRegistration.organization": "Organization",

Do we really want/need to have the same string defined multiple times in the same view?

Fortunately, in the long run transifex will handle the same text with different keys just fine. However, right now this causes a bug in the scripts that convert files - the earlier fix I made handles the same string in different l10n files, but not in the same one.

**Comment by chrisgarrity** [comment]
@rschamp @mewtaylor I think we decided that there should not be duplicate strings in the same l10n.json file - agree?

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/1150
