### ISSUE TITLE
Homepage rows not loading - blank thumbnail, title "Project", etc.

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1109]
Chrome 54 + Mac, IE 11 + Win 7 VM, **Staging**

Error console:
> www No response body
console.(anonymous function)
XMLHttpRequest cannot load https://googleads.g.doubleclick.net/pagead/id. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.youtube-nocookie.com' is therefore not allowed access.

<img width="1265" alt="screen shot 2016-12-13 at 12 16 53 pm" src="https://cloud.githubusercontent.com/assets/1320456/21150753/1a6b1efc-c12e-11e6-8d5b-834b7d022f87.png">

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratchr2/pull/4409

**Comment by mewtaylor** [comment]
also in https://github.com/LLK/scratchr2/commit/bf41bb46b14f0ca9c9d7bb0144c7ba2eefbe88e4
