### ISSUE TITLE
Uncaught ReferenceError: formatMessage is not defined - Teacher Registration, Portuguese, Brazilian Portuguese

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1125]
Potential blocker for https://github.com/LLK/scratch-www/pull/1099, if it was caused by that PR?

Staging, Chrome 55, Mac OS El Capitan

The error shows up in the console on the first step of Teacher Registration if you set the language to Portuguese.

<img width="1277" alt="screen shot 2016-12-16 at 9 23 24 pm" src="https://cloud.githubusercontent.com/assets/1320456/21283729/fbfe4c32-c3d5-11e6-914c-227c8dc97ee0.png">

**Comment by jwzimmer** [comment]
Occurs with Brazilian Portuguese as well, Staging, Firefox 50.0.2, Mac OS El Capitan:
<img width="1181" alt="screen shot 2016-12-16 at 9 45 10 pm" src="https://cloud.githubusercontent.com/assets/1320456/21283847/03774e16-c3d9-11e6-8c34-66735e965d14.png">

**Comment by mewtaylor** [comment]
Fixed in #1127
