### ISSUE TITLE
Update "Download Flash" link on FAQ 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#1130]
This is happening on production. 

On the General FAQ (scratch.mit.edu/info/faq), we don't point users to the correct link to download Adobe Flash:

**What are the system requirements for Scratch?**
To run Scratch 2, you need to be using (1) a Mac, Linux, or Windows computer; (2) a version of **Adobe Flash Player** released on or after June 15, 2016; 

The link should go here: https://get.adobe.com/flashplayer/

**Comment by thisandagain** [comment]
Assigning to @mewtaylor for PR review from contributor. :-)
