### ISSUE TITLE
The cat-b image on the homepage is using the wrong URL

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1145]
Currently it is using https://cdn.scratch.mit.edu/scratchr2/static/images/cat-b.png, but it should be located in scratch-www. Currently it 404s.

The cat-b image is the one when you hover over the Scratch Cat on the homepage when you are logged out:
<img width="213" alt="screen shot 2017-01-10 at 11 00 25 am" src="https://cloud.githubusercontent.com/assets/1320456/21815035/4e2f8348-d729-11e6-8ed2-7d1e3108c517.png">

**Comment by TheGrits** [comment]
Can reproduce on Chrome with ChromeOS.

**Comment by TheGrits** [comment]
Strange, now trying to access the cat-b image brings up an IP appeal page: https://cdn.scratch.mit.edu/ip_ban_appeal/206.176.100.14/

Looking at the IP in an IP finder, the IP belongs to a machine owned by Rapid City Public Schools. (South Dakota)

**Comment by jwzimmer** [comment]
Hi @TheGrits, I believe that is due to caching. We have another case where we need to switch which server the image is loaded from (so it will come from a static file server) because it should always return the same content. Once that's fixed I don't think you should encounter this again. Thanks. : )

**Comment by TheGrits** [comment]
@jwzimmer fyi the IP was completely unrelated. I live in Canada, not South Dakota. 👍

**Comment by TheGrits** [comment]
@mewtaylor @jwzimmer Image no longer 404s, the issue can be closed!
