### ISSUE TITLE
Add "South Sudan" to dropdown list of Locations

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-www#1146]
As pointed out in this forum topic

https://scratch.mit.edu/discuss/topic/233158/

South Sudan is a UN recognized country and it should be in our list of locations.

**Comment by TheGrits** [comment]
Looks like the [package](https://www.npmjs.com/package/iso-3166-2) that we [import](https://github.com/LLK/scratch-www/blob/develop/src/lib/country-data.js#L2) is up-to-date: [(South Sudan country code)](https://github.com/olahol/iso-3166-2.js/blob/master/codes.csv#L208) and [(South Sudan states/codes)](https://github.com/olahol/iso-3166-2.js/blob/master/data.csv#L3967-L3976)

Therefore, I'm not entirely sure why it isn't already added.

**Comment by mewtaylor** [comment]
@TheGrits the countries list we have is actually maintained in our old repo still (scratchr2), while that package is the one we use for teacher registration. @Paddle2See I can migrate this over to scratchr2 if that would be okay with you.

**Comment by TheGrits** [comment]
@mewtaylor Oh, that makes sense. Thanks for pointing of that gotcha!

**Comment by Paddle2See** [comment]
@mewtaylor that would be great.  I just pick repo names at random and throw issues into them.  I know you'll sort it all out somehow ;)

**Comment by mewtaylor** [comment]
Moved to https://github.com/LLK/scratchr2/issues/4441
