### ISSUE TITLE
Unpleasant grammar in email address validation message: "You must provide valid email address"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1147]
Production & Staging, Chrome 55, Mac OS El Capitan

**TL;DR** Error message has awkward grammar during registration.

**====**
Fix: Something like "You must provide a valid email address". /cc @kaschm 

Repro:
- Click Join Scratch on the homepage
- Go to the email step
- Enter an email address like "aaa@aaa .com"
- Click in the 2nd email address field
- Note error message

<img width="1025" alt="screen shot 2017-01-11 at 11 32 57 am" src="https://cloud.githubusercontent.com/assets/1320456/21857029/0d76510a-d7f2-11e6-8cbf-b4de177a3b6b.png">

**Comment by TheGrits** [comment]
@mewtaylor So if I'm thinking straight, this is in the scratchr2 repository too right?

**Comment by kaschm** [comment]
+1 on @jwzimmer's suggested text, 'You must provide a valid email address'

**Comment by mewtaylor** [comment]
@TheGrits you are correct! @jwzimmer I can move this over to scratchr2 if you'd like me to! Unless it's also in the teacher registration?

**Comment by jwzimmer** [comment]
I can move it in codetree. I don't think it happens in teacher/ student registration. 👍 @TheGrits & @mewtaylor

**Comment by jwzimmer** [comment]
Moved to LLK/scratchr2#4443
