### ISSUE TITLE
Typing "%" into search causes a fatal exception

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1153]
Operating System: `Mac OS 10.12.2`
Browser: `Chrome 52.0.2743.116 (64-bit)`

### To Reproduce
- Go to any page on Scratch
- Enter "100% pen" (or anything with a "%") into the search field
- Hit return

### Expected
- See search results

### Actual
- Fatal exception

### Reference
```
search.jsx:138 Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
    at Constructor.render (search.jsx:138)
```

**Comment by liam4** [comment]
Actually it'd seem that just typing "%" causes the crash. (I'm sure you guys noticed that, though.)

**Comment by TheGrits** [comment]
I guess this is Scratch's version of the blue screen of death!

Can confirm using Chrome 55.0.2883.105 (64-bit) on ChromeOS.

**Comment by WorldLanguages** [comment]
Same on Windows 10 - Chrome 55.0.2883.87

I think Scratch interprets the % as a symbol to go before a symbol code (like %20) and Scratch can't get the symbol "%20[...]" because the correct symbol would be "20[...]

**Comment by WorldLanguages** [comment]
It gets fixed if we use %25 instead of % in the URL.

[](https://scratch.mit.edu/search/projects?q=100%25%20pen)

**Comment by thisandagain** [comment]
In general it appears that we are no longer encoding / decoding uri components properly. Looking quickly at the code, my guess is this was introduced by this PR: https://github.com/LLK/scratch-www/commit/cbd983baf8ea720928c62707bb68676d3b30eef3

@mewtaylor any thoughts?
