### ISSUE TITLE
Add wiki button to navigation button.

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-www#1156]
The wiki page is a great resource but there is not easy enough access to the wiki page. Simply adding a button on the navigation bar leading to the wiki page could fix this problem

**Comment by rschamp** [comment]
Hi @CosmicWebServices, thanks for the suggestion. We are not planning to put any more items into the top navigation bar at this time, as we already have trouble with the current number of items there, especially on mobile.
