### ISSUE TITLE
Issue with fresh install

### ISSUE THREAD

**Issue by kirkins** [LLK/scratch-www#1162]
Using node v 4.0.0:

I cloned this project locally. Ran `npm install`, followed by `npm run build`.

Some parts of the site work like home page and about. Other parts like create don't work at all, it just returns:

> Cannot GET /projects/editor/?tip_bar=home

**Comment by kirkins** [comment]
Ok I don't know why I thought I should be using node v 4.0.0 misread someone else's post. It seems that I need 4.2.0 or higher.

**Comment by kirkins** [comment]
I uninstall and re-installed with node v 4.2.0.

I'm still having the same issue

**Comment by rschamp** [comment]
Not all pages on Scratch are migrated to this repository. The editor and project pages are still hosted by our legacy infrastructure. If you are able to view the homepage, then your install is working correctly.

**Comment by kirkins** [comment]
@rschamp thanks, so If I install a second repo I can get it working?

**Comment by rschamp** [comment]
Unfortunately that other repository (scratchr2) is not public.
