### ISSUE TITLE
Add two new activities to the /go page 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#1170]
Adding Story and Fashion to the activities on scratch.mit.edu/go 

As a reminder, we'll need the following for each Activity:

Story 

- [ ] Final title
- [ ] Final description 
- [ ] Image
- [ ] Banner image
- [ ] Link to Tutorial
- [ ] Link to Guide
- [ ] Link to Cards 

Fashion

- [ ] Final title
- [ ] Final description 
- [ ] Image
- [ ] Banner image
- [ ] Link to Tutorial
- [ ] Link to Guide
- [ ] Link to Cards

**Comment by thisandagain** [comment]
@chrisgarrity Do you think you will have time to get to this during the current iteration? If not, we should push this to March.

**Comment by chrisgarrity** [comment]
@thisandagain  Do we have the content? - it doesn't take much if we have the content, just updating the json files in https://github.com/chrisgarrity/scratch-www/tree/develop/src/views/thingstotry

**Comment by thisandagain** [comment]
@chrisgarrity It looks like we are still missing quite a bit of content which makes it unlikely that we'll be able to finish this during the current iteration. Moving to March.

**Comment by ntlrsk** [comment]
@sotts and Shruti and will have the content ready.  We plan to add them before the freeze and I can add the links earlier. Can we move back to this release?

**Comment by ntlrsk** [comment]
Oh, @carljbowman wondering if you had already made the main image for Story and Fashion for TTT page, or do those need to wait for March?

**Comment by thisandagain** [comment]
@ntlrsk Ok. Moving back to our freeze on Wednesday. When can we expect the content to be ready?

**Comment by ntlrsk** [comment]
@carljbowman Oh thanks! I found the banner images you had made: 
https://scratch.mit.edu/images/ttt/create-a-story-banner.jpg
https://scratch.mit.edu/images/ttt/fashion-game-banner.jpg

**Comment by ntlrsk** [comment]
@chrisgarrity 
FOR STORY:
Final Title: Create a Story
Final description: Choose characters, add conversation, and bring your story to life.
Image: https://scratch.mit.edu/images/ttt/create-a-story-banner.jpg
Link to tutorial: https://scratch.mit.edu/projects/editor/?tip_bar=story
Link to guide: https://scratch.mit.edu/pdfs/guides/StoryGuide.pdf   
Link to cards: https://scratch.mit.edu/pdfs/cards/StoryCards.pdf

FOR FASHION
 Final title: Fashion Game
 Final description: 
Make a game where you dress a character with different clothes and styles.
[Note: Or, if that's too long to fit on 2 lines, then:  Dress up a character with different clothes and styles.]
 Image: https://scratch.mit.edu/images/ttt/fashion-game-banner.jpg
 Link to Tutorial: https://scratch.mit.edu/projects/editor/?tip_bar=fashion
 Link to Guide: https://scratch.mit.edu/pdfs/guides/FashionGuide.pdf   
 Link to Cards:  https://scratch.mit.edu/pdfs/cards/FashionCards.pdf

Note: Tutorials and guides will be made available at those links by or before the freeze

Thanks!

**Comment by chrisgarrity** [comment]
@ntlrsk Can you confirm the order and placement of these new activities. Based on original TTT issue, I'm assuming they come between **hide** and **pong**, fashion first, then story.

**Comment by chrisgarrity** [comment]
@ntlrsk I just realized that we need two images for each activity, image and banner. Image is what appears on the /go page, banner is in the modal popup. Image dimensions are 750x450

**Comment by carljbowman** [comment]
@chrisgarrity - We preemptively added all the image assets.

#### For Fashion
Tile image: https://scratch.mit.edu/images/ttt/fashion-game.jpg
Banner image: https://scratch.mit.edu/images/ttt/fashion-game-banner.jpg

#### For Story
Tile image: https://scratch.mit.edu/images/ttt/create-a-story.jpg
Banner image: https://scratch.mit.edu/images/ttt/create-a-story-banner.jpg

**Comment by chrisgarrity** [comment]
@ntlrsk Ignore last comment - I realized the images are in the ttt directory - just not listed in the earlier comment above. Thanks!

**Comment by chrisgarrity** [comment]
@thisandagain I just added a PR for this and assigned @ntlrsk  and @mewtaylor for reviews, feel free to reassign.

**Comment by thisandagain** [comment]
Thanks @chrisgarrity !
