### ISSUE TITLE
Footer > For Developers link should be `/developers/` (currently missing the ultimate slash)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1171]
**TL;DR:** In the footer, the general pattern is to end all the links with a slash, but currently the link For Developers is just `/developers`. 

No effect on functionality, but I don't think there's a reason we couldn't be consistent here (and end all the links with `/`).

Found this with a WIP automated test for the footer links on the homepage!

**Repro:**
- Click on the "For Developers" link in the footer of the homepage
- Note the page redirects to `scratch.mit.edu/developers`
- Try other links, e.g. Credits or About Scratch
- Note they redirect to pages with ultimate `/`s

**Comment by thisandagain** [comment]
@jwzimmer Would you want to take a shot at resolving this and submitting a PR?

**Comment by TheGrits** [comment]
@thisandagain FYI I have already have made a PR at #1172

**Comment by thisandagain** [comment]
Whoops! You are too fast for me @TheGrits ! 😄

**Comment by mewtaylor** [comment]
@jwzimmer @TheGrits @thisandagain closing this as expected
