### ISSUE TITLE
Typo in Email Account Settings

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-www#1173]
The text "Send me Scratch Updates & Newsletters:" shouldn't have a colon after it, since the checkbox is on the left:

![Typo](https://cloud.githubusercontent.com/assets/9948030/22668952/fd24feb2-ec98-11e6-92ae-45685f25233c.png)

You can find that option on [this page](https://scratch.mit.edu/accounts/email_change/). It looks like the issue's there regardless of language..

**Comment by jwzimmer** [comment]
Hi @liam4, thank you for logging this issue, but since we are already tracking this bug in another (private) repository, I'm going to close this one. We appreciate your help finding issues! : )
