### ISSUE TITLE
Change (update) shortcut URL for story and fashion tutorials

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#1177]
We are adding the new tutorials, so would like the URL shortcuts to the tutorials updated:

scratch.mit.edu/story --> https://scratch.mit.edu/projects/editor/?tip_bar=story
scratch.mit.edu/fashion --> https://scratch.mit.edu/projects/editor/?tip_bar=fashion
scratch.mit.edu/dressup --> https://scratch.mit.edu/projects/editor/?tip_bar=fashion

**Comment by TheGrits** [comment]
@thisandagain I'll try tackling this one!

**Comment by thisandagain** [comment]
Great! Thanks @TheGrits !

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4530
