### ISSUE TITLE
Say "one day" instead of "24 hours" when talking about teacher registration wait period?

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#1178]
A translator in Transifex brought up that it would be easier for them to localize "one day" than "24 hours" when referring to the translation for:
* https://github.com/LLK/scratch-www/blob/9255185716b34e4c9d721322ad08437ed3fa4415/src/l10n.json#L134
* https://github.com/LLK/scratch-www/blob/9e1c985ae5e753aad1c7ca4c3536c7642a5d0aa8/src/views/teachers/faq/l10n.json#L7. 

What do folks think of the difference here?

**Comment by thisandagain** [comment]
That certainly makes sense to me. 👍

**Comment by TheGrits** [comment]
@thisandagain 😀 I like it when the `help wanted` tag shows up. I'll try to tackle this one right now.

**Comment by kaschm** [comment]
fine with me too 👍
