### ISSUE TITLE
Scratch Conference - Browser tab should say "Scratch Conferences" rather than "Scratch - Imagine, Program, Share"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1188]
Minor, non-blocking issue for https://github.com/LLK/scratch-www/pull/1184.

The `/2015` conference page tab says "Scratch Conference", but 2016 and 2017 (the current page) both say "Scratch - Imagine, Program, Share". Ideally, the tab would say "Scratch Conferences" to match the header.
<img width="575" alt="screen shot 2017-02-16 at 4 00 08 pm" src="https://cloud.githubusercontent.com/assets/1320456/23040893/07bb51f8-f461-11e6-9931-b4cbb84be26c.png">

**Comment by LiFaytheGoblin** [comment]
@jwzimmer 

One question: It seems like the conference websites all have different titles:
2014: Scratch@MIT | Scratch Conference 2014
2015: Scratch Conference
2016 & 2017: Scratch - Scratch Conference (after the sheme applied everywhere else (like Scratch - About, Scratch - Educators, etc). (https://github.com/LLK/scratch-www/pull/1340)

Should this be changed so all pages have the same type of title? Or is it enough if just 2016 and 2017 say something that at least has to do with Scratch Conference?

**Comment by jwzimmer** [comment]
@LiFaytheGoblin I think the only title that needs to be changed is 2017 - I think it should say "Scratch Conferences" iirc. (Scratch - Scratch Conferences may be ok, too - I'm not sure.) /cc @carljbowman
