### ISSUE TITLE
Search bar not working - Staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1189]
**TL;DR:** The API request is not getting the search query term.

Found while smoke-testing (https://github.com/LLK/scratchr2/issues/4457).

**Repro:**
- Go to staging
- Search for "duck"
- Search for "duck cat"
- Note the results are the same for either query, and don't seem relevant

**Comment by thisandagain** [comment]
I think this is a blocker. The XHR request that is being sent for a search term "foo bar" is (note the lack of `q` query string parameter):
https://api-staging.scratch.mit.edu/search/projects?limit=16&offset=0&language=en&mode=popular

**Comment by rschamp** [comment]
Fixed in #1193
