### ISSUE TITLE
Teacher registration gender options not accessible from keyboard

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#1195]
A user should be able to use tab to focus each of the gender radio buttons and select them from their keyboard. Currently these radio buttons are skipped while tabbing.

**Comment by Petroochio** [comment]
It appears that those inputs aren't skipped, it is just that they aren't showing any style when focused. I can take a crack at this real quick.

**Comment by Petroochio** [comment]
@rschamp @thisandagain is this an issue across all radio buttons that should be fixed globally, or is it only an issue in the teacher registration?

**Comment by thisandagain** [comment]
@Petroochio This particular issue is specific to the Teacher Registration flow.
