### ISSUE TITLE
Teacher registration Organization step "Other" option overlaps missing message string

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#1196]
I believe there should be no label at all on the last option for Organization type, but instead there's a string being overlapped by a text field. (Chrome 56 macOS 10.12.3)

![image](https://cloud.githubusercontent.com/assets/1512021/23171391/59fd32b6-f820-11e6-9b04-f3d3cb1f790e.png)

**Comment by mewtaylor** [comment]
This doesn't appear to be a new issue – do we still think it's blocking for release? If so, happy to keep the milestone the same. If not, maybe we should move it to March?

**Comment by rschamp** [comment]
I don't think this should be a blocker necessarily, but I don't see this on production, do you? Which language do you have it set to?
