### ISSUE TITLE
Credits page > Supporting Organizations > credits.supportersServicesHeader needs to be translatable

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1201]
The `/info/credits/` page has a header that needs to be a translatable string: "credits.supportersServicesHeader". (Any language.)

<img width="778" alt="screen shot 2017-02-22 at 10 44 58 am" src="https://cloud.githubusercontent.com/assets/1320456/23219200/74016854-f8ec-11e6-8a92-f0479ab3799c.png">

**Comment by TheGrits** [comment]
@jwzimmer This is another one you can blame on me, another typo. Making a patch right now.
