### ISSUE TITLE
Developers page > Learning Principles > developers.ProjectsTitle missing string

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1202]
The `/developers` page has a title that needs to be a translatable string: "developers.ProjectsTitle ". (Any language.)

<img width="677" alt="screen shot 2017-02-22 at 10 49 55 am" src="https://cloud.githubusercontent.com/assets/1320456/23219290/afdc3386-f8ec-11e6-9834-68db19366edf.png">

**Comment by TheGrits** [comment]
@jwzimmer Whoops, I know what's causing that, and it was a typo made by me. 

It's also on production FYI.
