### ISSUE TITLE
Mobile issues - Scratch Conference site

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1206]
The site looks pretty much the same across iPhone 6s/ Chrome, iPhone 6s Safari, and Android/ Chrome. These are the relatively minor issues I found.

1) In the mock-up, the Scratch | Conference element is centered in the navbar on mobile devices. On Staging, the element is left-aligned. Chrome, iPhone 6s version 10.2.1 and Chrome, Android version 6.0.1.

2) In the mock-up, the text for "Learn more..." is closer in size and line spacing to the paragraph above it then it is on Staging. Chrome, iPhone 6s version 10.2.1. 

![ae3c179c-824b-49fd-abd0-2a35d72cf15e](https://cloud.githubusercontent.com/assets/1320456/23229785/8dd4a4a8-f90f-11e6-8222-3b2df11ad2a3.PNG)

3) The text in the top paragraph also extends closer to the edge of the screen on Staging than in the Mock. (See pic from (2)) Chrome, iPhone 6s version 10.2.1. 

4) The text & icons/ headers for the individual events are left-aligned on Staging but not in the mock. Chrome, iPhone 6s version 10.2.1. 

![4e86d5d5-c61a-4e65-88ba-92365a5be6f5](https://cloud.githubusercontent.com/assets/1320456/23229891/f258adde-f90f-11e6-802e-15ae5d503ed7.PNG)

5) The lines of text are not aligned with the icons. Chrome, iPhone 6s version 10.2.1. 

![355306c0-9892-4e80-9943-f93f9818c527](https://cloud.githubusercontent.com/assets/1320456/23229904/03e598c8-f910-11e6-9b35-bfabb4fa5cba.PNG)

6) Should "Contact Organizer" be across two lines, or one? Chrome, iPhone 6s version 10.2.1. 

![2b8d43c3-c0b9-4d7b-9630-6362c0388e3b](https://cloud.githubusercontent.com/assets/1320456/23229936/1a40ba62-f910-11e6-851d-229d4abe0cfb.PNG)

**Comment by mewtaylor** [comment]
Issues 1-4 are a consequence of existing styling for the nav bar from previously, or from existing typography declarations for the conference site. @lifeinchords any preference between maintaining existing type/nav settings versus changing for 2017?

**Comment by lifeinchords** [comment]
I think 1-4 are ok to leave as is. One thing on these, for #1, maybe a bit of margin or padding to push the logo away for the screen edge. 

5 + 6 are minor
5 probably a bit better to do, 6 feels more nice to have. 
I'll give fixing them up a shot.

**Comment by mewtaylor** [comment]
@lifeinchords I have a solve for 5, which adds a negative margin to the top of the image. We could do that – the other option would be, I think to export a version of the svg that doesn't have transparent space around it. Thoughts?

**Comment by lifeinchords** [comment]
hey @mewtaylor, whichever is easiest. I just sent updated icons offline

**Comment by mewtaylor** [comment]
5 on the list is fixed in https://github.com/LLK/scratch-www/issues/1216, as is 6. And 1-4 are being kept. Should we close @jwzimmer @lifeinchords ?

**Comment by lifeinchords** [comment]
Sounds good to me
