### ISSUE TITLE
Tablet issues - Scratch Conference site - extra spacing in footer

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1207]
1) I don't know if the Scratch | Conferences element in the navbar is supposed to be centered or left-aligned? (@lifeinchords)
Currently on Staging it is left-aligned.

2) The footer has odd spacing, two blank lines above Scratch Day (iPad version 9.3.5, Safari).

![bc9b4b9d-fe31-463f-88d5-25e8e6234c05](https://cloud.githubusercontent.com/assets/1320456/23230453/0530291c-f912-11e6-99cd-fd9afb38ed60.JPG)

**Comment by lifeinchords** [comment]
1. I think @mewtaylor and I agreed to leave header as is
2. This one's a bit weird, @mewtaylor any idea what's causing this?

**Comment by mewtaylor** [comment]
@lifeinchords 2 is because the footer items are using flex row to be in columns, and the third column is overflowing. This is likely due to a mismatch between the tablet's width and our tablet breakpoint.
