### ISSUE TITLE
Way too much space between event descriptions, icons - Edge, Win 10 VM - Scratch Conference site

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1209]
There is a lot of extra space in between all the attributes of the event descriptions (location, language, etc.) and the icons, causing the events to be very long and full of white space. Edge, Win 10 VM on QA Machine, Staging, Scratch Conference site.

![b6d5c534-980c-44ae-84fa-4585d2982028](https://cloud.githubusercontent.com/assets/1320456/23231280/3aa77e6c-f915-11e6-89e7-e45eeec99eb1.JPG)
![f4257f37-5142-403c-8cb9-a6986ffda5f9](https://cloud.githubusercontent.com/assets/1320456/23231282/3aae11dc-f915-11e6-93bc-6a20e6f94f26.JPG)

**Comment by mewtaylor** [comment]
Unable to repro in sauce on Windows 10, Edge 14 – is it possible this is caching some styling for the old index page causing the issue? I.e. does it continue if you hard refresh @jwzimmer ?

**Comment by lifeinchords** [comment]
I just tried on a virtual machine: Windows 10, Edge 38, and it renders ok across breakpoints.

**Comment by jwzimmer** [comment]
Clearing the cache got rid of the extra space! So it was just an old version of the site. Thanks @mewtaylor.
