### ISSUE TITLE
Large bold font - Edge, Chrome on Windows - Scratch Conference site

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1210]
The large title font we use looks very large & bold in Edge & Chrome (on Windows, not on Mac). I don't know if we can avoid this?

I think we have discussed this before, but I could not find the case, so to be on the safe side, I filed this one.

Mock:
<img width="671" alt="screen shot 2017-02-22 at 3 45 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/23231479/fcf21784-f915-11e6-89cc-e2dc26684fad.png">

Staging, Edge, Win 10 VM:
![c61375d6-3fe6-44b1-a715-733c64199999](https://cloud.githubusercontent.com/assets/1320456/23231459/e422940e-f915-11e6-9e99-756634512467.JPG)

Staging, IE 11, Win 7 VM:
<img width="1021" alt="screen shot 2017-02-22 at 3 47 12 pm" src="https://cloud.githubusercontent.com/assets/1320456/23231543/3d599694-f916-11e6-8044-472aed196af8.png">

Staging, Chrome, Win 7 VM:
<img width="989" alt="screen shot 2017-02-22 at 4 55 07 pm" src="https://cloud.githubusercontent.com/assets/1320456/23234380/eb609504-f91f-11e6-8d8d-f541b1de4e06.png">

**Comment by thisandagain** [comment]
🐴

**Comment by lifeinchords** [comment]
I tested changing to `font-weight: bold` on the Edge 38 VM I'm testing on, vs the number values, like `300`  and the text looks much better. 
<img width="1221" alt="screen shot 2017-02-22 at 5 10 40 pm" src="https://cloud.githubusercontent.com/assets/716168/23234986/e01788e0-f921-11e6-8c6a-937bad82eb21.png">

Not sure why this is, I think it's either related to missing typeface variations, or how the browser applies/renders bold differs. 

Any ideas @mewtaylor why this is happening? 

Would switching the `font-weight` to `bold` for this release be possible? it would be a nice test, and maybe we'll make the change across `www` later. 

If it'll negatively impact `www` or involve refactoring a bunch of other places, I'd say let's skip it for now.
