### ISSUE TITLE
Title for Scratch Conferences site should be smaller

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1211]
The font size on Staging for the Conferences title looks larger in practice than it did in the mock. It doesn't seem to matter much which browser/ OS you're looking at (although Edge has a uniquely bold font, https://github.com/LLK/scratch-www/issues/1210). @carljbowman & @lifeinchords have a plan for fixing this and #1210.

Chrome 56, Mac OS El Capitan
<img width="955" alt="screen shot 2017-02-22 at 4 00 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/23232078/00f674ae-f918-11e6-9abd-84287c85b606.png">

**Comment by lifeinchords** [comment]
@mewtaylor and I worked out the sizing together at one point, which is why it's a bit different than the static designs. Looking at this again, I'm wondering if we can bump the `h1` down to 4rem. I know it's not ideal in terms of reusability, but maybe we can make an exception here?

**Comment by mewtaylor** [comment]
@lifeinchords it's a question of moving forward – do we want to update this for all conference type, or just for 2017?

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/issues/1216
