### ISSUE TITLE
Title of Shanghai Scratch Conference not correct - Scratch Conference Site

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1213]
The title for the Conference taking place in Shanghai should be "Scratch Conference: China*Love" (all on one line).

Staging, Chrome, Mac OS El Capitan
<img width="893" alt="screen shot 2017-02-22 at 4 59 29 pm" src="https://cloud.githubusercontent.com/assets/1320456/23234542/65e1bc2c-f920-11e6-8d0c-b82e732faa69.png">

**Comment by mewtaylor** [comment]
This is changed in the code... so I'm not clear exactly why it isn't on staging. seems to me the intl.js file is not updated correctly? @chrisgarrity any ideas?

**Comment by mewtaylor** [comment]
This is fixed – the string needed to be updated in Transifex inorder to show up correctly. Good to know for the future @chrisgarrity – I actually kind of like that we need to do that.

**Comment by jwzimmer** [comment]
Just confirming what @mewtaylor already said, the title is fixed on Staging now 👍 :

<img width="845" alt="screen shot 2017-02-23 at 9 10 22 am" src="https://cloud.githubusercontent.com/assets/1320456/23262204/ee6f6c1a-f9a7-11e6-91bc-10ab080cb69d.png">
