### ISSUE TITLE
Add "Community Moderator" to jobs page

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1218]
We're hiring a new moderator - and would like to revive the Scratch "Community Moderator" job description as soon as possible. 

### To Do
- [ ] Create new page with job description (`/jobs/moderator`)
- [ ] Update `/jobs` page with new link
- [ ] Remove "Senior Back-end Engineer" from `/jobs` page

### Reference
https://gist.github.com/thisandagain/f30219508c049e7666cdd89fbc1fdd87

---
Moved from LLK/scratchr2#4508
/cc @SpeakkVisually

**Comment by TheGrits** [comment]
@thisandagain 😁 I'll take a swing at this one.

**Comment by thisandagain** [comment]
@TheGrits That would be great! Just let me know if you have any questions. 😄

**Comment by TheGrits** [comment]
@thisandagain The positions currently on the jobs page do not have pages like you requested for the moderator page. Would you like pages made for them as well? (Senior Back-End Engineer and Trust & Safety Manager)

**Comment by TheGrits** [comment]
@thisandagain Also, should anything on the moderator page be localized? (I'm assuming not)

**Comment by thisandagain** [comment]
> The positions currently on the jobs page do not have pages like you requested for the moderator page. Would you like pages made for them as well? (Senior Back-End Engineer and Trust & Safety Manager)

No. We use the MIT Media Lab's job pages for those positions.

> should anything on the moderator page be localized? (I'm assuming not)

No. Job descriptions should not be localized.

**Comment by TheGrits** [comment]
@thisandagain Thanks, I should have a PR ready within an hour or so.

**Comment by thisandagain** [comment]
@TheGrits Amazing! One other thing I just noticed is we can remove the "Senior Back-end Engineer" position.

**Comment by TheGrits** [comment]
@thisandagain Yep, no problem.

**Comment by TheGrits** [comment]
@thisandagain About the Twitter links, are they supposed to be Tweet buttons or just links?

**Comment by thisandagain** [comment]
@TheGrits I think we can drop the sharing links. Thanks for checking though!
