### ISSUE TITLE
Special characters not properly decoded by search

### ISSUE THREAD

**Issue by WorldLanguages** [LLK/scratch-www#1224]
To reproduce:

Search anything starting with "/".

Instead of getting the search results, the most popular projects are shown.

**Comment by thisandagain** [comment]
I believe that this will be resolved when #1193 is deployed (expected later today).

**Comment by WorldLanguages** [comment]
Solved. Now there are no results, but I guess that it's hard to find titles starting with a symbol.

**Comment by rschamp** [comment]
It looks like this is still a problem, but maybe slightly different now that we are doing URI encoding/decoding. Somewhere along the line `/` characters in the search string are transformed to `%2f` which isn't being decoded properly by `decodeURIComponent`.

**Comment by jwzimmer** [comment]
On Staging & Production, other chars are also not being properly decoded:
<img width="1109" alt="screen shot 2017-04-13 at 7 26 13 pm" src="https://cloud.githubusercontent.com/assets/1320456/25028106/040e96be-2080-11e7-923f-e6ef2b3ccf3b.png">
