### ISSUE TITLE
English -> Sardu: Homepage not displaying translated strings

### ISSUE THREAD

**Issue by lifeinchords** [LLK/scratch-www#1230]
Started on home. Switched to Sardu via dropdown. Got:

![img_0051](https://cloud.githubusercontent.com/assets/716168/23315678/3fe4c426-fa95-11e6-9886-b8a89410bd55.JPG)

Selecting a project from carousel took me to Project page, which seems to display the translated strings in footer?

![img_0052](https://cloud.githubusercontent.com/assets/716168/23315787/b72afa5a-fa95-11e6-8a32-a6471cccb462.JPG)

iPhone 5
iOS 10.2

/cc @chrisgarrity

**Comment by chrisgarrity** [comment]
thanks @lifeinchords. @mewtaylor sc.json files are in scratchr2_translations. Maybe there's an error that prevents the splash intl file from getting built? especially as the menu/footer are ok on other pages.

**Comment by mewtaylor** [comment]
@chrisgarrity I think this is a pre-existing issue, and a consequence of sardu not being in the intl-messageformat package for `react-intl`. I'll try and add it to custom locales

**Comment by chrisgarrity** [comment]
fixed in https://github.com/LLK/scratch-www/pull/1236
