### ISSUE TITLE
failed to run "npm run build" , please help 

### ISSUE THREAD

**Issue by vvjin** [LLK/scratch-www#1231]
const { existsSync: exists } = fs;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\xxx\\nodejs2\\node.exe" "D:\\xxx\\nodejs2\\node_modules\\npm\\bin\\npm-cli.js" "run
" "build"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! www@1.0.0 build: `make build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the www@1.0.0 build script 'make build'.
npm ERR! This is most likely a problem with the www package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get their info via:
npm ERR!     npm owner ls www
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\scratch\scratch-www\npm-debug.log

**Comment by mewtaylor** [comment]
@vvjin Do you mind posting what version of Node you're using too? Thanks!

**Comment by vvjin** [comment]
E:\Users\vjin>node -v
v6.9.4
sorry for late reply, I was trying to figure out the problem.

**Comment by mewtaylor** [comment]
@vvjin thanks! I'm wondering if this is related to https://github.com/nodejs/node/issues/7294 at all? It looks like it should've been fixed for `v6.4` though...

I wonder if downgrading to LTS v4.x might be worth trying to see if that works, perhaps. Also, did you find anything else in your investigation by any chance?

**Comment by rschamp** [comment]
Closing because of age. @vvjin Please reopen if you need more help!
