### ISSUE TITLE
Make footer flexbox be `space-between` rather than `space-around`?

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#1232]
Just noticed this while looking at an `InformationPage` locally. Currently, we use `justify-content: space-around` for displaying the footer link lists. Since this centers the columns, we end up with this:
<img width="984" alt="screen shot 2017-02-28 at 8 57 52 am" src="https://cloud.githubusercontent.com/assets/1815772/23408070/bc996fba-fd94-11e6-801c-70d212e56ca5.png">

If we were to move to using `space-between` (filling the width its given, rather than centering within the space its given), we'd get something like this:
<img width="1031" alt="screen shot 2017-02-28 at 8 58 11 am" src="https://cloud.githubusercontent.com/assets/1815772/23408110/d534beee-fd94-11e6-862a-d6065961b62a.png">

/cc @carljbowman @lifeinchords

**Comment by lifeinchords** [comment]
I dig it! The left column in the footer lines up nicely with the content above it.
