### ISSUE TITLE
Update credits page

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1242]
- [ ] Scratch Team
    - [ ] Resort list to be alphabetical by last name
    - [ ] Add "Eric Rosenbaum" (`ericr`)
    - [ ] Add "Paul Kaplan" (`sgcc_`)
    - [ ] Move "Sayamindu Dasgupta" to "Previous Members" section
    - [ ] Move "Ricarose Roque" to "Previous Members" section
    - [ ] Move "Tim Mickel" to "Previous Members" section
    - [ ] Move "Connor Hudson" to "Scratch Moderators" section
    - [ ] Move "Hanako Tjia" to "Scratch Moderators" section
- [ ] Scratch Moderators
    - [ ] Resort list to be alphabetical by last name
- [ ] Previous Members
    - [ ] Resort list to be alphabetical by last name except for "John Maloney" and "Andrés Monroy-Hernández" who should still be listed first and second respectively

**Comment by TheGrits** [comment]
w00t! I'll tackle this one!
