### ISSUE TITLE
Add link to No Starch Scratch Coding Cards on Cards page

### ISSUE THREAD

**Issue by seotts** [LLK/scratch-www#1251]
Add language to the Cards page to link to the No Starch Scratch Coding Cards.

@ntlrsk, could you draft the text for that? Thanks!

**Comment by thisandagain** [comment]
@seotts @ntlrsk Please feel free to put this in whatever milestone you would like it to go out in. Putting in `backlog` for now.

**Comment by rschamp** [comment]
Tracking as a part of #1261
