### ISSUE TITLE
Migrate - Download Scratch 2 Offline Editor

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1254]
https://scratch.mit.edu/scratch2download/

- [x] Migrate to template used for /educators (or alternately /developers)
- [x] Make sure all parts of the page are translatable
- [ ] ~delete old template in scratchr2~

**Comment by TheGrits** [comment]
@chrisgarrity I know how to make a new page with the template and make the page translatable, but I can't delete the old template.

**Comment by chrisgarrity** [comment]
@TheGrits That would be great - the last item is mostly to make sure we don't forget to do the scratchr2 cleanup when we merge.

**Comment by mewtaylor** [comment]
@chrisgarrity marked the first two as done with #1258.

**Comment by chrisgarrity** [comment]
I'm going to close this as the page has been moved, and we can track removing the old template in the original issue: https://github.com/LLK/scratchr2/issues/4119
