### ISSUE TITLE
"Tips" Page

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1261]
### Update "Things to Try" Page
- [x] Change path to `/tips`
- [x] Redirect `/go` to `/tips`
- [x] Add section above tips content that links to the [Getting Starting](http://vimeo.com/llk/start-scratch) video
- [x] Add section below tips content that links to both download and purchase the [Scratch Coding Cards](https://www.amazon.com/Scratch-Coding-Cards-Creative-Activities/dp/1593277741)
- [x] Add section below tips content that links to the [Offline Editor](https://scratch.mit.edu/scratch2download/)
- [x] Add section below tips content that links to the [Help With Scripts](https://scratch.mit.edu/discuss/7/) forum topic

### Retire "Help" Page
- [ ] Retire current "help" template
- [x] Redirect `/help` to `/tips`

### Update Navigation
- See #1262

/cc @ntlrsk @carljbowman @rschamp @SpeakkVisually @christanbalch

**Comment by carljbowman** [comment]
cc/ @ntlrsk 

# Designs 
## 12 Column
**[Image with no grid](https://cloud.githubusercontent.com/assets/3409578/26125518/664a8614-3a50-11e7-943c-fd423028c3bd.png)**

<img  src="https://cloud.githubusercontent.com/assets/3409578/26124673/4f6ec6ba-3a4d-11e7-8dc8-fbbedaccf2dd.png" width="1280" />

## 8 Column
**[Image with no grid](https://cloud.githubusercontent.com/assets/3409578/26125544/80f1883c-3a50-11e7-83e9-38df1a6bc3e1.png)**

<img  src="https://cloud.githubusercontent.com/assets/3409578/26124679/54b1dab8-3a4d-11e7-8664-81229837e29f.png" width="768" />

## 6 Column
**[Image with no grid](https://cloud.githubusercontent.com/assets/3409578/26125565/95389c40-3a50-11e7-97fb-371aa69ea847.png)**

<img  src="https://cloud.githubusercontent.com/assets/3409578/26124686/5ca3ba02-3a4d-11e7-87d0-ee6c500f854c.png" width="560" />

## 4 Column
**[Image with no grid](https://cloud.githubusercontent.com/assets/3409578/26125579/a1f8fb3c-3a50-11e7-887e-6d36862cc321.png)**

<img  src="https://cloud.githubusercontent.com/assets/3409578/26124690/5e8f49e4-3a4d-11e7-9b94-83232f91f725.png" width="360" />

# Content 
## Assets
**[tips-assets.zip](https://github.com/LLK/scratch-www/files/1005758/tips-assets.zip)**

## Masthead Section
**Title** 
Getting Started

**Body**
Start making projects in Scratch by trying the [online tutorial]
(https://scratch.mit.edu/projects/editor/?tip_bar=getStarted) or downloading the [PDF guide](https://scratch.mit.edu/scratchr2/static/pdfs/help/Getting-Started-Guide-Scratch2.pdf).  

**Button**
[Try the Getting Started tutorial](https://scratch.mit.edu/projects/editor/?tip_bar=getStarted)

## Things to Try Section
**Title** 
Things to Try

**Body**
What do you want to make with Scratch? For each activity, you can try the Tutorial, download a set of Activity Cards, or view the Educator Guide.

### Activity Cards Section
**Title**
Get the Entire Collection of Activity Cards

**Body**
With the Scratch Activity Cards, you can learn to create interactive games, stories, music, animations, and more!

**Botton 1**
[Download PDF](https://scratch.mit.edu/scratchr2/static/pdfs/help/ScratchCardsAll.pdf)

**Botton 2**
[Purchase Printed Set](https://www.amazon.com/Scratch-Coding-Cards-Creative-Activities/dp/1593277741/ref=sr_1_1?ie=UTF8&qid=1494450316&sr=8-1&keywords=scratch+cards)

## Starter Projects Section
**Title**
Starter Projects

**Body**
You can play with Starter Projects to get ideas for making your own projects. 

**Button**
[Play with Starter Projects](https://scratch.mit.edu/starter_projects/)

## Offline Editor Section
**Title**
Offline Editor

**Copy**
To create projects without an Internet connection, you can [download the offline editor](https://scratch.mit.edu/scratch2download/). 

## Questions Section
**Title**
Questions

**Copy**
Have more questions? See the [Frequently Asked Questions](https://scratch.mit.edu/info/faq/) or visit the [Help with Scripts Forum](https://scratch.mit.edu/discuss/7/).

**Comment by carljbowman** [comment]
@thisandagain - Assigning you to reassign

**Comment by ntlrsk** [comment]
@carljbowman or @ascii Should I make a separate issue about (1) making the entire collection of card PDFs to point to and (2) updating the Educator page to say "Tips" rather than "Things to Try"?

**Comment by ntlrsk** [comment]
I remember now I already created an issue for that: https://github.com/LLK/scratch-www/issues/1308

**Comment by carljbowman** [comment]
@TheGrits - Would this be something you would be interested in implementing?

**Comment by St19Galla** [comment]
@TheGrits if you are too busy I can also help :)

**Comment by TheGrits** [comment]
@carljbowman I'd love to, this sounds like a great project!

@St19Galla Thanks for the offer, but I think I can take this one. 👍

**Comment by chrisgarrity** [comment]
@TheGrits I worked on the original /go page, so feel free to @ ping me with questions.

**Comment by TheGrits** [comment]
@chrisgarrity Thanks, will do if any questions do arise!

**Comment by chrisgarrity** [comment]
@TheGrits this would be good to get into the June release (freeze for testing on June 21). If you're going to have time to do it that's great. But if you're busy and won't have time, just let us know.

**Comment by TheGrits** [comment]
@chrisgarrity I won't be able to get it done for June 21, sorry. (I currently have an internship and was going to do this over the course of the next couple weekends.) Sorry about that!

**Comment by chrisgarrity** [comment]
@TheGrits No worries, usually things with help-wanted aren't on a time schedule, but then we decided this one would be good to get done soon, so it's on us. We appreciate all your help!

**Comment by chrisgarrity** [comment]
Not closing this one yet because it needs the navigation update in scratchr2

**Comment by chrisgarrity** [comment]
Tracking the last item in https://github.com/LLK/scratchr2/issues/4695

Closing this one.
