### ISSUE TITLE
Community Moderator Page 404ing

### ISSUE THREAD

**Issue by TheGrits** [LLK/scratch-www#1265]
The link to https://scratch.mit.edu/jobs/moderator from https://scratch.mit.edu/jobs is 404ing currently. No obvious problems with the routing...

**Comment by TheGrits** [comment]
Routing reference: https://github.com/LLK/scratch-www/blob/develop/src/routes.json#L183-L189

**Comment by mewtaylor** [comment]
@TheGrits nice catch, thanks so much for that! I'm looking into it now

**Comment by TheGrits** [comment]
@mewtaylor 👍 Quickly QA'ed the rest of the changes, doesn't look like there are any more obvious issues.

**Comment by mewtaylor** [comment]
Awesome, thanks so much @TheGrits for looking into that! @jwzimmer and I really appreciate it :).

**Comment by TheGrits** [comment]
@mewtaylor I've done some more thorough digging around with the .jsx file itself, the issue is still not presenting itself. Perhaps there is a problem with the page host?
