### ISSUE TITLE
Cloud data notice in editor links to /help/faq instead of /info/faq

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-www#1281]
(This might already be tracked somewhere..)

When you create a new cloud variable for the first time in a project using the Scratch 2.0 editor, a notice appears:

![Cloud data notice screenshot](https://cloud.githubusercontent.com/assets/9948030/25304589/b604fd10-2740-11e7-8c67-335e9874096b.png)

However, the "cloud data FAQ" link is broken; it links to https://scratch.mit.edu/help/faq/#clouddata, but it should link to https://scratch.mit.edu/info/faq/#clouddata.

It might also be a good idea to have a redirect from /help/* to /info/*, so that any other old links to the FAQ won't be broken.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-flash/issues/1281
