### ISSUE TITLE
Capitalization of strings

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1283]
Strings should probably be capitalized (reported by translators):
* 'you have been invited to join the class:' - registration.classroomInviteExistingStudentStepDescription
* 'select country' - registration.selectCountry

Most other strings in the general l10n.json are capitalized.

**Comment by rschamp** [comment]
These are probably expected, @chrisgarrity please confirm.

**Comment by chrisgarrity** [comment]
Confirmed that these are expected to be lowercase, will add notes to the strings in Transifex.
