### ISSUE TITLE
Profile Dropdown isn't Mobile Friendly

### ISSUE THREAD

**Issue by TheGrits** [LLK/scratch-www#1292]
![scratch mit edu- iphone 6 plus](https://cloud.githubusercontent.com/assets/12952370/25466225/0fe9f47e-2ad5-11e7-8e31-13bd8ec675bc.png)

Of course I forgot to test the dropdown on mobile. Sorry!

I'll try to figure out a patch ASAP

Related PR: #1270

**Comment by mewtaylor** [comment]
No apology necessary @TheGrits ! I missed it too – thanks for the quick PR to address the issue though :)
