### ISSUE TITLE
Use non-localized URL for Firefox

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1294]
Suggestion from translators:

in faq.requirementsBody, replace the Firefox link: `http://www.mozilla.org/en-US/firefox/new/` with a generic one `http://www.mozilla.org/firefox/new/` so the browser will pick the version based on the browser's locale.

Currently translators have to override the en-US link which is potentially error-prone, and creates warnings in transifex that the URL doesn't match.

**Comment by thisandagain** [comment]
Good catch! Thanks @chrisgarrity

**Comment by TheGrits** [comment]
I'll take this one!

**Comment by TheGrits** [comment]
@chrisgarrity In the same localization string there are links with similar en-us parts in the link. Should these be removed as well? (See Edge and Internet Explorer links for examples)

**Comment by chrisgarrity** [comment]
@TheGrits Good catch! Yes, they should be taken out of the Microsoft links as well. If you could double check that the links without the locale redirect you that would be great.
