### ISSUE TITLE
Some translations broken in "meow"

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1303]
### Repro
- Navigate to splash page
- Change language to "meow"

### Reference
![image](https://cloud.githubusercontent.com/assets/747641/25660574/e11074b0-2fda-11e7-8693-36c5e5f1b37c.png)

@mewtaylor @chrisgarrity @rschamp Any thoughts?

**Comment by jwzimmer** [comment]
They are also broken in Edible Scratch.

<img width="553" alt="screen shot 2017-05-03 at 9 45 56 am" src="https://cloud.githubusercontent.com/assets/1320456/25663329/5bfa5718-2fe5-11e7-87e9-80637a6dec7b.png">
