### ISSUE TITLE
What's Happening not Localizing

### ISSUE THREAD

**Issue by TheGrits** [LLK/scratch-www#1304]
French:
![scratch mit edu-french](https://cloud.githubusercontent.com/assets/12952370/25663036/9d9a90ee-2fe4-11e7-932a-3c735953940e.png)
Spanish:
![scratch mit edu-spanish](https://cloud.githubusercontent.com/assets/12952370/25663070/b7a98058-2fe4-11e7-9249-f9185366501b.png)

Looks like the phrases such as "shared the project" and "became a curator of" aren't being localized.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-api#249
