### ISSUE TITLE
Make translated cards for each language into a single PDF

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#1308]
The revised "Things to Try" page will have a link to download all the cards as a single PDF. This means we need to make the existing translated cards into a single PDF (one PDF for each language).  

This should not include the old cards (i.e., the "Starter Cards"). However, the old cards should still stay on the server for now (because we aren't getting rid of the Cards page yet).

**Comment by chrisgarrity** [comment]
Fixed with https://github.com/LLK/scratch-resources/pull/5
