### ISSUE TITLE
Local version of scratch-www won't run

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#1315]
Hi!

I'm trying to follow the instructions in the readme to get scratch-www running on my local computer, but unfortunately it won't work. 

My system:
Node Version: 4.2.0 (downgrading fixed other issues I had before)
Npm Version: 4.6.1
Python Version: 2.7.13 (again, downgrading fixed other issues I had before)
Windows 10
For make in windows I use the mingw32-make.

**Using the normal command line I get:**

```

C:\Users\Linda>cd C:\Repos\scratch-www

C:\Repos\scratch-www>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

C:\Repos\scratch-www>npm run build

> www@1.0.0 build C:\Repos\scratch-www
> make build

make[1]: Entering directory `C:/Repos/scratch-www'
rm -rf ./build
process_begin: CreateProcess((null), rm -rf ./build, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [clean] Error 2
make[1]: Leaving directory `C:/Repos/scratch-www'
make: *** [build] Error 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! www@1.0.0 build: `make build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the www@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Linda\AppData\Roaming\npm-cache\_logs\2017-05-18T16_43_04_837Z-debug.log

C:\Repos\scratch-www>
```
The error log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'build' ]
> 2 info using npm@4.6.1
> 3 info using node@v4.2.0
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle www@1.0.0~prebuild: www@1.0.0
> 6 silly lifecycle www@1.0.0~prebuild: no script for prebuild, continuing
> 7 info lifecycle www@1.0.0~build: www@1.0.0
> 8 verbose lifecycle www@1.0.0~build: unsafe-perm in lifecycle true
> 9 verbose lifecycle www@1.0.0~build: PATH: C:\Program_Files\nvm\v4.2.0\node_modules\npm\bin\node-gyp-bin;C:\Repos\scratch-www\node_modules\.bin;C:\Program Files (x86)\Python\Python27-13;C:\Program Files (x86)\Python\Python27-13\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\ProgramData\Miniconda3;C:\ProgramData\Miniconda3\Scripts;C:\ProgramData\Miniconda3\Library\bin;C:\Program_Files\mingw\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\Linda\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program_Files\mingw\bin;C:\Program_Files\nvm;C:\Program Files\nodejs
> 10 verbose lifecycle www@1.0.0~build: CWD: C:\Repos\scratch-www
> 11 silly lifecycle www@1.0.0~build: Args: [ '/d /s /c', 'make build' ]
> 12 silly lifecycle www@1.0.0~build: Returned: code: 2  signal: null
> 13 info lifecycle www@1.0.0~build: Failed to exec build script
> 14 verbose stack Error: www@1.0.0 build: `make build`
> 14 verbose stack Exit status 2
> 14 verbose stack     at EventEmitter.<anonymous> (C:\Program_Files\nvm\v4.2.0\node_modules\npm\lib\utils\lifecycle.js:279:16)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at EventEmitter.emit (events.js:172:7)
> 14 verbose stack     at ChildProcess.<anonymous> (C:\Program_Files\nvm\v4.2.0\node_modules\npm\lib\utils\spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at ChildProcess.emit (events.js:172:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:818:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid www@1.0.0
> 16 verbose cwd C:\Repos\scratch-www
> 17 verbose Windows_NT 10.0.14393
> 18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> 19 verbose node v4.2.0
> 20 verbose npm  v4.6.1
> 21 error code ELIFECYCLE
> 22 error errno 2
> 23 error www@1.0.0 build: `make build`
> 23 error Exit status 2
> 24 error Failed at the www@1.0.0 build script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 2, true ]

**Using cygwin I get:**
```
Linda@Ada ~
$ cd C:/Repos/scratch-www

Linda@Ada /cygdrive/c/Repos/scratch-www
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Linda@Ada /cygdrive/c/Repos/scratch-www
$ npm run build

> www@1.0.0 build C:\Repos\scratch-www
> make build

Access is denied.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! www@1.0.0 build: `make build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the www@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Linda\AppData\Roaming\npm-cache\_logs\2017-05-18T16_48_45_118Z-debug.log
```
The error log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'build' ]
> 2 info using npm@4.6.1
> 3 info using node@v4.2.0
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle www@1.0.0~prebuild: www@1.0.0
> 6 silly lifecycle www@1.0.0~prebuild: no script for prebuild, continuing
> 7 info lifecycle www@1.0.0~build: www@1.0.0
> 8 verbose lifecycle www@1.0.0~build: unsafe-perm in lifecycle true
> 9 verbose lifecycle www@1.0.0~build: PATH: C:\Program_Files\nvm\v4.2.0\node_modules\npm\bin\node-gyp-bin;C:\Repos\scratch-www\node_modules\.bin;C:\Program_Files\cygwin\usr\local\bin;C:\Program_Files\cygwin\bin;C:\Program Files (x86)\Python\Python27-13;C:\Program Files (x86)\Python\Python27-13\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\ProgramData\Miniconda3;C:\ProgramData\Miniconda3\Scripts;C:\ProgramData\Miniconda3\Library\bin;C:\Program_Files\mingw\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\Linda\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program_Files\mingw\bin;C:\Program_Files\nvm;C:\Program Files\nodejs
> 10 verbose lifecycle www@1.0.0~build: CWD: C:\Repos\scratch-www
> 11 silly lifecycle www@1.0.0~build: Args: [ '/d /s /c', 'make build' ]
> 12 silly lifecycle www@1.0.0~build: Returned: code: 1  signal: null
> 13 info lifecycle www@1.0.0~build: Failed to exec build script
> 14 verbose stack Error: www@1.0.0 build: `make build`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (C:\Program_Files\nvm\v4.2.0\node_modules\npm\lib\utils\lifecycle.js:279:16)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at EventEmitter.emit (events.js:172:7)
> 14 verbose stack     at ChildProcess.<anonymous> (C:\Program_Files\nvm\v4.2.0\node_modules\npm\lib\utils\spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at ChildProcess.emit (events.js:172:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:818:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid www@1.0.0
> 16 verbose cwd C:\Repos\scratch-www
> 17 verbose Windows_NT 10.0.14393
> 18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> 19 verbose node v4.2.0
> 20 verbose npm  v4.6.1
> 21 error code ELIFECYCLE
> 22 error errno 1
> 23 error www@1.0.0 build: `make build`
> 23 error Exit status 1
> 24 error Failed at the www@1.0.0 build script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 1, true ]

I am not sure if I am using cygwin correctly here. 
I'm logged in as an admin, so this should work I guess?
I hope someone can help me ...

@mewtaylor 
@cwillisf

**Comment by mewtaylor** [comment]
@LiFaytheGoblin handled this in https://github.com/LLK/scratch-www/pull/1329, thanks!
