### ISSUE TITLE
User menu too thin

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#1318]
At a full-width (greatest number of columns) page, the item "Account Settings" is split across multiple lines:

!["Profile \n My Stuff \n Account \n settings \n Sign out"](https://cloud.githubusercontent.com/assets/9948030/26285040/f7e7c5fc-3e1d-11e7-8868-118dbc84c77d.png)

Relatedly, at a min-width (least number of columns) page, the dropdown is too small to clearly present *any* of its items:

!["Profile \n My \n Stuff \n Accoun- \n setting- \n Sign \n out"](https://cloud.githubusercontent.com/assets/9948030/26285051/2684e174-3e1e-11e7-81e0-f4ea307f10f6.png)

Browser: Chrome Version 58.0.3029.110, macOS 10.12.4.

**Comment by TheGrits** [comment]
Fixed in #1293

**Comment by benjiwheeler** [comment]
This was not fixed in #1293 -- that change only affected screen sizes with tablet-or-less widths.

It is fixed by PR https://github.com/LLK/scratch-www/pull/2181

**Comment by thisandagain** [comment]
Resolved in LLK/scratch-www#2181

**Comment by towerofnix** [comment]
No big deal but that PR isn't merged yet. This should be (re-)opened and the PR should be changed to include "Resolves #1318".
