### ISSUE TITLE
Scratch Conference page: update Brazil dates

### ISSUE THREAD

**Issue by sleggss** [LLK/scratch-www#1322]
Change "September 28, 2017 - September 30, 2017" to "October 5, 2017 - October 7, 2017".

**Comment by TheGrits** [comment]
@mewtaylor I can make these changes quick if that'd help you!

**Comment by mewtaylor** [comment]
@TheGrits no worries I got it – thanks though :)

**Comment by leoburd** [comment]
Thanks for taking care of this!

When is the updated page going online?

.L

**Comment by mewtaylor** [comment]
@leoburd We will be doing a deploy next week, so this will go out then :).
