### ISSUE TITLE
[Page Titles] routes.json without effect on title (browser tab)

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#1337]
The routes.json (in src) appears to be supposed to set the title of a page like About or Conference. Unfortunately, it doesn't have any effect, the title will be "Scratch - Imagine, Program, Share" no matter what. 

This bug appears in:
- Windows + Firefox
- Windows + Chrome
- Ubuntu + Firefox

Here is what it looks like:
![routesjsonbug](https://cloud.githubusercontent.com/assets/5471273/26718534/9a33d7e4-4781-11e7-9674-16f564749241.PNG)

**Comment by LiFaytheGoblin** [comment]
@rschamp What does the has-patch label mean? I thought it means this issue can be solved with an existing pull request. But since I am assigned to this issue and I don't know about a fix, maybe I am wrong?

**Comment by rschamp** [comment]
@LiFaytheGoblin You're right, sorry about that. I misread the title of the PR that refers to this issue.

**Comment by mewtaylor** [comment]
Fixed in #1340
