### ISSUE TITLE
Changes to Credit Page

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#1343]
Proposed changes to the [credit page](https://scratch.mit.edu/info/credits/):
- remove Christina Huang from the moderators section of the credits page
- add Christina Huang to the "Previous MIT Scratch Team Members" list on the credits page

---
Moved from LLK/scratchr2#4671
/cc @christanbalch

**Comment by TheGrits** [comment]
@rschamp I'll cover this one.

**Comment by rschamp** [comment]
Thanks @TheGrits!

**Comment by TheGrits** [comment]
You can add `has-patch` to this one though! 😉
