### ISSUE TITLE
Scratch and Arduino

### ISSUE THREAD

**Issue by CarlosDopCol** [LLK/scratch-www#1349]
I do not know if this is where I ask this. Will there be a native connection to Arduino such as MBot?

This would greatly simplify and enhance students' ability to learn.

A greeting
Carlos

**Comment by TheGrits** [comment]
Hi Carlos!

I think this repository might be a better place to post this issue: https://github.com/LLK/scratch-flash/issues

Greetings from Canada!
- The_Grits

**Comment by thisandagain** [comment]
Hi @CarlosDopCol we are working on adding official support for Arduino to Scratch 3.0. In the meantime you can use our ScratchX extension here:
http://scratchx.org/
