### ISSUE TITLE
Migrate notifications page to www

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#1361]

**Comment by mewtaylor** [comment]
Concepts for the page from @carljbowman (thanksssssss :) )
![messages concept stuff](https://user-images.githubusercontent.com/1815772/28526035-3b50a648-7054-11e7-896e-57233ff1880b.png)
![messages concept stuff cols](https://user-images.githubusercontent.com/1815772/28526037-3d92d994-7054-11e7-958f-6d221082c419.png)
![messages concept mobile](https://user-images.githubusercontent.com/1815772/28526041-3fff3bc8-7054-11e7-8a09-eb8472cb6cf9.png)

**Comment by TheGrits** [comment]
WHOAAA NOW

**Comment by St19Galla** [comment]
This is crazy amazing!!!! :D

**Comment by St19Galla** [comment]
This is crazy amazing!!!! :D

One thing I would suggest is to change the name of the `Alerts` section. The term 'alert' in the Scratch Community generally has the negative connotation of the Moderator alerts, but judging by the looks of this, other things can classify as alerts as well. Perhaps it should be changed to 
`Messages from the Scratch Team` ?

**Comment by carljbowman** [comment]
@St19Galla - Ooo. That's a great idea. 'Alerts' does feel negative, we def should consider changing the language here.

**Comment by mewtaylor** [comment]
FWIW I do like `Messages from the Scratch Team`! @christanbalch @seotts @dietbacon looping y'all in for comment from the community perspective, thoughts?

**Comment by seotts** [comment]
@mewtaylor I like "Messages from the Scratch Team" a lot. In addition to sounding less harsh than "Alerts," it clarifies that it is coming from the ST instead of another Scratcher, which is a misinterpretation I often see.

**Comment by christanbalch** [comment]
Agreed with @seotts. I'll bring it up in Community Meeting today in case others have opinions as well and get back to you.

**Comment by dietbacon** [comment]
I like it too!  The only concern about it I have is how well a text string that long would work for mobile devices.

**Comment by carljbowman** [comment]
@dietbacon - We shouldn't be too concerned with the length of strings. We will come up with a design to fit the language that the team feels best describes these messages.

**Comment by christanbalch** [comment]
Got the 'all clear' from the other folks on the Community Team 👍

**Comment by thisandagain** [comment]
Thanks folks. After talking about this in the community meeting I think we agreed that the following changes would make sense:

- [ ] Change the language from "Alerts" to "Messages from the Scratch Team"
- [ ] Change the icon from the "yield" icon to something more friendly / playful

Other than that I think we are all excited about these new design changes! 😄

**Comment by mewtaylor** [comment]
This is completed in #1487
