### ISSUE TITLE
Replace "Help Page" in footer with "Tips Page"

### ISSUE THREAD

**Issue by SpeakkVisually** [LLK/scratch-www#1364]
We should replace the "Help Page" with "Tips Page" link 

![image](https://user-images.githubusercontent.com/5166432/27456021-6bdf02dc-576d-11e7-886b-ec466a9f4065.png)

**Comment by TheGrits** [comment]
@mewtaylor This issue should be closed, right? (Just checking in case Github missed the "fixes" keyword in the PR)

**Comment by mewtaylor** [comment]
@TheGrits yerp! Thanks!
