### ISSUE TITLE
Microworld preview image missing/404 in Safari

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#1372]
OS: macOS Sierra 10.12.5
Browser: Safari Version 10.1.1 (12603.2.4)

The preview image under "Get Inspired" fails to load:

![screen shot 2017-06-27 at 10 45 13 am](https://user-images.githubusercontent.com/192393/27593705-d0dc4d3c-5b25-11e7-98a1-908e7721f926.png)

Loads under Chrome.

**Comment by jwzimmer** [comment]
Is this the same as https://github.com/LLK/scratch-www/issues/998?

**Comment by rschamp** [comment]
Tracking in #998
