### ISSUE TITLE
"Online tutorial" link doesn't work, missing root URL - Tips page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1373]
Currently, when you click the link shown in the screenshot below (near the top of the Tips page), it goes to the URL `https://projects/editor/?tip_bar=getStarted`, which doesn't load. It seems to be missing the root URL for the host, like scratch.mit.edu or staging.

<img width="613" alt="screen shot 2017-06-27 at 11 41 56 am" src="https://user-images.githubusercontent.com/1320456/27596541-d1ade7ae-5b2d-11e7-9153-e027da787b6a.png">

/cc @chrisgarrity

**Comment by chrisgarrity** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/1377
