### ISSUE TITLE
"Buy cards" button does not reposition below "PDF" button - mobile devices, Tips page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1374]
Galaxy S5, Device Emulator, Win 7 VM, Chrome Version 59.0.3071.115 (Official Build) (32-bit)
and
my iPhone 6s, Chrome

The button to buy the cards on Amazon does not reposition below the PDF button, so it is off screen for small devices:
<img width="291" alt="screen shot 2017-06-27 at 12 30 49 pm" src="https://user-images.githubusercontent.com/1320456/27598841-c0841be0-5b34-11e7-891c-5d0dc8edec18.png">

**Comment by chrisgarrity** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/1380
