### ISSUE TITLE
"Dowloading" typo - Tips page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1378]
The top of the Tips page has a little typo, it should be "downloading" but it's "dowloading":
<img width="461" alt="screen shot 2017-06-27 at 3 19 36 pm" src="https://user-images.githubusercontent.com/1320456/27605918-21feabb2-5b4c-11e7-8129-b7ea01557bae.png">

/cc @chrisgarrity

**Comment by chrisgarrity** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/1377
