### ISSUE TITLE
"Note for Mac users" component's text should be center-aligned

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1382]
The text starting with "Note for Mac users" on the /download page should be center-aligned, as on the /wedo page: https://scratch.mit.edu/wedo.

Staging, Mac OS El Capitan, Chrome.

Not a blocker. 👍 

Wedo page:
<img width="1054" alt="screen shot 2017-06-27 at 5 12 12 pm" src="https://user-images.githubusercontent.com/1320456/27610326-dfbe7f9c-5b5b-11e7-8e07-981ff7d487d1.png">

Download page:
<img width="1280" alt="screen shot 2017-06-27 at 5 02 22 pm" src="https://user-images.githubusercontent.com/1320456/27610327-dfc3e644-5b5b-11e7-9121-9d95556626bd.png">

**Comment by TheGrits** [comment]
I'll fix this one right now!

**Comment by TheGrits** [comment]
@mewtaylor If I'm reading the code correctly, you moved the blue box in question up into the title banner thus making this issue out of date?

**Comment by mewtaylor** [comment]
@TheGrits it's actually the other way around – I moved the second paragraph from the title banner down into the blue box, which is left-aligned (in desktop only). It was in this PR: https://github.com/LLK/scratch-www/pull/1365, for reference.
