### ISSUE TITLE
`/help?` should redirect to `/tips`

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1386]
Generally we redirect `/name?` to `/name`. Since `/help` now redirects to `/tips`, `/help?` should also go to `/tips`. Currently `/help?` loads a blank page on Staging, but the user should end up on the Tips Page.

From https://github.com/LLK/scratch-www/pull/1357#issuecomment-311389191. (Not a blocker.)

**Comment by rschamp** [comment]
This will be fixed after we migrate the rest of /info to www.
