### ISSUE TITLE
`/info` should redirect to `/tips`

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1387]
`/info` should redirect to `/tips`, since `/help` now redirects to `/tips`, and `/info` currently redirects to `/help`, loading the old Help template, which we will soon be removing.

From testing https://github.com/LLK/scratch-www/pull/1357#issuecomment-311389191.

**Comment by chrisgarrity** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/1390
