### ISSUE TITLE
Change text on FAQ from "help page" to "tips page"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1388]
On the FAQ page, we refer to it as the "help" page, so we should call it the "tips" page now. Since we're replacing the Help page with the Tips page. Note the link redirects to the Tips page.

**FAQ page where we refer to "help"**
<img width="590" alt="screen shot 2017-06-28 at 12 41 58 pm" src="https://user-images.githubusercontent.com/1320456/27649299-549d78ce-5bff-11e7-9be6-9c5a272670d9.png">

**Comment by TheGrits** [comment]
@rschamp I'll tackle this one!

**Comment by mewtaylor** [comment]
Fixed in #1389
