### ISSUE TITLE
Update translations info on /credits page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1397]
**TL;DR:** At https://scratch.mit.edu/info/credits, we list Pootle under "Scratch would not be possible without free and open source software, including:" and don't mention Transifex. We should at least remove Pootle, and possibly add Transifex somewhere on the page, if appropriate (Transifex is not free).

/cc @kaschm, @chrisgarrity, @mewtaylor 

<img width="969" alt="screen shot 2017-07-05 at 11 58 36 am" src="https://user-images.githubusercontent.com/1320456/27873237-48b18120-6179-11e7-9d6b-18476cb07c39.png">

**Comment by TheGrits** [comment]
I'm willing to make the changes when this gets the go-ahead!

**Comment by carljbowman** [comment]
Add 'Transifex' to organizations that donate their services.
Remove 'Pootle'
