### ISSUE TITLE
Misplaced periods in text content of Download page?

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-www#1399]
> # Known Issues
>
> If your offline editor is crashing directly after Scratch is opened, install the Scratch 2 offline editor again (see step 2 above.) This issue is due to a bug introduced in Adobe Air version 14. (released April 2014).

This whole paragraph has a couple of things to note. First:

> This issue is due to a bug introduced in Adobe Air version 14. (released April 2014).

The period before "(released" doesn't look right here. Arguably it could be from the number before it, literally written 14., but we don't call Scratch 2 "Scratch 2.".

I'm thinking it just shouldn't be there at all? That would also make the lowercase R in "released" look correct:

> This issue is due to a bug introduced in Adobe Air version 14 (released April 2014).

Also, another quick thing:

> If your offline editor is crashing directly after Scratch is opened, install the Scratch 2 offline editor again (see step 2 above.) This issue is due to a bug […]

The period is inside of the parenthesis "(see step 2 above.)" here, which I don't think is correct. It looks like it's ending the sentence *inside* of the parenthesis, and not the sentence outside; so it ends up looking like there's a period missing. Instead I think the period should be placed outside of the parenthesis:

> If your offline editor is crashing directly after Scratch is opened, install the Scratch 2 offline editor again (see step 2 above). This issue is due to a bug […]

**Comment by mewtaylor** [comment]
Thanks @liam4 for catching this! And if you feel like attempting to fix this, lemme know!

**Comment by TheGrits** [comment]
@liam4 are you planning on tackling this one or may I?

**Comment by liam4** [comment]
Ah, you can take this, @TheGrits; I was having my own problems with getting this building properly when I took a look at it last week, and my main computer isn't working properly right now! Thanks.
