### ISSUE TITLE
Load More Button Behavior in Search Page

### ISSUE THREAD

**Issue by carlflor** [LLK/scratch-www#1400]
Some search scenarios might be better have the `Load More` button hidden.

**1. No results were found**

<img width="967" alt="screen shot 2017-07-06 at 6 45 33 pm" src="https://user-images.githubusercontent.com/4861092/27907920-1a66c6aa-627c-11e7-8b5f-fb9a8069770a.png">

Would it be better if there's a copy that says no match was found (or something similar) instead of still showing 'load more'?

**2. The search results are less than 16 (limit per search)**

<img width="951" alt="screen shot 2017-07-06 at 7 33 40 pm" src="https://user-images.githubusercontent.com/4861092/27909472-5e7445d2-6283-11e7-826a-c18da81c6fbd.png">

**3. Finally, when there are no more Projects/Studios to load upon clicking the button**

(tested using Chrome and Safari on Mac OSX)

**Comment by mewtaylor** [comment]
@carlflor thanks for logging this! We may not have time to get to it immediately ourselves, so definitely feel free to create a PR if you have the time and would like to. I'm happy to answer any questions you have along the way if you decide to do so!

**Comment by carlflor** [comment]
okay, this is something I could take on :)

**Comment by mewtaylor** [comment]
Awesome thanks so much!
