### ISSUE TITLE
Jobs - Add "Junior Designer" position to jobs page

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1404]
- Title: "Junior Designer"
- Link: https://www.media.mit.edu/about/job-opportunities/junior-web-designer-scratch/

**Comment by TheGrits** [comment]
I'll tackle this one!

**Comment by TheGrits** [comment]
@thisandagain On the position page the title is 'Junior **Web** Developer', can you confirm that it should be 'Junior Developer' on Scratch's page? (Should be confirmed before #1405 is merged)

**Comment by thisandagain** [comment]
@TheGrits Thanks! The title should be "Junior Designer" not "Junior Web Designer" or "Junior Developer".

**Comment by TheGrits** [comment]
lol whoops I even made a mistake in my clarification!
