### ISSUE TITLE
[FAQ] Scratch 2.0 works on Firefox/GNU/Linux

### ISSUE THREAD

**Issue by Jonathan50** [LLK/scratch-www#1408]
Here on this page: https://scratch.mit.edu/info/faq, the website says
> Chrome (Windows, ChromeOS, Mac or Linux), Firefox (Windows or Mac only)

This is incorrect, because Scratch 2.0 works fine on Firefox for Linux. :/

I am using Google Chrome on Mac, but presumably the same thing is always said on every browser.
The page is here https://scratch.mit.edu/info/faq

You do have to install Flash, but you'd have to install Flash when using Firefox for Windows or Mac anyway.

**Comment by jwzimmer** [comment]
Hi @Jonathan50, thanks for pointing this out. On our FAQ, we're not trying to list every browser/ OS that Scratch can work on - we're listing those which our team is most likely to commit resources to supporting. So, if a bug is reported that involves the requirements we list on the FAQ, we're more likely to decide to fix that bug than if a bug is reported on any other system. That being said, we recognize that we're not communicating to users as clearly as we would like to what is needed to run Scratch, so we're planning to create a [new page](https://github.com/LLK/scratch-www/issues/1375) which will hopefully represent this info in a manner that's more useful & helpful. : )
