### ISSUE TITLE
Shortcuts to Cards and Guides PDFs no longer working

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#1417]
These shortcuts to the PDFs are now giving a 403 error. We link to them on the Scratch Educator Guides and some other places:
scratch.mit.edu/name/cards
scratch.mit.edu/name/guide

(Same for fly, pong, etc.) Can these shortcuts be updated to work with the new PDF serving system? This is important for the CIS STEAM camp in late July (and for anyone else using the Educator guides). 

![image](https://user-images.githubusercontent.com/4721032/28193767-5a08e5a4-680d-11e7-8ba4-21b8921b7fe9.png)

**Comment by TheGrits** [comment]
Related to #1182

**Comment by ntlrsk** [comment]
I talked with @chrisgarrity and we're wondering how to open the PDF in the correct language. For now they could call go to the main Cards page scratch.mit.edu/info/cards (and then they can see which set they want).

**Comment by chrisgarrity** [comment]
@mewtaylor I'm assuming that there's no way for the redirect to detect the locale and redirect to a localized PDF. It would have to know which files have been localized etc. Going to the cards page would work for the cards, but not guides.

@ntlrsk the current redirect doesn't figure out language, so perhaps we should just redirect to the english pdfs. It would be consistent with what it does now, and would work for both cards and guides.

**Comment by ntlrsk** [comment]
I think it would be good for the cards to redirect to the cards page so they can choose them in their language. For the guides it could go to English since for now we don't have them translated.

**Comment by chrisgarrity** [comment]
Moved to LLK/scratchr2#4723
