### ISSUE TITLE
Localization - Document list of words to not be translated

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1431]
Having clarity around which words should not be translated came up during a translation discussion at the Scratch Conference in Bordeaux. Currently we have a great deal of inconsistency across languages / locales (e.g. some translate the word "Scratch" others keep "Scratch" but translate the word "Day" in "Scratch Day", etc). Here are some of the questions / suggestions that came out of the session:

### Questions
- Why does this inconsistency exist?
- Is it beneficial to have a standard across all locales?

If the answer to question 2 is "yes", then the following could be considered:

#### Brands
- Scratch
- ScratchJr
- Scratch Foundation
- ~Scratch Conference~
- ~Scratch Day~

#### Characters
- Gobo
- Pico
- Tera
- Nano
- Giga

#### Controversial
- ~Scratcher~

**Comment by liam4** [comment]
>* Scratcher

It might also be worth discussing "New Scratcher".

**Comment by chrisgarrity** [comment]
Currently we tell people never to translate Scratch or ScratchJr. Historically, some languages (that don't use latin characters) translated Scratch, but I think we should probably revisit whether that was the correct choice. @ntlrsk I think you know the story behind translating Scratch in China.

For Scratch Day in 2016 we told people that Scratch must not be translated, but it would be ok to translate 'Scratch Day' as 'Day of Scratch' if that made more sense for their language. To the extent that we're encouraging people to have their own Scratch days and not identify a specific date as **the day**, I think that's ok. 

I think that Scratch Foundation and Scratch Conference come down on the side of not translating, but could be argued the other way as well.

**Comment by LiFaytheGoblin** [comment]
@liam4 : "New" can be a very different word in another language, and in German for example, the translation "Neuer Scratcher" is very common. One wouldn't say "New Scratcher"...

Also suggestion:
Scratch Wiki

**Comment by chrisgarrity** [comment]
Added a section to the How to Translate Scratch wiki page on what not to translate:
https://wiki.scratch.mit.edu/wiki/How_to_Translate_Scratch#What_not_to_translate

**Comment by chrisgarrity** [comment]
@thisandagain is there someone we should be sending the wiki link to?

**Comment by thisandagain** [comment]
@chrisgarrity The French, Dutch, and Catalan translators were particularly interested in this. Perhaps we can add it to the Transifex discussion pages for each?
