### ISSUE TITLE
Edits to the Community Guidelines

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1438]
Currently the [Community Guidelines](https://scratch.mit.edu/community_guidelines/) state: "Scratch welcomes people of all ages, races, ethnicities, religions, sexual orientations, and gender identities."

We would like this to be changed to "Scratch welcomes people of all ages, races, ethnicities, religions, abilities, sexual orientations, and gender identities."

---
Moved from LLK/scratchr2#4733
/cc @christanbalch

**Comment by TheGrits** [comment]
@thisandagain I can take this one!
