### ISSUE TITLE
Remove Community Moderator Job listing

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1442]
https://scratch.mit.edu/jobs/moderator needs to come down as the position has been filled.

---
Moved from LLK/scratchr2#4729
/cc @dietbacon

**Comment by St19Galla** [comment]
I can take this!

**Comment by dietbacon** [comment]
Reopening as we've filled this position again!

**Comment by VutonDesign** [comment]
@dietbacon I can remove it if this becomes help-wanted.

**Comment by TheGrits** [comment]
@VutonDesign It is `help-wanted`! 👍

**Comment by VutonDesign** [comment]
Oops, I thought that was from last time.
I'll get a pull-request sent in a couple of minutes. 👍
