### ISSUE TITLE
Update Educator page to reflect new Tips page

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#1444]
It would be good to update the Educator page to refer to the Tips page.

1) Changing wording from "Things to Try" --> "Tips". 
2) Changing link from https://scratch.mit.edu/go -->  https://scratch.mit.edu/tips
3) Changing icon if possible: It would also be helpful to have a different icon for that page 
@carljbowman could a simplified version of the awesome cards icon from the Tips page work? 

Here is the current wording and icon:
![image](https://user-images.githubusercontent.com/4721032/28696338-f9546f66-7302-11e7-8b6a-e3d88b3cc57e.png)

**Comment by carljbowman** [comment]
@St19Galla - Thanks for making those changes. Here is a new illustration: [cards.svg.zip](https://github.com/LLK/scratch-www/files/1187977/cards.svg.zip)


_Mock does not reflect the text changes, only the illustration_
![quick-mock](https://user-images.githubusercontent.com/3409578/28784435-6bf561c0-75e1-11e7-9b41-6de0107bbb40.png)

**Comment by carljbowman** [comment]
@chrisgarrity - I am going assign you this issue as you are reviewing the associated PR.
