### ISSUE TITLE
Scratch Team updates for Credits page

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1450]
Comings and goings:

- [ ] Move Kasia Chmielinski and Saskia Leggett to previous team members
- [ ] Add Champika Fernando to current Scratch Team members and remove from previous
- [ ] Remove Di Liu from previous team member (already in current Scratch Team)

Note: Do not deploy before Aug 7.

**Comment by TheGrits** [comment]
I can take this one, do you want me to make the PR on August 7 or should I add a note on the PR to not merge till August 7th?
