### ISSUE TITLE
'has invited you to join the class:' is not translatable in some languages

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1454]
registration.classroomInviteNewStudentStepDescription (in general) is a sentence fragment. In languages where the subject doesn't come before the text, this becomes very difficult to translate.

Now that the www strings have been split from the legacy .po file, we could add a placeholder to the string:
`'{teacherId}<br/> has invited you to join the class'`

But if `{teacherId}` ends up in the middle of the translation, it may look strange:

You've been invited by **aTeacher**  to join the class: 

<img width="537" alt="screen shot 2017-08-04 at 1 20 31 pm" src="https://user-images.githubusercontent.com/399209/28980047-56b6743e-791a-11e7-8210-43396607d066.png">

**Comment by chrisgarrity** [comment]
Here are some suggestions from translators for a couple of the languages that would put the verb first:

From  kscanne
>  One suggestion might be to reword as "You received an invitation to join the class from:" with the big username below. A hackier solution that Mozilla sometimes uses is to provide an optional "prepended" string, empty in English (and most other languages), rendered *above* the user name when non-empty, and which we could use for the verb in GA/GD (and in the 700+ verb first languages is the world!)

From GunChleoc

> Another possible solution would be to have just the icon above the text and then have the username in bold within the text.

The full discussion is in the comments on [the string in Transifex](https://www.transifex.com/llk/scratch-website/translate/#gd/general-l10njson/102347925).

**Comment by gunchleoc** [comment]
Mockup for another design idea:

<img width="537" alt="scratch invitation" src="https://user-images.githubusercontent.com/4095570/29114969-c85fd5cc-7ced-11e7-8c78-3b625f753fbf.png">

**Comment by thisandagain** [comment]
How about leaving the design as is and simply changing the string to, "Your teacher has invited you to join a class".

**Comment by gunchleoc** [comment]
This might work for this particular string, but we have tons of those on the activity stream that need flexible position for both subject and object. "**X** likes your **Y**" comes to mind here, which is "Is toigh le **X** a' **Y** agad" in my language.

**Comment by chrisgarrity** [comment]
@gunchleoc we're in the middle of a pretty complete overhaul of the notifications system. We should be starting to have "{scratcher} loved your project {name}" strings soon. Probably starting with the activity feed, and then rolling out from there. Most of the educator registration flows are unique so this one will be handled separately.

**Comment by gunchleoc** [comment]
That's excellent news, thanks! :)
