### ISSUE TITLE
Language change in Explore not applied to all pages

### ISSUE THREAD

**Issue by WorldLanguages** [LLK/scratch-www#1455]
**Steps to reproduce:**

I'll consider you're using English as your Scratch language.

1. Go to the Explore page
2. Scroll into the footer and change the language to any other (French, for example)

**Result:**
All pages except Explore will be in English. Explore will be in French.

**Comment by thisandagain** [comment]
@mewtaylor do you mind taking a look at this?

/cc @chrisgarrity @rschamp

**Comment by mewtaylor** [comment]
Hmm this one's odd – somehow, even though the footer mechanism is the same, the language cookie, when set on explore, is only getting applied to the explore url, and not to the general default path `/`. But there's nothing I can see just yet to suggest why that's happening...
