### ISSUE TITLE
on Tips page Getting Started PDF link is not linking to translated file

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#1457]
Leo noticed that the link from https://scratch.mit.edu/tips to the Getting Started PDFs is pointing to the English version of the files.

For example for Portuguese Brazilian PDF is in the folder   pdfs->help->pt-br, the link from https://scratch.mit.edu/tips is to the English directory. Same for French.

**Comment by thisandagain** [comment]
@chrisgarrity would you have a moment to look at this bug? If not, please move to the next iteration.

**Comment by chrisgarrity** [comment]
@ntlrsk All of the guides need to be moved to the resources repo.

**Comment by chrisgarrity** [comment]
Resources is updated (http://resources.scratch.mit.edu/localized-urls.json). Next time www is deployed it should get updated links. @ntlrsk is this worth a hotfix?
