### ISSUE TITLE
'scratchlanguage' cookie domain set to 'scratch.mit.edu' only

### ISSUE THREAD

**Issue by WorldLanguages** [LLK/scratch-www#1460]
The `scratchlanguage `cookie domain is `scratch.mit.edu` and not `.scratch.mit.edu` (with a dot).

Because of that, Scratch subdomains like `api.scratch.mit.edu` use the language based in user's location, and not the one chosen by the user in the footer.

For example, the What's Happening box gets the information from the API, so it's displayed in a different language:
![image](https://user-images.githubusercontent.com/17484114/29193154-886b0a64-7dfa-11e7-90e2-474dd3585301.png)

**Comment by thisandagain** [comment]
The API receives the language as a query parameter rather than reading a user's cookie (this is to help with caching). For example, see how `/explore` is rendered via:
```
https://api.scratch.mit.edu/explore/projects?limit=16&offset=0&language=en&mode=trending&q=*
```

Issues with the "What's Happening" box are tangential to how the cookie is stored and shared across domains.
