### ISSUE TITLE
"Cannot GET /projects/editor/?tip_bar=home" How to Fix? thx

### ISSUE THREAD

**Issue by xmagicbox** [LLK/scratch-www#1461]
i git clone it,and install,start on google cloud, all port had opened on google cloud,it work on homepage,but click create,it's show me "Cannot GET /projects/editor/?tip_bar=home",who can tell me why and how to fix it, thanks very much!

**Comment by thisandagain** [comment]
The project page and editor have not yet been ported over to the `scratch-www` repo. We will do this next year.

**Comment by xmagicbox** [comment]
does the early versions ported over the editor to the scratch-www？ths

**Comment by thisandagain** [comment]
Hi @xmagicbox unfortunately I'm not sure I understand your question. Could you clarify?

**Comment by xmagicbox** [comment]
does the early version of scratch-www ported over the editor？

**Comment by TheGrits** [comment]
@xmagicbox No, the editor hasn't been previously ported over.
