### ISSUE TITLE
Clicking a linked image in a preview makes the preview navigate to the url instead of the browser

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1462]
Originally reported in: https://scratch.mit.edu/discuss/topic/273051/
### Expected behavior
Clicking a linked image in a post preview should make the browser go to the url
### Actual behavior
Clicking a linked image in a post preview makes the *preview* go to the url - it loads up the full webpage inside the preview box.
### Steps to reproduce
1. Go to the new post box
2. Use `[url=(an url, any url)][img]any image[/img][/url]`
3. Press “preview”
4. Click the image in the preview
5. The url you used will load *inside the preview*

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4763

**Comment by Kenny2github** [comment]
@thisandagain FYI it turns out that it doesn't have to be an image - any url will do the same.

(if you already found that out in the discussion in scratchr2 then 👍 )
