### ISSUE TITLE
Add Mod To Credits Page

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#1465]
We would like to add the following to the [Credits](https://scratch.mit.edu/info/credits/) page under the section that reads "The team of Scratch moderators manages, supports, and improves the Scratch online community":

Ellen Daoust - username [sunnyday4abluejay](https://scratch.mit.edu/users/sunnyday4abluejay/)

**Comment by St19Galla** [comment]
I can take this :)
