### ISSUE TITLE
how i can change the all the block 's language to other language ? Team should give many plan

### ISSUE THREAD

**Issue by youngonlyforyou** [LLK/scratch-www#1467]
how i can change the all the block 's language to other language ? Team should give many plan

**Comment by St19Galla** [comment]
Hello @youngonlyforyou :) If you are asking how to change the language on the text of the Scratch Blocks, you click the little Globe icon in the top left corner of the editor, then select your language :) It looks like this: 

<img width="100" alt="screen shot 2017-08-16 at 11 34 54 pm" src="https://user-images.githubusercontent.com/16446551/29394906-76a6af50-82db-11e7-8430-6ff6a54ba9d3.png">

**Comment by thisandagain** [comment]
Could you please clarify your question?
