### ISSUE TITLE
Migrate For Parents page to www

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1469]
Looking at the header of https://scratch.mit.edu/parents, I see that the For Parents page is still in scratchr2.
So I’m suggesting migrating it to this repo.
If it’s already being worked on, I guess I’m opening this issue to track the migration.
If there’s already an issue for it, that I didn’t see when searching, then oops 😬

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-www/issues/1248
