### ISSUE TITLE
Firefox - Text overflow on credits page

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1470]
The contributor lists don't fit on the cretis page, because line breaks are being blocked.

![scratch-credits-string-overflow](https://user-images.githubusercontent.com/4095570/29519732-56b577c8-8676-11e7-9df2-01b1c50d8980.PNG)

My browser / operating system: Windows 7, Firefox 55.0, Flash 26.0 (release 0)

Posting this here so I won't have to bother with image hosting for the screenshot ;)

---
Moved from LLK/scratch-flash#1344
/cc @gunchleoc

**Comment by TheGrits** [comment]
I'll take a shot at this one!

**Comment by thisandagain** [comment]
Thanks @TheGrits !

**Comment by TheGrits** [comment]
I tried adding `<div>`s around the words+comma combos to make sure that they don't get separated... but then they all float to the right. 🤔

I'm currently working a day job for the summer, so I may not fix this in a prompt manner. If someone else wants to take a shot at this one, go for it!

**Comment by thisandagain** [comment]
@TheGrits No problem! Thanks for giving it a shot.

**Comment by Petroochio** [comment]
I think I've got it. There is a global style 
```css
p a {
  white-space: no-wrap;
}
```
This appears to be causing the issue. I can disable it with `.credits p a { white-space: normal; }`

**Comment by gunchleoc** [comment]
Shouldn't the white-space: normal be a property of p rather than a?

I think a cleaner fix would be to have a special no-wrap style for places where no wrapping is allowed, wrapping is what one would expect normally, after all. I don't know the code base though.

**Comment by Petroochio** [comment]
@gunchleoc I think I agree with you, but I wasn't sure where changing a global style like that would cause issues in a project this large. To me it would seem less common to want no-wrap, but I was afraid of regression issues.

**Comment by gunchleoc** [comment]
Since that global style is asking for more trouble down the line, maybe possible regressions right now before even more pages are converted to the new format would be the lesser of 2 evils?

Of course, I'm not a coder on this project, so we'd best leave that decision to somebody who knows the project well.
