### ISSUE TITLE
Change text on About page; link text shouldn't be "Help"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1471]
Currently the link to the Tips page describes it as the "Scratch Help Page", which is outdated by the new Tips page:
<img width="388" alt="screen shot 2017-08-21 at 12 19 02 pm" src="https://user-images.githubusercontent.com/1320456/29528758-25b42058-866b-11e7-8ea6-50a61f4e4cf5.png">

**Comment by TheGrits** [comment]
What is the preferred text for the link? "Scratch Tips Page"?

**Comment by jwzimmer** [comment]
I think possibly just "Tips Page" (and maybe Scratch Credits --> Credits), I don't know why the "Scratch" part is there. @carljbowman?

**Comment by TheGrits** [comment]
@thisandagain Issue should've been closed, right?

**Comment by thisandagain** [comment]
Whoops! Yep.
