### ISSUE TITLE
Change which word is linked to for the Scratch 2.0 Offline Editor - currently "website"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1473]
I think we might want to change which word is linked to for the Scratch 2.0 Offline Editor on the FAQ (https://scratch.mit.edu/info/faq). Currently it's "website" which I think is a little unexpected for the 2.0 Offline Editor downloads page.

The part that says "download Scratch 2" might make more sense to be the linked text.

<img width="617" alt="screen shot 2017-08-21 at 2 37 03 pm" src="https://user-images.githubusercontent.com/1320456/29534832-822faff4-8685-11e7-910d-f4e2011aecb4.png">

/cc @carljbowman

**Comment by thisandagain** [comment]
Major +1 on moving that link to the words "download Scratch 2.0" (add the ".0").

**Comment by thisandagain** [comment]
Clarifying scope of work:
- [ ] Update text to read "Scratch 2.0" rather than "Scratch 2"
- [ ] Move link from the word "website" to "download Scratch 2.0"

**Comment by St19Galla** [comment]
I can take this as well :)

**Comment by thisandagain** [comment]
@St19Galla Julia ( @jwzimmer ) just pointed out that we should update the page headline as well to be consistent.
