### ISSUE TITLE
Is the link for the Scratch Device Manager app store supposed to still be for the "preview"?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1474]
Should the link for the Mac OSX SDM download on the /wedo page still be for a page titled "Preview"? /cc @cwillisf

Link is currently: https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1084869222&mt=12

<img width="1092" alt="screen shot 2017-08-21 at 3 45 33 pm" src="https://user-images.githubusercontent.com/1320456/29535427-cb63c6c2-8687-11e7-80a5-dd7e8083593c.png">

<img width="1067" alt="screen shot 2017-08-21 at 3 43 08 pm" src="https://user-images.githubusercontent.com/1320456/29535404-b758b00c-8687-11e7-943c-1effcd3f1788.png">

**Comment by thisandagain** [comment]
This is the correct link. Unfortunately Apple's language is confusing. The "Preview" thing is an Apple convention for the website that provides a deep link into the Apple App Store.

Another example:
https://itunes.apple.com/us/app/civilization-vi/id1123795278?mt=12
