### ISSUE TITLE
WeDo should be camel case

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1481]
https://github.com/LLK/scratch-www/blob/6309c306675c69b1b42b67c3b68a39dd720dfa58/src/views/wedo2/l10n.json#L13

The English source strings for the WeDo setup (1.0 and 2.0) should be WeDo instead of wedo.

**Comment by Kenny2github** [comment]
I got this

**Comment by TheGrits** [comment]
@thisandagain This one should be closed too.
