### ISSUE TITLE
Scratch Team update for credits page

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#1488]
New team member:

 - [ ] Tracy Tang 
    Please use: https://cdn.scratch.mit.edu/get_image/user/18417774_170x170.png

**Comment by TheGrits** [comment]
@colbygk I can take this one.

**Comment by TheGrits** [comment]
@colbygk Is this ST member a moderator or not?

**Comment by colbygk** [comment]
Thank you @TheGrits, this ST member is not a moderator.
