### ISSUE TITLE
www pages not loading on IE 11, Win 7 VM - Staging only

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1500]
The homepage, /about, and /messages are not loading for me in IE 11 on my Win 7 VM (Staging). The editor & My Stuff load. On Production, everything seems to load as usual. Staging loads as usual in Chrome on my Win 7 VM.

The error in the console is "Object doesn't support property or method `assign`".

<img width="744" alt="screen shot 2017-09-05 at 12 04 34 pm" src="https://user-images.githubusercontent.com/1320456/30070914-ebf0b664-9232-11e7-9fff-6f6ad6ac2997.png">
<img width="696" alt="screen shot 2017-09-05 at 12 04 27 pm" src="https://user-images.githubusercontent.com/1320456/30070913-ebeeb062-9232-11e7-8a31-246a3d676794.png">
<img width="1018" alt="screen shot 2017-09-05 at 12 03 39 pm" src="https://user-images.githubusercontent.com/1320456/30070915-ebfa7b0e-9232-11e7-8a72-ed81c23f8b59.png">

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/commit/5772eed8f7b13aeb5c23146a6ffb3e141cbab46d, thanks @jwzimmer !
