### ISSUE TITLE
Signing out from /messages doesn't trigger page redirect

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1501]
If you sign out (using the navbar) while you are on the /messages page, the page doesn't automatically take you to the homepage or show you 403 or anything; it continues to show you that user's messages page content. That content should not be accessible to anyone besides the relevant authenticated user. 

The navbar also doesn't always have the correct state; sometimes it stays in the "default" state after you sign out, where it doesn't display anything to the right of the search bar.

Repro'd in multiple browsers/ OSs (Chrome + Mac, IE 11 & Chrome + Win 7 VM).

Repro:
- Sign in on Staging
- Go to Messages page
- Sign out (via navbar)
- Note you remain on Messages page, no changes other than in navbar

<img width="987" alt="screen shot 2017-09-05 at 1 31 26 pm" src="https://user-images.githubusercontent.com/1320456/30074275-f1b8f5b4-923e-11e7-872f-d3c624c7f1af.png">
<img width="1025" alt="screen shot 2017-09-05 at 1 23 20 pm" src="https://user-images.githubusercontent.com/1320456/30074276-f1c09dfa-923e-11e7-8825-71b84ad7edc5.png">
<img width="1032" alt="screen shot 2017-09-05 at 1 24 00 pm" src="https://user-images.githubusercontent.com/1320456/30074274-f1ab2588-923e-11e7-8435-9bc7d6b42483.png">

**Comment by mewtaylor** [comment]
@carljbowman @jwzimmer @rschamp @thisandagain we had originally decided to not redirect to the homepage on log out in www, but that was before we had a page that was for only logged in users (messages). I'd propose we go back to what legacy does for now, and redirect to the splash page on logout, no matter where on the site you are.

**Comment by carljbowman** [comment]
@jwzimmer - Good catch. This seems like rather odd behavior.

I agree with @mewtaylor on the redirect. Redirecting on a logout while on a static page (e.g. About) feels a bit inconvenient, but displaying 'logged in' pages with no content feels like it sets up weird expectations around logged in and logged out state.

At this point I feel we should generalize and redirect to the splash on all log out actions. One could imagine page-by-page behavior, but that may seem like overkill at this point.

**Comment by thisandagain** [comment]
+1 on redirecting to splash page on logout for all instances. Thanks for catching this!

**Comment by mewtaylor** [comment]
Fixed in #1503
