### ISSUE TITLE
Uncaught TypeError: Cannot read property 'success' of undefined - Staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1505]
On the new messages page, Chrome 60, Mac OS El Capitan.

No obvious impact on functionality.

<img width="498" alt="screen shot 2017-09-05 at 5 11 14 pm" src="https://user-images.githubusercontent.com/1320456/30083674-6c6d7fdc-925d-11e7-99ce-1e18952d7a5e.png">

Repro:
- Sign in as jwzimmer1990
- Open console
- Refresh messages page

**Comment by mewtaylor** [comment]
Fixed in #1510
