### ISSUE TITLE
Activity feed for teacher doesn't load

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1506]
Admin notifications are visible, but none of the activity by students (adding projects, commenting, liking etc) are there. The spinny loading icon never goes away. I didn't make a gif, but imaging the loading icon spinning and you get the idea.
<img width="760" alt="screen shot 2017-09-05 at 5 27 42 pm" src="https://user-images.githubusercontent.com/399209/30084297-d38bc424-925f-11e7-9d97-3f5e556f7096.png">

I tried on both Chrome Version 60.0.3112.101 (Official Build) (64-bit), and Safari Version 10.1.2 (12603.3.8)

**Comment by chrisgarrity** [comment]
Console error: Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
getting https://scratch.ly/site-api/classrooms/activity/189/all/

**Comment by thisandagain** [comment]
@jwzimmer does this happen on production?

**Comment by jwzimmer** [comment]
I repro'd this issue on Staging, did not see it on Production.

Activity feeds load for teachertest123's classes on Production:
<img width="732" alt="screen shot 2017-09-05 at 5 48 29 pm" src="https://user-images.githubusercontent.com/1320456/30084971-9888fd94-9262-11e7-934e-87773d8d72d7.png">
<img width="622" alt="screen shot 2017-09-05 at 5 53 53 pm" src="https://user-images.githubusercontent.com/1320456/30085150-39d99352-9263-11e7-93af-66a75e68e408.png">

Activity feed does not load for teacher3830's class on Staging:
<img width="1280" alt="screen shot 2017-09-05 at 5 50 31 pm" src="https://user-images.githubusercontent.com/1320456/30085030-d23eb5ec-9262-11e7-8977-b28a9284bd7f.png">

Activity feed does load for all classes for teacher3830 on Staging:
<img width="1012" alt="screen shot 2017-09-05 at 5 51 53 pm" src="https://user-images.githubusercontent.com/1320456/30085092-1066558c-9263-11e7-82b5-b187b6f6556e.png">

**Comment by jwzimmer** [comment]
Moved to LLK/scratchr2#4789
