### ISSUE TITLE
When there are 0 unread messages, do not display counter

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1507]
In the old system, when there are no messages, there is no counter displayed. On the new Messages page, the "Messages" counter displays "0" when there are no unread messages. We should change this to match the old behaviour, as it seems a bit friendlier. Not a blocker. (Discussed with @carljbowman & @mewtaylor.)

Currently this is on Staging. (But since it's not blocking, it may be on Production soon-ish.)

<img width="991" alt="screen shot 2017-09-01 at 3 31 38 pm" src="https://user-images.githubusercontent.com/1320456/29984979-0194937e-8f2b-11e7-848d-ea51cba53a55.png">

**Comment by mewtaylor** [comment]
Fixed in #1510
