### ISSUE TITLE
Unicode chars not displaying properly - new /messages page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1508]
Unicode characters in comments display as ???!!!! (etc.) in the new messages page. 

To **repro**, comment `спасибо` on something and then check the notification on the messages page.

(Staging, Chrome 60, Mac OS El Capitan)

<img width="359" alt="screen shot 2017-09-05 at 5 35 33 pm" src="https://user-images.githubusercontent.com/1320456/30084517-bfeec208-9260-11e7-9e46-53a787581230.png">
<img width="436" alt="screen shot 2017-09-05 at 5 35 20 pm" src="https://user-images.githubusercontent.com/1320456/30084516-bfee0336-9260-11e7-8a65-dbacbff3ce91.png">

**Comment by mewtaylor** [comment]
This is an issue that's specific to how we were storing data on staging (I confirmed this by seeing that the migration had data with the correct charsets in it). I fixed the issue with our staging database, so any new comments with unicode chars should work fine (it's still broken for old tries though). This does not have any effect on production, where unicode chars will show up correctly.
