### ISSUE TITLE
Add 'For Translators' page

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1511]
We should have a page for translators based on the https://scratch.mit.edu/developers template.

Content will mostly come from https://wiki.scratch.mit.edu/wiki/How_to_Translate_Scratch

**Comment by St19Galla** [comment]
I can take this if it's a help-wanted issue :)

**Comment by Kenny2github** [comment]
Will this page be added into the footer or @St19Galla will you take care of that too?

**Comment by St19Galla** [comment]
@Kenny2github Yes, that would probably be apart of the PR should they need help :)

**Comment by thisandagain** [comment]
@chrisgarrity Do you want help with this?

**Comment by chrisgarrity** [comment]
@thisandagain I'll need to figure out what the text needs to be, but otherwise this could definitely be help-wanted.

**Comment by Kenny2github** [comment]
I know this was moved into backlog, but I'd just like to bump it anyway to see if there are any updates on this - i.e. is it help-wanted?

**Comment by chrisgarrity** [comment]
@Kenny2github it's not help-wanted yet. First we need to write the content. Once we have the correct copy, it should be switched to help wanted.

**Comment by chrisgarrity** [comment]
Superseded by https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators
