### ISSUE TITLE
Posting on the forums blanks "What I've been doing" section on user's profile

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1512]
I saw this issue reported in a profile comment somewhere and tried to repro it - and succeeded.
### Expected behavior
Posting in the forums does nothing to the "What I've been doing" section on your profile
### Actual behavior
Posting in the forums blanks said section
### Steps to reproduce
1. Do something that shows up in that section. There will be activity there;
2. Post in the forums.
3. Check the section again. It will be blank.

In my case, I had "kenny2scratch is now following dorkbot" in my section, then I made a post in Suggestions, and checked back and the item had disappeared.

**Comment by VutonDesign** [comment]
Same problem here 👍

**Comment by Kenny2github** [comment]
Closing as this seems to be resolved now.
