### ISSUE TITLE
Scratcher invite doesn't appear to be dismissed until you refresh the page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1518]
@mewtaylor & I have been looking at this. If a user gets an invite to be a Scratcher, then tries to dismiss that alert on the new messages page, it doesn't appear to be dismissed. Nothing seems to happen. However, if you refresh the page, the alert does disappear. Initially there was also an error in the console, which @mewtaylor already fixed, due to:
> an issue changing the cache after deleting it, which was causing the front end to not know to remove it

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/commit/1dffc08445353ce28c6511ff3cf3064840e7bed2
