### ISSUE TITLE
Icon size changes when notification text wraps to multiple lines - Messages page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1521]
Increase the size of the green people in the svg icon. Discussed with @carljbowman & @mewtaylor.
<img width="835" alt="screen shot 2017-09-08 at 4 31 24 pm" src="https://user-images.githubusercontent.com/1320456/30230177-2e20a328-94b3-11e7-8065-bbb3713c145a.png">

**Comment by jwzimmer** [comment]
Looking at the icons with @carljbowman, it looks like for some reason the studio invite icons are ignoring the css style telling them to resize from 16 x 16 to 20 x 20.

**Comment by jwzimmer** [comment]
<img width="430" alt="screen shot 2017-09-08 at 5 58 12 pm" src="https://user-images.githubusercontent.com/1320456/30232699-68e28bbe-94bf-11e7-8b34-90cc5e764e67.png">
<img width="436" alt="screen shot 2017-09-08 at 5 57 53 pm" src="https://user-images.githubusercontent.com/1320456/30232700-68ebd3f4-94bf-11e7-9c66-57662bb701f5.png">

**Comment by mewtaylor** [comment]
fixed in https://github.com/LLK/scratch-www/commit/d18fd0064bdcf8a566a3fadc2024f82175da3502
