### ISSUE TITLE
'New forum post' message rows have the wrong CSS class

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#1526]
They have the `.mod-studio-activity` CSS class. That makes user-styling them more difficult.

It looks to probably just something missed in copy/pasting?

The bad line: https://github.com/LLK/scratch-www/blob/develop/src/views/messages/message-rows/forum-topic-post.jsx#L19

**Comment by mewtaylor** [comment]
@towerofnix nice catch! if you want to fix it, please feel free to as well :).
