### ISSUE TITLE
500 Character warning message in comments stays red after posting

### ISSUE THREAD

**Issue by DatOneLefty** [LLK/scratch-www#1527]
after doing a comment that is 500 characters, and then submitting it, the empty comment box says 500 characters remaining in red like it is at 0 remaining instead of resetting back to gray

Screenshot:
![screen shot 2017-09-09 at 11 17 18 pm](https://user-images.githubusercontent.com/14064434/30245874-902d442e-95b5-11e7-9c30-6be1eee04f33.png)

**Comment by Kenny2github** [comment]
So you mean when you submit a comment that hits the limit, the number remains red instead of going back to gray? huh.

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4823
