### ISSUE TITLE
Messages only clear after doing a hard refresh

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1528]
### Expected behavior
Refreshing the messages page should clear the messages counter (i.e. make the number disappear and count all messages as read)
### Actual behavior
Only doing a hard refresh (Ctrl+F5 on Win, Cmd+Shift+R on Mac) clears the counter.
### Steps to reproduce
Assuming you have a non-zero number of messages:
1. Navigate to https://scratch.mit.edu/messages
2. Refresh a few times
3. Messages are not cleared
4. Hard refresh
5. Messages are cleared

**Comment by VutonDesign** [comment]
I've noticed that a hard refresh doesn't even help sometimes, I had 2 messages just there and I had to hard refresh the page 4 times then open every individual message up in a new tab! :desktop_computer:

**Comment by jwzimmer** [comment]
I am seeing this on Production as well, but **not** on Staging.

The counter stayed at 1 after I viewed the page, and hard refresh did not clear the counter.

(Chrome 60, Mac OS El Capitan, Production)

**Comment by Kenny2github** [comment]
@jwzimmer it turns out that even a hard refresh doesn’t work - as customhacker mentioned, you have to visit a non-scratch-www site (one that actually has the ability to mark the notifications as read) to clear messages.
However, this seems to be fixed - visiting the messages page in the first place cleared the number.

**Comment by mewtaylor** [comment]
@Kenny2github we just put in a fix for this last night – are you still seeing caching issues?

**Comment by thisandagain** [comment]
@mewtaylor The issue appears to be fixed for me!

**Comment by Kenny2github** [comment]
@mewtaylor yes, it appears to be fixed - doing a refresh worked fine! Closing.
