### ISSUE TITLE
Tips Page Card

### ISSUE THREAD

**Issue by VutonDesign** [LLK/scratch-www#1530]
## About
I've recently noticed that the "Fashion Game" card on this tips page is slightly longer than any other card causing it and any card under it to become lower and less symmetrical. 

## Fix
Remove a word from that card to keep it the same size as every card on that page.

## Priority 
Not that important but it's worth taking a look at.

**Comment by VutonDesign** [comment]
I can try and fix this, I'll submit a pull request later today. :paintbrush:

**Comment by chrisgarrity** [comment]
Not changing the text at this time, but the PR is all ready to go if we decide to at some point.
