### ISSUE TITLE
New Message Inbox | Spam Bug

### ISSUE THREAD

**Issue by VutonDesign** [LLK/scratch-www#1531]
Me and a few others have noticed that you can get spammed by tons of messages from one person if they were to repeat an action over and over again.  You don't even have to refresh the page.  For example, take this:
http://i.cubeupload.com/Efh6pj.jpg

I gave this user permission to spam me with those messages for testing purposes.
All you have to do is spam the "love" or "fave" button loads of times. I imagine this would be the same for new followers.

**Comment by mewtaylor** [comment]
@VutonDesign this should be fixed now – definitely let me know if you still see it though! Thanks for logging this :).
