### ISSUE TITLE
Bad gateway on projects the first time.

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-www#1535]
![screenshot 2017-09-11 at 3 25 41 pm](https://user-images.githubusercontent.com/10731781/30292850-9ae6c560-9705-11e7-95e4-a26fea954d9f.png)
Bad request the first time I load a project I have to reload to fix.

Chromebook

**Comment by TheGrits** [comment]
@CosmicWebServices Not seeing this on my machine.

MacOS running Chrome

**Comment by VutonDesign** [comment]
Just checked on my Chromebook, Works Fine. I guess you could try clearing your cache but I don't imagine it would do much.

**Comment by CosmicWebServices** [comment]
Hmm odd still happening

**Comment by thisandagain** [comment]
@CosmicWebServices We can't reproduce this. Can you please provide the exact link and OS version you are using?

**Comment by CosmicWebServices** [comment]
It seems to be a firewall/wi-fi problem now that I am looking more into it. Only happens at my school which has a strict firewall.
