### ISSUE TITLE
Placeholder projects should not be clickable

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#1536]
[This user ran into an issue because placeholder projects are clickable:](https://scratch.mit.edu/discuss/topic/276347/)

> **https://scratch.mit.edu/projects/undefined/ <--- whats up with that?**
> I was clicking buttons too fast and somehow i got there

Since placeholder projects don't have IDs, the user ends up being sent to `https://scratch.mit.edu/projects/undefined/`. It's probably best to just make placeholder projects not have links at all.

**Comment by GreenBayRules** [comment]
I'll try this one, but I'm not sure what a "placeholder project" is @towerofnix

**Comment by Kenny2github** [comment]
@GreenBayRules "placeholder project" refers to any link to a nonexistent project, such as https://scratch.mit.edu/projects/undefined/
The thing that automatically links scratch.mit.edu urls should not link the url if it leads to a nonexistent project (or any 404 url, for that matter)

**Comment by GreenBayRules** [comment]
oh okay thanks :D

**Comment by GreenBayRules** [comment]
Where is the code for making links clickable?

**Comment by Kenny2github** [comment]
@GreenBayRules I think it's in scratchr2, a private repository.

**Comment by GreenBayRules** [comment]
Oh okay, then I can't do this :P

**Comment by towerofnix** [comment]
It's almost certainly not. Whether the links are clickable or not (i.e. whether or not there is an `<a>` element) is decided client-side, because scratch-www pages are all rendered on the client.

**Comment by towerofnix** [comment]
The specific code for project thumbnails is here: https://github.com/LLK/scratch-www/blob/master/src/components/thumbnail/thumbnail.jsx

It looks like it wouldn't exactly be a simple one-line fix, though.

**Comment by rschamp** [comment]
Thanks for reporting this @towerofnix. I think a better solution would be not to render the dummy projects at all. So capturing this issue in #1620 instead.
