### ISSUE TITLE
Unable to search/ explore - Staging only

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1537]
Currently I don't get any results on from the search bar on Staging, regardless of what terms I search for.

Explore is also broken (no results).

To repro, try searching for e.g. "remix" on Staging. (Repro'd in Chrome & Safari + Mac.)

**Comment by thisandagain** [comment]
Hmm. Something certainly seems to be wrong with staging API endpoints that involve ElasticSearch:
https://api-staging.scratch.mit.edu/explore/projects?limit=16&offset=0&language=en&mode=trending&q=*

**Comment by mewtaylor** [comment]
Fixed! 'Twas but a simple aws issue.
