### ISSUE TITLE
Wrong user icon next to user being promoted notification in What's Happening feed

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1543]
Some users have reported that the promoter's icon is showing up in the feed next to the promotee's name, screenshot provided by @thisandagain.

(I think what may have happened is that @mewtaylor & I caught a bug where the username for promoter showed up instead of promotee before deploy, but did not notice that the fix for that fixed the text only & not the icon.)

<img width="393" alt="screen shot 2017-09-13 at 2 07 02 pm" src="https://user-images.githubusercontent.com/1320456/30393061-d7e663ac-988c-11e7-9503-795c2d856ae4.png">

**Comment by Kenny2github** [comment]
Yes, I noticed that too! I saw the "ceebee was promoted" thing and noticed that it was Lifay's pic!

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-www/pull/1541
