### ISSUE TITLE
Display "Load more" button on New Messages page when filter is applied and there are more messages

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1546]
When a user does not have a filter on the kind of activity being displayed, then Load More will load more messages as long as there are messages to load. If there are no messages to load, the button will not be displayed (which is good).
However, if the user applies a filter, and there are no activities of that type in the amount of total messages that have been loaded on the page, then the page will display no messages, and will not display the Load More button. If there are more messages for that user, the Load More button should still be displayed.

This issue + https://github.com/LLK/scratch-www/issues/1499 together would account for the following situation:
- A user goes to their messages page
- The first N messages are loaded on the page
- The user switches the filter to Project Activity
- There are no project activity notifications in the first N messages
- Currently, the page displays no messages and no Load More button, but it should display the Load More button - then the user would click Load More
- The next N messages would be fetched, but only those matching the filter would be displayed on the page
- If there are no project activity notifications in the 2nd N batch of messages, then this would lead to the user seeing the same blank/ no messages page, and having to click Load More again (which is not obvious); this is where https://github.com/LLK/scratch-www/issues/1499 comes in, since instead the loading state could display (e.g. a spinning load symbol) to indicate that the Load More button click had worked.

I'm not totally sure what UX would be clear, but what we have now could definitely be made clearer. /cc @carljbowman (discussed in person with @mewtaylor)

As reported (with helpful screenshots!) in https://scratch.mit.edu/discuss/topic/276228/.

**Comment by mewtaylor** [comment]
@carljbowman @thisandagain one other way we could handle this state is to selectively only display filters in the dropdown that are relevant to the user – i.e. if they have no forum activity, don't display that as an option in the dropdown. Any thoughts?

**Comment by thisandagain** [comment]
@mewtaylor @carljbowman I think I'd be ok to backlog this for now as it doesn't feel like a critical user pathway (I wish I had analytics to confirm / refute this though 😉 ).
