### ISSUE TITLE
Release Offline Editor for PT-BR

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1548]
### Description
We are testing out a way to package tips content with the offline editor for languages other than English. For this first test, we would like to publish an offline editor build for Brazilian Portuguese before the Scratch Conference in São Paulo on October 5th. Because of this deadline all work must be completed by September 20th in order to hit the freeze / release cycle.

### Scope
- [x] Resolve remaining issues with PT-BR assets ( @leoburd )
    - [x] Resolve improperly scaled images
      - Example: https://cdn.scratch.mit.edu/scratchr2/static/help/pt-br/blocks/move-steps.html
    - [x] Resolve issues with improperly translated strings (many of these are due to LLK/scratchr2#4765)
      - Example: https://cdn.scratch.mit.edu/scratchr2/static/help/pt-br/howto/get-started-6.html
    - [ ] Resolve "blurry" animations **omitting for now**
      - Example: https://cdn.scratch.mit.edu/scratchr2/static/help/pt-br/howto/pgametip10.html
      - Compare to: https://cdn.scratch.mit.edu/scratchr2/static/help/en/howto/pgametip10.html
- [ ] Generate PT-BR offline editor build ( @cwillisf )
- [ ] Get final PT-BR offline editor download links ( @cwillisf )
    - [ ] Windows
    - [ ] MacOS
- [x] Update download links in the `/download` view for the `pt-br` locale ( @chrisgarrity )

**Comment by towerofnix** [comment]
It might be nice if the Download page displayed that the offline editor is "also available in other languages"? (That's certainly not a blocker, though.)

**Comment by cwillisf** [comment]
Updated with examples of each class of issue

**Comment by cwillisf** [comment]
@towerofnix I think that's a good idea once we get past this test phase -- that is, once we have >2 languages ;)

**Comment by leoburd** [comment]
Would it be possible to also generate a version of the offline editor for Linux? Most places in Brazil use either Windows or Linux boxes.

**Comment by cwillisf** [comment]
@leoburd: the normal build process for the offline editor generates 3 builds: one for Windows, one for Mac, and one "cross-platform" build that can be used on older Mac machines, Linux, and other systems.

The cross-platform build is missing some features, though, such as hardware-accelerated graphics effects and hardware extensions. It's also a bit of a pain to run on Linux, since you need to install a very old version of Adobe AIR (version 2.6) -- that's the last version of AIR that Adobe ever shipped for Linux.

Anyway, it'll be there if people want to use it :)

**Comment by chrisgarrity** [comment]
PR for download links update based on a conversation that ChrisWF and I had yesterday: https://github.com/LLK/scratch-www/pull/1558

**Comment by thisandagain** [comment]
PR for updating image sizes: https://github.com/LLK/scratchr2/pull/4835

**Comment by leoburd** [comment]
Hello all, just to give an update.

We finished translating and reviewing the new strings.

We have just resized the Tips Window images and submitted a pull request (see above).

We won't have time to work on the blurry animations for this release. I think that should be ok for now.

Assuming that the translations and the images are acceptable, please feel free to move forward with the build.

Let me know if you have any questions or concerns, ok?

Thanks,

Leo
