### ISSUE TITLE
Text on homepage cut off in Spanish.

### ISSUE THREAD

**Issue by VutonDesign** [LLK/scratch-www#1556]
When your language is set to Spanish, A piece of text on the homepage gets cut off making it spell "Scratc" as highlighted below:

![capture](https://user-images.githubusercontent.com/26391179/30554359-33b19374-9c9c-11e7-8e8a-767d5af663c4.JPG)

**Comment by WorldLanguages** [comment]
Duplicate: #1198

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-www/issues/1198
