### ISSUE TITLE
step by step tutorials are german in the online version, but english in the offline version

### ISSUE THREAD

**Issue by JohannaJacob** [LLK/scratch-www#1557]
there is a german translated version of the step by step tutorial inside the scratch editor

the strange thing is that it is only translated in the online version. the offline version still contains the english version

use the online version and switch the language to "Deutsch" --> have a look at the step by step tutorial
use the offline version and switch the language to "Deutsch" --> have a look at the step by step tutorial

we can't recall if and when the offline version had a translated tutorial

**Comment by thisandagain** [comment]
We do not currently have a way to package languages other than english with the Offline Editor but are planning on addressing this limitation in Scratch 3.0.
