### ISSUE TITLE
Messages page not loading on first click of navbar icon - Staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1561]
When I click the messages icon in the navbar to view the Messages page, I am seeing a blank page first (errors from console below). If I click the icon again, the page reloads with the Messages (Chrome 60, Staging, Mac OS El Capitan). /cc @mewtaylor 

I am not seeing this issue on Production.

<img width="1280" alt="screen shot 2017-09-20 at 11 44 09 am" src="https://user-images.githubusercontent.com/1320456/30653453-1f6ff6d6-9df9-11e7-995c-a707a72d955f.png">
<img width="1179" alt="screen shot 2017-09-20 at 11 43 44 am" src="https://user-images.githubusercontent.com/1320456/30653456-1f781e38-9df9-11e7-84c1-e34d2272716e.png">
<img width="671" alt="screen shot 2017-09-20 at 11 47 42 am" src="https://user-images.githubusercontent.com/1320456/30653617-8ce9e0aa-9df9-11e7-9678-2d111c1861b0.png">
<img width="668" alt="screen shot 2017-09-20 at 11 47 34 am" src="https://user-images.githubusercontent.com/1320456/30653618-8cf1a574-9df9-11e7-88e6-817a322b9e9b.png">
<img width="1278" alt="screen shot 2017-09-20 at 11 44 04 am" src="https://user-images.githubusercontent.com/1320456/30653648-a1ec0820-9df9-11e7-816c-8a8cd56b43b7.png">

**Comment by mewtaylor** [comment]
hmm I'm unable to repro this @jwzimmer – are you still seeing it? I'm wondering if there was a caching issue when I first merged some PR

**Comment by jwzimmer** [comment]
I am still seeing this, unfortunately.

Here's exactly what I'm doing:
- Staging, Chrome 60.0.3112.101, Mac OS El Capitan
- Sign in as the Staging smoke test user (in shared-scratch-dev) from the homepage navbar
- Click the messages icon in the homepage navbar
- View messages page (don't do anything else)
- Open JS console

<img width="1279" alt="screen shot 2017-09-27 at 9 34 59 am" src="https://user-images.githubusercontent.com/1320456/30916376-40ace264-a367-11e7-91f3-09b232165b0b.png">
<img width="1277" alt="screen shot 2017-09-27 at 9 34 47 am" src="https://user-images.githubusercontent.com/1320456/30916377-40b1955c-a367-11e7-8bed-30c7f62d3ad5.png">
<img width="1276" alt="screen shot 2017-09-27 at 9 34 26 am" src="https://user-images.githubusercontent.com/1320456/30916378-40b2902e-a367-11e7-89fa-964890e054b9.png">

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/commit/d272a2e4e6fad500066bed519696da494b5724e1
