### ISSUE TITLE
In "(user) is now following you" message rows, (user) should be a highlighted link

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#1563]
Here's what my messages inbox looks like:

!["Minty-And-Fresh is now following you"](https://user-images.githubusercontent.com/9948030/30742351-13585a60-9f6f-11e7-910e-d1716b96756b.png)

Note that links to forum topics are highlighted ("Snap! Team development discussion, vol. 2" is highlighted, for example), but links to users just following you aren't ("Minty-And-Fresh" isn't highlighted). So it's not as obvious that I can click on the username to see who followed me, and it's less likely for me to notice the message at all, because it doesn't have a contrasting link in it.

**Comment by towerofnix** [comment]
Ah, yep, sorry for forgetting!

I'm running Firefox 52.3.0 on Debian Testing.

I took a look at the new messages page on different browsers and systems (Safari on macOS and iOS), and saw some interesting results:

* On Safari (iOS/macOS), profile links are bolded, and "focus" links are bolded and blue.
* On Firefox (Debian), *NO* links are bolded. Focus links are blue (but not bolded).

It looks like Firefox (Debian) displays `font-weight: 500` the same as `font-weight: 300` (while other browsers display 500 as more bolded).

**Comment by towerofnix** [comment]
The default font (no `font-family` set) does not display `500` differently:

![No font-family set](https://user-images.githubusercontent.com/9948030/30819325-c1cdac58-a1f4-11e7-982a-feb232d1727e.png)

The font `sans-serif` *does* display `500` differently:

![font-family: sans-serif](https://user-images.githubusercontent.com/9948030/30819363-da0b72fa-a1f4-11e7-8a44-04ab3c932a5f.png)

The font `Arial` does not display `500` differently:

![font-family: Arial](https://user-images.githubusercontent.com/9948030/30819444-0fcb813c-a1f5-11e7-9cd2-94ac6d72bb6a.png)

The font `Helvetica` does not display `500` differently:

![font-family: Helvetica](https://user-images.githubusercontent.com/9948030/30819406-f5a2a524-a1f4-11e7-91f8-6505bc982e9d.png)

The font `Helvetica Neue` is not installed.

This means that the font `Helvetica` is being used, and on my system (Firefox / Debian Testing), Helvetica is not displayed as bold with font weight 500.

**Comment by mewtaylor** [comment]
@towerofnix awesome, this is super helpful :).

**Comment by DeleteThisAcount** [comment]
Seems to happen with any name on the messages page.

**Comment by Kenny2github** [comment]
![link](http://i.cubeupload.com/fK7NuI.png)
Another screenshot taken on a Mac OS X Chrome 46 (old I know but I'm on a school pc)

**Comment by mewtaylor** [comment]
@rschamp @thisandagain I propose we close this in favor of #1630.

**Comment by towerofnix** [comment]
Closing per #1630.
