### ISSUE TITLE
Resolve issues with building repo using Node 6+

### ISSUE THREAD

**Issue by asanari** [LLK/scratch-www#1564]
Will not install or build for that matter, latest node and NPM on AWS Ubuntu 16.04

(http://prntscr.com/gols31)

**Comment by thisandagain** [comment]
Hi @hostwolf. Please try using Node 4 with the `scratch-www` repo. Sorry for the inconvenience.

**Comment by hostwolf** [comment]
Success, I will look into this and get back to you with whatever I can find out.

**Comment by Kenny2github** [comment]
Let me quickly chime in here that this explains why testing was so difficult for my PRs - I was using the wrong Node version! I'll try to see what the problem is as well :D

**Comment by mewtaylor** [comment]
@asanari are you still experiencing this issue at all? I was just able to re-build on `develop` with node 8, which should have been fixed in #1671

**Comment by mewtaylor** [comment]
@asanari I'm going to close this for now since I haven't heard back from you – please feel free to re-open if you are still experiencing any trouble now that we've updated our compatibility with node 8!
