### ISSUE TITLE
Profile picture on comments messages being not clickable

### ISSUE THREAD

**Issue by WorldLanguages** [LLK/scratch-www#1566]
Right now, the commenter's username is clickable, but not the profile picture:

![image](https://user-images.githubusercontent.com/17484114/30775763-9c9fc798-a070-11e7-9037-3ab3d1f24798.png)

This is a sort of inconsistency, because in profile comments the profile picture **is** clickable.

Should it be clickable or not?

**Comment by TheGrits** [comment]
@WorldLanguages I think it'd be cool if you could click the icon to navigate to the user's profile page!

**Comment by VutonDesign** [comment]
@WorldLanguages I don't know if it's meant to do that however I think it would be cool!

**Comment by WorldLanguages** [comment]
Yeah, I agree on it redirecting to the user's profile page.

**Comment by VutonDesign** [comment]
I know this isn't the suggestions forum but...
**+1** 👍

**Comment by thisandagain** [comment]
This seems reasonable to me. I'd be open to accepting a PR that makes the profile image clickable.

**Comment by VutonDesign** [comment]
@thisandagain I'll give it a go, Can't say from sure if I'll get it to work though :rofl:

**Comment by GreenBayRules** [comment]
This should fix it: https://github.com/LLK/scratch-www/pull/1576

**Comment by mewtaylor** [comment]
On Chrome 61, OSX 10.12 on staging:
* On messages page, I can click a user's avatar and it takes me to their profile
* On messages page, I can click a user's username and it takes me to their profile

Marking this as `qa-ok`
