### ISSUE TITLE
Messages - Handle user-generated text overflow & sanitization

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1568]
Diacritics such as "zalgo text" can overflow various notifications on the messages page. 

![image](https://user-images.githubusercontent.com/747641/30811792-36f867a2-a1d7-11e7-8212-cb4967f98ba2.png)

**Comment by Kenny2github** [comment]
I'd say make the speech bubble set to `overflow:hidden`?

**Comment by towerofnix** [comment]
Also consider that RTL override characters used to make the messages page look weird. (This isn't a problem on the new Messages page, but it's still worth thinking about when migrating other pages which contain user-generated text.)

**Comment by WorldLanguages** [comment]
@Kenny2github This isn't just for the speech bubble, but for every custom text a user can choose (invite to studio called x, new activity in studio/topic x, etc)

**Comment by Kenny2github** [comment]
Interestingly enough, according to that screenshot, the text goes *behind* notifications that came before it, but *in front* of notifications that came after it.

**Comment by joker314** [comment]
That's probably just z-index @Kenny2github

**Comment by joker314** [comment]
@WorldLanguages Then all of those fields also need `overflow: hidden;`

I guess I should note that sanitization is more complex than "no combining characters" because languages other than English do use diacritics and other combining characters that are needed.
