### ISSUE TITLE
Credits - Add new ST members to credits page

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1572]
I would just make a pull request, but I don't know their names:
quacht
pandatt.

**Comment by thisandagain** [comment]
Details:
- [ ] Add two new ST members to the credits page
- [ ] [Tina Quach](https://scratch.mit.edu/users/quacht)
- [ ] [Tracy Tang](https://scratch.mit.edu/users/pandatt)

**Comment by GreenBayRules** [comment]
okay do you want me to just make a pull request?

**Comment by GreenBayRules** [comment]
I was wrong, tracy tang was already added to the credits page. I will add tina quach, assuming he/she is a moderator.

**Comment by GreenBayRules** [comment]
Here is the pull request: https://github.com/LLK/scratch-www/pull/1573
