### ISSUE TITLE
Messages Page is blank when no one is signed in

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1575]
The messages page is blank when no one is  signed in. Is that supposed to happen? Maybe there could be something saying "Sign in to view messages"?
![image](https://user-images.githubusercontent.com/11379161/30835924-f6fd1c5e-a20f-11e7-9030-4348dce89ad9.png)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-www/issues/1502
