### ISSUE TITLE
Download page doesnt have have full stops/periods

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-www#1583]
On the download page for the offline scratch under steps 1 and 2 there are no full stops at the end of the sentences. 
![nofullstops](https://user-images.githubusercontent.com/29336855/31044311-3aee9788-a5cd-11e7-8ceb-a5af7cbdc82b.PNG)
This may or may not be in other languages. Haven't checked yet. I did make a pull request to fix this in english.

**Comment by DeleteThisAcount** [comment]
https://github.com/LLK/scratch-www/pull/1582

**Comment by GreenBayRules** [comment]
I don't think periods are needed for that area, and it looks better without periods, but thats just my opinion.
