### ISSUE TITLE
Make Navigation Bar consistent

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1584]
![image](https://user-images.githubusercontent.com/11379161/31050489-549d6af0-a600-11e7-80bf-340a23a98073.png)
I think the other pages should match the home page style of nav bar.

Also I think that the hover background of the "Join scratch" looks weird. The other nav bars have a dark blue hover background whereas the hover background of "Join Scratch" is orange. 

I think that these will make the nav bar more consistant, and if you guys approve this and add the "help-wanted" tag, I will be happy to submit a pull request.

**Comment by Kenny2github** [comment]
The other pages have the old style because they're not migrated to this repository yet - i.e. anything with the new navbar is in this repo. Anything with the old one is in scratchr2.

**Comment by GreenBayRules** [comment]
Oh okay, that makes sense :D
