### ISSUE TITLE
Migrate 404 page?

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-www#1585]
I think the 404 page should be migrated to this new www.

Why?

Unfortunately many people land on the 404 page. I think maybe we could change the 404 page to make it the new style.

**Comment by thisandagain** [comment]
Because of the way we route between the old and new sides of the Scratch website any page not handled by the new site "falls through" to our legacy systems. This means that the 404 is likely to be the last thing we migrate.

**Comment by Torotv** [comment]
Oh, I thought that.

**Comment by DeleteThisAcount** [comment]
Oh
