### ISSUE TITLE
String ( it's free ) lacks translation markup

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-www#1588]
I have searched all projects on Transifex for the string "free", but I could not find an entry for "( it's free )".

![scratch-free](https://user-images.githubusercontent.com/4095570/31142945-0d26ba0e-a87c-11e7-81ac-e54332b51787.PNG)

**Comment by thisandagain** [comment]
@chrisgarrity Any thoughts?

**Comment by TheGrits** [comment]
@chrisgarrity @thisandagain I'll tackle this one right now!

**Comment by TheGrits** [comment]
@thisandagain Is the preferred place to add such a string in the main l10n.json file or should I make a new file specifically for this component?

**Comment by mewtaylor** [comment]
@TheGrits the other strings that have the id `intro.<name>` are in `splash/l10n.json` since the intro component only appears on the splash page – I think putting it there makes sense!

**Comment by TheGrits** [comment]
@mewtaylor Cool, thanks!
