### ISSUE TITLE
Should 'oops' be capitalized?

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1593]
Issue noted from a translator:

From https://github.com/LLK/scratch-www/blob/161f50611c492b6f874bf7ab3bc7485c74a1abaa/src/views/messages/l10n.json#L29

Should the 'oops!' be capitalized?

**Comment by TheGrits** [comment]
@mewtaylor oops, maybe it should be! 😜

**Comment by VutonDesign** [comment]
@mewtaylor I generally find that it is capitalized, So I guess that should be changed.

**Comment by towerofnix** [comment]
Relatedly to this string, there should probably also be a period at the end of it?

**Comment by VutonDesign** [comment]
@towerofnix Good catch 👍

**Comment by thisandagain** [comment]
@chrisgarrity That's a good catch. Agreed that "Oops!" should be capitalized.
