### ISSUE TITLE
"may not" is misspelled in the Terms of Use

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1595]
In the Terms of Use, section 5.4, it says

>Unless you are licensed by Scratch under a specific licensing program or agreement, you many not use these logos to label, promote, or endorse any product or service. 

"many not" should be "may not" here.

I'll make a pull for this if it's help-wanted.

**Comment by TheGrits** [comment]
Oh wow, I probably introduced that typo somehow. Good catch @Kenny2github!

**Comment by GreenBayRules** [comment]
I'll implement this if the "help-wanted" tag is put on.

**Comment by thisandagain** [comment]
Oh geeze. Good catch @Kenny2github
