### ISSUE TITLE
Add hyphens to the community moderator page.

### ISSUE THREAD

**Issue by VutonDesign** [LLK/scratch-www#1596]
On the community moderator job page, A sentence needs a hyphen added to it.
 
For example...
>Active participation in online communities, forums, or other webbased media.

Should be...
> Active participation in online communities, forums, or other web-based media
----

I'd be happy to implement this if it becomes ```help-wanted```.

**Comment by Kenny2github** [comment]
"webbased" definitely needs hyphenation, but I think "interest driven" can remain the way it is.

**Comment by VutonDesign** [comment]
@Kenny2github Okay

**Comment by thisandagain** [comment]
Agreed that "webbased" should be "web-based".

**Comment by VutonDesign** [comment]
@thisandagain Yeah, I'll send in a pr now that it's ```help-wanted```.
