### ISSUE TITLE
Statistics Comma problem

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1600]
![image](https://user-images.githubusercontent.com/11379161/31317384-d424df02-abf4-11e7-8093-de5dc1c4c100.png)
On the statistics page, "Community Statistics at a Glance" has commas separating the stats, and "Website traffic last month" does not. I think it looks better without commas, but either way the statistics have to be consistent. If the help-wanted comes up, and if I can know which looks better, commas/or no commas, I will be happy to create a pull request.

**Comment by thisandagain** [comment]
This page is still in our legacy system. This would be good to resolve when we migrate it to `scratch-www`.

**Comment by GreenBayRules** [comment]
Oh okay

**Comment by Kenny2github** [comment]
Any target date for that happening yet?
