### ISSUE TITLE
FAQ quotation mistake

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1601]
![image](https://user-images.githubusercontent.com/11379161/31317431-ee4f2ca6-abf5-11e7-9fb0-c31d9ca6da19.png)
The period should be outside of the quotation marks.

**Comment by thisandagain** [comment]
👍

**Comment by GreenBayRules** [comment]
I'll do this.

**Comment by GreenBayRules** [comment]
There is the PR
