### ISSUE TITLE
More FAQ Grammar/Quotation issues

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1604]
![image](https://user-images.githubusercontent.com/11379161/31317824-c88f4fd0-abfc-11e7-8f0e-50e2f9d8beb9.png)
Period should be outside of quotation marks.
![image](https://user-images.githubusercontent.com/11379161/31317826-dc3efa1c-abfc-11e7-9129-cebd488e754c.png)
Should be hyphen between left and hand.
![image](https://user-images.githubusercontent.com/11379161/31317831-fdb51c3a-abfc-11e7-8b83-96c566d0c171.png)
This last one I just think should be changed to: I forgot my password: How can I reset it? or I forgot my password. How can I reset it?

I can make a pr if this gets help-wanted.

**Comment by thisandagain** [comment]
- [ ] Period should be outside of quotation marks in the "How do I add a cloud variable when I'm making a project?" section
- [ ] Change "I forgot my password, how can I reset it?" to "I forgot my password. How can I reset it?"

I disagree re: "left hand" vs "left-hand". That is a stylistic preference and not incorrect.

**Comment by VutonDesign** [comment]
The first 2 seem good, But I think the third one can stay the way it is.

**Comment by GreenBayRules** [comment]
Okay I will send pr now

**Comment by GreenBayRules** [comment]
Done PR ^
