### ISSUE TITLE
Block blends in with footer

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1606]
![image](https://user-images.githubusercontent.com/11379161/31318003-cbc3d790-abff-11e7-9ee2-4875c89f5b3e.png)
I'm not sure if this a problem, but I want to report it anyways just in case.

The last block of the Tips page blends in with the footer, I'm not sure if it was made that way on purpose, but maybe if the colors were different, then it would be easier to tell the difference between the footer and last block

**Comment by VutonDesign** [comment]
@GreenBayRules I think this was done on purpose, But I'll leave it to the ST to give the correct answer.

**Comment by GreenBayRules** [comment]
Yeah thats what I thought too, but maybe there should be like a horizontal line separating the  two

**Comment by VutonDesign** [comment]
@GreenBayRules Hmm, Maybe...

**Comment by thisandagain** [comment]
This is by design as the hierarchy of these items is roughly equivalent to the footer.
