### ISSUE TITLE
"through Github" is not consistent. 

### ISSUE THREAD

**Issue by VutonDesign** [LLK/scratch-www#1607]
A couple of weeks ago, I made a pr which added "through Github" to the Scratch-www section of the developer's page. I was looking at that page again and noticed something...

![capture](https://user-images.githubusercontent.com/26391179/31317997-c3a09e70-ac42-11e7-808e-5e17a0693f19.JPG)
As you can see above, the Scratch-www section does have "through Github" but the ScratchJr section does not. I think this should be made consistent as both sections have the same formatting.

----

I can take this if it becomes ```help-wanted```.

**Comment by thisandagain** [comment]
I think the current copy is fine. I'd rather not make copy changes unless they are clearly incorrect.

**Comment by VutonDesign** [comment]
Okay 👍
