### ISSUE TITLE
Teacher Account FAQ grammar issues

### ISSUE THREAD

**Issue by VutonDesign** [LLK/scratch-www#1608]
I've found some grammar issues on the teacher account FAQ page that I would be happy to work on.

> Are teacher accounts integrated with Google Classroom or any other classroom managment service?

Should be...

>Are teacher accounts integrated with Google Classroom or any other classroom management service?

----
> As a teacher, you can see all of your students activity and perform light moderation actions within your class.

Should be 

> As a teacher, you can see all of your students' activity and perform light moderation actions within your class.

**Comment by GreenBayRules** [comment]
Agreed with first.

For second, shouldn't it be students', since its a plural possessive noun?

**Comment by VutonDesign** [comment]
@GreenBayRules That's a good point, I'll fix that.

**Comment by thisandagain** [comment]
Looks good! Thanks @vutondesign

**Comment by GreenBayRules** [comment]
Made a pull request

**Comment by VutonDesign** [comment]
@GreenBayRules You beat me to it! 😆
