### ISSUE TITLE
Design - Initial state should be "blank"

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-www#161]
OS: windows 7
Browser: ie 11
server staging

1. Login to homepage
2. navigate to about
3. navigate to homepage

Observed: you will momentarily see the nav bar when you are logged out. You will see "sign in" as well as home page not logged in mode.

I think this is confusing to users. Should the right nav bar be blank while it fetches the login credentials to show we are in the process of fetching? It will be less confusing to users. Maybe make page blank while loading?

In Production , the behavior has the search bar covering the right part of the nav bar so we don't see signin or the page loads before the homepage is ready .and whats happening shows a spinning progress wheel

**Comment by TheGrits** [comment]
If the initial state of the project count number should not be an arbitrary large number, what should it be? "Fetching..."?

**Comment by liam4** [comment]
Perhaps "a lot of projects"? /s

Maybe make it fade in when the number of projects is loaded?

**Comment by TheGrits** [comment]
@liam4 Why make it fade when the number is loaded? Wouldn't you want it to be faded while it is loading, and normal when it is loaded?

**Comment by liam4** [comment]
I mean to make it invisible when it's downloading the project count, and to show with a fade effect when it's loaded.

**Comment by thisandagain** [comment]
Tracking the project count issue in #357

**Comment by mewtaylor** [comment]
Project count and carousel are currently handled, and #395 and #396 handle the other two initial state designs that we need currently – closing this one since it's being tracked in separate issues elsewhere.
