### ISSUE TITLE
Missing comma on the editor download page

### ISSUE THREAD

**Issue by VutonDesign** [LLK/scratch-www#1610]
**After looking at the offline editor download page, I noticed a punctuation mistake...**

This sentence...
![capture](https://user-images.githubusercontent.com/26391179/31352060-3ea2e00a-ad25-11e7-97bd-cca8ed6dc327.JPG)

Should have a comma in it...
![capture - copy](https://user-images.githubusercontent.com/26391179/31352030-274e4db8-ad25-11e7-830f-2231490d4375.JPG)

----

**Comment by GreenBayRules** [comment]
I don't think this is that big of a deal, it looks better without a comma

**Comment by thisandagain** [comment]
I think I'd prefer to keep this as is.
