### ISSUE TITLE
Credits: Add New ST member 

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1612]
@GulpTea needs to be added to the credits (I'm not sure if this is too early to add them to credits, I mean they literally joined 4 days ago).
If this gets help-wanted, I can do this.

**Comment by thisandagain** [comment]
@dietbacon can you please confirm which new ST accounts need to be added to the moderators section of the credits page?

**Comment by dietbacon** [comment]
Add:

Joel Gritter (@gulptea)
Carolina Kaufman (@lkaufm)

Move to "Previous MIT Scratch Team Members" section:

Connor Hudson
Lily Kim
Tauntaun Kim
Hanako Tjia

**Comment by thisandagain** [comment]
Great. Adding `help-wanted` label for implementation.

**Comment by VutonDesign** [comment]
@GreenBayRules Will I tackle this or leave it for @GreenBayRules?

**Comment by VutonDesign** [comment]
Nice, I can work on this since @GreenBayRules is away.

**Comment by GreenBayRules** [comment]
Here, let me try submitting another pull request for this, maybe it will pass then.
