### ISSUE TITLE
FAQ should say "Email" not "Email Settings"

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1614]
The FAQ about confirming email address includes:
```
Once logged in, click on your username in the top right and select "Account Settings", then "Email Settings" on the left hand side. 
```

The actual text in the left hand side is just "Email"

Pointed out by @gunchleoc in translations

**Comment by thisandagain** [comment]
@GreenBayRules @Kenny2github In the future please comment on the issue you are going to work on before starting work and submitting a PR to avoid issues of duplicate effort.

**Comment by GreenBayRules** [comment]
Okay.

**Comment by towerofnix** [comment]
> issues of duplicate effort

Literally duplicate efforts.. they're the same diff :)

**Comment by GreenBayRules** [comment]
XD
