### ISSUE TITLE
Remove My Stuff link from dropdown menu.

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-www#1619]
Remove the my stuff link from the acount drop down menu.
Why?
There's a link to it as an icon next to it so there's no purpose for it

**Comment by GreenBayRules** [comment]
Hmm... But for new scratchers they might not know that the icon means My Stuff.

**Comment by WorldLanguages** [comment]
Why don't you ask in the Suggestions forum first? 🤔 I think most Scratchers would be confused.
