### ISSUE TITLE
Discuss footer not aligning properly when posting

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1621]
![image](https://user-images.githubusercontent.com/11379161/31576611-1fa3b2d8-b0b3-11e7-9db2-32309bf2df9d.png)
In the discussion forums, when you go to post, the "Standard|Mobile" part becomes misaligned.

**Comment by Kenny2github** [comment]
What browser/OS are you using? This looks like a very specific problem.

**Comment by VutonDesign** [comment]
@Kenny2github It does, I'm not getting it 
![capture](https://user-images.githubusercontent.com/26391179/31583846-0fc61df0-b19a-11e7-8b04-5976d69b67a5.JPG)

Windows 8.1, Chrome 61.0.3163.100 (Official Build)

**Comment by GreenBayRules** [comment]
Windows 10, Latest chrome.

**Comment by Kenny2github** [comment]
Interesting, I can now repro this on Raspbian, latest Chromium:
![2017-10-16-103412_998x217_scrot](https://user-images.githubusercontent.com/28599280/31592846-9a9fd8e4-b25d-11e7-8d0f-0107930315e0.png)
It looks like it only happens when you can close the topic.

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4859
