### ISSUE TITLE
Credits: add new ST member

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1623]
@quachtina96 (Scratch username @quacht) needs to be added to the credits.

IIRC they've been an ST member for a while but just recently got a Scratch account?

I'd be happy to implement this if it's `help-wanted`.

**Comment by VutonDesign** [comment]
@Kenny2github I think this was already fixed in #1574

**Comment by mewtaylor** [comment]
Thanks @VutonDesign and @Kenny2github – it was indeed implemented in that PR!

**Comment by Kenny2github** [comment]
Oh right, it's just that develop hasn't been merged into master. Whoops!
