### ISSUE TITLE
Numbered font-weights don't work on all browsers

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#1630]
We've seen this a couple of times, most recently in #1563 – on some OS's (Debian, most recently), using numbered font weights does not result in bold text being generated on the screen. We should consider how we might want to adjust our typography settings to accommodate this limitation.

**Comment by TheGrits** [comment]
@mewtaylor I've noticed this on ChromeOS quite a while ago...

**Comment by carljbowman** [comment]
Closing this issue as it should have been fixed by this https://github.com/LLK/scratch-www/pull/1970
