### ISSUE TITLE
npm run build failed with 'make is not recognized' on Win10

### ISSUE THREAD

**Issue by lcyhjx** [LLK/scratch-www#1632]
Hi,

I clone the latest code, and I can run 'npm install' successfully , but when I run 'npm run build' / 'npm start', it will failed with ''make' is not recognized as an internal or external command'.  My operation system is win10. Does anyone know what the issue is and how can I fix it?

**Comment by lcyhjx** [comment]
It is addressed.  Use following command to install make
npm install make -g
then it works.

The error message misdirect me. I search it,  most feedback is to install make for windows.  But that is not the solution.

**Comment by thisandagain** [comment]
You can use [cygwin](http://www.cygwin.com/) or [https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux](WSL)  to resolve issues with missing command line tools that are needed for developing `scratch-www`.
