### ISSUE TITLE
Scratch Conference 2018 Website Phase 1

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-www#1633]
Theme: The Next Generation
URL: https://scratch.mit.edu/conference
Launch Date: Early December

Goal: Announce the theme, dates for the 2017 Scratch Conference, when registration opens, registration cost, and invite submissions (via Google Form) for sessions. 

Design: Re-use design from previous year

Copy link (still being finalized) : https://docs.google.com/document/d/1oJGcmMnyTkp5C6d1l6lhi_ies9HmsyZBjZk_mhtGTcw/edit?ts=59f09c88

**Comment by thisandagain** [comment]
### Details / To Do List
- [ ] Minimally modify existing page to include some copy plus link to Google Form for submissions
- [ ] Change "Email Us" link in the footer to point to `conference@scratch.mit.edu`

**Comment by Kenny2github** [comment]
That Google Drive link can't be accessed, is that deliberate?

**Comment by TheGrits** [comment]
@Kenny2github It's probably stored on the LLK drive, so it's only accessible to LLK staff by default.

**Comment by Kenny2github** [comment]
yeah - I'm asking if keeping it that way was deliberate

**Comment by TheGrits** [comment]
@Kenny2github More likely than not, yes.

**Comment by me-win** [comment]
The site copy is finalized at this doc: https://docs.google.com/a/scratchfoundation.org/document/d/1oJGcmMnyTkp5C6d1l6lhi_ies9HmsyZBjZk_mhtGTcw/edit?usp=sharing

Please keep the banner image the same.

**Comment by chrisgarrity** [comment]
@Kenny2github @TheGrits details are in the issue now if you're interested. If it gets done quickly we'll still release it this month

**Comment by GreenBayRules** [comment]
I can do this :D

**Comment by GreenBayRules** [comment]
#1673 Should fix it
