### ISSUE TITLE
Strings not marked for translation

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1634]
The `Projects` header on the Developers page:
https://github.com/LLK/scratch-www/blob/18f82fce3ffecd366168740ed827392eb88a66cc/src/views/developers/developers.jsx#L67

The paragraph about ScratchJr:
https://github.com/LLK/scratch-www/blob/18f82fce3ffecd366168740ed827392eb88a66cc/src/views/developers/developers.jsx#L97

**Comment by Kenny2github** [comment]
Looks like @TheGrits is onto this :)
