### ISSUE TITLE
Studio Curators Username text overflow

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1635]
![image](https://user-images.githubusercontent.com/11379161/32079874-7c8879d6-ba61-11e7-95ca-cee704c9c550.png)
You can see this on the bottom of this studio: https://scratch.mit.edu/studios/4387260/curators/

The user @BASICALLY_EVERYTHING's username is too large and is going outside of the box. I guess a solution for this could be to make it so that every username with more than x characters would have a "..." following their name.

**Comment by towerofnix** [comment]
> I guess a solution for this could be to make it so that every username with more than x characters would have a "..." following their name.

Or just use the CSS <code><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow">text-overflow:</a> ellipsis;</code> property - but I don't know if it's supported on every Scratch target browsers.

**Comment by GreenBayRules** [comment]
@thisandagain what do you think?

**Comment by thisandagain** [comment]
This is in our legacy system. Will address when we port this page to 3.0.
