### ISSUE TITLE
Feature request from teachers: More control over student accounts

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1640]
From https://scratch.mit.edu/discuss/topic/251689/ by Scratch teacher MrNealon101 :
>I realized after the fact that a teacher of a class account cannot delete student accounts. This defeats the purpose of having a class account for many reasons:
>1) Students drop/move out of the class and needs to be removed.
>2) Students post inappropriate content which includes usernames, comments, projects. 
>3) Students don't follow instructions with setting up their account and as a result they create accounts that the teacher cannot properly identify.
>4) Students create multiple accounts.
>5) Students bullying other classmates.
>
>Greater control of the class needs to be given to the teacher who is also the administrator. Perhaps this was an oversight with the MIT team, until additional safeguards are added, I cannot move forward with using Scratch with my class. There are way too many lapses for potential issues with school administrators, parents and students.
>In addition, with the shift in educational technology moving towards more online learning management systems such as Moodle, Google Classroom. Migrating Scratch to use existing accounts like Google, Facebook would greatly simplify the registration process. Students don't have to register and create an additional username/password.

**Comment by jwzimmer** [comment]
Hi @Kenny2github, thanks for bringing this up. We are mainly tracking teacher-account-related issues & feature requests in our scratchr2 repo, so I will move this there.
