### ISSUE TITLE
Add Malay Language

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1642]
The high priority strings have been translated to Malay

**Comment by redmangospros** [comment]
I Can Do This.

**Comment by LiFaytheGoblin** [comment]
@chrisgarrity Basically same question as in the other issue: Does Malay only have to be added to the language menu or is there something else to do?

**Comment by chrisgarrity** [comment]
@LiFaytheGoblin it looks like this was already taken care of (Bahasa Melayu is already in the language menus). So I'm closing the issues.
