### ISSUE TITLE
Offline editor download page: add "helper tool" issue to known issues list

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-www#1644]
On some macOS installations, this dialog pops up when starting the offline editor:
<img alt="screen shot 2017-10-10 at 9 14 45 am" src="https://user-images.githubusercontent.com/1320456/31388286-902c2fe6-ad9b-11e7-9910-f33c5fcbb826.png">

Due to Scratch 3.0 work it looks like it'll be a while before we have time to investigate this, so I think it makes sense to mention it in the "known issues" section of the offline editor download page.

Suggested wording:
> On a Mac you may see a prompt indicating that "Scratch 2 is trying to install a new helper tool" and asking for your user name and password. We are investigating.

**Comment by GreenBayRules** [comment]
I'll do this as well. :D

**Comment by GreenBayRules** [comment]
The above pull request should fix this and #1645
