### ISSUE TITLE
Offline editor download page: "Adobe Air" should be "Adobe AIR"

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-www#1645]
The download page capitalizes "Adobe AIR" inconsistently: in some places it's "Adobe Air" and in others it's correct. They should all say "Adobe AIR"

I also think we should update the "Note for Mac Users" as follows:
- **Old:** the latest version of Scratch 2.0 Offline requires Adobe Air 20. To upgrade to Adobe Air 20 manually, go [here](https://get.adobe.com/air/).
- **Suggested:** the latest version of Scratch 2.0 Offline requires Adobe AIR 20 or newer. To upgrade Adobe AIR manually, go [here](https://get.adobe.com/air/).

**Comment by GreenBayRules** [comment]
I'll do this one :D

**Comment by GreenBayRules** [comment]
Done #1646
