### ISSUE TITLE
Edit Scratch Conf Website - Correct Info for Costa Rica Conf

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-www#1649]
Please update the following details for the listing for Scratch Conference Costa Rica (on scratch.mit.edu/conference): 

* Change the date from “November 10, 2017 - November 12, 2017” to “November 12, 2017” 

* Change the text on the orange button to read “Visit Website”

* Link the button to https://scratchcostarica.com/

**Comment by GreenBayRules** [comment]
I can do this :D
