### ISSUE TITLE
/forums/viewpost.php still redirects to archive.scratch.mit.edu instead of scratcharchive.asun.co

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1651]
### Expected behavior
https://scratch.mit.edu/forums/viewpost.php should redirect to https://scratcharchive.asun.co/forums/viewtopic.php
### Actual behavior
It attempts to redirect to https://archive.scratch.mit.edu/forums/viewpost.php instead - but that domain is gone, so it's a DNS error.
### Steps to reproduce
Isn't it obvious?

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4874

**Comment by Kenny2github** [comment]
Yeah, I thought it'd be moved.
