### ISSUE TITLE
Messages page unread messages not being highlighted

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1652]
This is Staging-only, the highlighting is working on Production. This issue was repro'd in Chrome, Safari, and Firefox on Mac OS El Capitan.

I expect unread messages to be highlighted blue on the Messages page, but currently no messages are being highlighted (other than Messages from the Scratch Team).

To repro, sign in to a staging user such as abcdefky or abcdefky_s1, generate a new notification for them, then go to their Messages page.

<img width="1034" alt="screen shot 2017-11-03 at 9 49 30 am" src="https://user-images.githubusercontent.com/1320456/32376963-ad1bd5a4-c07c-11e7-920f-28dc3723aa06.png">

**Comment by mewtaylor** [comment]
Fixed in #1653
