### ISSUE TITLE
Pink Background Issue

### ISSUE THREAD

**Issue by RedMAngo22** [LLK/scratch-www#1655]
When You Remove A Background or Touch It, Sometimes The Project Goes Pink.
/cc @GreenBayRules 
/cc @thisandagain

**Comment by towerofnix** [comment]
This is a bug in Scratch 2.0. You should report bugs with the player [in the scratch-flash repository](https://github.com/LLK/scratch-flash/). However, there may already be a report for this particular bug - LLK/scratch-flash#135 looks related. And you should note that [Scratch 2.0 is now in maintenance mode:](https://github.com/LLK/scratch-flash/#readme)

> Note: Scratch 2.0 is now in maintenance mode while the team focuses efforts on Scratch 3.0. While critical issues will be addressed please note that any feature requests or minor issues will not be reviewed until the next major release.

This is likely not a critical issue, considering the bug report for it is in the "backlog" milestone and that it is so rare (it's only happened to me once or twice). Also, this is certainly not a bug in the Scratch *3.0* paint editor, which is currently where a significant amount of focus is being put; so, likely, the "fix" for this will be Scratch 3.0, which will never have had the bug in the first place.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-flash/issues/135

**Comment by GreenBayRules** [comment]
Please don't mention me, if not necessary
