### ISSUE TITLE
Messages number showing wrong on pages with new navbar

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1656]
This is on any page without the new navbar (You might have to click on the picture, to see the Messages number better)
![image](https://user-images.githubusercontent.com/11379161/32406104-74bca932-c12f-11e7-8781-1cbbb3016392.png)
This is on any page with the new navbar
![image](https://user-images.githubusercontent.com/11379161/32406106-86153ea6-c12f-11e7-9217-2d59db944460.png)
![image](https://user-images.githubusercontent.com/11379161/32406112-a6a5d7fc-c12f-11e7-887f-0a532d5cf0f3.png)
![image](https://user-images.githubusercontent.com/11379161/32406115-b733165c-c12f-11e7-95fd-8baa3684a886.png)
Using this, I can know what my real message number is (Note: I gained one message before making this screenshot):
![image](https://user-images.githubusercontent.com/11379161/32406149-259ca86a-c130-11e7-9590-1281a75d2a4b.png)

As you can see, any page with the new navbar does not show the messages number correctly.

**Comment by GreenBayRules** [comment]
Of course, this is probably only happening when a user has a high message count, so like if a user has 1 message, it still shows the same on both navbars.

**Comment by GreenBayRules** [comment]
EDIT: When i check my messages:
![image](https://user-images.githubusercontent.com/11379161/32406237-0df5548a-c132-11e7-8c15-824f3691274e.png)
has wrong one still

**Comment by mewtaylor** [comment]
@GreenBayRules – thanks for reporting this! I actually think that it's likely an issue with the message count on the legacy parts of the site. I'm going to move this issue to our legacy repo for now so we can track it there – I'll make sure to update you when we figure out what's up!

Tracking in https://github.com/LLK/scratchr2/issues/4877
