### ISSUE TITLE
Can shortcut URLs go to the specific PDFs instead of the cards overview page? 

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#1657]
Right now the shortcuts for each set of cards is pointing to the overview cards page instead of the specific PDFs. For example, [https://scratch.mit.edu/name/cards] is going to [https://scratch.mit.edu/cards]. 

Is this so that people can get the translations of the cards? 
If so, is there anyway for the shortcuts to link instead to the specific cards PDF in the current language?

For example, for
[https://scratch.mit.edu/pong/cards]  to go to
[https://resources.scratch.mit.edu/www/cards/en/pongCards.pdf]
and similarly if the browser is set to Portuguese Brazilian then going to the pt-br/pongCards resource

**Comment by chrisgarrity** [comment]
@ntlrsk yes, these are redirecting to the main cards page so people can get to translations. The problem is that these shortcuts are in the legacy system currently and are redirecting to the legacy cards page.

**Comment by chrisgarrity** [comment]
Correction: the redirect is to the new (www) cards page, but the shortcuts are defined in the legacy system.

**Comment by chrisgarrity** [comment]
We should revisit these links when the redirects are moved into www.

**Comment by ntlrsk** [comment]
@chrisgarrity Should we delete the /cards page and just redirect to /ideas (when that launches)?

**Comment by ntlrsk** [comment]
Closing this as translated materials will be accessible by the /ideas page.
