### ISSUE TITLE
Credit Page Bug?

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#1659]
I noticed today that Linda's avatar on the [credits page](https://scratch.mit.edu/info/credits/) is not loading, leaving this image instead:

![image](https://user-images.githubusercontent.com/11506947/32454786-40ee749e-c2ee-11e7-84f1-fa09be1c343a.png)

It should be linking to the avatar from her profile: https://scratch.mit.edu/users/lifaythegoblin/

- - - - - 
macOS Sierra Version 10.12.3
Chrome Version 61.0.3163.100

**Comment by TheGrits** [comment]
I'll look into this.

**Comment by TheGrits** [comment]
Found the issue and the fix, I'll make a pull request right now.

**Comment by mewtaylor** [comment]
This appeared to be a caching issue, and was fixed after I purged the endpoint.

**Comment by TheGrits** [comment]
@mewtaylor I noticed that the images for the credits page are using two different url patterns. (cdn and cdn2) Should we be moving all of the urls over to cdn2?
