### ISSUE TITLE
Switch text on hoc top banner based on logged in state

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1664]
If user is logged in, keep 'Animate a Name'

If not logged in change to 'Get Started with Coding!'

Make the whole animation link to the Animate a Name tutorial when clicked.

**Comment by chrisgarrity** [comment]
@ChampikaF @ntlrsk the changes are live on staging if you want to check them.

**Comment by ntlrsk** [comment]
The change in wording from logged out to logged in looks great to me.

**Comment by ChampikaF** [comment]
Looks great! Thanks!

**Comment by chrisgarrity** [comment]
resolved in https://github.com/LLK/scratch-www/pull/1654
