### ISSUE TITLE
translation Error //

### ISSUE THREAD

**Issue by redmangospros** [LLK/scratch-www#1665]
![sqsqsq](https://user-images.githubusercontent.com/21000033/32693341-518ebfea-c6f7-11e7-8dd8-a79fd3f4b0d6.png)

**Comment by thisandagain** [comment]
Can you please be more specific? Are you referring to the fact that the strings "Projects" and "Studios" are not translated?

**Comment by GreenBayRules** [comment]
That's weird, because for me, "Projects" and "Studios" are translated. 
![image](https://user-images.githubusercontent.com/11379161/32694849-08aeb1aa-c700-11e7-999d-8958953cbb81.png)

**Comment by redmangospros** [comment]
Yes, Same Thing packers.

**Comment by redmangospros** [comment]
The Launge is on english, and it is showing a differnt launge.

**Comment by redmangospros** [comment]
@thisandagain

**Comment by GreenBayRules** [comment]
No, I didn't have the same issue. I said that I DON'T have that issue :P

**Comment by redmangospros** [comment]
Firefox Does Have the same issue, because it doesn't have Les Utilisateurs what means users in english.
The TRanslation is in french.

**Comment by redmangospros** [comment]
console.clear() was prevented due to 'Preserve log'

**Comment by GreenBayRules** [comment]
I feel like your just using inspect element and google translate to try and confuse us lol

**Comment by redmangospros** [comment]
no.

**Comment by redmangospros** [comment]
@thisandagain

**Comment by VutonDesign** [comment]
@redmangospros We don't actually have a user search tab meaning you must be using a browser extension or inspect element.

If the above is the case, then it's not an issue on the ST's side.

**Comment by thisandagain** [comment]
@redmangospros Can you please disable whatever browser extension or userscript you are using to have "Users" in the search bar and then try again? I cannot replicate the issue you are seeing.

**Comment by redmangospros** [comment]
I Have no extestion installted!
