### ISSUE TITLE
Update llk link on developers page

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#1668]
The link on the developers page should no longer be `https://llk.media.mit.edu` and should instead be `https://www.media.mit.edu/groups/lifelong-kindergarten/overview/`

See:
> Scratch is a project of the Lifelong Kindergarten Group at the MIT Media Lab. You can learn more about Scratch here.

**Comment by VutonDesign** [comment]
I'll take this 👍

**Comment by colbygk** [comment]
Thank you @VutonDesign

**Comment by VutonDesign** [comment]
No problem 😉
