### ISSUE TITLE
Post Learning Resource Designer on /jobs page

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-www#1674]
url: scratch.mit.edu/jobs

request:

Add "Learning Resource Designer, MIT Media Lab, Cambridge, MA" to list of jobs
Link: https://www.media.mit.edu/about/job-opportunities/learning-resources/

**Comment by GreenBayRules** [comment]
I can do this :D

**Comment by GreenBayRules** [comment]
#1676 Done :D

**Comment by GreenBayRules** [comment]
Should be closed since #1676 was merged..

**Comment by thisandagain** [comment]
Resolved in #1676
