### ISSUE TITLE
Update localization guide to include info on FormattedHTMLMessage workarounds

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#1677]
React-Intl has started to deprecate `FormattedHTMLMessage`, highly recommending that people switch to using `FormattedMessage`, and simply passing values into the component that contain any necessary html in them – see [here](https://github.com/yahoo/react-intl/wiki/API#formathtmlmessage).

We should update the wiki to include this in our style guide, and show workarounds for how contributors can avoid using `FormattedHTMLMessage` when adding localized strings to a page.

**Comment by chrisgarrity** [comment]
@mewtaylor updated wiki section: https://github.com/LLK/scratch-www/wiki/Localization-Guide#removing-formattedhtmlmessage

**Comment by mewtaylor** [comment]
@chrisgarrity looks awesome thanks!
