### ISSUE TITLE
The "Scratch" logo on the `/conference` page should take you back to `/`

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#1680]
Currently the "Scratch" logo in the top left corner of the `/conference` page takes you back to `/conference`. Because of this, it is difficult to navigate back to the main Scratch website without needing to manually edit the address in your browser. This may make sense when we have a larger set of resources / pages available for conference, but for now it is quite confusing / frustrating. This link should be altered to match the header throughout the rest of the site and link to `/`.

**Comment by GreenBayRules** [comment]
I got this :D

**Comment by GreenBayRules** [comment]
PR available at #1681
