### ISSUE TITLE
Maybe add a colon to Conference page

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1682]
![image](https://user-images.githubusercontent.com/11379161/33104383-97d3988a-cedc-11e7-9820-ec0b5aa5d68c.png)
Might look better as:
![image](https://user-images.githubusercontent.com/11379161/33104390-a4aebc2e-cedc-11e7-98b8-0d996c9e3923.png)

**Comment by thisandagain** [comment]
I think we are ok with this as-is for now. Thanks for the suggestion!

**Comment by redmangospros** [comment]
+1 With This, Looks Good.
