### ISSUE TITLE
Upgrade to Webpack 3

### ISSUE THREAD

**Issue by as-com** [LLK/scratch-www#1691]
#1684

Webpack 2 introduced native support for ES6 modules with tree shaking, and Webpack 3 introduces support for module concatenation (scope hoisting). This could help with performance on the client side.

Also, it's a whole lot faster than Webpack 1 in build times.

This should be tagged "ergonomics."

**Comment by nbkhope** [comment]
Will it suffice to update the webpack config file and the package.json? If so, I would like to help out.

**Comment by R4356th** [comment]
@benjiwheeler, please consider removing the help wanted tag because it is now misleading since both Greenkeeper and Dependabot have created PRs for this (#2787 and #3931).

**Comment by benjiwheeler** [comment]
Resolved by now; see eg.g https://github.com/LLK/scratch-www/pull/5036
