### ISSUE TITLE
Migrate /research page

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1695]
The page at https://scratch.mit.edu/info/research shows the old header, indicating that it's in `scratchr2`. When (if at all) should it be migrated?

(if this becomes `help-wanted` I'll give it a shot)

If an issue for this has already been opened, I apologize - a quick search didn't show anything relevant.

**Comment by thisandagain** [comment]
Thanks! Please use the template from https://scratch.mit.edu/terms_of_use

**Comment by ntlrsk** [comment]
Thanks for noticing this and offering @Kenny2github !  
@ascii Wondering if it makes sense for me to update the page text before migrating to scratch-www 
If so, I'll take off 'help wanted' for now. Otherwise will ask for help editing after migration.

**Comment by thisandagain** [comment]
@ntlrsk Either way works for me. It should be very easy to update the text after it is migrated. Otherwise if you wanted to drop the updated text into this issue that would be great too. If so, please feel free to drop the "help wanted".

**Comment by Kenny2github** [comment]
@ntlrsk No rush, I'll wait until you (and @thisandagain) come to a decision. I'll start work once a plan of action is clear 😄

**Comment by Kenny2github** [comment]
Friendly ping! I know this is in backlog but I just want to quickly confirm whether there is an ETA on a plan of action for this. :D

**Comment by thisandagain** [comment]
@Kenny2github Go ahead and migrate. We can update the text after it is moved over to this repo. Thanks! 😄 

/cc @ntlrsk

**Comment by Kenny2github** [comment]
@ntlrsk Just letting you know, the page has been migrated so if you want to update the text you can feel free to open another issue
