### ISSUE TITLE
Stock answers to be added

### ISSUE THREAD

**Issue by dietbacon** [LLK/scratch-www#1696]
Some new stock answers we can use.

Project censor menu:

Title: Self harm
Body: We noticed you referenced self-injury in this project. When anything is shared regarding self-injury, we provide resources outside of Scratch that may be valuable. We do this because we don't believe that Scratch is the best place to work out self-injury related issues. If you are feeling intense emotions and need to speak to someone, please talk to an adult that you trust or chat online with a trained counselor at <a href='https://www.imalive.org/'>www.imalive.org</a>. We want to make sure that people dealing with tough things have someone to talk to when they need to.

Title: FNAF project

The Scratch Team has removed this project because it is too violent or scary for the Scratch website. Scratch is for kids ages 8 and up, so it's important that everything shared is appropriate for all ages.

For additional information about projects inspired by the Five Nights at Freddy’s game series, please see https://scratch.mit.edu/discuss/topic/168506/.

Send notification menu:

Title: Bad profile pic
Body: We have removed your profile picture because it was inappropriate for the Scratch website.  Scratch is for kids ages 8 and up, so it's important that this image is appropriate for all ages.

Title: Don’t remix my stuff
Body: Hi there! We noticed that some of your project notes say not to remix, or put restrictions on how users can modify your project. When you share stuff on Scratch, you are giving permission to all Scratchers to reuse any parts of your project in any way they want, as long as they add their own ideas and give you credit. In exchange, you get to reuse any parts of their projects. That's how Scratch is set up — sharing is a big part of it. Please don't share your projects to the site unless you are okay with this and remove any restrictions you may have placed on them.

Ban menu:

Title: Stop respawning, go to appeals
Categorization: in the permanent section, ban type permanent
Subject: Your account has been blocked because it was used to go around a block on another account.  Please login to your main account, read the message about why you were blocked, and contact appeals@scratch.mit.edu if you want to continue using Scratch.

Title: Extending ban for respawning
Categorization: both in 3 days and 1 week with ban lengths set accordingly
Your Scratch account's block time has been extended because you used an alternate account to get around this block.  Please do not create any additional accounts while your account is blocked or this will be extended further.

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4900
