### ISSUE TITLE
Migrate /contact-us/page

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1697]
Pretty much the same thing as kenny's issue, except with /contact-us/ I'd love to try this if the help-wanted tag comes.

**Comment by mewtaylor** [comment]
@GreenBayRules we actually have an issue already set up for this, #308 (it's been backlogged for a while so it's hard to find). It will likely need to be done by a Scratch Team member though, since it is not a static migration (i.e. involves some work on the backend with api too).
