### ISSUE TITLE
Update Scratch About Page - Credits

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-www#1700]
Page: https://scratch.mit.edu/about/
Section: "Support and Funding"

Request:
Update list to include Siegel Family Endowment

Current copy:
The Scratch project has received financial support from the National Science Foundation, Scratch Foundation, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, and MacArthur Foundation.

New copy:
The Scratch project has received financial support from the National Science Foundation, Scratch Foundation, Siegel Family Endowment, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, and MacArthur Foundation.

**Comment by VutonDesign** [comment]
@ChampikaF I'll take this, but I have one question:

Should I keep this part? - ```See the <a href=\"/info/credits\">credits page</a> for more information. If you&#39;d like to support Scratch, please see the Scratch Foundation <a href=\"https://secure.donationpay.org/scratchfoundation/\">donate page</a>, or contact us at <a href=\"mailto:donate@scratch.mit.edu\">donate@scratch.mit.edu</a>.```

**Comment by ChampikaF** [comment]
@VutonDesign  Thanks! Yes please keep that part.

**Comment by VutonDesign** [comment]
@ChampikaF Thanks, Just deleted my message a few seconds before as I had read the issue wrong. 😆

**Comment by chrisgarrity** [comment]
Confirmed with @ChampikaF to change the copy to:
The Scratch project has received financial support from the following organizations: National Science Foundation, Scratch Foundation, Siegel Family Endowment, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, MacArthur Foundation.

This makes translation easier. The string to translate can have a placeholder for the list, and the list doesn't need to be translated.
e.g.
```
"about.supportDescription": "The Scratch project has received financial support from the following organizations: {supporterList}. ...the rest of the text to translate..."
```
