### ISSUE TITLE
Scratch Conference site - small edits 

### ISSUE THREAD

**Issue by me-win** [LLK/scratch-www#1702]
Hi, we're requesting a few small changes to the Scratch Conference site (scratch.mit.edu/conference):

- Replace the header photo on the page with the one attached (cropped to show the four individuals at the top of the photo). ![_dsc4245](https://user-images.githubusercontent.com/33295461/33396975-27196358-d518-11e7-8236-1b7e73b0d914.jpg)
- Add a colon after Scratch Conference 2018 (It should read "Scratch Conference 2018: The Next Generation")
- Decrease the line size/spacing between “Scratch Conference 2018” and  “The Next Generation.” (Currently, the name does not read as the event name.)
- Please add the following line above the Submit Your Proposal button (left aligned): “Deadline for proposals is February 5, 2018.”

Thanks!

**Comment by redmangospros** [comment]
The Colon : Has Been Deind And Been Asked by @GreenBayRules  And Was Denined By @thisandagain

**Comment by thisandagain** [comment]
Thanks @me-win !

**Comment by redmangospros** [comment]
What DO you Need Help on?

**Comment by VutonDesign** [comment]
@redmangospros Fixing the things stated in the first post.

**Comment by thisandagain** [comment]
Adding `help wanted` label to this for all four items.

**Comment by redmangospros** [comment]
Where Is The Source Code For Confrence?

**Comment by VutonDesign** [comment]
The code for the 2018 conference page is at https://github.com/LLK/scratch-www/tree/develop/src/views/conference/2018/index

**Comment by redmangospros** [comment]
I Can Do The SemliColon :

**Comment by redmangospros** [comment]
Is It Right? #1705

**Comment by VutonDesign** [comment]
It’s right, however your meant to try and make all of the requested changes and not just pick one or two of the easy ones.

**Comment by redmangospros** [comment]
Well, I Did One, So anway.
Where It The COde For the img?

**Comment by GreenBayRules** [comment]
I'll go ahead and do this..

**Comment by GreenBayRules** [comment]
I can't find the location of the header image...

**Comment by chrisgarrity** [comment]
@GreenBayRules the header image is defined in the css as a background image: https://github.com/LLK/scratch-www/blob/bfff01f0246288ccad195a551d39cb4d37ed5222/src/views/conference/2018/index/index.scss#L11
You'll need to add the image to the static images for the [conference/index](https://github.com/LLK/scratch-www/tree/develop/static/images/conference/index)  probably by adding a 2018 directory.

**Comment by GreenBayRules** [comment]
Okay thanks chrisgarrity
