### ISSUE TITLE
Scratch 3.0 Preview FAQ Page

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-www#1711]
## Overview
We will need a static page that has FAQ content addressing the Scratch 3.0 preview. Most likely we will use our [FAQ page template](https://scratch.mit.edu/info/faq), so there is no real design work. 

## Content
https://docs.google.com/document/d/1DL9rY8tCUCYvKpfmd9xRSpwzFjuvEzW3TuxkpIHZKWU/edit?usp=sharing

## URL
`scratch.mit.edu/preview-faq`

We will use this URL as a pointer in the [Intro modal](https://github.com/LLK/scratch-gui/issues/828) and the [Unsupported Browser modal(s)](https://github.com/LLK/scratch-gui/issues/982).

**Comment by GreenBayRules** [comment]
Could this by any chance become help-wanted after the content has been decided?

**Comment by thisandagain** [comment]
@GreenBayRules Perhaps! We've got a lot of writing to do first, but I'll let you know once we get further on the content. 😄

**Comment by redmangospros** [comment]
Let Me Know too

**Comment by ChampikaF** [comment]
@carljbowman @thisandagain regarding the url - I like the idea of it living at scratch.mit.edu/info/faq-preview but could we also have a redirect from <preview url>/faq ?

**Comment by thisandagain** [comment]
We already have a (general) FAQ so I'd prefer to not use that URL pattern
for this.

**Comment by ChampikaF** [comment]
oops github didn't parse that correctly... what i was proposing was (preview-url)/faq

**Comment by thisandagain** [comment]
Oh! Of course. No problem. :-)

**Comment by amazinigmech2418** [comment]
Can I please be notified when the content is decided? I really want to help.

**Comment by thisandagain** [comment]
@amazinigmech2418 We are going to handle this ourselves. Thanks for the offer.

**Comment by amazinigmech2418** [comment]
You're welcome! I know you said only you and the rest of the ST are doing it, but if you ever need an easier way to update the page, I have a way to make easy API readers for the page...

**Comment by thisandagain** [comment]
@mewtaylor First draft is ready to go!
https://docs.google.com/document/d/1DL9rY8tCUCYvKpfmd9xRSpwzFjuvEzW3TuxkpIHZKWU/edit?usp=sharing 

(updated original issue description)

**Comment by vutondesign** [comment]
@thisandagain Looks Great! However, there seems to be an unfinished section about ScratchX:

![untitled](https://user-images.githubusercontent.com/26391179/34679276-65563d96-f48d-11e7-83a6-fdb6e95f2957.png)

**Comment by thisandagain** [comment]
@vutondesign Whoops! Good catch. Fixed. 😄

**Comment by towerofnix** [comment]
>New “top” block category

This should be removed; the top category [no longer exists](https://github.com/LLK/scratch-gui/issues/813).

**Comment by thisandagain** [comment]
@towerofnix Another good set of catches! Also fixed! Can you tell I started this document a while ago? 😜

**Comment by GreenBayRules** [comment]
![image](https://user-images.githubusercontent.com/11379161/34685203-79cc5d54-f45c-11e7-9f10-63dd041ff448.png)
Will the Scratch 1.4 editor still be available to download?

**Comment by towerofnix** [comment]
@GreenBayRules Yes:

!["The 1.4 and 2.0 versions of the Scratch Offline Editor will continue to be available."](https://user-images.githubusercontent.com/9948030/34688400-604f0c38-f488-11e7-9bcd-58c6caf832c4.png)

**Comment by thisandagain** [comment]
@GreenBayRules Thanks for the question. I just added some clarity to those lines.

**Comment by amazinigmech2418** [comment]
It says you can't save or share, but you can save using a downloadable JSON format.

**Comment by amazinigmech2418** [comment]
Also, will how will someone be able to test extensions? Developers won't know if it will work if they can't test it.

**Comment by mewtaylor** [comment]
Done in #1761

**Comment by towerofnix** [comment]
Small typo: "I’ve created books, online materials, starter projects based on Scratch 2.0 will I need to update them?" is missing a period (after "2.0"). Should be "..starter projects based on Scratch 2.0. Will I need to update them?"
