### ISSUE TITLE
Feature: Add hover effect to button

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1726]
![image](https://user-images.githubusercontent.com/11379161/33641768-c7f535fe-d9eb-11e7-9c26-18a4b8ea3b0c.png)
I think it would be a nice feature if you guys added a hover effect to the buttons in the Animate your  name popup on the front page

**Comment by GreenBayRules** [comment]
@thisandagain @chrisgarrity What do you guys think?

**Comment by chrisgarrity** [comment]
The popup on the front page is just for CS Ed week (also known as Hour of Code). Those featured banners will be coming down at the end of this week, so it's not worth it right now.
