### ISSUE TITLE
Credits: Add New ST member

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-www#1728]
Please add [my account](https://scratch.mit.edu/users/kittyloaf/) as a new ST member.

**Comment by vutondesign** [comment]
Is this help wanted?

**Comment by vutondesign** [comment]
Perfect, I'll get to this right now. 👍

**Comment by vutondesign** [comment]
@thisandagain @kchadha What name will I use?

**Comment by kchadha** [comment]
Karishma Chadha. Thanks!

**Comment by vutondesign** [comment]
No problem, this should be fixed in #1728.
