### ISSUE TITLE
Full screen blurs sprites

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1742]
### Expected behavior
Full screen should show sprites with the same sharpness (especially vector sprites like the Scratch Cat).

### Actual behavior
If you look closely, in full screen the Scratch Cat is blurred.

### Steps to Reproduce

1. Open https://llk.github.io/scratch-gui/develop (since full screen hasn't been pushed into master yet)
2. Look at the Scratch Cat
3. Go into full screen
4. Look at the cat again - it's bigger, but blurred

### Operating System and Browser

Probably irrelevant

**Comment by vutondesign** [comment]
I'm guessing you meant to open this in scratch-gui instead of here.

Anyway, It's a duplicate of LLK/scratch-gui#1041 which is being tracked in LLK/scratch-render#24.

**Comment by Kenny2github** [comment]
WHOOP, yeah, I meant to open it in scratch-gui. Thanks for finding the dupe!
