### ISSUE TITLE
Idea to improve extension policy

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-www#1747]
People have been very upset about the policy. I have some code in my fork of this that can improve the policy by blocking advertising only for dangerous extensions.

### Steps to Reproduce

The policy is always running. To test the extension, use the console to temporarily add the forked version to the site.

### Operating System and Browser

This isn't needed for this issue.

**Comment by redmangospros** [comment]
:D

**Comment by GreenBayRules** [comment]
@mewtaylor Maybe add the needs-discussion tag?

**Comment by amazinigmech2418** [comment]
The code in my fork is now updated! It now fits all requirements by the bot named Travis!

**Comment by mewtaylor** [comment]
@amazinigmech2418 thank you for the suggestion. However, we cannot explore adding something like this to the site.

The [original announcement](https://scratch.mit.edu/discuss/topic/284272/?page=1#post-2907564) on the extension advertisement policy still applies here – the risks still outweigh the benefits. Only looking for "dangerous" extensions in advertisements still allows for advertising of new extensions that have not yet been seen – or changes to existing extensions that we're not made aware of – which means there would still be risks to Scratchers.

Please let me know if you have any other questions!

**Comment by amazinigmech2418** [comment]
@mewtaylor This automatically updates the code so dangerous extensions can be blocked even if they were safe before. Also, new extensions could just be added via api pages that it then uses to read the data into the arrays. It could be a new moderator tool.  Changes to extensions will automatically be read by the blocker.

**Comment by mewtaylor** [comment]
@amazinigmech2418 Thanks for clarifying your proposal! The idea is interesting – however, we still are not going to be exploring it as an alternative to the policy. As you alluded to, the proposal still requires manual moderation and monitoring even with this type of automation. Consequently, having the policy we do is still important because it sets expectations moving forward for the community, which is also a helpful tool.

**Comment by amazinigmech2418** [comment]
Thank you for responding. I actually just came up with an even better idea! Scratch scripts! They would be like userscripts, but would be checked for malicious code by scratch. There could be many Scratch scripts to replace the safe extensions. They would also have less control over the browser too and would only be able to post API, run some JavaScript, and run Scratch extensions. They would also have key detection blocked and posts to the computer blocked as well as all get requests so no malicious code could be used. Also, intervals and location would be blocked.

**Comment by redmangospros** [comment]
Cool

**Comment by amazinigmech2418** [comment]
@redmangospros Thank you! It will basically be code attachments to Scratch that will be able to improve website experience.
