### ISSUE TITLE
Add Abkhaz to the languages menu

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1751]
For some reason Abkhaz is in the scratchr2 pages, but not on www. It's mostly translated, and I was contacted by one of the translators to ask why.

**Comment by LiFaytheGoblin** [comment]
@chrisgarrity Does this just need to be added to the actual menu in the footer or is there any other stuff that needs to be done?

**Comment by chrisgarrity** [comment]
@LiFaytheGoblin it should just get added to the menu - it was already added to scratchr2, but somehow the footer on www was missed.
