### ISSUE TITLE
Full stop is part of the email link on the developer's page

### ISSUE THREAD

**Issue by vutondesign** [LLK/scratch-www#1752]
An answer to an FAQ on the developer's page has one of the scratch contact emails, however, the link to it seems to include the full stop instead of that being normal text.

![2](https://user-images.githubusercontent.com/26391179/34539224-954247a8-f0c7-11e7-857d-695d701f4de6.png)
![untitled](https://user-images.githubusercontent.com/26391179/34539229-97bdfc70-f0c7-11e7-8a48-f917505c365f.png)

### Operating System and Browser
MacOS High Sierra (10.13.2), Chrome 63.0.3239.108

**Comment by thisandagain** [comment]
@vutondesign Weird. Good catch! 😄

**Comment by Kenny2github** [comment]
In case it's not obvious, I've taken this.

**Comment by amazinigmech2418** [comment]
Wow! You're very observant @vutondesign .

**Comment by vutondesign** [comment]
@amazinigmech2418 I seem to just stumble across this type of bug randomly. 😆

**Comment by Kenny2github** [comment]
@thisandagain perhaps add the "has-patch" label? ;)
