### ISSUE TITLE
Junior Designer job posting should be updated

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#1753]
Clicking "Junior Designer" on https://scratch.mit.edu/jobs leads to a 404 at https://www.media.mit.edu/about/job-opportunities/junior-web-designer-scratch/

It should be updated to read simply "Designer" and lead to this URL https://www.media.mit.edu/about/job-opportunities/web-designer-scratch/

/cc @thisandagain

**Comment by redmangospros** [comment]
I got this!

**Comment by rschamp** [comment]
Oops sorry about this, this is already fixed on the develop branch. We just need to deploy it to the site.

**Comment by amazinigmech2418** [comment]
OK.

**Comment by redmangospros** [comment]
Ok

**Comment by redmangospros** [comment]
ok
