### ISSUE TITLE
Idea for Scratch Scripts (will need discussion)

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-www#1755]
It's kind of tedious to make a scratch extension have to reload every time a project loads. Also, people have made other Scratch add-ons that can't be done anymore other than through bookmarklets which are tedious to run. I have the code in my fork (replaced extensionblocker with it).

### Steps to Reproduce

It always is tedious to do those things

### Operating System and Browser

Windows 10 withs some version of Chrome

**Comment by redmangospros** [comment]
Please explain more @amazinigmech2418

**Comment by amazinigmech2418** [comment]
@mewtaylor @Kenny2github @thisandagain Can you please view this to see if it would work?

**Comment by amazinigmech2418** [comment]
@redmangospros See my fork. It has the code. It is basically a mini version of browser extensions, but they are safe and only run on Scratch. It won't break the policy either since you have to upload the extension to Scratch and it has to get checked before it can be used.

**Comment by redmangospros** [comment]
:D

**Comment by thisandagain** [comment]
Hi @amazinigmech2418 we would need more information to thoroughly respond to this. At the time we do not have an intention of revising our extension policy. We will reevalutate after the release of Scratch 3.0.

**Comment by amazinigmech2418** [comment]
@thisandagain OK. My idea isn't to revise the policy, but to allow people to code things for Scratch that will always run including Scratch extensions to increase the number of possible blocks.
