### ISSUE TITLE
Idea to improve gh productivity

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-www#1756]
You could make a bot that detects issues that are unread or have certain tags and organize issues and PRs in a way that will make it easier to find issues to respond to and will allow for faster development of Scratch! You can use the code from Mountio GHStatus.

**Comment by thisandagain** [comment]
We use a few bots plus a tool called [CodeTree](https://codetree.com) to help with organizing issues.

**Comment by amazinigmech2418** [comment]
OK.

**Comment by redmangospros** [comment]
@amazinigmech2418 
I won't say That GHstaus that WE made together, Is A Bot

**Comment by amazinigmech2418** [comment]
We? I made all of the code. You just gave me the link to find API pages.

**Comment by redmangospros** [comment]
@amazinigmech2418
