### ISSUE TITLE
Scratch.30

### ISSUE THREAD

**Issue by redmangospros** [LLK/scratch-www#1760]
When Is SCratch 3.0 Beta coming out?

**Comment by thisandagain** [comment]
We are planning on releasing the "Preview Version" this month.

**Comment by redmangospros** [comment]
Do you have to be a scratch user?

**Comment by amazinigmech2418** [comment]
@redmangospros There already is a preview for 3.0 at llk.github.io/scratch-gui/, but I'm guessing for the preview version, you won't have to be a user and it will probably be a downloadable version.
