### ISSUE TITLE
Reduce string duplication in teacher registration

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1764]
The string `Your information will not be displayed publicly, and will be kept confidential and secure` shows up twice in the l10n file, with and without a period at the end.

This causes extra work for translators, and the possibility of inconsistency if it's translated by different people. We should probably replace the two messages `teacherRegistration.orgStepDescription` and `teacherRegistration.addressStepDescription` into one:
```
"teacherRegistration.privacyDescription": "Your information will not be displayed publicly, and will be kept confidential and secure.",
```

**Comment by redmangospros** [comment]
Is this help-wanted?

**Comment by lmahony** [comment]
I can pick up this one. Seems like a good starting point for a first contribution

**Comment by thisandagain** [comment]
@Narulacodes No. I think @LiFaytheGoblin is on this.

**Comment by Narulacodes** [comment]
Okay Thanks, I wanted to help.
Where Is the source code anyways?

**Comment by vutondesign** [comment]
@Narulacodes The line without the period at the end is at:
https://github.com/LLK/scratch-www/blob/ad3189c1642ecf3f3bb7269d1c716865badd6a4e/src/views/teacherregistration/l10n.json#L7

**Comment by Narulacodes** [comment]
Thanks.

**Comment by LiFaytheGoblin** [comment]
Hi, so I made some changes and the npm tests are good, but when I try to test it in the browser I can't get past the first step of the teacher registration, since it can't check whether my username is still available. Does anyone know how I can test my changes in the browser?

**Comment by LiFaytheGoblin** [comment]
@thisandagain ^ maybe you can help me?

**Comment by chrisgarrity** [comment]
@LiFaytheGoblin yes, it's hard to test locally unless you have a local copy of the legacy scratchr2 running. One thing you can do is 'fake' the starting step. On this line change the `0` to the step you want to check. Just make sure you don't check in the faked step number.

**Comment by LiFaytheGoblin** [comment]
Thanks, @chrisgarrity, I'll try that!

**Comment by LiFaytheGoblin** [comment]
Great, I was able to test it :)
