### ISSUE TITLE
Updates to Scratch Day site

### ISSUE THREAD

**Issue by me-win** [LLK/scratch-www#1765]
We need to update the Scratch Day site to go back to the 5-month phase seen here: https://day.scratch.mit.edu/home/2017/march/ (this phase removes the Moments Around the World Twitter module and replaces with the video module) 

* The design of the site will remain the same as the link above, but there are text changes, which can be found here: https://docs.google.com/document/d/1kQ8NfCZaBrltUxe2Qjb-1FmuN7_nEZLJg8HrF8q3iyU/edit?usp=sharing

* Please update the photos in the slideshow to the attached photos. The file names contain the country that each photo is from, which can be used for labeling. 

* The video on the homepage should to be updated to: https://youtu.be/4qY8z4P0G3I
* The video on the "How to Host" page should also be updated to: https://youtu.be/4qY8z4P0G3I

Argentina
![scratchday_argentina](https://user-images.githubusercontent.com/33295461/34896328-6dd10b68-f7b7-11e7-8136-69760bda0912.jpg)

Ecuador
![scratchday_ecuador](https://user-images.githubusercontent.com/33295461/34896329-6e020600-f7b7-11e7-99ad-377c1b241898.jpg)

Gabon
![scratchday_gabon](https://user-images.githubusercontent.com/33295461/34896330-6e09dea2-f7b7-11e7-8f44-f0b838faacca.jpg)

Italy
![scratchday_italy](https://user-images.githubusercontent.com/33295461/34896331-6e1780c0-f7b7-11e7-88c3-2b0eba3934e1.jpg)

Japan
![scratchday_japan](https://user-images.githubusercontent.com/33295461/34896332-6e24f23c-f7b7-11e7-80db-12065b45115f.jpg)

Paraguay
![scratchday_paraguay](https://user-images.githubusercontent.com/33295461/34896333-6e31449c-f7b7-11e7-8c88-ea61ad16518b.jpg)

**Comment by redmangospros** [comment]
I got this!

**Comment by GreenBayRules** [comment]
I can do this if it is help-wanted

**Comment by redmangospros** [comment]
I already said i got this

**Comment by chrisgarrity** [comment]
@redmangospros @GreenBayRules sorry - this is all in a private repo, so it has to be done by a ST member. @me-win I'll move this issue to the scratchday repo :)

**Comment by chrisgarrity** [comment]
Moved to LLK/scratchday#287
