### ISSUE TITLE
Project Page Redesign

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1774]
Move projects from scratchr2 to www, with new Scratch 3.0 editor

**Comment by Narulacodes** [comment]
Will this move projects that are prvite in scratchr2 to www? is what i undeerstand?

**Comment by rschamp** [comment]
@Narulacodes Yes, the project page code which is currently private, will be reimplemented in this repository. This is an umbrella issue to track a huge amount of work required to do that.

**Comment by Narulacodes** [comment]
Ok. Thank U.

**Comment by kyleplo** [comment]
https://thimbleprojects.org/HTTP/kyleplo/312991/

**Comment by RedGuy12** [comment]
isn't this done?

**Comment by rschamp** [comment]
Yup!
