### ISSUE TITLE
[teacher accounts][moderation] Mods should be able to change the name of a class

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#1778]
If a class has a bad name, eg gives away the location of students, a mod should be able to edit it. However, this is currently not possible. 

### Steps to Reproduce

If you are a mod go to a class page (well maybe chose a test class page) and try changing the title. Refresh the page - the old title is back!

### Operating System and Browser

Chrome, Win10

**Comment by amazinigmech2418** [comment]
It seems like maybe it doesn't send the change to the server or that the server doesn't process it.

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4965

**Comment by amazinigmech2418** [comment]
@thisandagain Do you mean https://github.com/LLK/scratch2r/issues/4965 ?

**Comment by amazinigmech2418** [comment]
Nevermind. That doesn't exist either. The repo you said it was moved to doesn't exist. @thisandagain

**Comment by GreenBayRules** [comment]
@amazinigmech2418 The scratchr2 repo is a repo only viewable by members of the scratch team.
