### ISSUE TITLE
About page: broken link

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-www#1780]
On https://scratch.mit.edu/about , find the section on Quotes

![image](https://user-images.githubusercontent.com/3766964/35414856-c00fd262-01f1-11e8-900b-82f69722c90f.png)

the highlighted link leads to the Wiki section on Translating Scratch instead of displaying quotes.  I don't know where the quotes page is, sorry.

**Comment by St19Galla** [comment]
I can take this :)

**Comment by chrisgarrity** [comment]
The correct link is `/info/quotes/`. Thanks
