### ISSUE TITLE
Embedded projects can't run Scratch extensions

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-www#1784]
You should be able to run all Scratch extensions in embedded projects, but based on the console, the needed variables for extensions aren't defined.

### Steps to Reproduce

1. Go to https://scratch.mit.edu/projects/200555817/ since when you make websites with that, it makes a Scratch domain.
2. Download the extension needed.
3. Run the bookmarklet.
4. Start the project.
5. Enter
6. "text" Enter
7. Embed code for a project with a needed extension and enter.
8. "next" Enter
9. Enter
10. "title" Enter
11. Title + Enter
12. "next" Enter
13. Enter
14. Enter
15. Enter
16. "y" Enter
17. Enter
18. Load the needed extension for the project to embed.
19. Open the console and see the error.
20. (optional) Run the project and see it fail.

### Operating System and Browser

Chrome on Windows 10

# Note: 
This is not advertising my project. You can use a longer way with an HTML file and figuring out how to allow Flash in embedded projects. It's just faster and easier to use my project.

**Comment by amazinigmech2418** [comment]
@thisandagain This is a pretty major problem and could limit embedded projects majorly. If someone wanted to make a Picoboard demo in a website with Scratch embedded, the Picoboard extension wouldn't be able to load.

**Comment by thisandagain** [comment]
We won't be adding support for extensions in embed projects for Scratch 2.0. We will review this is a potential implementation feature while implementing project embeds for Scratch 3.0.
