### ISSUE TITLE
News item icons too large on scratch.mit.edu/news

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#179]
The new retina icons for the news items display too large. 
![image](https://cloud.githubusercontent.com/assets/11506947/10739611/d182acda-7bf3-11e5-90fc-af5b236a9517.png)

**Comment by thisandagain** [comment]
@christanbalch Are you still seeing this?

**Comment by christanbalch** [comment]
No, I'm not seeing it anymore @thisandagain (but that is probably because the Scratch News page doesn't really exist at the moment, so I can't really say for sure - https://scratch.mit.edu/news)

**Comment by liam4** [comment]
^^ I know this was an issue last I checked (a couple months ago..), but now the news page is kind of gone.
