### ISSUE TITLE
Section of the privacy policy is slightly misleading. 

### ISSUE THREAD

**Issue by ktrvs** [LLK/scratch-www#1803]
In the User-generated Content section of the privacy policy, a sentence says:

> If you prefer to work on projects in complete privacy, you can use either the Scratch 2 offline editor or Scratch 1.4.

It could lead people to think that the 1.4 editor isn't an offline editor, and it would maybe be better if it said something along the lines of:

> If you prefer to work on projects in complete privacy, you can use either the Scratch 2 or Scratch 1.4 offline editor.

**Comment by apple502j** [comment]
Scratch 1.4 doesn't have an online editor, so we shouldn't call it "Scrstch 1.4 offline editor".

**Comment by ktrvs** [comment]
> Scratch 1.4 doesn't have an online editor, so we shouldn't call it "Scrstch 1.4 offline editor".

But it still is an offline editor, so I don't think that we would need to go into more depth than there already was.
