### ISSUE TITLE
3.0 Preview FAQ > browser support text has faint background color

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1804]
### Steps to Reproduce
- Go to `preview-faq` in Chrome 64.0.3282.119, Mac OS 10.13.2
- Scroll down to "Compatibility" section
- Note that Tablet & Desktop sections have faint lighter backgrounds behind the text
  - The background of the text should appear to be the same grey as the rest of the page

<img width="465" alt="screen shot 2018-02-05 at 12 45 58 pm" src="https://user-images.githubusercontent.com/1320456/35820237-02401d3e-0a73-11e8-9ccb-9a3773314787.png">

### Operating System and Browser

_Chrome 64.0.3282.119, Mac OS 10.13.2_

**Comment by amazinigmech2418** [comment]
You could just remove the background and not define background-color for the elements.

**Comment by LiFaytheGoblin** [comment]
It looks like the page is in a shared google doc which has a css file. The class c11 (as it appears on the website) has a background property which shouldn't be there. Maybe you are using a google add-on or so, where you can just remove the background property?

**Comment by thisandagain** [comment]
Fixed in the upstream doc (may take a few minutes to propagate).
