### ISSUE TITLE
Update Scratch Press link to point to Scratch Foundation Media Kit

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-www#1808]
The "Press" link in the footer at scratch.mit.edu should be updated. We're creating a new Scratch Press page #1449 but in the meantime we can point to the Scratch Foundation Media Kit. 

"Press" currently points to:
https://wiki.scratch.mit.edu/wiki/Scratch_Press

Instead, it should point to:
https://www.scratchfoundation.org/media-kit/

**Comment by thisandagain** [comment]
Wonderful. Thanks @ChampikaF!

**Comment by ChampikaF** [comment]
Looks like this was updated on the new system but not the old. So on pages like the homepage (scratch.mit.edu) the footer link to "press" goes to https://www.scratchfoundation.org/media-kit/ but on project pages or user profile pages like https://scratch.mit.edu/users/-BW-GamerGirl/ the "press" link in the footer still goes to https://en.scratch-wiki.info/wiki/Scratch_in_the_Press. 

Can we update the footer on the old system as well?

**Comment by thisandagain** [comment]
@ChampikaF Can you please open a new issue on `scratchr2`?
