### ISSUE TITLE
2018 Conference - close registration 

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1810]
We will need to remove the `register now` buttons when we're no longer accepting registrations for the conference. This will probably be a hotfix. I'm putting it in the March iteration so that we're ready to hotfix when it's needed.

###Changes:
- [ ] Remove `Register Now` buttons
- [ ] Replace buttons with ???
- [ ] Other changes to FAQ?

@me-win @ChampikaF I'm assigning you to update the copy needed, then you can re-assign to me.

**Comment by Narulacodes** [comment]
If this is help-wanted, I Would love to help out.

**Comment by me-win** [comment]
In the event they we sell out, please:

* Remove Register buttons
* Replace top Register button with the text "Scratch@MIT is sold out!" and underneath "Full event schedule coming soon" 
* Remove the Registration info entirely in the bottom portion and in the top navigation 
* Add the following as the first question in the FAQ portion: 

**The conference is sold out. What can I do?**
Scratch@MIT is sold out and at capacity. Regrettably, we are unable to add any additional guests. Please keep in mind that you must have registered on Eventbrite to attend Scratch@MIT; people who are not registered / do not have a ticket will not be able to attend the conference.

**Comment by chrisgarrity** [comment]
@me-win the plan is to have this ready to go at the end of the month to use when we sell out. Is there any chance that we'll sell out before the end of the month and need it sooner?

**Comment by me-win** [comment]
@chrisgarrity I don't think we'll sell out sooner... we're at about 54 percent tickets sold right now. I'll keep you posted if that changes.

**Comment by chrisgarrity** [comment]
@me-win question about the text in the header. Here's a version using normal text. Is this ok, or do you want it to match the date size/format?:![Screen Shot 2018-03-14 at 4.36.14 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/632c4ea1-0bb6-4c1c-9d24-8dd1221ef010/Screen+Shot+2018-03-14+at+4.36.14+PM.png)

**Comment by me-win** [comment]
@chrisgarrity Can you make "Scratch@MIT is sold out!" match the date size/format? The text underneath is fine with normal text. 

thanks!
