### ISSUE TITLE
2018 Conference: full conference program update

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1811]
Full build out of site with program information for each day.
Content TBD

**Comment by Narulacodes** [comment]
#1812 
Same response as i said in #1812

**Comment by me-win** [comment]
@chrisgarrity The text changes for the full build-out can be found in this Google Doc: https://docs.google.com/document/d/1Qk7BbGClIULhxTgzQm2VQIJRFZ2I1rWq1SRohZbkSe0/edit?usp=sharing

We're still finalizing some of the information (as you can see), but we're working to get all of the information by Friday, April 6. At that time, I'll also attach any logos/photos/graphics that you need.

**Comment by me-win** [comment]
Adding calendar icon and logo image files for the site update.

[2018 Cal icons.zip](https://github.com/LLK/scratch-www/files/1891425/2018.Cal.icons.zip)
[2018 Conf Logos.zip](https://github.com/LLK/scratch-www/files/1891426/2018.Conf.Logos.zip)

**Comment by me-win** [comment]
@shickey Here is the photo of Mres
![mitchelresnick_400](https://user-images.githubusercontent.com/33295461/39546136-59d0f338-4e21-11e8-9280-c892ccab66c4.jpg)

**Comment by shickey** [comment]
@me-win 👍 Perfect, thanks!

**Comment by me-win** [comment]
@shickey attaching the icons for the Scratch Store

![shopify_blue](https://user-images.githubusercontent.com/33295461/39594907-f0ae4c64-4edb-11e8-8ffe-47872fe66ff9.png)
![shopify_hover](https://user-images.githubusercontent.com/33295461/39594908-f0bf7584-4edb-11e8-8704-1db5598b2d18.png)

**Comment by shickey** [comment]
@me-win Thanks! Any chance you can send along just the white icon part (without the color background)?

**Comment by chrisgarrity** [comment]
I added these to the scratchday site recently
https://github.com/LLK/scratchday/blob/master/scratchday/scratchday/static/img/social-icon_sprite.png

I'll try to figure out where I found the icon.

--C


Chris Garrity
chrisg@media.mit.edu
Scratch Team & Clubhouse Village
Lifelong Kindergarten Group | MIT Media Lab

**Comment by shickey** [comment]
All set @chrisgarrity/@me-win on the store icon now. Thanks!
