### ISSUE TITLE
Comments which used up all their characters and cancelled still have a red warning

### ISSUE THREAD

**Issue by joker314** [LLK/scratch-www#1813]
_Describe the problem. Please make sure you can reproduce the bug. It's also
helpful to include screenshots or animated gifs of the problem._

When you're typing a comment (in a studio, project, or profile), a helpful counter shows how many characters you've typed, and how close you are to the limit of 500.

When this counter gets to "0", it's also red. When you press the "Cancel" button to clear the entire comment, the counter is reset to "500", but it's colour isn't reset until you start typing again. It should return to the colour of black straight away. (This is just an issue of style and isn't very important)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described above. The 
more detailed and explicit the steps are the better._

1) Open a profile, project, or studio of your choice
2) Scroll down to the textbox for leaving a comment
3) Notice the counter which says "500" characters left, in black
4) Type in 500 characters worth of comment.
5) Once you've finished, observe the red "0"
6) Press on the "Cancel" button to remove the comment
7) Observe the red "500"

### Operating System and Browser

_Windows 10 Chrome Version 64.0.3282.140 (Official Build) (64-bit)_

**Comment by Narulacodes** [comment]
I can repro this, and get the same promblem, but with chromeos

**Comment by amazinigmech2418** [comment]
This happens all the time...

**Comment by Narulacodes** [comment]
@amazinigmech2418  Yep, Had this 200 times, or more. LOL. anyone counting?

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#4990
