### ISSUE TITLE
Make *.scratch-wiki.info and a few scratch-*.info links clickable

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1817]
In email conversations with the Scratch Team, the wiki team were promised that links to any scratch-wiki.info domain would be clickable. I'm opening this issue here in case it hasn't been opened already in scratchr2.
Current list of wiki domains:
- https://en.scratch-wiki.info
- https://scratch-dach.info
- https://nl.scratch-wiki.info
- https://hu.scrach-wiki.info
- https://scratch-ru.info
- https://scratch-indo.info
- https://ja.scratch-wiki.info
- https://jp.scratch-wiki.info (alias for ja.scratch-wiki.info)
- https://fr.scratch-wiki.info
- https://test.scratch-wiki.info

Considering the pattern, all domains matching the globs \*.scratch-wiki.info should be made clickable. Besides that, the three scratch-*.info domains should also be made clickable.

**Comment by towerofnix** [comment]
>or scratch-*.info should be made blue and clickable.

I don't think that'd be best - somebody could register a site on the domain scratch-viruses.info (or whatever), and that would be automatically clickable. But subdomains (like `*.scratch-wiki.info`) are never usable by anyone other than the owner of the higher domain (i.e. `scratch-wiki.info`), so it's fine to glob that (I think?).

**Comment by ktrvs** [comment]
@towerofnix Yep, I was just about to mention that.

**Comment by Kenny2github** [comment]
@towerofnix then I guess make special exceptions for the three scratch-*.info domains? I'll edit the OP to reflect that.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratchr2/issues/4984
