### ISSUE TITLE
Better validation on account creation fields

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-www#1819]
The admin panel doesn't appear to moderators when we attempt to access this new account

          https://scratch.mit.edu/users/slothbutt2/

so we can't delete / block / send notifications 

It appears that there is something bogus in the account information that is preventing the admin panel from appearing

**Comment by tsjsw** [comment]
Is this to the specific user?

**Comment by Paddle2See** [comment]
That user is an example of invalid age data getting into a newly created account.  It has happened before, if I recall correctly.

**Comment by jwzimmer** [comment]
Tracking in https://github.com/LLK/scratchr2/issues/4989.
