### ISSUE TITLE
Add "Real Name" reminder to Teacher Account flow

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#1824]
Currently in the account creation flow for Teacher Accounts we do not tell Teachers to choose a username that does not include personally identifiable information. This is what the flow currently looks like: 

![image](https://user-images.githubusercontent.com/11506947/36867853-8111827a-1d64-11e8-9d8c-aa5783c1a262.png)

We would like to add the text "**Please do not use any portion of your real name in your username.**" at the top of the page, written in bold. Here is a quick mock-up of what we are thinking:

![image](https://user-images.githubusercontent.com/11506947/36868160-7d6fcc20-1d65-11e8-82b2-5db187687ccd.png)

**Comment by JoelGritter** [comment]
@christanbalch I can do this!
