### ISSUE TITLE
Remove filled listings from `/jobs/`

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1825]
The jobs page at https://scratch.mit.edu/jobs/ includes several openings that have been closed:

- Designer
- Learning Resource Designer
- QA Engineer
- Senior Backend Engineer

The only one that should be left on the page is the Full Stack Engineer

### Steps to Reproduce

Go to https://scratch.mit.edu/jobs/ and note that there are five positions listed.

### Operating System and Browser

_Mac OS 10.13.2, Chrome 64.0.3282.167_

**Comment by Narulacodes** [comment]
If this becomes help-wanted, I can take this. :D 
I always want to help the scratch community

01001000 01100101 01111001 00100001 00100000 01001001 00100000 01110111 01100001 01101110 01110100 00100000 01110100 01101111 00100000 01110101 01101110 00101101 01100010 01101100 01101111 01100011 01101011 01100101 01100100 00100000 01101111 01101110 00100000 01110011 01100011 01110010 01100001 01110100 01100011 01101000 00101110 0001010 01001101 01111001 00100000 01110101 01110011 01100101 01110010 01101110 01100001 01101101 01100101 00100000 01101001 01110011 00100000 01100010 01101100 01110101 01100101 01110000 01100001 01110010 01110010 01101111 01110100 00110001 00111000

**Comment by JoelGritter** [comment]
Since nobody seems to be springing on this issue, I'll take care of it. I expect to make a PR in the next couple of minutes.
