### ISSUE TITLE
Scratch 3.0 Preview FAQ page doesn't work when Google Docs is blocked

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#1829]
The Scratch 3.0 Preview FAQ page (`/preview-faq`) doesn't load its content when the Google Docs domain is blocked. This is particularly a problem in locations where Google Docs is blocked, as is the case in several countries around the world. Chinese Scratch user cyx2015s [noticed this](https://scratch.mit.edu/discuss/post/3021529/).

### Steps to Reproduce

Open the Scratch 3.0 Preview FAQ page - https://scratch.mit.edu/preview-faq - while the Google Docs domain is blocked.

**Comment by thisandagain** [comment]
We'll be moving this off of Google Docs as we get closer to August, but it was important for us to have something easy to edit / manipulate as things are moving so quickly right now.
