### ISSUE TITLE
Add Kazakh (kk) to the language menu

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1834]
The folks from Zerde (zerde.gov.kz) have reviewed/translated all the high priority strings, so it's time to add it to the scratchr2 and www menus as 'қазақ' (I've asked the translators to confirm that's the correct name)

**Comment by LiFaytheGoblin** [comment]
Ah, thanks!

**Comment by LiFaytheGoblin** [comment]
I also didn't notice this went into the April milestone. Will do this now.
