### ISSUE TITLE
Update Preview FAQ to reflect translation set at launch

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-www#1848]
The [Scratch 3.0 Preview FAQ](https://scratch.mit.edu/preview-faq) states "...we plan to support the same range of world languages (with improved support for right-to-left languages)..."

We should update this to reflect the set of languages we're planning to support at launch. 

It would be good to do this prior to posting the Scratch 3.0 announcement blog post since it points to the FAQ.

**Comment by GreenBayRules** [comment]
I can do this if it becomes help wanted

**Comment by GreenBayRules** [comment]
alright I'll do this one.

What exactly should I change?

**Comment by chrisgarrity** [comment]
Strange - I thought I'd added the new text...

In any case here is the new text for the FAQ:
At the launch the editor will be able to support a wide range of world languages (with improved support for right-to-left languages). At a minimum English, Chinese (both China and Taiwan), Dutch, French, German, Italian, Japanese, Korean, Portugese (Brazil), Spanish, and Russian will be supported along with any other languages that have been fully translated by our volunteers. We will continue to add languages as translations are completed. If you can help with translation, please contact **translate@scratch.mit.edu.**

**Comment by chrisgarrity** [comment]
@greenbayrules are you working on this one. If not I'll take it as we need it before the end of the month.

**Comment by GreenBayRules** [comment]
Sorry forgot about this. Will do right now.

**Comment by GreenBayRules** [comment]
@chrisgarrity Actually to do this i would need access to this file: https://docs.google.com/document/d/e/2PACX-1vQZFrpOagYqEwcrBBCplIomiyguPAodIJVnCq9Sr11WDI_aa2b-JtDWak-Aiu-cwWobTXftRMF6wBbd/pub?embedded=true as that is the one that is being loaded into that page.

**Comment by chrisgarrity** [comment]
@GreenBayRules you should be fine updating the preview-faq view: https://github.com/LLK/scratch-www/tree/develop/src/views/preview-faq

The google doc was temporary until we added the page on www.

**Comment by chrisgarrity** [comment]
@GreenBayRules sorry I thought we'd switched this over to a full view. I'll take care of updating the doc.

**Comment by chrisgarrity** [comment]
Fixed by updating the Doc - @BryceLTaylor can you check it looks fine for you, and close if so.
