### ISSUE TITLE
Localize new project page

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1854]
The new project page (preview) will need localization strings. 

- [x] add `l10n.json` to the preview view (internally use `projects.<message>` for the message id
- [x] replace all static strings in preview.jsx with formatMessage etc.
- [x] add preview to the transifex config
- [x] push initial set of strings to transifex

**Comment by LiFaytheGoblin** [comment]
I would be interested in seeing how to make a page translatable, maybe we can talk about this a bit @chrisgarrity

**Comment by chrisgarrity** [comment]
This has been done
