### ISSUE TITLE
Handle view count for new project page

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1858]
Use green flag prop from LLK/scratch-gui#3968 to call end point in LLK/scratch-api#476

**Comment by towerofnix** [comment]
> **If the new count is not over 100,** call the API endpoint to increment view count

Just to clarify, what does this imply? It sounds like it means that, under the new project page, projects would be limited to having 100 views, but I don't understand why that'd be intended.

**Comment by thisandagain** [comment]
Assigning to @rschamp for triage / assignment to Ben (?)

**Comment by joker314** [comment]
As a slightly secondary question, will there be checks made server-side to enforce the 100-view limit, or just client side?

**Comment by colbygk** [comment]
Hi @joker314 and @towerofnix A guiding principle of Scratch is to encourage constructive learning and positive community interactions. Gaming views is a part of the system we have to spend considerable resources on avoiding (in both database transactions and informational storage), and yet, even if we had a perfectly non-game-able system, it makes for a competitive metric that we'd like to avoid leading to negative experiences within the wider community.

**Comment by benjiwheeler** [comment]
Closed by the combination of four PRs, referenced above
