### ISSUE TITLE
Error in projects view

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-www#1866]
_Describe the problem. Please make sure you can reproduce the bug. It's also
helpful to include screenshots or animated gifs of the problem._
I don't know if this is the right place but here:

![image](https://user-images.githubusercontent.com/11379161/39220708-a8a4b00c-47e7-11e8-8116-a4367dab49da.png)
That is speakvisually's profile. Clicking view all leads to this:

![image](https://user-images.githubusercontent.com/11379161/39220720-bc80f6e4-47e7-11e8-93ce-b56bd8dcc201.png)
As you can see the projects order doesn't match up. Also, clicking on the cloud run, leads to this (meaning it is unshared)
![image](https://user-images.githubusercontent.com/11379161/39220730-d0936162-47e7-11e8-8a77-41f7aa8a5170.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described above. The 
more detailed and explicit the steps are the better._
Go to https://scratch.mit.edu/users/speakvisually/
then https://scratch.mit.edu/users/speakvisually/projects/
then to the cloud speed run
### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Ubuntu 16.04 Chrome 65.

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#5058
