### ISSUE TITLE
3.0 Preview - Handle unshared projects

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1873]
- [ ] show unshared project

Depends on https://github.com/LLK/scratch-api/issues/520 , https://github.com/LLK/scratch-api/issues/519

**Comment by thisandagain** [comment]
Assigning to @rschamp for triage / assignment to Ben (?)

**Comment by Narulacodes** [comment]
Is there a idea prototype?

**Comment by thisandagain** [comment]
@colbygk Can you provide a status update on the blocking issues here?

/cc @rschamp @benjiwheeler

**Comment by colbygk** [comment]
The backend work to allow an unshared project to be viewed by the creator of the project landed in  LLK/scratch-api/pull/510 there are some tidying up issues in #520, #519, but they should not be blocking.

**Comment by thisandagain** [comment]
@colbygk Thanks for the clarification. Removing the "blocked" label. @benjiwheeler let us know if you'd like to discuss any more of the details (the description here is pretty vague).

**Comment by benjiwheeler** [comment]
Just noting on this that the features include:
[ ] logged in owner should be able to view their own unshared project
[ ] logged in non-owners should NOT be able to view others' unshared projects
[ ] logged out users should NOT be able to view others' unshared projects

**Comment by rschamp** [comment]
@benjiwheeler all of those are already complete, aren't they? Please reopen if I've misunderstood. The issues linked in the description relating to censored states seem like they should be handled separately from the unshared state.

**Comment by benjiwheeler** [comment]
Reopening because we have not actually addressed unshared project visibility in editor.

As @paulkaplan noted at recent bug hunt:

> You can view unshared projects you do not own when you use the preview/id/editor URL, but you are prevented from seeing those at preview/id

**Comment by benjiwheeler** [comment]
Tentative plan: 

> This should probably be handled in www, which should wait for project metadata before passing the project id in the GUI (or mounting the GUI altogether?). Otherwise every time we asked the editor to load a project it would make a duplicate request to the API for project info.
