### ISSUE TITLE
make translations error

### ISSUE THREAD

**Issue by tygithubs** [LLK/scratch-www#1876]
$ make translations
make i info Invoking translations target
'.' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
make × ERR  ./bin/get-localized-urls localized-urls.json
./bin/build-locales node_modules/scratchr2_translations/www/translations intl
make × ERR  Recipe exited with code %d
(node:12932) UnhandledPromiseRejectionWarning: Error: Recipe exited with code %d
    at ChildProcess.<anonymous> (C:\Users\10554\AppData\Roaming\npm\node_modules\make\src\cli.js:143:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:12932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

How do you solve this problem???

**Comment by tygithubs** [comment]
win10OS  node---v8.11.1  npm---5.6.0  webpack---2.7.0  make --version 0.8.1

**Comment by chrisgarrity** [comment]
@tygithubs from the [scratch-www/README](https://github.com/LLK/scratch-www#windows):

> Windows
Some users have experienced difficulties when trying to get our web client to work on Windows. One solution could be to use Cygwin. If that doesn't work, you might want to use Wubi (Windows XP, Vista, 7) or Wubiuefi (Windows 8 or higher). Wubi(uefi) is a Windows Installer for Ubuntu that allows you to have Ubuntu and Windows on one disk, without the need of an extra partition.

Have you tried cygwin?

**Comment by NikolaySolodukhin** [comment]
Hi, i am using windows 10, node 8.11.1 and  cygwin. Cygwin doesn't help  http://prntscr.com/jhc28p

**Comment by tygithubs** [comment]
I've already used the Cygwin, but "$ make  @translations" Command or error

**Comment by chrisgarrity** [comment]
Could you try using the Windows Subsystem for Linux: https://docs.microsoft.com/en-us/windows/wsl/install-win10

That is what the Scratch Team developers use.
