### ISSUE TITLE
Remove Linux download link from /downloads

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#1880]
We no longer support the offline editor on Linux and the download can not be installed on supported versions of Ubuntu.  We should remove it from the downloads page.

**Comment by towerofnix** [comment]
For reference, how will Linux users be able to run Scratch 2.0 from this point on? I suspect the only way will be by building scratch-flash locally. I believe it makes sense to link to the scratch-flash repository from the downloads page for Linux users; we don't always, but often do have enough know-how to build and use something like scratch-flash, if we know it exists.
