### ISSUE TITLE
Signing in with blank username should not attempt to sign in

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#1883]
Right now, if you attempt to sign in with a blank username it attempts to log in.  Eventually, if you keep trying you will hit the Captcha.  The application should deny logging in without reaching out to the API. 

### Steps to Reproduce

Navigate to the home page while logged out
Click Sign In
Enter a password, but no Username
Click Sign In
Repeat
Eventually you will hit the captcha

### Operating System and Browser

All

**Comment by BryceLTaylor** [comment]
This is basically a duplicate of this issue: https://github.com/LLK/scratchr2/issues/4762
Since that one is on Scratchr2, I'll leave them both for now.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratchr2/issues/4762
