### ISSUE TITLE
scratch-* Wiki links are not clickable

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1884]
In the most recent deploy, `*.scratch-wiki.info` links became clickable. However, there are three special case wikis (the oldest wikis, not including the English wiki) that are not `*.scratch-wiki.info`: `scratch-dach.info`, `scratch-ru.info`, and `scratch-indo.info`. These links should also be made clickable.

EDIT: Note that I'm not asking that all links matching `scratch-*.info` be made clickable! I'm merely asking for the three particular special case Wiki links to be made clickable, too.

### Steps to Reproduce

Visit https://scratch.mit.edu/users/kenny2scratch#comments-45505165

### Operating System and Browser

Windows 7 and 10, Chrome 66

**Comment by LiFaytheGoblin** [comment]
@Kenny2github can we tackle this on the wiki side by actually switching our domains and having redirects eg from scratch-dach.info to de.scratch-wiki.info, it seems like this would make sense to have?

@mtwoll @jacob-g @choco31415 @akhof

**Comment by Kenny2github** [comment]
That would be possible, and in fact there are redirects for those domains. However, they only work at the root path, so a link like https://de.scratch-wiki.info/wiki/Scratch_Wiki 404s while https://de.scratch-wiki.info redirects. Additionally, we should be able to have clickable links to the special domain Wikis anyway, so that we can directly link to them.

**Comment by Kenny2github** [comment]
#latepost
All of the domains have been recently moved (and redirected on *all* paths):
* scratch-dach.info -> de.scratch-wiki.info
* scratch-indo.info -> id.scratch-wiki.info
* scratch-ru.info -> ru.scratch-wiki.info

No more special casing is required. This issue is resolved!
