### ISSUE TITLE
Multiple bugs here, listed in Scratch. More updates later.

### ISSUE THREAD

**Issue by tsjsw** [LLK/scratch-www#1892]
https://scratch.mit.edu/discuss/topic/290843/
https://scratch.mit.edu/discuss/topic/301414/
https://scratch.mit.edu/discuss/topic/301424/
(this one can't always be reproduced)
https://scratch.mit.edu/discuss/topic/301427/
https://scratch.mit.edu/discuss/topic/302024/
https://scratch.mit.edu/discuss/topic/302027/

**Comment by Kenny2github** [comment]
Please open a separate issue for each of these bugs, with a detailed description for each, filling out the issue template.

**Comment by tsjsw** [comment]
So not just to link them?

**Comment by Kenny2github** [comment]
You can add a link to the forum topic in each of the separate issues if it provides more information, but there should be a detailed description on the issue itself.

**Comment by thisandagain** [comment]
As @kenny2github said:
> Please open a separate issue for each of these bugs, with a detailed description for each, filling out the issue template.
