### ISSUE TITLE
Change Links to wiki.scratch.mit.edu

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#1898]
- https://scratch.mit.edu/about/ http://wiki.scratch.mit.edu/wiki/How_to_Translate_Scratch

### Steps to Reproduce

See that page
### Operating System and Browser
Windows 8.1
Chrome 66.0.3359.181

I can help if it's marked as help wanted

**Comment by kerrtrvs** [comment]
@apple502j It does redirect anyway, but yeah, should probably be changed properly.

**Comment by apple502j** [comment]
(To be honest, it should be translated so that foreign people don't have to read English version)

**Comment by joker314** [comment]
Did the above-referenced pull request resolve this? If so, we can close this.

**Comment by apple502j** [comment]
Closed.
