### ISSUE TITLE
Implement saving projects

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1901]
New project page needs:
- [ ] create project (new empty project)
- [ ] remix project existing project
- [ ] create copy of existing project

**Comment by benjiwheeler** [comment]
These should be different issues:

 * create project (new empty project)
 * remix project existing project
 * create copy of existing project

**Comment by benjiwheeler** [comment]
Current plan for this issue: just send sb3 file to project server.

**Comment by rschamp** [comment]
The re-scoped issue was accounted for by https://github.com/LLK/scratch-gui/pull/3021
