### ISSUE TITLE
Move /parents to scratch-www

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#1905]
The page shows the old navigation bar, which means that it's on scratchr2.
Should it be moved?

And it should be translated, but it seems not so far.

### Steps to Reproduce
open https://scratch.mit.edu/parents/

### Operating System and Browser
Windows 8.1
Chrome 66.0.3359.181

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-www/issues/1248. Please check for existing issues before creating a new issue.
