### ISSUE TITLE
Change splash to use 30000000 as a default value of projects

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#1916]
https://github.com/LLK/scratch-www/blob/develop/src/views/splash/splash.jsx#30
We celebrated :tada: 30000000 projects some months ago, but the repo didn't.

### Steps to Reproduce
See the code - but note that it's only used when API died so you can seldom see it.

### Operating System and Browser
(Do you care it?)

Windows 7 Homepremium 64bit firefox 60.0.2

**Comment by GreenBayRules** [comment]
Just wondering what does that project count do, in the site

**Comment by apple502j** [comment]
@GreenBayRules
The screen at the left when logged out I think

**Comment by apple502j** [comment]
merged!
