### ISSUE TITLE
Should people commit package-lock.json after running npm install?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#1917]
After running `npm install`, I was prompted with:

> npm notice created a lockfile as package-lock.json. You should commit this file.

I know this is to some degree a matter of developer preference. IMHO the bias should be towards committing semver-related lockfiles, but I don't know if that has any particular issues in node-world that make it problematic?

In any case, since this message seems to appear with more recent npm versions, the README should advise the newly installing contributor/user what to do.

To reproduce: clone the repo locally; you may need to `sudo npm install -g npm`, I ran into this with npm v6.1.0 .

**Comment by thisandagain** [comment]
There are a bunch of challenges with the `package-lock.json` file, but we are currently in the process of moving everything over to using them once we sort out some of the remaining issues. You'll see this and other repos (particularly Scratch 3.0) start to transition soon.
