### ISSUE TITLE
git occur error when build scratch-www

### ISSUE THREAD

**Issue by cugliang** [LLK/scratch-www#1926]
When i build the code by the command:npm run build,there are some errors like:
NODE_OPTIONS=--max_old_space_size=8000 ./node_modules/.bin/webpack --bail
Error: Command failed: git log -1 --format=%H
fatal: your current branch 'master' does not have any commits yet

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
make[1]: *** [webpack] Error 1

make: *** [build] Error 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! www@1.0.0 build: `make build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the www@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I use  git version 2.17.0.windows.1 and npm 6.1.0.
I am not familiar with nodejs,but i think it cant submit code with git when i build it,maybe there is a bug,do anyone know what's going on?

**Comment by cugliang** [comment]
I know the reason of this problem,and i changed some code in web.config.js.
Now it can be built,but for the version of nodejs is higher than 4.4,so there is a new problem.
It shows that,
Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (64)
Now I uninstall the node-sass,all are built successfully with nodejs(V10.3).

**Comment by cugliang** [comment]
I consider that changing of web.config.js cant effect the splash,but i get the warning.I dont know how to solve it,has anyone know?
this is the message of warning in browser console.

Warning: Failed prop type: Invalid prop `news` of type `array` supplied to `SplashPresentation`, expected `object`.
    in SplashPresentation (created by InjectIntl(SplashPresentation))
    in InjectIntl(SplashPresentation) (created by Splash)
    in Splash (created by Connect(Splash))
    in Connect(Splash)
    in div (created by Page)
    in div (created by Page)
    in ErrorBoundary (created by Page)
    in Page
    in IntlProvider
    in Provider

**Comment by thisandagain** [comment]
Hi @cugliang. Could use please try building with Windows Subsystem for Linux? We do not officially support Windows as a development environment for this repo.

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by cugliang** [comment]
#@thisandagain 
I try to find the reason of SplashPresentation refer to my last issue,but I will give up for I am not familiar with scratch-www.
I browse the page in chrome and firefox,also in microsoft edge,it only can show feature projects and feature studios and others,but not join scratch and sign in in top bar,some message showes there:
Invalid prop news of type array supplied to SplashPresentation, expected object.
in SplashPresentation (created by InjectIntl(SplashPresentation))
in InjectIntl(SplashPresentation) (created by Splash)
in Splash (created by Connect(Splash))
in Connect(Splash)
in div (created by Page)
in div (created by Page)
in ErrorBoundary (created by Page)
in Page
in IntlProvider
in Provider

But,in one browser as internet explorer,it can show join scratch and sign in in top bar,but cant show real data of feature projects and feature studios,but test data with the title project.

**Comment by thisandagain** [comment]
@cugliang Login / sessions are not supported in Scratch WWW but rely on some of our other systems that are not open source.
