### ISSUE TITLE
Teacher Registration Must change year after triggering too young error

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#1930]
If you put a birthdate in July 2002 (which makes you 15 years old when this was written) and click next step it will give you the "you're too old" error.  If you change the month to February (which would make you 16) and click Next Step it should pass and take you to the next step.

It doesn't.  It won't pass until you change the year and then change it back.
![mustchangeyear](https://user-images.githubusercontent.com/1088291/41622765-9e5a3cc0-73de-11e8-8ddb-bba92ba647fd.gif)

### Steps to Reproduce

Navigate to https://scratch.ly/educators/
Click "Request Account" at the bottom of the page
Enter a username and password and click Next Step
Enter July 2002 as the birthdate (or later if after June 2018)
Enter other information and click Next Step
Note: You get the "You're too young error" (See https://github.com/LLK/scratch-www/issues/1929)
Change the month to February but don't touch the year
Click Next Step
Note: Nothing happens, the error stays.
Change the year to 2001
Change the year back to 2002 (leaving the month at February)
Click Next Step
Note: it takes you to the next step

### Operating System and Browser

Chrome on Mac

**Comment by apple502j** [comment]
maybe?
https://github.com/LLK/scratch-www/blob/develop/src/components/registration/steps.jsx#L480
