### ISSUE TITLE
Search bar only decodes special characters after switching to Studios tab and back

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#1934]
When you enter a search term with special characters, the search bar should show the decoded characters immediately after hitting enter.

Instead after entering a search you must click the Studios tab to see the updated characters.  You can switch back to the projects tab and the characters will be correct.

![searchspecialcharacters](https://user-images.githubusercontent.com/1088291/41678639-8e608610-7499-11e8-84a1-0da32b6dc419.gif)

### Steps to Reproduce

enter the following things in the search bar and hit enter
  ?q=%D0%9A%D0%BE%D0%BC%D0%B0%D1%80 (should still appear as Комар)
  ?q=cat%3Fcat (should now appear as cat?cat)
  ?q=cat%20cat (should still appear as cat cat)
  ?q=CATCAT (should still appear as cat cat)
Note: the special characters aren't displayed properly
Click the Studios tab
Note: now the characters display correctly.
Click the projects tab
Note: the characters still display correctly

### Operating System and Browser

Chrome on Mac

**Comment by chen-robert** [comment]
I'll be working on this bug

**Comment by benjiwheeler** [comment]
To clarify, we don't really care about search input text like '?q=cat' being turned into 'cat'

**Comment by chen-robert** [comment]
Okay thanks!

**Comment by AmazingMech2418** [comment]
I'm confused on why this was needed since it caused #5486. The user isn't likely to input a URL-encoded query into the search bar.
