### ISSUE TITLE
Preview - Don't show empty Instructions/Notes and Credits on projects you don't own

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#1938]
A brief history / series of notes: In the Scratch 1.4 site, there was no "Instructions" field; only "Notes and Credits". In the Scratch 2.0 site, a field called "Instructions" was added. Generally, it shows up above the Notes and Credits field. But if the project was made by someone you aren't logged in as, the Instructions field doesn't show at all. (On the other hand, projects with empty Notes and Credits *do* show an empty Notes and Credits area.)

Presently in the Scratch 3.0 / scratch-www preview site, both Instructions and Notes-and-Credits always show, whether or not you're logged in. This is particularly noticeable with projects that have an empty Instructions field, either because they were made in 1.4 or because they were intentionally left empty so that there'd be more vertical space in Notes and Credits. Image courtesy of @technoboy10 and stolen from #1935:

![A project with an empty "Instructions" field; there is a blue box for the Instructions content, but it is empty (so very vertically short, but there)](https://user-images.githubusercontent.com/3019167/41872677-a4d6dc00-7890-11e8-8790-a16f02d7d745.png)

Behavior in scratch-www should at least match 2.0 in that empty Instructions fields of projects made by other people should not be visible. I also recommend that the Notes and Credits field follows this same behavior, being hidden if it is empty; I don't see any particular reason to hide an empty Instructions field but not also to hide an empty Notes and Credits.

**Comment by joker314** [comment]
At the moment, if one field is empty, the other can stretch to fill up its space. Should we just leave that area blank if both the Instructions _and_ Notes and Credits are left blank?

**Comment by Narulacodes** [comment]
🍡

**Comment by LiFaytheGoblin** [comment]
up to date screenshot:
<img width="968" alt="screen shot 2018-08-20 at 3 07 19 pm" src="https://user-images.githubusercontent.com/5471273/44361082-cd345080-a48a-11e8-944d-41a664307e72.png">

What should it look like @carljbowman

**Comment by LiFaytheGoblin** [comment]
I think this would be nice:

<img width="971" alt="screen shot 2018-08-22 at 3 43 03 pm" src="https://user-images.githubusercontent.com/5471273/44486639-24b8f480-a622-11e8-90f9-51c8eaa27280.png">

Even if that is empty.
