### ISSUE TITLE
Isn't scratch.mit.edu/proxy/featurted Suposed to show data for featurted projects on scratch site?

### ISSUE THREAD

**Issue by Narulacodes** [LLK/scratch-www#1948]
**TITLE**

**Comment by towerofnix** [comment]
It does. Go to here: https://api.scratch.mit.edu/proxy/featured

..Then find "community_featured_projects".

**Comment by apple502j** [comment]
https://github.com/LLK/scratch-www/blob/develop/src/redux/splash.js#L102
source

**Comment by joker314** [comment]
Note it is "api.scratch.mit.edu" and not "scratch.mit.edu"

**Comment by Narulacodes** [comment]
i made a website with this and over.

**Comment by Narulacodes** [comment]
Please check it out if u can
