### ISSUE TITLE
Text edit in FAQ

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#1950]
We need to make a text edit in the [Privacy Policy section of the FAQ](https://scratch.mit.edu/info/faq/#privacy) page.

The portion of the text that needs to change currently reads, "contact email address - If the account holder is younger than 13, we ask for the email address of their parent or guardian....".

We need to change the age to 16 so it reads as, "contact email address - If the account holder is younger than 16, we ask for the email address of their parent or guardian...." instead.

**Comment by JoelGritter** [comment]
I can take care of this one today at some point!
