### ISSUE TITLE
Connect report project modal to API

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1957]
Connect the modal created for https://github.com/LLK/scratch-www/issues/1857 (included in https://github.com/LLK/scratch-www/pull/1900) to the API endpoint for reporting projects.

**Comment by thisandagain** [comment]
Assigning to @rschamp for triage / assignment to Ben (?)

**Comment by benjiwheeler** [comment]
We are punting on this for now, and instead connected it to the existing scratchr2 endpoint.

More discussion at https://github.com/LLK/scratch-www/pull/2015
