### ISSUE TITLE
IE doesn't show console warning when you first open the console

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#1960]
When you open the console it should give you a warning

Instead the console is blank.  If you load the page while the console is open it will have the warning.

### Steps to Reproduce

Go to the home page
Open the developer console
Note: it is blank
refresh the page
Note: the warning is there

### Operating System and Browser

Internet Explorer on Windows

related to this pr: https://github.com/LLK/scratch-www/pull/1946

**Comment by JoelGritter** [comment]
That's typical IE behaviour. The console object is not initialized unless the devtools panel is open: https://stackoverflow.com/a/45503413/

One way we may get around this is to use the `window.onresize` event, as discussed here: https://stackoverflow.com/a/41627911/
