### ISSUE TITLE
New project page doesn't load player

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#1961]
If you go to this project page: https://scratch.ly/preview/1000015381/ the player should be there.

It isn't.

### Steps to Reproduce

Go to this page: https://scratch.ly/preview/1000015381/
Note: no player appears

### Operating System and Browser

Chrome on Mac

**Comment by Narulacodes** [comment]
403 forbidden on Chrome on A Windows 10 pc. @BryceLTaylor.
Same thing. @thisandagain

**Comment by rschamp** [comment]
Hi @Narulacodes, that's expected because scratch.ly is our staging server and is restricted from public access (but not related to this issue).

**Comment by Narulacodes** [comment]
Ok, Thanks @rschamp.

**Comment by rschamp** [comment]
It works now!
