### ISSUE TITLE
Update credits page (move mewtaylor to former members)

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1966]
On [mewtaylor's profile](https://scratch.mit.edu/users/mewtaylor), he says he is a "former Scratch Team member", and his rank is Scratcher. However, the [credits page](https://scratch.mit.edu/info/credits) still lists him as a current Scratch Team member.

### Steps to Reproduce

Visit https://scratch.mit.edu/info/credits

### Operating System and Browser

Irrelevant

**Comment by thisandagain** [comment]
We will be redesigning the "credits" page soon and will address this at that time.
