### ISSUE TITLE
Add new ST member to scratch credits page

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#1977]
Please add `pondermake` to Scratch Team credits page

**Comment by GreenBayRules** [comment]
I can do this.

**Comment by GreenBayRules** [comment]
What is their first and last name?

**Comment by GreenBayRules** [comment]
@thisandagain

**Comment by thisandagain** [comment]
Kathy Wu

**Comment by GreenBayRules** [comment]
Thanks

**Comment by GreenBayRules** [comment]
@thisandagain Are they a moderator or Deverloper?

**Comment by thisandagain** [comment]
They are a developer. Sorry we didn't provide enough information to complete this initially.
