### ISSUE TITLE
Add ST member to credits page

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#1978]
Please add `brycedtea` to Scratch Team credits page

**Comment by joker314** [comment]
We should use their full names, right? To confirm, for this ST member, it is `Bryce Taylor`?

**Comment by thisandagain** [comment]
@joker314 Correct!

**Comment by joker314** [comment]
(I am doing this)

**Comment by thisandagain** [comment]
Also (as per #1977) Bryce is a developer.
