### ISSUE TITLE
New messages do not have mod-unread class

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#1984]
New messages do not have mod-unread class, so the background color didn't change.

### Steps to Reproduce
1. Get a message
2. Go to message page
3. No background color

### Operating System and Browser
Windows 7 HomePremium 64bit SP1
Firefox 61.0.1

**Comment by DeleteThisAcount** [comment]
+1

**Comment by joker314** [comment]
A duplicate-ish issue was filed at #1989 and fixed with #1990. There, it appears the CSS for those classes was wrong -- not the HTML classes assigned to the relevant elements.

This should hopefully now be resolve either way!
