### ISSUE TITLE
Show full project/studio title in the hover title text

### ISSUE THREAD

**Issue by SheepTester** [LLK/scratch-www#1986]
Many projects have titles that are truncated, and the only way to see the full title is to load the project page.

It would be nice if the titles showed the full title when you hover over them like YouTube videos.

### Steps to Reproduce

Go to the front page and note that some project titles are cut off. Hovering over them shows nothing.

### Operating System and Browser

ChromeOS 10575.58.0, Chrome 67.0.3396.99

**Comment by LiFaytheGoblin** [comment]
This involves several things:
- [ ] on project pages, hovering over a title should display the full title
- [ ] on studio pages, hovering over a title should display the full title
- [ ] on other pages where there is a truncated project or studio name, eg. the what's happening section, on hovering it should display the full title

**Comment by LiFaytheGoblin** [comment]
Actually, the project name should be cut off at some point.

<img width="1223" alt="screen shot 2018-08-21 at 11 13 04 am" src="https://user-images.githubusercontent.com/5471273/44410841-3f607000-a533-11e8-910d-b162d948766d.png">

**Comment by LiFaytheGoblin** [comment]
With a space:

<img width="985" alt="screen shot 2018-08-21 at 11 15 39 am" src="https://user-images.githubusercontent.com/5471273/44411020-99613580-a533-11e8-85db-05d02dbb1089.png">

**Comment by LiFaytheGoblin** [comment]
Compare with short title

<img width="727" alt="screen shot 2018-08-21 at 11 17 08 am" src="https://user-images.githubusercontent.com/5471273/44411120-cdd4f180-a533-11e8-98d4-f7b27ae56d85.png">

**Comment by LiFaytheGoblin** [comment]
Add to scss:
```
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```
Add title attribute with full title to visible project title
