### ISSUE TITLE
microbit page does not include having a microbit as a requirement

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-www#1987]
_Describe the problem. Please make sure you can reproduce the bug. It's also
helpful to include screenshots or animated gifs of the problem._

### Steps to Reproduce

visit /microbit
notice having a microbit is not required

(its very simple to fix)

**Comment by thisandagain** [comment]
We'll be thinking about the requirements issue more holistically as we get closer to the full release of 3.0. In the meantime I'm going to close this as `wontfix`.
