### ISSUE TITLE
Audit "darken" and "lighten" scss 

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-www#1992]
### Overview
Sometimes the `darken` and `lighten` scss properties can break with the new colors. This can cause feedback issues like https://github.com/LLK/scratch-www/pull/1990

Likely the fix for `darken`'s will be to bring in all the shades of the 3.0 colors: primary, secondary, and tertiary. 

`ligthen`'s will need some more thought.

**Comment by Narulacodes** [comment]
If we add this, `I'll thake this.`
`Darken` `Lighten`

**Comment by carljbowman** [comment]
@Narulacodes - Thanks for the offer. But I just wrapped up work on this and will be submitting a PR later this morning.

If you are looking for something to help with, look for issues with the `help wanted` label.

**Comment by carljbowman** [comment]
Fixed by https://github.com/LLK/scratch-www/pull/2007#pullrequestreview-142097092
