### ISSUE TITLE
Conflicting revision dates in Terms of Use

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1999]
At the end of the TOU minus appendices:
![image](https://user-images.githubusercontent.com/28599280/43256127-16d499b6-90cc-11e8-9bbf-5cc500b5247a.png)
At the end of the TOU including appendices:
![image](https://user-images.githubusercontent.com/28599280/43256176-3f692a22-90cc-11e8-8219-ff30f8a2479a.png)

Issue template is irrelevant, this is a textual issue

**Comment by apple502j** [comment]
When is the real update? @thisandagain

**Comment by thisandagain** [comment]
Good question. The last real update is April 2016.
