### ISSUE TITLE
Animate Add To Studio modal button transitions

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2005]
Design team designed animated transitions from state to state for Add To Studio modal buttons.

We should implement those.

Part of this is replacing the css spinner animation with the newer spinner svg.

**Comment by LiFaytheGoblin** [comment]
It is almost done except there is another bug when simulating a slow connection it happens that when you click the button for the first time the checkmark or plus spins until the loading circle image is loaded. 
Also the class needs to be added on click or sth else the bump appears when the element is first loaded
