### ISSUE TITLE
Curator row is missing curator name in Edible Scratch

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#2014]
### Expected Behavior

The curator row should say the equivalent of "Projects Curated By <username>" in all languages.

### Actual Behavior

In Edible Scratch, the username is missing:
![image](https://user-images.githubusercontent.com/28599280/43690634-860da6ee-990d-11e8-9e6b-d279945a0bfe.png)

### Steps to Reproduce

Visit https://scratch.mit.edu and set your language to Edible Scratch.

### Operating System and Browser

Windows 10 Chrome 68

**Comment by DeleteThisAcount** [comment]
I can help with this, just waiting for help wanted

**Comment by Kenny2github** [comment]
Okay, I think the problem is obvious.

In the [scratch-www splash l10n file](https://github.com/LLK/scratch-www/blob/develop/src/views/splash/l10n.json), the string has a format parameter:
![image](https://user-images.githubusercontent.com/28599280/44383400-32e81180-a54b-11e8-9b52-11bbdf882982.png)


In the [scratchr2_translations splash cat file](https://github.com/LLK/scratchr2_translations/blob/master/www/translations/scratch-website.splash-l10njson/cat.json), the string does not have a format parameter:
![image](https://user-images.githubusercontent.com/28599280/44383388-2c599a00-a54b-11e8-93ef-531852aaa8bc.png)

This is yet another issue that belongs in scratchr2_translations. Moved to (waiting)
