### ISSUE TITLE
Clip text in Add to Studio buttons

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2016]
Text is currently limited by number of characters.

Add to or replace this by using CSS properties:

    overflow: hidden;
    text-overflow:ellipsis;

See: https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_text-overflow_hover

**Comment by LiFaytheGoblin** [comment]
also needs white-space: nowrap; for the ... to show up
