### ISSUE TITLE
Extra space in Scratch 3.0 FAQ

### ISSUE THREAD

**Issue by joker314** [LLK/scratch-www#2018]
In the Scratch 3.0 FAQ, under the section headed _Will Scratch 3.0 introduce new blocks?_, there are two spaces between the words "You will find some new blocks in the" and the words "Beta version". There should only be a single space. It looks like there's a normal space, followed by a non-breaking space (`&nbsp;`)

### Steps to Reproduce

Visit https://scratch.mit.edu/3faq
Scroll to main heading **What's new** subheading **Will Scratch 3.0 introduce new blocks?**
Observe extra non-breaking space between aforementioned words

### Operating System and Browser

Chrome v68.0.3440.84 (Official Build) (64-bit) on Windows 10

**Comment by DeleteThisAcount** [comment]
@joker314 found a good forum post about this

**Comment by thisandagain** [comment]
Fixed. Many take a few minutes before it is visible in production.
