### ISSUE TITLE
ability to "load" new 3.0 project

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2019]
user should be able to do File -> New to load a new default 3.0 project in the editor, which replaces the current project data.

**Comment by towerofnix** [comment]
Oh, btw.. what's the LLK/scratch-projects repository? Are there any plans to open source that, or to document the API used to interact with it?

**Comment by colbygk** [comment]
The scratch-projects repository and software is our interface for storing project JSON files to our backend storage system. We have no current plans for open sourcing this and I think it's unlikely we will make any documentation updates before or immediately after the Scratch 3.0 release in January 2019.

**Comment by wwj718** [comment]
hi @colbygk, 
I noticed that the existing [project homepage](https://scratch.mit.edu/projects/238301439/) is based on Django

![image](https://user-images.githubusercontent.com/3153878/44081770-1d8242c0-9fe2-11e8-9264-90ca002838ce.png)

I want to know if the new  backend of scratch3.0 is also based on django.

Thanks!

**Comment by colbygk** [comment]
Hello there,  the simple answer is that no, Scratch 3.0 is not based on django. The more complex answer is that we're currently in the process of shifting a lot of backend infrastructure away from being handled by django, and some of this infrastructure ends up handing data back into requests made by the Scratch 3.0 frontend. This includes parts like the individual project pages, which we are currently updating.

**Comment by wwj718** [comment]
@colbygk  thanks for your reply!

**Comment by wwj718** [comment]
@colbygk 
I guess the  new backend only provides REST api,  Business logic is at the front end.
I would like to know if you  will use django-rest-framework or Rails to provides the REST api，Or you will use Serverless Framework

**Comment by benjiwheeler** [comment]
We are currently building the REST API in node, with a server (not sure what the opposite of "serverless" is :)

As @colbygk said, the plan is to launch 3.0 using both the node and django servers providing API endpoints, andover time to shift backend business logic over from the django server to the node server.

**Comment by wwj718** [comment]
@benjiwheeler Thanks!

**Comment by benjiwheeler** [comment]
Should we create a new project on the server for every user, including ones who are not logged in? Or should we wait until a user is logged in to create it? My understanding is that we do the latter for 2.0.

**Comment by colbygk** [comment]
I believe that we should wait until login and keep the same behavior as 2.0. This seems like something reasonable to raise at the next project page huddle.

**Comment by benjiwheeler** [comment]
Moved to LLK/scratch-gui#2954
