### ISSUE TITLE
Ability to share only within a class or organization

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2025]
Multiple teachers at the 2018 Scratch conference, and other teachers including several at my Aug 2018 training in NYC, have asked that there be a sharing setting between world-viewable and totally private.

There are legal and organizational aspects of this -- some schools have trouble convincing parents it's OK to have their children post their creative work online, and there are concerns about personally identifiable info.

**Comment by thisandagain** [comment]
This is something we have discussed at length and ultimately decided against. As I often like to say, "sunshine is the best disinfectant". The fact that all actions taken in the Scratch community are public is a major way in which we keep the community safe and is connected strongly to our promise as an open (remix-able) community.
