### ISSUE TITLE
Color picker in the Paint Editor does not work in the GUI when loaded within WWW

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-www#2030]
Popovers such as the color picker in the paint editor are not working in the editor in WWW

### Steps to Reproduce
1. See inside a project
2. Go to costumes tab
3. Click on the fill/outline color dropdown or the More dropdown. Nothing happens.
Notice that dropdowns are not working anywhere in Scratch Paint. Something is interfering with react-popover. We didn't see any relevant errors in the console.

### Operating System and Browser
All

**Comment by paulkaplan** [comment]
@chrisgarrity this looks like it is due to the entire GUI being at z-index: 11 https://github.com/LLK/scratch-www/blob/develop/src/views/preview/preview.scss#L18

Do you know if that is still necessary, or was just a leftover?

**Comment by chrisgarrity** [comment]
@paulkaplan it's leftover from trying to load gui in front of the rest of the project page. (11 was the minimum to get it to cover everything).

**Comment by fsih** [comment]
Huzzah!
