### ISSUE TITLE
Add to Studio interactions seem to succeed even when the response is 403?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2032]
Helping @LiFaytheGoblin get set up in her dev environment, we noticed that she was able to click Add to Studio buttons and appear to join and leave studios, though the requests were actually failing with a 403 status code response.

### Steps to Reproduce

Unclear how to reproduce -- the problem is not occurring for me. Needs more work to reproduce. May be a good idea to set scratch-api to fail temporarily, and see how www responds. 

### Operating System and Browser

Mac OS 10.13.6 Chrome 68.0.3440.106

**Comment by thisandagain** [comment]
@BryceLTaylor Would you mind attempting to reproduce this?

**Comment by BryceLTaylor** [comment]
I can't seem to reproduce this on my own.  It seems I would need to make it so I received a 403s in the responses.  I tried turning off the connection in the developer tools, but it just hung in a reasonable way.

**Comment by BryceLTaylor** [comment]
@LiFaytheGoblin Seems to be getting the 403s when working locally, not on staging or production.
