### ISSUE TITLE
Cursor should be pointer when hovering over studio entry on add-studio-dialog

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#2038]
It is currently the default cursor, so it is not intuitive that the thing can be clicked. In Safari it is the text cursor even. Should it be a pointer cursor to indicate the clickability of the studio entry?

### Steps to Reproduce
Hover over one of the studio entries on the new project page 'add to studio' dialog.
<img width="614" alt="screen shot 2018-08-22 at 3 35 27 pm" src="https://user-images.githubusercontent.com/5471273/44486249-09011e80-a621-11e8-9315-bcbdcd4c725d.png">

### Operating System and Browser

MacOS, Chrome and Safari

**Comment by carljbowman** [comment]
Good catch. We should set the cursor in CSS to be the pointer for these elements.

**Comment by carljbowman** [comment]
@benjiwheeler - Do you mind making that tweak?

**Comment by LiFaytheGoblin** [comment]
I can do that :)
