### ISSUE TITLE
incorrect link to credits page from wiki

### ISSUE THREAD

**Issue by hlcolani** [LLK/scratch-www#204]
This is a small issue I noticed:
When you are on the Wiki and use the navigation at the bottom to get to the Credits page, clicking on the word "credits" takes you to https://scratch.mit.edu/credits/ instead of https://scratch.mit.edu/info/credits/ (the second url is currently the correct one, even though the first one is more concise). For the new website, should I change the path to the credits page to "https://scratch.mit.edu/credits/"? Please let me know.

**Comment by TheGrits** [comment]
Is there a separate repository for the wiki?

**Comment by TheGrits** [comment]
Should be closed, fixed by this commit: https://github.com/LLK/scratchwikiskin/commit/74e2491b41cd5f231da23a6874cd1aebdecd43bd

**Comment by mewtaylor** [comment]
Thanks @TheGrits ! Closing now.
