### ISSUE TITLE
Add a Scratch Link page

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-www#2050]
There should be a Scratch Link page with a download link, detailed download instructions (including guide for installer on windows) and a description of what Scratch Link does.

Proposed URL: "https://scratch.mit.edu/link"

### Steps to Reproduce

Look for a generic Scratch Link page.

### Operating System and Browser

All

**Comment by thisandagain** [comment]
Currently we are distributing Scratch Link through the various extension pages. We currently do not see a need for it to have it's own page.
