### ISSUE TITLE
Users should be able to write new comments / reply to comments

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2053]
Currently, you can only read comments, not write them.

There are designs for this in invision, and @kathymakes is working on design for this. (@kathymakes, I put you on this for convenience -- feel free to remove yourself if this stuff is set.)

**Comment by benjiwheeler** [comment]
@paulkaplan I assumed that this issue was a duplicate, but a quick search didn't turn up another.

**Comment by paulkaplan** [comment]
Done!
