### ISSUE TITLE
Users should be able to report comments as inappropriate

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2055]
We need designs for this -- we have designs for the report button ( https://projects.invisionapp.com/d/main/default/#/console/13318727/295901018/preview ) but not the modal for reporting (AFAIK)

@kathymakes, assigning you for that.

**Comment by carljbowman** [comment]
@benjiwheeler - Just to clarify, we should match the behavior or 2.0: there is not a modal for reporting comments. Reporting a comment works more like a toggle. 

Here is a sketch of the new comments systems working like 2.0's toggle system:
![comment reporting](https://user-images.githubusercontent.com/3409578/44808919-6f46ed80-ab9b-11e8-966f-f6ca494c660c.png)

Let us know if you need more.

**Comment by WorldLanguages** [comment]
"Unreport". The best feature ever. Thank you lol

**Comment by DeleteThisAcount** [comment]
agree +1

very help
