### ISSUE TITLE
Update Scratch Link installer links

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-www#2056]
Once we have Scratch Link available in both the Windows and Mac app stores, we'll want to provide links to the stores via their app store badges, in place of the current download button.

We also will need to provide links to the direct download, because some users will be unable to install via the app store. We should visually bias users toward using the app stores, though, because they will provide a better experience.

**Comment by kyleplo** [comment]
Something like this?

![scratch-link-download](https://user-images.githubusercontent.com/31634240/44956704-46be3c80-ae96-11e8-9708-bedc8be09a7c.PNG)

**Comment by carljbowman** [comment]
@kyleplo - Pretty much. We do want to slightly deemphasize the "Direct Download" option. Downloading from the stores will provide a will provide a better experience in the longer arc. For example, stores will help keep the software up-to-date. 

We would prefer that folks who can use the store to download to the store, so we want the badge to stand out more.

### Windows Sketch
![windows-download](https://user-images.githubusercontent.com/3409578/45036814-7c485e80-b02b-11e8-8b15-c502cd55467b.jpg)

### Mac Sketch
![mac-download](https://user-images.githubusercontent.com/3409578/45036822-7f434f00-b02b-11e8-85cf-7ff98cd34b7f.jpg)
