### ISSUE TITLE
Redesign Credits Page

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-www#2061]
Logging to track this work. We will flesh out the project in more detail during the green flag meeting.

Generally we want to make some changes to how collaborators are represented, make sure the list of folks working on Scratch is up-to-date, and clean up the overall design of the page.

**Comment by kathymakes** [comment]
Here are notes from the green flag. 
https://docs.google.com/document/d/1GgqyXPbeduQooMh000-9AjKhIU97kZbby1vMBecs0_U/edit

**Comment by kathymakes** [comment]
Round 2 of designs on Invision:
https://invis.io/PVO4F19TJ3G
