### ISSUE TITLE
Design audit for comment states (matrix) 

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2063]
These designs are relevant to @benjiwheeler 's issues here:
https://github.com/LLK/scratch-www/issues/2055
https://github.com/LLK/scratch-www/issues/2054

WIP Documentation + notes of current states:
https://docs.google.com/spreadsheets/d/1fd3T-rvfscXdTAlBEM3yc4i0q3zEa5iYaH4rOV3XeU4/edit#gid=0

WIP Designs here:
https://invis.io/5QNVDKQA79M

#### See comments for most recent design.
(zoom for detail)
![all](https://user-images.githubusercontent.com/8203939/45048548-318a0f00-b04a-11e8-8dc9-c3b38babbd75.png)

### Note 1:
The pizza cat avatar in these sketches represents the logged-in person.
<img width="227" alt="screen shot 2018-09-05 at 10 00 47 am" src="https://user-images.githubusercontent.com/8203939/45099614-b41bd880-b0f5-11e8-8313-906d631c92e9.png">

### Note 2:
In this matrix I've drawn actions on each comment to compare how the actions are different for you vs. others.

Normally, actions should appear only on hover.
![hover](https://user-images.githubusercontent.com/8203939/45099690-e4637700-b0f5-11e8-8c13-0dd707112908.png)

**Comment by kathymakes** [comment]
**Some outstanding questions include:**

- For Moderators, what’s the difference between deleted and reported? Currently on scratch, a reported comment by a moderator behaves really similarly to a deleted comment. Both disappear globally.
- For all users, including Moderators: Can you delete a comment you reported, even if no user can longer see it?

**Comment by kathymakes** [comment]
-- Edited original post-- 
Added a note about how actions should only appear on hover. We're still in the process of deciding how to mirror this behavior on mobile.

Also, the pizza cat icon represents you, vs the other avatars which represent other users.

**Comment by DeleteThisAcount** [comment]
The copy link button seems awesome, why only for admins?

It would be so helpful for wiki editors, and basically everyone

**Comment by kathymakes** [comment]
After 3.0 meeting, we decided:
-- Next Steps: Explore options for differentiating visuals for Reported + Deleted for admins (use the term, "Censor" instead?)
-- "Delete" for an already reported comment isn't commonly used, but it does get used
-- Why "Delete" on user's own projects only? Learned that this is an intentional choice and not a technical limitation

**Comment by kathymakes** [comment]
Also should add : "censored by admin, vs. deleted by user"

**Comment by kathymakes** [comment]
One potential design for making "delete" and "censored" appear different:
(also added "censored by...")

<img width="790" alt="screen shot 2018-09-06 at 5 06 29 pm" src="https://user-images.githubusercontent.com/8203939/45185166-3e983100-b1f7-11e8-85f0-2c8f8999c2fa.png">

**Comment by kathymakes** [comment]
Updated main matrix:
- added changes in previous comment (not finalized yet)
- re-aligned "DELETE" and more consistent actions to the right

![r2_all](https://user-images.githubusercontent.com/8203939/45185193-5a033c00-b1f7-11e8-8896-9ec2ea0b9631.png)

**Comment by kathymakes** [comment]
Updated main matrix image again.

We decided for now not to change "Report" to a different word.
Also, we discovered that report actions are different for regular user depending on **whose page they are on** (their own, vs. others')

![round 2](https://user-images.githubusercontent.com/8203939/45500744-561e6f00-b74d-11e8-89ec-210b6fcd6921.png)

**Comment by kathymakes** [comment]
Closing because there are other specs which are more up-to-date than this.
