### ISSUE TITLE
Project Title input field needs validation errors to appear to the right of the input (in desktop window sizes) or below it (in mobile sizes)

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2065]
Currently, validation errors appear in the middle of the title input field when using desktop widths...

![screen shot 2018-09-04 at 5 33 52 pm](https://user-images.githubusercontent.com/3431616/45059125-ea5f4680-b068-11e8-9d1f-3a0ea5393852.png)

...and push the title field left when using mobile widths...

![screen shot 2018-09-04 at 5 34 52 pm](https://user-images.githubusercontent.com/3431616/45059105-dd425780-b068-11e8-8868-2cc35c6889be.png)

**Comment by kathymakes** [comment]
@benjiwheeler 
Here are some specs, based off the designs implemented here:
https://scratch.mit.edu/educators/register

Happy to chat about more of these in person or pair up!

——
On mobile:
![spec - mobile](https://user-images.githubusercontent.com/8203939/45060578-7627a180-b06e-11e8-9293-1f69ab72525b.png)

Roughly 30% (whenever the player and description align on the same left margin)
![spec - 480](https://user-images.githubusercontent.com/8203939/45060575-7627a180-b06e-11e8-8236-7ea010d56088.png)

Roughly 60% (whenever we begin stacking the player + description)
![spec - 768](https://user-images.githubusercontent.com/8203939/45060577-7627a180-b06e-11e8-97b7-4b3c747850a3.png)

**Comment by kathymakes** [comment]
One change made to the design:
In the tablet size (~60%) the tooltip should drop *below* the textfield, with an upwards caret.
The text box currently spans the whole row, up until the "See Inside" Button
(Text box does not shrink on resize)

**Comment by kathymakes** [comment]
Updated: Added screen size 1280px to the spec above
