### ISSUE TITLE
Studio List in Add to Studio modal on Project Page doesn't update when you create a studio

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2066]
When you create a new studio and then navigate to the new project page, you should be able to see that studio in the Add to Studio modal.

Currently it doesn't appear on the studio list at first, but it will show up after a while.  On Scratchr2 the new studio shows up immediately.

![add to studio2](https://user-images.githubusercontent.com/1088291/45100785-14ac1500-b0f8-11e8-89b6-8a6fbf27510d.gif)

### Steps to Reproduce

On staging:
Create a new studio
Navigate to a project in your my stuff
Click on the Add to Studio (on the Scratchr2 page)
Note: the new studio appears in the list.
Close the modal
Navigate to the new project page for that same project
Click "Add to Studio"
Note: the modal doesn't contain the new studio

### Operating System and Browser

Mac on Chrome

**Comment by thisandagain** [comment]
Moved to LLK/scratch-api#605
