### ISSUE TITLE
Project page comment "fade out" looks incorrect on Safari

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2067]
If you load a project page with a lot of comments it should truncate the list so that they aren't all visible.  The last visible entry should have a gradient that fades it out.

On Safari, on either ipad or a mac, it looks awful:

ipad
![ipadgradientcommentsgradientprojectpage](https://user-images.githubusercontent.com/1088291/45105676-c5b7ad00-b102-11e8-82b5-a9b6c10f639f.PNG)

on mac
![screen shot 2018-09-05 at 11 53 03 am](https://user-images.githubusercontent.com/1088291/45105684-cbad8e00-b102-11e8-93bf-f839fd7cbf88.png)

### Steps to Reproduce

Open a project with a lot of comments such as https://scratch.ly/preview/25532916/
Scroll down until you see where the comments get truncated
Note: it looks wrong.

I did not see this on chrome or firefox

### Operating System and Browser

Safari on Mac
Safari on iPad

**Comment by LiFaytheGoblin** [comment]
Reason + Solution https://css-tricks.com/thing-know-gradients-transparent-black/
