### ISSUE TITLE
UX— Comment actions for Scratch admins

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2080]
## Overview
These drawings show how **Admins** use REPORT, DELETE, COPY LINK on comments.
Right now, I'm showing how behavior currently works in 2.0 (except for COPY LINK, which is new). These UX flows might change.

**Related links:**
[Comment states overview
](https://github.com/LLK/scratch-www/issues/2063)[Comment actions for Regular Scratch users](https://github.com/LLK/scratch-www/issues/2087)

## Questions

**Things to design:**
* Should Restore/Unreport actions on parents restore whole thread?
* Should you be able to restore a child comment if the parent is deleted? (guessing no)

**Edge cases to discuss:**
* Moderator “reporting” / “un-reporting” a comment flow ?

---
## Designs (in progress)

> **Note:** In these drawings, "Pizzacat" represents the Scratch admin who is logged in.
<img width="60" alt="screen shot 2018-09-13 at 1 40 01 pm" src="https://user-images.githubusercontent.com/8203939/45505406-8d474d00-b75a-11e8-9a0d-9586a9c81769.png">

> **Note:** In reality, actions should only appear on hover. (In mockups, they appear on every comment)
<img width="200" alt="screen shot 2018-09-13 at 1 41 24 pm" src="https://user-images.githubusercontent.com/8203939/45505530-d0092500-b75a-11e8-93f1-ffe5edbe2f41.png">

---

### 1. An admin can report all comments.
(except for their own comments)

•  changes visibility: community can't see
•  creates ticket in moderation queue

![admin report 2](https://user-images.githubusercontent.com/8203939/45504982-57559900-b759-11e8-9cd2-47a4e36e5797.png)

Comment gives admin option to "unreport."
![admin report 3](https://user-images.githubusercontent.com/8203939/45504983-57559900-b759-11e8-9629-273b27b44f25.png)

When the page is refreshed, the comment is gone. (can be resurfaced in "show deleted"). 
![admin report 4](https://user-images.githubusercontent.com/8203939/45504984-57559900-b759-11e8-8844-3c037695bf49.png)

---
### 2. An admin can unreport reported comments.

•  changes visibility: community can see

> Note: This appears when admin is in the "show deleted comment" view.

![admin unreport 2](https://user-images.githubusercontent.com/8203939/45505329-5ffa9f00-b75a-11e8-9a19-a75bbf372d61.png)
![admin unreport 3](https://user-images.githubusercontent.com/8203939/45505323-5e30db80-b75a-11e8-8d8c-99d968397bae.png)

---
### 3. An admin can delete all comments.

•  changes visibility: community can't see

![admin delete 2](https://user-images.githubusercontent.com/8203939/45514960-dc01e080-b774-11e8-9bfb-8a4f3377ca98.png)

> Note: Admins have no modals when they're hiding and restoring comments.

![admin delete 3](https://user-images.githubusercontent.com/8203939/45514961-dc01e080-b774-11e8-87f9-ecaf82104b8d.png)

---

### 4. An admin can restore deleted comments.

•  changes visibility: community can see

![admin delete 6](https://user-images.githubusercontent.com/8203939/45515043-14a1ba00-b775-11e8-87ed-0ed2dca957aa.png)
![admin delete 7](https://user-images.githubusercontent.com/8203939/46492838-b9477280-c7dc-11e8-9b0d-c1e4f2a3d5c9.png)
![admin delete 8](https://user-images.githubusercontent.com/8203939/46492839-b9e00900-c7dc-11e8-9cfd-7d402d1d9767.png)

---
### 5. An admin can copy links to comments.

• copies an anchor link to the clipboard.
• pasting link should scroll you to that comment.

> Note: This should also work for:
> * nested thread replies
> * hidden comments (possibly switch views for admin?)

![admin copylink 2](https://user-images.githubusercontent.com/8203939/45515612-a65df700-b776-11e8-97d6-b6900d280331.png)

Format for comment url tbd.
![admin copylink 3](https://user-images.githubusercontent.com/8203939/45515613-a65df700-b776-11e8-8584-76e48362dae1.png)

Scrollbar is for mockup purposes only... should autoscroll to the comment, which is be highlighted.
![admin copylink 4](https://user-images.githubusercontent.com/8203939/45699447-f30b4e80-bb37-11e8-9fe8-35cc28fa8137.png)

**Comment by towerofnix** [comment]
>A regular user can delete all comments in their own space.
>* changes visibility: community can't see
>* creates ticket in moderation queue

This is interesting. I thought that if a user deletes a comment (without reporting it), the ST wouldn't be notified. So deleting is basically the same as reporting, but it also hides the comment from the community?

**Comment by kathymakes** [comment]
> > A regular user can delete all comments in their own space.
> > 
> > * changes visibility: community can't see
> > * creates ticket in moderation queue
> 
> This is interesting. I thought that if a user deletes a comment (without reporting it), the ST wouldn't be notified. So deleting is basically the same as reporting, but it also hides the comment from the community?

Thanks for commenting -- you're actually correct! The spec is pretty WIP right now, and that was an error on my part. I'll update it. Good catch 👍

**Comment by kathymakes** [comment]
Changed this UX spec to only include admins, because the issue was getting too bloated w/ images.
Will create separate issue for regular Scratcher comment UX.

**Comment by kathymakes** [comment]
Made some changes to Admin Delete/Restore flow (above)
Want to call out some of the distinctions here, specifically around threaded comments:

-  **Deleting a parent comment deletes all the children.**

![admin delete 1](https://user-images.githubusercontent.com/8203939/46493024-3d99f580-c7dd-11e8-9726-4a551c98ffe7.png)
![admin delete 2](https://user-images.githubusercontent.com/8203939/46493025-3d99f580-c7dd-11e8-9c48-503b04fe964d.png)

___

- **Restoring a parent comment only restores the parent.**
Once the parent is restored, you then have the option to restore on children comments.

![a - admin restore 1](https://user-images.githubusercontent.com/8203939/46493015-3a066e80-c7dd-11e8-9732-c0157818352c.png)
![a - admin restore 2](https://user-images.githubusercontent.com/8203939/46493016-3a9f0500-c7dd-11e8-98de-fcde67709572.png)
![a - admin restore 3](https://user-images.githubusercontent.com/8203939/46493017-3a9f0500-c7dd-11e8-97d3-ad74cbe423f7.png)

@paulkaplan if it's helpful for you :)

**Comment by kathymakes** [comment]
### Reporting in a Thread
Reporting in a thread is a bit like deleting in a thread, but there are some key differences:

 -  **When admins report a parent comment, it will remove the comment and all of its child comments– but _not until the page is reloaded_.**

![2](https://user-images.githubusercontent.com/8203939/46497514-cb2f1280-c7e8-11e8-918f-2840b0ed72a3.png)

 - **As long as you haven't reloaded the page, you can still report or delete child comments.**

![image](https://user-images.githubusercontent.com/8203939/46499331-cde03680-c7ed-11e8-8d8b-0cf9e071046f.png)

- **After reloading the page, all the removed comments disappear.**

![4](https://user-images.githubusercontent.com/8203939/46497522-d2562080-c7e8-11e8-85a6-e8a8585de44f.png)

### Unreporting in a Thread

These sketches show the same comments above, but in "Showing Deleted Comments View." 

- **If you unreport a child comment, it will default to a deleted comment, because it's parent comment is still reported/hidden.**

![4 - hidden](https://user-images.githubusercontent.com/8203939/46498089-6eccf280-c7ea-11e8-8e35-bbe7b94af563.png)

- **If you unreport the parent comment with deleted child comments, it behaves like "Restore."**
(You have to manually restore child comments.)

![5 - hidden](https://user-images.githubusercontent.com/8203939/46498076-65438a80-c7ea-11e8-9e83-438a25edc9d0.png)


![6 - hidden](https://user-images.githubusercontent.com/8203939/46498080-670d4e00-c7ea-11e8-8613-3a39441d6e33.png)

**Comment by kathymakes** [comment]
**Update:** We decided to change the way that you restore deleted/reported threads.
@paulkaplan 

When you restore the parent comment, it restores all of the children comments **that are marked, "deleted by parent"**, but not the ones that have already been censored for other reasons.

![restore whole threads - 1](https://user-images.githubusercontent.com/8203939/46971759-e3c1e700-d08a-11e8-88b8-c2e273240742.png)
![restore whole threads - 2](https://user-images.githubusercontent.com/8203939/46971761-e3c1e700-d08a-11e8-88d4-4ad6f2f1dd24.png)
