### ISSUE TITLE
New project page: Load More button sometimes unnecessarily there

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#2085]
Load more button is always there - I think it shouldn't? It is because projectInfo.stats.comments is sometimes 1 more than there are comments.

### Steps to Reproduce
Go to a preview project page, eg scratchly 1000004400 and see that there is a load more button even though there is only one comment on that project

### Operating System and Browser
MacOS, Chrome

**Comment by chen-robert** [comment]
Could you provide a link please? I'm new and not really familiar with where everything is yet :).

**Comment by LiFaytheGoblin** [comment]
Yes, sorry. Scratch.ly is only available for the Scratch Team.

**Comment by chen-robert** [comment]
Oh ok. Sorry, I'm a bit confused. Is scratch.ly the same as this repository or something different?

**Comment by LiFaytheGoblin** [comment]
It is a website that is basically a copy of the Scratch website used for testing.

**Comment by chen-robert** [comment]
Ok thanks!

**Comment by LiFaytheGoblin** [comment]
@colbygk Hey so there is this problem @chen-robert is describing about the api. Is there away to get the number of not-censored or deleted comments on a project page via api? That would maybe solve the issue of the load more button appearing where it should not!
