### ISSUE TITLE
UX— Comment actions for Regular Scratch users

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2087]
## Overview
These drawings show how **Regular Scratch users** use REPORT, DELETE on comments. 
Right now, I'm showing how behavior currently works in 2.0. These UX flows might change.

**Related links:**
[Comment states overview
](https://github.com/LLK/scratch-www/issues/2063)[Comment actions for Scratch admins](https://github.com/LLK/scratch-www/issues/2080)

## Questions

**Things to design:**
* An interstitial way to communicate that your comment has been reported, even if it looks normal on refresh? 

**Edge cases to discuss:**
* Users reporting a comment and understanding that it won’t immediately be hidden (unless they are the 3rd reporter)

---
## Designs (in progress)

> **Note:** In these drawings, "Pizzacat" represents the regular Scratcher who is logged in.
<img width="60" alt="screen shot 2018-09-13 at 1 40 01 pm" src="https://user-images.githubusercontent.com/8203939/45505406-8d474d00-b75a-11e8-9a0d-9586a9c81769.png">

> **Note:** In reality, actions should only appear on hover. (In mockups, they appear on every comment)
<img width="200" alt="screen shot 2018-09-13 at 1 41 24 pm" src="https://user-images.githubusercontent.com/8203939/45505530-d0092500-b75a-11e8-93f1-ffe5edbe2f41.png">

---
### 1. A regular user can report all comments in any space.
(except for their own comment)

 •  does NOT change comment visibility 
•  creates ticket in moderation queue

> Note: Reported comment stays when it's not your own profile or project.

![regular report 2](https://user-images.githubusercontent.com/8203939/45506166-743f9b80-b75c-11e8-91d2-fcb6f8af5186.png)

![regular report 3](https://user-images.githubusercontent.com/8203939/45506167-743f9b80-b75c-11e8-9639-551dfe9067ff.png)

![regular report 3-1](https://user-images.githubusercontent.com/8203939/45629330-267ca900-ba64-11e8-8064-9dc30a9f479b.png)

![regular report 9](https://user-images.githubusercontent.com/8203939/45629478-85422280-ba64-11e8-86b3-50b637d7295f.png)

When the page is refreshed, the comment will still be visible to the community. Styling returns to normal.

Not the most ideal behavior... Still, changing comment state after page refresh is not something we can address right now.

![regular report 5](https://user-images.githubusercontent.com/8203939/45506169-74d83200-b75c-11e8-99dc-2a518296826e.png)

---
### 2. A regular user can report **_+ remove_** all comments in their own space.
(except for their own comment)

•  changes visibility: community can't see
 •  creates ticket in moderation queue

> Note: Reported comment DISAPPEARS when it is your profile or project.

![regular report 7](https://user-images.githubusercontent.com/8203939/45626437-9176b180-ba5d-11e8-9e75-c6976be69115.png)
![regular report 8](https://user-images.githubusercontent.com/8203939/45506878-84587a80-b75e-11e8-9863-6660c2acf93f.png)

Messaging is different here, because the comment is going to be automatically removed.
Is this too much overhead/messaging?

![regular report 8-1](https://user-images.githubusercontent.com/8203939/45629486-88d5a980-ba64-11e8-934c-78ed96bb751e.png)

I also wonder if we should just remove the comment, like we do for delete. That could be misleading?
But keeping the comment around might also be confusing...

![regular report 9](https://user-images.githubusercontent.com/8203939/45629478-85422280-ba64-11e8-86b3-50b637d7295f.png)

When the page is refreshed.... the comment will be hidden from the community.
![regular report 10](https://user-images.githubusercontent.com/8203939/45506880-84587a80-b75e-11e8-95f4-5f25c9fb0413.png)

---

### 3. A regular user can delete all comments in their own space.

•  changes visibility: community can't see

![regular delete 2](https://user-images.githubusercontent.com/8203939/45506651-e9f83700-b75d-11e8-92d7-10f43cf90fe3.png)
![regular delete 3](https://user-images.githubusercontent.com/8203939/45506652-e9f83700-b75d-11e8-9da0-73b079efb99a.png)
![regular delete 4](https://user-images.githubusercontent.com/8203939/45506653-e9f83700-b75d-11e8-948b-6fbe50471363.png)

**Comment by kathymakes** [comment]
**Alternative Report States?**
(These just subtly different - in case the red state is confusing/misleading?)

_On someone else's page - shows only the red caption_
![regular report 4__alt](https://user-images.githubusercontent.com/8203939/46747531-92c38480-cc7f-11e8-946f-a425daf8f8f7.png)

_On your own page - removes immediately_
![regular report 9__alt](https://user-images.githubusercontent.com/8203939/46747532-92c38480-cc7f-11e8-9cdd-b466add1f489.png)

**Comment by towerofnix** [comment]
>On your own page - removes immediately

I'm a little worried this might make users confused as to whether or not the comment was actually reported, since there is no explicit feedback that says "the comment was reported". While the actions "report" and "delete" are different (you're clicking on different buttons, of course), the effect *looks* the same, so it might look like the report "didn't work".

**Comment by kathymakes** [comment]
@towerofnix Yeah, that makes a lot of sense! I am leaning towards keeping the red state so that it looks more reported... 

What would you think if they still got some kind of warning, like a modal?
![image](https://user-images.githubusercontent.com/8203939/46873801-8a955180-ce05-11e8-9a62-e141b7189fdc.png)

**Comment by towerofnix** [comment]
@kathymakes That definitely shows the feedback so there's no confusion :) Showing a message like that is also potentially helpful just anywhere so that (inexperienced) users understand what Report did and that it did indeed work.

I don't think there are many other "popup" modals like that on scratch-www yet (the sign up screen is the only one that comes to mind), but I think this is a good usage of one.
