### ISSUE TITLE
http://localhost:8333/projects/editor/?tip_bar=home

### ISSUE THREAD

**Issue by mengma1** [LLK/scratch-www#2088]
_Describe the problem. Please make sure you can reproduce the bug. It's also
helpful to include screenshots or animated gifs of the problem._

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described above. The 
more detailed and explicit the steps are the better._

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Cannot GET /projects/editor/

why?

**Comment by apple502j** [comment]
Because it's hosted on scratchr2 not scratch-www.
I also think there is no Scratch 3 Editor wrapper here yet.
