### ISSUE TITLE
Ensure ownership state on the project page

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2092]
Each of these states should be visibly distinct:

Do I own the project?
 - No
 - Yes

Is the project censored?
 - No
 - Yes (w/ message from moderation team)

Is the project shared?
 - No
 - Yes
 - Yes (confirmation after the share action)

**Comment by benjiwheeler** [comment]
Related questions:

Mostly answered/implemented already, but needs explicit listing and checking:
* How should the project page's appearance and UI change to reflect ownership vs. non-ownership?
* How should the project page's appearance and UI change to reflect shared/unshared state?
* Which post/put/delete API calls are possible from the project page and GUI, and are they all being given the right auth checks?

Needs discussion and implementation:
* How should GUI's appearance and UI change to reflect ownership vs. non-ownership?
* How should GUI's appearance and UI change to reflect shared/unshared state?
* How should the project page's appearance and UI change to reflect user types -- new scratcher, scratcher, teacher, student, moderator/administrator/superuser?
* How should GUI's appearance and UI change to reflect user types -- new scratcher, scratcher, teacher, student, moderator/administrator/superuser?

**Comment by kathymakes** [comment]
Thanks for writing this up! Will add some notes about what we already have:
____
> Related questions:
> 
> Mostly answered/implemented already, but needs explicit listing and checking:
> 
> * How should the project page's appearance and UI change to reflect ownership vs. non-ownership?

**Someone else's project:**
- [ ] Report button
- [ ] Remix button
- [ ] No text fields are editable
      - Should also be styled differently
- [ ] No commenting "on/off" toggle ability

___
> * How should the project page's appearance and UI change to reflect shared/unshared state?

**Unshared project**
- [ ] No ability to love/favorite
- [ ] Unshared project banner with option to "Share"

**Shared project**
- [ ] Shared project banner on share.
        - This disappears the next time you visit the page

___
> Needs discussion and implementation:
> 
> * How should GUI's appearance and UI change to reflect ownership vs. non-ownership?

So far, this seems well addressed with the avatar + title version of the nav bar.
<img width="420" alt="screen shot 2018-11-26 at 9 32 21 am" src="https://user-images.githubusercontent.com/8203939/49020365-40babd80-f15e-11e8-93b5-2ae4436a1793.png">

___
> * How should GUI's appearance and UI change to reflect shared/unshared state?

Right now, we have a design for a button appearance/string change:
"Share" –> "Shared."
<img width="467" alt="screen shot 2018-11-26 at 9 32 17 am" src="https://user-images.githubusercontent.com/8203939/49020351-38fb1900-f15e-11e8-82ca-bf1a683eea0b.png">

___
> * How should the project page's appearance and UI change to reflect user types -- new scratcher, scratcher, teacher, student, moderator/administrator/superuser?

Hm, my intuition is that we should change as little as possible between the different user types, at least for the project viewing experience. This is something to chat about more...

One thing for sure is that admins/mods will have special privileges for moderation (ex: delete, report, copy link for comments). But I'm not sure how much of censoring projects will actually live in the mod iframe tool?

For a new Scratcher, we talked briefly about adding more celebratory messaging ("Congrats, you shared a project," etc) on the project page until they become a Scratcher.

___
> * How should GUI's appearance and UI change to reflect user types -- new scratcher, scratcher, teacher, student, moderator/administrator/superuser?

Also good to discuss more. We did talk about adding encouraging prompts/modals for Scratchers who are remixing and sharing for the first time. We can think about what kind of messaging we want to add here.

**Comment by kathymakes** [comment]
Also, link to the censored state messaging @benjiwheeler :
https://github.com/LLK/scratch-www/issues/2126#issuecomment-436424184

**Comment by benjiwheeler** [comment]
Only specific issue left is that you can love/favorite your own unshared project. Checking if that's something we want to take action on in the future. Made https://github.com/LLK/scratch-www/issues/2415

Several notes of Kathy's should be followed up on in the long term.
