### ISSUE TITLE
Redirect old project URLs to the new URL structure

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2095]
We should support and translate URLs using `#editor` `#player` and `#fullscreen` into the new URL scheme 

This should include /project/:id/fullscreen

Notes from discussion:
handle these in www, in view code before components even mount; do history replace, so we don’t have to manage URL state

**Comment by benjiwheeler** [comment]
Our current thinking: in preview.jsx, before rendering, consider redirecting instead.
