### ISSUE TITLE
Website down page shows old tweet

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#2097]
<img width="966" alt="screen shot 2018-09-20 at 1 06 58 pm" src="https://user-images.githubusercontent.com/5471273/45834810-208dfe80-bcd6-11e8-9683-40e976eaff73.png">

Thanks to @seotts for pointing it out!

**Comment by kerrtrvs** [comment]
Was just about to open an issue for this. 😄

**Comment by me-win** [comment]
correct URL: https://twitter.com/scratch

**Comment by chen-robert** [comment]
@LiFaytheGoblin Is there a way to simulate this error page for local development? Thanks!

**Comment by colbygk** [comment]
@chen-robert Thank you for taking time to look at this. At the present time, the error page is located in our CDN provider (Fastly). This allows us to show an error page even though our backend systems are not available. This means the actual content of the error page is very static and is a single, self-contained html page that includes the image data directly. You should be able to load it directly into a web browser.

**Comment by thisandagain** [comment]
@colbygk Is this now resolved?

**Comment by colbygk** [comment]
Yes! Updated the fastly content and we've added the snippet to scratch-www
