### ISSUE TITLE
Display notice for Chrome 69 users to re-enable Flash

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#2100]
### Expected Behavior
The recent Chrome 69 update requires users to re-enable Flash for each site every time they restart the browser. There should be a notice to let users know that they must enable Flash again.

### Actual Behavior
There is no such notice

### Steps to Reproduce
Go to any project page

### Operating System and Browser
Chrome 69 Windows 10

**Comment by benjiwheeler** [comment]
What are you envisioning for when and where the notice would appear?

 It's hard for the website or client side code to know that Flash is or isn't enabled, isn't it? My sense is that this is something where the experience varies too widely across platforms and browsers for us to handle it well -- we may just need to count on users realizing, with the browser's notifications and appearance, that Flash needs to be reenabled.

**Comment by Kenny2github** [comment]
Where does the "browser not supported" notice appear on scratchr2? I'd imagine it would add to there.

Detecting whether Flash is enabled is (according to a quick search) done with [SWFobject](https://github.com/swfobject/swfobject), which is already included on project pages. If `swfobject.getFlashPlayerVersion()` returns a 0.0.0 version number, flash is not enabled; otherwise it should correspond to the Flash version. In fact, you can simply paste the following JS line in the dev console on a project page to correctly check if Flash is enabled:
```javascript
swfobject.getFlashPlayerVersion().major ? 'Enabled' : 'Disabled'
```

So I don't think this would be too hard to accomplish.

**Comment by benjiwheeler** [comment]
This sounds doable, but I'm still not quite clear what it would accomplish. Flash itself will display a message suggesting that you need to enable it, right? That might not be as clear as it could be, but I worry we would only confuse things further by adding banner messages and such.

I think I need help envisioning what this might look like.

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#5159
