### ISSUE TITLE
Project page should display error image/message when nonexistent or unshared ids requested

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2110]
If I enter a nonexistent or unshared project id url, like https://scratch.ly/preview/1000015726/ or https://scratch.mit.edu/projects/245262633484/  I expect to see something like this (current scratch.mit.edu ):

![screen shot 2018-09-26 at 9 01 44 am](https://user-images.githubusercontent.com/3431616/46081627-fc656e00-c16a-11e8-86b1-897a1535b54f.png)

...but instead, I see:

![screen shot 2018-09-26 at 9 01 25 am](https://user-images.githubusercontent.com/3431616/46081635-012a2200-c16b-11e8-8c15-373644fe1faf.png)

We need to discuss some aspects of this:
* do we want to display an error within the project page (and respond with a 200), or redirect to a 404?
* if displaying within project page, should we make the error essentially take over the whole page, to be clearer to users that the entire page wasn't found (rather than suggesting that we agree such a project exists, we just failed to deliver it)
* what should the image and language of the page be?

For reference, see page we currently display when you try to register for a classroom with a nonexistent classroom id:

![screen shot 2018-09-26 at 10 35 27 am](https://user-images.githubusercontent.com/3431616/46087267-f2963780-c177-11e8-8796-54e7ee3cffcf.png)

**Comment by paulkaplan** [comment]
Fixed
