### ISSUE TITLE
Project page should wait until project finishes loading before allowing swapping between player and editor

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2111]
To reproduce:

1. Load a project page for an existing project. Before it finishes loading, click See inside.
2. Observe that the project player is black/unloaded, and does not load.

Note that the js console will show the error:
`WebGL: INVALID_VALUE: texImage2D: no canvas`

(Example of black/unloaded player:)
![screen shot 2018-09-26 at 9 50 23 am](https://user-images.githubusercontent.com/3431616/46084524-dee7d280-c171-11e8-879c-559d2aa3a1e2.png)

**Comment by chen-robert** [comment]
Maybe this can be solved by adding an `onload` attribute to https://github.com/LLK/scratch-gui/blob/develop/src/containers/gui.jsx?

**Comment by benjiwheeler** [comment]
I can't reproduce this now.
