### ISSUE TITLE
Project page responsive overall design

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2115]
Tracking work in: https://github.com/LLK/scratch-www/issues/2310

### Overview

For Phase 1, we are focusing on desktop (1280px) and mobile (320px) sizes for these views:

- **Your own project**
- **Someone else's project**

In-between breakpoint sizes are scheduled for phase 2, but I have included them here because @LiFaytheGoblin is already starting some of this work this iteration. 👍1280px and 320px will still be the most important sizes to finish.

### Related Links
**[Invision Screens](https://invis.io/NEO9MT96KDZ)** (for higher res images)
**[Issue: Landscape rotation to GUI on Tablet](https://github.com/LLK/scratch-gui/issues/3229)**

___

### Your Own Project

___

**1280** – Desktop
![my project - empty - 1280](https://user-images.githubusercontent.com/8203939/46096471-495a3c00-c18d-11e8-91ee-28de739ef00e.png)

**1024** – iPad in Landscape
![my project - empty - 1024](https://user-images.githubusercontent.com/8203939/46096502-58d98500-c18d-11e8-82df-e6214bcbda30.png)

**960**
![my project - empty - 960](https://user-images.githubusercontent.com/8203939/46096510-5ecf6600-c18d-11e8-811d-6752fbaae107.png)

**768** – iPad in Portrait
<img src="https://user-images.githubusercontent.com/8203939/46100356-30568880-c197-11e8-8c79-409971ca7686.png" width="384px">

**480**
> Note: After 480px, all options to enter GUI go away. For example, REMIX & SEE INSIDE.
<img src="https://user-images.githubusercontent.com/8203939/46100237-e2da1b80-c196-11e8-8e58-8c64010d65da.png" width="240px">

**320** – Mobile
<img src="https://user-images.githubusercontent.com/8203939/46100230-dd7cd100-c196-11e8-87f1-7eb46e5c1af2.png" width="160px">

### Someone Else's Project

___

**1280** – Desktop
![my project - empty - 1280](https://user-images.githubusercontent.com/8203939/46097186-3f393d00-c18f-11e8-97e5-7b03d812199e.png)

**1024** – iPad in Landscape
![my project - empty - 1024](https://user-images.githubusercontent.com/8203939/46097185-3f393d00-c18f-11e8-93be-92966e938383.png)

**960**
![my project - empty - 960](https://user-images.githubusercontent.com/8203939/46097184-3ea0a680-c18f-11e8-89a9-9b466859f293.png)

**768** – iPad in Portrait
<img src="https://user-images.githubusercontent.com/8203939/46097183-3ea0a680-c18f-11e8-9494-d978222cf9ec.png" width="384px">

**480**
> Note: After 480px, all options to enter GUI go away. For example, REMIX & SEE INSIDE.
<img src="https://user-images.githubusercontent.com/8203939/46097182-3ea0a680-c18f-11e8-856c-e8e5edeb8ebc.png" width="240px">

**320** – Mobile
<img src="https://user-images.githubusercontent.com/8203939/46097277-8293ab80-c18f-11e8-9c8c-e6dd681a7d16.png" width="160px">

**Comment by kathymakes** [comment]
Thought it might be good to also add the "success" state for your shared project:

![image](https://user-images.githubusercontent.com/8203939/46486903-bd6b9400-c7cc-11e8-8281-79f4bf6a52d8.png)

**Comment by locness3** [comment]
There should still be an overlay between the green flag and the project stage

**Comment by locness3** [comment]
I think mobile should have a search too

**Comment by kathymakes** [comment]
@locness3 Good catch on both of those, thanks!

**Comment by kathymakes** [comment]
@locness3 Wanted to let you know that we don't have plans to implement search bar for mobile in the near future but it is on our list to get done later! There are a host of reasons we aren't able to do it right away. Just in case you don't see any of the UI drawings update in the near term :) Thanks for pointing it out.

**Comment by locness3** [comment]
I imagine something like this : 

![base](https://user-images.githubusercontent.com/37651007/46820647-043a2a80-cd87-11e8-9504-9aed9df340fb.png)

And this when you click Search icon : 

![search clicked](https://user-images.githubusercontent.com/37651007/46820672-13b97380-cd87-11e8-970d-5a73462cb68b.png)

Yeah it's very pixelated x) I used icons from the website directly

**Comment by kathymakes** [comment]
@locness3 Nice! Yeah I like that pattern, I think we would do something like that; we could have an icon expand to take up the full space. Thanks for sharing :)

**Comment by kathymakes** [comment]
Following our conversation, we decided to have read only comments after 480px. Here's an example:

![image](https://user-images.githubusercontent.com/8203939/48137611-74e24300-e270-11e8-8407-6ff98853a509.png)

Reply & post box are gone.

**Comment by locness3** [comment]
Difficult to get the mobile keyboard interaction right now ?
