### ISSUE TITLE
On MS Edge, See inside causes weird querystring URL to load

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2127]
To reproduce:

1. On Edge, load the preview page
![screen shot 2018-09-27 at 4 38 40 pm](https://user-images.githubusercontent.com/3431616/46173336-f3ac8f00-c273-11e8-8cd8-5982a732daca.png)
2. Now click "See inside". The editor loads fine, at first...
![screen shot 2018-09-27 at 4 39 14 pm](https://user-images.githubusercontent.com/3431616/46173339-f3ac8f00-c273-11e8-80bc-e12d807a2756.png)
3. But then, immediately after the editor loads, the url navigates to `scratchl.ly/preview/[project number]/editor/?title=MYTITLEHERE&instructions`
![screen shot 2018-09-27 at 4 39 19 pm](https://user-images.githubusercontent.com/3431616/46173340-f3ac8f00-c273-11e8-9e17-07ada269af0e.png)

**Comment by paulkaplan** [comment]
Can't repro this anymore. closing.
