### ISSUE TITLE
Make remixed projects not shareable until the user makes a change

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-www#2130]
I think that you shouldn't be allowed to share remixes until you make a change. This would be useful because many users just remix projects as spam, or to pretend the project is their own, and not make any changes to it. Some other users are so desperate to get this feature that they invent their own "remix detectors" (and some do work, not sure how). Also, projects should take the parent project's comment enabled/disabled status. My parents at first didn't want comments enabled, but if someone remixed (without changing a thing) and then commented on the remix, it would still basically be a comment for me, when I disabled comments.

### Steps to Reproduce

N/A

### Operating System and Browser
All

**Comment by benjiwheeler** [comment]
I like this idea. It might be a bit tricky to implement, but possible.

**Comment by apple502j** [comment]
No Support, there are two allowed case:

* The author might use remix to transfer the projects to their test accounts.
* Some people might use remix to translate strings inside Notes. (like SDS)

**Comment by benjiwheeler** [comment]
Thanks for the counter-examples. Not sure if this change makes sense or not. I will bring it up for long-term discussion. For now, I'm going to close it as something that we do not have plans to implement, but we'll revisit it after 3.0 launch.

**Comment by apple502j** [comment]
@benjiwheeler After one year are you going to revisit it?

**Comment by benjiwheeler** [comment]
@apple502j Thanks for the reminder. I'll bring this up with the team. Do you have thoughts on whether it makes sense to do or not, on balance? Seems like it might help in most cases, but might be very annoying in some cases.
