### ISSUE TITLE
Mobile designs for read-only fields (short term)

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2140]
### Overview
We will eventually have editable fields on mobile, but not before initial launch.
In the short term, we want to communicate that editing won't be an option. All of these are designs for "read only" fields.

### Designs

**Tablet size - Comments are read only**
![explore more - 768 copy](https://user-images.githubusercontent.com/8203939/46961367-9df72580-d06e-11e8-83a1-5257dc797a7a.png)

**Phone size - Comments are read only**
<img width = "200" src = "https://user-images.githubusercontent.com/8203939/46961316-81f38400-d06e-11e8-9a9b-3269702b941b.png">

**Tablet size - Your own project page - read only**
![no editable fields - 768 copy](https://user-images.githubusercontent.com/8203939/46422928-5d5ceb00-c703-11e8-86d5-31e3ffdb71a5.png)

**Phone size - Your own project page - read only**
<img width = "200" src = "https://user-images.githubusercontent.com/8203939/46422927-5d5ceb00-c703-11e8-8913-071eb53779c6.png">

**Comment by towerofnix** [comment]
"Comments are read only" - Is this the case of "commenting disabled" (seems not, since the "commenting on" toggle) or just that you can't leave comments on mobile? If the latter - maybe these aren't the final designs - but there are "Reply" links beside the comments?

**Comment by kathymakes** [comment]
@towerofnix Sorry for the late response, yes you're right! The reply links should not exist until later. Thanks for the catch.

**Comment by benjiwheeler** [comment]
Should there be delete and report links?

**Comment by kathymakes** [comment]
Our decision - can toggle commenting on mobile. But for now, don't include delete & report. Feels a bit weird if you can only delete comments but you can't post new comments. Very subtractive state to be in

**Comment by benjiwheeler** [comment]
Reassigned to January 2019, following @thisandagain's reassigning of https://github.com/LLK/scratch-www/pull/2512 to January

**Comment by benjiwheeler** [comment]
Question: should the text by the comments toggle read "Commenting on" or "Turn commenting off"? And should it be before or after the toggle?
