### ISSUE TITLE
New project page: Fullscreen mode when switching to landscape even if not expected

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#2142]
So when you are on a phone in portrait orientation and view the new project page and open a modal such as report and then switch to landscape the fullscreen player will appear even though this is not what is expected.

On orientation change, the fullscreen player should only appear of no modal is open. Are there more restrictions to when the fullscreen player should automatically appear or not?

**Comment by thisandagain** [comment]
Resolved in #2145
