### ISSUE TITLE
Spec – Comment States

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2144]
### Comment States
___

**Spec Overview**
- Normal states
- Hover/Select states
- Delete/Report states
- Actions
- Tooltips

**Related Issues**
- [Spec – Comment Replies & Threads](https://github.com/LLK/scratch-www/issues/2167)
- [Comment actions for admins](https://github.com/LLK/scratch-www/issues/2080)
- [Comment actions for regular users](https://github.com/LLK/scratch-www/issues/2087)
- [Comment matrix](https://github.com/LLK/scratch-www/issues/2063) (Might be outdated)

___

**Normal States**

![sizing](https://user-images.githubusercontent.com/8203939/46484879-a460e400-c7c8-11e8-9873-1a76c4b266c6.png)

**Hover, Delete, Report, Selected States**

![image](https://user-images.githubusercontent.com/8203939/46971917-474c1480-d08b-11e8-8194-78e23743453e.png)

**Actions**
> For actions, the ordering is "Report," "Copy Link," (for admins) and always "Delete" last.
These are ordered so that the most constant/unchanging ones will always be most right aligned.

<img width ="250" src = "https://user-images.githubusercontent.com/8203939/46483898-b477c400-c7c6-11e8-912f-7e3daea7e34a.png">

**Tooltips**
> When a link is copied, use the tooltip we use in other parts of GUI, with a blue background.

<img width ="250" src = "https://user-images.githubusercontent.com/8203939/46679255-96d6a000-cbb4-11e8-9e13-39d3f780ebe0.png">

<img width ="250" src = "https://user-images.githubusercontent.com/8203939/46679231-8d4d3800-cbb4-11e8-92c6-6d610b8e8425.png">

**Comment by kathymakes** [comment]
### Spec – Replying to a Comment

![replying - child](https://user-images.githubusercontent.com/8203939/46686003-e9b85380-cbc4-11e8-9710-e9dcfb03288a.png)
![image](https://user-images.githubusercontent.com/8203939/46686007-ef159e00-cbc4-11e8-9494-5ddb19fdf8de.png)

![image](https://user-images.githubusercontent.com/8203939/46686025-fa68c980-cbc4-11e8-947d-39d9a065095a.png)

![replying - expanded 1](https://user-images.githubusercontent.com/8203939/46685815-5f6fef80-cbc4-11e8-9ee2-11d0acf26d05.png)
![replying - expanded 2](https://user-images.githubusercontent.com/8203939/46685816-5f6fef80-cbc4-11e8-8589-9f175934b29c.png)

**Comment by kathymakes** [comment]
**Update:** After chatting with mods today, we're decided not to have the "deleted" gray state, and just style both as the red state.

**Comment by locness3** [comment]
@kathymakes Why Copy Link is only for admins ?

**Comment by locness3** [comment]
@kathymakes Why Copy Link is for admins only ?

**Comment by thisandagain** [comment]
@kathymakes @paulkaplan Are we ok to close this?
