### ISSUE TITLE
Use variables for media queries for consistency

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-www#2156]
After #2153: Make sure the new media query variables from src/_frameless.scss are used everywhere in www instead of the repeatedly written media queries in the various scss files to ensure consistency.

Example:
Instead of "@media only screen and (min-width : #{$mobile}) and (max-width : #{$tablet}-1)"
use "@media #{$medium}"

**Comment by sjgllghr** [comment]
I’d like to work on this if no one else has started already. 

Should this include uses of `@media only screen and (max-width: $mobile - 1)` etc. within _frameless.scss itself? For example: https://github.com/LLK/scratch-www/blob/9e1741f8839d94571289fd0b2f7e0ca7f7256459/src/_frameless.scss#L73-L77
