### ISSUE TITLE
Cannot search with words containing percent

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#2160]
We cannot search with `100%pen`.

### Steps to Reproduce
1. Search `100%pen` projects
2. Fail and error page

### What's wrong?
https://github.com/chen-robert/scratch-www/blob/develop/src/views/search/search.jsx#L81

%pe is invalid so it raises URIError.

### Operating System and Browser
On Windows 10 Firefox 62

**Comment by apple502j** [comment]
Duplicate of #1153
However, it was closed.

**Comment by chen-robert** [comment]
I'll take a look at this.
