### ISSUE TITLE
Spec - Replying to a Comment (WIP)

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2167]
### Replying to a Comment
___
**Still need to include**
- Reply editor with error message (e.g. too many characters)
- Reply editor with #search-query

**Related Issues**
- [Spec – Comment States](https://github.com/LLK/scratch-www/issues/2144)
- [Comment actions for admins](https://github.com/LLK/scratch-www/issues/2080)
- [Comment actions for regular users](https://github.com/LLK/scratch-www/issues/2087)
___

**Replies should always...**
- appear at the very bottom of a thread (sorted chronologically, oldest -> recent)
- scroll to your reply so you know where your reply went
- include the "@" for the original poster you're replying to
- be in "selected" state

**The editor field should always...**
- appear under the comment you are replying to (for context)

—
_e.g. a Parent Comment_

![image](https://user-images.githubusercontent.com/8203939/46744401-17f76b00-cc79-11e8-8d53-de1b792a62a3.png)
![replied - parent](https://user-images.githubusercontent.com/8203939/46744387-1332b700-cc79-11e8-8ba1-514f05b1647c.png)

—
_e.g. a Child Comment_

![replying - child](https://user-images.githubusercontent.com/8203939/46745149-7e30bd80-cc7a-11e8-8635-50dca4266b4b.png)
![replied - child](https://user-images.githubusercontent.com/8203939/46745151-7ffa8100-cc7a-11e8-8037-d978be3e7dfe.png)

**Replies in a collapsible thread should always...**
- expand the "See all..." action and scroll you to the bottom of the thread

—
_e.g. Before clicking "reply"_

![image](https://user-images.githubusercontent.com/8203939/46686025-fa68c980-cbc4-11e8-947d-39d9a065095a.png)

—
_e.g. After clicking "reply"_

![replying - collapsed](https://user-images.githubusercontent.com/8203939/46745253-b6380080-cc7a-11e8-9aa8-8f18139c9bdf.png)

—
_e.g. After posting your reply_

![replied - expanded](https://user-images.githubusercontent.com/8203939/46745264-b9cb8780-cc7a-11e8-99fd-5ee0e78a25da.png)

**Comment by kathymakes** [comment]
**Design for Collapsible Threads**

Here's the design for threads which hide comments after the 3rd threaded comment. Sizing + styling for reference:

![image](https://user-images.githubusercontent.com/8203939/46679805-b8845700-cbb5-11e8-97ae-1e704a886d08.png)

**Comment by kathymakes** [comment]
Hey @towerofnix , good observation - we are planning to add tags in Notes & Credits (project metadata) and also in comments, so that clicking on a tag will search that tag. We won't have it in Scratch until after launch (January), but stay tuned. Hope that helps :)

**Comment by kathymakes** [comment]
Hey @joker314 thanks for your message! I think those are really good questions- it's kind of confusing to have "@username" in the editor, and I think intuitively it would make sense that you can edit them.

I'm going to make some changes to the spec so that we won't have "@username" in the field anymore, though #search-query should still be "blue" or active. Still deciding how to treat that- thanks for your thoughts!

**Comment by thisandagain** [comment]
@kathymakes @paulkaplan Can this be closed?
