### ISSUE TITLE
Navigation - Make top navigation and footer responsive

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#217]
All of the work we are doing to integrate grid systems and flex box into our new views is limited by the fact that our navigation is not responsive which leads to some bugs (see: #214) as well as a less than ideal viewing experience on mobile devices.

- [x] Design responsive top navigation
- [x] Design (or eliminate) responsive footer
- [ ] Implement updated top navigation
- [ ] Implement updated footer

/cc @carljbowman @kaschm @mewtaylor @rschamp

**Comment by thisandagain** [comment]
@carljbowman Can you share specs with @mewtaylor when you are ready? It would be nice to get this wrapped up this iteration.

**Comment by carljbowman** [comment]
## Responsive Nav / Footer 
*omg it's happening* 🎉

**Overview Deck: [R3_Responsive Nav & Footer.pdf](https://github.com/LLK/scratch-www/files/354249/R3_Responsive.Nav.Footer.pdf)**

--

### Navigation Logged Out

- [ ] Change 'Join Scratch' to 'Sign up' verbiage across the site: navigation, sign up flow
- [ ] Change 'Sign in' to 'Log in' verbiage across the site: navigation, login dropdown, editor nav

#### 12 cols
![r3_responsive nav footer_nav - desktop - logged out](https://cloud.githubusercontent.com/assets/3409578/16688429/0b1bfc5a-44ec-11e6-9919-d6543122f10a.png)

#### 8 cols 
![r3_responsive nav footer_nav - tablet to desktop - logged out](https://cloud.githubusercontent.com/assets/3409578/16688439/1b56bc90-44ec-11e6-92c2-ba01887633df.png)

#### 6 cols
![r3_responsive nav footer_nav - mobile to tablet - logged out](https://cloud.githubusercontent.com/assets/3409578/16688461/2e1a998c-44ec-11e6-9294-07235300bbac.png)

#### 4 cols
![r3_responsive nav footer_nav - mobile - logged out](https://cloud.githubusercontent.com/assets/3409578/16688469/368d7e40-44ec-11e6-85b9-ae7dcad98db5.png)

-----

### Navigation Logged In

#### 12 cols
![r3_responsive nav footer_nav - desktop - logged in](https://cloud.githubusercontent.com/assets/3409578/16688498/50eacedc-44ec-11e6-98d4-ddf07dda485e.png)

#### 8 cols
![r3_responsive nav footer_nav - tablet to desktop - logged in](https://cloud.githubusercontent.com/assets/3409578/16688503/577f524a-44ec-11e6-8c5f-102cccd21744.png)

#### 6 cols
![r3_responsive nav footer_nav - mobile to tablet - logged in](https://cloud.githubusercontent.com/assets/3409578/16688511/61cc926c-44ec-11e6-8a0a-9f68f2fa9c03.png)

#### 4 cols
![r3_responsive nav footer_nav - mobile - logged in](https://cloud.githubusercontent.com/assets/3409578/16688516/691978aa-44ec-11e6-8ce2-d48c92061e8a.png)

-----

### Footer

#### 12 cols
![r3_responsive nav footer_footer - desktop](https://cloud.githubusercontent.com/assets/3409578/16688530/77d24bb0-44ec-11e6-9dc2-9067f5b833c2.png)

#### 8 cols
![r3_responsive nav footer_footer - tablet to desktop](https://cloud.githubusercontent.com/assets/3409578/16688541/82f88266-44ec-11e6-8e2e-ad07c3cb5129.png)

#### 6 cols
![r3_responsive nav footer_footer - mobile to tablet](https://cloud.githubusercontent.com/assets/3409578/16688550/8a00238e-44ec-11e6-833a-ed2ef4d6e926.png)

#### 4 cols
![r3_responsive nav footer_footer - mobile to tablet copy](https://cloud.githubusercontent.com/assets/3409578/16688555/9194021e-44ec-11e6-9ca2-d07fd10dc1c9.png)
