### ISSUE TITLE
Join flow is broken

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-www#2175]
Clicking 'Join Scratch' on the home page, leads to an "Oops" page.

### Steps to Reproduce

1. Click 
![image](https://user-images.githubusercontent.com/1786240/46824245-3edb9d00-cd5e-11e8-8adf-ced73d5fc6de.png)

2. Observe: 
![image](https://user-images.githubusercontent.com/1786240/46824220-2cf9fa00-cd5e-11e8-8207-90086f3e107d.png)

**Comment by benjiwheeler** [comment]
Looks like https://github.com/LLK/scratch-www/pull/2165 didn't fix this.

Looks like the final version we went with -- https://github.com/LLK/scratch-www/pull/2165/commits/791ea5518ebbf563d3311f4d2ac0ce75c3dd29c8 -- didn't cover every case after all.

Looks like a previous version -- https://github.com/LLK/scratch-www/pull/2165/commits/1da35e9d181b825817ebe80aa6b7852a678c004d -- does solve this problem.

**Comment by benjiwheeler** [comment]
Fixed by https://github.com/LLK/scratch-www/pull/2176
