### ISSUE TITLE
Spec – Editor Errors

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2178]
## Editor Errors

**Related Issues**
- [Spec – Comment Replies & Threads](https://github.com/LLK/scratch-www/issues/2167)
- [Comment actions for admins](https://github.com/LLK/scratch-www/issues/2080)
- [Comment actions for regular users](https://github.com/LLK/scratch-www/issues/2087)
- [Comment matrix](https://github.com/LLK/scratch-www/issues/2063) (Might be outdated)
___

### Example Use Cases

**Example 1**
Short form error - e.g. can't post empty comment
![error - can t post empty](https://user-images.githubusercontent.com/8203939/46832008-f4185000-cd72-11e8-99ac-c84927b2df6f.png)

**Example 2**
Longer form error - e.g. bad word
![error - bad word](https://user-images.githubusercontent.com/8203939/46832007-f4185000-cd72-11e8-9669-52261e11d361.png)

**Example 3**
Maxed out character count
![error - too long](https://user-images.githubusercontent.com/8203939/46832009-f4185000-cd72-11e8-9d90-eb30c0a4db69.png)
___
### Reply
These errors also appear in-line when you reply to comments. 

![reply error - too long](https://user-images.githubusercontent.com/8203939/46832716-bfa59380-cd74-11e8-82cf-34d0d095160e.png)
___
### Mobile
These are similar to the pattern we use for mobile tooltips– flush to the width of the screen.

<img width = "250" src = "https://user-images.githubusercontent.com/8203939/46832446-08a91800-cd74-11e8-9df3-6d7f40e417e5.png">
<img width = "250" src = "https://user-images.githubusercontent.com/8203939/46832452-0e9ef900-cd74-11e8-951c-9fdb469cee49.png">
<img width = "250" src = "https://user-images.githubusercontent.com/8203939/46832449-0c3c9f00-cd74-11e8-99d8-bf45ce4540a3.png">

**Comment by kathymakes** [comment]
**Note:** Even if there are multiple errors, we will just show one error at a time
A good "order of operations" might be censoring/filtering bad words first, then errors about length?

**Comment by DeleteThisAcount** [comment]
could we make the comment area have a fixed length instead of telling the user when they are in negitive comments.

like how it is currently.

because that would be really annoying while typing looong paragraphs and then finding out you are forexamole -100 chars passed the limit

**Comment by kathymakes** [comment]
@DeleteThisAcount Yeah, thanks for bringing that up! We were leaning towards both approaches, they definitely have pros and cons. We were thinking it's a little more forgiving to be able to go over the limit and then edit your post, since what people might do now is repaste into a text file somewhere. But maybe we can also cap it at a negative number so that people don't go waaaay over the limit and then have to cut down? Potentially they could write another comment :)

**Comment by Kenny2github** [comment]
> go over the limit and then edit your post
You mean before posting? Nah, if you're exceeding the limit it's already time to edit it.
> what people might do now is repaste into a text file
You mean from a text file? Pasting into a comment from a text file is indeed something people do; I think you're right here, but the pasting should be handled separately:
* If pressing a key would take the character count over the limit, prevent it entirely
* Allow pasting any length of text
* If a key is pressed while already over the limit from a paste, allow it; as soon as it's within the limit, any keypresses that would take it over the limit are once again prohibited

**Comment by kathymakes** [comment]
I think github glitched and deleted my original comment. Reposting here:

<img width="784" alt="screen shot 2018-10-22 at 10 41 36 am" src="https://user-images.githubusercontent.com/8203939/47367864-922ee300-d6ae-11e8-8386-cdb9aa16da06.png">

**Comment by DeleteThisAcount** [comment]
i have an idea.

comments could be up to an increased limit of 1000 chars.

but will require a read more click to view.

and text can reach -1000 as a hard limit

and recomend short and sweet comments when you click post but allow for posting 1000 char comments

**Comment by thisandagain** [comment]
@kathymakes @paulkaplan Sorry ... one more. Can this be closed? It would be nice to have any remaining work split out into separate issues.
