### ISSUE TITLE
Tags overlapping with Notes and Credits section

### ISSUE THREAD

**Issue by sehgalvibhor** [LLK/scratch-www#2185]
For some projects, the tags are overlapping the Notes and credits section. I am able to replicate this in Mozilla Firefox, Chrome and Edge. Attached screenshot for reference:

![image](https://user-images.githubusercontent.com/10993808/46927146-a3924280-d051-11e8-9ac9-f96090ddbb6c.png)

### Steps to Reproduce

Open the projects with project id 237198187, 239000001. In the Notes and Credits section see the tags are overlapping with the text.

### Operating System and Browser

Windows 10, Chrome/Firefox/Edge

**Comment by towerofnix** [comment]
I've definitely seen this before. I doubt the ST will work on fixing it now though - they have already built a nearly fully-functioning project page with scratch-www, probably to be published in January with the release of 3.0. I don't think this is an issue in that new project page.

**Comment by thisandagain** [comment]
We are tracking this in the new project page for Scratch 3.0.
