### ISSUE TITLE
'Copy link' should work, and help user see that it works

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2200]
@kchadha writes:

> The ‘copy link’ button has no visual feedback that anything happened when you clicked on it... 

Does this need design?

**Comment by kchadha** [comment]
I think it also has no functionality attached to it...? There was nothing copied to my clipboard when I clicked on it.

**Comment by benjiwheeler** [comment]
Resolved by https://github.com/LLK/scratch-www/pull/2343

**Comment by kathymakes** [comment]
We can do a tooltip here like we do with comment "copy link." 
<img width="240" alt="screen shot 2018-12-03 at 5 35 22 pm" src="https://user-images.githubusercontent.com/8203939/49405918-00d97480-f722-11e8-87d3-50dcad6ba71f.png">

fill: white
font color: UI blue
border: 1px UI blue at 50% opacity

**Comment by rschamp** [comment]
This is non-trivial until we have a reusable tooltip component in www :/
