### ISSUE TITLE
project page info textareas not handling apostrophes

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2205]
@ericrosenbaum writes:

> On iOS Safari, on player page, apostrophes in instructions/notes and credits show up incorrectly as ' and they also turn into blue links. 
![46354994-e0ac0d00-c62d-11e8-843b-8b21ba405007](https://user-images.githubusercontent.com/3431616/47118550-9635ad80-d235-11e8-8849-c42ff263fbbb.png)

**Comment by thisandagain** [comment]
This appears to be resolved:
![image](https://user-images.githubusercontent.com/747641/52232317-36b5e900-288a-11e9-80f3-000d5cec45b2.png)
