### ISSUE TITLE
Project header Avatar component should use an environment variable for the CDN domain

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2215]
[Update: https://github.com/LLK/scratch-www/pull/2289 introduced a `STATIC_HOST` variable which we should use for this purpose!]

on scratch.ly, the menubar avatar thumbnail loads fine; the URI it's using is
https://scratch.ly/get_image/user/100021916_32x32.png

but the avatar thumbnail next to the project page title is 503'ing; the URI is
https://cdn2.scratch.mit.edu/get_image/user/100021916_48x48.png

It's causing the avatar not to load by project title, even when it's fine in the menu bar:
![47318794-03bd5180-d61b-11e8-978d-c653955462fc](https://user-images.githubusercontent.com/3431616/47691764-ba947100-dbc9-11e8-877e-43d9a40195c1.png)

is this a fastly configuration issue? are we ok with it?

**Comment by colbygk** [comment]
That cdn2.scratch.mit.edu is incorrect, it should probably be cdn.scratch.ly

/cc @rschamp

**Comment by rschamp** [comment]
It's using a hardcoded domain when it should be using a variable: https://github.com/LLK/scratch-www/blob/48e70307c8aec75b9452e926f8debc273d46b0cb/src/views/preview/presentation.jsx#L106

**Comment by benjiwheeler** [comment]
Resolved by #2322
