### ISSUE TITLE
URGENT: Homepage shows wrong SDS

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-www#2219]
This is not the SDS:
![image](https://user-images.githubusercontent.com/31634240/47259622-d6856d80-d479-11e8-9c01-701fc9724afe.png)

### Steps to Reproduce

Go to the Scratch homepage.
### Operating System and Browser

All

**Comment by towerofnix** [comment]
Relevant (but I haven't watched it yet): https://www.youtube.com/watch?v=f24OAfVQQJE

**Comment by towerofnix** [comment]
Update - this seems to be fixed. It's now [Create Your Own Restaurant](https://scratch.mit.edu/studios/5541632/). However, I had to reload ignoring cache (ctrl-shift-R, or clear your cache) to see the updated studio.
