### ISSUE TITLE
Do we need to alter (or even keep?) /create route that creates new project?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2225]
Currently, we redirect from `/create` to `/preview/editor?tip_bar=home` . However, it does not look from our logs like this route is used much; from our homepage, "Create" just links directly to `/preview/editor?tip_bar=home` .

This redirect is currently done by scratchr2, by returning a 301 with the html content and url for `/preview/editor?tip_bar=home` .

* should we keep this there?
* should we remove this and put it directly into fastly instead?
* should we use www's routes.json to do it (and remove it from scratchr2), like 
```
    {
        "name": "create",
        "pattern": "^/preview/create/?$",
        "routeAlias": "/preview/create/?$",
        "redirect": "/preview/editor?tip_bar=home"
    },
```
?

Note https://github.com/LLK/scratch-www/issues/2236 , which uses `tutorial` instead of `tip_bar`.

**Comment by chrisgarrity** [comment]
I'd like to consolidate some of these URL issues.
I think there are three classes of URLs
Shortcuts: These are redirects (usually in scratchr2) that provide a short name for another URL, tracking in #2270 
Tip-Bar redirection: redirects in Fastly that maps `?tip_bar=...` to `?tutorial=...` tracking in #2236 
Handle hash URLs: e.g., `#editor` tracking in #2095 

Note: the shortcuts are things that we have used in publications, so even if they don't get much use we need to support them.
