### ISSUE TITLE
Sharing from new projects page puts project at the end of the list

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2227]
If, as one user, you share a project from the 3.0 project page and then from a second user look at the projects shared by the first user (users/[username]/projects/) the newly shared project will be at the end of the list.

If you share it from the 2.0 project page it appears at the start of the list.  

I made two copies of the same project and shared 1 from 2.0 and one from 3.0.
![screen shot 2018-10-23 at 12 05 42 pm](https://user-images.githubusercontent.com/1088291/47380579-cd8bda80-d6cb-11e8-882c-8b3a4c6b615b.png)

### Steps to Reproduce

Sign in as a user
Create a new project
Navigate to the project page
change `/project/` to `/preview/` in the url
Click the share button in the upper right of the project page
Sign out
navigate to the user's user page `/users/username`
Click view all on the Shared Projects row
Note: the newly shared project is at the end of the list.

### Operating System and Browser

Mac Chrome, Mac Firefox

**Comment by thisandagain** [comment]
@BryceLTaylor Can you confirm that this is still happening. The root cause is issues with the `datetime_shared` and `datetime_first_shared` fields in the DB.

**Comment by BryceLTaylor** [comment]
This appears to be working properly at the moment.  I shared a project from the 3.0 project page on scratch.ly and as another user it was at the start of the list.  I'm closing this issue.
