### ISSUE TITLE
On ipad, typing into a text field on project page on causes page to reload

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2233]
On ipad safari, if you go to the 3.0 project page and start typing into a text field, such as a project title, comment, or project description, the page will reload and give an error message:

`A problem occurred with this webpage so it was reloaded.`

![img_0036](https://user-images.githubusercontent.com/1088291/47460985-b1606a00-d7ad-11e8-8fc3-ce9d4d9c66cd.PNG)

After it reloads, if you select one of the text fields and start typing, no text appears.  They keys on the keyboard give no feedback as if they were pressed.

### Steps to Reproduce

Sign in on scratch.ly
Navigate to a project page for a project you own 
Change projects to preview in the url
select a text field such as a comment or the project title
Begin typing on the soft keyboard
Note: the page reloads and gives the error
Select the text field and try typing again
Note: no text appears and the keyboard gives no feedback.

### Operating System and Browser

safari on ios 10.3.1

**Comment by thisandagain** [comment]
@BryceLTaylor Before @benjiwheeler starts looking at this next month can you confirm that this is still an issue?

**Comment by BryceLTaylor** [comment]
@thisandagain I'm not seeing this anymore.  It's looking good.
