### ISSUE TITLE
display notification after sharing, including special text for first time sharing

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2240]
On current production site, first time sharing shows notification text: "Congratulations on sharing your project! Other people can now try it out, give comments, and remix it." Subsequent project shares then show "Your project is now shared."

We should replicate a similar experience in 3.0.

This presents a complication, though: currently, shared status is updated for the project via a simple project metadata PUT to an API endpoint. API doesn't do any complex querying to see if the share is the user's first share ever.

There are a few ways we could address this:
1. change the project info updating endpoint to do complex querying if the project is set to be shared
2. create a different, sharing-only endpoint that does the logic from # 1
3. Skip the complex logic entirely and instead use another property of the user as a basis for which message we show, such as whether or not they are a scratcher

I vote for # 3!

**Comment by carljbowman** [comment]
@benjiwheeler - Thanks for logging this issue!

There is a lot more that we can do to create a better share experience! We have some addtional ideas for both the first share experience but also more generally improve the share flow to prompt adding a title and project information if that information is missing. 

This work will also intersect with a larger initiative of improving the overall early experiences (onboarding) with Scratch. There are a few things in 2.0, like New User (which needs a new name) becoming a Scratch, but it's rather obscured. Totally agree, we can make these first time experiences more celebratory and exciting! 

Likely before we get to this particular work in this issue, we have a lot to do on the very first touch point with first time users, the sign up flow.

**Comment by DeleteThisAcount** [comment]
just gonna say this here


the new scratchers share message is so encouraging for some reason, i would love if it showed more often lol

**Comment by kathymakes** [comment]
Thanks @carljbowman! Yeah, that sums up where we are with design for now - hoping for a holistically thoughtful experience for new scratchers! I would be OK with showing a "Congratulations" message either the first project or the first few projects until they become a scratcher. Can draw up

**Comment by kathymakes** [comment]
For now (release), we can keep the same simple visual styling. @benjiwheeler 
![project page success alert](https://user-images.githubusercontent.com/8203939/47669267-e8a19300-db80-11e8-9c3c-12f756b3db6d.png)
