### ISSUE TITLE
Keyboard input lost in Firefox (and perhaps others)

### ISSUE THREAD

**Issue by chainjazz** [LLK/scratch-www#2247]
It seems that keyboard input gets lost (for anything you need to type in), in particular, it seems the Flash plug-in doesn't pass the keyboard input.

There is an immediate solution, which points to the direction of the problem:
if you "get out" of the Flash plugin, e.g. by selecting some text input feature of the browser interface itself, the keyboard input is regained)

### Steps to Reproduce

0. Open your browser
(0.1 Switch to full screen)
(0.2 Make sure your browser does not autostart flash plug-in)
1. Open a Scratch project
(1.1. Allow the Flash plug-in to run in the current session)
2. See inside
3. Work a little bit, start, stop, re-arrange blocks
4. Try to use keyboard to input anything that accepts keyboard input (in the plug-in), eg.
change var names, create new blocks, change numeric values in blocks
--- error: no keyboard input registered

### Operating System and Browser

Windows 7 x64, Firefox 62.0.3

**Comment by thisandagain** [comment]
Moved to LLK/scratch-flash#1404
