### ISSUE TITLE
Load More does nothing on My Stuff page

### ISSUE THREAD

**Issue by sehgalvibhor** [LLK/scratch-www#2252]
### Steps to Reproduce

Create few projects, open 'My Stuff'. Despite the number of projects, 'Load More' button is visible but does nothing. The window size keeps increasing and when you press 'Load More' it will append nothing to the project list. Basically, it seems to be a never ending project list. Shouldn't the project list expand on clicking 'Load More'?

Projects Created : 15

Before Pressing Load More:
Shows all the 15 projects, and still exists as button.

![image](https://user-images.githubusercontent.com/10993808/47693294-1bf12a00-dc34-11e8-8318-c745352e9ad1.png)

After Pressing Load More:
Does nothing, just disappears! 

![image](https://user-images.githubusercontent.com/10993808/47693331-42af6080-dc34-11e8-89a5-313d8e01988a.png)

### Operating System and Browser

Windows 10, Chrome Version 69

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#5209
