### ISSUE TITLE
AddToStudio submission sometimes appears to work... but doesn't

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2255]
@chrisgarrity reports:

> Chris successfully added https://scratch.ly/preview/1000015439/ to studio https://scratch.ly/studios/10002341/ , but adding to https://scratch.ly/studios/10002352/ appears to succeed but really never adds (and is not green when you reload project page)

**Comment by BryceLTaylor** [comment]
I am able to add projects to studios I own and ones I don't.  I'm not sure what the difference between those studios are.  If we see this again we can reopen this issue.
