### ISSUE TITLE
Chess Escape's code area comments cause remixing to BSOD

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2261]
@kchadha writes: 

> Attempting to remix the chess escape project (featured project, 26069997) results in the gui oops page. Safari claims the following errors in the console:

![47670750-5bf8d400-db84-11e8-84cf-da7bbe6a9812](https://user-images.githubusercontent.com/3431616/47694876-eae20c80-dbd5-11e8-9be5-c86268736acd.png)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-projects#96
