### ISSUE TITLE
Design spec for general use spinner

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2264]
### Overview
This is a design spec for a non-svg, div based spinner animation.

**Relevant issues:**
- **[Loaders in extension alerts](https://github.com/LLK/scratch-gui/issues/2811#issuecomment-434006353)**
- **[Loaders during comment posting](https://github.com/LLK/scratch-www/issues/2195)**

___
### Example 1
Here it is in the **extension alert.**

![spinner-downloading](https://user-images.githubusercontent.com/8203939/47732190-139ced00-dc3c-11e8-92b3-fc3b38d67248.gif)

Note that this is 16px in diameter.
```
   width: 1rem;
   height: 1rem;
   border: 3px solid rgba(255,140,26,0.2);
```
And the spinner "fill" is orange...
```
&:after {
   border-top-color: rgba(255,140,26,1);
}
```
___
### Example 2
Here it is in a **comment "post" button.**

![spinner-button](https://user-images.githubusercontent.com/8203939/47732191-139ced00-dc3c-11e8-81f5-fb99843343e3.gif)

This is 12px in diameter.
```
   width: 0.7rem;
   height: 0.7rem;
   border: 3px solid rgba(255,255,255,0.25);
```
And the spinner "fill" is white...
```
&:after {
   border-top-color: #FFFFFF;
}
```

___
### Spinner CSS
Here is the CSS animation + styles from the codepen I'm using, but feel free of course to change as it makes sense.

```
.spinner {
/*----------------------------------------*/  
/* these sizes + colors are more variable */
   width: [width];
   height: [width];
   border: 3px solid [color name];
/*----------------------------------------*/  
   border-radius: 50%;
   display: inline-block;
   position: relative;

  &:after, &:before {

/*-----------------------------------*/  
/* sizes should be the same as above */
    width: [width];
    height: [width];
/*-----------------------------------*/  

    content: '';
    border-radius: 50%;
    display: block;
  }
  
  &:after {
/*-----------------------*/
/* spinner-specific color */
   border-top-color: [color];
/*-----------------------*/

    position: absolute;
    top: -3px;
    left: -3px;
    border: 3px solid transparent;
    animation: spin 1.5s cubic-bezier(0.4, 0.1, 0.4, 1) infinite;
  }
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}

```

**Comment by towerofnix** [comment]
I think this spinner (or at least a similar one) is also used when signing in via the nav bar.

**Comment by benjiwheeler** [comment]
We now have one of these in www, and another in gui.
