### ISSUE TITLE
Single comment view for notifications - Phase I

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2265]
## Overview
This issue is about the "single comment view" that Scratchers will see when they click on a newly notified comment.

This is the current behavior in 2.0:

![scratchly scroll](https://user-images.githubusercontent.com/8203939/47742388-e445aa80-dc52-11e8-963c-8710e71787e5.gif)

However, we will not be able to do this in 3.0 given issues with performance.

We've come up with a fix so that most scratch projects— which have 20 comments or fewer —will still be able to use the 2.0 scrolling behavior.

For edge cases, we'll isolate a single top-level comment or thread so that we don't load all the preceding pages.

## Proposed UX

Right now, this is the same as what an admin will see when they "copy link" into the URL.

**If comment is within the first page of comments...**
...then load comment in context of first 20 comments.

![first 20 comments](https://user-images.githubusercontent.com/8203939/47733453-a2126e00-dc3e-11e8-93dd-ac9d5052ddbf.png)

**If comment is BEYOND the first page of comments...**
... then load comment (and parent thread + replies) in the “focused view”.

(Additionally, we can load first page of comments instead of greeking?)

![decontextual](https://user-images.githubusercontent.com/8203939/47733452-a048aa80-dc3e-11e8-8f01-9ca34ee62c43.png)

## Considerations

- Need to create more visual distinction between “focused” comment and first page of comments

- We should watch our metrics on replying after launch and see how the numbers are affected by the design.

- In general, we might want to give some more attention to “Reply”

- We can also keep an eye on ways to make the “decontextual” view clearer.
      - e.g. surface next most recently indexed comment? 
      - e.g. greeking versus nongreeking

**Comment by kathymakes** [comment]
@carljbowman Drew up some alternative versions for the single comment view... we can discuss later!

**[Invision Link](https://invis.io/JBOY3LV4DVX)**

**Comment by kathymakes** [comment]
@carljbowman @paulkaplan 
Chatted with Paul and sounds like we don't have the time and resources to split off **1) loaded first page of comments** and **2) decontextual single comment** into separate containers on the same page.

For launch, we feel OK about using the design specced on this page - "See all comments" link with a greeked SVG/component below. 

(Especially because loading comments beyond #20 is somewhat of an edge case)

In the longterm (post launch), we will want to keep recent comments and single comment in a single page. This way, we can keep the feeling of comments being "live," where you can see recent activity all within the same page.

**Comment by carljbowman** [comment]
@kathymakes @paulkaplan - Thanks for thinking through further. While it's not exactly where we want to be, it will set us up nicely for the next steps as Kathy has outlined: providing more context to the focused comment and making sure comments feel "alive". 

@kathymakes - Do you mind filing a issue to track some of these "Comments - Phase 2" ideas while they are fresh.

--- 

A few follow up question or thoughts on the "greeked" direction:

1. Does clicking "See All Comments" take you to the default view of comments: there is no focused comment (previously focused comment returns to inline comment list) and comments appear as if you just loaded a project page?
2. It might be worth continuing to explore the hierarchy of the "See All Comments" link. Right now this link blends in with the greeked comments.

**Comment by kyleplo** [comment]
I like the fifth one best

**Comment by thisandagain** [comment]
@kathymakes @paulkaplan Can we close this?
