### ISSUE TITLE
Typo on the micro:bit page

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#2267]
Under the Troubleshooting section: "Only one computer can be connected to an micro:bit at a time." This should be "a micro:bit", not "an micro:bit"!

**Comment by DeleteThisAcount** [comment]
i can fix this? wouldnt this be in translations though?

**Comment by towerofnix** [comment]
@DeleteThisAcount Maybe in translations, but I think making a change here would work too: https://github.com/LLK/scratch-www/blob/950f13a35a83b009c74a2f35683a62cb419513fc/src/views/microbit/l10n.json#L29

**Comment by chrisgarrity** [comment]
@DeleteThisAcount @towerofnix is correct, you can make the correction in the l10n.json file. That will get sync'd with our translation service.

**Comment by DeleteThisAcount** [comment]
ok cool
