### ISSUE TITLE
Create URL shortcut to Tutorials window

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#2271]
It will be helpful to have a URL we can use to point people to the editor with the Tutorials window open.

scratch.mit.edu/tutorials

It would open the editor and behave as if they clicked the Tutorials button.

**Comment by ntlrsk** [comment]
This shortcut is not working: scratch.mit.edu/tutorials

**Comment by chrisgarrity** [comment]
Actually, I think this needs discussion. The link that opens the editor with the tutorials visible, `https://scratch.mit.edu/projects/editor/?tutorial=all` works for any place that we want to link to the tutorials. However, having a shortcut means that the link is more likely to be out there 'in the wild', and there is no context when you land on the tutorials page - it doesn't even say Scratch. If you hit the back button from the tutorials you are taken to the editor (not the page you came from).
