### ISSUE TITLE
Implement 2018 HOC banner

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#2280]
Add HoC banner - based on the one from last year.

**Comment by carljbowman** [comment]
## Timeline
Display banners on the homepage from Monday, Dec. 3rd to Friday, Dec. 14th

## Banner Mocks
[InVision Sketches](https://invis.io/3YOUQVX48ME)

## States
There are two states for the homepage during Hour of Code, one for logged-out and one for logged in. The two banners display different content and point to different places.

### Logged-out: Top page banner
- Shows three 3.0 activities
  - Getting Started
    - Opens 3.0 editor with “Getting Started” tutorial open on Beta
  - Create Animations that Talk
    - Opens 3.0 editor with “Create Animations that Talk” tutorial open on Beta
  - Animate an Adventure Game 
    - **Slightly different behavior:** opens 3.0 editor with “Animate an Adventure Game” tutorial open and starter project on Beta.
- “See more activities” button - Tracking work here: https://github.com/LLK/scratch-gui/issues/3643
  - Opens 3.0 editor with “Tutorials” library open

### Logged-in: Mid-page banner
- Shows three 2.0 activities
  - Animate a Name
    - Opens 2.0 editor with “Animate a Name” tutorial open
  - Make it Fly
    - Opens 2.0 editor with “Make it Fly” tutorial open
  - Create a Pong Game
    - Opens 2.0 editor with “Create a Pong Game” tutorial open
- “See more activities” button
  - Opens “Tips” page

## Responsive
Display on desktop and horizontal tablet, hide on mobile breakpoints

### Desktop
Display all three activities on both logged-in and logged-out states

### Horizontal Tablet
Display two activities

- Logged-out
  - Create Animations that Talk
  - Animate an Adventure Game

- Logged-in
  - Animate a Name
  - Make it Fly

## Assets
- Logged-out activity images
  - [3.0-hoc-activity-images.zip](https://github.com/LLK/scratch-www/files/2550365/3.0-hoc-activity-images.zip)


- Logged-in activity images 
  - Use assets from Tips page

**Comment by kyleplo** [comment]
Could there be a close button on the banner?
