### ISSUE TITLE
Update Scratch Jr. link in footers to use https

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2297]
These lines should link to the https version of Scratch Jr:
https://github.com/LLK/scratch-www/blob/4b3d6b9e9dab03eb7c75b0ef9f8f8741fb5050a3/src/components/footer/www/footer.jsx#L189
https://github.com/LLK/scratch-www/blob/55f4b5b92ab2b6a1e3e0c060140383470473e2ef/src/components/footer/conference/2016/footer.jsx#L83
https://github.com/LLK/scratch-www/blob/55f4b5b92ab2b6a1e3e0c060140383470473e2ef/src/components/footer/conference/2017/footer.jsx#L26
https://github.com/LLK/scratch-www/blob/5844fed2e0c56d40880ead6ec04e7d2d0a1962d0/src/components/footer/conference/2018/footer.jsx#L102

And then we will also need to update tests:
https://github.com/LLK/scratch-www/blob/bdc22605310b9e46af1165fe6edf62ca0c0a0f4b/test/integration/smoke-testing/test_footer_links.js#L272
https://github.com/LLK/scratch-www/blob/55f4b5b92ab2b6a1e3e0c060140383470473e2ef/test/integration-cypress/cypress/smoke-tests/test-footer-links.js#L265

**Comment by MasterOfTheTiger** [comment]
What is required to fix this? I would like to to so, but is there a caveat somewhere?

**Comment by rschamp** [comment]
No caveat, all that's required is to change `http` to `https` on all those lines above.

**Comment by MasterOfTheTiger** [comment]
I fixed this in #2300.
