### ISSUE TITLE
UX: Downloads Page

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-www#2299]
### Overview
We are redesigning the [Downloads page](https://scratch.mit.edu/download). At a high level, we want to follow the patterns we use for the Extensions pages (example: [Microbit](https://scratch.mit.edu/microbit)) and cut down the content.

Here are more notes and info: [Google Doc](https://docs.google.com/document/d/1otHd3j_Dpa9_6Y_nVCxP5b1DN1yCZWTSntAdI5I_quQ/edit)

### Design
Still a work in progress. Logging to track this work.

![1280px](https://user-images.githubusercontent.com/8203939/48578031-a4cfbd00-e8e6-11e8-8ab3-5b82fa6ba93c.png)

### Still need

- [ ] Finalized copy for the page
- [ ] Screenshots, if we decide to include

### Responsive

Most of our pages that follow the extensions page formula aren't totally optimized for stretching smaller. But here is one potential framework to follow.

This is probably a Phase 2, or lower priority item (especially because this page isn't very useful to folks on phones or tablets.)

Still, would be nice to bake responsive into our styles in the process of building it out, and show it a little TLC!

<img width="1355" alt="responsive" src="https://user-images.githubusercontent.com/8203939/48578087-b913ba00-e8e6-11e8-84bd-f4ad0dc3a2b1.png">

**Comment by kyleplo** [comment]
Maybe mobile screen sizes shouldn't show the download buttons?

**Comment by benjiwheeler** [comment]
We could show something else -- like "Please view this page on a Windows or
Mac computer to download."

What logic are we correctly using to determine which OS to highlight? What
does it currently show for, say, Chromebooks?

**Comment by kathymakes** [comment]
Yeah - good point @kyleplo ! It would be much better to tell them up front than to redirect to the app store (and then not be able to do anything.) 

I think for Chromebook, maybe they could both be dimmed out?

**Comment by MasterOfTheTiger** [comment]
Wait. I do not see a GNU/Linux option. Electron supports it right?

**Comment by thisandagain** [comment]
@masterofthetiger Linux will not be available at launch, but we are working with some partners of Linux (Raspberry Pi in particular) support for later in 2019.

**Comment by kathymakes** [comment]
### A few changes...

The current illustration of GUI might communicate, "Here is the scratch 3.0 editor," but if we wanted to emphasize that this is a downloadable editor, we can alternatively try this illustration:

![image](https://user-images.githubusercontent.com/8203939/49405176-a9d2a000-f71f-11e8-842d-e6e6027cbb54.png)

___
Another change to suggest is that we could move "Direct Link" from here...

<img width = "200" src = "https://user-images.githubusercontent.com/8203939/49405229-cc64b900-f71f-11e8-9cdd-1baf42ce3502.png">

And we can de-emphasize it by moving it into the FAQ (See "How do I install...")   

![image](https://user-images.githubusercontent.com/8203939/49405542-bacfe100-f720-11e8-8ecd-5876a3b342a7.png)

After talking to @carljbowman and @cwillisf, seems like this will be a good move because it will discourage folks from accidentally downloading it on an unsupported device/getting an outdated version.

___

Finally we should finalize our copy text soon! And make sure that the tone/point of view feel consistent too. Assuming this will change but just to point out:

(e.g addressing the user)
<img width="294" alt="screen shot 2018-12-03 at 5 27 56 pm" src="https://user-images.githubusercontent.com/8203939/49405621-ef439d00-f720-11e8-8c45-f245afff0802.png">

(versus addressing the Scratch team)
<img width="244" alt="screen shot 2018-12-03 at 5 28 03 pm" src="https://user-images.githubusercontent.com/8203939/49405622-ef439d00-f720-11e8-80d8-8b051552ed80.png">

**Comment by kathymakes** [comment]
I've been working on the app icon as well.... you can check it out in context here:

[**Invision Mockup**](https://invis.io/42PFHBPEHMP)

___
#1 Scratch Cat

![image](https://user-images.githubusercontent.com/8203939/49407549-f66da980-f726-11e8-8072-9af498587ccf.png)

#2 Blocks

![image](https://user-images.githubusercontent.com/8203939/49407561-fff71180-f726-11e8-9b3e-b7c708d341de.png)

**Comment by kathymakes** [comment]
Notes from today's meeting. @picklesrus 

**UX/content changes**

- [ ] Keep “direct download” link in Trouble shooting under separate question (“How do I install if I don’t have access to App Store?” for example)
- [ ] Let’s pay attention to educator feedback and change if needed.
- [ ] Kathy to chat with Champika about content/text changes

**Questions from implementation**

- Arrows on older version download links. Should they flip in RTL?
        - Talk to @chrisgarrity about the special unicode characters for flipping
        - Arrows should be svg (@kathymakes  to provide files)

- Where should the current 2.0 page move to?
        - Move to subdirectory of /download?
        - /download/scratch2
        - Redirect from 1.4 to /download/scratch1.4?

- Where should the direct download links point?
        - Approvals may not come through in time
        - If we don’t have it 1 week before release, then we will just have direct download.
        - Back up plan: Big direct download button, which gets replaced with App Store button
        - Direct download link → S3 bucket that Chris can get links for

- Will step 2 of the install instructions differ for Windows vs MacOS?
        - In case we don't have App Store ready, we should prep for direct download
        - Step 1, direct download
        - Step 2, do the thing you need to do for your OS

**Comment by kathymakes** [comment]
@picklesrus Assets for screenshot images and arrow .svg files below 🙂 

[Downloads Assets.zip](https://github.com/LLK/scratch-www/files/2645767/Downloads.Assets.zip)

**Comment by kathymakes** [comment]
Link to content, work in progress:

https://docs.google.com/document/d/1Z2kflOu_5DzAbCBqg8qx1jCJ9bRKyLNuRtgHfMOPWto/edit

**Comment by towerofnix** [comment]
(Screenshots read "Scratch on Linux is not supported", but I think this should be "Scratch Desktop is not supported on Linux", since of course Scratch 3.0 *can* run inside Firefox/Chromium, and we don't want to give the wrong idea to someone who stumbles upon that page without realizing that Scratch 3.0 also runs online.)

**Comment by thisandagain** [comment]
Good catch @towerofnix. We'll make that change.
