### ISSUE TITLE
/projects should show 404 page (no project id specified)

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2306]
We should decide where `https://scratch.mit.edu/preview` should go. 404 page? New project?

Maybe our regex needs to be revised.

**Comment by kyleplo** [comment]
@chrisgarrity We do have `/projects/editor` and `/projects/`*`user`*`/`*`id`* from the Scratch 1.*x* site

**Comment by Kenny2github** [comment]
@kyleplo no, chris meant like `/projects-anythingelse` (`/preview/editor` would not match the `/preview` pattern either)
