### ISSUE TITLE
preview/0/editor displaying in URL bar ? (Hard to repro)

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2308]
@benjiwheeler writes:

> Logged out of scratch.ly, using the editor view, I somehow got the browser to display preview/0/editor, which is super wrong. But I can’t reproduce. Might be important to reproduce this!

**Comment by BryceLTaylor** [comment]
I can get there by manually typing /projects/0/editor but only if I'm signed out.  If I make changes and then sign in it updates the number in the url, which is correct.  This seems fine to me.
