### ISSUE TITLE
Preview page not loading

### ISSUE THREAD

**Issue by chen-robert** [LLK/scratch-www#2315]
Going to `/preview/${url}` no longer loads properly on the local server.

### Steps to Reproduce

For example, navigating to `localhost:8333/preview/941948` results in a blank screen aside from header and footer. I remember a few weeks ago, it was still loading properly. 

![image](https://user-images.githubusercontent.com/20526314/48523590-e7838d80-e831-11e8-9137-4d39b65cede6.png)

### Operating System and Browser

Windows Hyper-V Ubuntu. 
Google Chrome

**Comment by rschamp** [comment]
@chen-robert The preview is no longer a preview, and is now viewable at `/projects/:id` :)
