### ISSUE TITLE
Long delay before Save begins in project on staging

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2326]
In staging project 1300000328, I saw a super long delay after clicking Save now (or Save as a copy) before save seems to begin.

![slooow2](https://user-images.githubusercontent.com/3431616/48675423-b6070c80-eb26-11e8-8f25-c487fdc291db.gif)

**Comment by Kenny2github** [comment]
'aaaat's lag

**Comment by BryceLTaylor** [comment]
@benjiwheeler I'm unable to reproduce this.  Were you on a particular operating system/browser?
