### ISSUE TITLE
Switch to editor view after user remixes from project page

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2339]
We may want to switch to editor view after user remixes from project page.

This might help encourage making project changes before sharing.

Related to https://github.com/LLK/scratch-www/issues/2328

**Comment by kyleplo** [comment]
I think this is a good idea.

**Comment by thisandagain** [comment]
Yes. We should either automatically switch to the editor or hide the remix button on the community view until this can be resolved. 

/cc @carljbowman @christanbalch

**Comment by benjiwheeler** [comment]
Just want to revisit this since implementing the remix button animation and remixed banner. Do we still want to navigate the user away? If so, at what point of the current sequence of click->animate button->change url and show success banner ?

**Comment by thisandagain** [comment]
Click -> Animate Button -> Change URL -> Switch to Editor

**Comment by kathymakes** [comment]
I like Andrew's suggestion here... I think it's alright to drop the banner for the time being - the encouraging banner seems most important in the new user experience, and there are other ways we can add that in when we think about the broader messaging for new scratchers :)
