### ISSUE TITLE
Update project page metadata with information loaded via the API

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2354]
The Scratch 2 project page has this metadata, which we should think about keeping:
```
<title>{ projectTitle } on Scratch</title>
<meta name="description" content="{ projectTitle } on Scratch by { username }" />
<meta property="og:title" content="Scratch - { projectTitle }"/>
<meta property="og:description" content="{ projectInstructions|truncatewords:50 }" />
```

**Comment by paulkaplan** [comment]
Not going to close this because the new meta tags are in but will not be shown until we use a meta-tagless template, which i think is going to be done in the sentry change @rschamp ?

**Comment by rschamp** [comment]
Correct
