### ISSUE TITLE
Sort out Japanese Hiragana

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#2359]
Scratch 3.0 uses `ja-Hira` for Japanese Hiragana. I noticed that scratchr2_translations (scratchr2 and www), renames `ja-Hira` to `ja-hr`

All of them should be using the standard `ja-Hira` when 3.0 launches.

/cc @thisandagain

**Comment by thisandagain** [comment]
@chrisgarrity That's exciting. :-/ Thanks for catching that!
