### ISSUE TITLE
No scroll bars on add to studio modal if there are many studios

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2360]
On the new project page if there the user has many studios, the list fades out, but there is no scroll bar.  Currently it can only show 20 studios.  

### Steps to Reproduce

Create studios so you have more than 20 of them.
Navigate to a project page
Click add to studio
Note: there are no scroll bars and it only shows 20 studios.  There's no way to access the other studios.

### Operating System and Browser

Mac Chrome

**Comment by paulkaplan** [comment]
Given the people who use studios very well may have lots of studios, this seems like it might be #critical. @thisandagain ?

**Comment by thisandagain** [comment]
@paulkaplan Yup! I talked with @benjiwheeler about this today. We are going to try to prioritize this.
