### ISSUE TITLE
Delete /info/cards page and redirect to /ideas

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#2369]
The http://scratch.mit.edu/info/cards page is going to be out of date at Scratch 3.0 launch. Rather than update it, @chrisgarrity and I recommend:
 1) deleting it, and 
2) redirecting anything pointing to this page to scratch.mit.edu/ideas

**Comment by Kenny2github** [comment]
Does this issue want help?

**Comment by thisandagain** [comment]
@kenny2github A PR would be most welcome! Also assigning @chrisgarrity for follow-up as there is some time sensitivity (needs to be merged by the end of December).
