### ISSUE TITLE
need /embed view that can be used to embed projects in an iframe

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2388]
Many 2.0 projects are shared in iframes currently, all around the web in play-only mode.

We should make an endpoint that provides such a view.

Features:
* it should be as small and cacheable as possible
* redirects the current embed URL: `/projects/embed/:id`
* handles the URL `/projects/:id/embed`
* will use the 'greenflag overlay' getting implemented for project page
* Logo on the bottom, not too prominent, watermarked styling, links back to the splash page.
* remove or disable the fullscreen button
* green flag/stop buttons position should match gui

#### Enhancements that are not being considered for the initial version
* should the title be present?
* should there be a watermark/overlay that communicates something about what Scratch is?
* should the user's name and avatar be present?
* should there be some link back to the project's Scratch page?

**Comment by DeleteThisAcount** [comment]
hmm also wanted to say that people often to steal games from scratch and embed on their own website

example: look up "paper minecraft flash game" on google. scratch has little to none watermarking on their embed and unless the creator credits themselves in the project, there in to credit to the creator

**Comment by kathymakes** [comment]
> hmm also wanted to say that people often to steal games from scratch and embed on their own website
> 
> example: look up "paper minecraft flash game" on google. scratch has little to none watermarking on their embed and unless the creator credits themselves in the project, there in to credit to the creator

@DeleteThisAcount Thanks for bringing that up. Yeah we were talking about how it's important to ensure authors/creators are well-represented. Unfortunately we can't consider this in full until we launch 3.0. Thanks for your thoughts & the example!
