### ISSUE TITLE
Scratch News Text issue

### ISSUE THREAD

**Issue by hlcolani** [LLK/scratch-www#239]
For some reason, when I use Chrome, the text in the Scratch News section of the homepage doesn't fit in the Box? I only see that in Chrome, so it might just be on my computer
![screen shot 2015-11-13 at 4 42 36 pm](https://cloud.githubusercontent.com/assets/14829217/11158335/91d99554-8a25-11e5-8bb9-43100c465768.png)

**Comment by TheGrits** [comment]
I do not have the bug. My browser / operating system: ChromeOS 7647.73.0, Chrome 48.0.2564.92, Flash 20.0 (release 0)

**Comment by liam4** [comment]
It appears as it should for me. I'm on Mac OS X 10.10.3, Chrome 50.0.2639.0.

**Comment by mewtaylor** [comment]
I am also not able to repro this anymore – it looks like it got fixed somewhere along the way but not closed. Thanks for investigating @liam4.

Closing this as fixed – we can reopen if it comes up again later.
