### ISSUE TITLE
Confirm that history management is adding/replacing appropriately

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2391]
new project - add URL with id to history (or replace?)
remix - add URL with new id to history
save copy - add URL with new id to history
load project - add URL to history (what id??)

(In the future, we may want to consider adding a higher-order component to either www or gui.)

We already know that users could have unexpected behavior when hitting the back button.

I don't understand enough about how various browsers track history to know what potential impact our history management has, what it means that we're not providing "real" back button functionality, and what the impact might be if we've made errors in the (already incomplete) way we approach things currently.

This issue, as written above, is just to confirm that we're at least doing our incomplete approach the way we intend. It might prevent unforeseen problems. The confirming itself would mean a moderate amount of checking current behavior and seeing if it makes sense -- say, an hour or so.

Adding a new higher-order component could help centralize these manipulations, but it would probably make sense not to do such a refactor until we are significantly improving our overall approach to history management -- say, by triggering page reloads if you go back or forward in history.

**Comment by thisandagain** [comment]
@benjiwheeler Can you please provide more context here? Is this a QA issue that you'd like to have @BryceLTaylor review?

**Comment by benjiwheeler** [comment]
Added more notes to description above.

I don't really understand what the user experience should be, in this current state where we know it doesn't work but just don't want it to not work *tooo* badly :) . So I'm not sure what I'd ask @BryceLTaylor to test. It's a difficult issue to take specific action on.

**Comment by thisandagain** [comment]
> Adding a new higher-order component could help centralize these manipulations, but it would probably make sense not to do such a refactor until we are significantly improving our overall approach to history management -- say, by triggering page reloads if you go back or forward in history.

Agreed! @BryceLTaylor do you mind working together with @benjiwheeler to audit the current behavior?

**Comment by benjiwheeler** [comment]
Looked into this. Seems to me the code is correctly implementing at least our "incomplete" current approach, because all creations of a new project go through the same www code that pushes history state.

I edited this issue: https://github.com/LLK/scratch-www/issues/2337 so we're tracking the question of whether or not we should reload.
