### ISSUE TITLE
Project page of a remixed remix has misaligned info

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2458]
If you remix a project that is already a remix, the project page for your new project will appear with the info boxes and their text misaligned.

### Steps to Reproduce

Remix a project with one user
Sign out
Sign in with another user
Navigate to the remixed project page
Remix it
Look at the project page for your new project
Note: The Instructions and Notes and Credits appear strangely positioned

<img width="850" alt="screen shot 2018-12-12 at 3 33 46 pm" src="https://user-images.githubusercontent.com/1088291/49897147-55b47380-fe23-11e8-89e5-5ac5baf91535.png">

### Operating System and Browser

Mac Chrome

**Comment by thisandagain** [comment]
@benjiwheeler Here is a critical item that I hope is a quick fix.

/cc @paulkaplan

**Comment by benjiwheeler** [comment]
One more example:

![image](https://user-images.githubusercontent.com/3431616/49911671-46e6b480-fe55-11e8-9cb7-ea9e68d8481d.png)

E.g., http://localhost:8333/projects/2000000409/

#2132 was related, FYI
