### ISSUE TITLE
Converting other scratchr2 pages to scratch-www screenshots

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-www#2481]
Hi! I wanted to share with you these screenshots I took of possible scratch-www versions of scratchr2 pages:

Discuss Home:
![discuss](https://user-images.githubusercontent.com/31634240/49968508-02f6bc80-fef4-11e8-80ca-82abc9c1dfa7.PNG)

Discuss Topic:
![discuss-topic](https://user-images.githubusercontent.com/31634240/49968510-02f6bc80-fef4-11e8-8ece-420d3117b954.PNG)

My Stuff Page:
![mystuff](https://user-images.githubusercontent.com/31634240/49968511-02f6bc80-fef4-11e8-9b08-b7f72fee3868.PNG)

Profile Page:
![profile](https://user-images.githubusercontent.com/31634240/49968512-038f5300-fef4-11e8-8f18-0db4e8f4beaa.PNG)

Studio Page:
![studio](https://user-images.githubusercontent.com/31634240/49968513-038f5300-fef4-11e8-9e87-3bfccdcb6499.PNG)

### Steps to Reproduce

N/A
### Operating System and Browser

Windows 10 Chrome 70

**Comment by apple502j** [comment]
Discussion forum seems impossible - They use DjangoBB (a Python program) for the forums.
Others - looks nice.

**Comment by towerofnix** [comment]
@thisandagain Did you accidentally close this? (Considering you mentioned carl and kathy but then immediately closed it!)

**Comment by thisandagain** [comment]
@towerofnix I closed it as we have a separate project tracking system for revising the design of each of these pages. I mentioned Carl and Kathy as I want to make sure we include these mockups as we are considering our redesigns.

**Comment by kyleplo** [comment]
@apple502j They could switch to a different forum system, like they did between 1.4 and 2.0

Also, I just found this: https://github.com/shoumma/ReForum
