### ISSUE TITLE
A remixed project without changes has the wrong thumbnail

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2484]
If you remix a project and then immediately, without making changes, leave the page, the project will have just the cat on a white background for the thumbnail.

### Steps to Reproduce

Sign in
Navigate to a project you don't own
See inside
Click "Remix" at the top of the page
Note: the project gets a new number and the title says "remix" in it
Click the "my stuff" folder icon in the top bar
Note: on the my stuff page the thumbnail for the project is just the cat on a white backdrop.
If you ever save the project it gets the correct thumbnail.

### Operating System and Browser

Mac Chrome

**Comment by benjiwheeler** [comment]
@thisandagain can you help me understand why this issue is critical?

**Comment by thisandagain** [comment]
@benjiwheeler As we've seen in the past when thumbnails are not properly working in the "My Stuff" page, users can become highly disturbed and worry that their work did not properly save which results in a flood of bug reports and help desk tickets.

**Comment by benjiwheeler** [comment]
Confirmed that this is now working in scratch.ly
