### ISSUE TITLE
/tips to /ideas redirect is not working on staging

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-www#2485]
When i hit /tips on staging, I get a 301 redirect response but it doesn't provide a location and so I just see a blank page. This is pretty confusing, given the code looks right https://github.com/LLK/scratch-www/blob/develop/src/routes.json#L393-L396

/cc @chrisgarrity @ericrosenbaum @rschamp

**Comment by rschamp** [comment]
This was due to the rewrite for the old tips view sticking around. We don't have anything that knows how to remove outdated views.  I fixed it manually.
