### ISSUE TITLE
Concerns about aggregating loves/favorites on the project page

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2496]
@thisandagain writes:
We decided to only show 100+ on views, but I’m worried that aggregating the loves and favorites into “human” readable strings (e.g. 1K) may cause some serious issues with the community at launch.
![image11](https://user-images.githubusercontent.com/1088291/50097841-bc9da800-01e8-11e9-9d67-cd943933e4d3.png)

**Comment by paulkaplan** [comment]
We decided to remove the approximation in  love/favorite numbering
