### ISSUE TITLE
Get rid of use of FormattedHTMLMessage in FAQ page

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-www#2521]
The FAQ page (info/faq) makes relatively heavy use of FormattedHtmlMessage.  We should make it use FormattedMessage instead.

**Comment by Kenny2github** [comment]
help wanted or no?

**Comment by picklesrus** [comment]
@Kenny2github: Sure!

**Comment by MasterOfTheTiger** [comment]
May I do this? Or is someone else already doing it?

**Comment by Kenny2github** [comment]
I'm on it.
