### ISSUE TITLE
Autoplay masthead Scratch video?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2529]
Follow-on to https://github.com/LLK/scratch-www/pull/2526, which introduced the "Create stories..." masthead to be activated post-launch (around Jan 18 2019)

Currently, the "Create stories" masthead will require two clicks to play the video:

Starting view:

![image](https://user-images.githubusercontent.com/3431616/50298029-2f5a8d80-044c-11e9-99b6-6cf827963b68.png)

After one click:

![image](https://user-images.githubusercontent.com/3431616/50298039-35506e80-044c-11e9-80d6-223ab9b5340f.png)

After two clicks:

![image](https://user-images.githubusercontent.com/3431616/50298057-3ed9d680-044c-11e9-9532-9a64528eebcd.png)

Should we set the video to autoplay? 

From quick look at Wistia docs, autoplay seems to be a setting that is attached to the file on Wistia's end, not an embed option. (Not sure about this, just from a quick glance.)

So we might need to decide that this video should autoplay *everywhere*, or *nowhere*.

**Comment by thisandagain** [comment]
That would cost *a lot* of money and may incur bandwidth utilization for the user that they do not want.
