### ISSUE TITLE
Storage's handling of broken assets still makes project crash

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2534]
Storage was recently changed to make a broken asset (like an invalidly formatted svg) be gracefully replaced with a static question mark image, so the project will recover and be saveable and loadable.

But it appears this is not working.

### Steps to Reproduce

1. Download [broken.sb3](https://drive.google.com/open?id=1Jiensy23u98RoWnzcUJL_TnSIahp-t3R) (or use the .zip below, and change extension to .sb3)
[broken.zip](https://github.com/LLK/scratch-www/files/2700615/broken.zip)

2. log into staging site

3. go to editor

4. upload broken.sb3 file

5. let it save

6. reload the page

7. BSOD crash!!!!!

...Furthermore, you'll also get a crash if you do steps 1-5 above, and then do:

6. download the file (let's call it "resaved.sb3")

7. create a new project

8. upload the file "resaved.sb3" again

9. let it save

10. reload 

11. BSOD crash!!!!!!!

### Operating System and Browser

Observed on Mac Mojave with current Chrome, and Windows Chrome

**Comment by thisandagain** [comment]
@kchadha This isn't a launch blocker, but if you could take a look at this tomorrow morning it would be helpful. I'm curious if you would consider this a blocker.

/cc @fsih
