### ISSUE TITLE
Project reports do not include the thumbnail

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-www#2550]
The code handling project reports always creates a blank white thumbnail (source: https://github.com/LLK/scratch-www/blob/develop/src/redux/preview.js#L855-L858)

Warning: this might be a bit complex to implement since the GUI is the one who is in control of the the thumbnail stuff. I also do not fully understand when project reports include thumbnails and when they do not.

**Comment by paulkaplan** [comment]
@rschamp from looking at the default thumbnail data we include in the `reportProject` reducer action [src](https://github.com/LLK/scratch-www/blob/develop/src/redux/preview.js#L964-L967) it seems like maybe the problem is that we are including the `data:image` prefix in the POST instead of just the b64 encoded image. That is, we might be able to fix just by stripping `data:image/png;base64,` from the thumbnail we get back from the GUI.

**Comment by thisandagain** [comment]
Resolved in #3211

**Comment by paulkaplan** [comment]
For future generations, this bug was the focus of **The Bug Report Episode 2: Thumbnail Holy Grail**
