### ISSUE TITLE
Not enough font choices in add to studio

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-www#2566]
![image](https://user-images.githubusercontent.com/31634240/50612873-a4e14780-0ea9-11e9-8e9b-471d97c2bfc2.png)

### Steps to Reproduce

Open the add to studio modal in a browser that doesn't support Helvetica Neue 

### Operating System and Browser

Windows Chrome

**Comment by IamTregsthedev** [comment]
I can help. Where is the FIle loacted, and what do i add?

**Comment by kyleplo** [comment]
@IamTregsthedev I already submitted a PR, sorry. The file is in src/components/modal/add-to-studio/modal.scss

**Comment by IamTregsthedev** [comment]
Oh ok

**Comment by benjiwheeler** [comment]
@IamTregsthedev Thanks for your willingness to help! Please feel free to chime in on other issues too, we'd love your help! https://github.com/LLK/scratch-www/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
