### ISSUE TITLE
Remixes section of the project page should have a "see all" link

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2584]
On the project page at the top of the remixes section there should be a "see all" link to to the /remixes view.

**Comment by thisandagain** [comment]
@carljbowman If I remember correctly we already had a design for this. Can you confirm?

**Comment by carljbowman** [comment]
Our original sketch was similar to what @benjiwheeler implemented. Just the "See All" text is a bit smaller at 12px, to help mitigate wrapping with longer languages.

![see all](https://user-images.githubusercontent.com/3409578/50692453-eb49ba00-1001-11e9-911f-c4168904b6f9.png)

**Comment by benjiwheeler** [comment]
Resolved by https://github.com/LLK/scratch-www/pull/2596
