### ISSUE TITLE
Extension starter projects should be in a different account

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-www#2585]
We should consider which account the starter projects for extensions should live in. Currently there are 3 starter projects for each of the three hardware extensions, and those 9 projects are in an account called [ericr-sampleprojects](https://scratch.mit.edu/users/ericr-sampleprojects/). 

We should either rename this account or move the projects into a different account.

**Comment by kosiecki17** [comment]
Would it be appropriate to move these to the LearningResources account?

**Comment by DeleteThisAcount** [comment]
remember that people have already bookmarked the links. so if you unshared them, they would break a few links.

renaming the account seems to be the best solution
