### ISSUE TITLE
Long strings in instructions or notes & credits don't wrap

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2586]
Long strings in instructions or notes & credits don't wrap; they push past page boundaries.

Example: https://scratch.mit.edu/projects/268361524/

![image](https://user-images.githubusercontent.com/3431616/50658217-a3c22000-0f66-11e9-8ed5-9141565feb31.png)

### Operating System and Browser

Mac Mojave 10.14.2, current Chrome

**Comment by towerofnix** [comment]
NUMNUMNUMNUMNUMNUMNUMNUMNUMNUMNUMNUMNUMNUMNUMNUMNUM!!!!!

!["i stole the rainbows!!!!"'s description, which is numnumnum.. over and over again: https://scratch.mit.edu/projects/61400486/](https://user-images.githubusercontent.com/9948030/52380129-f9e12200-2a42-11e9-9cf2-9b79aa199c82.png)

**Comment by benjiwheeler** [comment]
This popped up again on this project: https://scratch.mit.edu/projects/331977179/

![image](https://user-images.githubusercontent.com/3431616/66776969-b1adb580-ee95-11e9-9d31-b23073a6c400.png)

I did some quick playing around with the CSS, but couldn't get it to behave. Yet everything is fine when the window width is narrow, which makes the element scroll. Seems like this should be solvable. One of the core problems is that there is only supposed to be a fixed width for the element when the screen is either narrow, or full width ("desktop") -- in intermediate sizes, it is supposed to resize itself to fit 100% available width (or rather, a calculated width starting with 100%), which causes this overflow to occur.

overflow-wrap: break-word did not seem to do anything.

**Comment by benjiwheeler** [comment]
Fixed by #2518; also see related #4149
