### ISSUE TITLE
Account Nav should go above monitors in the editor

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2587]
If you have a monitor in the upper right side of your project in the editor and you open the account nav it will go behind the monitors.

It shouldn't.

### Steps to Reproduce

Open the editor
Scroll down to variables in the category menu
Check the box next to "My Variable"
Drag the monitor to the upper right side of the stage
Click on your username
Note: the menu that appears goes behind the monitor

### Operating System and Browser

Mac Chrome

**Comment by jfo8000** [comment]
FYI when I changed the z-index in the inspector it resolved this problem.  Looks to be a simple case of switching 41 to 999? 
```
.menu-bar_menu-bar-menu_239MD {
    margin-top: 3rem;
    z-index: 999; /* <---- used to say 41 */
}
```

**Comment by DeleteThisAcount** [comment]
where would this code be?

**Comment by jfo8000** [comment]
Not entirely sure, I only chrome debugged the live site...  this style looks to be processed and stuffed into a style tag by some build process.

**Comment by benjiwheeler** [comment]
@jfo8000 and @DeleteThisAcount, there's a pull request that partially resolves this, but it's not finished. Please read the comments there. You are welcome to take a look and submit a fix!
