### ISSUE TITLE
Add Sound section to credits page

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-www#2589]
We need to add a section to the credits page for the creators of sounds and music that we use in the sound library. Some of the sounds have creative commons licenses which require attribution.

Here's the text (to be inserted following the "illustrations" section):

---

### Sounds

The Scratch sound library uses free sound resources from Adobe.com, Archive.org, FreeMusicArchive.org, FreeSound.org, and Incompetech.com.

Thanks to Nina Paley from Archive.org; Kellee Maize, Peter Rudenko, and Chris Zabriskie from FreeMusicArchive.org; and Kevin MacLeod from Incompetech.com. Thanks to the following freesound.org artists: acclivity, belloisec, Benboncan, Calcuttan, coby12388, copyc4t, cs272, Flick3r, FreqMan, gelo_papas, han1, InspectorJ, jiserte, junggle, juskiddink, klankbeeld, LittleRobotSoundFactory, LloydEvans09, lonemonk, rhodesmas, sandyrb, themfish, tyops.

**Comment by thisandagain** [comment]
@ericrosenbaum I made some minor adjustments to the text, but this looks good.

**Comment by apple502j** [comment]
According to CC BY, these are required: 
- author name 🆗 
- copyright notice 🆖 
- notice to CC license 🤔 (FAQ page will do?)
- link 🆖
