### ISSUE TITLE
Comments section appears on unshared projects

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-www#2590]
You can comment on your own unshared projects.

### Steps to Reproduce

Look at an unshared project page.

### Operating System and Browser

Windows Chrome

**Comment by benjiwheeler** [comment]
Partially addressed by https://github.com/LLK/scratch-www/pull/2612 , but needs to be disallowed on backend too

**Comment by benjiwheeler** [comment]
Resolved by https://github.com/LLK/scratch-www/pull/2612 and https://github.com/LLK/scratch-api/pull/703
