### ISSUE TITLE
404 for projects doesn't have title

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#2607]
404 page has no title. It should have a title.

### Steps to Reproduce
Go to a project page like https://scratch.mit.edu/projects/1000000000000000000

### Operating System and Browser
any

**Comment by IamTregsthedev** [comment]
I'll Kindly can Take this, if not a Scratch team or someone else wants too. 👍

**Comment by apple502j** [comment]
I'm also on this 😛 
Now lint passed, just I need to check if it really works

**Comment by IamTregsthedev** [comment]
WHYYYYY @apple502j  AGAIN!

**Comment by IamTregsthedev** [comment]
> WHYYYYY @apple502j AGAIN!

I was going to take this but okay i guess. :( 👍
