### ISSUE TITLE
Loves and favorites are not creating notifications

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2614]
Loving and favoriting projects should create notifications that can be viewed on the user profile pages and in messages.

But they're not, because currently only scratchr2 creates them; api's POST and DELETE endpoints for loves and favorites don't create them yet.

We should have the project page hit different API endpoints, to proxy these requests to scratchr2 until we can update API.

**Comment by apple502j** [comment]
Why is this PR still open?

**Comment by benjiwheeler** [comment]
Thanks for noticing, @apple502j! I'll close it now.

Resolved by #2615, #2616, and API's #694 & #695.
