### ISSUE TITLE
Navigation Bar:  Cannot GET /accounts/standalone-registration/

### ISSUE THREAD

**Issue by XueYuSky** [LLK/scratch-www#2619]
I git clone the repo: scratch-www using:
git clone https://github.com/LLK/scratch-www.git
then run: 
npm install
make translations
npm start
after that: I open chorm and type in the url: localhost:8333
I got this: 
![1](https://user-images.githubusercontent.com/13450817/50810655-adbc9800-1345-11e9-85f5-e1270134c5a5.PNG)
![2](https://user-images.githubusercontent.com/13450817/50810659-b3b27900-1345-11e9-8188-2176ce007e4b.PNG)
![3](https://user-images.githubusercontent.com/13450817/50810662-b7de9680-1345-11e9-863a-e2ba3e4cc41e.PNG)

### Steps to Reproduce
git clone https://github.com/LLK/scratch-www.git
then run: 
 npm install
make translations
npm start
open chorme and type in the url: localhost:8333

Please Signin Scratch,and you 'll get my problem.

### Operating System and Browser

Win10 And Chorme 71.0.3578.98

**Comment by towerofnix** [comment]
The reason there is this error is because the page https://scratch.mit.edu/accounts/standalone-registration/ is not migrated to the modern scratch-www repository - it is still part of the closed-source scratchr2 repository. When scratch-www is deployed to https://scratch.mit.edu, it expects scratchr2 to also be running (so that that page shows up), and when running locally, it just fails to load the page. (As such, you cannot register or sign into Scratch while running scratch-www locally.)

**Comment by joker314** [comment]
Try setting the FALLBACK environment variable. This will send all the scratchr2 pages to the actual live website. Careful, though, if you log in you will be performing live actions on the site when you e.g. comment on projects.

```
FALLBACK="https://scratch.mit.edu" npm start
```

**Comment by XueYuSky** [comment]
> Try setting the FALLBACK environment variable. This will send all the scratchr2 pages to the actual live website. Careful, though, if you log in you will be performing live actions on the site when you e.g. comment on projects.
> 
> ```
> FALLBACK="https://scratch.mit.edu" npm start
> ```

Thanks for your help. It works and the that page shows up. But I use my account to login, it appears nothing happended. I can't login the web.

**Comment by joker314** [comment]
Ah yep! Take a look at the README.md file, it has a section on FALLBACK. It reads that the issue of logging in might be something that's being fixed, but also there are some security concerns.

**Comment by XueYuSky** [comment]
> Ah yep! Take a look at the README.md file, it has a section on FALLBACK. It reads that the issue of logging in might be something that's being fixed, but also there are some security concerns.

Which README.md should I take a look at ？ The one in scratch-www or scratch-gui ?
