### ISSUE TITLE
ERROR in ./~/_@sentry_core@4.4.2@@sentry/core/dist/integrations/extraerrordata.js

### ISSUE THREAD

**Issue by liuyunzidian** [LLK/scratch-www#2623]
when I run "npm start"
there is an ERROR:
ERROR in ./~/_@sentry_core@4.4.2@@sentry/core/dist/integrations/extraerrordata.js
Module not found: Error: Can't resolve '../../../utils/logger' in '/home/scratch-data/scratch-www/node_modules/_@sentry_core@4.4.2@@sentry/core/dist/integrations'
 @ ./~/_@sentry_core@4.4.2@@sentry/core/dist/integrations/extraerrordata.js 6:15-47
 @ ./~/_@sentry_core@4.4.2@@sentry/core/dist/integrations/index.js
 @ ./~/_@sentry_core@4.4.2@@sentry/core/dist/index.js
 @ ./~/_@sentry_browser@4.4.2@@sentry/browser/dist/index.js
 @ ./src/views/preview/project-view.jsx
 @ ./src/views/preview/preview.jsx

when I open in broswer there is empty,and in console :
extraerrordata.js:6 Uncaught Error: Cannot find module "../../../utils/logger"
    at webpackMissingModule (extraerrordata.js:6)
    at eval (extraerrordata.js:6)
    at Object.75 (splash.bundle.js:1147)
    at __webpack_require__ (common.bundle.js:55)
    at eval (index.js:11)
    at Object.78 (splash.bundle.js:1171)
    at __webpack_require__ (common.bundle.js:55)
    at eval (index.js:32)
    at Object.72 (splash.bundle.js:1075)
    at __webpack_require__ (common.bundle.js:55)

where is the problem? How to solve this?

**Comment by thisandagain** [comment]
What version of Node and NPM are you running? What operating system are you using?

**Comment by liuyunzidian** [comment]
@thisandagain My Node is v6.11.3, NPM is 3.10.10, OS is Ubuntu 14.04.5.

**Comment by liuyunzidian** [comment]
After I use npm(I'm used cnpm) this is ok.
