### ISSUE TITLE
Add Community Moderator link to jobs page

### ISSUE THREAD

**Issue by dietbacon** [LLK/scratch-www#2625]
Please add https://scratch.mit.edu/jobs/moderator back to the main jobs page at https://scratch.mit.edu/jobs with the Community Moderator position listed as 'Remote' as we're ready to bring on new moderators again.

**Comment by IamTregsthedev** [comment]
I'll Take this! Where is the file?

**Comment by apple502j** [comment]
@IamTregsthedev https://github.com/LLK/scratch-www/blob/develop/src/views/jobs/jobs.jsx

**Comment by IamTregsthedev** [comment]
Where is the file? What do i add?
