### ISSUE TITLE
Project title shows up after project has loaded

### ISSUE THREAD

**Issue by BonfireScratch** [LLK/scratch-www#2626]
Project title shows up after project has loaded

### Steps to Reproduce

1) Go to any scratch project
2) Watch the title of the tab change after project has loaded

### Operating System and Browser

_Windows 7 Chrome 71.0.3578.98 (32-bit)_

**Comment by BonfireScratch** [comment]
I thought that project title was being set by the Scratch API

**Comment by thisandagain** [comment]
This is by design as the new project page is not rendered server-side, but rather manipulated by the client at runtime.
