### ISSUE TITLE
remixing from project page (before project has finished loading) seems to result in broken state

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2628]
hitting remix on project page before project has finished loading appears to be remixing forever. Some reports that it results in a seemingly broken state

The cause may relate to logic in the project state machine in gui, which only allows you to initiate a remix when the project is already loaded; we may need to revert https://github.com/LLK/scratch-www/pull/2515 , which preempively puts the button into a "remixing" state when it's not ready.

Or, it may relate to https://github.com/LLK/scratch-www/issues/2629, which suggests that the remixing state is being entered when the project is not remixable, or that remixing is failing in a way we're not catching.

**Comment by thisandagain** [comment]
From discussion the suggestion here is to simply disable the remix button until the project has completed loading.
