### ISSUE TITLE
no banner appears warning that project can't be shared until email is confirmed

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2633]
to repro:

1. be a new scratcher
2. create a project
3. go to project page
4. you should see banner warning that it’s not shared, and to confirm email. BUT you don't.

**Comment by paulkaplan** [comment]
So this has been open for quite a while, but @carljbowman recently added a lot of context around this issue so i'm going to close this in favor of that one https://github.com/LLK/scratch-www/issues/3669
