### ISSUE TITLE
Can't click links of highlighted comment

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#2647]
When a comment is highlighted, I can't click the username or avatar links to view the profile of the commenter; my mouse doesn't even turn into the pointer cursor when I hover over them. When a comment *isn't* highlighted, though, I can click those links. I know the `<a>` elements are at least properly present, because I can use keyboard navigation (tab/shift+tab) to focus and activate them - I just can't use my mouse to do so.

I can also select the text in the comment; it's just the links that I can't use.

### Steps to Reproduce

Open a page with a highlighted comment: https://scratch.mit.edu/projects/276932192/#comments-105962617 Then try to click the profile picture or username.

Then open the page without highlighting the comment: https://scratch.mit.edu/projects/276932192/

### Operating System and Browser

I'm on Linux (Debian). I can repro this on both Firefox and Chromium.

**Comment by locness3** [comment]
`z-index: 1`to avatar and author link could fix this. @towerofnix @thisandagain

**Comment by JoelGritter** [comment]
Issue appears to be resolved, tested on Chrome/Safari/Firefox on MacOS.

**Comment by mxmou** [comment]
This was fixed by #3232.
