### ISSUE TITLE
After posting a max length comment, character count remains red

### ISSUE THREAD

**Issue by KennethSweezy** [LLK/scratch-www#2652]
When posting a max length comment (500 Characters), after posting, the character count remains red, creating things like [this](https://ibb.co/jfTpyTj). I have seen several other issues relating to this, namely #1813 and #1527 however this led to an unknown repository.

### Steps to Reproduce
1. Fill the max character limit of a comment
2. Then post the comment
3. Notice that the character count is still red

### Operating System and Browser
Mozilla/5.0 (X11; CrOS aarch64 11021.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.76 Safari/537.36

**Comment by joker314** [comment]
Hi, those repositories are private, you're right. Even though they can't be publicly viewed, those repositories still exist and are still traking the issue for internal Scratch Team members

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratchr2/issues/4990

**Comment by KennethSweezy** [comment]
Thanks for the explanation!
