### ISSUE TITLE
Little Bluebridge Foundation links to the page itself on Credit Page

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#2681]
On https://scratch.mit.edu/credits 's Sponsor column, LBF links to the page itself.

### Steps to Reproduce
1. Go to Credits
2. Click LBF on Sponsor

### Operating System and Browser
Windows 10/Firefox 64

tips:https://github.com/LLK/scratch-www/blob/develop/src/views/credits/credits.jsx#L65 should be fixed so that a tag won't be added without URL

**Comment by thisandagain** [comment]
Great catch!

**Comment by kathymakes** [comment]
@thisandagain I'm not sure where this might link, I don't believe that LBF has its own website. We could ask Tony Zhang's group and in the meantime leave it as an unlinked image.

**Comment by thisandagain** [comment]
Yup! No website for this one. I think I'd prefer that we simply remove the link (e.g. `<a href>`) from the image.

**Comment by jakel181** [comment]
I don't see a website for "Little Bluebridge Foundation" at all nor does a google search or with a company database. (www.crunchbase.com).  http://www.bluebridge.foundation/ shows no affiliation with "Little Bluebridge Foundation" and a whois lookup https://whois.icann.org/en/lookup?name=www.bluebridge.foundation shows the domain is owned by Booster Enterprises and registered by godaddy. A company search of that leads me to https://boosterthon.com/ and a whois of that shows a full whois guard, though it is registered to Amazon Registrar, Inc. (AWS). Both websites relate to getting money via grants or fundraisers, though neither of them mention "Little Bluebridge Foundation". All of this leads me to believe that "Little Bluebridge Foundation" is actually a typo and should actually be "Blue Bridge Foundation".

**Comment by thisandagain** [comment]
@jakel181 No. The foundation is called "Little Bluebridge Foundation" and is run by an anonymous donor. Please do not change the name.

**Comment by jakel181** [comment]
Ok 👌 :)
