### ISSUE TITLE
FAQ refers to a section which does not exist

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#2708]
```
Does Scratch 3.0 remove any coding blocks from earlier versions of Scratch?
    No coding blocks have been removed in Scratch 3.0, but some have changed a bit and others have moved into "Extensions" (as described below, under "Where did the Pen blocks go?..").
```
But `Where did the Pen blocks go?` does not exist.
### Steps to Reproduce
See FAQ

### Operating System and Browser
any

**Comment by thisandagain** [comment]
Marking this as "help wanted". Desired fix is to simply change this line to read:
`No coding blocks have been removed in Scratch 3.0, but some have changed a bit and others have moved into "Extensions".`
