### ISSUE TITLE
Firefox project page to full screen does not go to full screen at first

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#2721]
When going to full screen in 64.0.2 (64-bit) Firefox macOS, the first overly is on the whole project page, without showing the real full screen of the project. See attached GIF:

![jan-28-2019 09-24-53](https://user-images.githubusercontent.com/192393/51842991-1d3bfc80-22e0-11e9-8b25-495c7910ba39.gif)

After clicking the green flag, the stage takes over the full screen.

### Steps to Reproduce

Load project into Firefox, click fullscreen, see that it's a full screen version of the project page and not the stage.

### Operating System and Browser

macOS 10.13, Firefox 64.0.2 (64-bit)

**Comment by apple502j** [comment]
repro: Windows 7 Firefox 65

**Comment by adroitwhiz** [comment]
Fixed by https://github.com/LLK/scratch-render/pull/588 --can someone with write access to this repo close this? @fsih

**Comment by BryceLTaylor** [comment]
fixed
