### ISSUE TITLE
Replace scratchblocks with s3blocks

### ISSUE THREAD

**Issue by NitroCipher** [LLK/scratch-www#2726]
By only replacing one file, you guys can start using the Scratch 3.0 style blocks for the forums. 

If you want everything to run smoothly and be updated as soon as i push an update, you can repoint [this file from you CDN](https://cdn.scratch.mit.edu/scratchr2/static/__238e692fba4864e9ff337c17d8a4033d__//djangobb_forum/scratchblocks/scratchblocks.js) to [my bundle off of github](https://s3blocks.github.io/js/bundle.js)

the only issue is that the top of hat blocks are slightly clipped (when at the top of the blockscript, not any other time), but that doesn't affect anything much, and i will fix that asap

**Comment by NitroCipher** [comment]
![screenshot 2019-01-29 at 09 29 15](https://user-images.githubusercontent.com/11393734/51919197-89823300-23a8-11e9-9f75-16ffe996423e.png)

I used [resource override](https://chrome.google.com/webstore/detail/resource-override/pkoacgokdfckfpndoffpifphamojphii) to locally replace the bundled js file to show that it works on [the forums.](https://scratch.mit.edu/discuss/topic/273387/?page=18)

**Comment by Kenny2github** [comment]
I hate to break it to you, but you have a competitor: https://scratchblocks.github.io/#?style=scratch3&script=when%20gf%20clicked

**Comment by NitroCipher** [comment]
@Kenny2github I'm well aware of tvjr's update. Though with all the changes made to the structure of scratchblocks, it isn't quite as simple to switch to. This would work as a quick fix until the ST is ready to do more reworking

**Comment by apple502j** [comment]
Forums are not handled here.

**Comment by NitroCipher** [comment]
I just kicked out the last couple of bugs today, so everything is perfect for release

**Comment by NitroCipher** [comment]
Hats are fixed, and extension blocks have icons

![image](https://user-images.githubusercontent.com/11393734/52103561-e568d980-25ab-11e9-9dec-70bf5bf8149d.png)

**Comment by NitroCipher** [comment]
@towerofnix Normally yes, but looking at the bbcode, the user used overrides to change the shape of a reporter to a hat, and changed the category ```(when gf clicked ::hat events)```, rather than using brackets ```{when gf clicked}```

**Comment by thisandagain** [comment]
Moved to LLK/scratchr2#5274

**Comment by benjiwheeler** [comment]
@NitroCipher FYI, I tested this and it looks good. Ideally, you could submit pull requests to scratchblocks and stay having a single codebase.

**Comment by NitroCipher** [comment]
@benjiwheeler s3blocks was being written originally in to be merged back into scratchblocks, but I got distracted from working on it due to school work for an extended period of time. Tjvr began refactoring scratchblocks in my absence, and it now the structures barely resemble each other. Both s3blocks and scratchblocks have their advantages; Scratchblocks now has support for both 2.0 and 3.0 styles, but has syntax errors and is not directly compatible the scratch forums, so it will need to be resolved prior to release. s3blocks uses the exact same syntax as the original scratchblocks, and would be as simple as replacing a single file, and could be released today, with no extra work needed.

**Comment by NitroCipher** [comment]
@benjiwheeler [Any new info?](https://scratch.mit.edu/users/thisandagain/#comments-53943332)

**Comment by benjiwheeler** [comment]
Thanks for the background info, @NitroCipher. 

If @tvjr's version is not ready to go, I'll use yours.

**Comment by NitroCipher** [comment]
Alright, best of luck! [bundle here](https://s3blocks.github.io/js/bundle.js)

**Comment by benjiwheeler** [comment]
@NitroCipher, do I need to include your whole sourceMappingURL?

**Comment by NitroCipher** [comment]
I would assume so.

**Comment by towerofnix** [comment]
@NitroCipher Isn't the source mapping only used for representing the code?

Since it looks like you're already using webpack or some similar tool, you should consider making a "production" bundle which has source maps disabled and uses an uglifying/minifying tool to decrease the file weight of forum pages.

**Comment by NitroCipher** [comment]
@towerofnix Whooops, i've always used the autogenerated bundle :P 

@benjiwheeler Well anyways, here is the smaller build file https://s3blocks.github.io/js/s3blocks.min.js

**Comment by NitroCipher** [comment]
@benjiwheeler What's happening?

**Comment by benjiwheeler** [comment]
When I ran this scratchblocks file in staging, forum pages with blocks-eligible text took a long time to load fully -- 30 seconds or so. We're trying to figure out why.

**Comment by NitroCipher** [comment]
Hmm, thats odd. Are you using s3blocks.min.js or bundle.js?

**Comment by benjiwheeler** [comment]
I'm using the min.js link that you provided above. @tvjr's implementation is also making the page render very slowly; see https://github.com/scratchblocks/scratchblocks/issues/274#issuecomment-467999015

**Comment by tjvr** [comment]
> Both s3blocks and scratchblocks have their advantages;  Scratchblocks now has support for both 2.0 and 3.0 styles, but has syntax errors and is not directly compatible the scratch forums, so it will need to be resolved prior to release.

Out of interest, I'm not sure what you mean by this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NitroCipher** [comment]
> > Both s3blocks and scratchblocks have their advantages;  Scratchblocks now has support for both 2.0 and 3.0 styles, but has syntax errors and is not directly compatible the scratch forums, so it will need to be resolved prior to release.
> 
> Out of interest, what do you mean by this?

It is all fine now. You fixed it when you re-added rings. Everything works now afaik

**Comment by benjiwheeler** [comment]
Now both of your implementations are working faster -- don't know what was causing that problem for me before. Maybe there was some kind of cacheing issue.

@tvjr, I did notice that your blocks library compose menu isn't displaying correctly. @NitroCipher's menu looks like this: 

<img width="245" alt="screen shot 2019-03-05 at 3 18 10 pm" src="https://user-images.githubusercontent.com/3431616/53835220-f023df00-3f5a-11e9-9244-496de295c57f.png">

...but yours looks like this:

<img width="266" alt="screen shot 2019-03-05 at 3 21 59 pm" src="https://user-images.githubusercontent.com/3431616/53835241-f9ad4700-3f5a-11e9-9b53-f9fb9a059185.png">

**Comment by NitroCipher** [comment]
Glad to here, any idea why the speed was weird? On the topic of the menu, can we fix the z-index of it?

**Comment by benjiwheeler** [comment]
No, I can't figure out why the speed was so slow. It loaded quickly when the normal, Scratch2-style js file was in place, but both your changed js file, @NitroCipher, and @tjvr's caused the pages to take 17-30s to fully render. The problem might have been caused by one of my Chrome extensions acting up, but how they load fine with the same extensions active, AFAIK.

**Comment by towerofnix** [comment]
For what it's relevant, if possible, I think there should be `overflow-y: scroll` on the category list now, just like for the block list (i.e. list that shows up when you hover over a category); after all there is potential for the list to get very long, as we see even in NitroCipher's properly-displayed list.

**Comment by tjvr** [comment]
It looks different because I've updated the blocks to match Scratch 3.0. 🙂

Simply updating the list of blocks defined in the `menu.js` file should fix the problem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by memesong** [comment]
> @towerofnix Normally yes, but looking at the bbcode, the user used overrides to change the shape of a reporter to a hat, and changed the category `(when gf clicked ::hat events)`, rather than using brackets `{when gf clicked}`

Couldn't you have just used the `@greenFlag` syntax instead, though?
