### ISSUE TITLE
main view element min height creates unwanted spacing

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2729]
To repro:
1. view a project page for someone else's project that has commenting turned off, and no comments
2. observe space at the bottom:

![image](https://user-images.githubusercontent.com/3431616/51924722-92303480-23bb-11e9-9fb1-4532e8ab9729.png)

This is because the `#view` id in `main.scss` has `min-height: 768px`. Changing this to `min-height: 680px` fixes this problem.

Related: https://github.com/LLK/scratch-www/issues/1828

**Comment by R4356th** [comment]
@benjiwheeler, the space seems to have significantly decreased; is this issue still valid?

**Comment by benjiwheeler** [comment]
More about this: @carljbowman and I discussed this, and we noted that scratchr2 seems to handle this better; compare the scratchr2 project 404 page. scratch.mit.edu/projects/INVALID, when you zoom out and make the page tall, the footer sticks to the bottom of the page:

![image](https://user-images.githubusercontent.com/3431616/95115823-12bc4200-0714-11eb-8164-5159ff2aca2c.png)

![image](https://user-images.githubusercontent.com/3431616/95115825-13ed6f00-0714-11eb-9f9f-401e9ed6df14.png)

 Vs. on the www page, scratch.mit.edu/projects/9999999999999999 , where the footer positions according to the `view`'s `min-height`:

![image](https://user-images.githubusercontent.com/3431616/95115886-2d8eb680-0714-11eb-9bd0-ee8654257062.png)

![image](https://user-images.githubusercontent.com/3431616/95115912-397a7880-0714-11eb-8ebb-643b307aa270.png)

**Comment by benjiwheeler** [comment]
We merged a narrow fix to this case, but it could make sense to revisit the way we float the footer in the future to make it stick to the bottom of the window more aggressively.
