### ISSUE TITLE
"Assign yourself bugs" page references non-existent "first bug" label

### ISSUE THREAD

**Issue by tkelley-eg** [LLK/scratch-www#2743]
The documentation references a label that does not exist - `first bug`

GitHub docs recommend using the label `good first issue`.  See https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

Since this is designed to help GitHub users locate good first issues across the site, it might be beneficial to adopt this label?

### Steps to Reproduce

Visit https://github.com/LLK/scratch-www/wiki/Assigning-Yourself-Bugs

### Operating System and Browser

N/A

**Comment by tkelley-eg** [comment]
This is my first attempt at contributing, so I wanted to pick something basic so I could test out the workflow.  I'd be happy to address this in the docs.  This would obviously require the creation of the label by someone with the proper permissions.

**Comment by tkelley-eg** [comment]
Ah, I see that the source for that page isn't in this repo....  I don't see it in any other repo or that it's accessible from the "Scratch Wiki" site.  Is there a way for folks to contribute to this content?

**Comment by towerofnix** [comment]
GitHub wiki pages, like that one, are sort-of stored on a separate git repository internally, but it's only accessible to collaborators on the actual code repository (scratch-www), I believe. So the only way to contribute to it is to make suggestions, as you do in this issue.

**Comment by thisandagain** [comment]
Thanks for reporting. I removed that page as it was out of date and misleading.
