### ISSUE TITLE
Migrate Starter Projects

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#2744]
https://scratch.mit.edu/starter_projects/
(Linked from Ideas)

This should be migrated to scratch-www.

Questions:
1) will it retire? (I don't think so, ST kept it when they made Ideas)
2) should new projects be added?
3) localization of project notes/description?

**Comment by otsfan203** [comment]
That makes sense. No, it won't retire (or at least I don't think so) because one of the starter projects has a 3.0-added sprite in it and I doubt they'd update it just to retire it.
   As for the second question, I believe I answered that in my first answer. Third, I don't know.

**Comment by thisandagain** [comment]
Thanks @apple502j. This was on my list of items to file.  For your questions:

1. No. We would actually like to update it, so getting it over to WWW would make that easier.
2. Eventually yes, the ST has ideas for this.
3. No. Let's handle localization for project titles, notes, and descriptions as a separate matter to be discussed in the future.

**Comment by kyleplo** [comment]
I can take this

**Comment by thisandagain** [comment]
Sounds good!

/cc @chrisgarrity for any questions that come up.
