### ISSUE TITLE
Update Scratch Conference website 

### ISSUE THREAD

**Issue by me-win** [LLK/scratch-www#2761]
To support the regional Scratch conferences happening this year, we'll need to switch the Scratch conference website (scratch.mit.edu/conference) to this template: https://scratch.mit.edu/conference/2017  

We're still in the process of collecting content, which can be found in this [Google Doc](https://docs.google.com/document/d/1M_LJqOjAxxYFm3j-D8WbvFtWhZJgPCbZ5aNGSA2KZyc/edit?usp=sharing).

**Comment by thisandagain** [comment]
@benjiwheeler Can you take this on as a task for this month? We'd like to have this deployed by March 1st.

/cc @chrisgarrity

**Comment by benjiwheeler** [comment]
@thisandagain Will do.

**Comment by benjiwheeler** [comment]
blocked pending getting access to the google doc.

**Comment by me-win** [comment]
@benjiwheeler granted you access to the Google Doc!

**Comment by jakel181** [comment]
I would be happy to help as well. :)

**Comment by IamTregsthedev** [comment]
:D

**Comment by me-win** [comment]
*** Due to unforeseen circumstances, there's a possibility that Scratch Africa will be postponed until next year. Organizers are still considering their options and will let us know ASAP.**

*** Update the URL for Scratch Conference Europe.** 
Raspberry Pi folks just got back to us with an updated link for their website: scratchconferenceeurope.raspberrypi.org

*** Update the name and description for Conferencia Scratch al Sur.**
Name: Scratch al Sur Conferencia Chile 2019

Organizers provided us with a new, more detailed description...

_Scratch al Sur Conferencia Chile 2019 is an event aimed at teachers of all educational areas and levels, who seek to innovate in the classroom through creative learning, thus supporting public policies that are promoted through the National Plan of Digital Languages, launched by the Chilean government as of 2019. Various workshops, panels, experiences, stands, a presentation of the new Scratch 3.0, Makey-Makey, and much more will be offered._

These are not high priority updates, and it would be fine to push them mid or late May (or later).

**Comment by thisandagain** [comment]
Thanks @me-win! 

Just to confirm: what action would you like to take re: the Africa conference? Couple options:
- Remove the whole section
- Replace current copy with text provided
- Add text provided to the beginning of the current copy block
- Add text provided to the bottom of the current copy block
- Anything else you would like! :-)

@benjiwheeler Do you mind if I add this to your plate for May?

**Comment by me-win** [comment]
Hi, sorry for the delay!

Here's our suggestion:

- Remove the copy underneath the event title and replace it with the following copy:
 _The Scratch2019NBO conference, originally planned for Nairobi, Kenya in July 2019, has been postponed. Information about future plans will be available later this year_
- Move the whole section the bottom of the conference page.

**Comment by thisandagain** [comment]
No worries. Thanks @me-win!

@benjiwheeler any additional questions or are you good to move forward with this?

**Comment by benjiwheeler** [comment]
Here's what it looks like:

![screencapture-localhost-8333-conference-2019-2019-05-08-09_32_43](https://user-images.githubusercontent.com/3431616/57384055-e0ed2780-717d-11e9-93ec-f23f0b49a942.png)

**Comment by benjiwheeler** [comment]
Here's what it looks like:

![screencapture-localhost-8333-conference-2019-2019-05-08-09_32_43](https://user-images.githubusercontent.com/3431616/57384055-e0ed2780-717d-11e9-93ec-f23f0b49a942.png)

**Comment by benjiwheeler** [comment]
Here's what it looks like:

![screencapture-localhost-8333-conference-2019-2019-05-08-09_32_43](https://user-images.githubusercontent.com/3431616/57384179-198d0100-717e-11e9-966b-db67075ab590.png)

**Comment by me-win** [comment]
@benjiwheeler — updates look great! 

Can you also please update the event description for Scratch al Sur Conferencia Chile 2019? The new description is: 

**Scratch al Sur Conferencia Chile 2019 is an event aimed at teachers of all educational areas and levels, who seek to innovate in the classroom through creative learning, thus supporting public policies that are promoted through the National Plan of Digital Languages, launched by the Chilean government as of 2019. Various workshops, panels, experiences, stands, a presentation of the new Scratch 3.0, Makey-Makey, and much more will be offered.**

**Comment by benjiwheeler** [comment]
@me-win Oh, thanks for noticing -- I did change it, but I didn't update the screenshot. I'll do that now.
