### ISSUE TITLE
Unable to sign in on Firefox

### ISSUE THREAD

**Issue by DrDingleberry** [LLK/scratch-www#2762]
Clicking the sign in button and typing username and password does nothing, except for resetting the username and password fields.
### Steps to Reproduce
Just open up the latest version of Firefox, and attempt to sign in.
### Operating System and Browser
Windows 10 x64 1809 Firefox 65.0
_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by locness3** [comment]
Are you logged in when you type username and password, submit and then reload the page ?

**Comment by DrDingleberry** [comment]
> Are you logged in when you type username and password, submit and then reload the page ?

Nope, doesn't work. I checked the console in inspect element, and no errors seem to be thrown.

**Comment by thisandagain** [comment]
@DrDingleberry Can you please try this in a private window in Firefox? This may be due to a caching and/or browser extension issue and we'd like to rule that out before proceeding.

**Comment by DrDingleberry** [comment]
@thisandagain I was able to log in in a private window, but I have no extensions installed, leading me to believe that this is a bug with caching, as you suggested. I guess the next step is to find out whether the issue is with Firefox or Scratch.

**Comment by thisandagain** [comment]
@DrDingleberry Unfortunately we have seen some problems with corrupted caches in Firefox recently. I recommend you clear your cache and try logging in again.
