### ISSUE TITLE
Mod job posting: "read and write another language" rather than "speak"

### ISSUE THREAD

**Issue by seotts** [LLK/scratch-www#2768]
Under "Qualification" on https://scratch.mit.edu/jobs/moderator, it says, "Not required, but would be cool: Ability to speak another language." But really, we're looking for folks who can read and write languages other than English-- just speaking would not be as useful.

So, I propose we change "Not required, but would be cool: Ability to speak another language." to "Not required, but would be cool: Ability to read and write another language."

**Comment by Kenny2github** [comment]
I think that's a bug, not a suggestion - it definitely *should* say read and write rather than speak. Is this `help wanted`?

**Comment by jakel181** [comment]
I've done it! :) It is linked in this pull request. https://github.com/LLK/scratch-www/pull/2773 I would love to apply for it too, but I would need to wait two more years hahaha. Anyways, I hope it has been done correctly! :)

**Comment by jakel181** [comment]
Well I think this can be closed now! :D @thisandagain https://github.com/LLK/scratch-www/pull/2807
