### ISSUE TITLE
Update community moderator job description

### ISSUE THREAD

**Issue by dietbacon** [LLK/scratch-www#2806]
Update text of https://scratch.mit.edu/jobs/moderator with job description fromhttps://docs.google.com/document/d/1TYus13MIF717HSUpcdzI5yio_fem26btmnGZG7WIpxI/ to more accurate reflect the typical duties of the moderator position.

File: https://github.com/LLK/scratch-www/blob/develop/src/views/jobs/moderator/moderator.jsx

**Comment by jakel181** [comment]
@dietbacon I can take this as well, if it isn't the same as this:  https://github.com/LLK/scratch-www/pull/2807 :)

**Comment by thisandagain** [comment]
Resolved in #2807
