### ISSUE TITLE
Some users aren't getting a project id when creating a new project

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2818]
When you're signed in and you create a new project it should give you a project ID that you can see in the URL.  Some users are reporting that they are unable to save and when they sent a screenshot it clearly shows that they are signed in and in the editor but there is no project id in the url.

![img_5116](https://user-images.githubusercontent.com/1088291/53762094-2e56cb00-3e95-11e9-8449-b0b8fa043533.jpeg)

In this state they have no way to save their project that they have been working on.

### Steps to Reproduce

This seems to happen irregularly and I haven't been able to reproduce it yet.

### Operating System and Browser

Chrome on Chromebook

**Comment by jakel181** [comment]
Maybe it has something to do with all those extensions?

**Comment by BryceLTaylor** [comment]
I've been completely unable to reproduce this on any of our chromebooks.  I've occasionally gotten reports of people being unable to save, that I think may be this issue, but it's hard to confirm.  I am going to close this and reopen it if we get another report with more information.

**Comment by benjiwheeler** [comment]
@BryceLTaylor @thisandagain I think it might be worth my spending some time looking at ways that the project-state reducer could get into this state.

The project-state reducer leans pretty heavily on the assumption that react will call `componentDidUpdate` at least once for every change in the component's props; there could be edge cases we're not catching, either with that assumption or with other assumptions.
