### ISSUE TITLE
Add micro:bit cards to the /microbit page

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#2830]
Add link to download micro:bit Scratch cards to the microbit extension page. Place it after Starter Projects, before Troubleshooting.

Here is the [PDF](https://www.dropbox.com/s/8ud9bei5do7fzem/microbit-scratch-cards.pdf?dl=0) (Note: PDF may get updated - Natalie and KO will confirm )

/cc @kosiecki17

**Comment by benjiwheeler** [comment]
Seems simple. We could borrow the scratch cards section on the ideas page, or design something more Microbit-specific.

**Comment by thisandagain** [comment]
@ntlrsk I moved this to May due to some scheduling pressure. Is that ok with you?

**Comment by benjiwheeler** [comment]
Labeling this as 'needs discussion' pending @carljbowman clarifying plans.

**Comment by benjiwheeler** [comment]
Update: still waiting on further discussion from the team. Maybe this should be more explicitly put on one person's plate, or backlogged?

**Comment by thisandagain** [comment]
@benjiwheeler I added this to our weekly design meeting agenda. Will follow-up after discussion.

/cc @carljbowman

**Comment by kathymakes** [comment]
Here's one potential design & copytext that we'd like to chat more about with @ntlrsk and @kosiecki17. We'll loop back after our design meeting on 8/15:
 <img width="714" alt="Screen Shot 2019-08-01 at 5 17 22 PM" src="https://user-images.githubusercontent.com/8203939/62328136-4b152000-b480-11e9-965f-1e01f529f1ea.png">

**Comment by thisandagain** [comment]
@kathymakes Looks great! Let's move forward. My only nitpick would be to remove the duplicate trail of "S"s in the illustration, but I'm happy to defer to your judgement. Let's move forward with implementation.

/cc @benjiwheeler

**Comment by kathymakes** [comment]
### Illustrated section
<img width="1317" alt="Screen Shot 2019-08-08 at 2 06 40 PM" src="https://user-images.githubusercontent.com/8203939/62726663-c416f900-b9e5-11e9-9f50-8bd07f0917c8.png">

### In context

![microbit Cards Design](https://user-images.githubusercontent.com/8203939/62726611-a5b0fd80-b9e5-11e9-9bde-116eace503c1.png)
