### ISSUE TITLE
Search url escaping does not happen, throws error if user clicks between Projects and Studios

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2831]
### Steps to Reproduce

1. search for "100% pen"
2. results look good, and URL querystring looks like `?q=100%25%20pen`
3. now click Studios
4. site throws error with "Oops", URL querystring looks like `?q=100%+pen/`

The same problem happens if you first go to `https://scratch.mit.edu/search/studios?q=100%25%20pen`, then click Projects.

**Comment by Kenny2github** [comment]
I believe it's not HTML escaping but rather URL escaping... and the specific problem is that the links to "projects" or "studios" aren't URL-escaped.

**Comment by 439bananas** [comment]
Hey, might I bring up that \*%\* causes an error?

**Comment by MasterOfTheTiger** [comment]
> Hey, might I bring up that *%* causes an error?

That is exactly it. The "%" sign is escaped in some situations but not others.
