### ISSUE TITLE
Rename the Scratchteam account

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-www#2832]
_currently the scratch team account with all the starter projects is called Scratchteam -- notice the missing capital T._

This would add unified scratch team accounts Example ScratchCat

So it should be called ScratchTeam
### Steps to Reproduce

visit the scratch team account @Scratchteam

**Comment by Kenny2github** [comment]
...not an issue with scratch-www, should not be opened here. Contact an ST member on their profile instead.

**Comment by DeleteThisAcount** [comment]
whoops sorry
