### ISSUE TITLE
_ksllxmfcai_ easter egg doesnt work on project page

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-www#2833]
The _ksllxmfcai_ easter egg (turns into triangle eye) doesnt work on project pages

### Steps to Reproduce

Visit comment section on any project

Comment _ksllxmfcai_

Notice it doesnt turn into triangle eye

**Comment by apple502j** [comment]
It was removed.

**Comment by thisandagain** [comment]
This was a april fools day feature that was meant to be temporary.

**Comment by DeleteThisAcount** [comment]
no, @thisandagain currently in profile comments it actually turns into the word triangle eye, shouldnt this also work in project comments?
