### ISSUE TITLE
link to story tutorial should open Create a Story tutorial

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#2837]
This tutorial link isn't working:
https://scratch.mit.edu/projects/editor/?tutorial=story

It opens the editor, but it should also open the Tutorial Window with the Create a Story tutorial. We need this link for an upcoming ISTE blog post on Scratch resources.

(Note: We understand that the back button from any tutorial will go to the Scratch editor, but that's OK.)

![image](https://user-images.githubusercontent.com/4721032/54153973-3ecbf000-4417-11e9-9f57-840ecbf2899b.png)

Thanks!

**Comment by apple502j** [comment]
Easy fix:
Just by changing https://github.com/LLK/scratch-www/blob/3aa37d5a82f75f2fc3657b6ae73120a4df76034f/src/routes.json#L452 to 
`/projects/editor/?tutorial=tell-a-story`

**Comment by ntlrsk** [comment]
@apple502j thanks for highlighting that "=tell-a-story" is working - we can use that for the ISTE blog post. Eventually having the /story work will be helpful.

**Comment by joker314** [comment]
@apple502j is also suggesting a fix. /story is something which is automatically redirected, but it is currently redirecting to an invalid place. Changing the linked line will fix the issue.
