### ISSUE TITLE
Update "Siegel Family Endowment" logo on credits page

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#2849]
Update the "Siegel Family Endowment" logo on credits page with a new logo file (see below).

### Before
![image](https://user-images.githubusercontent.com/747641/54704619-7884b100-4b11-11e9-9b67-ab000757eac3.png)

### After
![sfe](https://user-images.githubusercontent.com/747641/54704829-e4ffb000-4b11-11e9-8da0-1be150783b59.png)

### Assets
[SFE-RIGHT-GRADIENT.svg.zip](https://github.com/LLK/scratch-www/files/2989297/SFE-RIGHT-GRADIENT.svg.zip)

**Comment by IamTregsthedev** [comment]
I'll do this, as I added Siegel into the credits page in my first PR.

Which File is this?

**Comment by thisandagain** [comment]
@IamTregsthedev I'd rather someone take this that is more familiar with our codebase. We are going to create a new label soon called "good first issue" that may be a better fit for you until you become more comfortable with the WWW code. Thanks for the offer though!

**Comment by IamTregsthedev** [comment]
I really want to do this, so if i could Please know where the file is?

**Comment by benjiwheeler** [comment]
@iamtregstgedev, as @thisandagain explained, this particular issue is not a good match for someone who isn't familiar with the code base yet.

It's great that you are eager to help! Please look out for the "good first issue" label, which will help mark items that would be a good match for you, as you get more familiar with the code in this repo!
