### ISSUE TITLE
You can't reply to a comment in the "single comment view

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-www#2860]
### Expected Behavior
After you click the send button, the comment will be sent properly

### Actual Behavior
After you click the send button, the single comment view disappears and the comment didn't send

### Steps to Reproduce
Open message and click a comment replied to you, reply to the comment in the single comment view

### Operating System and Browser
Win 8, Chrome 71
From scratch_gui 4679

**Comment by paulkaplan** [comment]
@BryceLTaylor i couldn't repro this. One thing I was able to do was when replying to a nested comment, and there are a lot of nested comments, your comment gets put at the bottom of that list, so you might not be able to see it without hitting "load more comments".
