### ISSUE TITLE
Unverified user posting project page comment gets unclear error

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2861]
If you have created an account and not verified it you can't post comments on project pages.  However, it does show you a text box for posting a comment.  If you enter a comment and submit it you get an error that is not clear.  "comments.isNotPermitted" and the comment box still appears.

<img width="955" alt="Screen Shot 2019-03-26 at 10 24 35 AM" src="https://user-images.githubusercontent.com/1088291/55005489-778ccd00-4fb2-11e9-9fde-1f6fc0da5c2c.png">

### Steps to Reproduce

Create a new account, but don't verify your email
Navigate to a project page for a project you don't own
Enter a comment below the project and click post
Note: the error appears

### Operating System and Browser

Mac Chrome

**Comment by apple502j** [comment]
yes, that's it... maybe someone forgot to add the message at /src/l10n.json .
I know message ID will be used if there is no json entry.

**Comment by benjiwheeler** [comment]
Ran into this one just now. This should be a very quick fix.

**Comment by fsih** [comment]
It would probably be helpful to explain why the user is not allowed to comment and how to fix it (e.g. look for verification email)

**Comment by paulkaplan** [comment]
@carljbowman mentioned this is what we did in 2.0 
![image](https://user-images.githubusercontent.com/654102/73491011-ae263780-437b-11ea-84f4-d9433260ea6a.png)

I think getting a basic string there should be a high priority.
