### ISSUE TITLE
Maori is not translated on the site

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#2873]
When you switch to Maori on a page in www (e.g. splash, explore) all the text shows up as the message ids.

It's just a problem for www (the gui and legacy pages show up in maori). I've confirmed that Maori strings are defined in scratch-l10n. The generated intl file has an entry for maori `mi` with the maori strings defined.

Maori has a custom locale because it wasn't available in `react-intl/locale-data` when we added it. It's there now, so it should also get updated. That might be related to the problem, but I don't think so.

This needs deeper investigation.

**Comment by thisandagain** [comment]
Marking this as "critical" given the connection to our work with UNESCO and the conference coming up in May. @benjiwheeler would you be willing to pair with @chrisgarrity on this?

**Comment by benjiwheeler** [comment]
Yes, will prioritize it.
