### ISSUE TITLE
Scratchr2 wiki link is outdated

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#2885]
It's been a year since the [server transfer](https://en.scratch-wiki.info/wiki/Scratch_Wiki#Server_Transfer) and the link to the Wiki on profiles and forums is still the old wiki.scratch.mit.edu domain.

### Steps to Reproduce

Visit any scratchr2 page.

**Comment by apple502j** [comment]
@Kenny2github Here's scratch-www, you know. You should ask at BaG or ST's profile.

**Comment by Kenny2github** [comment]
@apple502j I tend to report issues with scratchr2 on scratch-www anyway so that the issue can be moved to the scratchr2 repository without much effort.

**Comment by benjiwheeler** [comment]
Thanks for filing. We filed this at https://github.com/LLK/scratchr2/issues/5120
