### ISSUE TITLE
[Language][French] Homepage : Gobo Text Cut Off

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-www#295]
![french cut off](https://cloud.githubusercontent.com/assets/6530036/11878946/87257568-a4c6-11e5-81e1-b719d7f08448.jpg)

**Comment by Tymewalk** [comment]
Tera's text looks cut off, too.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-www/issues/1198
