### ISSUE TITLE
Remixed projects should not show comments from the original

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#2990]
After remixing and sharing a project I viewed the project page and the comments from the original project were still visible. After refreshing the page the comments were gone.
![x-comments](https://user-images.githubusercontent.com/399209/58095896-ebf27f80-7ba1-11e9-8e4a-a0adda0edd59.png)

### Steps to Reproduce

1. Click the remix button on a project
2. I made changes (I don't know if that would even be necessary)
3. I think I clicked view project page to change the instructions then clicked share, but it might have been the other way round (share, then see project page)

### Operating System and Browser

Mac OSX 10.14.4, Chrome Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by apple502j** [comment]
Duplicate of #2608

**Comment by chrisgarrity** [comment]
@apple502j thanks - I didn't see that one.
