### ISSUE TITLE
Image on the /educators page is returning a 404 error

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#2996]
All images on the /educators page should appear on the stage.

Instead the image next to the "How Educators Are Using Scratch" section is not appearing, showing a missing image icon.

![image (2)](https://user-images.githubusercontent.com/1088291/58200900-debcba00-7ca1-11e9-9c8b-0974149b04b2.png)

Checking the console, you get a 404 on this request: `https://scratch.mit.edu/educators/images/teachers/makey-activity.png` 
![Screen Shot 2019-05-22 at 2 58 11 PM](https://user-images.githubusercontent.com/1088291/58201011-162b6680-7ca2-11e9-860c-de406f27e440.png)

@thisandagain suggests: The image link is to "images/teachers/makey-activity.png" instead of "/images/teachers/makey-activity.png".

### Steps to Reproduce

Open the developer tools to the network tab
Check "Disable Cache"
Navigate to https://scratch.mit.edu/educators
Note: the image is broken

If you don't have the cache disabled you might load the image from your cache and not see the issue.

### Operating System and Browser

Chrome on Mac, Firefox on Mac

**Comment by apple502j** [comment]
Can't repro on Firefox 67, Windows 10
![image](https://user-images.githubusercontent.com/33279053/58235462-d173fe00-7d7b-11e9-985b-a0999dd33874.png)
