### ISSUE TITLE
Long instructions / notes and credits fields mess up layout

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#3011]
The picture says it all...

![A Scratch project with a very lengthy "Notes and Credits" section. The full content of it is visible, and it messes up the page's layout -- the box pushes the entire right column up and overflows below the project view section.](https://user-images.githubusercontent.com/9948030/58357202-49abf380-7e50-11e9-982c-fd65967363e9.png)

### Steps to Reproduce

Open the page of a project with a lengthy instructions/N&C value, created by someone other than you. (This doesn't happen on your own project pages because the actual input fields don't appear to have an issue.)

### Operating System and Browser

Firefox 66.0b3, Linux. Can't reproduce on Chromium.

/cc @thisandagain since this should be pretty high priority if it affects every Firefox user (needs repro on other devices / FF versions, but that is likely the case). I saw this happen on https://scratch.mit.edu (any project with long instructions/N&C).

**Comment by benjiwheeler** [comment]
Uh oh, this might be a problem I introduced with my recent change to that part of the site. I'll work on a fix right away. 

Thanks for pointing this out, @towerofnix.

**Comment by apple502j** [comment]
repro: firefox 77 on windows 10, same project

**Comment by benjiwheeler** [comment]
I repro'd it too, and made a much simplified use case using our html & css:

https://codepen.io/benjiwheeler/pen/earzje?editors=1100

Looks like the culprit may be this flexbox issue: https://stackoverflow.com/a/36247448

**Comment by NilsTheBest** [comment]
Sorry to burst in and if this isn't the right place to point this out, but apparently this also happens on Chrome? According to this post: https://scratch.mit.edu/discuss/topic/352810/ the user appears to be on Chrome and encounter the same problem.
