### ISSUE TITLE
[Feature Request] Center Costume

### ISSUE THREAD

**Issue by GarlandKey** [LLK/scratch-www#3051]
There are times when you need to center costumes more accurately than just eye-balling it. _Example: Sprites with multiple costumes that rotate from the center point of the sprite._

Right now you have no choice but to use the center marker to eye-ball the location of the costume.

**Comment by kyleplo** [comment]
This should be on llk/scratch-paint

**Comment by GarlandKey** [comment]
https://github.com/LLK/scratch-paint/issues/456

Closing.
