### ISSUE TITLE
Migrate - Contact Us

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#308]
[Description added by @benjiwheeler in Oct 2019]

The Contact Us page looks like this:

![image](https://user-images.githubusercontent.com/3431616/67578127-d284cf00-f70f-11e9-9e65-342de3c2c326.png)

It should be updated for Scratch 3.0, moved from scratchr2 to this repo (scratch-www), and revised in consultation with the Scratch Team!

**Comment by St19Galla** [comment]
I can take this one off of @technoboy10 's hands if he would like!

Any particular page template you want me to go off of?

**Comment by thisandagain** [comment]
@St19Galla Thanks! I think we should hold off on this one until we have a plan for how to handle the form in our new API.

**Comment by benjiwheeler** [comment]
Some updated collected thoughts, from across the team:

* what text should the contact us page have?
* what options appear in that dropdown?
* are there things we can do with the form that are more complex? (i.e. add options to the dropdown which, if selected, would provide answers to some of the more simple questions people submit instead of sending us an email)

**Comment by apple502j** [comment]
Here are some opinions:
- l10n for forum link. Some Japanese people created several QaS topics in Japanese.
- Optional email for logged-ins (the response comes as alerts or messages) This is quite useful when users themselves don't own emails.
- Dropdown options:
-- Inappropriate contents
lets user type "where" and "who"
-- Impersonation
lets user type who impersonated who
-- Login Problems
let them reset password (not forced)
-- Email Problems
-- Bugs (including Security)
this is forwarded to Dev Team if possible to do so?
-- Licensing and Branding
Kind of "can I make Scratch Cat mug" or something
-- DMCA
Redirects to DMCA page
-- Jobs
-- Press
-- Account Suspension Request

**Comment by apple502j** [comment]
@chrisgarrity this can be closed
