### ISSUE TITLE
Missing translation for comment error `isNotPermitted`

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-www#3093]
The API returns an error key (`isNotPermitted`) that currently does not have a corresponding translation in `l10n.json` (around line 230).

This happens when you try to comment after creating an account a moment previiously. If you hit this issue you see
<img width="705" alt="Screen Shot 2019-06-27 at 11 39 35" src="https://user-images.githubusercontent.com/654102/60281332-c4927f00-98d2-11e9-91db-dd85c37aa4a6.png">

Credit to @fsih for finding this

**Comment by benjiwheeler** [comment]
tracked in https://github.com/LLK/scratch-www/issues/2861
