### ISSUE TITLE
Educator Page Update

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#311]
Update `https://scratch.mit.edu/educators/` with new content that highlights Scratch use in classroom and after-school settings.

Need:

- [x] Final content structure (@kaschm)
- [x] Design (@carljbowman)
- [x] Final links to Scratch Foundation blog when interviews are up (@kaschm)

**Comment by thisandagain** [comment]
Blocked on content & design. Assigning to @kaschm for tracking.

**Comment by kaschm** [comment]
Thanks @thisandagain !

**Comment by kaschm** [comment]
Final content here: https://docs.google.com/document/d/16gJYgW-di4M0pFE0mCWmnRmRMTYnz-jo4Sw_OoVxUjE/edit

**Comment by kaschm** [comment]
@carljbowman , screenshot for the page is here:
https://drive.google.com/a/media.mit.edu/file/d/0BwdnRUms3m2bMHZacWdoNWhsa1E/view?usp=sharing

**Comment by carljbowman** [comment]
## Scratch For Educators 

**Assets**
[for-educators-assets.zip](https://github.com/LLK/scratch-www/files/303307/for-educators-assets.zip)


**Missing Content** 
@kaschm - For each of the 4 User Stories 
- [ ] Name of person and association (e.g. school)
- [ ] Photo 

### Desktop (12cols)
![r3_educators-landing](https://cloud.githubusercontent.com/assets/3409578/15869878/40292550-2cbc-11e6-9721-9ee395031797.png)

![r3_educators-landing 12cols](https://cloud.githubusercontent.com/assets/3409578/15869896/5977a70c-2cbc-11e6-8e2e-be9c68ef8356.png)

### Tablet – Desktop (8cols)
![r3_educators-landing 8cols](https://cloud.githubusercontent.com/assets/3409578/15869906/606813f8-2cbc-11e6-8ddb-8c2fe8a9bdcb.png)

### Mobile – Tablet (6cols)
![r3_educators-landing 6cols](https://cloud.githubusercontent.com/assets/3409578/15869925/6be89ec8-2cbc-11e6-8ebf-051b43198e0b.png)

### Mobile – (4cols)
![r3_educators-landing 4cols](https://cloud.githubusercontent.com/assets/3409578/15869938/77b52fc8-2cbc-11e6-9d55-1927e52d5226.png)

**Comment by carljbowman** [comment]
## Scratch for Educators

**Assets:** [6.21_for-educators-assets.zip](https://github.com/LLK/scratch-www/files/325686/6.21_for-educators-assets.zip)


### Desktop (12cols)
![final_educators-landing 12cols](https://cloud.githubusercontent.com/assets/3409578/16231142/e130cfbc-3792-11e6-9f63-eeb9da305ad3.png)

![final_educators-landing 12cols-grid](https://cloud.githubusercontent.com/assets/3409578/16231145/e4ce0d42-3792-11e6-879d-4cabc5b8cab3.png)

### Tablet – Desktop (8cols)
![final_educators-landing 8-cols](https://cloud.githubusercontent.com/assets/3409578/16231152/f957373e-3792-11e6-8ef3-967b085be988.png)

![final_educators-landing 8-cols-grid](https://cloud.githubusercontent.com/assets/3409578/16231154/fc092ac8-3792-11e6-89b3-d5691d8b4360.png)

### Mobile – Tablet (6cols)
![final_educators-landing 6-cols](https://cloud.githubusercontent.com/assets/3409578/16231166/06b10d38-3793-11e6-9537-fb0ec8be6680.png)

![final_educators-landing 6-cols-grid](https://cloud.githubusercontent.com/assets/3409578/16231168/08de1bc8-3793-11e6-8a4c-3f778231b46f.png)

### Mobile (4cols)
![final_educators-landing 4-cols](https://cloud.githubusercontent.com/assets/3409578/16231171/10c91f04-3793-11e6-98d3-faafa457e447.png)

![final_educators-landing 4-cols-grid](https://cloud.githubusercontent.com/assets/3409578/16231172/13c73114-3793-11e6-9bc4-7676acff7cce.png)

**Comment by carljbowman** [comment]
@technoboy10 - Updated the Assets zip to include images for the cards in the 'Who Uses Scratch' section. These images reflect the stories listed in the [Google Doc](https://docs.google.com/document/d/16gJYgW-di4M0pFE0mCWmnRmRMTYnz-jo4Sw_OoVxUjE/edit), which differ from the cards speced in the mocks. That said the design will not change based on this content adjustment.

**Comment by kaschm** [comment]
@carljbowman @technoboy10 - reading the thread, I believe that we're set for interviewee content - but if you're missing anything, please ping me ASAP. Thanks!

**Comment by carljbowman** [comment]
@kaschm - We are all set. The google doc is all up to date and we have all the image assets. Thanks!
