### ISSUE TITLE
Make unit tests look for test files in sub directories

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#3157]
Right now, `npm run test` will run the unit tests in the unit folder.  If we add any kind of folder structure to organize tests they won't get run.  We should make sure we change the script in package.json that runs the unit tests to look in sub directories when any are added.

**Comment by benjiwheeler** [comment]
Resolved by https://github.com/LLK/scratch-www/pull/3162

**Comment by benjiwheeler** [comment]
Closing this because the solution for unit tests used in #3162 isn't very generalizable -- it depends on all the files in a directory being test files, an assumption that isn't correct in other directories.
