### ISSUE TITLE
Master - Several pages, such as the homepage, do not function at all

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#3203]
Several pages, including the Scratch homepage, no longer function at all, showing a blank white or blue screen as soon as the page loads. The console shows this log:

```
TypeError: e[r] is undefined
common.bundle.js:1:96
    t https://scratch.mit.edu/js/common.bundle.js:1
    <anonymous> https://scratch.mit.edu/js/splash.bundle.js:36
    t https://scratch.mit.edu/js/common.bundle.js:1
    webpackJsonp https://scratch.mit.edu/js/common.bundle.js:1
    <anonymous> https://scratch.mit.edu/js/splash.bundle.js:1
```

The "Stop! This is part of your browser intended for developers..." message still displays (as well as warnings about onmozfullscreenchange, etc being deprecated).

### Steps to Reproduce

Open any of these pages:

* https://scratch.mit.edu (blank white screen)
* https://scratch.mit.edu/explore/projects/all (blank blue screen)
* nearly any other scratch-www page

Note some pages still do work:

* https://scratch.mit.edu/about (but other about pages, e.g. ToS, "for parents", Jobs don't work)
* Project pages
* any page from scratchr2

### Operating System and Browser

Linux Firefox, Chromium; Mac Firefox, Safari.

/cc @thisandagain this seems reasonably urgent enough to ping? :P

**Comment by thisandagain** [comment]
We are on it.
