### ISSUE TITLE
Make pushing strings to transifex easier

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#3215]
Currently, if someone wants to push strings from current l10n files up to Transifex, they must have the `tx` commandline program installed. But this is inconvenient.

@chrisgarrity writes:
> we should add the transifex npm package and write a script that will do the tx push for the l10n files. Then all anyone needs is a TX_TOKEN, and if it's not someone who's on transifex in any case they can just use the shared one.

> Essentially we need the www version of https://github.com/LLK/scratch-l10n/blob/master/scripts/tx-push-src.js

**Comment by chrisgarrity** [comment]
Actually I was just looking and https://github.com/LLK/scratch-l10n/blob/master/scripts/tx-push-src.js has the basis of what's needed. But it's designed for just one file,

i.e. `tx-push-src scratch-website general-l10njson ./src/l10n.json`

We need something that does it for all the l10n files.

**Comment by benjiwheeler** [comment]
Current thinking: let's tie the update to when developers merge to the develop branch.

This will allow translators the earliest reasonable access to the strings, so that many translations can be in place already when we deploy.

We know there is some string thrashing, but in most cases there is none or it settles down quickly.

We also think this will be better than tying the update to a cron job, because it will be in clearer sync with the version we are preparing to deploy, and there will not be a separate, unique point of failure.

**Comment by benjiwheeler** [comment]
Described some of our longer-term intentions to consolidate route and transifex resource strings here: https://github.com/LLK/scratch-www/issues/3642

**Comment by benjiwheeler** [comment]
Turns out https://github.com/LLK/scratch-www/pull/3643 did not correctly connect Travis cron to the relevant new translations push job.
