### ISSUE TITLE
Wording on Scratch download page is confusing for Scratch 2

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#3238]
On the Scratch download page, the link for Scratch 2 says: "Scratch 2.0 Desktop" - this is confusing because everywhere else "Scratch Desktop" is the name of Scratch 3.0. 

The link should just say "Scratch 2" or "Scratch 2 Offline Editor" since the software itself just says Scratch 2 (see below).

![image](https://user-images.githubusercontent.com/4721032/62826099-f1011280-bb83-11e9-86be-eb08687a7f72.png)

![image](https://user-images.githubusercontent.com/4721032/62826132-6371f280-bb84-11e9-98a5-60805c969c7e.png)

![image](https://user-images.githubusercontent.com/4721032/62826137-708ee180-bb84-11e9-8699-cdd43ce6aa18.png)

**Comment by towerofnix** [comment]
Is there any reason for 1.4's link to say "Scratch 1.4 Desktop" either? There's never been an (official) online release of the 1.4 editor, so if 2.0's link is changed to just "Scratch 2.0", it'd only be consistent to change the 1.4 link the same way.

**Comment by ntlrsk** [comment]
I agree that 1.4 also should not be named Desktop to avoid confusion.

**Comment by chrisgarrity** [comment]
fixed in https://github.com/LLK/scratch-www/pull/3429
