### ISSUE TITLE
Project pages' incompatibility for mobile screens.

### ISSUE THREAD

**Issue by GDUcrash** [LLK/scratch-www#3284]
On mobile devices (in portrait mode), on project pages, the stage canvas goes off the screen and this is really annoying.

The website itself looks really optimized to mobile screens, but the canvas... :/

![Screenshot_2019-08-21-20-49-44](https://user-images.githubusercontent.com/35695734/63455342-475c3400-c455-11e9-8150-eae0ae296313.png)

### How this can be fixed

I know, thats not really easy to resize a canvas, but my idea is to use css `transform: scale() ` property, but maybe there might be better solutions.

**Comment by benjiwheeler** [comment]
Thanks @GDUcrash, we actually have a (long delayed and overdue) fix in the works!

Closing per existing issue https://github.com/LLK/scratch-www/issues/2513
