### ISSUE TITLE
Investigate why more projects are being tagged with language 'en'

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#3325]
Since the launch of 3.0 proportionally more projects are tagged 'en', and it's probably incorrect. Figure out what's missing to get projects tagged with the correct language everywhere.

**Comment by thisandagain** [comment]
@chrisgarrity Moving this to November.

@rschamp @kchadha Some context: there is something going wrong during project creation which is causing the vast majority of new projects to be saved with "en" as the language which is throwing off our reporting.
