### ISSUE TITLE
Add/Remove Moderators on Credits Page

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#333]
We need to add two people to the credits page (https://scratch.mit.edu/info/credits/) under Community Moderators:

1) Linda Fernsel (https://scratch.mit.edu/users/lifaythegoblin/)
2) Lily Kim (https://scratch.mit.edu/users/pinkfoot123/)

We also need to remove Megan Haddadi from the Community Moderators list and add her to the "Previous MIT Scratch Team Members" list

**Comment by technoboy10** [comment]
I can take this one. (Not sure how to assign myself directly)
