### ISSUE TITLE
[A11y] Webaim Reports Some Errors 

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-www#337]
went to wave.webaim.org

saw the following https://saucelabs.com/tests/7bb20b0bcfb1490c914103ea44e43ee9

from error: 

language of doc missing
noscript element alert
heading level skipped

Not sure if errors valid .. please close if not valid

**Comment by mewtaylor** [comment]
@thisandagain @rschamp there are some different tools we could use for this that seem to differ on levels of severity (example: chrome accessibility tab versus webaim.org). I'm wondering if we'd want to decide on one tool to all use, and then maybe see if it's something we could add to our testing process? i.e. an accessibility linter of sorts?

**Comment by thisandagain** [comment]
Having it integrated into `npm test` seems ideal. I don't know of anything off the top of my head, but likely worth some research.
