### ISSUE TITLE
Add shortcuts for "Imagine a World" and "Make it Fly" tutorials

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#3390]
Add/update these 3 redirects, for HoC:
/imagine -> /projects/editor/?tutorial=imagine-if
/makeitfly ->/projects/editor/?tutorial=make-it-fly 
/fly ->/projects/editor/?tutorial=make-it-fly

**Comment by ntlrsk** [comment]
Checking in on this as we are highlighting scratch.mit.edu/imagine for HOC.
