### ISSUE TITLE
Update current team on Credits page

### ISSUE THREAD

**Issue by dietbacon** [LLK/scratch-www#3410]
The Credits Page at https://scratch.mit.edu/credits has some updates needed (mostly moderator additions/removals, but a few others as well):

Add:

Amy Lee (amylaser)
Maren Vernon (algorithmar)
JT Galla (bluecrazie)
Zachary Deiman (Za-Chary)
Joan Fusco (Mos20)
Jacy Edelman (pixelmoth)

Move to Past Contributors:

Tina Quach (quacht)
My Nguyen (me_win)
Lisa O'Brien (lob12)
Joel Gritter (GulpTea)
Linda Fernsel (LiFayTheGoblin)
Ellen Daoust (SunnyDay4aBlueJay)
Julia Zimmerman (stymphalianbirb)

Remove: 

Nicole Hughes (theladynico)

**Comment by apple502j** [comment]
[help wanted] or no?

**Comment by JoelGritter** [comment]
@dietbacon Any updates on Joan's username?
@apple502j I'd guess this would be [help wanted] after we get Joan's username. 👍

**Comment by apple502j** [comment]
@JoelGritter There exists some members without usernames in the Credits at the moment.

**Comment by dietbacon** [comment]
I see this has already gone out with most of the changes made, but 2 new names have been added to the add list:

Joan Fusco (Mos20)
Jacy Edelman (pixelmoth)

**Comment by apple502j** [comment]
Thanks!
