### ISSUE TITLE
Make capitalization of "macOS" consistent across Downloads and Extensions Pages

### ISSUE THREAD

**Issue by kaaaaathy** [LLK/scratch-www#3413]
## Background
Sometimes we write "macOS," other places we write "Mac," or "Mac OS."

**Example:** [Downloads Page](https://scratch.mit.edu/download):

<img width="460" alt="Screen Shot 2019-09-26 at 7 17 49 AM" src="https://user-images.githubusercontent.com/8203939/65698114-e4038a00-e030-11e9-80e9-e46fbe133301.png">

**Example:** FAQ/Troubleshooting section, Extension pages:
(Scroll to bottom of [micro:bit page](https://scratch.ly/microbit), for example)

<img width="583" alt="Screen Shot 2019-09-26 at 7 21 12 AM" src="https://user-images.githubusercontent.com/8203939/65698122-e6fe7a80-e030-11e9-9f20-1bd0d4da6e5a.png">

________
## Proposal
Apple uses "macOS" when they are talking about OS versions, and "Mac" when they talk about the hardware product.

We will soon have other OS's like ChromeOS, which we probably don't want to refer to as Chrome, since it could be confused with the browser. 

**Let's use "macOS" with lowercase capitalization everywhere**, since we're usually talking about the OS version.

**Comment by apple502j** [comment]
`[help wanted]` or no?
