### ISSUE TITLE
FAQ references the "Echo" effect in the sound editor which has been removed

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#3454]
scratch.mit.edu/info/faq has a question about new features in the sound editor.  It mentions new effects and talks about the Echo effect, which has been removed.

![Screen Shot 2019-10-16 at 10 18 30 AM](https://user-images.githubusercontent.com/1088291/66927964-b2159000-effe-11e9-9edd-15364c7dddd7.png)

![Screen Shot 2019-10-16 at 10 18 22 AM](https://user-images.githubusercontent.com/1088291/66927975-b5108080-effe-11e9-867a-fcd13003d955.png)

We should remove the reference to the echo effect.

**Comment by apple502j** [comment]
[help wanted]?
