### ISSUE TITLE
npm run start  Invalid regular expression error

### ISSUE THREAD

**Issue by BaLaLaLs** [LLK/scratch-www#3463]
System: Mac os catalina 10.15 and windows 10.
My two computers are the same. I didn't edit any code
stop:
 git clone 
npm install
npm run start 
![image](https://user-images.githubusercontent.com/23353559/67084100-e50e7e00-f1ce-11e9-9769-9fb54ae2baae.png)

**Comment by apple502j** [comment]
Try using the very latest scratch-www, I think. The regex changed since then.
