### ISSUE TITLE
Upgrade to Node 4.2.X LTS

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#351]
We should move from Node 0.12 to the 4.2 LTS release now that it is stable.

- [x] Update `dependencies`
- [x] Update `devDependencies`
- [x] Test Node 4.2.X LTS locally
- [x] Add `4.2` to travis.yml
- [x] Land in staging for testing
- [ ] Update continuous deployment target
- [ ] Retire old environment

**Comment by liam4** [comment]
Goodness me yes. Node 0.12 is terrible. :)

**Comment by thisandagain** [comment]
> Node 0.12 is terrible. :)
Can you explain what you mean by "terrible"? Please try to be constructive with your comments.

**Comment by liam4** [comment]
It's support for ES6 is much less complete than Node 4 and 5. NPM generally is more user friendly.

**Comment by thisandagain** [comment]
"Less complete ES6 support" != "terrible". I'd appreciate if we could try to be constructive and explicit when working through technical issues.

**Comment by liam4** [comment]
Okay, I'll try to be more constructive.

**Comment by Jonathan50** [comment]
```
$ node --version
v5.4.1
$ nodejs --version
v0.10.29
$ 
```
this is confusing

**Comment by mewtaylor** [comment]
@Jonathan50 I think it's safe to follow the `node` version (see the versions in the [changelog](https://github.com/nodejs/node/blob/v5.5.0/CHANGELOG.md#2016-01-12-version-541-stable-thealphanerd), which match up with it). If you have any additional questions/issues with downloading and installing node, it might also help to checkout their [repo](https://github.com/nodejs/node) – it's super well documented and might be helpful!

**Comment by thisandagain** [comment]
`https://staging.scratch.mit.edu` is now running Node.js 4.3.2 LTS.

**Comment by liam4** [comment]
:tada:
