### ISSUE TITLE
in join flow, provide custom validation errors for the most common invalid character classes

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#3526]
(Related to https://github.com/LLK/scratch-www/issues/3524 , which calls for a more readable general username character validation message.)

There are several common types of invalid character that users might type in a username in Join Flow, which are invalid.

We should provide specific error messages that make clear what's wrong.

1. Spaces: we should have a message specific about spaces
1. Special characters (=, $, (, *, etc.): we should say you can't use these particular characters, or maybe say only letters?
1. Foreign characters: we should explain that only the English alphabet is allowed (this might be harder)

Any others?

**Comment by BryceLTaylor** [comment]
Tracking in #3524
