### ISSUE TITLE
Can't resolve 'scratch-gui' when call const GUI = require('scratch-gui');

### ISSUE THREAD

**Issue by huylh97** [LLK/scratch-www#3535]
![Capture](https://user-images.githubusercontent.com/28486635/68926053-28044700-07b7-11ea-92e0-31b6280974fb.PNG)
![Capture1](https://user-images.githubusercontent.com/28486635/68926054-28044700-07b7-11ea-8680-d6796bddf05b.PNG)
I have already -- npm install https://github.com/LLK/scratch-gui.git
But it erroe when I import scratch-gui to my App.js

**Comment by apple502j** [comment]
try `npm install scratch-gui`.

**Comment by HoangHuyLe** [comment]
It also error
![Capture](https://user-images.githubusercontent.com/28486635/68931008-34da6800-07c2-11ea-8e0d-ef7dbde0448b.PNG)
