### ISSUE TITLE
'Supporting Originizations' in credits overflows

### ISSUE THREAD

**Issue by Jonathan50** [LLK/scratch-www#354]
This seems to be fixed by adding the CSS rule `word-wrap: break-word`.

Screenshot:
![picture of bug](http://i.cubeupload.com/mnK0k6.png)

I'm on Debian GNU/Linux 7.0 "Jessie" with Iceweasel (rebranded Firefox) 38.6.0.
I don't get this issue with Safari 9.0.1 or Google Chrome on OS X.

**Comment by TheGrits** [comment]
I'm not getting it. My browser / operating system: ChromeOS 7647.73.0, Chrome 48.0.2564.92, Flash 20.0 (release 0)

**Comment by mewtaylor** [comment]
Confirmed this on FF 42.0 on OS X 10.11, so it seems that it might be a firefox-specific issue
