### ISSUE TITLE
Splash - Initial value of project count is arbitrary

### ISSUE THREAD

**Issue by TheGrits** [LLK/scratch-www#357]
https://github.com/LLK/scratch-www/issues/161#issuecomment-171460369

The least that could be done is update the number, that should be an easy edit.
(The current initial value is 10569070 to be exact)

**Comment by mewtaylor** [comment]
I think this might be covered under the scope of #161 – @thisandagain does covering this in the #161 enhancement make sense to you too?

**Comment by TheGrits** [comment]
Hmm, I guess that does make sense.

**Comment by thisandagain** [comment]
@mewtaylor Actually I kind of like splitting that meta-issue up. Let's keep this!

**Comment by mewtaylor** [comment]
:+1: SGTM thanks @thisandagain @TheGrits !
