### ISSUE TITLE
How to add project on the home page now is just blank? 

### ISSUE THREAD

**Issue by woshichuanqilz** [LLK/scratch-www#3571]
_Describe the problem. Please make sure you can reproduce the bug. It's also
helpful to include screenshots or animated gifs of the problem._

### Steps to Reproduce
Just follow the tutorial on the github. The website start correctly. But the main page is just blank, 

_Explain what someone needs to do in order to see what's described above. The 
more detailed and explicit the steps are the better._

### Operating System and Browser
OS: Manjaro 18
Browser: Chrome

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
You need to set up API server yourself. (the real one is closed-source)
