### ISSUE TITLE
Update GUI in Scratch forums

### ISSUE THREAD

**Issue by Nambaseking01** [LLK/scratch-www#3574]
Moved from here: https://github.com/LLK/scratch-gui/issues/5322

I was searching for other issues about this, but there aren't. I'm not particularly impatient about this feature, but since this is the GUI repo I thought I'll suggest it to calm some people down. The GUI in the Scratch forums is still in the 2.0 version, so maybe you could do more work on making it 3.0? It would really be nicer for a lot of Scratchers.

**Comment by benjiwheeler** [comment]
See https://github.com/LLK/scratchr2/issues/5274

**Comment by Nambaseking01** [comment]
@benjiwheeler That link is leading me to a 404 error, unless I'm mistaken.

**Comment by apple502j** [comment]
That repo is private. @Nambaseking01

**Comment by Nambaseking01** [comment]
@apple502j Oh, I see - thank you for mentioning that. Will close this.
