### ISSUE TITLE
Share button area not showing on some Windows machines

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#3612]
I have now seen on multiple people's Windows machines that the top of the Project Page that should show a Share button (for a new project) is not available. It happened again in a workshop where people brought their own machines. It looks like scrolling up should work on the project page but it won't scroll up to where the Share button would be. 

We made sure the browser was at Actual Size. 

It also wasn't showing up on See Inside. 

I will try emailing the two people at two different places where I saw this to try to find out the Windows OS, browser, and type of computer.

**Comment by ntlrsk** [comment]
I see from a comment in the forum that it may be an ad blocker.

**Comment by ntlrsk** [comment]
Also here on the forum it shows that solved it for someone so I'll close the issue: https://scratch.mit.edu/discuss/topic/293320/

**Comment by ntlrsk** [comment]
I heard back from the participant and they explained that once they confirmed their email they were able to access the Share button. It would be helpful to make this cause clearer for logged in Windows users who have not confirmed their address.

**Comment by apple502j** [comment]
(Windows totally unrelated)

**Comment by apple502j** [comment]
Duplicate of #2863
