### ISSUE TITLE
Remove Community Moderator Job Listing

### ISSUE THREAD

**Issue by dietbacon** [LLK/scratch-www#3616]
Please remove the link to "Community Moderator (Part-Time, Remote)" from the "Current Openings" section of the [Opportunities Page](https://www.scratchfoundation.org/opportunities/).

**Comment by apple502j** [comment]
Note that we can't help you; the foundation's website is closed-source.

**Comment by dietbacon** [comment]
The page has been updated to remove the job listing, closing the issue.
