### ISSUE TITLE
update Scratch Cards page to include new cards

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#362]
It would be great when possible to update the Scratch Cards page to include the thematic card sets: Dance, Name, and Hide-and-Seek (with others to come). 

http://scratch.mit.edu/dance/cards
http://scratch.mit.edu/name/cards
http://scratch.mit.edu/hide/cards

**Comment by mewtaylor** [comment]
@ntlrsk do you have the images that would appear for these (i.e. the thumbnail for the cards page)? I do not have them anywhere yet. Just wanted to know if you do before I attempt to do any cropping or anything.

**Comment by thisandagain** [comment]
@mewtaylor can this be closed?

**Comment by mewtaylor** [comment]
Yes – sorry thought this was closed by the PR. Thanks!
