### ISSUE TITLE
Banned users cannot see the Terms of Use or Privacy Policy

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#3698]
If you are banned, you cannot see Terms of Use or Privacy Policy, which may be a problem because violation of Terms of Use can ban users but then they can't review it.

**Comment by BoomerScratch** [comment]
Workaround: the user can sign out and then see the terms of use or privacy policy, so this glitch is no problem.

**Comment by benjiwheeler** [comment]
Not labeling this Help wanted because the fix may be complex. It might require making changes to how the site handles redirecting banned users.

**Comment by apple502j** [comment]
@benjiwheeler It should be as easy as modifying https://github.com/LLK/scratch-www/blob/develop/src/redux/session.js#L14 IIRC

**Comment by benjiwheeler** [comment]
@apple502j Thanks for clarifying! I'm marking it Help wanted.
