### ISSUE TITLE
2020 Conference: proposal deadline is past

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#3707]
The deadline for proposals for [Scratch@MIT 2020](https://scratch.mit.edu/conference/2020) was Feb 3. It is now past then. However, the link to submit proposals is still present (though the form is closed):
![image](https://user-images.githubusercontent.com/28599280/75134652-e2daa400-5719-11ea-92c2-8ddd4f02958e.png)
The link should be removed and the text updated to say that proposals are no longer being accepted.

**Comment by benjiwheeler** [comment]
@Kenny2github Thanks for pointing this out!

**Comment by ntlrsk** [comment]
Thanks @Kenny2github! This is addressed by issue: https://github.com/LLK/scratch-www/issues/3708
