### ISSUE TITLE
Update Scratch Conference 2020 page

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#3708]
The Scratch Conference page needs to be updated to add a link to the Registration site, add the hotels, remove the call for proposals, and other text updates. The updated text and links are all on the Google doc used for the original conference page, called "Scratch Conference 2020 Announcement".

**Comment by ntlrsk** [comment]
Here's the updated text and links [Scratch Conference 2020 Announcement.pdf](https://github.com/LLK/scratch-www/files/4253358/Scratch.Conference.2020.Announcement.pdf)

**Comment by ntlrsk** [comment]
@rschamp @kchadha We just decided to delay conference registration one month to gather more info about how coronavirus may impact travel and the conference. So we need a change to the wording on the button and in the registration text to follow.

**Comment by ntlrsk** [comment]
NEW Changes:

1) Replace "Registration will open on March 3." with the following text:

We have delayed the opening of registration until April 3. We’re excited to gather together as a community in July, but we are closely monitoring the situation around the Coronavirus (COVID-19) to determine how it might impact our plans. We will provide more information as it becomes available.

2) Change main button text (instead of "Register for the conference") put: 
**Go to registration page**

**Comment by rschamp** [comment]
@ntlrsk the PR is updated with those changes

**Comment by rschamp** [comment]
Fixed in #3723

**Comment by ntlrsk** [comment]
@mresmres asked to add line break and space to make the announcement clearer: "We have delayed the opening of registration until April 3...."
