### ISSUE TITLE
Some images not shown on /download/ with trailing slash

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#3748]
Some images on download page are not shown. It seems like image URL is wrong, resulting in 403. Note that this **does not** happen for extension pages.

### Steps to Reproduce
1. Go to https://scratch.mit.edu/download/
2. See some images (requirements, store badge) missing

### Operating System and Browser
Windows 10 Firefox 74

**Comment by BoomerScratch** [comment]
Hmm... same to me. Weird. The images showed before but no longer anymore? :/

**Comment by BryceLTaylor** [comment]
The links are only broken if you go to that page with a trailing slash in the url.  If you delete the slash the images load normally.  Note: the link in the footer takes you to the page without a trailing slash and the images load normally.
