### ISSUE TITLE
Pages with the Scratch 3.0 Theme are blank if JavaScript is disabled

### ISSUE THREAD

**Issue by Accio1** [LLK/scratch-www#3759]
If you attempt to view any pages which have the Scratch 3.0 theme (the home page, project page, etc.) while JavaScript is disabled, the page is blank without any explanation. There should be some kind of message which informs the user that they need to enable JavaScript to view the page.

### Steps to Reproduce

1. Block JavaScript for scratch.mit.edu in your browser settings
2. Visit a page which has the 3.0 theme (homepage, project page, project editor, etc.)

### Operating System and Browser

My browser / operating system: ChromeOS 12739.94.0, Chrome 80.0.3987.137, No Flash version detected

**Comment by Accio1** [comment]
Perhaps you could use the `<noscript>` tags to display a message.

eg.
`<noscript><h1>JavaScript is required to display this page, please enable JavaScript in order to continue.</h1></noscript>`

**Comment by JeffaloBob** [comment]
does this really need to happen, its pretty much expected that if you don't have JS you don't have most of the web.

**Comment by mxmou** [comment]
> does this really need to happen, its pretty much expected that if you don't have JS you don't have most of the web.

It is, but it still isn't expected that pages will be empty.

**Comment by benjiwheeler** [comment]
Contributors, if you wanted to take a crack at the logic to show a message of some sort instead of a blank page, we could use that and then try to improve the design on top of it.

**Comment by GrahamSH-LLK** [comment]
@benjiwheeler To go along with what Accio1 said, if we added a <noscript><h1>JavaScript is required to display this page, please enable JavaScript in order to continue.</h1></noscript> to the <head> element and styled it, we could have a good looking, working system. We could even try to add instructions, by linking to a website like https://www.enablejavascript.io

**Comment by Accio1** [comment]
@GrahamSH-LLK I think that the problem isn't what to display, but rather how to display it. This would somehow have to be added to every page that has the Scratch 3.0 theme, and the pages are displayed using React (Which is a JavaScript library), so I'm not sure how we would be able to display it on each page.
