### ISSUE TITLE
Input field hidden when soft keyboard open.

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#3773]
When adding a classroom on a tablet with the soft keyboard open, the field that you're typing into is not visible
![Screenshot_2020-03-26-11-05-08](https://user-images.githubusercontent.com/399209/77691669-b8c80c00-6f7b-11ea-8943-0c97c559cc6f.png)

### Steps to Reproduce

Try logging in as a teacher on an Android tablet (in this case a 7-inch), add a classroom. You can't see the name field as you're typing.

### Operating System and Browser

Galaxy Tab A (2016) 
SM-T280
Android 5.1.1
Chrome 80.0.3987.149

**Comment by apple502j** [comment]
This looks like an issue on scratchr2 side.

**Comment by benjiwheeler** [comment]
@apple502j is correct -- moved to https://github.com/LLK/scratchr2/issues/5693
