### ISSUE TITLE
Have separate messages for following people and studios

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#3780]
We have only one string defined for a user following another user or studio.
https://github.com/LLK/scratch-www/blob/7f9ffada5fe1167721669b9bc3e2d5d83cc40692/src/views/splash/l10n.json#L16

In some languages you would not use the same translation for both. _The initial report came in for Korean, but it's quite possible for other languages._

In addition to adding two strings to the `l10n` file, we'd need to refactor [FollowMessage](https://github.com/LLK/scratch-www/blob/develop/src/views/splash/activity-rows/follow.jsx), probably into two separate components `FollowStudio` and `FollowUser`.

### Steps to Reproduce

Have an account you're following follow another user and a studio. The same message will be used for both in all languages.

**Comment by apple502j** [comment]
working on it!
