### ISSUE TITLE
Update Scratch conference page to announce one year delay

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#3781]
We need the text updated on the Scratch Conference page http://scratch.mit.edu/conference to explain that the conference is delayed one year until July 2021. I will post updated text below, but am posting this issue now to put it on the radar for scheduling. 

(We will also be sending out an email announcement and updating the Eventbrite page this week April 2 or 3.)

**Comment by ntlrsk** [comment]
Here is the text - I used the Suggestion feature for all the changes to be made: 
https://docs.google.com/document/d/1WtMW8jkN6A8ROBqMGWxiD_-D1x1lkEaB0GvCgS1w7J0/edit

Please let me know if you have any questions. Thanks!

**Comment by Accio1** [comment]
> Here is the text - I used the Suggestion feature for all the changes to be made:
> https://docs.google.com/document/d/1WtMW8jkN6A8ROBqMGWxiD_-D1x1lkEaB0GvCgS1w7J0/edit
> 
> Please let me know if you have any questions. Thanks!

I can't see anything which has been written with the suggestions feature.

**Comment by ntlrsk** [comment]
@Accio1 Thanks for noticing this. I accepted the suggestions so now they should be visible.If it's possible to make these changes that would be great.

**Comment by Accio1** [comment]
> @Accio1 Thanks for noticing this. I accepted the suggestions so now they should be visible.If it's possible to make these changes that would be great.

I just made a pull request which should fix this. Hopefully it can be merged soon!
