### ISSUE TITLE
Credits page is no longer in Alphabetical Order

### ISSUE THREAD

**Issue by Accio1** [LLK/scratch-www#3813]
Since #3805 removed the last names from the credits page, the order that Scratch Team members are listed on the page doesn't make sense. They used to be ordered alphabetically by last name, but now since the last names are removed, they appear to be in a random order.

They should be reordered to be alphabetical by first name so that the page makes more sense.

### Steps to Reproduce

1. Go to the [credits page](https://scratch.mit.edu/credits)
2. Observe that the Scratch Team members appear to be in a random order.

### Operating System and Browser

This would appear on any device and browser

**Comment by Accio1** [comment]
I would be willing to help fix this if the Scratch Team agrees that it needs to be fixed.

**Comment by Accio1** [comment]
@BryceLTaylor is this something that the Scratch Team would like fixed?

**Comment by BryceLTaylor** [comment]
@Accio1 We would love it if you fixed it.

**Comment by Accio1** [comment]
> @Accio1 We would love it if you fixed it.

Great! I'll be able to start after #3830 is merged, because that affects the credits page as well, and starting before that was merged could cause conflicts (I think).

**Comment by benjiwheeler** [comment]
@Accio1 OK, 3830 is merged! Please rebase on it and update this PR when you get a chance, and I'll review it.

**Comment by Accio1** [comment]
> @Accio1 OK, 3830 is merged! When you submit a PR for this, please tag me, and I'll review it.

Ok, I've started working on it. I just had one question. What should I do if more than one person has the same name. (eg. there are two Chris and two Mark)? Should the person with their username first in the alphabet come first?

**Comment by benjiwheeler** [comment]
Good question. Sure, then alphabetize by username, that sounds good!
