### ISSUE TITLE
Homepage bottom text is not translated

### ISSUE THREAD

**Issue by qucchia** [LLK/scratch-www#3814]
The text at the bottom of the homepage is not translated to other languages.
![Screenshot 2020-04-18 at 12 47 34](https://user-images.githubusercontent.com/45072410/79635726-ee26da80-8172-11ea-8a36-17279f5fb3fd.png)

### Steps to Reproduce

Switch to any language other than English, go to https://scratch.mit.edu/ and scroll to the very bottom.

### Operating System and Browser
N/A

**Comment by apple502j** [comment]
nab: can't repro for Japanese, it is just "translation missing"
![image](https://user-images.githubusercontent.com/33279053/79638098-be9dbf80-81be-11ea-85dd-3d0904d21eaa.png)

**Comment by chrisgarrity** [comment]
It's a relatively new string and just hasn't been translated to all languages. Closing.
