### ISSUE TITLE
Some scratch headers have the 2.0 design.

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-www#3815]
Some pages of the scratch website have the 2.0 design of the top bar, pages are listed below:
· Mystuff
· Studios
· Profile pages

### Steps to Reproduce

Go to one of the pages listed above on scratch.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
Because they're not migrated!

not a bug

**Comment by Explosion-Scratch** [comment]
Sorry, it seemed like an "issue" though =) So I only post bugs in the
issues section? (I'm really new to github, sorry)

On Sunday, April 19, 2020, apple502j <notifications@github.com> wrote:
> Because they're not migrated!
>
> not a bug
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/EyeeEONRdsC3Rnhdb9GaU6Yhp19bLCJfUr0WDafi6OmSjV4-XDXY1_4M_OW9GspPkCVOv6Te5Ocp5E9ppSZ-O5SeUwEF0sg4GlXds1NN8jspd0swki5Dx6u3GOyZCvqOlSRWtVIedEzQNvThbbNuHTHxuvKZhhT61iKCnNKyV8xWd-5u28bXFwg3_fRHBmV7BTPdG9AKa6bR5895HXi5uQy1nqZ2709n92ZvY9UH_g=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3X3YKBEULLJPKE2ZVTRNL6CHA5CNFSM4MLYNVXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOES4YOMQ.gif>

**Comment by benjiwheeler** [comment]
@Explosion-Scratch this is totally an "issue"! However, we happen to know about it and we have a long-term plan (albeit, a plan that's moving slowly :) ) to improve it. You can file issues here even if they're not bugs, but this one is basically a sub-issue of a much larger issue: our plan to migrate from the Scratch 2.0 website platform (which uses Django) to the Scratch 3.0 website platform (which uses Node).

I'm not sure if there's a good place to point you to where you could read more about what our overall, long-term plans are. It's hard to know, from the outside, what's an issue we need to be notified about, vs an issue we already know about. Keep reading our issues, and submitting issues when something doesn't look right, and you'll understand more over time!

Thanks for helping out,
-Ben
