### ISSUE TITLE
Please add Kait to the credits page

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#3820]
Please add "Kait" to the [Credits Page](https://scratch.mit.edu/credits)

Username: [MunchtheCat](https://scratch.mit.edu/users/MunchtheCat/)

**Comment by Accio1** [comment]
@christanbalch I can do this if it is help wanted.

**Comment by R434660** [comment]
I could do that, @christanbalch .

**Comment by R4356th** [comment]
@christanbalch, you need to tell us the UserId.

**Comment by Ghassan19** [comment]
Can I be in the scratch team
