### ISSUE TITLE
About building

### ISSUE THREAD

**Issue by liudandandear** [LLK/scratch-www#3828]
Hello, I want to build a scratch web, so I've run the clone scratch-www project, but because there is no back-end API, such as scratch-apiI, my website is a semi-finished product. I want to ask if there is a scratch-api, or the scratch www back-end API project? Thank you for your reply.

**Comment by apple502j** [comment]
It's closed source: https://scratch.mit.edu/discuss/post/2701986/
(note: thisandagain left the ST last year)
