### ISSUE TITLE
What's Happening area doesn't show studio follows correctly

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#3831]
When someone you follow follows a studio it should show their username in the message that appears in the What's Happening section of the home page.  It doesn't show up for studio follows

![Screen Shot 2020-04-27 at 11 25 10 AM](https://user-images.githubusercontent.com/1088291/80390510-82332900-887a-11ea-9b17-69aad48559c1.png)

Also, when you click on the studio name (which does appear) it takes you to a 404 page.  That's because the href in for the studio link is "/studios/undefined".  Similarly, the user href is "/users/undefined".  
![Screen Shot 2020-04-27 at 11 10 56 AM](https://user-images.githubusercontent.com/1088291/80390611-a8f15f80-887a-11ea-99a6-77d58d07c549.png)

I looked at the network traffic and the response for "activity" was:

`[{"id":9263955,"datetime_created":"2020-04-27T15:15:17.000Z","actor_username":"btester2","actor_id":31851500,"gallery_id":26466882,"title":"Character Remix!", "type":"followstudio"}, ... , "actor_username":"MrOskin","actor_id":20611229,"gallery_id":25750734,"title":"6K - Connect the Dots","type":"followstudio"}]`

So it appears to be getting the 

### Steps to Reproduce

Make sure you are following an alt account
Using the alt account, follow a studio
Sign back in with your main account
Note: the What's Happening section shows your alt account following a studio, but it doesn't show the username
Click the link for the studio in the What's Happening section
Note: it takes you to a 404 page (Whoops!)

### Operating System and Browser

Mac Chrome

**Comment by apple502j** [comment]
I made this bug I'll fix it soon #3829 @BryceLTaylor

**Comment by apple502j** [comment]
@chrisgarrity should be closed
