### ISSUE TITLE
Changed usernames can be re-taken by a new account.

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-www#3833]
If  scratcher's userbame is changed by the Scratch Team, the old username can be taken by another account, seeming to impersonate the old username. This should be a simple API fix.

**Comment by JeffaloBob** [comment]
i don't think this is an issue because this barely ever happens, and when it does. user usually takes that other name as a 'redirect' back to their new name.

**Comment by Explosion-Scratch** [comment]
Actually the only two people I know who's usernames were changed were impersonated by their original account name. This should be an easy fix, also, wjy not redirect (like a real redirect) the old username to the new one?

**Comment by JeffaloBob** [comment]
i'm sure the scratch team could just register the usernames themselves though, making an api change would make people feel like changing usernames is a feature the scratch team offers regularly

**Comment by Explosion-Scratch** [comment]
I don't see any point in NOT doing it and I don't think many people will even notice an API change like that.

**Comment by benjiwheeler** [comment]
This is a complex problem that is actually not simple to change. It is also a backend issue. So I'm closing this issue, and opening an issue in our private repo `scratch-api`.

**Comment by Explosion-Scratch** [comment]
Thanks.

>
