### ISSUE TITLE
Move Andrew and Abisola to past contributors

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#3848]
On the credits page, we should move Andrew Sliwinski and Abisola Okuk to past contributors.

Follow-up to https://github.com/LLK/scratch-www/pull/3836

**Comment by Accio1** [comment]
I can do this once #3836 is merged.

**Comment by apple502j** [comment]
@benjiwheeler Should [ipzy](https://scratch.mit.edu/users/ipzy/) be moved as well?

**Comment by benjiwheeler** [comment]
@apple502j I don't see ipzy there -- where do you see them?

**Comment by apple502j** [comment]
oops - looks like already removed
