### ISSUE TITLE
Setting future month does not raise validation error in Join Flow

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#3852]
You can set the birth year and month to December 2020.

### Steps to Reproduce
1. Go to Join page
2. Enter username and password
3. Choose country
4. Choose "December 2020"
5. Click "Next"
6. No error shown

### Operating System and Browser
Firefox 75, Windows 10

**Comment by BryceLTaylor** [comment]
There are some other places where this is too aggressive, so we should figure out when we want to show the error.

**Comment by benjiwheeler** [comment]
In the teacher/student join flow, it shows a validation error message as soon as you make a selection that's in the future. I agree that's too aggressive. 

Some possibilities to consider:
1. show an error if the user tries to advance to the next screen with a future date selected
2. enforce a minimum age, like 2 or 3 years old, and don't let user proceed until they choose a birth date that means they're older

That said, it's helpful to know for sure that the user didn't tell the truth when they signed up.

**Comment by benjiwheeler** [comment]
@BryceLTaylor I suggest this be considered low impact, not medium. No users will ever have their experience affected for the worse by this. It's true that it allows us to collect incorrect data, but only on users who have attempted to enter a false birthdate, and it's likely they would just choose a false birthdate anyway.

**Comment by benjiwheeler** [comment]
Spoke to @carljbowman about this. We agreed it would be appropriate to close this issue as "do not fix", because it's not clear that a fix would actually improve things. If someone submitted a PR to fix this, we would not be likely to give this the time to test and review it.
