### ISSUE TITLE
Cookies should be marked as Lax

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#3874]
On Firefox 76, a warning will show up when cookies are not marked as Secure when it should:
> Cookie "permissions" will be soon rejected because it has the "sameSite" attribute set to "none" or an invalid value, without the "secure" attribute.

In the future, "secure" will be necessary, so we should add it now. (adding "secure" just makes sure it's HTTPS - and Scratch is httpsified so no problem should occur)

**Comment by picklesrus** [comment]
fixed by #4219

**Comment by rschamp** [comment]
In order for linking into Scratch while appearing to be logged in and your language setting retained, we need the browser default behavior, `SameSite=Lax`.
