### ISSUE TITLE
Nav bar needs an initial state

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#395]
Currently, once the browser loads a page, that page then makes a request to the api to see if the user who's loading the page is logged in or not. While the page is waiting for the api to make a response, the nav defaults to its signed out state – it shows "Join Scratch", and "Sign in" components.

This is usually not noticeable, as often the api responds quickly with information about whether the user is logged in. However, this can still be confusing for users. It might briefly appear to them that they are logged out – prompting them to try and login – when in reality, the page is still trying to determine if they are or not.

We need to have the nav component display a "default" state – a design for before it knows whether or not the user is logged in.

**Comment by rschamp** [comment]
Elsewhere on the site, the "Join Scratch" and "Sign in" items don't appear until it knows the state.  I think we should mirror that behavior.
