### ISSUE TITLE
HelpWidget: "not useful" button too large, overlapping the content

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#3987]
On Japanese locale, "Not useful" button on help widget is too large and some contents are hidden under it. This is a Freshdesk side problem, but I'll write this here.

![image](https://user-images.githubusercontent.com/33279053/82038056-ee68b600-96dd-11ea-8a0b-5ce14c8caf1c.png)

**Comment by Explosion-Scratch** [comment]
How do I find this in scratch? Which page is it on?

**Comment by apple502j** [comment]
@Explosion-Scratch On Contact Us.

**Comment by chrisgarrity** [comment]
This is actually a bug in the Freshdesk widget. We just need to file a bug in their system.

**Comment by chrisgarrity** [comment]
@apple502j could you add what OS/browser you're using. The button overflows for me, but doesn't overlap content (MacOS/Chrome 81)

**Comment by benjiwheeler** [comment]
I suggest we consider this as something we will never take action on.

**Comment by chrisgarrity** [comment]
Received confirmation from Freshdesk that this is a bug on the help widget.

**Comment by Explosion-Scratch** [comment]
So this will likely never be fixed? Also would it be possible to workaround
this by resizing the text and/or the text box?
>
>

**Comment by apple502j** [comment]
@Explosion-Scratch Actually that is not Scratch code

**Comment by Explosion-Scratch** [comment]
@Apple502j I see, so this is basically unfixable by the ST?
>
>
