### ISSUE TITLE
When commenting ASCII characters, make a better comment block message.

### ISSUE THREAD

**Issue by BoomerScratch** [LLK/scratch-www#3991]
When you post a comment that includes ASCII characters, you get this:
![image](https://user-images.githubusercontent.com/60622217/82141938-0143cd80-9839-11ea-97cc-f024cdc89754.png)
This confuses people, so you need to make a better message, like this:
![image](https://user-images.githubusercontent.com/60622217/82142181-ca6eb700-983a-11ea-8119-9c8ef8fbf402.png)

**Comment by TheAwesome98-Real** [comment]
I think that's a good idea, and maybe also highlight characters or words that need to be removed?

**Comment by BoomerScratch** [comment]
> I think that's a good idea, and maybe also highlight characters or words that need to be removed?

Well, if so, then that would also will be nice when there is any bad language in the comment and links to unmoderated chat.

**Comment by Kenny2github** [comment]
Highlighting bad language has been suggested before and rejected (iirc) because it might be accidental bad language in which case highlighting what's wrong would teach new bad language...

**Comment by TheAwesome98-Real** [comment]
oh yeah, that is a good point...

once i was trying to comment a completely okay word, and the filter said there's a problem with my message, it'd be cool if you could type highlightBadLanguage(); in the console, or maybe introduce **** censoring, like ROBLOX. the **** censoring might be annoying, though.
 

Sent from https://mail.com/ web client.

 
 

Sent: Monday, May 18, 2020 at 3:33 AM

**Comment by Explosion-Scratch** [comment]
Maybe instead of highlighting what it thinks is a bad word it should just replace it with an asterisk? Note that this would apply to ajy number of letters for example: "bad" ---> "*" "word" ---> "*"

**Comment by TheAwesome98-Real** [comment]
say i said "you're a poo" and poo is the bad word. we could do "you're a ***" but say that was an actual bad word, I guess they'd still learn a new bad word.

**Comment by R4356th** [comment]
@TheAwesome98-Real and @Explosion-Scratch, both of your ideas have a great possibility of teaching young kids bad words, as mentioned by @Kenny2github.

**Comment by Explosion-Scratch** [comment]
@R4356th My idea will replace it with ONE asterisk, therefore not highlighting WHAT the thought bad word was and not revealing the number of letters of the thought bad word.

**Comment by R4356th** [comment]
> @R4356th My idea will replace it with ONE asterisk, therefore not highlighting WHAT the thought bad word was and not revealing the number of letters of the thought bad word.

I do not get how that would solve the problem. When you are commenting, you know what you wrote and where you wrote it; and someone might be curious to know what that its bad meaning is.

**Comment by BryceLTaylor** [comment]
The current behavior is by design.
