### ISSUE TITLE
Love Count Gets Shown In Words Instead of Numbers

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#3997]
I noticed that in one project the love count was showing in words instead of numbers.
![scree](https://user-images.githubusercontent.com/61620631/82334916-6f8bba00-9a0a-11ea-991b-de0b828f9eba.png)
![scree3](https://user-images.githubusercontent.com/61620631/82335216-da3cf580-9a0a-11ea-9f78-9c9fb72080da.png)

### Steps to Reproduce

Go to https://scratch.mit.edu/projects/396212882/

### Operating System and Browser

Windows 10 Pro, Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by apple502j** [comment]
cannot repro on Firefox 76.0.1, Windows 10, locale ja-JP

**Comment by R4356th** [comment]
In that same project page, my message count showed 0 (practically because it was showing 0) instead of 1.

**Comment by JeffaloBob** [comment]
perhaps this could be google translate in chrome doing something?

**Comment by WorldLanguages** [comment]
Your browser triggered auto translation because the notes of the project are in Spanish

**Comment by R4356th** [comment]
> Your browser triggered auto translation because the notes of the project are in Spanish

Uh, right! This is Google Translate bug then.

**Comment by adroitwhiz** [comment]
There could still potentially be [a way for Scratch to fix this](https://stackoverflow.com/questions/33436115/how-to-disable-chrome-translation-bar-on-my-website).

**Comment by R4356th** [comment]
> There could still potentially be [a way for Scratch to fix this](https://stackoverflow.com/questions/33436115/how-to-disable-chrome-translation-bar-on-my-website).

Right but this should not be reopened, I think.
