### ISSUE TITLE
Scratch Team Member noncanonical's name  is not on the Credits page

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4006]
New Scratch Team member noncanonical's name is not on the Credits page. They probably joined the ST two months ago.

### Steps to Reproduce

Go to the Credits page.

### Operating System and Browser

Windows 10 Pro, Chrome 81.0.4044.138 (Official Build) (64-bit)
Windows 10 Pro, Chrome 83.0.4103.61 (Official Build) (64-bit)
Android 7, Chrome 81.0.4044.138 (Official Build) (64-bit)

**Comment by Kenny2github** [comment]
Please specify: which Scratch Team member? What even is a "noncanonical" name? What do you expect to see, and what do you actually see?

**Comment by Accio1** [comment]
> What even is a "noncanonical" name?
That is the username of the missing member. Their profile is [here](https://scratch.mit.edu/users/noncanonical/)

**Comment by R4356th** [comment]
@Kenny2github, all of the questions are answered in the issue. As @Accio1 has said, "noncanonical" is the name of the Scratch Team member whose name is not on the Credits page and I do not know their real name. I expect to see their name on the Credits page.

**Comment by Kenny2github** [comment]
OH their username is literally "noncanonical" lmao

**Comment by BoomerScratch** [comment]
We need noncanonical's first name before we can put it on the credits page...

**Comment by R4356th** [comment]
> We need noncanonical's first name before we can put it on the credits page...

I know.

**Comment by R4356th** [comment]
I am assuming basing on some other facts, their name is Emma.

**Comment by BoomerScratch** [comment]
> I am assuming basing on some other facts, their name is Emma.

I recommend asking a scratch team member, maybe you are wrong.

**Comment by R4356th** [comment]
> > I am assuming basing on some other facts, their name is Emma.
> 
> I recommend asking a scratch team member, maybe you are wrong.

There of course is a good possibility but I am not going to ask any ST member about this. Also, this not "help wanted" yet.

**Comment by GrahamSH-LLK** [comment]
Why not?

**Comment by R4356th** [comment]
> Why not?

The Credits page is not always up to date.

**Comment by GrahamSH-LLK** [comment]
That doesn't mean we shouldn't try to keep it up to date.
