### ISSUE TITLE
Cloud Chatroom takedown message has wrong link and code

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4014]
If your cloud chatroom gets taken down by the Scratch Team, you get a message (more like an alert) telling you about that and pointing to the forum announcement made by dietbacon on cloud chatrooms. However, it is a wrong link- "scratch.mit.edu/https://scratch.mit.edu/discuss/topic/357609/ " . The link should be "https://scratch.mit.edu/discuss/topic/357609/" instead. And along with that link, there is also another bug; it has got </a> tag with the link. I got that alert but it is removed from my account (taking it down was a mistake ST made), so I cannot provide any screenshot.

### Steps to Reproduce

N/A, ST and users whose chatroom got taken down only.

### Operating System and Browser

Windows 10 Pro, Chrome 81.0.4044.138 (Official Build) (64-bit)
Android 7, Chrome 81.0.4044.138 (Official Build) (64-bit)
Windows 10 Pro, Chrome 83.0.4044.138 (Official Build) (64-bit)

**Comment by R4356th** [comment]
It is important to fix this issue because Scratchers recieving that alert might get confused.

**Comment by apple502j** [comment]
This is probably not a bug in scratch-www because they use raw HTML provided from the API to render.

**Comment by R4356th** [comment]
@apple502j, do you mean it is a scratchr2 bug or what?

**Comment by BryceLTaylor** [comment]
This has been resolved.
