### ISSUE TITLE
Teachers must select a state while registering

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4019]
While registering, a teacher must select a state. This can be a problem because there are many countries which do not have any state.
![Screenshot_20200526-150657](https://user-images.githubusercontent.com/61620631/82882334-bf1a3a80-9f62-11ea-80ff-500ebe174d74.png)

### Steps to Reproduce

Complete all necessary steps to get to the address selection step, and do not select any state.

### Operating System and Browser

Android 6, Chrome 80 (64 bit) (Official build)

**Comment by BryceLTaylor** [comment]
This is not true.  If you select a country that does not have states (such as Vatican City) the state field is not present.

**Comment by R4356th** [comment]
Wait, I found the reason- you have got wrong information about Bangladesh. Scratch thinks there about 100 states in Bangladesh, while there are only 64 districts!

**Comment by R4356th** [comment]
Besides, some city names are wrong and some appear twice. I think you have inserted cities in the place of states for Bangladesh.

**Comment by R4356th** [comment]
This is still an issue because you have got wrong info.

**Comment by BryceLTaylor** [comment]
The state feature is behaving as expected, but it sounds like there is a real issue about the data being presented.  I would prefer to keep this issue closed. Please file a separate issue that is about the state information being incorrect for Bangladesh.

**Comment by R4356th** [comment]
> The state feature is behaving as expected, but it sounds like there is a real issue about the data being presented. I would prefer to keep this issue closed. Please file a separate issue that is about the state information being incorrect for Bangladesh.

Alright.
