### ISSUE TITLE
Text overflow in what's happening

### ISSUE THREAD

**Issue by BoomerScratch** [LLK/scratch-www#4023]
Related to #2853
When there is a long text in what's happening, the text does not break.
![image](https://user-images.githubusercontent.com/60622217/83017638-4c719380-a024-11ea-8555-2fbd9659a80a.png)

### Steps to Reproduce

1. On your alt account, follow your main.
2. Switch to your main.
3. Create and name a project:
————————————————————————————————————————————————————————————————————————————————————————————————————
4. Love and/or favorite it.
5. Switch to your alt account and go to the front page.

### Operating System and Browser

Windows NT 10.0, Chrome 83.0.4103.61

**Comment by R4356th** [comment]
Can't repro on any of Windows 10 Pro, Chrome 83.0.4103.61 (Official Build) (64-bit) or Android 7, Chrome 81.0.4044.138 (Official Build) (64-bit)

**Comment by BoomerScratch** [comment]
@R4356th have you really copy and pasted the text? Otherwise, it does not work.

**Comment by R4356th** [comment]
> @R4356th have you really copy and pasted the text? Otherwise, it does not work (probably).

@BoomerScratch, I am following you and had logged in when you loved and favourited that project.

**Comment by BoomerScratch** [comment]
@R4356th hmm...

**Comment by GrahamSH-LLK** [comment]
Happens on Google Chrome: Version 81.0.4044.141 (Official Build)  (64-bit)
Platform: 12871.102.0 (Official Build) stable-channel atlas
Channel: stable-channel
![image](https://user-images.githubusercontent.com/64214252/83043988-93a25900-a011-11ea-8a39-f0ac9a5c39b8.png)

**Comment by apple502j** [comment]
Related to #2853

**Comment by BoomerScratch** [comment]
@apple502j I already wrote that:
![image](https://user-images.githubusercontent.com/60622217/83050988-a470c000-a04d-11ea-86cd-f9d809007bd0.png)

**Comment by GrahamSH-LLK** [comment]
It also happens on the messages page. See image.
![image](https://user-images.githubusercontent.com/64214252/83065196-11c22800-a031-11ea-85f0-1e1b1460c3d1.png)

**Comment by GrahamSH-LLK** [comment]
Happens on chrome 85, Android 9, Pixelbook Go build

**Comment by BoomerScratch** [comment]
Working on a fix...

**Comment by GrahamSH-LLK** [comment]
Great! Did you see my comment about the "messages" page also?

**Comment by BoomerScratch** [comment]
@GrahamSH-LLK Yes. I think we should fix that later.

**Comment by BoomerScratch** [comment]
I have found a fix; with `word-break: break-word;`. Can I directly make a pull or do I have to wait?

**Comment by GrahamSH-LLK** [comment]
I think we have to wait until this is "help wanted", but we can ask a ST member.

**Comment by GrahamSH-LLK** [comment]
![image](https://user-images.githubusercontent.com/64214252/83658146-cdcea600-a58f-11ea-9710-3b1a63dd2c8f.png)
This is what happens with that. I think we might need a different solution.

**Comment by BoomerScratch** [comment]
@GrahamSH-LLK I don't think that's a problem.

**Comment by GrahamSH-LLK** [comment]
@BoomerScratch I don't like how long it ends up because the "news" section ends up with a lot of empty space. If you think it's fine, then we can use it.

**Comment by BoomerScratch** [comment]
@GrahamSH-LLK Well, if you use such long words with whitespaces, you get the same.

**Comment by apple502j** [comment]
@BoomerScratch `word-break: break-word` is deprecated, I guess `break-all` is better?

**Comment by BoomerScratch** [comment]
@apple502j Yeah.

**Comment by benjiwheeler** [comment]
@BoomerScratch please tag me when you submit the PR. And thanks!

`word-break: break-word` is deprecated, but it's still supported more widely than other options, so we would probably accept it. This is a tricky area, please be sure to test in a variety of browsers!

**Comment by BoomerScratch** [comment]
@benjiwheeler OK
@apple502j I have tested `break-all`, but it doesn't seem to fix the bug...
