### ISSUE TITLE
As a new scratcher, there are old images

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-www#4038]
When you are a new scratcher, you see this 
![image](https://user-images.githubusercontent.com/64214252/83068208-f86faa80-a035-11ea-8639-670a51bb2504.png) box. It shows 2.0 blocks. This would be an easy fix, as it is just an image. This could be confusing for new scratchers.  I suggest using this image because the new block for the drum is too long.
![image](https://user-images.githubusercontent.com/64214252/83075699-49859b80-a042-11ea-8eb1-98c4a5a4f431.png)

### Steps to Reproduce

Create a new account. 
See 2.0 blocks

### Operating System and Browser

N/A

**Comment by GrahamSH-LLK** [comment]
It would also have to be fixed here: 
![image](https://user-images.githubusercontent.com/64214252/83272774-97f97e00-a199-11ea-9ada-041ab431ef96.png), but this may be scratchr2. A mockup looks like this: 
![image](https://user-images.githubusercontent.com/64214252/83273103-16eeb680-a19a-11ea-9efa-2521a19b2d7a.png)

**Comment by Explosion-Scratch** [comment]
Yes, this could be confusing and should be changed. Should I suggest it on the scratch forums to aee what others think?

**Comment by GrahamSH-LLK** [comment]
I think we'll be fine, but you can if you want to.

**Comment by GrahamSH-LLK** [comment]
@Explosion-Scratch Do you know who is in charge of images like this?

**Comment by Explosion-Scratch** [comment]
@GrahamSH-LK I'm sorry, I'm not part of the ST nor do I help develop the site, I just comment and suggest stuff :)

**Comment by GrahamSH-LLK** [comment]
@Explosion-Scratch I know. I just have no idea who is in charge, and I was hoping you would know.

**Comment by Accio1** [comment]
It looks to me like replacing https://github.com/LLK/scratch-www/blob/develop/static/images/welcome-learn.png with a new image would solve this problem.

**Comment by GrahamSH-LLK** [comment]
@Accio1  Yes. That should work. Do _you_ have any idea who is in charge of this on the ST?

**Comment by GrahamSH-LLK** [comment]
@rschamp It says that you created this image, so do you have any thoughts on this?

**Comment by benjiwheeler** [comment]
I will bring this to the attention of the Scratch Team's Resources team.

**Comment by GrahamSH-LLK** [comment]
Great!

**Comment by benjiwheeler** [comment]
If someone wanted to submit an updated version of the image (you could just include it here, or make a PR), I could bring it to the Resources and Community teams; I can't guarantee they'd approve it (they might want to make their own), but they might take it as a stopgap!

**Comment by Accio1** [comment]
> If someone wanted to submit an updated version of the image (you could just include it here, or make a PR), I could bring it to the Resources and Community teams; I can't guarantee they'd approve it (they might want to make their own), but they might take it as a stopgap!

I can do that!

**Comment by Accio1** [comment]
I got a picture of the blocks above and removed the background from it so that it's a png. 
![Scratch Blocks](https://user-images.githubusercontent.com/48496940/85339509-5024f880-b4b2-11ea-83bd-ae44276b0eec.png)
