### ISSUE TITLE
I can't log in to my account!

### ISSUE THREAD

**Issue by BoomerScratch** [LLK/scratch-www#4040]
(note: should be moved to LLK/scratch-api)
I can't log in to my account! When I try to log in, nothing happens. When I look in the console, I see 503 errors. I'm not sure if this is temporary, but I'm scared.

### Steps to Reproduce

Log in to your Scratch account.

### Operating System and Browser

All

**Comment by R4356th** [comment]
Can repro on Windows 10 Pro, Chrome 83.0.4103.61 (Official Build) (64-bit) and with both a Scratcher and a New Scratcher account. I wish I did not sign out to test!

**Comment by R4356th** [comment]
Per the browser console there are errors in https://scratch.mit.edu/js/common.bundle.js file's line 6, 16, 22, 36 etc.

**Comment by BoomerScratch** [comment]
We should use contact us...

**Comment by Kenny2github** [comment]
503 means "Service Unavailable". Usually this indicates the server is down. This is temporary and should not be reported as a GH issue.

**Comment by R4356th** [comment]
Resolved! I can login now. @BoomerScratch, I think you should try again.

**Comment by BoomerScratch** [comment]
Yes, it works!
