### ISSUE TITLE
Credits page still has the old link to the Translators page on the Scratch Wiki

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4051]
The link to the Translators page (on the Scratch Wiki) on Credits page is old. It has the Scratch Wiki's old domain- wiki.scratch.mit.edu, which now redirects to en.scratch-wiki.info. This might not sound important enough but it can be confusing for New Scratchers.

### Steps to Reproduce

1. Go to the Credits page.
2. Scroll down to the Translators section.
3. Hold the hyperlink on translators and inspect it (without the Inspect tool, a part of Dev Tools)

### Operating System and Browser

N/A

**Comment by Accio1** [comment]
The link auto redirects to the new wiki, so I don't see how this is that big of a deal.

**Comment by R4356th** [comment]
> The link auto redirects to the new wiki, so I don't see how this is that big of a deal.

New Scratchers might get confused seeing en.scratch-wiki.info being used in most places and wiki.scratch.mit.edu in some other places. Not every Scratcher is old enough to understand redirects.

**Comment by R4356th** [comment]
I could fix this if it was labelled help wanted.

**Comment by benjiwheeler** [comment]
Thanks @R4356th, please submit a PR and tag me in the description!

**Comment by R4356th** [comment]
Alright, @benjiwheeler!
