### ISSUE TITLE
Languages not supported by Freshdesk can still be selected on Contact Us

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4052]
The new Contact Us page has been designed to make it more compatible with Freshdesk. Freshdesk does not support all the languages Scratch is currently available in. As such, many of the non-English languages should not be compatible with the new Contact Us page. But yet, non-English languages which Freshdesk does not support can still be chosen.

### Steps to Reproduce

1) Go to the Contact Us page
2) Select any language Freshdesk does not support

### Operating System and Browser

Windows 10 Pro, Chrome 83.0.4103.61 (Official Build) (64-bit), Android 6, Chrome 80 (64 bit) (Official build)

**Comment by apple502j** [comment]
Is it a problem though? The freshdesk will fallback to English anyway, and we should translate as many things as we can

**Comment by R4356th** [comment]
> Is it a problem though? The freshdesk will fallback to English anyway, and we should translate as many things as we can

Yes, I believe it is a problem because speakers of non-English languages will think it is a bug.

**Comment by chrisgarrity** [comment]
This is the way much of the site works. If a translation isn't available, it defaults to English. The fact that Freshdesk can't support all the languages that Scratch does is different, but not a reason to treat the page any differently.

**Comment by R4356th** [comment]
> This is the way much of the site works. If a translation isn't available, it defaults to English. The fact that Freshdesk can't support all the languages that Scratch does is different, but not a reason to treat the page any differently.

@chrisgarrity, I was actually suggesting you not to show the languages Freshdesk does not support. But alright, you can keep it closed.

**Comment by Accio1** [comment]
> > This is the way much of the site works. If a translation isn't available, it defaults to English. The fact that Freshdesk can't support all the languages that Scratch does is different, but not a reason to treat the page any differently.
> 
> @chrisgarrity, I was actually suggesting you not to show the languages Freshdesk does not support. But alright, you can keep it closed.

This doesn't make sense. Removing certain languages from the entire site, just because one page from a 3rd party service doesn't support those languages is a bad idea, and would reduce the accessibility of Scratch by people around the world.

**Comment by R4356th** [comment]
> This doesn't make sense. Removing certain languages from the entire site, just because one page from a 3rd party service doesn't support those languages is a bad idea, and would reduce the accessibility of Scratch by people around the world.
@Accio1, you got me wrong. What I suggested was actually to remove the languages from the Contact Us page only
 :P

**Comment by apple502j** [comment]
Why not? Contact Us page still can be *partially* translated.

**Comment by R4356th** [comment]
> Why not? Contact Us page still can be _partially_ translated.

You are yet another person to get me wrong. I meant removing the languages which cannot be translated.

**Comment by Accio1** [comment]
The footer with the language selection box is the same for each page. Therefore, it would probably be a lot of work to make it hide languages for certain pages. Even if this was implemented, it could possibly lead to even more confusion (eg. "Why does my language change to English when I go to the contact us page?", "The contact us page won't let me choose my language, even though the other pages on the site do", etc.). It seems like the work that it would take to implement this wouldn't be worth the small benefits and potential downsides that this suggestion would bring.

**Comment by apple502j** [comment]
@R4356th You are wrong - Contact Us can be partially translated for any language. Choose Welsh (Cymraeg) and you will see what I mean
