### ISSUE TITLE
Update credits page

### ISSUE THREAD

**Issue by dietbacon** [LLK/scratch-www#4060]
https://scratch.mit.edu/credits should have the following updates:

**Add to MIT Scratch Team section:**

Amielle (originalwow)
Craig (noncanonical)
Joshua (Class12321)
Ellen (SunnyDay4aBlueJay)

**Remove from MIT Scratch Team section:**

Elizabeth (rmiel)

**Add to Past Contributors:**

Elizabeth Foster

**Remove from Past Contributors:**

Ellen Daoust

## files to change

* src/views/credits/people.json
* src/views/credits/credits.jsx

**Comment by GrahamSH-LLK** [comment]
Great! I'll start working on this!

**Comment by benjiwheeler** [comment]
Thanks @GrahamSH-LLK! When you make the pull request, please @ me in the description or in a comment
