### ISSUE TITLE
Mentioning @welcomingcommittee in project comments links users/welcomingcommittee/ instead of the Welcoming Committee studio

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4072]
When you mention welcomingcommittee with @ in front in project comments, users/welcomingcommittee gets linked, instead of the Welcoming Committee studio.

### Steps to Reproduce

Mention welcomingcommittee with @ in front

### Operating System and Browser

Windows 10 Pro, Chrome 83.0.4103.61 (Official Build) (64-bit), Android 6, Chrome 80 (64 bit) (Official build)

**Comment by GrahamSH-LLK** [comment]
Isn't that the intended behavior? I can't seem to link to _any_ studios. It always links to a user.

**Comment by GrahamSH-LLK** [comment]
It links to a user even when there is no user.

**Comment by R4356th** [comment]
> It links to a user even when there is no user.

No, @GrahamSH-LLK! :smile: There used to be a user even a few days ago! It was probably banned because of the confusion. If you comment on scratchr2 pages like studios or user profiles, then it would take you to the Welcoming Committee studio.

**Comment by R4356th** [comment]
By the way, this is the proof that there used to be a user- https://api.scratch.mit.edu/users/welcomingcommittee .

**Comment by GrahamSH-LLK** [comment]
No, what I meant was that even with a different studio, one that doesn't
have a corresponding user, still links to the user. @(insert here) always
links to a user. I don't think there is a way to do that with a studio.

@R4356th

**Comment by Kenny2github** [comment]
@GrahamSH-LLK On profile comments (and any other scratchr2 comments), @welcomingcommittee actually links to a studio - it's a specific special-case feature that the ST implemented. This issue is valid - that feature needs to be reimplemented on scratch-www.

**Comment by R4356th** [comment]
@Kenny2github is right. Here is a SWC curator's quote about it- https://en.scratch-wiki.info/wiki/Talk:Welcoming_Committee#Should_me_mention_a_fun_fact.3F.

**Comment by GrahamSH-LLK** [comment]
@R4356th Sorry! I misunderstood what the issue was about! Now I see what the issue was about.
