### ISSUE TITLE
Poll for notification count updates using decaying time

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4079]
We currently poll for notification counts on a regular basis, in both www and scratchr2.

We should instead check for updates using decaying times -- 5 minutes, then 10 minutes, then 20 minutes, etc.

The endpoint accounts for about 1/3 of our api backend time.

**Comment by apple502j** [comment]
Is it problem for www? I think scratchr2 is slower

**Comment by picklesrus** [comment]
Fixed by https://github.com/LLK/scratch-www/pull/4293
