### ISSUE TITLE
Edge project-notes area scrolls horizontally when strings are long

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4089]
Follow-on to https://github.com/LLK/scratch-www/pull/2518

On Edge, on the “long instructions” project, there is a horizontal scrollbar:

![image](https://user-images.githubusercontent.com/3431616/84408528-43fb8a00-abda-11ea-9bd4-63e248ef708a.png)

@adroitwhiz suggests that we can fix this by adding overflow: auto to .project-notes (and then we might also be able to remove the deprecated `word-break: break-word;` from     `.project-description`'s CSS)

**Comment by BryceLTaylor** [comment]
Is this a problem with the new Edge?

**Comment by BoomerScratch** [comment]
@BryceLTaylor No, because the new Edge looks different.

**Comment by benjiwheeler** [comment]
Note that https://github.com/LLK/scratch-www/pull/4149 fixed this, but (knowingly) introduced a related bug, https://github.com/LLK/scratch-www/issues/4157
