### ISSUE TITLE
Fullscreen does not hide elements on macOS Safari or iPad

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#4098]
When the project is showed in fullscreen view, navigation bars and comment sections still appear. Green flag bar is completely covered with navigation bar, and the green flag overlay (the one that appears when project is first loaded) is bigger than the stage. Also, the stage top and bottom are cut. This does not happen when fullscreened inside the editor (by using the button next to Normal Stage Size); this only happens on WWW fullscreen, so this is probably scratch-www issue.

This is [reported by mmahhi](https://scratch.mit.edu/discuss/post/4117863/) with a picture describing the problem:
![image](https://user-images.githubusercontent.com/33279053/84529549-99d84b00-ad1c-11ea-9940-0e56110c7bf5.png)

UA: My browser / operating system: MacOS Macintosh X 10.15.4, Safari 13.1.1, No Flash version detected, they say it's the 6th generation of iPad

And there is also a [report from BlueBird927](https://scratch.mit.edu/discuss/post/4118705/):
> My browser / operating system: MacOS Macintosh X 10.12.6, Safari 12.1.2, No Flash version detected
> Every since last night (6/11/20), full screen doesn't work properly. Instead of giving me the normal full screen, it stays the same, but the screen part of the project page gets bigger.

I suspect #2518 caused this.

### Steps to Reproduce
On iPad, go to project page
Click fullscreen button on the project page

### Operating System and Browser
> My browser / operating system: MacOS Macintosh X 10.15.4, Safari 13.1.1, No Flash version detected, they say it's the 6th generation of iPad (by mmahhi)
> My browser / operating system: MacOS Macintosh X 10.12.6, Safari 12.1.2, No Flash version detected (by BlueBird927)

**Comment by apple502j** [comment]
More repros:
- [by AIUEO0987654321](https://scratch.mit.edu/discuss/post/4117299/): 
> "On iPadOS13.5.1, the project page gets glitched when I go to fullscreen"

- [by RoyalCHARLIE](https://scratch.mit.edu/discuss/post/4120548/): 
>My browser / operating system: MacOS Macintosh X 10.10.5, Safari 10.1.2, Flash 32.0 (release 0) 
>When I Click The Fullscreen Button It Give A Wider Screen.

- [by 144881USVD](https://scratch.mit.edu/discuss/post/4120868/)
> A fullscreen project has been crashed! Picture：https://cheny0y0.github.io/144881/IMG_4599.png

- [by cs004](https://scratch.mit.edu/discuss/post/4119454/)
> My browser / operating system: MacOS Macintosh X 10.13.6, Safari 13.1.1, Flash 32.0 (release 0)
> When I pressed the fullscreen button, the webpage glitched out. it opened up the normal fullscreen menu, and I could play the project normally, although the share tab at the top and comment tab at the bottom stayed there instead of disappearing. I tired sharing the project and trying to open up all the buttons at the top (create, explore, tutorials, etc.) but they did nothing. the only way to get rid of the screen was to close the page and reopen it by searching up scratch.mit.edu again. (refreshing the page does nothing) I actually found this from my mobile device, which is an Ipad pro (and had no problems on anything else since I bought it), although this glitch still happens of PC as well.

- [by MrNiceBrice](https://scratch.mit.edu/discuss/post/4116994/)
> I pressed full-screen, and the comments and the create/explore/ideas/about bar was showing up and blocking the screen when I was in full-screen! So, I restarted my iPad, and then went back, and it happened again! So I went to a different browser, and it still happened! I could not see the screen!

- [by mafiabigdude](https://scratch.mit.edu/discuss/post/4115960/)
> When ever i go into fullscreen the comments and top of my screen come with it blocking out the green flag, stop sign and exit fullscreen buttons

- [by aaaief](https://scratch.mit.edu/discuss/post/4117282/)
> I can’t use fullscreen

- [by Edgy_Punk](https://scratch.mit.edu/discuss/post/4116537/)
> My browser / operating system: MacOS Macintosh X 10.13.6, Safari 13.1.1, Flash 32.0 (release 0)
> Okay, so if I watch a project and go into fullscreen, it won't go into fullscreen. The display will just become a bit bigger and I can't stop the project. The only time it works properly is if I go INSIDE the project.

**Comment by apple502j** [comment]
Changed title - there are some repros from macOS Safari users

**Comment by BoomerScratch** [comment]
The same got reported again [by coolgijoe](https://scratch.mit.edu/discuss/topic/413747/):
> So…. I'm having an issue where I'm playing full screen on games, and when I hit full screen, the full screen is smaller, and i can scroll and see the comments there. That shouldn't happen. And for some reason, this doesn't happen in the editor.

**Comment by BoomerScratch** [comment]
[This topic](https://scratch.mit.edu/discuss/topic/414511/) by PokeLegend23 includes a helpful image:
![](https://cdn2.scratch.mit.edu/get_image/project/405156681_600x1200.png)

**Comment by MrNiceBrice** [comment]
This is what I was saying! It is soo unfair! Anyone know how to fix it?

**Comment by BoomerScratch** [comment]
@MrNiceBrice We do not have a solution yet... Also, this is not labelled "help wanted".

**Comment by apple502j** [comment]
@benjiwheeler This issue is flooding on BaG forum - and the only "suspicious" change is #2518 - can you try reverting it, checking it on scratch.ly, and if it worked, then hotfixing asap? Overflowing descriptions is better than completely useless fullscreen.

**Comment by benjiwheeler** [comment]
@apple502j Hm, taking a look. Agree that overflowing descriptions is better than completely useless fullscreen.
