### ISSUE TITLE
1.4 Page download page is out of date

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-www#4100]
On https://scratch.mit.edu/scratch_1.4/, it says The previous version of Scratch, version 1.4, is still available for download. It should be A previous version of Scratch, version 1.4, is still available for download. Also, it says "However, projects created in Scratch 2.0 cannot be opened in 1.4." This should say However, projects created in Scratch 2.0 or later cannot be opened in 1.4." Lastly, System requirements are outdated : it doesn't work on macOS 10.15 or later, but it does work on Windows 10."
Thanks to @R4356th and @mxmou for some of these problems! Also, "Try logging into Scratch website to make sure username and password are correct." should be Try logging into the Scratch website to make sure the username and password you tried are correct." This makes it more grammatically correct.

### Steps to Reproduce

Go to https://scratch.mit.edu/scratch_1.4/. See that it says "The previous version"

### Operating System and Browser
N/A

**Comment by R4356th** [comment]
Another bug in that same page, it says "However, projects created in Scratch 2.0 cannot be opened in 1.4.", instead of However, projects created in Scratch 3.0 cannot be opened in 1.4.

**Comment by BoomerScratch** [comment]
XD I just noticed that yesterday. Also, the thing that @R4356th said above needs to be fixed.

**Comment by mxmou** [comment]
> Another bug in that same page, it says "However, projects created in Scratch 2.0 cannot be opened in 1.4.", instead of However, projects created in Scratch 3.0 cannot be opened in 1.4.

I think it should be "However, projects created in Scratch 2.0 *or later* cannot be opened in 1.4.".

**Comment by mxmou** [comment]
System requirements are outdated too: it doesn't work on macOS 10.15 or later, but it does work on Windows 10.

**Comment by GrahamSH-LLK** [comment]
"Try logging into Scratch website to make sure username and password are correct." Should be Try logging into the Scratch website to make sure the username and password you tried are correct." This makes it more grammatically correct.

**Comment by Explosion-Scratch** [comment]
Yes, this is not very important but should be fixed since it could be confusing.

**Comment by GrahamSH-LLK** [comment]
I fixed it in my fork. Take a look here: https://github.com/GrahamSH-LLK/scratch-www/commit/1b58769224e5360f91f35a2ff25d0fcf8efbd820

**Comment by benjiwheeler** [comment]
@GrahamSH-LLK, sorry for the delay. Please do submit your PR!
