### ISSUE TITLE
New Accounts can still be created when signed in

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4110]
You can create a new account when you are signed in by visiting the Join Flow.

### Steps to Reproduce

1. Sign in to your Scratch account.
2. Go to Join Flow.
3. Complete all steps and create an account.

### Operating System and Browser

Windows 10 Pro, Firefox 77.0.1 (64-bit)

**Comment by GrahamSH-LLK** [comment]
Reproduced on chromeos. Hmm. Could this be intended behavior?

**Comment by BryceLTaylor** [comment]
This is working as intended
