### ISSUE TITLE
Redirect old 'donate' page 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#412]
This page:
https://scratch.mit.edu/info/donate/

Should redirect (forever) to:
https://secure.donationpay.org/scratchfoundation/

**Comment by thisandagain** [comment]
@mewtaylor Could you take this?

**Comment by mewtaylor** [comment]
@thisandagain – @rschamp has already implemented this in the cdn for staging. Reassigning to @rschamp until this is also in production on the cdn.

**Comment by thisandagain** [comment]
👍

**Comment by rschamp** [comment]
This is in place on Fastly.
