### ISSUE TITLE
touching mouse pointer works, even when mouse and sprite are off stage

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4124]
Demo: https://scratch.mit.edu/projects/406347413/

Thanks to user https://scratch.mit.edu/users/TimMcCool/ for finding this (and sorry about our plan to remove it!)

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-gui#5243

**Comment by BryceLTaylor** [comment]
Closing as duplicate
