### ISSUE TITLE
Update About & Credits page

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#413]
**About Page:**
https://scratch.mit.edu/about/

Update "Support and Funding" text to read: 

The Scratch project has received financial support from the National Science Foundation, Scratch Foundation, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, and MacArthur Foundation. See the Credits <https://scratch.mit.edu/info/credits/> page for more information. If you'd like to support Scratch, please see the Scratch Foundation donate <https://secure.donationpay.org/scratchfoundation/> page, or contact us at donate@scratch.mit.edu

**Credits Page:**

Update Scratch Team section:
* Chris Garrity (chrisg on Scratch)
* Julia Zimmerman (jwzimmer1990 on Scratch)

Supporting Organizations should read:

National Science Foundation, Scratch Foundation, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, MacArthur Foundation.

**Comment by mewtaylor** [comment]
Additionally, we need to add Julia and @chrisgarrity to the credits page.

**Comment by TheGrits** [comment]
@mewtaylor Is Julia a moderator or not?

**Comment by mewtaylor** [comment]
@TheGrits Julia is a Scratch Team member – both jwzimmer1990 (Julia) and chrisg (Chris) should go in the Scratch Team section. I'll update the issue description accordingly, thanks!

**Comment by TheGrits** [comment]
@mewtaylor Gotcha, I'll edit the PR this aft.

**Comment by mewtaylor** [comment]
Closed by @TheGrits in #414
