### ISSUE TITLE
Ask/answer entry widget disappears when toggling between project page and editor

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4141]
The ask/answer entry widget disappears when toggling between project page and editor:

![Jun-24-2020 18-59-27](https://user-images.githubusercontent.com/3431616/85635828-e4c35e00-b64c-11ea-86f5-ebadc4b7e2d1.gif)

Observed on Mac Chrome, but probably not browser-specific

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-vm#1855

**Comment by GrahamSH-LLK** [comment]
I think this isn't a www problem.

**Comment by BryceLTaylor** [comment]
Closing as duplicate
