### ISSUE TITLE
Update 404 Page

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-www#4159]
Scratch uses 2 404 pages right now. One matches the new design, and one is scratchr2.

### Steps to Reproduce

Go to scratch.mit.edu/projects, and see the 404 page. Then go to scratch.mit.edu/hwejfnsadhwqk and see the older version/ Since we already have a newer 404 page, we should update the other one to be on www. This shouldn't be very hard, as we already have the new one.
### Operating System and Browser
N/A

**Comment by apple502j** [comment]
This is hard. 404 is handled in scratchr2 because it's the fallback server - that 404 error is exception. We will not see 404 error until everything gets migrated.

**Comment by GrahamSH-LLK** [comment]
Ok, then.
