### ISSUE TITLE
What should we do about frameless?

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#4168]
To solve #4025 frameless.scss needs to be updated. However, frameless is no longer maintained. We can fix frameless.scss, or find another library that acts like frameless.

**Comment by rschamp** [comment]
@apple502j What about _frameless.scss needs to be updated to solve #4025?

**Comment by apple502j** [comment]
we need to bump `node-sass` - and it seems like there are some compatibility issues: see benjiwheeler's comment on #4025

I hope the changes are small, but this definitely needs lots of testing.

**Comment by rschamp** [comment]
I don't think this new issue is needed in addition to #4025, so I am going to close it. There's not much to `_frameless.scss` — it's not really a library so much as the file where we set up our layout variables.  To answer the original question, we will probably solve this by fixing `_frameless.scss`, not finding a library to replace it.  (That is until we change the way CSS works in scratch-www so it's more similar to the way we do it in scratch-gui.)
