### ISSUE TITLE
Header for mystuff is incorrect.

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-www#4183]
_Describe the problem. Please make sure you can reproduThe header for the mystuff page is "Scratch, Imagine, Program, Share" Wouldn't "Mystuff- Scratch, Imagine, Program, Share" be better?

**Comment by apple502j** [comment]
This is scratchr2 issue.

**Comment by BoomerScratch** [comment]
As said above, this is a Scratchr2 issue. The pages with the old navbar are Scratchr2. This is the old navbar:
![insert image alt text here](https://en.scratch-wiki.info/w/images/archive/20171005194343%21Oldnavigationbar.PNG)
Be sure to report bugs with pages that have the Scratch 3 navbar! 😉
The Scratch 3 navbar is:
![insert image alt text here](https://en.scratch-wiki.info/w/images/archive/20190510160227%21ScratchHeader.PNG)

**Comment by Explosion-Scratch** [comment]
@BoomerScratch and @Apple502j, Where am I supposed to report scratchr2 bugs then?

**Comment by apple502j** [comment]
@Explosion-Scratch Bugs and Glitches.

**Comment by Explosion-Scratch** [comment]
@Apple502j Okay! :) Thanks!
