### ISSUE TITLE
WWW pages take too long to load

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4186]
WWW pages take too long to load compared to scratchr2 pages and other websites. While it takes about two seconds to load for scratchr2 pages, it takes about a minute and fifteen seconds for www pages to load. This causes the project pages to show messages inside of the code instead of the alt text for big projects. One might argue that it is my own network problem but it is not because everything still loads fast when these pages do not load.

### Steps to Reproduce

Visit any WWW page (for example, homepage, messages page etc) and use a stopwatch to measure the time it takes to load.

### Operating System and Browser

Windows 10, Chrome 84, Firefox latest version
Android 7, Chrome 84

**Comment by R4356th** [comment]
Adding to that, project pages sometimes take about two minutes to load.

**Comment by apple502j** [comment]
This is probably because scratchr2 is rendered server-side and scratch-www is rendered client-side. For me personally some scratchr2 pages take very long to load.

**Comment by R4356th** [comment]
>  For me personally some scratchr2 pages take very long to load.

For example? I never experience anything like that.

**Comment by GrahamSH-LLK** [comment]
Both messages and mystuff took 1.61 seconds. (I have really good internet)

**Comment by R4356th** [comment]
> Both messages and mystuff took 1.61 seconds. (I have really good internet)

For Mystuff, it took me only five seconds. But this issue remains valid as other webpages still load way faster than WWW pages.

**Comment by BryceLTaylor** [comment]
@R4356th What are the file sizes of the different pages that you are loading?  What is the time that it takes for them to load?

**Comment by R4356th** [comment]
@BryceLTaylor, I have answered the second question in the original comment. As for the first one, I am confused with what do you mean by "file sizes of the different pages that you are loading". Do you mean the sb3 files for projects or the HTML, CSS files that are downloaded when you save the webpage with your browser?

**Comment by BryceLTaylor** [comment]
The Scratch Team continuously monitors and works on site performance as specific issues come up.
