### ISSUE TITLE
Community Blocks Interviews page is still accessible 

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4187]
The Community Blocks Interviews page is still accessible and present in this repository even though that is an old and inactive project.

### Steps to Reproduce

Go to https://scratch.mit.edu/info/communityblocks-interviews.

### Operating System and Browser

N/A

**Comment by R4356th** [comment]
I could delete files from this repo.

**Comment by R4356th** [comment]
The information on that page is also outdated.

**Comment by benjiwheeler** [comment]
@R4356th Thanks for pointing this out, please feel free to fix!

**Comment by apple502j** [comment]
@benjiwheeler is it still "needs discussion"?

**Comment by Naleksuh** [comment]
Why is this a problem? I don't see why this was an issue

**Comment by R4356th** [comment]
Did you even read anything in the issue?

**Comment by Naleksuh** [comment]
> 
> 
> Did you even read anything in the issue?

Now this is a very conclusive answer to the question, no loose ends!

**Comment by R4356th** [comment]
> > Did you even read anything in the issue?
> 
> Now this is a very conclusive answer to the question, no loose ends!

???

**Comment by benjiwheeler** [comment]
@Naleksuh, the description for this issue is clear about what the problem is. It's not a very bad problem, but it's something we should fix.

@apple502j I'll follow up to find out if it's still "needs discussion"...

**Comment by Naleksuh** [comment]
Personally I would prefer keeping it up for legacy purposes. There are a
ton of other pages that arent in use anymore (most of which are in
scratchr2). I guess what I want to say is that the issue does not explain
why this page being up is problematic

**Comment by R4356th** [comment]
> Personally I would prefer keeping it up for legacy purposes. There are a ton of other pages that arent in use anymore (most of which are in scratchr2). I guess what I want to say is that the issue does not explain why this page being up is problematic

This page is available on archive.org.
