### ISSUE TITLE
The About page says "Tips Page" instead of Ideas page

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4188]
The About page calls the Ideas page "Tips Page", which is not the real page name. 

### Steps to Reproduce

Go to https://scratch.mit.edu/about.

### Operating System and Browser 

N/A

**Comment by R4356th** [comment]
I have fixed this in my fork!

**Comment by R4356th** [comment]
@benjiwheeler, interested in labelling this as help wanted?

**Comment by benjiwheeler** [comment]
@R4356th Thanks for noticing! Please submit your PR!
