### ISSUE TITLE
China server trouble

### ISSUE THREAD

**Issue by MapMaths** [LLK/scratch-www#4191]
(In China server) I can't get into my user page and the discussion. It always say:"server troubles" So do my friends.

### Steps to Reproduce

homepage:
![image](https://user-images.githubusercontent.com/62785981/87417845-51ee6180-c603-11ea-829d-dd741521b9de.png)
contect us:
![image](https://user-images.githubusercontent.com/62785981/87417911-6b8fa900-c603-11ea-840e-f2be810cc927.png)
others:
![image](https://user-images.githubusercontent.com/62785981/87417953-7ea27900-c603-11ea-9b5f-83e68114f820.png)

### Operating System and Browser

Windows 10, 360 se, Chrome, Edge

**Comment by ljy-002** [comment]
I also have this problem

**Comment by MapMaths** [comment]
Mine is Okay now, but the cookies missed......

**Comment by MapMaths** [comment]
The trouble seems fixed, so let me close it
