### ISSUE TITLE
trouble.html and maintenance.html should be updated

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4194]
The static HTML files have unnecessary code such as style language type declaration and p tag. These do nothing but make the files trouble.html and maintenance.html bigger and look bad. They also use HTML4 and migrating to HTML5 will not be a big deal. 

### Steps to Reproduce 

Go to maintenance.html and trouble.html. 

### Operating System and Browser

N/A

**Comment by R4356th** [comment]
I am working on a fix, by the way.

**Comment by GrahamSH-LLK** [comment]
Where are the files?

**Comment by GrahamSH-LLK** [comment]
Oh wait, i found them. These look like scratchr2 files.

**Comment by R4356th** [comment]
@benjiwheeler, I have implemented a fix for this.

**Comment by R4356th** [comment]
> 
> 
> Oh wait, i found them. These look like scratchr2 files.

But they are not. I will try to www-ify them probably.

**Comment by GrahamSH-LLK** [comment]
These are defenitely scratchr2 files. WWW files all use react.js. I think these are copies of the files from scratchr2?

**Comment by R4356th** [comment]
@GrahamSH-LLK, not sure. But they are open source.

**Comment by benjiwheeler** [comment]
@R4356th We closed this issue, but did you have some work you thought would help with it?

**Comment by R4356th** [comment]
@benjiwheeler, yes, just some basic work.
