### ISSUE TITLE
Add redirect shortcuts for 2 tutorials: Animate a Character & Video Sensing

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#4203]
We often want to share links to tutorials in resources as short URLs. There are shortcuts for most of the top tutorials, except for Animate a Character and Video Sensing

SHORTCUTS:
For Animate a Character
**scratch.mit.edu/animate-a-character**

For Video Sensing:
 **scratch.mit.edu/video-sensing**

**Comment by Accio1** [comment]
Is this help-wanted? I think I could do this if it is.

**Comment by benjiwheeler** [comment]
Note that we're checking on the /animate redirect, this is temporarily blocked

**Comment by Accio1** [comment]
I've fixed this on my fork. Do you want me to submit a PR?

**Comment by benjiwheeler** [comment]
@Accio1 Yes please!
