### ISSUE TITLE
Teachers and students can no longer sign up; an error occurs.

### ISSUE THREAD

**Issue by BoomerScratch** [LLK/scratch-www#4212]
![image](https://user-images.githubusercontent.com/60622217/87792857-bea46e80-c844-11ea-959e-29d1bff887d6.png)

Teachers can no longer sign up. As of [this bug report](https://scratch.mit.edu/discuss/topic/423675/), the same happens with students. It appears that the API request gets sent to the wrong URL. It should be `https://api.scratch.mit.edu/accounts/checkusername/USERNAME`, but instead, it gets sent to `https://scratch.mit.edu/accounts/check_username/USERNAME/`.

### Steps to Reproduce

Go to [the teacher registration](https://scratch.mit.edu/educators/register) or to the student registration, and type in a username.

### Operating System and Browser

all?

**Comment by BryceLTaylor** [comment]
This has been fixed.
