### ISSUE TITLE
Browser should not be necessary in WWW

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4214]
Browser is listed as a dependency even though it does not seem to be used anywhere. It was used for Contact Us before meta data detection was removed. So it should be removed.

### Steps to Reproduce

Go to package.json and package-lock.json.

### Operating System and Browser

N/A

**Comment by apple502j** [comment]
If you mean `bowser`, it's used in download pages.

**Comment by R4356th** [comment]
Right. Bowser is what I meant.
