### ISSUE TITLE
NPM Package?

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4215]
Is there an NPM package for this repo? If so, where?

### Steps to Reproduce

N/A

### Operating System and Browser

N/A

**Comment by BoomerScratch** [comment]
I think there is no NPM package for this repo. You should use this:
```bash
npm install https://github.com/LLK/scratch-www.git
```

**Comment by rschamp** [comment]
No, this is just the code for the website, it's not meant to be installed by another project.
