### ISSUE TITLE
Welcoming Committee studio is still linked even if welcomingcommittee is not typed in lowercase letters entirely

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4217]
The Welcoming Committee studio is only linked if it is typed in lowercase letters entirely on Scratchr2 pages. But on WWW pages, it is still linked if welcomingcommittee is not typed in lowercase letters entirely.

### Steps to Reproduce

Comment @welcomingcommittee in a WWW page.

### Operating System and Browser

Firefox 78.0.2 (64-bit), Windows 10 Pro

**Comment by Accio1** [comment]
I don't see how this is an issue though. Isn't it actually an upgrade, because you could type any variation of @welcomingcommittee and it would still redirect to the correct place.

**Comment by R4356th** [comment]
Obviously but Scratchers may get confused.

**Comment by R4356th** [comment]
This is sorta traditionally being typed in lowercase letters.

**Comment by Accio1** [comment]
> Obviously but Scratchers may get confused.

I don't see how this is confusing. It makes more sense that @WelcomingCommittee and @welcomingcommittee link to the same place, because they are both the same apart from capitalization..

**Comment by R4356th** [comment]
> 
> 
> > Obviously but Scratchers may get confused.
> 
> I don't see how this is confusing. It makes more sense that @WelcomingCommittee and @welcomingcommittee link to the same place, because they are both the same apart from capitalization.

But Scratchr2 does not have this (mis)feature and that is where all the confusion originates.

**Comment by BoomerScratch** [comment]
This is low severity, but it's an easy fix:
https://github.com/LLK/scratch-www/blob/08e8bb043c0bdd97c244dd95919d03ef436141d2/src/lib/decorate-text.jsx#L27
```diff
- href={match.toLowerCase() === 'welcomingcommittee' ? '/studios/146521/' : `/users/${match}`}
+ href={match === 'welcomingcommittee' ? '/studios/146521/' : `/users/${match}`}
```

**Comment by R4356th** [comment]
This should fix the issue:

 https://github.com/LLK/scratch-www/blob/08e8bb043c0bdd97c244dd95919d03ef436141d2/src/lib/decorate-text.jsx#L27
 
 ```diff
 - href={match.toLowerCase() === 'welcomingcommittee' ? '/studios/146521/' : `/users/${match}`}
+ href={match.toLowerCase() == 'welcomingcommittee' ? '/studios/146521/' : `/users/${match}`}

**Comment by R4356th** [comment]
@benjiwheeler, want to let us (either me or @BoomerScratch) fix this?

**Comment by R4356th** [comment]
> 
> 
> This is low severity, but it's an easy fix:
> 
> https://github.com/LLK/scratch-www/blob/08e8bb043c0bdd97c244dd95919d03ef436141d2/src/lib/decorate-text.jsx#L27
> 
> ```diff
> - href={match.toLowerCase() === 'welcomingcommittee' ? '/studios/146521/' : `/users/${match}`}
> + href={match === 'welcomingcommittee' ? '/studios/146521/' : `/users/${match}`}
> ```

@BoomerScratch, I think that <code>toLowerCase()</code> is necessary for this.

**Comment by GrahamSH-LLK** [comment]
Well, when we shift scratchr2 over, it will get this feature. Until then, it is a good misfeature. It's just an inconsistency, like how scratchr2 pages look different than scratch-www.

**Comment by BoomerScratch** [comment]
@R4356th That doesn't work:
```javascript
> 'welcomingcommitteE'.toLowerCase() == 'welcomingcommittee'
< true
```
Mine:
```javascript
> 'welcomingcommitteE' === 'welcomingcommittee'
< false
```

**Comment by BryceLTaylor** [comment]
This is not a bug

**Comment by R4356th** [comment]
> 
> 
> @R4356th That doesn't work:
> 
> ```js
> > 'welcomingcommitteE'.toLowerCase() == 'welcomingcommittee'
> < true
> ```
> 
> Mine:
> 
> ```js
> > 'welcomingcommitteE' === 'welcomingcommittee'
> < false
> ```

Huh? With my one you are converting <code>welcomingcommitteE</code> to lowercase and it is supposed to return true because when that is converted to lowercase it would become <code>welcomingcommittee</code>.
