### ISSUE TITLE
Feature Request: Option to Export code in Other Programming Language

### ISSUE THREAD

**Issue by Bombaybrothers** [LLK/scratch-www#4235]
## Feature Request:

Can we add a ****option**** were we can create a Scratch code using block but then we can ****export**** codes in different ****programming language**** such as convert it to ****JavaScript (ES6), Python 3?****

It will help other not justb to learn Scratch but also JavaScript and Python.

**Comment by apple502j** [comment]
There are two problems:
1) Sometimes there is not a good syntax to describe Scratch's behavior. For example, how do you stop scripts in other sprites on Python?
2) Even if it's possible, the code will not work without interpreters. For example, `sprite1.goto(0,0)` may be a way to describe `go to x:(0) y:(0)` block. However, you cannot simply put `sprite1.goto(0,0)` on browser consoles - it will say `ReferenceError: sprite1 is not defined`.

**Comment by BoomerScratch** [comment]
That is [rejected](https://scratch.mit.edu/discuss/topic/343602/). See 2.2 on the list.
