### ISSUE TITLE
Scratchr2: When signed in, profile shows different number of followers than logged out

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-www#4236]
When signed in, my profile shows a different number of followers than logged out
![image](https://user-images.githubusercontent.com/64214252/88479918-ac9b8d80-cf20-11ea-8b4c-95887fcdd95d.png)
![Screenshot 2020-07-26 at 9 15 01 AM](https://user-images.githubusercontent.com/64214252/88479932-c046f400-cf20-11ea-95ab-fba8952ae833.png)

### Steps to Reproduce
Go to your follower count when logged in and out.

### Operating System and Browser

ChromeOS

**Comment by apple502j** [comment]
This is a caching behavior. Also please don't post scratchr2 bugs here, use Bugs and Glitches forum
