### ISSUE TITLE
Unsharing a shared project with a blank title sets the title to a negative integer

### ISSUE THREAD

**Issue by 1132262GitHub** [LLK/scratch-www#4239]
_When you unshare a shared project project with a blank title, it sets the title to a negative integer. It appears that the first time you do this, the title remains blank, but after that it is set to -2 and the number decreases by one for each time this is attempted with a new project._

### Steps to Reproduce

_1. Create a project, delete its title
2. Share it.
3. Unshare it. (title will remain the same the first time if you haven't done it before)
4.  Do the above again with a different project. The title should become a negative integer._

### Operating System and Browser

_MacOS 10.15.5, Chrome 84.0.4147.89_

**Comment by BoomerScratch** [comment]
Are you sure you don't have another project that has a blank title? If so, then that is intentional.

**Comment by 1132262GitHub** [comment]
Ah, that would explain it.

**Comment by apple502j** [comment]
this is intended:

foo
foo-1
foo-2

(blank)
(blank)-1
(blank)-2
