### ISSUE TITLE
Default project count in intro out of date again

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#426]
A while ago we changed the default text on the homepage to read `Over 13 million` projects rather than an incorrect number (which it was before – see #357). We have very quickly moved into 14 million projects, though, making the current text out of date. Possible fixes:

* Continue updating this number every million we get
* Determine alternative text to display that captures the magnitude of projects created but does not need updating as often

**Comment by TheGrits** [comment]
I'll let someone else take this one if they want, I feel that I've kinda been hogging issues recently. 😛

The only thing that came to mind for alternative text for me was `gazillions of projects`, but that's a little informal. (And ambiguous)

**Comment by TheGrits** [comment]
It seems that there are no takers, so I'll go ahead.
