### ISSUE TITLE
When deleted alerts should act like read messages.

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-www#4272]
When a user recieves an alert and then clicks the "X" button at the top right it is deleted forever. This is problematc if a user wants to re-read an alert or accidentally deletes it. A solution to this is for the alert to be marked as read and act like a message once x'ed out.

### Steps to Reproduce
Get an alert and then delete it with the "x" button at he top right. It is now gome forever.

### Operating System and Browser
N/A

**Comment by R4356th** [comment]
This is a feature.

**Comment by Explosion-Scratch** [comment]
Really? Last time I got an alert this was not the case.

**Comment by R4356th** [comment]
When did you get an alert message last tine?

**Comment by apple502j** [comment]
Duplicate of #2218

**Comment by Explosion-Scratch** [comment]
@R4356th About 4 months ago.

@Apple502j Thanks for pointing that out! :) I'll close this one.
