### ISSUE TITLE
Out of date link on Around the World section of the About page

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#4273]
The last sentence of Around the World links to the obsolete wiki page:

> To add or improve a translation, see the [translation](https://en.scratch-wiki.info/wiki/How_to_Translate_Scratch) page.

It should link to https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators

Ideally we'd also replace the image - the list of languages is from Scratch 2.0, and they are not all part of Scratch 3. Also, it's very Euro-centric. (Note: moved this point to its own issue: https://github.com/LLK/scratch-www/issues/4403 )

Where it says "and available in more than 40 languages", it should say 60 instead of 40.
### Steps to Reproduce

https://scratch.mit.edu/about

**Comment by doc-han** [comment]
Hi, can I work on this?

**Comment by benjiwheeler** [comment]
@doc-han Go for it!

**Comment by Nambaseking01** [comment]
This would be helpful for another reason - the wiki page literally states that the article doesn't match Scratch Wiki editing standards, and if any New Scratchers wish to contribute with translating Scratch, that will give out a slightly imagine and make it seem like the Scratch wikians aren't dedicated or smart enough.

**Comment by chrisgarrity** [comment]
BTW I've updated the Scratch Wiki page to link to the new guide and removed out of data information. So if anyone has the old wiki page bookmarked they will have a link to the new guide.

**Comment by Nambaseking01** [comment]
@chrisgarrity Awesome! That's so convenient!

**Comment by chrisgarrity** [comment]
@doc-han note that I've split updating the image out to it's own issue as it's blocked until we decide on a new graphic. Just the text changes are all that's needed to fix this issue /cc @benjiwheeler
