### ISSUE TITLE
FAQ page has not been moved yet 

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4298]
The FAQ page has not been moved to a URL like scratch.mit.edu/page-name yet. This causes inconsistency. 

### Steps to Reproduce

Go to scratch.mit.edu/info/faq

### Operating System and Browser

N/A

**Comment by R4356th** [comment]
I could tackle this one, by the way.

**Comment by Nambaseking01** [comment]
I don't understand why it should be switched to a new page - it makes sense that the FAQ is under the /info/ direction.

**Comment by R4356th** [comment]
Once almost every page like this used to be in a /info directory but they all got moved when 3.0 was released.

**Comment by Nambaseking01** [comment]
Could you specify which pages were moved from /info? Then I might see a reason why the FAQ page hasn't been.

**Comment by R4356th** [comment]
info/cards to ideas, info/credits to credits etc.

**Comment by Nambaseking01** [comment]
hm, I don't see any differences between those pages and the FAQ one. I don't understand why the Scratch Team would just leave alone the FAQ page and change the directory for all the rest of the pages. 

Well, then, it would indeed be nice if this were changed - seems inconsistent and non-professional.

**Comment by benjiwheeler** [comment]
This has been prioritized by the Scratch Team, indicating that we want to do it! Thanks @R4356th. I'm going to label it help wanted -- @R4356th or anyone else, please feel free to submit a PR for it.
