### ISSUE TITLE
Minor typo in Scratch FAQ page

### ISSUE THREAD

**Issue by Nambaseking01** [LLK/scratch-www#4299]
There is a small typo at the "Cloud Variables" section of the FAQ page - the question saying "I am logged in, but I cannot use projects with cloud variables What is going on?" needs a dot between the first sentence and the second one like this:

"I am logged in, but I cannot use projects with cloud variables. What is going on?" 

### Steps to Reproduce

* Go to the Scratch FAQ page (https://scratch.mit.edu/info/faq)
* Click on "Cloud Variables" on the list of sections on the right side of the screen
* Scroll down until you see the question before the last

### Operating System and Browser

N/A - grammar mistakes cannot be different in other operating systems and browsers.

**Comment by R4356th** [comment]
Great eyes, @Nambaseking01. BTW, @benjiwheeler, I prepared a fix but you could assign @Nambaseking01 instead if you wanted to.

**Comment by benjiwheeler** [comment]
@R4356th and @Nambaseking01, we'd be happy to get a pull request from either of you. @Nambaseking01, this would be your first pull request for the Scratch codebase, right? Want to give it a try?

**Comment by Nambaseking01** [comment]
@benjiwheeler I could give it a try for sure, I'll try to do it but I'm rather nervous... I'll do my best, but if I can't do it, then you can request @R4356th.

**Comment by Nambaseking01** [comment]
Done, you can merge it now if you wish.
