### ISSUE TITLE
missing space in teacher account request form

### ISSUE THREAD

**Issue by JeffaloBob** [LLK/scratch-www#4308]
there is a missing space between the bold text and the regular text in the teacher sign up request form.

![image](https://user-images.githubusercontent.com/40470736/90045126-e1ecfd00-dcce-11ea-9d19-c50195077c8a.png)

### Steps to Reproduce

1. visit https://scratch.mit.edu/educators/register
2. notice the missing space

### Operating System and Browser
Chrome on Windows 10

**Comment by Nambaseking01** [comment]
Huh, that's the second grammar mistake this week - definitely interesting how many there have been popping up...

**Comment by JeffaloBob** [comment]
this hasn't been set as help wanted yet but i think the issue is here https://github.com/LLK/scratch-www/blob/develop/src/components/registration/steps.jsx#L183

**Comment by benjiwheeler** [comment]
Thanks, @JeffaloBob and @Nambaseking01. This could probably be fixed by adding a `&nbsp;` to https://github.com/LLK/scratch-www/blob/develop/src/components/registration/steps.jsx#L183 .

(Or maybe there's a better solution, we're open to other possibilities)

**Comment by benjiwheeler** [comment]
Fixed by #4474
