### ISSUE TITLE
Wrong text in the Join Scratch menu

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-www#4313]
When you select where you live, it says “country” instead of “location” as the profile and account settings display.

**Comment by R4356th** [comment]
Country is more appropriate than location, in my opinion.

**Comment by BryceLTaylor** [comment]
This is by design.

**Comment by cyx2015s** [comment]
But obviously Antarctic is not a country...

**Comment by cyx2015s** [comment]
Maybe I misunderstood the meaning of country...

**Comment by apple502j** [comment]
@BryceLTaylor Just want to make sure this is not the reason behind the Great Firewall blocking Scratch.

**Comment by R4356th** [comment]
> Maybe I misunderstood the meaning of country...

No, you are right. Antarctica is a continent but according to the Statistics page, there is no Scratcher from Antarctica.

**Comment by cyx2015s** [comment]
So how does the scratch statistics count the location of Scratchers? By their account settings or there are other ways?

> > Maybe I misunderstood the meaning of country...
> 
> No, you are right. Antarctica is a continent but according to the Statistics page, there is no Scratcher from Antarctica.
