### ISSUE TITLE
Grammatical mistakes in Teacher Registration page

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4322]
The error message "Sorry, teachers must be at least 16 years old" is missing a full stop (or period).

### Steps to Reproduce

1. Go to https://scratch.mit.edu/educators/register

1. Select username and password

1. Change the month

### Operating System and Browser

N/A

**Comment by R4356th** [comment]
There are many other mistakes on that page.

**Comment by kchadha** [comment]
@R4356th thanks for catching this! Unfortunately, we won't fix this issue because of the way our translation system works. This would create more work for all of the people translating our webpages and we only want to do that when absolutely necessary.

**Comment by R4356th** [comment]
@kchadha, I was just wondering if these issues be fixed could be fixed on Transifex. All the English strings available there.

**Comment by apple502j** [comment]
@R4356th No.
- English strings are provided from l10n.json in scratch-www and not on Transifex.
- But when l10n.json changes, it marks the translation as "changes needed", even though there is no actual change.
- This can be problematic because it adds unnecessary steps for translators.

**Comment by R4356th** [comment]
@apple502j, I am talking about [this](https://www.transifex.com/llk/scratch-website/viewstrings/#en/teacherregistration-l10njson/111721227) on Transifex. I think you are a translator so you should be able to view that.
