### ISSUE TITLE
Statistics page graph text is broken

### ISSUE THREAD

**Issue by Thingyman-DEV** [LLK/scratch-www#4340]
_On the statistics page, for the Monthly Activity Trends and the Age Distribution of New Scratchers graph, the y-axis titles are overlapping with the y-axis numbers. Also, the y-axis numbers with 8 digits are cut off in monthly comment activity._

### Steps to Reproduce

_Look at  [https://scratch.mit.edu/statistics/](https://scratch.mit.edu/statistics/)_

### Operating System and Browser

_I am on ChromeOS using chrome, however I can also reproduce on MacOS Catalina using both chrome and safari. However on safari, the numbers in monthly comment activity are cut off at a different point than on chrome_

![Screenshot 2020-08-20 at 5 53 29 PM](https://user-images.githubusercontent.com/67653706/90829613-16376d80-e30e-11ea-9d8e-e0db92a76d30.png)
![Screenshot 2020-08-20 at 5 41 28 PM](https://user-images.githubusercontent.com/67653706/90829615-16d00400-e30e-11ea-9d2a-c3abb45b8ba8.png)
![Screenshot 2020-08-20 at 5 41 11 PM](https://user-images.githubusercontent.com/67653706/90829616-16d00400-e30e-11ea-9d48-01f3cb83934c.png)

**Comment by GrahamSH-LLK** [comment]
Can repro.

**Comment by apple502j** [comment]
Should be moved to scratchr2

**Comment by Thingyman-DEV** [comment]
@benjiwheeler Can this please be moved to scratchr2?

**Comment by GrahamSH-LLK** [comment]
> @benjiwheeler Can this please be moved to scratchr2?

Scratchr2 is _not_ a public repository. You have to use the "Bugs and Glitches" forum.

**Comment by Thingyman-DEV** [comment]
> > @benjiwheeler Can this please be moved to scratchr2?
> 
> Scratchr2 is _not_ a public repository. You have to use the "Bugs and Glitches" forum.

Oh, ok.
