### ISSUE TITLE
Minor typo on Educators page

### ISSUE THREAD

**Issue by Thingyman-DEV** [LLK/scratch-www#4343]
_On the Educators page under News and Updates there is a missing period after "Sign up to receive updates and tips from the Scratch Team"_

### Steps to Reproduce

_Go to [https://scratch.mit.edu/educators](https://scratch.mit.edu/educators) and scroll to News and Updates_

### Operating System and Browser

_MacOS 10.15.6 Using Google Chrome_
<img width="968" alt="Screen Shot 2020-08-21 at 10 06 21 AM" src="https://user-images.githubusercontent.com/67653706/90900021-c781e600-e396-11ea-8794-2f421f87f728.png">

**Comment by GrahamSH-LLK** [comment]
It's not intended there, it's just hard for the translators to change. Probably the same here.

**Comment by BryceLTaylor** [comment]
Closing for the same reasons https://github.com/LLK/scratch-www/issues/4322 was closed by @kchadha
