### ISSUE TITLE
Project 404 page has extra space

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4347]
The project 404 page has extra space under the text saying that the project was not found. Here is a screenshot:

<img width="949" alt="404 extra space" src="https://user-images.githubusercontent.com/61620631/91032072-43905e00-e623-11ea-9fa7-87071560e8d7.png">

### Steps to Reproduce

Go to https://scratch.mit.edu/projects/.

### Operating System and Browser

Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by GrahamSH-LLK** [comment]
Can repro.

**Comment by Thingyman-DEV** [comment]
Can repro. MacOS 10.15.6 Using chrome and using safari.

**Comment by GrahamSH-LLK** [comment]
This could be intended... Maybe they wanted it to be a full screen 404?

**Comment by R4356th** [comment]
> This could be intended... Maybe they wanted it to be a full screen 404?

Why would @BryceLTaylor add the priority label then? 😛

**Comment by wgyt735yt** [comment]
Can reproduce on ChromeOS 13099.110.0 using Chrome 84.0.4147.136.

**Comment by benjiwheeler** [comment]
Now that we have addressed https://github.com/LLK/scratch-www/pull/2763 , the design is where we want it, at least for now.
