### ISSUE TITLE
You can see what you are doing if you are following if you are following yourself.

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4348]
If you follow yourself (with Inspect or Inspect Element), you can see what you are doing in the What's Happening section on the front page. I think this behaviour could be changed.

### Steps to Reproduce

1) Follow yourself with Inspect or Inspect Element (what it is called depends on your browser).
1) Perform a community activity
1) Go to homepage (https://scratch.mit.edu).

### Operating System and Browser

Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by Accio1** [comment]
I don't think that it is worth the effort to fix this. Following yourself isn't an officially supported feature, so if you don't want to see yourself on the what's happening tab, then you shouldn't follow yourself.

**Comment by ljy-002** [comment]
I have this problem too

**Comment by Thingyman-DEV** [comment]
I always thought that that was an intended feature. Hmm.

**Comment by BoomerScratch** [comment]
This is a scratch-api issue.

**Comment by R4356th** [comment]
But has work to do with WWW, too, I think.

**Comment by BryceLTaylor** [comment]
I'm not sure what you expect when this happens.  

It also seems that this is not a bug in the regular functioning of Scratch, but a result of you deliberately going outside of the interface with Scratch.

We typically don't address issues that come up as a result of someone using Scratch outside of the provided user interface unless it negatively impacts other user's experiences.
