### ISSUE TITLE
resource request "localized-urls.json" is in error.

### ISSUE THREAD

**Issue by Macaulish64** [LLK/scratch-www#4362]
when i try to build the project, it can't work because of the resource request.
```
> www@1.0.0 translate:urls /home/ubuntu/scratch-www
> node ./bin/get-localized-urls localized-urls.json
```
then i read the code "get-localized-urls.json". I find it will request the url of "https://resources.scratch.mit.edu/localized-urls.json". Maybe because of i'm in china, it can't be access now.

how could i fix it?

### Steps to Reproduce
when execute the commands:
```
npm run build
```

 Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-88-generic x86_64)

**Comment by apple502j** [comment]
Use VPN or get out of China.

**Comment by Macaulish64** [comment]
> Use VPN or get out of China.

emmm...i use vpn, but it's not work. I try again.
Thanks.

**Comment by BoomerScratch** [comment]
@Macaulish64 Is the location of the VPN set somewhere outside of China? If it still doesn't work, try choosing a location that is even further from China.

**Comment by chrisgarrity** [comment]
@Macaulish64 the localized-urls.json file is generated as part of the build process for Scratch resources: https://github.com/LLK/scratch-resources

As a work around you could fork the scratch-resources repo and generate your own copy of the json.
In your fork of scratch-resources, run
```
npm run localize
```
to generate the file, and then copy it into the www root directory.

Then change the translate step in the `package.json` to remove `translate:urls` from the build process. Of course the generated file references `https://resources.scratch.mit.edu/...` so if you try to go to one of the localized links - e.g. the music cards in Catalan, the file probably won't load, but at least you'll be able to run a local server.
