### ISSUE TITLE
Console warning does not appear when doing "inspect→console" on safari and chrome

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#4365]
The warning to not add copy-pasted javascript to the browser console does not appear if you select "inspect" or "inspect element" on a page and then select "console".

**Comment by Accio1** [comment]
Can't repro Windows, Chrome

It looks like this for me
![ScratchConsoleWarning.png](https://user-images.githubusercontent.com/48496940/91504295-b5261180-e89a-11ea-920a-3941484cfb70.png)

**Comment by R4356th** [comment]
Can't repro on Windows 10, Chrome Version 84.0.4147.135 (Official Build) (64-bit).

**Comment by colbygk** [comment]
Looks like I should have put this on the scratchr2 repo

**Comment by GrahamSH-LLK** [comment]
Please close!

**Comment by colbygk** [comment]
Moving to llk/scratchr2
