### ISSUE TITLE
david-siegel-photo.svg should be converted to png

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#4369]
https://github.com/LLK/scratch-www/blob/0c76fd789a60010618873f966b114b95c82d8db2/static/images/annual-report/david-siegel-photo.svg should be converted to PNG because it's a picture (which is not something SVG is intended for)

**Comment by JeffaloBob** [comment]
heres the png image
![image](https://user-images.githubusercontent.com/40470736/91655634-40c5bb00-eab2-11ea-8f2b-e9cd6f05f303.png)

**Comment by BryceLTaylor** [comment]
Please only file issues on released code.
