### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by LankyBox01** [LLK/scratch-www#4373]
Apparently; i can't log-in to scratch.
If i press the "Log in" button it just logs me out and redirects me to the front page.

Sometimes, it also shows this URL:
https://scratch.mit.edu/accounts/login/?next=/accounts/banned-response/
And i am afraid i was banned.

Can anyone help?

**Comment by LankyBox01** [comment]
Also, i just realized that there's a 404 in the issues tab XD
[proof](http://u.cubeupload.com/LankyBox01/90nHNQ.png)

**Comment by R4356th** [comment]
Can't repro. This should be closed.

**Comment by LankyBox01** [comment]
> Can't repro. This should be closed.

What? There's really nothing to reproduce.
I just enter my username & password, i hit the log-in button, and it happens.

**Comment by R4356th** [comment]
You do not understand! I am saying this does not happen to me! It is not a Scratch bug.

**Comment by LankyBox01** [comment]
> You do not understand! I am saying this does not happen to me! It is not a Scratch bug.

huh...

**Comment by LankyBox01** [comment]
Now i was banned :((
