### ISSUE TITLE
1.4 download links are over http

### ISSUE THREAD

**Issue by JeffaloBob** [LLK/scratch-www#4374]
![image](https://user-images.githubusercontent.com/40470736/91668321-3506e280-eb0c-11ea-892c-78468132d897.png)

the issue is that the link to download scratch 1.4 is a http link which now makes browsers angry 
![image](https://user-images.githubusercontent.com/40470736/91668357-7b5c4180-eb0c-11ea-85a1-9abbb29de9e0.png)
it should be as simple as replacing it with a https link (the url works in https too)
### Steps to Reproduce
click the download link over at https://scratch.mit.edu/scratch_1.4#installation

### Operating System and Browser

Google Chrome 84.0.4147.135 on windows 10 1909

**Comment by R4356th** [comment]
It is because no protocol has been specified in the link.

**Comment by SausageMcSauce** [comment]
The majority of the links on the Scratch 1.4 download page uses http links, not just the one discussed in this issue.

**Comment by benjiwheeler** [comment]
I think this should be a very simple fix, just having the link use 'https://...'

**Comment by jemunm378** [comment]
@benjiwheeler I can easily fix this bug 👍

**Comment by jemunm378** [comment]
@JeffaloBob Please close!
