### ISSUE TITLE
Discuss usage of main.scss, _typography.scss, and lib.render

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#438]
For discussion:

@carljbowman @mewtaylor and I were talking about https://github.com/LLK/scratch-www/pull/435/files/ac9717a095079da5b733aec5e3c0ef19a14d252d#r61077230 and things ended up growing into a larger discussion about global styles.

* #440: ~~The conference views don't use lib.render because it doesn't use intl. This causes it to be built differently than the rest of the views since it needs to import main.scss itself. IMO, ideally all the views should all function the same way following the principle of least surprise.  
If in lib.render, `window._messages` falls back to `{}`, pages without intl packages can still be rendered successfully.  
Then the import of main.scss can be taken out of the conference `Page` component, and the conference views can use render in order to use `main.scss` styles.~~

* #442: ~~In `frameless.scss`, the actual styles should move to main.scss, and `frameless.scss` should only provide variables.~~

* #441: ~~Should the `_typography.scss` file be merged into `main.scss`? Right now some pages import `_typography.scss` to get styles that apply to `#view`, but some pages don't — this could become messy as more views are added. However there may be some unintended consequences that we'll need to deal with if we apply the styles in `_typography.scss` globally.~~

* Get rid of `#view` and instead apply styles to views in the same way as all the other components, so we avoid overrides.  The same can probably happen to `#nav` and `#footer` but there are no overrides there atm.

**Comment by thisandagain** [comment]
> The conference views don't use lib.render because it doesn't use intl. This causes it to be built differently than the rest of the views since it needs to import main.scss itself. IMO, ideally all the views should all function the same way following the principle of least surprise.

Major +1 on this. Having a single "exit" point for our views seems important.

> Should the _typography.scss file be merged into main.scss? Right now some pages import _typography.scss to get styles that apply to #view, but some pages don't — this could become messy as more views are added. However there may be some unintended consequences that we'll need to deal with if we apply the styles in _typography.scss globally.

I also agree that these should be merged into `main.scss`. Having our typography rules be optional seems like a bad idea.

> Get rid of #view and instead apply styles to views in the same way as all the other components, so we avoid overrides. The same can probably happen to #nav and #footer but there are no overrides there atm.

Not sure about this one, but it would be nice to see an example of what you have in mind.

**Comment by mewtaylor** [comment]
On the `_typography.scss` point – there were a couple of different paths forward we discussed earlier off hand, so I thought I'd just include them in this thread to keep track of what we came up with:
1. get rid of the file, and put its type standards into `main.scss`
2. import the file in `main.scss` and remove references to it elsewhere

We were feeling partial to option 1, since we don't have enough global stylings (nor do we really want to) to merit making `main.scss` something that imports a number of other, more specific, scss files.

**Comment by thisandagain** [comment]
That makes sense. Either is totally fine to me ... really whatever you and @carljbowman prefer is 👍 for me. 😄

**Comment by mewtaylor** [comment]
👍 cool – I'd propose that we break out the `typography` and `render` parts of this discussion into their own issues then, since we have a path forward for those (if that works for you, @rschamp).

**Comment by rschamp** [comment]
SGTM @mewtaylor — moved to #440 and #441

**Comment by rschamp** [comment]
@thisandagain Re: `#view` styles, we define the `#view` element within the `Page` component, but the styles for it are split across frameless.scss, main.scss and each of the `{{view}}.scss` files, unlike every other component we have.  It's weird because `components/page/www/page` doesn't have *any* scss at all, it uses the "defaults", but `components/page/conference/page` has its own scss with overrides for `#view` — if you want to compare the difference between these two, you have to compare conference/page.scss, _frameless.scss, and main.scss, instead of `conference/page.scss` and `www/page.scss`. It's just kind of messy.

I think it would be more consistent if the layout styles for the view container were in `page.scss` since this is the component that defines the overall layout and puts the view in its place.  Each view could then define its own relevant styles in a `.name-of-my-view` block, just like any other component.

**Comment by mewtaylor** [comment]
This has been broken out into sub tasks, and completed for the most part, outside of #442 . Closing as this is no longer being referenced
