### ISSUE TITLE
Update  "Email Confirmation" modal

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-www#4390]
_Heads up: I'm not marking this help-wanted because it involves tracing some of the functionality of the resend-confirmation iframe back and making sure the functionality is correctly ported over_

We want to replace the content of the modal that comes up when click the banner that appears when your email address is not confirmed. Right now it uses an iframe of the legacy system, now we want a modal in the new style.

<img width="879" alt="Screen Shot 2020-09-02 at 2 50 11 PM" src="https://user-images.githubusercontent.com/654102/92024164-cacc8880-ed2b-11ea-99fc-1ba25225b651.png">

Clicking "check out these tips" will show more info

<img width="737" alt="Screen Shot 2020-09-02 at 2 49 57 PM" src="https://user-images.githubusercontent.com/654102/92024427-31ea3d00-ed2c-11ea-8316-132c51174196.png">

Also update the banner text to this: 
![Screen Shot 2020-09-08 at 9 48 47 AM](https://user-images.githubusercontent.com/654102/92485158-9720b100-f1b8-11ea-9ed4-ef6d639f0dc0.png)
And allow it to be localized (i.e. bring in https://github.com/LLK/scratch-www/pull/4283)

/cc @carljbowman can you provide the vector assets here?

**Comment by carljbowman** [comment]
Here is a first pass at releasing those assets. Right now the green background blob is separate from email icon, as that blob gets used in multiple modals (this modal and the Join or Sign-in modal). 

That said, if you prefer having these assets combined and/or preferred formatting please let me know.

[confirm email modal assets.zip](https://github.com/LLK/scratch-www/files/5169019/confirm.email.modal.assets.zip)

**Comment by paulkaplan** [comment]
@carljbowman I think it would be helpful to a single vector asset that includes the icon and the background, with the background clipped. It would make positioning much easier, particularly if it doesn't need to adjust to different sizes

**Comment by carljbowman** [comment]
No prob - here is a new combined asset:

[confirm-email-illustration.svg.zip](https://github.com/LLK/scratch-www/files/5218848/confirm-email-illustration.svg.zip)
