### ISSUE TITLE
Couldn't save project on staging with 403 errors

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-www#4397]
I keep hitting try again and it immediately tells me project failed to save
### Steps to Reproduce
Here's the project: (rename to .sb3)
[All About Simple Machines! (3).zip](https://github.com/LLK/scratch-www/files/5164505/All.About.Simple.Machines.3.zip)

Here's what the console looks like:
<img width="395" alt="Screen Shot 2020-09-02 at 15 45 37" src="https://user-images.githubusercontent.com/2855464/92029454-893fdb80-ed33-11ea-818f-713305ac21b2.png">
Error 1:
<img width="379" alt="Screen Shot 2020-09-02 at 15 45 41" src="https://user-images.githubusercontent.com/2855464/92029461-8e9d2600-ed33-11ea-892c-e7ec896f90a6.png">
Error 2:
<img width="396" alt="Screen Shot 2020-09-02 at 15 38 51" src="https://user-images.githubusercontent.com/2855464/92029472-9361da00-ed33-11ea-9e32-85e6f637187e.png">

### Operating System and Browser
Mac OSX Chrome

**Comment by fsih** [comment]
Edit: this project now just contains 1 asset and it's not saving
<img width="786" alt="Screen Shot 2020-09-02 at 15 50 52" src="https://user-images.githubusercontent.com/2855464/92029835-20a52e80-ed34-11ea-9bb1-295af9e727ef.png">

**Comment by fsih** [comment]
I left the page and came back and it saves now

**Comment by BryceLTaylor** [comment]
Couldn't reproduce.  Closing until it comes up again.
