### ISSUE TITLE
Replace image for 'Around the World' section on the About page

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#4403]
The image showing languages is from Scratch 1.4 and shows some languages that we no longer have in Scratch 3.

This could be an updated list of languages, or a global map, or .... We will probably be able to reuse something from the annual report, so I've made this blocked until we decide whether there's something appropriate, or we need something new. 

Once we have an updated asset, this should be relatively easy to fix.

Splitting this out from #4273 

Current:

![image](https://user-images.githubusercontent.com/3431616/108406251-28786280-71f0-11eb-818f-21e70d3fd106.png)

**Comment by benjiwheeler** [comment]
Could repurpose this image:

![image](https://user-images.githubusercontent.com/3431616/108406350-4f369900-71f0-11eb-9c03-733da9fb30c8.png)

**Comment by benjiwheeler** [comment]
@zoebentley is working on a bunch of updates to the About Me page, including updating this image! So now let's consider this blocked on that work, and once it launches we can close this.

**Comment by benjiwheeler** [comment]
This is done -- thanks @zoebentley !
