### ISSUE TITLE
Scratch Setup.exe link redirects to http instead of https

### ISSUE THREAD

**Issue by Ascor8522** [LLK/scratch-www#4406]
It's nice to provide only one link to the latest version of the Scratch Desktop installer for Windows 👍, but it would be even nicer to redirect to the https version of the page.
It is now **taking one more unneeded redirection** when downloading the installer and **can also be a security issue** at some point.

When downloading the file, see the redirects
```
ascor8522@desktop:~$ wget "https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe"
--2020-09-08 18:22:39--  https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe
Resolving downloads.scratch.mit.edu (downloads.scratch.mit.edu)... 151.101.38.133
Connecting to downloads.scratch.mit.edu (downloads.scratch.mit.edu)|151.101.38.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.scratch.mit.edu/desktop/Scratch%20Desktop%20Setup%203.15.0.exe [following]
--2020-09-08 18:22:39--  http://downloads.scratch.mit.edu/desktop/Scratch%20Desktop%20Setup%203.15.0.exe
Connecting to downloads.scratch.mit.edu (downloads.scratch.mit.edu)|151.101.38.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.scratch.mit.edu/desktop/Scratch%20Desktop%20Setup%203.15.0.exe [following]
--2020-09-08 18:22:39--  https://downloads.scratch.mit.edu/desktop/Scratch%20Desktop%20Setup%203.15.0.exe
Reusing existing connection to downloads.scratch.mit.edu:443.
HTTP request sent, awaiting response... 200 OK
Length: 112376224 (107M) [application/octet-stream]
Saving to: ‘Scratch Setup.exe.’
```

### Steps to Reproduce

1. Download the Scratch Setup Windows installer at https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe

### Operating System and Browser

Any OS.
Any browser / command line tool.

**Comment by jemunm378** [comment]
@Ascor8522 I had this problem too

**Comment by JeffaloBob** [comment]
duplicate? #4374

**Comment by cwillisf** [comment]
Thanks for bringing this to our attention! There was a missing setting on the server side; it should be fixed now. You might see the fix immediately or it might take some time for the setting to propagate, so if it still looks broken please give it a day or so. If you still see a redirect to HTTP (instead of HTTPS) after today, please let us know. Thanks again!

Also h/t @colbygk for helping me figure out the details!
