### ISSUE TITLE
Messages are going crazy

### ISSUE THREAD

**Issue by Thingyman-DEV** [LLK/scratch-www#4407]
_If you have been using scratch recently, then you know the messages glitch. Messages are notifying you twice, the numbers are all wrong, sometimes they aren't showing up, it's a mess. I know the scratch team is working on it, I just wanted to also make a place where we can discuss this on github._

### Steps to Reproduce

_I don't currently know. If you use scratch for a little while, wait until you get some messages, and they will go crazy._

### Operating System and Browser

_Mac OS 10.15.6 using Google Chrome._

**Comment by GrahamSH-LLK** [comment]
Yeah. Something's really wrong with the api.

**Comment by Accio1** [comment]
Can reproduce on Windows, Chrome. It's showing that I have unread messages when I don't have any, as well as not showing recent messages when I visit the messages page.

**Comment by Thingyman-DEV** [comment]
Can repro on Mac OS 10.15.6 with safari.

**Comment by R4356th** [comment]
Can't repro on Windows 10 on Microsoft Edge old version and Android 7 and 6 on Chrome 83.

**Comment by GrahamSH-LLK** [comment]
I think this is a widespread API issue.

**Comment by R4356th** [comment]
I really am not experiencing any issue.

**Comment by Thingyman-DEV** [comment]
Hmm. I also have seen a _ton_ of threads in bugs and glitches about it. I'm not trying to debunk what @R4356th is saying, but I do agree with @GrahamSH-LLK that this is probably an API issue. I think it may also be primarily affecting forum notifications, but I can't confirm that.

**Comment by GrahamSH-LLK** [comment]
Can anyone find any API changes? Or changes to the messages page? I also noticed that it's also doing it with ScratchNotifier. And it's not just forum posts, it's everything.

**Comment by apple502j** [comment]
I'm suspecting the root cause is #3721 @benjiwheeler amiright?

**Comment by Accio1** [comment]
According to Paddle2See, this issue is caused by hardware upgrades and should be resolved soon

> I talked to our developers.  They are working on some hardware upgrades and it is causing some issues with the system as a whole.  Hopefully it will sort itself out pretty soon.

Source: https://scratch.mit.edu/discuss/topic/437860/?page=4#post-4401680

**Comment by Thingyman-DEV** [comment]
I believe it is fixed now.
