### ISSUE TITLE
Merge/import _typography.scss with main.scss

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#441]
From #438 

Should the `_typography.scss` file be merged into `main.scss`? Right now some pages import `_typography.scss` to get styles that apply to `#view`, but some pages don't — this could become messy as more views are added. However there may be some unintended consequences that we'll need to deal with if we apply the styles in `_typography.scss` globally.

**Comment by carljbowman** [comment]
This approach of moving the styles from `_typography.scss` into `main.scss` is fine with me. The original reasoning was to keep `main.scss` as clean as possible. That said I agree with @rschamp 's point that importing typography to the page level scss adds a addtional level of obscurity the greater taxonomy.

When this migration happens we just need to run through all the WWW pages that use `main.scss` and clean up any weird side effects. We will need to audit some of the headers and spacing at the page level.
