### ISSUE TITLE
Improve communication when users get muted

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#4447]
When users post unconstructive or disrespectful comments they can end up "muted", unable to comment, for some amount of time. Currently there is very little explanation of how they ended up muted, and no redirection towards positive engagement.

### Design

Final design copy and graphical elements TBD /cc @kathymakes @zoebentley 

Flow is a non-dismissible three step modal:
1. General info modal with next button
2. Redirect towards positive engagement with 'back' and 'next' buttons
3. Closing message with 'back' and 'close' buttons

**Comment by kathymakes** [comment]
Thanks Chris!

Here's the most up to date **[invision file](https://invis.io/62YSG3GVF5X)** – @picklesrus we can work together to finesse the exact spacing, e.g. making sure everything is a multiple of 4px.

And here's the **[copytext doc](https://docs.google.com/document/d/1FNEB8LN-VrlzcKwRATRjYjqT45buHDQ6bBEBErFJ6OA/edit#)** which is a WIP!

Strings and illustrations are still not final yet

**Comment by chrisgarrity** [comment]
Clarifying when educational modal is shown:
* on first mutable offense, on subsequent mutable offenses we will just show the comment disabled component (#4459)
* if the user clicks 'learn more' link in the comment disabled component
