### ISSUE TITLE
Link to Scratch2 offline editor MSI returns 404

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#4458]
On the /download/scratch2 page there is a link for a user maintained msi installer for the scratch 2 offline editor.  Clicking it takes you to a 404 page on github.
<img width="631" alt="Screen Shot 2020-09-25 at 11 06 08 AM" src="https://user-images.githubusercontent.com/1088291/94283812-7ded6380-ff1f-11ea-8be9-632f6baa1eb9.png">

### Steps to Reproduce

Go to https://scratch.mit.edu/download/scratch2
Click the link for the MSI installer in the "Other Versions of Scratch" section of the page
Note: it takes you to a github 404 page
<img width="718" alt="Screen Shot 2020-09-25 at 11 10 34 AM" src="https://user-images.githubusercontent.com/1088291/94283974-c147d200-ff1f-11ea-9d45-94adcfdbf3da.png">

### Operating System and Browser

Mac Chrome (but probably others)

**Comment by GrahamSH-LLK** [comment]
Huh. That used to work. Was the repo made private?

**Comment by GrahamSH-LLK** [comment]
@benjiwheeler Could this be made help wanted? I can't find the repo anywhere on GitHub, so I assume it's gone. If so, I'll just remove the formattedmessage.

**Comment by benjiwheeler** [comment]
Thanks for offering to help, @GrahamSH-LLK. Seems like we set that repo to be private, which might have been a mistake... investigating

**Comment by benjiwheeler** [comment]
Fixed! It was stuck in a weird state, and adding a comment and forcing gh-pages to re-publish fixed the problem.

**Comment by GrahamSH-LLK** [comment]
> Fixed! It was stuck in a weird state, and adding a comment and forcing gh-pages to re-publish fixed the problem.

@benjiwheeler Okay! I just noticed on the page that the "View on GitHub" link is broken because of the repo being private, so you might want to fix  that!
