### ISSUE TITLE
Glitch to get views on a project.

### ISSUE THREAD

**Issue by jemunm378** [LLK/scratch-www#4503]
1. Sign out. 2. Go to a project. 3. Click the green flag. 4. refresh. 5. Repeat steps 3 and 4 for a bit. 6. You can keep doing it to get views higher.

Maybe it can be resolved by scratch remember your IP? If this issue is not fixed, then it can turn scratchers into competing for views.

**Comment by R4356th** [comment]
I believe this is an expected behaviour.

**Comment by jemunm378** [comment]
Oh, well not much scratchers know about this, but I feel like scratch should remember the IP before people start commenting for views

**Comment by BryceLTaylor** [comment]
I could not reproduce this issue.  refreshing and clicking the green flag did not increase the view count while signed in or signed out.
