### ISSUE TITLE
Update Address on DMCA Page

### ISSUE THREAD

**Issue by dietbacon** [LLK/scratch-www#4508]
On the page https://scratch.mit.edu/DMCA we need to update the address for Scratch's office

OLD TEXT:

Copyright Agent / Mitchel Resnick
MIT Media Laboratory
77 Massachusetts Ave
Room E14-445A
Cambridge, MA 02139
Tel: (617) 253-9783

NEW TEXT

Copyright Agent / Mitchel Resnick
Scratch Foundation
201 South St. Suite 1-102
Boston, MA 02111
Tel: 857-233-5422

**Comment by Purple-Hacker** [comment]
Do you need help with this? I can make a PR
