### ISSUE TITLE
Scratch1.4 download links only download if you open links in new tab in chrome

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#4528]
If you go here: https://scratch.mit.edu/scratch_1.4 and click one of the download links it should start the download for the installer but it doesn't.  If you right click on it and choose "Open Link in New Tab" it will download the file.

![Screen Shot 2020-10-16 at 10 37 18 AM](https://user-images.githubusercontent.com/1088291/96272140-b1119880-0f9b-11eb-909c-434fc736ffe2.png)

### Steps to Reproduce

Navigate to https://scratch.mit.edu/scratch_1.4
Click one of the download links
Note: nothing starts downloading even if you wait a long time
Right click on the download link
Choose "Open Link in New Tab"
Note: the file starts downloading

This happens with the "MacScratch1.4.dmg",  "ScratchInstaller1.4.exe", and "Install Scratch with Software Center" links.  The "Installer" link under Windows and the "download here" link under Debian/Ubuntu open a download dialog.

### Operating System and Browser

Mac Chrome, Windows Chrome.  (Not Mac Firefox or Mac Safari)

**Comment by R4356th** [comment]
"MacScratch1.4.dmg" is the only link that does not work for me on Windows 10, Chrome latest version (86.0.4240.75).

**Comment by apple502j** [comment]
This is a simple backend problem. You're not sending `Content-Disposition: attachment`.

**Comment by BryceLTaylor** [comment]
This appears to be fixed.
