### ISSUE TITLE
Export to open video formats

### ISSUE THREAD

**Issue by davidh38** [LLK/scratch-www#4536]
Exporting the scratch file to mpeg or swf any other video formats.

### Explanation

In order to export the file people have to use a screen recorder which leads to low quality or go to potentially shady sites in order to export.

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-gui#5699

**Comment by BryceLTaylor** [comment]
Closing as duplicate of LLK/scratch-gui#5699
