### ISSUE TITLE
Update credits page

### ISSUE THREAD

**Issue by dietbacon** [LLK/scratch-www#4541]
Please add Cindy (https://scratch.mit.edu/users/floralsunset) to the [Credits page](https://scratch.mit.edu/credits)!

**Comment by Accio1** [comment]
@dietbacon I can do this if it is help wanted!

**Comment by GrahamSH-LLK** [comment]
So can I!

**Comment by GrahamSH-LLK** [comment]
I fixed this in my branch github.com/GrahamSH-LLK/Scratch-WWW:patch-1

**Comment by Accio1** [comment]
@GrahamSH-LLK I already said that I would do this.

**Comment by benjiwheeler** [comment]
@Accio1 @GrahamSH-LLK please don't worry about who gets credit for it -- you both make great contributions and we appreciate it! We'll credit you both for your readiness to help in the release notes.

**Comment by benjiwheeler** [comment]
Please submit a PR, one or both of you! Thanks, to both!

**Comment by Accio1** [comment]
@GrahamSH-LLK Feel free to do this. I have contributed a few times to this repository in the past, but it looks like this is your second issue, so go ahead! :)
