### ISSUE TITLE
Ensure muting modal works on small screens

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#4618]
As a follow on to https://github.com/LLK/scratch-www/issues/4447 make sure there are no problems with the mute modals on various sized screens. 

Back and Close buttons are not aligned on all screens.

**Comment by picklesrus** [comment]
Here's one problem when the width is smallish:
![image](https://user-images.githubusercontent.com/15675877/104772166-fda67480-5740-11eb-91d2-73619d6894a6.png)

**Comment by chrisgarrity** [comment]
We checked for format issues prior to launch so I'm closing this issue. If there are problems we can open up specific bugs.
