### ISSUE TITLE
"Load more" bug still happens in search results

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-www#4624]
#4260 has been fixed for comments, messages and Explore, but not search results.

### Steps to Reproduce

Search for something and click Load more. The page will be scrolled down.

### Operating System and Browser

Windows 10
Microsoft Edge 86.0.622.63

**Comment by benjiwheeler** [comment]
I think the same fix as #4260 could be used here?

**Comment by mxmou** [comment]
@benjiwheeler Yes, `overflow-anchor: none` fixes this.
