### ISSUE TITLE
Question: What is the timeline for migrating the remaining scratchr2 pages?

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-www#4631]
Scratchr2 is for Scratch 2.0. When did 3.0 come out? Oh, about 2 years ago. I know that the Scratch Team has more pressing things to do, but supporting the scratch community with a fast, modern, and easy to use platform is important. Slowly continuing to migrate the harder pages, (mystuff, profiles, forums) is no easy task, and I understand that. The thing is, it's frustrating to see that there seems to have been no major change in those integral pages since 3.0 was released. The scratch community asks, "When will these pages be migrated?"

Some quotes from the community:

````
Please implement other important features (like save error alert) before migrating pages.

- Scratch 3.0 Open Source Contributor (apple502j)
````
````
Opening My Stuff on griffpatch account fails / times out. Generally, the main 'All Projects' view is ok, 
but as soon as you try to show 'shared' projects only, or sort by loves, etc the page never returns and 
a 503 timeout error is given in the browser console. This has been the case ever since Scratch 3 went 
live, but was not a problem in Scratch 2.

- Griffpatch
````
````
Why haven't the user and studio pages been migrated when project pages have?

- wgyt
````
From, 
The Scratch Community

**Comment by rschamp** [comment]
We are migrating pages from scratchr2 to scratch-www as resources become available and need presents itself. I'd like to clear up a misconception — while scratchr2 was built to launch Scratch 2.0, scratch-www was not built to launch Scratch 3.0.  Scratch 3.0 and scratch-www are not related.
