### ISSUE TITLE
Images sometimes not showing.

### ISSUE THREAD

**Issue by lovecodeabc** [LLK/scratch-www#4657]
Hello to the team,
I saw a image not loading thing over the past weekend and this week. Most common in My Stuff.
It does show after a few seconds, but it used to show faster. Is this an issue with the cdn?
![4A2C0182-7355-47B9-9144-AA5CE0AB0CF1](https://user-images.githubusercontent.com/74517386/99469213-375d2980-2910-11eb-8657-9dd7e609be37.jpeg)

### Steps to Reproduce

Go to your My Stuff, **quick** so you don’t miss it.

### Operating System and Browser
iOS 14.1, Safari 14

**Comment by SausageMcSauce** [comment]
My Stuff is in a private repository, and according to other issues, bugs about 2.0 styled pages (which are not in this repository) should only be reported in the Bugs and Glitches forum.

**Comment by GrahamSH-LLK** [comment]
> My Stuff is in a private repository, and according to other issues, bugs about 2.0 styled pages (which are not in this repository) should only be reported in the Bugs and Glitches forum.

That is incorrect. @BryceLTaylor has said multiple times that it is helpful to post them here, and they will get transferred to scratchr2. This problem is probably because of the scratch server troubles recently.

**Comment by lovecodeabc** [comment]
Fixed.
