### ISSUE TITLE
Hook up Optimizely for WWW

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#467]
We'd like to be able to test content on the homepage for upcoming partnerships. @thisandagain - please share login when you have it!

**Comment by thisandagain** [comment]
Looks like this will be expensive. Moving to follow-up milestone while we sort out billing.

**Comment by thisandagain** [comment]
Both expensive and will cause some slow-downs (particularly for international users). Pushing to backlog and assigning to @kaschm for follow-up on pricing.
