### ISSUE TITLE
Studio thumbnails are different sizes depending on page

### ISSUE THREAD

**Issue by 1132262GitHub** [LLK/scratch-www#4670]
_On project pages, explore, and user profiles, studio thumbnails render at 170x100, but within the studio, they render at 200x130._

### Steps to Reproduce

_Go to a studio. Notice the dimensions of the studio. Go to a project in the studio, and find that studio on the project's page. Notice how the dimensions are now different._

<img width="656" alt="Screen Shot 2020-11-19 at 4 58 34 PM" src="https://user-images.githubusercontent.com/59401608/99742812-2257d600-2a89-11eb-9332-5ade93f5b248.png">
<img width="659" alt="Screen Shot 2020-11-19 at 5 01 12 PM" src="https://user-images.githubusercontent.com/59401608/99742811-2126a900-2a89-11eb-9249-11ed98cad75a.png">

It would be nice if they all were 200x130.

### Operating System and Browser

_Chrome 86 on macOS (Big Sur)_

**Comment by R4356th** [comment]
I believe this is an expected behaviour.

**Comment by BryceLTaylor** [comment]
This is the expected behavior.  The pages that use 200x130 thumbnails are the old Scratchr2 style and over time will be replaced with the newer scratch-www style.
