### ISSUE TITLE
Homepage module

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#468]
We're adding a homepage module to both logged in and logged out users for a content partnership:

- [x] Content (@kaschm)
- [x] Design (@carljbowman)
- [x] Implementation (@rschamp)

**Comment by carljbowman** [comment]
##  R1 - Banner Sketch 
All content is temporary. Sketch for general sizing and positioning of elements. 
- [ ] Name of the Initiative - Temporarily: 'Make it Fly'
- [ ] Call to action - Could be the same one or two lines that we use on social 
- [ ] Button content

Awaiting addtional asset release from CN
- [ ] Final Girl assets

**Banner appears the same in Logged out & Logged in state**

![r1_make-it-fly-banner logged-out](https://cloud.githubusercontent.com/assets/3409578/15115879/0639869a-15cf-11e6-9f7f-8c7624bfbe4e.png)

![r1_make-it-fly-banner logged-in](https://cloud.githubusercontent.com/assets/3409578/15115884/0b20d4e2-15cf-11e6-9441-25c7b2ffa2d6.png)


## User Flow

- [ ] Need final dates for banner appearing on the homepage (Initial Push)
- [ ] Need final decision. Where to point after initial push: 'Make it Fly' Studio or CN Profile page

![r2_ppg-flow](https://cloud.githubusercontent.com/assets/3409578/15115499/3acec5e8-15cd-11e6-8eae-4c073fcce1d7.png)

**Comment by rschamp** [comment]
Moved to LLK/scratchr2#3659
