### ISSUE TITLE
Non-responsive element on homepage

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#469]
User-reported issue with a non-responsive element on the Scratch homepage. The video element does not resize to fit inside the frame as the page/ browser window changes size.

The user captured very helpful documentation of the issue in action:
Gif of page resizing: http://i.imgur.com/lj9G0Tr.gif
Internet Explorer:
<img width="609" alt="screen shot 2016-05-09 at 10 20 25 am" src="https://cloud.githubusercontent.com/assets/1320456/15116029/b08c2fe4-15cf-11e6-874c-7a0ed3488407.png">
Firefox:
<img width="608" alt="screen shot 2016-05-09 at 10 21 24 am" src="https://cloud.githubusercontent.com/assets/1320456/15116059/cff70020-15cf-11e6-8768-1d6eddcdfe42.png">

The issue occurs in Chrome as well:
<img width="912" alt="screen shot 2016-05-09 at 10 26 31 am" src="https://cloud.githubusercontent.com/assets/1320456/15116261/8cd8ea28-15d0-11e6-96e3-bc8668b5f715.png">

In Chrome, the video element goes from fitting in the frame as your resize the window to **not** fitting in the frame as you resize the window at approximately 935x705 pixels. This is smaller than the [minimum screen size currently supported by Scratch](https://scratch.mit.edu/info/faq/). As discussed with @carljbowman, this is a low priority issue.

Steps to repro:
- Go to scratch.mit.edu
- Make sure you are not signed in (this issue occurs on the homepage you see when you are not signed in)
- Resize the browser window until you see the video element extend outside of the white and gray frame on the right side.

**Comment by Choco31415** [comment]
In these sorts of situation, what would be best? For the video to shrink to fit, or for the video to squish the content on the left?

**Comment by jwzimmer** [comment]
@carljbowman ^^ what's the design preference? : )

**Comment by kyleplo** [comment]
Not a bug anymore - this can be closed.

**Comment by colbygk** [comment]
Confirmed
