### ISSUE TITLE
Display "welcome back" message when user is unmuted

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#4690]
Depends on backend generating the notification (https://github.com/LLK/scratchr2/issues/5832).

https://projects.invisionapp.com/share/62YSG3GVF5X#/screens/432618237

**Comment by lovecodeabc** [comment]
Why would this be needed?

**Comment by chrisgarrity** [comment]
We decided to use the standard admin notification instead of creating anything new. No changes needed on the front end.
