### ISSUE TITLE
Update annual-report route to allow for extra URL information

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#4708]
This route: https://github.com/LLK/scratch-www/blob/ee5495cf7c044b0b0b99b73124c6d1fd90cf6ac7/src/routes.json#L9-L16

Should have an alias that supports extra info on the URL, such as:

https://scratch.mit.edu/annual-report?something=stuff

This has been done manually already, but we need to finalize this in the code base to make it stick before the next deploy:

```
    "routeAlias": "^/annual-report/?(?:\?.*)?$",
```

**Comment by colbygk** [comment]
Created hot fix for this: https://github.com/LLK/scratch-www/blob/fd6018a92ff9b88506497aba6ae2add50b2e989d/src/routes.json#L10-L15

**Comment by kchadha** [comment]
Closed by #4717
