### ISSUE TITLE
Inconsistent capitalization in the account menu

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-www#4731]
In the menu that appears when you click your username in the top right, "My Stuff" and "Account settings" are capitalized differently. See https://scratch.mit.edu/discuss/post/4665559/

### Steps to Reproduce

Sign in and open the account menu.

### Operating System and Browser

Windows 10, Edge 87 but affects all browsers.

**Comment by BryceLTaylor** [comment]
The inconsistency is not a problem for the majority of users.

**Comment by RandomGamePlayer** [comment]
wait why can i still comment even tho it's closed

**Comment by mxmou** [comment]
> wait why can i still comment even tho it's closed

It's possible to comment on closed issues unless they're locked.

**Comment by RandomGamePlayer** [comment]
> 
> 
> > wait why can i still comment even tho it's closed
> 
> It's possible to comment on closed issues unless they're locked.

oh

**Comment by Secret-chest** [comment]
> The inconsistency is not a problem for the majority of users.

It's an 1-character change. Why not change it?

**Comment by mxmou** [comment]
> > The inconsistency is not a problem for the majority of users.
> 
> It's an 1-character change. Why not change it?

I don't know why the ST doesn't want to change it, but a possible reason is that the "updated" string would need to be translated again into every language.
