### ISSUE TITLE
Default PFP Broken

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-www#4735]
During the migration of profile pictures to uploads.scratch.mit.edu, you have inadvertently broken default pfps. On another note, the old default is _way_ out of date. It should be updated. 
People are even _rioting_ about it! https://scratch.mit.edu/studios/28236804/

### Steps to Reproduce
Look at any default PFP profile or project
### Operating System and Browser
All

---
For the design team
Stolen from forums
![Image](http://u.cubeupload.com/darkness3560/newscratchavataropti.png)

**Comment by adroitwhiz** [comment]
To clarify: https://uploads.scratch.mit.edu/users/avatars/default.png returns a 404.

It looks like this on profile pages:
![image](https://user-images.githubusercontent.com/25993062/101362353-01a3c480-386e-11eb-8519-776cc321be94.png)

**Comment by BryceLTaylor** [comment]
This has been solved with a configuration change.
