### ISSUE TITLE
Bad word detector problem

### ISSUE THREAD

**Issue by lovecodeabc** [LLK/scratch-www#4744]
Yeah, title. Screenshot: 
![image](https://user-images.githubusercontent.com/74517386/101666078-c1824480-3a1b-11eb-9191-61e2017840b9.png)

### Steps to Reproduce

My bio at time of writing this was
"HAPPY HOLIDAYS!
thanks lhatr for the bell

ʟᴏᴠᴇᴄᴏᴅᴇᴀʙᴄ | ᴡɪᴋɪᴀɴ | sᴄʀᴀᴛᴄʜᴘʀᴏ ᴏs | ʀᴇǫᴜᴀʟᴀʀ ғᴏʀᴜᴍᴇʀ | ɴᴏ ғ4ғ 
URGENT URGENT URGENT I NEED IDEAS FOR MY 75 follower Q&A POST IN MY COMMENTS!
Mail record 8"
My WIWO is "
 What I'm working on
- Atlantic Hurricane Season Sim - 3.1%
- My website - 100%! Check it out at aboutme.lovecodeabc.repl.co
- Tower Defence - 6%

"
### Operating System and Browser
Chromebook ChromeOS 85.0.4183.133

**Comment by BryceLTaylor** [comment]
@lovecodeabc Can you supply repro steps?  What words did you type in that the bad word detector was incorrect on and where did you type them?

**Comment by lovecodeabc** [comment]
> @lovecodeabc Can you supply repro steps? What words did you type in that the bad word detector was incorrect on and where did you type them?
When I added the .co to aboutme.lovecodeabc.repl, it activated.

**Comment by pufferfish101007** [comment]
@BryceLTaylor I can reproduce this by writing "repl.co" in any of the following: about me what I'm working on,, comments (profile, project and studio), studio descriptions, project descriptions, notes & credits. However, in the forums, it lets it past. It says that repl.co contains unmoderated chat, which it doesn't. Interestingly, repl.it and repl.run are not blocked.

**Comment by R4356th** [comment]
repl.co domains may be malicious since you could make a chat platform there, too.

**Comment by R4356th** [comment]
@BryceLTaylor, why is this "needs repro", by the way?

**Comment by BryceLTaylor** [comment]
@R4356th "needs repro" in this case was because the original post did not indicate which word/words in the whole description were causing the problem.  I asked for reproduction steps, so it got "needs repro."

**Comment by BryceLTaylor** [comment]
links to repl.co are intentionally blocked.
