### ISSUE TITLE
"ℹ ｢wdm｣: Failed to compile. " when running command "npm start"

### ISSUE THREAD

**Issue by leighyu1983** [LLK/scratch-www#4806]
### Steps to Reproduce

1. clone the latest build of scratch-www
2. npm start
3. error shows as shown in attached image.
![react_error](https://user-images.githubusercontent.com/42841816/103396035-f2155400-4b6b-11eb-8d4d-7ebae1e717e5.png)

### Operating System and Browser
All

**Comment by rschamp** [comment]
Hi, this usually is associated with a reason further up in the logs about what caused the failure. If you can supply that I'll reopen. Thanks!
