### ISSUE TITLE
The images is not working on project pages

### ISSUE THREAD

**Issue by lovecodeabc** [LLK/scratch-www#4821]
Hehe. Funny: 
![Screenshot 2021-01-06 at 2 37 23 PM](https://user-images.githubusercontent.com/74517386/103812837-1f12ac80-502d-11eb-822f-e37d794d071f.png)

### Steps to Reproduce

I dunno if this is a cache issue. But the link is https://scratch.mit.edu/projects/443370138/

### Operating System and Browser

ChromeOS v85.0.4183.133

**Comment by BryceLTaylor** [comment]
Could not reproduce

**Comment by Accio1** [comment]
This might happen if your internet cuts out or becomes slow part way through loading the project.
