### ISSUE TITLE
Explore page usernames overflow when avatar images not found

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4822]
When explore page usernames can't be loaded, the CSS formatting becomes off, and usernames overflow when avatar images.

To reproduce:

1. View Explore page
2. Inspect a user avatar
3. Change the `src` URL to something invalid:

![image](https://user-images.githubusercontent.com/3431616/103821762-db27a380-503c-11eb-98bf-49c90fa7b89d.png)

![image](https://user-images.githubusercontent.com/3431616/103821498-3c9b4280-503c-11eb-9d82-10d86ceb4797.png)

**Comment by BryceLTaylor** [comment]
This appears to affect Chrome but not Safari on mac

**Comment by mxmou** [comment]
Setting `display: block` and `overflow: hidden` on the image makes it look like this:
![image](https://user-images.githubusercontent.com/51849865/106506895-9cb1c700-64ca-11eb-8895-cf303f98d26e.png)

Is that an acceptable solution?
