### ISSUE TITLE
Explore page usernames are sometimes centered, sometimes left-justified

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4823]
Explore page usernames are sometimes centered, sometimes left-justified.

It seems that the creator’s name is centered if the project title is really long, but is left-aligned if the project title is short.

![image](https://user-images.githubusercontent.com/3431616/103821946-378ac300-503d-11eb-9ddb-f0b3cd084c78.png)

**Comment by lovecodeabc** [comment]
![Screenshot 2021-01-07 at 12 44 30 PM](https://user-images.githubusercontent.com/74517386/103925871-26e25780-50e6-11eb-8e42-c9e8c91dec1f.png)
Cannot reproduce

**Comment by BryceLTaylor** [comment]
This appears to only be the case if the window is narrow.  I could see it in Chrome on Mac and we could also see it on Safari.

**Comment by lovecodeabc** [comment]
> This appears to only be the case if the window is narrow. I could see it in Chrome on Mac and we could also see it on Safari.

I thought Scratch doesn’t support phones..
I’ll look into it.

**Comment by mxmou** [comment]
The username is currently centered relative to the title. What is the intended behavior?

**Comment by RedGuy12** [comment]
> The username is currently centered relative to the title. What is the intended behavior?

I would think it should stay left aligned
