### ISSUE TITLE
Minor cosmetic issue (spacing) on new developer page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#484]
@rschamp These two words are missing a space, in Design for Tinkerability > "To support this style of interaction, we design our **interfacesto** encourage quick experimentation and rapid cycles of iteration."

https://scratch.mit.edu/developers

Chrome, 50.0.2661.94 (64-bit)
<img width="745" alt="screen shot 2016-05-17 at 12 25 49 pm" src="https://cloud.githubusercontent.com/assets/1320456/15330714/085abd28-1c2c-11e6-8a2b-fe8e495e3a0d.png">

**Comment by TheGrits** [comment]
@jwzimmer @technoboy10 already made a PR that fixes this in #483

**Comment by jwzimmer** [comment]
Reopening since the PR #483 has not actually been merged yet, will close after PR is merged. : )
