### ISSUE TITLE
Project sizing is broken on mobile

### ISSUE THREAD

**Issue by astrosticks** [LLK/scratch-www#4851]
Opening a project page on a mobile device with a low enough resolution / small enough screen will cause the project canvas to overflow out of the page body. 

### Steps to Reproduce

Open a Scratch project page on a mobile browser.

### Operating System and Browser

Tested on iPhone 6S with iOS 14 on both Safari and Firefox

![CA0A001D-A53B-46CE-BDCA-ED2E6F4F926D](https://user-images.githubusercontent.com/32315760/104575326-9ee7da80-561c-11eb-9e29-e3261cae73d1.png)

![544C37B3-9BFE-4C6C-A42E-A17398E36AFB](https://user-images.githubusercontent.com/32315760/104575330-9f807100-561c-11eb-9452-186bb0acf1d1.png)

**Comment by astrosticks** [comment]
Realized this is a dupe of #2513

**Comment by EiJackGH** [comment]
> Realized this is a dupe of [#2513](https://github.com/scratchfoundation/scratch-www/issues/2513)

No repro.
