### ISSUE TITLE
Rephrase Community Guidelines page

### ISSUE THREAD

**Issue by Ascor8522** [LLK/scratch-www#4857]
I'd advise to rephrase / rework the following sentence on the bottom of Community Guidelines page.
`Scratch welcomes people of all ages, races, ethnicities, religions, abilities, sexual orientations, and gender identities.`

While Scratch tries to be inclusive and welcome everybody, the sentence
- makes assumption that races do exist, and this could be considered as offensive by some (offensive)
- makes a difference between a race and an ethnicity, while the word "ethnicity" already covers people from all origins (redundancy)
- might implies only people with those listed "criteria" are welcome, and not the others (e.g. what about people with all kinds of political opinions, are they welcome? they are not listed tho) (completeness)
- mentions sexual orientation, which (sexuality) is a topic that is not allowed on Scratch (messages and posts containing words related to those topics are banned / forbidden), kinda ironic (censorship/irony)
- mentions gender identities, while Scratch primary's audience is young people, who often have no idea what that really means/implies and is a topic they shouldn't worry about for now. Their concern is only to focus on creative thinking and other skills

**My point is, why not just saying `Scratch welcomes everybody.`** since
- it doesn't sound offensive, while it could have been earlier
- it is short, complete and not redundant
- it is more inclusive (which is the original goal of the sentence)
- it does not mention topics not allowed on Scratch / topics the targeted audience shouldn't worry about

**Comment by BryceLTaylor** [comment]
The community guidelines are phrased as intended.

**Comment by easrng** [comment]
> ... mentions gender identities ... they shouldn't worry about for now.

That is absolutely false, many people (including myself) knew from a very young age that their AGAB did not "fit" with how they felt about themselves. 

> ... who often have no idea what that really means/implies ...

And that is an education issue.
