### ISSUE TITLE
Keep mute time remaining at 1 min when less than a minute to go.

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#4886]
If you update the page when you're muted, but there is less than a minute to go it says "You will be able to comment again in 0 minutes", this is misleading.

It would be better to just keep it at 1 minute until it expires.

**Comment by lovecodeabc** [comment]
Maybe like “You can comment again in ___ seconds”

**Comment by picklesrus** [comment]
Also done in scratchr2 so closing. https://github.com/LLK/scratchr2/pull/5961
