### ISSUE TITLE
1.4 Download page should say Mac OS version 10.4-10.14

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4913]
1.4 Download page should say Mac OS version "10.4 through 10.14"

Currently it says "10.4 or later"

**Comment by RoBlockHead** [comment]
working on it!

**Comment by BryceLTaylor** [comment]
This information appears in multiple places on the page.  I believe this issue is specifically referring to here:
![Screen Shot 2021-01-28 at 3 36 21 PM](https://user-images.githubusercontent.com/1088291/106195767-9c3dc700-617e-11eb-9855-214e43a3d0c2.png)

**Comment by JoelGritter** [comment]
@RoBlockHead still working on it? I could also make a PR for this issue.

**Comment by RoBlockHead** [comment]
> @RoBlockHead still working on it? I could also make a PR for this issue.

Unfortunately not, had some stuff interrupt my work. It's all yours.
