### ISSUE TITLE
Bring the trouble and maintenance pages into line with each other

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4914]
Now that we've updated the maintenance page, we should revisit the trouble page. Do we need it? Should we update it similarly? What is each page for?

**Comment by carljbowman** [comment]
Yes, let's merge these pages to be the same.

**Comment by benjiwheeler** [comment]
After meeting with design team, we decided to keep the pages distinct, and update their designs to match, with slight differences.
