### ISSUE TITLE
Unable to reshare projects

### ISSUE THREAD

**Issue by amylh** [LLK/scratch-www#4921]
Multiple Scratchers who have had projects censored are unable to re-share them because the re-share button is missing.

### Steps to Reproduce
Examples of un-sharable projects:
* ~~https://scratch.mit.edu/projects/470379265/~~ (has been reviewed by admin)
* https://scratch.mit.edu/projects/456093741/

### Operating System and Browser
macOS. Mozilla, Chrome

**Comment by jeffalo** [comment]
that's kinda the point of censoring them isn't it?

**Comment by amylh** [comment]
> that's kinda the point of censoring them isn't it?

Right, but Scratchers are supposed to be able to reshare them after they have edited the projects to comply with the rules.

**Comment by BryceLTaylor** [comment]
Can you share the projects from inside the editor?

**Comment by amylh** [comment]
> Can you share the projects from inside the editor?

@BryceLTaylor Nope.

**Comment by amylh** [comment]
> Can you share the projects from inside the editor?

@BryceLTaylor They aren't my projects so I can't check for sure, but after some testing on my own projects, it seems like the in-editor share button is still there - it's just the share button on the project landing page that's missing. I think the owners of the projects I listed in my original comment probably just forgot about the in-editor share button.
