### ISSUE TITLE
News items overflowing below icons

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#493]
I think this is due to the typography update?

Staging
![image](https://cloud.githubusercontent.com/assets/1512021/15360043/081f0eb4-1cda-11e6-9547-a3e34e026707.png)
 vs
Production
![image](https://cloud.githubusercontent.com/assets/1512021/15360054/1951c8c0-1cda-11e6-8bc0-a16cac2d4d46.png)

**Comment by TheGrits** [comment]
Could this also be the cause of the bolding issue on the Privacy Policy page?

**Comment by rschamp** [comment]
@TheGrits Could you make a separate issue for that? I don't see any problems with bolding on that page.

**Comment by TheGrits** [comment]
It's also affecting the `What's Happening` box:
Staging:
![screenshot1](https://cloud.githubusercontent.com/assets/12952370/15360267/ed43f2de-1cda-11e6-9ee2-46ab7df58990.png)
Production:
![screenshot2](https://cloud.githubusercontent.com/assets/12952370/15360261/eb2b9178-1cda-11e6-9239-0980341d6910.png)

**Comment by rschamp** [comment]
Thanks @TheGrits! Since this change was made to make text more consistent across the site, things looking different is OK, so long as the change doesn't break the layout (like the overflow issue). So the different spacing on the What's Happening box is probably ok so long as @carljbowman is ok with it.

**Comment by mewtaylor** [comment]
@rschamp @TheGrits I actually think the "What's Happening?" change might be breaking layout – it looks, from the example above, as if the padding for the text is offsetting it from the thumbnail more than before, not just spacing the text more due to line-height changes. If so, IMHO that might be worth adjusting.

**Comment by carljbowman** [comment]
@TheGrits - Thanks for taking a look at this. The new generalized type standards really focus on extremely text heavy pages, mostly focused on sizing and spacing for large chunks of text. As a side affect line-height is causing weird spacing.

That said, the homepage and it's specific modulars (e.g. 'What's Happening') have not received a lot of design consideration. The strategy with the new standards has been to be general, until they need to be specific for layout purpose, but with this case we just have not gotten to that level of detail.

We should use the general standards for font-sizing, but port over layout/spacing until we have time to revisit these elements.

**Comment by rschamp** [comment]
Fixed in #520
