### ISSUE TITLE
Add bad word filter messages for chain mail

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#4936]
With the vague Community Guidelines, it is not obvious why "a comment" (which is, by some people, called chain mail) triggered a bad word filter. Since the Scratch Team is now doing an overhaul for bad word detector and muting, there should be some sort of messages specific to that.

IMO, most Scratchers do not trigger bad word detector deliberately - they just didn't know the rules, or didn't know how ST reads the rules. In both cases, the user just gets confused because they do not know that a chain mail is "disrespectful" (and by my definition of the word "disrespectful", I don't think I can call them so.) Because the current system does not provide enough information to make them understand, this often leads to "bad word filter malfunctioned" or "i got false reported" feedbacks, and possibly results in future filter triggers (and ban).

For some reason, [the developers or moderators are not happy with adding one for ASCII art](https://github.com/LLK/scratch-www/issues/3991), but I think these need to change.

**Comment by chrisgarrity** [comment]
@apple502j in the new system we're gathering feedback from scratchers who are confused about why they triggered the filters. In some cases, we've been able to adjust the filters to avoid false positives. For other cases we will be prioritizing new messages based feedback data, and we will open issues as needed that include the specific wording.
