### ISSUE TITLE
[Staging] Bolding not working

### ISSUE THREAD

**Issue by TheGrits** [LLK/scratch-www#494]
So far I've noticed this on the homepage and on the Privacy Policy page:
### Staging:

![screenshot1](https://cloud.githubusercontent.com/assets/12952370/15360438/8a464db6-1cdb-11e6-92fa-27d839da8406.png)
### Production:

![screenshot2](https://cloud.githubusercontent.com/assets/12952370/15360458/a76ee0d8-1cdb-11e6-9fcb-9bc1615954e0.png)
### Staging:

![screenshot3](https://cloud.githubusercontent.com/assets/12952370/15360514/d8e56ef2-1cdb-11e6-93c0-6fb16a63fe8a.png)
### Production:

![screenshot4](https://cloud.githubusercontent.com/assets/12952370/15360527/e6a93500-1cdb-11e6-9b42-979c2568f328.png)

**Comment by rschamp** [comment]
Could you tell us your browser/OS? I see bolding on the Privacy Policy page as expected:
(Staging)
![image](https://cloud.githubusercontent.com/assets/1512021/15360789/0c15a458-1cdd-11e6-92d3-51e92a836371.png)

I wonder if it's an issue with available fonts. Maybe you don't have the weights we're specifying?

**Comment by TheGrits** [comment]
@rschamp My browser / operating system: ChromeOS 7978.74.0, Chrome 50.0.2661.103, Flash 21.0 (release 0)

**Comment by TheGrits** [comment]
@rschamp 
I've had an interesting discovery: When I disable the `font-weight: 500` rule for the homepage links, they bold correctly.

**Comment by TheGrits** [comment]
@rschamp There are two contradicting rules on the Privacy Policy page: 
![screenshot 2016-05-18 at 9 53 41 am](https://cloud.githubusercontent.com/assets/12952370/15361169/7b753286-1cde-11e6-8af4-17d5919760d6.png)

**Comment by TheGrits** [comment]
Seems to be fixed now, so I'm closing the issue.
