### ISSUE TITLE
Inbox counts unread messages from "Older Messages" pages

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-www#495]
See this picture:
![](http://u.cubeupload.com/Tymewalk/11moremessages1.png)
It says I have 14 messages. But when I check my inbox:
![](http://u.cubeupload.com/Tymewalk/11moremessages2.png)
I only have 3.

The same happens when I go to the homepage (note that it was taken immediately after, compare the "What's Happening" feed):
![](http://u.cubeupload.com/Tymewalk/11moremessages3.png)

I don't see these extra messages anywhere else on the site, so I think it's a problem with the homepage's topbar.

Anyone else experiencing this? I'm running Firefox 46 if it helps.

(Also, if someone could direct me to where the messages are counted I could poke around and see what's going on)

**Comment by Tymewalk** [comment]
Also, note that the "Wiki" tab in the inbox is just from a userscript I'm running.

I did disable it and the same thing happens, though - 11 extra messages.

**Comment by mewtaylor** [comment]
@Tymewalk thanks for the thorough report! Quick question – does the number change to reflect the right amount after a few minutes? The count on the homepage is cached for a small amount of time.

**Comment by Tymewalk** [comment]
@mewtaylor Nope. No matter how long I wait, it still adds 11 to my real message count. The messages do update properly, for example, if I get a new message it'll raise the counter to 12.

**Comment by Choco31415** [comment]
I have talked to several Scratchers about this bug before, and it seems like this bug has very inconsistent behavior. Several Scratchers have only experienced it on the pages that use the old website skin. Another Scratcher reported that they only experienced it on the front page. Another Scratcher reported that it happened on “ALL pages (except for the messages page)”.

In general, though, it seems like the bug happens such that the message count displayed is always: x + message count.

One odd thing is that the website API seems to report the correct number of messages for Scratchers who are affected by the bug.

@mewtaylor:
I've experienced the bug myself, twice, and it did not go away for a few hours.

**Comment by jwzimmer** [comment]
A user reported this issue via freshdesk:
> The message count isn't resetting when I read the messages. Sometimes a message count even pops up when there hadn't been one before, and it still turns out there are no new messages.

**User Metadata:**
- User: bharvey 
- Operating System: MacOS Macintosh X 10.6 
- Browser: Firefox 31.0 
- Flash Version: Flash 21.0 (release 0)

**Comment by mewtaylor** [comment]
@Choco31415 @Tymewalk @jwzimmer thanks for summarizing what you've heard from others too! And the info about the api. It seems that there are some things happening here with caching, this is helpful for knowing where to start investigating.

**Comment by jwzimmer** [comment]
Potentially related:
- https://github.com/LLK/scratchr2/issues/3482

Discussion in Bugs & Glitches:
- https://scratch.mit.edu/discuss/topic/195160/
- https://scratch.mit.edu/discuss/topic/201561/
- https://scratch.mit.edu/discuss/topic/203786/
(I responded to the above threads that we're looking into notifications showing an inaccurate number of new messages.)
- https://scratch.mit.edu/discuss/topic/203316/

With studio activity:
- https://scratch.mit.edu/discuss/topic/204333/
- https://scratch.mit.edu/discuss/topic/204389/
- https://scratch.mit.edu/discuss/topic/204379/
(I did not respond to these threads since I'm not sure if they'll fall under the umbrella of this case, so I didn't want to say we're looking into something we're not.)

**Comment by Tymewalk** [comment]
Updating, I still experience this, and I briefly did around 2 weeks ago on all pages, but now it's back to just on the new-skinned pages.

I'm testing on with Firefox 47.0.

**Comment by Tymewalk** [comment]
(Thanks to P-Code for telling me this!)

It's caused by unread messages in older pages. This happened when I went inactive for a while and messages kept piling up. I never bothered to check the older messages because they were all studio updates, so they were never marked as read.

To reproduce:

- Get enough messages one page can't display them (and you have to click "older messages" to see them all).
- Open your inbox, but don't click "older messages yet".
- Go to the front page. Note what number there is (for me it was 53).
- Go back to your inbox and read the older messages. (Click older messages and view the greyed messages)
- Go back to the front page. The number should be lower or gone (for me it was 11, meaning I still have 11 messages I haven't read.)

To fix I think there should be a "mark all messages as read" button if there isn't already. I can't seem to find those remaining 11 messages.

**Comment by Tymewalk** [comment]
Updated the title to reflect why this happens.

Summing up what I've seen: the old pages count messages that have come in since the inbox was last checked, whereas the new ones count messages waiting to be seen, such as those on "older messages" pages.

The solution is to add a "mark all messages as read" button to clear out old messages (I can't find where those last 11 are). This way if users come back from long periods of inactivity or get featured/curated and get flooded with messages, they can clear the inbox easily.

**Comment by mewtaylor** [comment]
@Tymewalk thanks so much for updating this to reflect the investigation, and for providing such a thorough report of what you're seeing!

this is an issue with our api, so I'm going to close the issue here and open it up there. I'll let you know as soon as we get to it!

**Comment by Tymewalk** [comment]
Not really sure where that repo/issue tracker is, so I'll just post here.

On all pages except the messages page itself, it says I have 11 messages:
![note that this isn't a new page](http://i.imgur.com/XaLReyu.png)
Note that this only happened on the new pages before, but now it happens everywhere (tested on projects, profiles, discussion forums, etc.)

**Comment by Choco31415** [comment]
@Tymewalk Can you try going here and checking if you get the 11 message bug? https://scratch.mit.edu/parents/

**Comment by Tymewalk** [comment]
@Choco31415 Just checked now. The bug still appears on new pages, but is gone on old pages like that one, my profile, and the forums.

Whatever changed in those 5 days fixed it.

**Comment by Tymewalk** [comment]
![Huzzah!](http://i.cubeupload.com/GuThNe.png]

The issue has finally been fixed on new pages. I still think a "mark all messages as read" button would be good, though.

**Comment by mewtaylor** [comment]
@Tymewalk ah sorry forgot to check in with you and close this! Thanks for confirming :). We probably can't get to a "mark all messages as read" button for now, but as we move the notification system over to www and refactor it, we'll see what we can do!
