### ISSUE TITLE
add a link to Scratch Lab in footer

### ISSUE THREAD

**Issue by jeffalo** [LLK/scratch-www#4961]
discovery for scratch lab isn't great, once theres a scratch lab home page, adding a link to footer will make it easier to find (& can help with seo)

[there's also a forum topic about this](https://scratch.mit.edu/discuss/topic/481481)

### Steps to Reproduce

1. go to footer
2. there is no link to scratch lab

**Comment by BryceLTaylor** [comment]
Thanks for the suggestion.  We have other things to consider before we can act on this.
