### ISSUE TITLE
Pirated

### ISSUE THREAD

**Issue by ljy-002** [LLK/scratch-www#4995]
I would like to ask:
Since the US Scratch was blocked, there have been many piracy in China
For example: [Scratch-cn](http://www.scratch-cn.cn/)
More cheeky: [Make money](http://p1.youynjy.cn/index.php?m=goods&a=details&content_id=91#)
**Is Scratch authorized?**

**Comment by apple502j** [comment]
Scratch itself is open source, so it is possible to legally make Scratch clones. However, they have to remove Scratch logo or Scratch mascots, as they are trademarked.

**Comment by ljy-002** [comment]
So what to do

**Comment by BryceLTaylor** [comment]
Thanks for reporting this.  We're looking into it.
