### ISSUE TITLE
[Staging] Footer link for Press not working

### ISSUE THREAD

**Issue by TheGrits** [LLK/scratch-www#500]
Staging:
![screenshotstaging](https://cloud.githubusercontent.com/assets/12952370/15432644/23f28a18-1e7d-11e6-993e-b577b0dc6774.png)
Production:
![screenshotproduction](https://cloud.githubusercontent.com/assets/12952370/15432663/3dddc6ae-1e7d-11e6-897b-49436afcf41c.png)

**Comment by mewtaylor** [comment]
Fixed by #503
