### ISSUE TITLE
Having Trouble link on Confirm Email banner points to wrong page and 404s

### ISSUE THREAD

**Issue by wgyt** [LLK/scratch-www#5086]
_Describe the problem. Please make sure you can reproduce the bug. It's also
helpful to include screenshots or animated gifs of the problem._

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described above. The 
more detailed and explicit the steps are the better._

1. Login to an account that doesn't have a confirmed email
2. Go to a 2.0 page with the confirm your email banner (My Stuff, Settings, etc.)
3. Click the "having trouble?" link
4. See the 404 page

### Operating System and Browser

Windows 10 Version 20H2:
Chrome 88.0.4324.190 (Official Build) (64-bit) (cohort: Stable)
Edge 88.0.705.81 (Official build) (64-bit)

**Comment by BryceLTaylor** [comment]
The link takes you to https://scratch.mit.edu/help/faq/#accounts which is not a real page anymore.  It should take you to https://scratch.mit.edu/info/faq/#accounts
