### ISSUE TITLE
Scratch 2.0 Offline Editor page has broken Adobe AIR links

### ISSUE THREAD

**Issue by djsrv** [LLK/scratch-www#5132]
The [Scratch 2.0 Offline Editor page](https://scratch.mit.edu/download/scratch2) currently has multiple links to http://get.adobe.com/air/. This link used to be the download page, but now it just redirects to a blog post which states that Adobe no longer supports AIR.

Adobe AIR support is now provided by HARMAN, and their download page for the free version is https://airsdk.harman.com/runtime. All Adobe AIR links should be updated to this one.

Unfortunately, HARMAN does not provide AIR for Mac OS 10.5 or older, so I'm not sure if there's anywhere to download that version now. That link may have to be removed.

### Steps to Reproduce

Click any of the Adobe AIR download links on [Scratch 2.0 Offline Editor page](https://scratch.mit.edu/download/scratch2). They all redirect to https://blog.adobe.com/en/publish/2019/05/30/the-future-of-adobe-air.html

**Comment by Secret-chest** [comment]
I'm sad cuz I use Linux...

**Comment by flight-commander** [comment]
Scratch 2.0 fixed - Version 451 up and running on Mac OS Big Sur - Managed to get it working for my kids. Will post how to get version 461 running in a bit....Can't install 461, but there is a work around if you need it. 

461 actually runs much smoother though. . Press to watch

[![Watch the video](https://i.ytimg.com/an_webp/XhvIXZ-9SVU/mqdefault_6s.webp?du=3000&sqp=CIW1wpwG&rs=AOn4CLD2I15tIdn7eaYFoZGA6X7Ka1mlQQ)](https://www.youtube.com/watch?v=XhvIXZ-9SVU&t=327s)

**Comment by SoCuul** [comment]
It appears that the download links were also removed at some point, to download the 2.0 offline editor alltogether.

**Comment by mxmou** [comment]
> It appears that the download links were also removed at some point, to download the 2.0 offline editor alltogether.

I don't think they were removed on purpose - they don't appear because the certificate for the download.scratch.mit.edu domain has expired, which causes a request to fail. The link that should be there is http://cdn.scratch.mit.edu/scratchr2/static/sa/Scratch-461.air
