### ISSUE TITLE
Conference Schedule pages not loading randomly; fixed by hard refresh - on staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#517]
I saw this in IE 11 while testing #497 and told @mewtaylor about it; he then saw it in Chrome. Hard refresh caused the page to load properly; regular refresh did not.

I did not repro this. I have to QA the other issues for this release and from talking to @mewtaylor this issue is non-blocking unless we repro or someone else runs into it. Logging it so we can figure it out at some point. **--> Since @technoboy10 ran into this issue, too, @mewtaylor and I agree it is now a blocking issue.**

@mewtaylor thinks it might be a bundling issue
http://stackoverflow.com/questions/31566586/jquery-and-jquery-validate-unable-to-get-property-call-of-undefined-or-null-r

IE 11 (windows 7 vm from microsoft)
<img width="782" alt="screen shot 2016-05-26 at 4 54 24 pm" src="https://cloud.githubusercontent.com/assets/1320456/15590361/50ce794c-2365-11e6-813e-fcec5d6e275c.png">

**Comment by technoboy10** [comment]
Getting the same blank page and error on /conference on staging (Chrome).

**Comment by rschamp** [comment]
I think this is due to the deployment errors we're seeing on the release branch builds.

**Comment by mewtaylor** [comment]
Seems reasonable – fyi we're seeing build failures on the `develop` branch too, not just release.

**Comment by mewtaylor** [comment]
@technoboy10 @jwzimmer I'm no longer seeing intermittent errors – are you?

**Comment by technoboy10** [comment]
@mewtaylor Nope, not seeing errors anymore on the same browsers I tested on before.

**Comment by mewtaylor** [comment]
@jwzimmer @rschamp I'm wondering if we should close this for now – it seems like it might've been something up externally. Thoughts?

**Comment by rschamp** [comment]
Yeah I think this was due to Fastly not getting purged between deploys from develop and release, so should be fixed now that it's purged.  Because of the error we will need to purge manually after each deploy.
