### ISSUE TITLE
Move the "Learning with Scratch" pdf off of llk.media.mit.edu

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#5196]
The "Learning with Scratch" one page pdf linked to from /parents is found on llk.media.mit.edu, and recently a certificate expired on it so that some browsers gave a security warning.  This was reported in help desk ticket 311730.  

We should move the PDF to a location that we maintain.

### Steps to Reproduce

Navigate to scratch.mit.edu/parents
In the Learning section under "How does Scratch work for children?" click the link that says "Learning with Scratch"
![Screen Shot 2021-03-26 at 11 36 02 AM](https://user-images.githubusercontent.com/1088291/112656180-83246000-8e27-11eb-8fcb-d7667d3a5a33.png)
Note: it takes you to https://llk.media.mit.edu/scratch/Learning-with-Scratch.pdf
In some instances this may show a security warning

**Comment by colbygk** [comment]
We could take this PDF and place it into https://downloads.scratch.mit.edu/Learning-with-Scratch.pdf

**Comment by Rendangbike** [comment]
Interestingly, the link is secure on Chrome.

**Comment by apple502j** [comment]
Certificate was renewed btw.

**Comment by BryceLTaylor** [comment]
Since this is working, we're going to close this issue.  It's okay to link out to an external resource.
