### ISSUE TITLE
Hitting share while editing project instructions makes your edits disappear

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#5210]
## Related to:
https://github.com/LLK/scratch-www/issues/3399 - possible solution to this category of problem

## Expected behavior:
1. create a project
2. in project's community page, start to edit instructions
3. click "Share" button
4. reload page
5. your instructions changes should be there

## Actual behavior:
5. they are not there!

![share-prob](https://user-images.githubusercontent.com/3431616/113043397-614e1480-916a-11eb-8554-1d8f2d08142d.gif)

**Comment by BryceLTaylor** [comment]
I couldn't reproduce this.  Is it a result of replication lag?
