### ISSUE TITLE
Increased amount of BaG reports on "question mark assets"

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#5239]
@paulkaplan @benjiwheeler @fsih This could be due to recent release ( #5234 ) having wrong deps version, maybe revert? @BryceLTaylor Is this severity-high, impact-high?

**Comment by apple502j** [comment]
Seems like this is now fixed? Maybe it's asset server being down... hmm

**Comment by BryceLTaylor** [comment]
We have fixed the immediate cause of the problem and are still working on some of the resulting fallout.  Thanks for reporting!
