### ISSUE TITLE
scratch 2.0 -> 3.0

### ISSUE THREAD

**Issue by meena-ceutania** [LLK/scratch-www#5244]
in users by scratch, its the version 2.0
# convert 2.0 in 3.0

**Comment by GrahamSH-LLK** [comment]
If you want to convert 2.0 pages to 3.0, you can check out Scratch Addons. It's Open Source at https://github.com/scratchaddons/scratchaddons. Get it at https://scratchaddons.com

**Comment by SausageMcSauce** [comment]
> If you want to convert 2.0 pages to 3.0, you can check out Scratch Addons. It's Open Source at https://github.com/scratchaddons/scratchaddons. Get it at https://scratchaddons.com

Browser extensions are not allowed to be linked to on Scratch, and since these GitHub repositories might be linked to from Scratch, the rule on browser extensions might extend to Scratch's repositories.

**Comment by GrahamSH-LLK** [comment]
> > If you want to convert 2.0 pages to 3.0, you can check out Scratch Addons. It's Open Source at https://github.com/scratchaddons/scratchaddons. Get it at https://scratchaddons.com
> 
> Browser extensions are not allowed to be linked to on Scratch, and since these GitHub repositories might be linked to from Scratch, the rule on browser extensions might extend to Scratch's repositories.

I'm taking the risk. If the ST have a problem with it, they can delete the comments.
