### ISSUE TITLE
Squished/ Responsive nav: Conference page on mobile

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#529]
Non-blocking issue found in https://github.com/LLK/scratch-www/pull/497

I saw this on my iPhone 6 in Chrome; space between icon and links should be larger:
![img_7288](https://cloud.githubusercontent.com/assets/1320456/15618897/b322e498-241e-11e6-9283-030b8dcf4fc2.PNG)

**Comment by mewtaylor** [comment]
Fixed in #551
