### ISSUE TITLE
Disabling Comments Through Bookmarklets Not disabling comments

### ISSUE THREAD

**Issue by Shluffy** [LLK/scratch-www#5300]
Using code to disable comments through a bookamrklet will check the checkbox but not actually disable comments
### Steps to Reproduce

1. Save `javascript:let a = document.getElementById("comments-enabled"); a.checked=true;` as a bookamrklet
2. Go to your scratch userpage and click it.
3. This happens 

https://user-images.githubusercontent.com/81823039/116407152-7668a280-a7ff-11eb-96c1-a13880ba5884.mp4

### Operating System and Browser
ChromeOS 13904.10.0, Chrome 91.0.4472.19 chrome beta

**Comment by Accio1** [comment]
Not sure, but I feel like [this](https://github.com/LLK/scratch-www/issues/4348#issuecomment-682658478) comment may also apply here. Using a bookmarklet is not an officially supported Scratch feature so I don't really see how it needs to be fixed.

**Comment by Shluffy** [comment]
> Not sure, but I feel like [this](https://github.com/LLK/scratch-www/issues/4348#issuecomment-682658478) comment may also apply here. Using a bookmarklet is not an officially supported Scratch feature so I don't really see how it needs to be fixed.

Yes, I do see how that applys
