### ISSUE TITLE
Scratch Giving Week Donate Button Banner

### ISSUE THREAD

**Issue by kmlshalf** [LLK/scratch-www#5318]
## Background
This banner will be displayed during Scratch Giving Week (same dates as Scratch Week, May 17-23). The goal is to increase visibility of the donate page, and eventually lead to having a more visible donate button on the scratch homepage. 

The banner will **only be shown on the logged-out Scratch homepage**, and will not be visible to any logged-in scratchers. 

## Specs
<img width="791" alt="Screen Shot 2021-04-29 at 6 39 11 AM" src="https://user-images.githubusercontent.com/17713728/116559815-a70b1380-a8b5-11eb-8840-bfad98536c1d.png">

- Static/Sticky banner will stay in place with the nav during scrolls (see [prototype](https://www.figma.com/proto/17RXndTw4zD0R703zhk0xi/R1_Logged-out-Homepage-Donate-Sketch?page-id=139%3A0&node-id=139%3A1&viewport=560%2C409%2C0.4380169212818146&scaling=min-zoom) for clarification)
- The banner will go over the existing page content. 
- Donate button will link to [donate page](https://secure.donationpay.org/scratchfoundation/)
- There is an option to close the banner using the 'close' x in the corner. However, the banner will show up again if a user leaves the site and comes back throughout the duration of Scratch Giving Week. 

![Banner Sizing + Spacing](https://user-images.githubusercontent.com/17713728/116560640-6cee4180-a8b6-11eb-89be-6d3249952b9a.png)

### Copy
_Scratch is the world’s largest free coding community for kids. Your support makes a difference._

### Resizing
- Text should start wrapping at screen width 1090px. 
- Button should wrap at screen width 752px.
- Banner retains same font size and icon size throughout resizing. Spacing between items within banner (text/sparkle icon/donate button) also remain the same. Donate button/sparkle icon/text group will always be centered, with left text-alignment. 

**834px width (Chromebook/Tablet)**
<img width="752" alt="iPad Pro 11" src="https://user-images.githubusercontent.com/17713728/116559913-bee29780-a8b5-11eb-88c5-3d4ced2ba90a.png">

**768px width (Chromebook/Tablet)**
<img width="693" alt="iPad mini" src="https://user-images.githubusercontent.com/17713728/116559938-c609a580-a8b5-11eb-950b-20b4216d1072.png">

**414px width (Mobile)**
<img width="684" alt="iPhone 11 Pro Max" src="https://user-images.githubusercontent.com/17713728/116560019-d4f05800-a8b5-11eb-8e89-bada05fa3cce.png">

## Links
[**Figma Prototype**](https://www.figma.com/proto/17RXndTw4zD0R703zhk0xi/R1_Logged-out-Homepage-Donate-Sketch?page-id=139%3A0&node-id=139%3A1&viewport=560%2C409%2C0.4380169212818146&scaling=min-zoom)
[**Figma Page**](https://www.figma.com/file/17RXndTw4zD0R703zhk0xi/R1_Logged-out-Homepage-Donate-Sketch?node-id=139%3A1)
[**Donate page**](https://secure.donationpay.org/scratchfoundation/)

**Comment by kchadha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Donate Button on Homepage for Scratch Week](https://trello.com/c/TFQglPLe/207-donate-button-on-homepage-for-scratch-week)
