### ISSUE TITLE
Post deploy - unexpected results of typography changes

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#532]
Per conversation with @carljbowman and @rschamp, using this issue to smoke test/ search scratch-www for unexpected effects caused by the typography changes. (Some of the issues may not be caused by typography; we can spin off separate cases for those issues as needed.)

**Issues on Homepage, About**

1) moved to --> #537

2) Language dropdown opens smaller than it could:
<img width="319" alt="screen shot 2016-05-31 at 10 40 42 am" src="https://cloud.githubusercontent.com/assets/1320456/15678519/9e9b807e-271c-11e6-813f-be2e16d2e36b.png">
![out9](https://cloud.githubusercontent.com/assets/1320456/15678518/9e8f5204-271c-11e6-8f54-e7ee5ea5a846.gif)

3) moved to --> #538

4) Period on it's own line on about page, https://scratch.mit.edu/about/:
<img width="435" alt="screen shot 2016-05-31 at 10 46 40 am" src="https://cloud.githubusercontent.com/assets/1320456/15678619/08e7688a-271d-11e6-9757-55bbd9a839b5.png">

5) Maybe spacing with links on about page is too large? (I'm not sure if this is by design or not.)
<img width="374" alt="screen shot 2016-05-31 at 10 48 00 am" src="https://cloud.githubusercontent.com/assets/1320456/15678685/3f4dd828-271d-11e6-9a34-937da4c3b351.png">

6) Initial play button for video on about page doesn't seem to work:
- Go to about page
- Click the circle play icon on the Learn to Code, Code to Learn video
- Note that the video doesn't play, although the click does have an effect (brings up pause/ play bar at bottom of video screen)
- Clicking on the video now will make it play/ pause
  <img width="445" alt="screen shot 2016-05-31 at 10 49 29 am" src="https://cloud.githubusercontent.com/assets/1320456/15678793/8b807048-271d-11e6-87f8-03e74c6e9263.png">
  ![out9](https://cloud.githubusercontent.com/assets/1320456/15678941/14185948-271e-11e6-8f4e-ee807fa021c0.gif)

**Issues on Conference**

7) moved to --> https://github.com/LLK/scratch-www/issues/536

8) Different border sizes in very small browser window (Plan Your Visit section; Exploring Cambridge is wider than the others):
<img width="418" alt="screen shot 2016-05-31 at 12 10 39 pm" src="https://cloud.githubusercontent.com/assets/1320456/15681821/d66d8a9a-2728-11e6-8ed3-a1d070da33d9.png">
<img width="425" alt="screen shot 2016-05-31 at 12 10 30 pm" src="https://cloud.githubusercontent.com/assets/1320456/15681822/d66e27fc-2728-11e6-9a8a-be064969120e.png">
<img width="435" alt="screen shot 2016-05-31 at 12 10 12 pm" src="https://cloud.githubusercontent.com/assets/1320456/15681823/d66fa47e-2728-11e6-9096-930b2d7fd23d.png">

9) Different border sizes in very small browser screen (What to Expect section):
<img width="402" alt="screen shot 2016-05-31 at 12 23 03 pm" src="https://cloud.githubusercontent.com/assets/1320456/15682188/8430cd12-272a-11e6-908c-7cdfa6ae9017.png">
<img width="415" alt="screen shot 2016-05-31 at 12 22 45 pm" src="https://cloud.githubusercontent.com/assets/1320456/15682189/84342a7a-272a-11e6-9449-08adaaa4b4aa.png">

**Comment by jwzimmer** [comment]
@carljbowman, @rschamp - I went through and smoke-tested the homepage and conference page; these are all the issues I found. I made a new issue as discussed for the schedule items > detail pages. If there's anything else I should spin off as a new case, let me know. Who should this issue go to now? Should it go in the backlog? Should I assign anyone to it? Thank you!

(I removed prio-high label since this was prio-high for me to go through and check for post-deploy issues but I am not sure what prio the bugs are; I would think they're not super high priority, but I don't want to overrule @carljbowman's opinion on that.)

**Comment by carljbowman** [comment]
@jwzimmer - Thanks for running through and finding these issues. Most of these seems like prio-low, but I would escalate the following issues:

- **1 & 3**: Anything to do with the Nav and Nav Dropdown as those are extremely user facing
- **7**: The issue on the Details Page on Scratch Conference seems really bad, but less related to Typography. @rschamp - any news?

**Comment by jwzimmer** [comment]
@carljbowman - opened new cases for 1 (https://github.com/LLK/scratch-www/issues/537) & 3 (https://github.com/LLK/scratch-www/issues/538), set prio to high (feel free to edit).
(As for 7, I do actually still see the issue where the schedule items are clickable when they have no details, e.g. https://scratch.mit.edu/conference/1118/details (after clearing cache from History tab and doing hard refresh). So I'm leaving case #536 open for that.)
