### ISSUE TITLE
Delete the country options of Taiwan, Macau, and Hong Kong and redirect to China

### ISSUE THREAD

**Issue by 17097231932** [LLK/scratch-www#5334]
# Delete the country options of Taiwan, Macau, and Hong Kong and redirect to China
As we all know, Taiwan, Macau, and Hong Kong are inseparable parts of China and I oppose Hong Kong independence and Taiwan independence. So I suggest deleting the Taiwan, Macau, and Hong Kong country options on scratch.mit.edu, and changing the country of the existing user to China. This can also solve the problem of not being able to access scratch.mit.edu in China, so that ordinary Chinese users can also use scratch to learn programming.
Thank you very much.
>  From a Chinese elementary school student.

**Comment by 17097231932** [comment]
5% of registered users from Scratch are Chinese. We very much hope that Scratch can come to China again. Thank you.

**Comment by apple502j** [comment]
Probaby won't fix: see https://github.com/LLK/scratch-www/issues/4313#issuecomment-673646924

(also IMHO: "Free speech should be respected more than anything else, including 3 million users")

**Comment by charlie-moomoo** [comment]
> I suggest deleting the Taiwan, Macau, and Hong Kong country options on scratch.mit.edu, and changing the country of the existing user to China. This can also solve the problem of not being able to access scratch.mit.edu in China, so that ordinary Chinese users can also use scratch to learn programming.

Even if do this, it still can't be solved.
It was China that blocked the Scratch, which has nothing to do with Scratch itself.

**Comment by GrahamSH-LLK** [comment]
cc @benjiwheeler This is (probably) rejected, I think there's precedent in another issue?

**Comment by Corrupte** [comment]
Regardless of my political views, which support independence for Taiwan and other Chinese-related countries, this can cause a multitude of problems.

1. Controversy
Considering only 5% of Scratch users are from China, considering other independent countries as part of China can be extremely controversial for all other users. Scratch would receive huge backlash for this, and the general consensus is that Taiwan, Hong Kong, and others are independent. 
2. Restrictions
People in, for example, Taiwan, should not be put under Chinese online regulations. If this suggestion were to be put in place, countries like Taiwan would be put under harsh restrictions that don't even follow their laws.

These aren't the only problems, but these are possibly the largest of them. Please consider more thoughtfully before suggesting things based on your own personal political views, and also think about the whole world in general. Are people outside of China going to agree with this in general? No, they will not.
