### ISSUE TITLE
Most of pages display in English with any locales.

### ISSUE THREAD

**Issue by abee2** [LLK/scratch-www#535]
except the top, "Create", "About", and "Help".

**Comment by rschamp** [comment]
Thanks @abee2. In which locales and on which pages are you observing English?  Is there content that was previously translated that you now see as English?

**Comment by abee2** [comment]
This issue was fixed now. Thanks.
I guess this issue related with the web updates on yesterday.
One Japanese scratcher reported me about this issue. I tested it with Japanese and some other locales by the menu of bottom of each page at 12:00 AM JST on June 1st.
However most pages were still displayed in English. I cleared cache and checked it again, but nothing changed. Those pages were already translated in each languages.

**Comment by rschamp** [comment]
Sorry I didn't update this thread. You are correct, we had some issues with localization during the web updates yesterday, but everything should be back to normal now.
