### ISSUE TITLE
Conference, production: Clickable schedule items with no details redirect to "Agenda item not found" page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#536]
Chrome, on production, on the conference pages.

E.g. https://scratch.mit.edu/conference/9/details

Missing item details for the details pages for many schedule items -
When I QA'd the Conference page, there were detail pages when you clicked on the items, or the item wasn't clickable. Now there seem to be no detail pages for some clickable items.

My understanding from #497 was that if there weren't supposed to be detail pages for a given schedule item, it should not be clickable - so I shouldn't get taken to the "Agenda item not found" page even if the schedule item is not intended to have details.

<img width="1061" alt="screen shot 2016-05-31 at 10 59 30 am" src="https://cloud.githubusercontent.com/assets/1320456/15679172/e7374582-271e-11e6-961a-9e3dd721aa9b.png">
<img width="648" alt="screen shot 2016-05-31 at 10 59 05 am" src="https://cloud.githubusercontent.com/assets/1320456/15679171/e735d54e-271e-11e6-829b-941dbd9e92a1.png">
For some items, the detail pages exist... possibly fixed by the purging of the cache stuff @rschamp mentioned? (Or I just didn't click on any schedule items intended to have details initially.)
<img width="822" alt="screen shot 2016-05-31 at 11 56 00 am" src="https://cloud.githubusercontent.com/assets/1320456/15681353/d5501f44-2726-11e6-880d-4e3b0c36c191.png">
I do still get clickable items with no content, e.g. https://scratch.mit.edu/conference/11/details

**Comment by mewtaylor** [comment]
@jwzimmer are you still seeing this by any chance?

**Comment by jwzimmer** [comment]
@mewtaylor Nope! Looks good. : )
