### ISSUE TITLE
Gap above Log In dropdown on Homepage - on production

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#537]
Per conversation with @carljbowman, spin off case for high-prio issue from #532.

**Issue on Homepage**
Chrome

Scratch login on homepage has a gap:
<img width="1016" alt="screen shot 2016-05-31 at 10 37 30 am" src="https://cloud.githubusercontent.com/assets/1320456/15678272/b50fc1ae-271b-11e6-890d-8a25c56215f7.png">

**Comment by jwzimmer** [comment]
Note: when you're not logged in, the menu looks like a speech bubble.
<img width="326" alt="screen shot 2016-06-08 at 4 37 49 pm" src="https://cloud.githubusercontent.com/assets/1320456/15910090/5fdcc646-2d97-11e6-938f-1ca01f2a352b.png">

**Comment by carljbowman** [comment]
@jwzimmer - Thanks for logging this.

The Logged out 'speech' bubble was not affected by the global typography, everything there looks fine on Logged out state. 

**The dropdown when logged in should be attached to the nav.**

![nav_desktop](https://cloud.githubusercontent.com/assets/3409578/15910837/c818b1f4-2d9a-11e6-9980-0b9656f5918c.png)

**Hover on List Item**

![nav_desktop_hover-list-item](https://cloud.githubusercontent.com/assets/3409578/15910849/d59560a2-2d9a-11e6-8420-dbfaeefdfc49.png)
