### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Chaos-emerald** [LLK/scratch-www#5396]
No bug, but I want dark mode.

### Steps to Reproduce

None

### Operating System and Browser

Chrome OS and Chrome

**Comment by Emerald-chaos** [comment]
@benjiwheeler or @BryceLTaylor Check this

**Comment by gosoccerboy5** [comment]
This is already posted on the forums..

**Comment by Shluffy** [comment]
> This is already posted on the forums..
> Also, looks like a duplicate on scratch-gui: [#59](https://github.com/LLK/scratch-gui/issues/59)

that seens ti be only the editor

**Comment by gosoccerboy5** [comment]
> > This is already posted on the forums..
> > Also, looks like a duplicate on scratch-gui: [#59](https://github.com/LLK/scratch-gui/issues/59)
> 
> that seens ti be only the editor

I haven't contributed to Scratch, and am not active at all here, but I suspect it would be better to post there.

**Comment by jemunm378** [comment]
Yeah, this been ask way to many times.

**Comment by BryceLTaylor** [comment]
Duplicate of https://github.com/LLK/scratch-gui/issues/59
