### ISSUE TITLE
Separate "invited but not joined" and "joined" in inviter error

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#5402]
Currently (in scratchr2 studios) inviting someone who was already invited (but did not join) shows the error "username is already a curator of this studio", which is incorrect. Will this be fixed in the migrated version, so that the message is less confusing?

I'd propose "username is already invited to the studio" as the new message. While it is best to have two separate messages for two situations, this message should still apply to cases where the invitee joined the studio.

**Comment by apple502j** [comment]
From what I can tell in #5388 the new message is `"They are already part of the studio."`, so the problem would still exist.

**Comment by kathymakes** [comment]
Hi everyone, this is the proposed design for if someone is already invited to the sutdio: <img width="480" alt="Screen Shot 2021-05-18 at 2 58 03 PM" src="https://user-images.githubusercontent.com/8203939/118708226-7568d680-b7e9-11eb-8dc3-cde876da7f6e.png">

Ideally we can also distinguish a state for if they are already a curator, versus invited, but I think it's fine if we use the state above for 1) invited and 2) invited and accepted, depending what is easier for Eng
<img width="463" alt="Screen Shot 2021-05-18 at 2 58 40 PM" src="https://user-images.githubusercontent.com/8203939/118708293-8a456a00-b7e9-11eb-9cee-e477d2404083.png">

**Comment by benjiwheeler** [comment]
not marking this help wanted because it is within the studios migration domain. Studios folks, if you decide not to implement this, please comment here whether it should be considered help wanted.

**Comment by apple502j** [comment]
Note that solution 1 ("username is already invited to the studio") is just one-liner from what I know. Solution 2 (separate messages) probably requires backend changes which cannot be help wanted (unless Scratch Team decides to open-source scratch-api, of course!)

**Comment by seotts** [comment]
Looks like we fixed this as part of the studio migration, so I'm going to close this.
