### ISSUE TITLE
Studio description always uses textarea; no links get linkified

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#5411]
For those who can edit descriptions, the studio description is an editable textarea, which is expected (and is current behavior.) However, the description also uses textarea for those who can't edit. While it's disabled, it's inconsistent with current behavior.

This also **makes it so that no links are clickable.**

![image](https://user-images.githubusercontent.com/33279053/118281737-845d3980-b508-11eb-8894-32329eedd892.png)

![image](https://user-images.githubusercontent.com/33279053/118281697-78717780-b508-11eb-9cca-bc6040b2a3b8.png)

**Comment by gosoccerboy5** [comment]
Hm. Maybe switch to a \<div> or \<p>?

**Comment by paulkaplan** [comment]
@apple502j yup, it needs to be rendered as a div when not editable. The machinery for linkifying etc can be found in the `lib/decorate-text`, we want options `{usernames: true, hashtags: false, scratchLinks: true}` Happy to review a PR for this.
