### ISSUE TITLE
Change the "LEGO Foundation" text in the footer to "the LEGO Foundation"

### ISSUE THREAD

**Issue by Ihatr1** [LLK/scratch-www#5412]
Pretty small typo, but nevertheless somewhat important to implement as the foundation refers to itself as "The LEGO Foundation" on its homepage.

It also looks kind of weird in the footer, a "the" would make it look much better (quality-wise).

**Comment by gosoccerboy5** [comment]
Can you provide a link to where this typo is? Or provide a screenshot?

**Comment by Ihatr1** [comment]
At the bottom of the home page:
![image](https://user-images.githubusercontent.com/77250850/118299872-ee44f700-b4a6-11eb-81bd-73f6984a94d3.png)

**Comment by gosoccerboy5** [comment]
Oh, ok
