### ISSUE TITLE
text has become blank when following someone

### ISSUE THREAD

**Issue by Marc92020** [LLK/scratch-www#5424]
This also happens when you add a project to a studio, change your what im working on or about me, changing studio descriptions and titles, changing the thumbnail of a studio and inviting, removing and promoting Scratchers in studios. For some reason, it just shows a small green box or red box with no text.

This has been happening for a very long time so someone probably already made an issue for this.

**Comment by GrahamSH-LLK** [comment]
This should be closed. This is an r2 bug, which isn't in this repo, and www studios are in progress, so there's no point in dedicating resources to fixing it.

**Comment by Marc92020** [comment]
ok then

**Comment by mxmou** [comment]
This also affects updating About me and What I'm working on on profiles, which probably won't be migrated to scratch-www soon. The issue should be moved to scratchr2 though.
