### ISSUE TITLE
Persistent homepage element for Teacher Accounts

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#543]
Show persistent homepage element in all logged in Teacher Accounts. 

@carljbowman for more details and designs

**Comment by thisandagain** [comment]
@mewtaylor Can you handle implementation of this after @carljbowman finishes up the design spec?

**Comment by carljbowman** [comment]
@mewtaylor - Attached is a mock with the final copy and button language from yesterday's design meeting. 

![r1_teacher-personal-portal](https://cloud.githubusercontent.com/assets/3409578/15930121/1ee162f4-2e1f-11e6-9ced-11fc9560ab22.png)
