### ISSUE TITLE
Harakou has been removed from the credits page

### ISSUE THREAD

**Issue by Accio1** [LLK/scratch-www#5485]
Harakou has been removed from the credits page. This seems to have happened accidentally during #5078 

### Steps to Reproduce

If you visit the [Credits Page](https://scratch.mit.edu/credits), Harakou's name and profile icon are not present.

### Operating System and Browser

This will happen on any OS and Browser

@benjiwheeler I can fix this if it is help-wanted

**Comment by seotts** [comment]
Thanks for raising this! Removing Harakou was indeed a mistake. We just fixed it in #6085 so I will close this issue.

**Comment by benjiwheeler** [comment]
It looks like it totally happened again, as part of https://github.com/LLK/scratch-www/pull/6688 ! Ack!
