### ISSUE TITLE
Clicking the search icon without searching anything shows an empty page

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-www#5487]
Clicking the magnifying glass icon without enter anything into the search bar shows an empty page (https://scratch.mit.edu/search/projects) instead of just focusing the search bar.

### Steps to Reproduce

Click the icon in the search bar without entering anything into it.

### Operating System and Browser

Edge 90 on Windows

**Comment by AmazingMech2418** [comment]
Is this even really a bug? I mean, the button is meant to search for what you have typed in and if you have nothing typed in, it searches for nothing...

**Comment by Shluffy** [comment]
> Is this even really a bug? I mean, the button is meant to search for what you have typed in and if you have nothing typed in, it searches for nothing...

I think it still should filter that

**Comment by mxmou** [comment]
@AmazingMech2418 The behavior is confusing. One might thing that the icon needs to be clicked to search.

**Comment by carljbowman** [comment]
There are two awkward / confusing behaviors which both stem from not validating if any text has been entered into the text field prior to initiating the search.

When the search field contains no text and...
1. ... clicking the search icon (magnifying glass) results in loading a search page with not results
2. ... pressing the `Return` key to initiate a search while the search field is focused  results in loading a search page with not results

In both cases we should not initiate a search unless there is text in the field.

**Comment by benjiwheeler** [comment]
Sounds like the Scratch Team's intended design is (as @carljbowman said) for the search form to not submit at all (and the icon not to interpret clicks as a submit), if the search box is empty (or only whitespace).

**Comment by jeffalo** [comment]
I can do this one.

**Comment by jeffalo** [comment]
@benjiwheeler I made a PR: #5884.
