### ISSUE TITLE
I Cant Sign In.

### ISSUE THREAD

**Issue by ScratchBotManager** [LLK/scratch-www#5518]
I Cant Sign In To My Account Due To A Bug, Its Getting Annoying.
``
![scratchblocks](https://user-images.githubusercontent.com/84136976/120251800-aa951000-c250-11eb-9180-8a0cb314cf89.png)

**Comment by PoIygon** [comment]
You have to copy the authencation code. Go to the project. Paste it into the comments. Go back and press done

**Comment by CluckCluckChicken** [comment]
I'd use [contact us](https://scratch.mit.edu/contact-us/), instead of a GitHub issue with included blockspam.

**Comment by Shluffy** [comment]
due to a bug? what is the bug?

**Comment by Corrupte** [comment]
Please replicate the bug and maybe even attach a video. If you could describe the bug that would be great. Also, I would describe the steps you took to solving this, like, did you try to reset your password or recover the account? You may have forgotten the password or it could have gotten compromised.

**Comment by FunctionalMetatable** [comment]
[small]When blockspam comes to GitHub...[/small]
Please reset your password by going to [url=https://scratch.mit.edu/accounts/password_reset/]this link[/url], or use [url=https://scratch.mit.edu/contact-us/]Contact us[/url] to get help from the [wiki]Scratch Team[/wiki].

**Comment by SausageMcSauce** [comment]
> [small]When blockspam comes to GitHub...[/small]
> Please reset your password by going to [url=https://scratch.mit.edu/accounts/password_reset/]this link[/url], or use [url=https://scratch.mit.edu/contact-us/]Contact us[/url] to get help from the [wiki]Scratch Team[/wiki].

BBCode does not work on GitHub. It uses Markdown.

**Comment by FunctionalMetatable** [comment]
> > [small]When blockspam comes to GitHub...[/small]
> > Please reset your password by going to [url=https://scratch.mit.edu/accounts/password_reset/]this link[/url], or use [url=https://scratch.mit.edu/contact-us/]Contact us[/url] to get help from the [wiki]Scratch Team[/wiki].
> 
> BBCode does not work on GitHub. It uses Markdown.

I know it was a joke

**Comment by BryceLTaylor** [comment]
Please reach out to us through [contact us](https://scratch.mit.edu/contact-us/) for technical issues you're having.
