### ISSUE TITLE
Change the appearance of avatar outlines

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-www#5558]
Outlines were recently added to comment avatars. There are currently two problems with them:
- The blue color doesn't always look good, depending on the colors used in the avatar.
- Transparent pictures don't look very good:
![image](https://user-images.githubusercontent.com/51849865/120903137-aac44f80-c644-11eb-9146-b677b7ffc488.png)

The second problem could be solved by using a background instead of a `box-shadow`. A solution for the first one could be making the outlines black. I think this would look good:
![image](https://user-images.githubusercontent.com/51849865/120903169-e3fcbf80-c644-11eb-8ce2-c4aa888d3e3b.png)

**Comment by carljbowman** [comment]
This is by design. This style of avatar is becoming the standard across WWW pages.
