### ISSUE TITLE
Add 'for Developers' in the footer

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#556]
currently, this page is linked to from nowhere at all on the scratch site. 

we should link to this new page via the footer:
https://scratch.mit.edu/developers

@carljbowman for specific placement in footer

**Comment by carljbowman** [comment]
@kaschm - Added it to the 'About' Section.

![add-developers-to-footer](https://cloud.githubusercontent.com/assets/3409578/15899402/94bad458-2d69-11e6-9c2d-cf5382348ced.png)
