### ISSUE TITLE
Terms of use  and faq can be confusing together

### ISSUE THREAD

**Issue by Shluffy** [LLK/scratch-www#5566]
As of now, scratch is owned by the scratch foundation. Previously, it was owned solely by llk.

The Terms of use says:

> 5.2 Scratch provides support materials, including images, sounds, video, and sample code, to help users build projects. Support materials are licensed under the Creative Commons Attribution-ShareAlike 2.0 license. You may also use screenshots of Scratch under the same license. Please note that this does not apply to materials that are also trademarked by the Scratch Team or other parties as described in parts 5.4 and 5.5, below.
The Creative Commons Attribution-ShareAlike 2.0 license requires you to attribute any material you use to the original author. When you use Scratch support materials, or screenshots of the Scratch website, please use the following attribution: "Scratch is developed by the Lifelong Kindergarten Group at the MIT Media Lab. See http://scratch.mit.edu."

or 

> When you use Scratch support materials, or screenshots of the Scratch website, please use the following attribution: "Scratch is developed by the Lifelong Kindergarten Group at the MIT Media Lab. See http://scratch.mit.edu."

The faq says:

> We ask that you include a note somewhere in your materials saying: "Scratch is a project of the Scratch Foundation, in collaboration with the Lifelong Kindergarten Group at the MIT Media Lab. It is available for free at https://scratch.mit.edu"

Terms of use should be updated as this can be confusing

**Comment by apple502j** [comment]
Duplicate of #3455 and #3803

**Comment by Shluffy** [comment]
both of those combined.
