### ISSUE TITLE
This isn't an issue...

### ISSUE THREAD

**Issue by banana439monkey** [LLK/scratch-www#557]
but where's the skin found for the client?

**Comment by mewtaylor** [comment]
@banana439monkey I think this is a question more suited to be asked on the [Scratch open source forum](https://scratch.mit.edu/discuss/49/). We try to limit the issues opened here to bugs found with the repo. Do you mind opening a topic in there instead?

**Comment by banana439monkey** [comment]
Done

On 7 June 2016 at 17:41, Matthew Taylor <notifications@github.com> wrote:

> @banana439monkey <https://github.com/banana439monkey> I think this is a
> question more suited to be asked on the Scratch open source forum
> <https://scratch.mit.edu/discuss/49/>. We try to limit the issues opened
> here to bugs found with the repo. Do you mind opening a topic in there
> instead?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LLK/scratch-www/issues/557#issuecomment-224340030>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANHJ7W1eMEOV872NLNNAAzE0QRdrJipwks5qJZ8kgaJpZM4IwHjP>
> .
>



-- 
*Got a problem or a question? Help? Ask away and I'll help! It's not like I
won't. <https://scratch.mit.edu/users/banana439monkey>*

**Comment by mewtaylor** [comment]
cool thanks :)

**Comment by banana439monkey** [comment]
No problem. :)

On 7 June 2016 at 19:26, Matthew Taylor <notifications@github.com> wrote:

> Closed #557 <https://github.com/LLK/scratch-www/issues/557>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LLK/scratch-www/issues/557#event-684774997>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANHJ7XZtst4m86n168tnFch-o_hudE96ks5qJbfwgaJpZM4IwHjP>
> .
>



-- 
*Got a problem or a question? Help? Ask away and I'll help! It's not like I
won't. <https://scratch.mit.edu/users/banana439monkey>*
