### ISSUE TITLE
Scratch Conference page - text updates

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#561]
- On "What to Expect" page, update name: Nichole Pinkard 
- For fusion table, change session types/titles to plural (ex: Morning Workshop to Morning Workshops)
- For fusion table, on Thursday and Friday, for some reason Lunch is at the end of the page (instead of in the middle)

/cc @sleggss

**Comment by mewtaylor** [comment]
1 & 3 have been fixed already, I believe. @sleggss I can handle 2 if you'd prefer me to!

**Comment by sleggss** [comment]
@mewtaylor sure! 

Also I have FAQ wording updates. Should I make a separate issue?

**Comment by mewtaylor** [comment]
@sleggss yes that'd be great!

**Comment by mewtaylor** [comment]
@sleggss I updated the plurality now, so it should show up after the caches expire (in like 20 minutes). If you wouldn't mind checking that they show up correctly, then we can close this issue, I think.

**Comment by sleggss** [comment]
@mewtaylor Thanks Matt. Though it looks like there are some sessions now in the plural category and some in the singular category (ex: there's now an "Afternoon Workshop" category and an "Afternoon Workshops" category in Thursday and Friday...).

**Comment by mewtaylor** [comment]
This is fixed now, so closing
