### ISSUE TITLE
Adding additional sponsor logos to Scratch Conference site

### ISSUE THREAD

**Issue by sleggss** [LLK/scratch-www#563]
@mewtaylor @carljbowman : We need to add No Starch and Intel to the conference website. I have No Starch's logo, but Intel needs us to sign a contract with usage guidelines first (attached here). I'll send Intel's logo as soon as I can.

Intel's guidelines:
[Int_corp_logo_3rdPrty_tlug_111910 (2).pdf](https://github.com/LLK/scratch-www/files/309252/Int_corp_logo_3rdPrty_tlug_111910.2.pdf)

**Comment by sleggss** [comment]
![nostarch_logo_large](https://cloud.githubusercontent.com/assets/8669615/15969332/9a21696c-2efd-11e6-897f-0c767b3244ca.jpg)

**Comment by kaschm** [comment]
@sleggss looks like this still needs info - I'm going to reassign you until we have intel's logo. Hope this is okay!

**Comment by sleggss** [comment]
@kaschm we have the logo! Sent it to Matt earlier but didn't want to post it here because of confidentiality reasons. I'll update the label...

(cc @mewtaylor )
