### ISSUE TITLE
ISOS list

### ISSUE THREAD

**Issue by derter-menter** [LLK/scratch-www#5691]
hi. You need to update the ISO 3166 list scratch uses for countries.

this is because north Macedonia is still Macedonia, the Yugoslavian..: etc.

The new ISO 3166 list just has north Macedonia.

this needs to be updated as Macedonians may get offended and scratch is for everyone.

**Comment by mxmou** [comment]
The list is called ISO 3166.

**Comment by derter-menter** [comment]
> The list is called ISO 3166.

Thanks, will add to OP

**Comment by derter-menter** [comment]
> hi. You need to update the ISO 3166 list scratch uses for countries.
> 
> this is because north Macedonia is still Macedonia, the Yugoslavian..: etc.
> 
> The new ISOS list just has north Macedonia.
> 
> this needs to be updated as Macedonians may get offended and scratch is for everyone.

**Comment by carljbowman** [comment]
This is a duplicate, closing in favor of this issue: https://github.com/LLK/scratch-www/issues/6020
