### ISSUE TITLE
Ownership transfer for studios

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#5693]
There should be a way to transfer the ownership of a studio in case someone leaves Scratch or is simply unable to be online. This is even more important because Scratch Team made a quick (and imo silly) decision to require owner status to edit studio titles or descriptions.

Alternative: studios could be owned by multiple people. Not sure how that works when it comes to deleting, tho.

**Comment by leahcimto** [comment]
With the having multiple owners that sort of relates with having more ranks above manager

**Comment by mxmou** [comment]
> This is even more important because Scratch Team made a quick (and imo silly) decision to require owner status to edit studio titles or descriptions.

I understand why this was done, but the manager limit and the confirmation when promoting a curator are more than enough to achieve the same goal.

**Comment by miles854** [comment]
What about studios that have a need for multiple Scratchers to be able to edit the studios description and title, as well as sometimes a studios thumbnail? Also what about if a the studios owner has gone inactive and not transferred ownership to another Scratcher? This will cause lots of studios to not be updated, and puts a lot more work on the studio owner. Lots of studios used managers to help run a studio, and not being able to edit a studios description and title was a big part of why many of them needed multiple studio managers.

**Comment by BryceLTaylor** [comment]
This feature has been implemented now, thanks!
