### ISSUE TITLE
Studio follower count says 100 instead of 100+ when there are over 100 followers

### ISSUE THREAD

**Issue by leahcimto** [LLK/scratch-www#5695]
When a studio has over 100 followers, it says 100 followers instead of 100+ as expected.

Example from The Forum Helpers which has 439 followers:
![07DEAE15-FB25-4E07-9F16-5B0E5D8EFD17](https://user-images.githubusercontent.com/68165163/124631406-5c77bb80-de51-11eb-8c8b-73c3467f00e9.jpeg)
 

### Steps to Reproduce
1. Go to a studio with over 100 followers
2. Notice it says 100 followers

### Operating System and Browser
Happens on all browsers and operating systems.

**Comment by mxmou** [comment]
> which has 439 followers

493

**Comment by leahcimto** [comment]
Also when there is one follower it says “1 followers”

**Comment by jeffalo** [comment]
the count limit was removed earlier today and now the counts should be able to pass 100, should this issue be closed since it technically no longer exists?

**Comment by leahcimto** [comment]
Yep, closing.
