### ISSUE TITLE
Immediately focus on reply boxes

### ISSUE THREAD

**Issue by gosoccerboy5** [LLK/scratch-www#5701]
When you click "reply" on a comment, focus on the input box that pops up to allow immediate typing. (Apologies I couldn't produce an example video/gif, but the videos weren't working..)

### Steps to Reproduce

I'm not _exactly_ sure, but a simple `element.focus()` call when the reply box is created should do the trick.

### Operating System and Browser

MacOS Big Sur, Chrome 91

**Comment by jeffalo** [comment]
this would match the behaviour of scratchr2 pages where the reply box is autofocused.

**Comment by CodeGuy92** [comment]
agreed

**Comment by mxmou** [comment]
This appears to be a duplicate of #2668, which is fixed.

**Comment by gosoccerboy5** [comment]
epic, thanks @mxmou

**Comment by AksharVivek** [comment]
yeah it would be usefull

**Comment by gosoccerboy5** [comment]
@AksharVivek Why would you reply to this now? The topic is closed.

**Comment by AksharVivek** [comment]
didn't notice it was closed

**Comment by gosoccerboy5** [comment]
its fine

**Comment by AksharVivek** [comment]
oh

**Comment by AksharVivek** [comment]
lol i have no idea how to use github
