### ISSUE TITLE
Mute pop up on studio pages is too big

### ISSUE THREAD

**Issue by leahcimto** [LLK/scratch-www#5728]
This is what the mute pop up looks like when you are on a studio page:
<img width="1432" alt="Screen Shot 2021-07-14 at 11 41 22 AM" src="https://user-images.githubusercontent.com/68165163/125651148-c1320144-738a-46fe-afd6-141ded0a403d.png">

You can't scroll down to get the close/next button.

### Steps to Reproduce

Get muted and open the pop up on a studio page

### Operating System and Browser
macOS 11.4 Firefox 89

By the way, I got muted for sharing a link to the password reset page...

**Comment by leahcimto** [comment]
I think this has been resolved? I can't replicate this anymore.

**Comment by tomlum** [comment]
Yup! this has been resolved, these modals are now scrollable 👍
