### ISSUE TITLE
[Explore/Search] "Load More" sometimes returns number not divisible by 4

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#575]
If there are more projects, it should return 16 more, which it appears to not do sometimes

**Comment by mewtaylor** [comment]
@thisandagain  this appears to be something with the api – when I have seen it happen, it looks as if the last item returned in the previous "Load More" and the first item returned in the current "Load More" are the same. I think we should close the issue in www.

**Comment by thisandagain** [comment]
Sounds good. Mind opening an issue in API?
