### ISSUE TITLE
Project on Explore page doesn't have a Love (Heart) icon & shows up as "Untitled"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#585]
In the games section of the Explore page, a project does not have a Love icon (or the number of loves). It also is called Untitled on the Explore page, but on the project page it does have a name. It appears to be the only one: https://staging.scratch.mit.edu/projects/113921963/.

In Chrome Version 51.0.2704.84 (64-bit) and Safari Version 9.1.1 (11601.6.17).

Another issue from a while ago reported no love or favorite icons: https://github.com/LLK/scratch-www/issues/102.

I noticed this while testing: https://github.com/LLK/scratch-www/pull/577.

<img width="1047" alt="screen shot 2016-06-16 at 4 37 28 pm" src="https://cloud.githubusercontent.com/assets/1320456/16133046/e4c04a48-33e3-11e6-80ae-0417a8c0c5ae.png">
<img width="977" alt="screen shot 2016-06-16 at 4 36 29 pm" src="https://cloud.githubusercontent.com/assets/1320456/16133048/e4c1a528-33e3-11e6-9cf2-848fbef03b01.png">

**Comment by TheGrits** [comment]
@jwzimmer Perhaps not relevant anymore due to the recent update?
