### ISSUE TITLE
Button for curators tab on studio page is slightly shorter than the others

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#5865]
On the studios page, the button for the curators tab is slightly shorter than the other buttons (maybe 2 pixels)

<img width="579" alt="Screen Shot 2021-08-03 at 4 01 27 PM" src="https://user-images.githubusercontent.com/1088291/128078898-0265f01d-9d74-4cb1-b898-b0b54ceffb37.png">

### Steps to Reproduce

Navigate to a studios page
Observe the button

### Operating System and Browser

Mac Chrome

**Comment by mxmou** [comment]
The difference is 1 pixel: the Curators tab icon is rendered at 21x20 pixels, the others are 21x21.
