### ISSUE TITLE
Redirecting to Explore - 403 Forbidden Error

### ISSUE THREAD

**Issue by St19Galla** [LLK/scratch-www#587]
On the homepage of staging.scratch.mit.edu, clicking the "Explore" button from the navbar brings you to this link: https://staging.scratch.mit.edu/explore/projects/all However, when on the [Help](https://staging.scratch.mit.edu/help/) page, clicking the "Explore" button from the navbar brings you to this link: https://staging.scratch.mit.edu/explore/?date=this_month which returns a 403 Forbidden error.
<img width="820" alt="screen shot 2016-06-16 at 9 35 42 pm" src="https://cloud.githubusercontent.com/assets/16446551/16138310/5b652ab2-340a-11e6-9b75-7cff80caa1af.png">
This also happens when going to Explore from any webpages that _do not_ have the updated navbar, such as Discuss, Statistics, and Profile.

This occurs in Safari and Chrome on my Mac.

**Comment by Choco31415** [comment]
I can confirm this bug happens on Safari and Firefox on my Mac.

**Comment by jwzimmer** [comment]
@Choco31415 & @St19Galla - Thank you for pointing this out. However, this isn't exactly a bug, it's a result of how we have set up our testing on staging.scratch.mit.edu. : )
