### ISSUE TITLE
There is too much padding under the reply comment compose box on studio pages

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#5889]
When you reply to a comment, there should be the same amount of padding below the reply compose box as there would be between comments.

Currently there is too much padding.

<img width="959" alt="Screen Shot 2021-08-06 at 11 46 10 AM" src="https://user-images.githubusercontent.com/1088291/128538275-6a07d52d-8fe4-4f72-b5db-22b5e8a3ec7f.png">

### Steps to Reproduce

Navigate to a studio with more than one comment
Click reply on the first comment in the list (top of the list)
Note: the reply box appears and there is too much padding under it

### Operating System and Browser

Mac Chrome

**Comment by carljbowman** [comment]
**Intended Design**

Without specs
<img width="996" alt="Examples" src="https://user-images.githubusercontent.com/3409578/130245958-332d0af3-d47f-4dec-9904-7635381d693e.png">

With
<img width="996" alt="Examples with specs" src="https://user-images.githubusercontent.com/3409578/130246009-828afd61-3794-488f-a036-1af502c95e67.png">
 specs

**Comment by carljbowman** [comment]
Related to https://github.com/LLK/scratch-www/issues/5890

New specs standardize spacing around the various elements within the comment list.
