### ISSUE TITLE
Initial automated test for scratch-www

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#590]
- [ ] Make a simple initial test now that we know what tools we're moving forward with.
    * I have an almost working mocha script that clicks on the Explore link of the navbar (one of the test cases from the Most Important Workflows decided on in #474); need to finish this up and then check it in.
    * May need to return to evaluation steps from https://github.com/LLK/scratch-www/issues/474 if the tools are not what we want, but we shouldn't really have to... I think we do want to use mocha, selenium, saucelabs, various webdrivers, and perhaps chai/ chai-as-promised.

 - [ ] Test tools should be added to requirements.txt
    * Selenium is in the scratchr2 requirements.txt
    * I have been screen-shotting and labelling everything I am installing for future reference.
- [ ] Test architecture
   * Should enable finding tests easily
   * Should mirror existing repo architecture as much as is reasonable
   - [ ] Naming conventions
   * @mewtaylor and I have worked out the basics of this but I'm sure in practice details will come up that we'll have to decide about.

- [ ] First test should be checked into repo
   - [ ] Document how to run, update test
   - [ ] Feedback from team on extensibility, usability, test's output and utility, etc.

**Comment by jwzimmer** [comment]
This is obviously not happening in the next 3 days, so moving to next milestone.

**Comment by thisandagain** [comment]
Moving to September milestone as per discussion with team last week. /cc @rschamp

**Comment by jwzimmer** [comment]
Discussed with @mewtaylor & @rschamp. Current plan is:
- [ ] Revise Most Important Workflows (see https://github.com/LLK/scratch-www/issues/474) so that we can align them with automated tests that don't leave the homepage, for performance reasons
- [ ] Choose one test to automate
- [ ] Automate it using tap and selenium if possible
  - If this doesn't turn out to be a good strategy, re-visit
- [ ] Work with @mewtaylor & @rschamp to commit the test to scratch-www and set up how it will be run against PR's
  - [ ] Document this process
