### ISSUE TITLE
Is there a way to know what version of this package is being used on scratch.mit.edu?

### ISSUE THREAD

**Issue by floehopper** [LLK/scratch-www#5909]
Is there a way to know what version of the `scratch-www` package is being used on scratch.mit.edu? e.g. is there a branch or tag pattern which indicates this? Or is there a way to see if from the scratch.mit.edu website somehow? Thanks.

**Comment by RedGuy12** [comment]
iirc, the version on https://github.com/LLK/scratch-www/tree/master is the live version and is updated periodically.

**Comment by floehopper** [comment]
Thanks 👍  Any idea roughly how often "periodically" means...? Hourly, daily, weekly, ...?

**Comment by RedGuy12** [comment]
it looks like every 1-2 weeks

https://github.com/LLK/scratch-www/pulls?q=author%3Aapp%2Fgithub-actions+master+release+is%3Apr

**Comment by floehopper** [comment]
That's great - thank you! 👍
