### ISSUE TITLE
Document <title>'s aren't localized

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#592]
Since this is inserted via `routes.json` and then directly into the template, it's outside of our localization flow.

**Comment by rschamp** [comment]
We should investigate what implications this has for SEO.

**Comment by thisandagain** [comment]
Without `hreflang` tags and unique URLs for each page by language, doing this will harm our search relevance:

https://support.google.com/webmasters/answer/189077?hl=en
https://help.localizejs.com/docs/search-engine-optimization-seo
