### ISSUE TITLE
Entering a project link containing a comment ID when adding to a studio

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-www#5928]
When a link to a project comment is entered into the Add Projects input, the comment ID is treated as a project ID.

### Steps to Reproduce

Enter the following URL into the project URL input in a studio you curate:
https://scratch.mit.edu/projects/369597049#comments-104

Project 104 and not 369597049 is added.

### Operating System and Browser

Any, tested on Firefox 91 on Android

**Comment by BryceLTaylor** [comment]
I'm going to close this issue in favor of #5950.
