### ISSUE TITLE
Comment reply input field should not be indented under a reply

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-www#5951]
When replying to a reply comment, the text field becomes indented a third time. It appears as though the reply to a reply will become another layer nested / indented in the reply chain.

**Current State**
<img width="967" alt="Screen Shot 2021-08-19 at 10 39 44 AM" src="https://user-images.githubusercontent.com/3409578/130088585-4ee8e317-9e91-47f0-a7b8-84ec5a7b3062.png">

**Intended Design**
<img width="889" alt="Screen Shot 2021-08-19 at 10 40 23 AM" src="https://user-images.githubusercontent.com/3409578/130088697-ca2d7f32-da2e-40c2-b723-8eb1f701e135.png">

**Comment by locness3** [comment]
This is a problem on small screens.

**Comment by locness3** [comment]
nice...
