### ISSUE TITLE
Add RTL support to studio pages

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#5952]
Currently, switching to a language that is written Right to Left does not change the layout of the studio page.  In those languages we should switch the orientation of the page.

![Screen Shot 2021-08-19 at 10 56 03 AM](https://user-images.githubusercontent.com/1088291/130091429-d405ff47-02fb-4c42-a892-802476ab4b03.png)

The image above is a working sketch and it needs more more speccing out.

**Comment by chrisgarrity** [comment]
The studio layout uses flexbox, so all that's needed to handle RTL is add/remove the `dir="rtl"` attribute to the view div appropriately. Here's a screenshot of adding the dir attribute to the view div:
![Screen Shot 2021-08-19 at 1 44 04 PM](https://user-images.githubusercontent.com/399209/130118293-1dc225a3-e54d-4ecc-8b47-5d9bc3aa78d7.png)
The other thing that looks like it may need adjusting is some of the padding (e.g. between the label and icon on buttons). Using padding-inline-start/end would be better than padding-left/right, but we'd need to check that the attribute is supported in all browsers.

**Comment by apple502j** [comment]
It is supported in every major browser except for Legacy Edge, though it will require prefixes before Safari 12.1, Cr69 and FF71.

**Comment by BryceLTaylor** [comment]
We can do a first pass implementing @chrisgarrity 's suggestion.  @apple502j if you're interested in working on this, we would appreciate the help.

**Comment by LankyBox01** [comment]
# Compatibility Table
PC Compatibility:
| Chrome | Edge | Firefox | Internet Explorer | Opera | Safari |
| ------- | ------- | ------- | ------- | ------- | ------- |
| ✅Full | ✅79 | ✅Full | ❌None | ✅Full | ✅Full |

Mobile compatibility:
| WebView (Android) | Chrome (Android) | Firefox for Android | Opera (Android) | Safari (IOS) | Samsung Internet |
| ------- | ------- | ------- | ------- | ------- | ------- |
| ✅Full | ✅Full | ✅Full | ✅Full  | ✅Full | ✅Full |

**Comment by LankyBox01** [comment]
For `dir="rtl"`

**Comment by LankyBox01** [comment]
# Compatibility Table for `dir="rtl"`
## PC Compatibility:
| Chrome | Edge | Firefox | Internet Explorer | Opera | Safari |
| ------- | ------- | ------- | ------- | ------- | ------- |
| ✅Full | ✅79 | ✅Full | ❌None | ✅Full | ✅Full |

## Mobile compatibility:
| WebView (Android) | Chrome (Android) | Firefox for Android | Opera (Android) | Safari (IOS) | Samsung Internet |
| ------- | ------- | ------- | ------- | ------- | ------- |
| ✅Full | ✅Full | ✅Full | ✅Full  | ✅Full | ✅Full |
