### ISSUE TITLE
Create Illustrations for Step 10 in Teacher Join Flow

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-www#597]
https://github.com/LLK/scratch-www/issues/409 to move forward without illustrations.
- [ ] 'Confirm' Email illustration
- [ ] 'Wait for Approval' illustration
- [ ] 'Get Started with Resources' illustrations 

![r3 1_teacher-join-flow final](https://cloud.githubusercontent.com/assets/3409578/15748003/1efbe224-28ab-11e6-8572-b19e4238218a.png)

**Comment by thisandagain** [comment]
@carljbowman Moving to next iteration.

**Comment by kaschm** [comment]
@carljbowman ping! do you think it will be possible to get these in time to develop for the freeze?
