### ISSUE TITLE
Refactor `frameless.scss` to use `rem` for columns

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#598]
currently, our `$cols` can potentially have different translations into pixel values depending on what the relative `font-size` in within the element that's getting a width or column value. Given the way we prototype responsive design and how it affects grids, it seems more appropriate to use `rem` for the unit of `frameless` so that columns stay at a consistent pixel value at all levels of html hierarchy

**Comment by thisandagain** [comment]
As per last conversation let's hold off on this until @carlbowman has time to work through this with us holistically.
