### ISSUE TITLE
Make "commenting is off" message on projects and profiles resemble the studio page message

### ISSUE THREAD

**Issue by leahcimto** [LLK/scratch-www#6030]
When studio comments are turned off, the following message is shown:
<img width="877" alt="studio comments" src="https://user-images.githubusercontent.com/68165163/132259812-902a52f4-34db-4f9d-a474-fb7c4de7b2ce.png">

On projects, it shows:
<img width="698" alt="project page comments" src="https://user-images.githubusercontent.com/68165163/132259855-02a4d36a-6596-4ac2-8df7-a3acaf0f59fa.png">

Same with profile comments:
<img width="917" alt="profile comments" src="https://user-images.githubusercontent.com/68165163/132259874-f7a04c4f-62d2-4fef-86f9-a6097a2e2689.png">

The message shown on studio pages should be changed to "Sorry, comment posting has been turned off for this studio."

<br>

This should be pretty easy to fix.  I'm pretty sure [this](https://github.com/LLK/scratch-www/blob/0646261af15e3b631ea0b603db136ff95d015242/src/views/studio/l10n.json#L116) could be edited to say "Sorry, comment posting has been turned off for this studio.", or [this](https://github.com/LLK/scratch-www/blob/0646261af15e3b631ea0b603db136ff95d015242/src/views/studio/studio-comments-not-allowed.jsx#L6) could be edited to say `<FormattedMessage id="studio.comments.turnedOff" />`.
### Steps to Reproduce

1. Go to a studio with comments turned off
2. Notice that the message shown is inconsistent with project and profile pages

### Operating System and Browser

macOS 11.5.2, Firefox 91.0.2

**Comment by LankyBox01** [comment]
agreed :shipit:

**Comment by Naleksuh** [comment]
I mentioned this before the feature to turn off comments was merged and people acknowledged it was something to fix eventually, but nobody cared too much.

**Comment by LankyBox01** [comment]
https://github.com/LLK/scratch-www/blob/develop/src/views/studio/studio-activity.jsx#L143

**Comment by BryceLTaylor** [comment]
The studio page message is what we want to go with.  Thanks for pointing this out @leahcimto !

**Comment by Naleksuh** [comment]
@BryceLTaylor I see you added "help wanted" here. However, this change would require an accompanying change to scratchr2 which is private so I can't do that. Can you confirm when it is changed there and I can PR to change it here?

**Comment by BryceLTaylor** [comment]
The profile page would require a Scratchr2 change, but it looks like the Project page should be able to be handled in www alone.  If a particular change needs to be made in Scratchr2 to make the front end change work, you could file that as a separate issue.

**Comment by Naleksuh** [comment]
@BryceLTaylor Yeah, that's what I meant. It should be just as simple as changing the translation string, so can anyone with access to scratchr2 do both?

**Comment by derter-menter** [comment]
> The studio page message is what we want to go with. Thanks for pointing this out @leahcimto !

Why? It just looks ruder without the "sorry". The profile and project one still is the statement, so why?

**Comment by leahcimto** [comment]
@BryceLTaylor I think I have a simple fix in my fork. Could I submit a PR?

**Comment by TheRobotCodingMan** [comment]
@leahcimto
I agree with him.
