### ISSUE TITLE
Language dropdown doesn't keep state

### ISSUE THREAD

**Issue by technoboy10** [LLK/scratch-www#605]
When selecting another language besides English on the Staging site, the site reloads and changes language, but the dropdown language menu at the bottom of the page defaults to English, preventing value change events from firing (which means that you can't change back to the en locale).

<img width="970" alt="screenshot 2016-06-24 09 54 08" src="https://cloud.githubusercontent.com/assets/3019167/16339649/d0c147ea-39f1-11e6-8c90-13104949ff38.png">

**Comment by rschamp** [comment]
Hm, it's also pretty large. Is that intentional @mewtaylor @carljbowman?

**Comment by mewtaylor** [comment]
It's fallout from styling the `select` for teacher registration, so it just needs a bit of reformatting I think, now that we actually do custom styling on selects.
