### ISSUE TITLE
No content in teacher banner when logged in as a teacher

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#611]
Locally I see this when I'm logged in as an educator:

![image](https://cloud.githubusercontent.com/assets/1512021/16342335/906b6c08-39ff-11e6-8ef2-18f1e8caec6d.png)

Labeling "staging" but not entirely accurate since you can only test this locally atm.

**Comment by mewtaylor** [comment]
fixed in https://github.com/LLK/scratch-www/issues/614
