### ISSUE TITLE
User has broken profile pic on homepage > What's Happening but not elsewhere - on production

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#613]
@christanbalch (using Chrome) reported of user Pepestan_Gaming:

> Random broken icon, only shows up in the What's Happening section (his icon is fine everywhere else).

Broken icon:
<img width="507" alt="screen shot 2016-06-24 at 2 41 07 pm" src="https://cloud.githubusercontent.com/assets/1320456/16347268/bed60f2a-3a19-11e6-8cc5-fa67152a39e9.png">

Normal icon:
In comments section
<img width="287" alt="screen shot 2016-06-24 at 2 42 40 pm" src="https://cloud.githubusercontent.com/assets/1320456/16347402/8651bc34-3a1a-11e6-8a92-631044ecd6fb.png">
On profile page
<img width="195" alt="screen shot 2016-06-24 at 2 41 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/16347401/864f6a9c-3a1a-11e6-8ed0-b2a5d999de59.png">

I followed Pepestan_Gaming and saw the same broken thumbnail on my What's Happening section (in Chrome):
<img width="471" alt="screen shot 2016-06-24 at 2 49 22 pm" src="https://cloud.githubusercontent.com/assets/1320456/16347493/000091cc-3a1b-11e6-89bb-a2c3aa825a45.png">

And in Firefox 47.0:
<img width="502" alt="screen shot 2016-06-24 at 2 51 25 pm" src="https://cloud.githubusercontent.com/assets/1320456/16347537/39a06c4a-3a1b-11e6-8b19-1ca6f2d93804.png">

**Comment by TheGrits** [comment]
Probably related to #187

**Comment by rschamp** [comment]
Tracking in #187
