### ISSUE TITLE
Homepage login's spacing is too large; gaps between Username & Password fields - on staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#618]
Repro:
- Go to the homepage on staging
- Click on Sign In if you are not signed in (otherwise log out and then click Sign In)
- Note that the gaps between the Username and Password text and their fields are too large

<img width="279" alt="screen shot 2016-06-28 at 2 56 31 pm" src="https://cloud.githubusercontent.com/assets/1320456/16428672/eca5b6a6-3d40-11e6-8f2a-1ff4fa4aec4c.png">

**Comment by mewtaylor** [comment]
fixed in https://github.com/LLK/scratch-www/issues/631
