### ISSUE TITLE
Teacher FAQ button in Teacher banner leads to 404

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#625]
/cc @mewtaylor 

Re https://github.com/LLK/scratch-www/pull/558:
- **The button for Teacher Account FAQ should take me to FAQ**
  - Right now, the button redirects to the 404 page
<img width="910" alt="screen shot 2016-06-29 at 11 05 32 am" src="https://cloud.githubusercontent.com/assets/1320456/16457472/a3c1be72-3de9-11e6-886a-217e0895251d.png">

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/629
