### ISSUE TITLE
Teacher Banner loses content but remains (purple bar) after logging out of teacher account

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#626]
/cc @mewtaylor 

Re https://github.com/LLK/scratch-www/pull/558
Chrome Version 51.0.2704.106 (64-bit)
- **The banner should not be present when I log out after logging in as a teacher**
  - The banner loses its content but still appears (it goes away after you refresh the page)
<img width="1019" alt="screen shot 2016-06-29 at 11 09 56 am" src="https://cloud.githubusercontent.com/assets/1320456/16457585/0f62897c-3dea-11e6-9899-c9036b20d2f6.png">

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/issues/640
