### ISSUE TITLE
Add app privacy policy to the website

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#6297]
The app stores need to be able to link to a version of the privacy policy that corresponds to the privacy policy in the apps.

The route should be `/privacy_policy/apps`

The apps privacy policy view should be based on the website privacy_policy view.

The [copy for the apps privacy policy](https://docs.google.com/document/d/1CknRE-CTjpxnA8kXEPOWibBM91tx-pnk0HKm19zTiOw/edit?usp=sharing). _Note this document is not currently public, and therefore this is not a help wanted issue_

It should be set up so that the content can be translated (a new l10n file).

**Comment by apple502j** [comment]
Website privacy policy is not translated, why translate this?

**Comment by chrisgarrity** [comment]
@apple502j the policy around translating (or not) is evolving, and we've decided the new policy for the apps should be translated. The same policy is included in the android app, and will need translation.

**Comment by chrisgarrity** [comment]
Resolved in #6355

**Comment by apple502j** [comment]
@chrisgarrity The privacy policy is not shown on Transifex for some reason;

![image](https://user-images.githubusercontent.com/33279053/148989195-09abdbdb-223e-4d2e-bcff-a74aa2720cf6.png)
