### ISSUE TITLE
Annual Report follows incorrect username format

### ISSUE THREAD

**Issue by jeffalo** [LLK/scratch-www#6305]
![image](https://user-images.githubusercontent.com/40470736/142032725-6e1d1838-799b-4ba0-a196-280d27b1029b.png)

### Expected Behavior

The annual report should use the @ sign to denote usernames. (@STORMPRIMEX), as with the rest of the site. Perhaps these should also be links to user profiles?

### Actual Behavior

The annual report uses u/ to indicate usernames (u/STORMPRIMEX), similarly to reddit. I've never seen this format used anywhere else on Scratch.

### Steps to Reproduce

1. Go to 'https://scratch.mit.edu/annual-report'
2. Scroll down to a project embed
4. See a username

**Comment by jeffalo** [comment]
![image](https://user-images.githubusercontent.com/40470736/142035831-d02ea6eb-2617-40e8-b8db-c27ba3e1bdbd.png)

Looks like they aren't all Scratch users..? u/cellie doesn't seem like they are a Reddit user or Scratch user.

**Comment by ninjamar** [comment]
> cellie
typo?

**Comment by derter-menter** [comment]
I don't see how this got "low severity" when it is an extreme professionalism issue. Does scratch want to look good?
Should be fixed quickly

**Comment by Quantum-Codes** [comment]
> Looks like they aren't all Scratch users..? u/cellie doesn't seem like they are a Scratch user or a Reddit user (the only platform I know that uses u/username)

They are Scratch users, instead of prefixing "@", they prefixed "u/". Cellie and stormprimex users exist.
https://scratch.mit.edu/users/cellie/
https://scratch.mit.edu/users/stormprimex/

**Comment by locness3** [comment]
lmao? How would this happen?

**Comment by derter-menter** [comment]
> Is this issue still relevant?

no as it was fixed (on my end I get correctly formatted usernames)

**Comment by mxmou** [comment]
> > Is this issue still relevant?
> 
> no as it was fixed (on my end I get correctly formatted usernames)

It wasn't: https://scratch.mit.edu/annual-report/2020

**Comment by derter-menter** [comment]
> 

oops, thought it meant the 2021 annual report.
