### ISSUE TITLE
Scratch Is Not Found

### ISSUE THREAD

**Issue by reeceypie** [LLK/scratch-www#6307]
I tried to load Scratch, but it wont open.
![image](https://user-images.githubusercontent.com/66112471/142054356-2bb04d81-d06c-48d0-8ed5-9cc5d8cc9122.png)

To reproduce, just go to scratch.mit.edu

**Comment by Marc92020** [comment]
try going to scratch again
it might be fixed now

**Comment by jeffalo** [comment]
this issue seems to be resolved now.

**Comment by BryceLTaylor** [comment]
Thank you.  This was fixed.
