### ISSUE TITLE
New Scratcher to Scratcher Onboarding Flow Update

### ISSUE THREAD

**Issue by kmlshalf** [LLK/scratch-www#6328]
The current New Scratcher to Scratcher Onboarding flow is out of date with the new community guidelines and needs to be moved out of scratchr2. This update is to remake the flow to match scratch-www UI and put in the new content, along with some additional improvements. 

<img width="707" alt="Screen Shot 2021-11-22 at 9 31 18 AM" src="https://user-images.githubusercontent.com/17713728/142879329-ecaf3e4d-5f29-4870-98b3-9a6e6aedcf47.png">

### Links
[Figma](https://www.figma.com/file/B1G6u6UIuHV7bJEfzIpSVY/Scratcher-Onboarding-Flow?node-id=262%3A7152)
[Images](https://drive.google.com/drive/folders/1O7_cSV9BYTsc2YA_dcj2HLFpMBl9F9kT?usp=sharing)

**Comment by devxan** [comment]
@kmlshalf the Figma file and google drive folder are both not shared with anyone on the internet. Please change this.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/57809064/143049376-c44a35be-1425-4cf5-8e5d-cba1bfd840a4.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/57809064/143049745-35cab37a-b5c2-4868-aada-354e9d5b4060.png">

**Comment by Naleksuh** [comment]
The issue with this though is that the profile page itself is scratchr2. I don't think it would make sense to load scratch-www content from scratchr2 content. Wouldn't this change be better to make with a different profile page? (that is, if anything needs to be changed- the dialog has always been similar but different from the guidelines itself)

**Comment by kchadha** [comment]
@tomlum is this issue fixed now? If so, can you link to the PR that resolved it and close the issue?

**Comment by tomlum** [comment]
Fixed with https://github.com/LLK/scratch-www/pull/6500
