### ISSUE TITLE
Host transfer activity leads to incorrect user profile

### ISSUE THREAD

**Issue by LegoManiac04** [LLK/scratch-www#6367]
### Expected Behavior

The host transfer message in the studio Activity tab has two links, one that links to the profile of the user being made host, and the other to the user that was previously host.

### Actual Behavior

Both clickable usernames lead to the profile of the person being made host. (i.e. "**[ScratchCat](https://scratch.mit.edu/users/ScratchCat/)** was made the studio host by **[ceebee](https://scratch.mit.edu/users/ScratchCat/)**")

### Steps to Reproduce

1. Make a different user Host in a studio
2. Go to the activity tab
3. Click the username of the user that was the prior host
4. See that it leads to the incorrect profile

**Comment by hello-smile6** [comment]
Could my PR be merged? I made it first.
