### ISSUE TITLE
Logging in on a 2nd Device while the 1st deviced is signed in causes the login to fail causes the GUI to break.

### ISSUE THREAD

**Issue by DXLB-Dichter** [LLK/scratch-www#6378]
### Expected Behavior

Signs into the site. 2nd device logs out

### Actual Behavior

Fails to sign into the site, can't log in. When selecting an another page, the GUI breaks

### Steps to Reproduce

1. Go to 'https://scratch.mit.edu/login 
2. Sign into device 1
3. Sign into device 2
4. Resign into device 1
5. Move to any page

### System Details

HP Chromebook 14A G5
Chrome OS Version 94.0.4606.124 (64bit)

**Screenshots**
![Screenshot 2021-12-14 11 46 00](https://user-images.githubusercontent.com/80650273/146052205-8b9d39d8-4efc-4c2d-96db-eb5359892a71.png)
![Screenshot 2021-12-14 11 48 31](https://user-images.githubusercontent.com/80650273/146052393-3ba1f1e6-b83d-4fa8-9491-79c513f955ed.png)

**Comment by LegoManiac04** [comment]
Scratch seems to be having a lot of issues right now, so I have a feeling that's why you're having these issues right now.
