### ISSUE TITLE
Can't log into Scratch with some user agents

### ISSUE THREAD

**Issue by MystPi** [LLK/scratch-www#6395]
### Expected Behavior

A user should be able to log into Scratch with any user agent. https://scratch.mit.edu/robots.txt

### Actual Behavior

With a certain user agent (shown below) a user is not able to log into Scratch. It also shows a message along the lines of "an error occured".

### Steps to Reproduce

1. Set your useragent to `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ninetails/2.2.0 Chrome/96.0.4664.45 Electron/16.0.0 Safari/537.36`.
2. Log in to Scratch (or try to at least).

One interesting thing I found is that if you change the `x86_64` part of the UA, it will work.

**Comment by hello-smile6** [comment]
Testing with `curl/7.55.1` UA.

**Comment by hello-smile6** [comment]
Throwing this UA at Scratch's authentication. Let's see how this goes.
![image](https://user-images.githubusercontent.com/73048226/146687674-00059705-c0b3-42cd-b237-bcc74a69b549.png)

**Comment by hello-smile6** [comment]
> Throwing this UA at Scratch's authentication. Let's see how this goes. ![image](https://user-images.githubusercontent.com/73048226/146687674-00059705-c0b3-42cd-b237-bcc74a69b549.png)

Result: failed. I'll try signing in with elinks in a VM.

**Comment by hello-smile6** [comment]
Booting Arch Linux VM right now.

**Comment by CocoTheMii** [comment]
Can reproduce on both Scratch-WWW and ScratchR2 pages.

Additionally, attempting to go to https://scratch.mit.edu/login returns the message:
`[{"username": "", "num_tries": 0, "success": 0, "msg": "Something went wrong", "messages": [], "id": null}]`

**Comment by hello-smile6** [comment]
> Can reproduce on both Scratch-WWW and ScratchR2 pages.
> 
> Additionally, attempting to go to https://scratch.mit.edu/login returns the message: `[{"username": "", "num_tries": 0, "success": 0, "msg": "Something went wrong", "messages": [], "id": null}]`
> 
> The UA was applied using the Network Conditions tool in Microsoft Edge 96.0.1054.62 on Windows 11 build 22000.376.

Does it work with my configuration?

**Comment by CocoTheMii** [comment]
> > Can reproduce on both Scratch-WWW and ScratchR2 pages.
> > 
> > Additionally, attempting to go to https://scratch.mit.edu/login returns the message: `[{"username": "", "num_tries": 0, "success": 0, "msg": "Something went wrong", "messages": [], "id": null}]`
> > 
> > The UA was applied using the Network Conditions tool in Microsoft Edge 96.0.1054.62 on Windows 11 build 22000.376.
> 
> Does it work with my configuration?

It does not. All three pages tested still return errors.

**Comment by hello-smile6** [comment]
> > > Can reproduce on both Scratch-WWW and ScratchR2 pages.
> > > Additionally, attempting to go to https://scratch.mit.edu/login returns the message: `[{"username": "", "num_tries": 0, "success": 0, "msg": "Something went wrong", "messages": [], "id": null}]`
> > > The UA was applied using the Network Conditions tool in Microsoft Edge 96.0.1054.62 on Windows 11 build 22000.376.
> > 
> > 
> > Does it work with my configuration?
> 
> It does not. All three pages tested still return errors.

Okay. I wonder how you can detect a web browser that's pretending to be a CLI download program...

**Comment by colbygk** [comment]
>A user should be able to log into Scratch with any user agent. https://scratch.mit.edu/robots.txt

[citation needed]

**Comment by hello-smile6** [comment]
> A user should be able to log into Scratch with any user agent. https://scratch.mit.edu/robots.txt

Actually, `robots.txt` is a _guideline_ for search engines and web crawlers. Additionally, any entity that is not a web browser should respect `robots.txt`. Therefore, as `/site-api` is disallowed in `robots.txt`, there is plenty of justification for unrecognized UAs to be blocked, such as cURL, which could potentially be used (in the form of libcurl) for a bot, and other abnormal UAs. At least, that's what my opinion on the subject is.

**Comment by hello-smile6** [comment]
> > A user should be able to log into Scratch with any user agent. https://scratch.mit.edu/robots.txt
> 
> Actually, `robots.txt` [is a _guideline_ for search engines and web crawlers](https://en.wikipedia.org/w/index.php?title=Robots_exclusion_standard&oldid=1057231261). Additionally, any entity that is not a web browser should respect `robots.txt`. Therefore, as `/site-api` is disallowed in `robots.txt`, there is plenty of justification for unrecognized UAs to be blocked, such as cURL, which could potentially be used (in the form of libcurl) for a bot, and other abnormal UAs. At least, that's what my opinion on the subject is.

In fact, `/login` should probably be added to the `robots.txt "Disallow" list for all UAs.
