### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by LankyBox01** [LLK/scratch-www#6416]
### Expected Behavior
In the explore page, if the language is set to romanian, the title of the page should be "Explorează".

### Actual Behavior

The title is Exploreaza instead, without the accent.
And it's not just the title, there are a lot of missing accents in multiple pages.

### Steps to Reproduce
https://scratch.mit.edu/explore/projects/all

### System Details
No.

**Screenshots**
No.

**Comment by RedGuy12** [comment]
You can fix them yourself by going [here](https://www.transifex.com/llk/public/) and pressing "Help Scratch Team translate content.

**Comment by LankyBox01** [comment]
@RedGuy12 i cant make a transifex account.

**Comment by RedGuy12** [comment]
why not

**Comment by LankyBox01** [comment]
@RedGuy12 I'm not 18

**Comment by RedGuy12** [comment]
you don't need to be?

**Comment by BryceLTaylor** [comment]
@chrisgarrity this translation might need updating in Transifex.  I'm closing this issue here, though.
