### ISSUE TITLE
Phone Number error message no longer displaying

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#642]
appears to not get any content in the error message anymore.

**Comment by thisandagain** [comment]
Confirmed:

![image](https://cloud.githubusercontent.com/assets/747641/16501707/ba67f228-3ed8-11e6-8a80-b0954fac360d.png)

**Comment by rschamp** [comment]
@mewtaylor Maybe to do with the change to `validationHOCFactory`?

**Comment by mewtaylor** [comment]
@rschamp that's my assumption – haven't taken a deeper look yet

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/653
