### ISSUE TITLE
CE-310 Title Text on EV3 Page Overlaps

### ISSUE THREAD

**Issue by leahcimto** [LLK/scratch-www#6423]
### Expected Behavior
The text "EV3" in the title should be next to "LEGO MINDSTORMS"

### Actual Behavior
Text "EV3" overlaps with body text in fullscreen mode.

### Steps to Reproduce
1. Go to https://scratch.mit.edu/ev3/
2. Notice that the text EV3 overlaps with the body text

### System Details
macOS 11.5.2, Firefox 95.0.2, MacBook Air

**Screenshots**

<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/68165163/148123574-a9a08387-aee0-46cb-ba9c-29b4435d6558.png">

**Comment by GrahamSH-LLK** [comment]
Seems to be a firefox only bug

**Comment by mxmou** [comment]
Could be fixed by adding `width: 100%` to the `h1`.

**Comment by kccuber-scratch** [comment]
This happens on Windows too
![image](https://user-images.githubusercontent.com/92891642/173246310-c289f878-8fbb-4888-89e2-116884a47c25.png)

Firefox 100, Windows 10

**Comment by GrahamSH-LLK** [comment]
> Hi @GrahamSH-LLK @kccuber-scratch I'm a computer science student, and we are currently working towards contributing to an open source GitHub for one of our classes. I would love to take this issue and work towards solving it!

Hi @edelfino11, sorry for the misunderstanding. Kcuber and I are not members of the scratch team, we're actually members of the scratch community. This issue is not marked [help wanted](https://github.com/LLK/scratch-www/labels/Help%20wanted) so the scratch team _probably_ won't accept PRs for this, but you could try. If you want to try your luck I'd say ping somebody who has assigned labels to an issue recently.

**Comment by edelfino11** [comment]
Hi @GrahamSH-LLK, I see! Sorry about that.

**Comment by edelfino11** [comment]
Hi @chrisgarrity, I created a small PR to fix this issue! I know it is not on the help wanted list, but it's a simple fix that can impact those using Firefox. (I was let known by others in this issue to tag an actual member of the scratch team, so here we are!) Thank you for your time!

**Comment by benjiwheeler** [comment]
Thanks, @edelfino11 -- we should have marked this help wanted!

**Comment by benjiwheeler** [comment]
Resolved by https://github.com/LLK/scratch-www/pull/7291
