### ISSUE TITLE
After logging out of staging, I can't log back in

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#643]
As mentioned in dev slack chat. @rschamp mentioned it might be caused by something @mewtaylor merged earlier today?

Staging, Chrome

- I was using staging as a student account
- I logged out
- The homepage is in the default state (no way to sign in)
- I can seemingly get around it by logging in from an "old" page (scratchr2) e.g. Discuss

<img width="1231" alt="screen shot 2016-06-30 at 2 50 19 pm" src="https://cloud.githubusercontent.com/assets/1320456/16500542/128ce72a-3ed3-11e6-8679-b0466c531a2c.png">
<img width="1063" alt="screen shot 2016-06-30 at 2 49 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/16500541/1288d8b0-3ed3-11e6-8e03-e94471dd7080.png">

After logging in from the Discuss page & returning to the homepage:
<img width="450" alt="screen shot 2016-06-30 at 3 00 10 pm" src="https://cloud.githubusercontent.com/assets/1320456/16500607/6b46b882-3ed3-11e6-994b-4c2ff582176f.png">

**Comment by thisandagain** [comment]
Confirmed.

**Comment by mewtaylor** [comment]
fixed in https://github.com/LLK/scratch-www/pull/644
