### ISSUE TITLE
Node version requirement in readme is incorrect

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-www#6442]
### Expected Behavior

The readme would accurately specify a node.js version needed to build scratch-www.

### Actual Behavior

It says that node version 8 or higher is required. I don't think this is correct: trying to run `npm install` on WSL with node 8 installed shows the following error:
```
> chromedriver@96.0.0 install /path/to/scratch-www/node_modules/chromedriver
> node install.js

/path/to/scratch-www/node_modules/del/node_modules/globby/index.js:28
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/scratch-www/node_modules/del/index.js:4:16)
```

Node 16 and later doesn't work either because the `node-sass` package only added node 16 support in version 6.0.0, but scratch-www needs version 4.

**Comment by hello-smile6** [comment]
> ### Expected Behavior
> The readme would accurately specify a node.js version needed to build scratch-www.
> 
> ### Actual Behavior
> It says that node version 8 or higher is required. I don't think this is correct: trying to run `npm install` on WSL with node 8 installed shows the following error:
> 
> ```
> > chromedriver@96.0.0 install /path/to/scratch-www/node_modules/chromedriver
> > node install.js
> 
> /path/to/scratch-www/node_modules/del/node_modules/globby/index.js:28
>         } catch {
>                 ^
> 
> SyntaxError: Unexpected token {
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:617:28)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/path/to/scratch-www/node_modules/del/index.js:4:16)
> ```
> 
> Node 16 and later doesn't work either because the `node-sass` package only added node 16 support in version 6.0.0, but scratch-www needs version 4.

What's the minimum version for the `globby` package? That's where the error occurs.
