### ISSUE TITLE
I can't log in on staging in IE?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#654]
This could be user error? I am on IE11 on Win7 Virtual Machine Version 20141027.

I tried to sign in as jwzimmer1990; after pressing the Sign In button the first time, the homepage returned to Signed Out state, and no projects/ studios loaded. I tried to sign in again... the Sign In button didn't close the log-in dropdown (as shown in gif). I cleared my cookies and tried again - after pressing the Sign In button the first time, the homepage returned to Signed Out state, and no projects/ studios loaded.

<img width="782" alt="screen shot 2016-06-30 at 5 08 14 pm" src="https://cloud.githubusercontent.com/assets/1320456/16504310/5a72450a-3ee5-11e6-9f90-c1d79e3c8603.png">
![out](https://cloud.githubusercontent.com/assets/1320456/16504309/5a716464-3ee5-11e6-981f-b47c816b2061.gif)

**Comment by cwillisf** [comment]
I tried in Internet Explorer 11.420.10586.0 on Windows 10 and I was not able to log in:
![image](https://cloud.githubusercontent.com/assets/7019101/16524756/68b3e1ea-3f77-11e6-808e-978f64b73990.png)

**Comment by cwillisf** [comment]
It worked correctly in Edge, though.

**Comment by jwzimmer** [comment]
I can't log in on IE 11 on a Win 8.1 VM either (on staging; I can on production).

**Comment by rschamp** [comment]
Fixed in #661

**Comment by jwzimmer** [comment]
@rschamp There is only the default state (no log in option)? This is also what I'm now seeing in Safari after clearing cookies.
<img width="766" alt="screen shot 2016-07-05 at 3 23 27 pm" src="https://cloud.githubusercontent.com/assets/1320456/16596994/96aad554-42c4-11e6-8335-ea40a176f339.png">

**Comment by rschamp** [comment]
The last issue you posted here should have been fixed in #672
