### ISSUE TITLE
Educators resources do not default to English when translation not available

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#655]
Educator resources link from waiting room https://staging.scratch.mit.edu/educators#resources, with language set to German: 
![screen shot 2016-06-30 at 5 34 35 pm](https://cloud.githubusercontent.com/assets/399209/16505087/61894b0a-3ee9-11e6-80ca-97e1f25d43fd.png)

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/issues/659
