### ISSUE TITLE
build serve is not working

### ISSUE THREAD

**Issue by raviprakashdev** [LLK/scratch-www#6613]
serve -s build is not working

when i ran command npm run build i get build successful message
when i ran serve -s build i get build  index of files in browser
![image](https://user-images.githubusercontent.com/41155449/156988771-9eb45c09-3867-4759-b1bd-1850f789933d.png)

### Operating System and Browser
-wsl and chrome

**Comment by carljbowman** [comment]
If you are looking for the homepage, that page is called splash.html
