### ISSUE TITLE
Explore - Studios titles & thumbnails do not match production

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#665]
### Example 1

Studio result in `/explore`:
![image](https://cloud.githubusercontent.com/assets/747641/16590783/f6716c28-42a6-11e6-85bb-54749220227e.png)

Studio detail page:
![image](https://cloud.githubusercontent.com/assets/747641/16590799/0891ee46-42a7-11e6-960a-bf301d17c20d.png)

---

### Example 2

Studio result in `/explore`:
![image](https://cloud.githubusercontent.com/assets/747641/16590838/317a7224-42a7-11e6-8766-07790cbaf46b.png)

Studio detail page:
![image](https://cloud.githubusercontent.com/assets/747641/16590846/41100302-42a7-11e6-9063-37ccdccdd640.png)

**Comment by mewtaylor** [comment]
@thisandagain this tracked in https://github.com/LLK/scratchr2/pull/3716, which will go out with this deploy (but is not in production yet). We can also test this during the deploy.

**Comment by thisandagain** [comment]
As per discussion offline: there are two issues to track here:
- [ ] Thumbnails out-of-date LLK/scratchr2#3716
- [ ] Studio titles out-of-date (not tracked)

**Comment by thisandagain** [comment]
Looks good! Closing.
