### ISSUE TITLE
Explore - XHR request should include `q=*` not `q=all`

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#666]
Currently, the explore page issues an XHR request with a query string of `q=all` which actually does a search for projects that include `all` in the metadata. This should be changed to either `q=*` or simply drop that query string parameter altogether.

**Comment by thisandagain** [comment]
Funny enough this has a fairly minor impact on projects but a huge impact on studios.

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/issues/668
