### ISSUE TITLE
Explore page is blank in Safari

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#670]
I tried refreshing and clearing my history (cookies). Explore page is still blank.

Repro: Go to staging, click on Explore.

<img width="1097" alt="screen shot 2016-07-05 at 2 15 53 pm" src="https://cloud.githubusercontent.com/assets/1320456/16595137/bb904da8-42bb-11e6-9cdf-fbd6051b40ea.png">
<img width="1114" alt="screen shot 2016-07-05 at 2 15 29 pm" src="https://cloud.githubusercontent.com/assets/1320456/16595136/bb900a8c-42bb-11e6-9237-811c3b1ccea6.png">

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/commit/9a037fda818c415097df26e9b6eed4f9c5078924
