### ISSUE TITLE
Can't dismiss confirm your email banner/ unconfirmed email banner

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#673]
Chrome, Staging

- Create a new account
- Don't confirm the email
- Log in on Scratch
- Try to dismiss the banner

I thought I filed a bug for this already but I couldn't find it, so apologies if I did and this is a redundant case.

It covers the nice new teacher banner if you happen to have an educator's account:
<img width="1008" alt="screen shot 2016-07-05 at 4 37 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/16599189/3920f944-42cf-11e6-8268-1e412c1c5bf9.png">

**Comment by jwzimmer** [comment]
I found the case I was thinking of: https://github.com/LLK/scratchr2/issues/3583
That case is closed, so I'm not sure if this is a separate issue or if the fix to that issue didn't work/ didn't fix this scenario? (@mewtaylor)

**Comment by mewtaylor** [comment]
@jwzimmer this appears to be slightly different than that issue, so a separate ticket for this makes sense!
