### ISSUE TITLE
Filter is just imaginary

### ISSUE THREAD

**Issue by ScolderCreations** [LLK/scratch-www#6732]
### Expected Behavior

Scratch should have a filter that prevents usage of racial slurs, naming private messaging platforms, etc.

### Actual Behavior

The filter isn’t real. You can say anything you want. This is  a w f u l.

### Steps to Reproduce

no

### System Details
iPadOS 15, but this issue has occurred across all major OSes.

**Screenshots**

no

**Comment by ScolderCreations** [comment]
> The filter is handled by the backend. You should send a contact us message detailing reproduction steps.
> 
> Edit: You're right, the filter is broken <img alt="Screenshot 2022-04-12 at 20 33 58" width="444" src="https://user-images.githubusercontent.com/83728060/163010943-c1b95437-617b-45c8-a7c5-f5339f8ff2b1.png">

Contact Us takes way longer than a GitHub issue, and this should be top priority.

**Comment by RedGuy12** [comment]
> Contact Us takes way longer than a GitHub issue, and this should be top priority.

Let's be honest, the Scratch Team rarely responds to GitHub issues made by Scratchers, and if they do, it's not fast. At all.

**Comment by ScolderCreations** [comment]
Good point. Time to write an email…

**Comment by BryceLTaylor** [comment]
We were experiencing a temporary issue with our filter.  It has been resolved.
