### ISSUE TITLE
Website footer partially visible

### ISSUE THREAD

**Issue by nasirkhan** [LLK/scratch-www#6744]
### Expected Behavior

Footer should show all the contents of that area. The desktop site shows content in 5 columns and i expect to see the same content from the mobile as well.

### Actual Behavior

Footer displays contents in tow columns and that tow are not visible completely. Not sure if the other contents should be visible here, but i expect to see those, as desktop site have contents of 5 columns. 

### Steps to Reproduce

1. Go to 'https://scratch.mit.edu from Chrome/ Firefox form your mobile 
2. Scroll down at the very bottom of the page.
3. You will see the partially visible menu

### System Details

Device: Google Pixel 6
Browser: Google Chrome, Mozilla Firefox

### Screenshots
![Screenshot_20220302-200217](https://user-images.githubusercontent.com/396987/165064777-fdedcc6a-d950-4d6e-9a6b-0c08d76b25c3.png)

**Comment by jeffalo** [comment]
Looks like #5856 is meant to solve this.

**Comment by BryceLTaylor** [comment]
Thanks @jeffalo.  Yep.  It is currently working as intended, but a redesign is in the works.
