### ISSUE TITLE
Issue with teacher sign-up/ registration in IE 11

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#675]
From @cwillisf:
> I signed up for a new account and at the end, when I clicked "OK, Let's go!" I got some unexpected behavior
> 1) I got a popup that said something like "In order to display this page, Internet Explorer must resubmit the data from the form" -- I forgot to screenshot it, but it's a standard IE dialog that shows up (for example) when you reload a page that resulted from a form POST
> I clicked "Retry" or "Resubmit" (as opposed to "Cancel")
> 2) Then I got this page: 
<img width="367" alt="screen shot 2016-07-05 at 6 06 07 pm" src="https://cloud.githubusercontent.com/assets/1320456/16601553/37518852-42db-11e6-86ee-e81be95c8949.png">
> however, if I now navigate to staging.scratch.mit.edu, I'm logged in on my new account and everything seems fine

**Comment by mewtaylor** [comment]
closing as staging only issue. If we see it again, will re-open!
