### ISSUE TITLE
Undefined favorites in tooltip on Explore page - IE 11, Staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#676]
If you use your mouse to hover over the star icon on the Explore page in IE 11, then the tooltip says "undefined favorites". The loves and views tooltips return the same number as shown in the IE (not undefined).

![out](https://cloud.githubusercontent.com/assets/1320456/16620708/789297b2-4361-11e6-9988-251404b5b7a7.gif)

**Comment by mewtaylor** [comment]
@jwzimmer I see this in Chrome on Mac OSX as well

**Comment by St19Galla** [comment]
This can be closed as the loves, favorites, and views were all changed to just the username, right? :) @jwzimmer

**Comment by mewtaylor** [comment]
@St19Galla you're completely right – thanks!
