### ISSUE TITLE
YouTube Nocookie

### ISSUE THREAD

**Issue by 8-6-7-5-3-0-9-1-9-8-5-0-5-1-5-2-0-6-0-7** [LLK/scratch-www#6762]
Use YouTube Nocookie for playing videos

**Comment by BryceLTaylor** [comment]
Please explain what the intended benefit of your suggestion is.  I will close this for now.

**Comment by 8-6-7-5-3-0-9-1-9-8-5-0-5-1-5-2-0-6-0-7** [comment]
@BryceLTaylor The intended benefit is to play the video without inserting unsolicited tracking cookies from YouTube onto a Scratch page. As explained by @jeffalo previously here https://github.com/LLK/scratch-www/pull/6763#issuecomment-1117451519

**Comment by 8-6-7-5-3-0-9-1-9-8-5-0-5-1-5-2-0-6-0-7** [comment]
This does not fully prevent tracking, but this way people can load the page without having third party cookies inserted
