### ISSUE TITLE
Placeholder Image overlaps the text

### ISSUE THREAD

**Issue by nasirkhan** [LLK/scratch-www#6780]
### Expected Behavior

In the class manage dashboard, placeholder image should be within the the image area and do not overlap the text and links beside that.

### Actual Behavior

Where the image for the class (Under the teacher account) has not been set, it shows a placeholder image and it overlaps the text and links beside that. 

### Steps to Reproduce

1. Login to 'https://scratch.mit.edu' as a Teacher
2. Create a new class 
3. Select the new created class to edit
4. You will find the issue there

### System Details

Windows 11, Firefox 100

**Screenshots**
![Screenshot 2022-05-09 at 22-41-10 Scratch - Imagine Program Share](https://user-images.githubusercontent.com/396987/167460860-7e6460ff-353d-4643-a36a-afded49896db.jpg)

**Comment by BryceLTaylor** [comment]
Thanks. We have this filed already here: https://github.com/LLK/scratchr2/issues/6363

**Comment by nasirkhan** [comment]
https://github.com/LLK/scratchr2/issues/6363 is not accessible, i assume it is a private repo. 

is there any timeline set to fix this issue?
