### ISSUE TITLE
Stuck in default state nav bar on homepage in IE 11 after logging in as a new student

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#679]
I sign in as a teacher; log out; sign in as a student who has never successfully logged in (so I'm expecting to be redirected to the page where I have to change my password); get taken instead to homepage with default nav bar; clear cookies to return homepage to logged out state; try to sign in as student, get taken to homepage with default nav bar again. (I am able to sign in apparently successfully as newteachor or jwzimmer1990 after clearing the cookies.)

- I logged out as a teacher (newteachor)
- Then tried to log in as mystudont
- I entered my credentials (mystudont, newteachor - it was my first log in as this newly-created student)
- I expected to get redirected to a page asking me to change my password
- Got directed to homepage with default navbar
- Cleared cookies
- Back to normal homepage & navbar in logged out state
- Tried to log in as mystudont
- Default navbar/ homepage

![out](https://cloud.githubusercontent.com/assets/1320456/16623154/d20e5336-436a-11e6-9d2f-81e16fe41502.gif)
<img width="949" alt="screen shot 2016-07-06 at 11 00 08 am" src="https://cloud.githubusercontent.com/assets/1320456/16623155/d22394f8-436a-11e6-9557-350220c4b910.png">

**Comment by jwzimmer** [comment]
I was not expecting to see stuck-in-default-navbar issue again after these:
- https://github.com/LLK/scratch-www/pull/672
- https://github.com/LLK/scratch-www/issues/654

So I'm not sure if this is a different issue or if maybe the fix there is not available on staging (although I think since the PR was merged to release, it should be on staging?).

**Comment by thisandagain** [comment]
@mewtaylor Can you take a look?

**Comment by mewtaylor** [comment]
Just to add some info, here was my experience in Chrome:
* Logged out as teacher
* logged in as student
* was redirected to a reset password page, as desired, but only after seeing a flash of the homepage first
* nav bar had initial state on that page, because it appears that `account-nav.json` was returning a 302 response

**Comment by mewtaylor** [comment]
should be fixed in https://github.com/LLK/scratchr2/pull/3794

**Comment by mewtaylor** [comment]
Fixed in all other browsers except for IE 11. It seems as if IE doesn't follow redirects from xhr requests, so when it gets a `302` on the session, it is cancelling rather than following.

**Comment by mewtaylor** [comment]
Fixed again in https://github.com/LLK/scratchr2/pull/3796
