### ISSUE TITLE
Teacher Registration - I don't see validations (e.g. for username already exists) until I click "Next"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#683]
Staging, Chrome

In teacher registration, I don't see the validation that I'm trying to sign up with an extant username until I click the Next button:
<img width="683" alt="screen shot 2016-07-06 at 3 13 52 pm" src="https://cloud.githubusercontent.com/assets/1320456/16631283/55473030-438c-11e6-8a51-37b8833835b8.png">

In our other join flow, you see the verification that username exists right after you type it:
<img width="598" alt="screen shot 2016-07-06 at 3 13 44 pm" src="https://cloud.githubusercontent.com/assets/1320456/16631284/554b6e70-438c-11e6-8916-74944b0e70aa.png">

Most of the validations for the fields in the teacher registration flow are not triggered until you click "next".

However, the phone number validation seems to be as soon as the system detects that the field has been typed in but the existing number isn't valid... e.g. if I type my real phone number, it comes up as "invalid" until the last digit... (which doesn't seem like obviously the best behaviour to me? Maybe it could wait until the user deactivates the field or otherwise signals they're "done" typing):
<img width="712" alt="screen shot 2016-07-06 at 3 49 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/16632279/68f775e0-4391-11e6-8475-2cff07876931.png">

Ideally, I think we would be consistent with when validations are triggered for fields across the platform. /cc @carljbowman

**Comment by carljbowman** [comment]
@jwzimmer Great catch. I have some questions generally about when we display validation. In the case of the Username. I agree we should validate before the user clicks 'Next Step'. 

I also find it a bit awkward that forms are validating while the user is entering information. For example when you first start typing in a username, the the tooltip 'Usernames must be at least characters'. It is a bit jarring to have the tip come up as a first interaction.

<img width="1142" alt="screen shot 2016-07-07 at 5 23 38 pm" src="https://cloud.githubusercontent.com/assets/3409578/16670302/a0ba09d0-4467-11e6-8ff8-f64e011ff6b4.png">

We should validate when the field loses focus (e.g. user clicking away).

**Comment by thisandagain** [comment]
+1 on validation after field loses focus.
