### ISSUE TITLE
Deleted project notif not displaying correctly

### ISSUE THREAD

**Issue by RIMOPA** [LLK/scratch-www#6839]
### Expected Behavior

The notification should say something like "Poject [projectName] deleted"
### Actual Behavior

![image](https://user-images.githubusercontent.com/97112832/170843155-e88bc06f-3a2b-42fe-99ca-faf152d98004.png)

### Steps to Reproduce

1. Go to 'https://scratch.mit.edu/mystuff'
2. Click on 'New project'
3. Return to 'https://scratch.mit.edu/mystuff'
4. Click on 'Delete'
6. See buggy notification

### System Details
Windows 10 Version 21H2 (Build 19044.1706)
Google Chrome 102.0.5005.61 (Build oficial) (64 bits) (cohort: 102_win_control) 

**Screenshots**
![image](https://user-images.githubusercontent.com/97112832/170843263-9d9c8b4c-84db-4296-8238-c7f07463eef5.png)

**Comment by lankybox02** [comment]
This is on scratchr2

**Comment by RIMOPA** [comment]
> This is on scratchr2

@lankybox02 No, It is on the actual https://scratch.mit.edu/mystuff
