### ISSUE TITLE
Teacher Registration: Confusing use of "characters" in username validation - excludes "?", "!" (non-alphanumeric characters)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#684]
We may want a narrower description of "characters" in the validation message for username... A lot of users may think ?,&,!, etc., would be considered "characters" when we're really trying to restrict to alphanumeric chars, I think. /cc @kaschm & @carljbowman 

<img width="668" alt="screen shot 2016-07-06 at 3 22 39 pm" src="https://cloud.githubusercontent.com/assets/1320456/16631587/dfeb9acc-438d-11e6-8341-847ea1c943cb.png">

**Comment by kaschm** [comment]
Good catch. @rschamp, would it be correct to assume we really mean 

'Your username may only contain numbers, letters, and dashes' ? 

@jwzimmer @carljbowman , is this any clearer?

**Comment by jwzimmer** [comment]
(@kaschm I thumbs-up'd your comment, but then thought you might not see that since it doesn't incur a notification - yes, I think the text you wrote is clearer. : ) )

**Comment by rschamp** [comment]
@kaschm yes, correct.

**Comment by St19Galla** [comment]
#685
