### ISSUE TITLE
Updates to Scratch Credits Page

### ISSUE THREAD

**Issue by scratcher-erik** [LLK/scratch-www#6843]
Please remove the following Scratch team members from the [Credits page](https://scratch.mit.edu/credits) under 'Our Team' and add them to the 'Past Scratch Team Members' section:

- Bryce - https://scratch.mit.edu/users/BrycedTea/
- Ray - https://scratch.mit.edu/users/raimondious/
- Carl - https://scratch.mit.edu/users/designerd/

**Comment by benjiwheeler** [comment]
Also need to remove dinopickles, kittyloaf, and scmb1. 

('-')7  [salute texticon]

![image](https://user-images.githubusercontent.com/3431616/176452336-bb7cdd5b-6d14-4e86-9afe-025081f693eb.png)
