### ISSUE TITLE
Search / Explore - Ensure language preference is attached to request

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#686]
Currently (even if you language is set to something other than English), the explore and search pages will make an XHR request to:
`https://api.scratch.mit.edu/search/projects?limit=16&offset=0&q=*`

This request should reflect language preference. E.g.:
`https://api.scratch.mit.edu/search/projects?limit=16&offset=0&language=es&q=*`

**Comment by mewtaylor** [comment]
fixed in #687
