### ISSUE TITLE
Teacher Registration - Area code for Vatican City not necessarily correct

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#690]
It looks like there are [two options](https://en.wikipedia.org/wiki/Telephone_numbers_in_Vatican_City) for choosing the Vatican City area code: +379 or +39. The tool we're using for the phone number in teacher registration chose +39. That may be the correct choice, but I would like someone to confirm that - @kaschm? 

I also don't know if there could be other countries where there were multiple reasonable options for the country code, and if so, whether the tool we're using has made the choices we prefer in all of those instances. It could be worth looking into further (which I can do, if anyone wants me to : ) )? /cc @thisandagain 

(We may also want to consider if we like the alternate spellings & translations the tool offers for country names... like the flag choices, we could potentially be taking political stances by offering a given alternate spelling, translation, etc., or even by offering them for certain countries (e.g. if we offer a translation of a country's name in an unofficial language spoken by a region seeking independence or something, just to come up with some kind of example).)

<img width="678" alt="screen shot 2016-07-07 at 10 33 09 am" src="https://cloud.githubusercontent.com/assets/1320456/16657534/de73e0a2-4430-11e6-876a-fbdc20b9088e.png">
<img width="602" alt="screen shot 2016-07-07 at 10 32 52 am" src="https://cloud.githubusercontent.com/assets/1320456/16657533/de73e142-4430-11e6-90a0-8c8638d1c95f.png">

**Comment by kaschm** [comment]
Amazing catch - @jwzimmer, both are valid; I think it's fine that we force +39

**Comment by thisandagain** [comment]
Closing for now based on feedback from @kaschm
