### ISSUE TITLE
Change "what country do you live in" to "what is your location" on the join scratch page

### ISSUE THREAD

**Issue by derter-menter** [LLK/scratch-www#6901]
It says country even though tonnes of places on that list are not countries, and are instead territories of other countries, like American Samoa, Guam etc 

Some are partially recognised states. Is Western Sahara a country? Taiwan? Changing to location can reduce controversy on what is a country in Scratch.

Finally, it is location on account settings

**Comment by Adzboy** [comment]
How about "Where do you live?"

**Comment by derter-menter** [comment]
> How about "Where do you live?"

Seems bit more personal/creepy imo, but could work

**Comment by derter-menter** [comment]
> Well, I mean some people may not be comfortable sharing the exact location, but if it was optional, than it could work.

This would still be the ISO list used, it won't be more specific.

**Comment by Adzboy** [comment]
> > How about "Where do you live?"
> 
> Seems bit more personal/creepy imo, but could work

Same could be said for "What is your location"

**Comment by Cool-Scratcher** [comment]
Taiwan is a country...?

**Comment by derter-menter** [comment]
> Taiwan is a country...?

partially recognised.

**Comment by Bashamega** [comment]
First of all western sahara is a country in Africa.

I gathered all the countries in the world and placed them in  a PDF
[Countries.pdf](https://github.com/LLK/scratch-www/files/9350610/Countries.pdf)
