### ISSUE TITLE
Entered too-long phone number during Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#691]
It seemed to accept this phone number even though it is too long, for some reason? I am not sure under exactly what conditions the validation fails - I thought at first that it might be thrown off by ending a phone number in 0, but it correctly rejects e.g. +1 (738) 982-73000, +1 (738) 982-73120, +1 (617) 253-88100, etc. It seems to be something about the rest of the phone number that fools it, since it accepts +1 (123) 456-78931 (and other similar numbers) as well - maybe the first two 1's? It rejects e.g. +1 (234) 567-89391.

Maybe this is actually a valid US phone number pattern? : \

No validations being triggered:
<img width="380" alt="screen shot 2016-07-07 at 11 06 13 am" src="https://cloud.githubusercontent.com/assets/1320456/16658056/de0e33fe-4432-11e6-847e-cc41a82b121c.png">
<img width="384" alt="screen shot 2016-07-07 at 11 03 15 am" src="https://cloud.githubusercontent.com/assets/1320456/16657974/89517614-4432-11e6-9c3e-a1d66e9222e3.png">
<img width="418" alt="screen shot 2016-07-07 at 11 03 03 am" src="https://cloud.githubusercontent.com/assets/1320456/16657973/89513f28-4432-11e6-9d37-e0545f239cea.png">

Validation:
<img width="613" alt="screen shot 2016-07-07 at 11 06 00 am" src="https://cloud.githubusercontent.com/assets/1320456/16658075/f5847822-4432-11e6-85fc-1d4349d5f8ff.png">

![out](https://cloud.githubusercontent.com/assets/1320456/16657835/e12ec644-4431-11e6-931e-f1612b7d55a6.gif)

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/702

**Comment by jwzimmer** [comment]
I can still enter a longer phone number, on production, in Chrome:

Number is invalid:
<img width="639" alt="screen shot 2016-07-09 at 6 36 51 pm" src="https://cloud.githubusercontent.com/assets/1320456/16710654/4e97c0a4-4604-11e6-90f9-4f30e651fdd9.png">

Add a 1, and it's valid (but too long for a US number?):
<img width="506" alt="screen shot 2016-07-09 at 6 36 39 pm" src="https://cloud.githubusercontent.com/assets/1320456/16710653/4e9601c4-4604-11e6-869a-8ac54d064f47.png">

... Is there any chance that the phone number can be this long & be valid in the US? I called +1 (123) 456-78911 and got "your call cannot be completed as dialed".

**Comment by jwzimmer** [comment]
Actually, this does work, it just doesn't get triggered at the right time! When I pressed "Next" I got a validation against this phone number. --> https://github.com/LLK/scratch-www/issues/712

**Comment by mewtaylor** [comment]
Turns out that this is specific to the use case of putting "1" as the first number after the country code, and is discussed upstream: https://github.com/googlei18n/libphonenumber/issues/1061.

Essentially, it's seeing a 1 as someone accidentally typing in the country code themselves, chopping it off, and starting the number at "2". This is why `123-456-78911` is seen as valid (i.e. it is `234-567-8911`, which is in Akron), but `223-456-78911` was seen as invalid (too long). So, the library is seeing numbers as too long, except in the country code use case.
