### ISSUE TITLE
Teacher Registration - should users be able to use back & forward arrows/ navigate through steps (get 403 error)?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#692]
Currently, there is no obvious way to move through the steps in registration other than in sequential forward order (step 1, step 2, step 3... last step). Do we want users to be able to go back and change info they entered in an earlier step?

Also, using the back arrow in the browser (Chrome, staging) causes you to get a 403 error. If you then try to use the forward arrow to go back to the step you were in, you're redirected to the first step and none of your information is saved. I'm not sure this is the ideal behaviour.

Use the back arrow:
<img width="427" alt="screen shot 2016-07-07 at 11 51 07 am" src="https://cloud.githubusercontent.com/assets/1320456/16659848/dc5ebb30-4439-11e6-85ce-743e151ef325.png">
Use the forward arrow:
<img width="483" alt="screen shot 2016-07-07 at 11 51 19 am" src="https://cloud.githubusercontent.com/assets/1320456/16659849/dc633674-4439-11e6-9723-41298d4dd793.png">

**Comment by kaschm** [comment]
@carljbowman - thoughts on this? it feels like we should have an elegant way of going backwards that doesn't involve a 403.

**Comment by thisandagain** [comment]
As discussed with @carljbowman yesterday I think we should detect the "back" button press and present an error telling the user that their progress will be lost.

**Comment by thisandagain** [comment]
Keeping @carljbowman assigned to confirm and provide flow.

**Comment by carljbowman** [comment]
@thisandagain - Thanks for documenting! As discussed this flow is good with me. 👍
