### ISSUE TITLE
License name should be mentioned with version number

### ISSUE THREAD

**Issue by nasirkhan** [LLK/scratch-www#6929]
### Expected Behavior

On the [FAQ page](https://scratch.mit.edu/faq) it is mentioned that almost all the contents and shared projects are licensed under "Creative Commons Attribution-ShareAlike" license. Whereas it is mandatory to mention the license version number and recommended to use the 4.0 version since its release. 

### Actual Behavior

License names are mentioned without version numbers.

### Steps to Reproduce

1. Go to [https://scratch.mit.edu/faq](https://scratch.mit.edu/faq)
2. Search "Creative Commons Attribution-ShareAlike"

**Comment by benjiwheeler** [comment]
Closing in favor of the similar https://github.com/LLK/scratch-www/issues/6930
