### ISSUE TITLE
Phone number field not required but it should be - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#693]
Either phone number & checkmark should both be optional, or both should be required.

Right now, you can leave the phone number field blank but you are forced to check the box saying Scratch can call you, which doesn't make sense.

Chrome, staging

<img width="443" alt="screen shot 2016-07-07 at 12 00 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/16660060/d9c9d5c0-443a-11e6-97a6-cab75745300c.png">
<img width="737" alt="screen shot 2016-07-07 at 12 10 02 pm" src="https://cloud.githubusercontent.com/assets/1320456/16660332/dc685120-443b-11e6-9a1a-4cd51bbed23b.png">

**Comment by jwzimmer** [comment]
Possibly not putting in a phone number caused this?
<img width="666" alt="screen shot 2016-07-07 at 12 17 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/16660575/f1d74326-443c-11e6-8bc8-f25ddab35303.png">

**Comment by thisandagain** [comment]
This is prio-high but not for the beta test. Adding to July milestone.

**Comment by thisandagain** [comment]
Nvmd! The connection to #696 makes this a blocker.

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/702
