### ISSUE TITLE
Floating field validation for Country - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#694]
The Country validation is off to the right instead of aligned like the other validations. It is also not outlined in orange.

Chrome, staging

<img width="846" alt="screen shot 2016-07-07 at 12 05 17 pm" src="https://cloud.githubusercontent.com/assets/1320456/16660156/375576ea-443b-11e6-971b-ab345b837116.png">

**Comment by jwzimmer** [comment]
This alignment may not be ideal either:

<img width="650" alt="screen shot 2016-07-07 at 12 08 17 pm" src="https://cloud.githubusercontent.com/assets/1320456/16660249/8a9ceafe-443b-11e6-998b-ff2efcb501eb.png">

**Comment by mewtaylor** [comment]
For the `Gender` field, were you thinking about alignment horizontally, or alignment vertically?

**Comment by jwzimmer** [comment]
Both? Probably vertically though? I mean, as is, it's not too bad, but it kind of looks like it's pointing to a non-existent field, to me...

**Comment by mewtaylor** [comment]
Ah ok – @jwzimmer the way it was aligned vertically was to be with the `Gender` title, since that's the "field" that it's referring to. But perhaps that would be clearer if it were differently aligned horiztonally?

**Comment by jwzimmer** [comment]
@mewtaylor I don't know - if @carljbowman thinks it's fine as is, that's fine with me. : )

**Comment by carljbowman** [comment]
@jwzimmer @mewtaylor 

RE Select Country tooltip: This is definitely a bug and should be aligned like 'Address Line 1'

RE Gender tooltip: It is not clear to me that the tooltip is pointing at the title 'Gender', it seems just slightly off and by that nature unintentional. This behavior is also inconsistent with how we center align vertically to fields. My leaning is towards center aligning vertically with the set of fields.

That said, we will have a similar issue on 'Type of Organization'. In these cases we may want to be more specific with the tooltip content: 'Please select a gender, this field is required'. For the case of the 'Type of Organization': 'Please check all the Types of Organizations that apply, this field is required'.

**Comment by jwzimmer** [comment]
Also seeing this in IE 11:

<img width="620" alt="screen shot 2016-07-07 at 4 18 57 pm" src="https://cloud.githubusercontent.com/assets/1320456/16668438/f0cb527a-445e-11e6-92e2-a6aff51ef600.png">

**Comment by jwzimmer** [comment]
Maybe case https://github.com/LLK/scratch-www/issues/699 should be closed and consolidated with this case?

**Comment by mewtaylor** [comment]
@jwzimmer I think they should stay separate – #699 is different, since this applies outside of IE in other browsers.

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/702
