### ISSUE TITLE
Type of Organization should be required - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#695]
If you don't check anything for Type of Organization, you can still proceed to the next step (the top two fields are the only ones that seem to be required on this step). We meant to require type of organization... we're missing that validation. /cc @carljbowman & @kaschm 

<img width="472" alt="screen shot 2016-07-07 at 12 10 17 pm" src="https://cloud.githubusercontent.com/assets/1320456/16660363/f98220a6-443b-11e6-8679-81e796df2bd7.png">
<img width="495" alt="screen shot 2016-07-07 at 12 10 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/16660364/f9a6b484-443b-11e6-9e3d-089eff1a5f1a.png">

**Comment by mewtaylor** [comment]
I kind of assumed that "Check all that apply" has the implicit understanding that, if none apply and therefore are not checked, that is still a valid option – so it would be made understood as part of that text. But perhaps that is not an ok assumption on my part to make for others signing up.

**Comment by jwzimmer** [comment]
Check all that apply could be read to mean "at least 1" I think. : )

**Comment by mewtaylor** [comment]
Ah gotcha – well I imagine that @kaschm would be the right person to clarify this anyways :). @kaschm I hope you don't mind that I tagged you in this issue!

**Comment by carljbowman** [comment]
@jwzimmer @mewtaylor This field should be required. Looks like we just did not add a validation. Thanks for looking out for consistency!

**Comment by mewtaylor** [comment]
fixed in https://github.com/LLK/scratch-www/pull/702
