### ISSUE TITLE
Can't proceed to next step after email - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#697]
I got stuck in the email step of teacher registration (with a valid email & no error messages displayed in the UI). I am not sure if it's because I entered html/ javascript injections in earlier fields, or if that's unrelated. (Chrome, staging.)

![out](https://cloud.githubusercontent.com/assets/1320456/16661357/88648e86-4440-11e6-895e-2fa3d2009e4f.gif)
<img width="258" alt="screen shot 2016-07-07 at 12 45 49 pm" src="https://cloud.githubusercontent.com/assets/1320456/16661402/c59a7b76-4440-11e6-9d62-77930249f5fe.png">
<img width="244" alt="screen shot 2016-07-07 at 12 51 57 pm" src="https://cloud.githubusercontent.com/assets/1320456/16661593/a57fd29a-4441-11e6-985e-51f3f56e65d7.png">
<img width="410" alt="screen shot 2016-07-07 at 12 40 21 pm" src="https://cloud.githubusercontent.com/assets/1320456/16661359/88672dee-4440-11e6-8a72-4f85a6acde8b.png">
<img width="422" alt="screen shot 2016-07-07 at 12 39 30 pm" src="https://cloud.githubusercontent.com/assets/1320456/16661358/88663060-4440-11e6-852b-ea6cf1a13662.png">

**Comment by mewtaylor** [comment]
Unable to repro – I tried with and without injection. I did injection on the `textarea

**Comment by jwzimmer** [comment]
@mewtaylor could it be caused by failures of previous registration attempts?
i'm getting it repeatedly (with all valid inputs, no injection):
<img width="1011" alt="screen shot 2016-07-07 at 12 56 04 pm" src="https://cloud.githubusercontent.com/assets/1320456/16661739/557b0732-4442-11e6-8d6b-6f9ca8df9af4.png">
however, i did get that error at the end of a prior registration attempt - https://github.com/LLK/scratch-www/issues/696
so could that failure be causing these errors?
i'm going to try clearing cookies and registering.

**Comment by jwzimmer** [comment]
More details from console:
<img width="607" alt="screen shot 2016-07-07 at 1 05 17 pm" src="https://cloud.githubusercontent.com/assets/1320456/16662136/08424c8a-4444-11e6-9ad2-4afce469745f.png">
<img width="593" alt="screen shot 2016-07-07 at 1 06 16 pm" src="https://cloud.githubusercontent.com/assets/1320456/16662137/0845d076-4444-11e6-9cad-cbb879d9811c.png">

@mewtaylor said it looks like an invalid CSRF token & to try restarting browser

**Comment by jwzimmer** [comment]
Closing this because it seems to be out of our control per convo with @mewtaylor - if any users encounter it, they should restart their browser and clear their cache & cookies.
