### ISSUE TITLE
Waiting for approval card appears at same time as I can access My Classes - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#698]
The Waiting for Approval card did not clear simultaneously from the time I confirmed my email & was able to see My Classes - I would expect not to see My Classes (since I should get redirected to the waiting room if the approval period isn't over) at the same time as the Waiting for Approval card (since if the card exists, the approval period shouldn't be over). /cc @rschamp 

IE 11:
<img width="591" alt="screen shot 2016-07-07 at 2 55 34 pm" src="https://cloud.githubusercontent.com/assets/1320456/16666224/af34ec18-4454-11e6-82b5-29458a2901d9.png">

(Note:
Originally this case included another issue, "I am not sure if this is just a timing issue, but I have created several teacher accounts in Chrome without encountering the Waiting for Approval card. I created an account as quickly as possible to try to make sure I would reach the waiting room before the 5 minute waiting period ended (I would think it would start from the end of account creation, but to be on the safe side I considered it might start at the beginning of account creation but only complete if registration was successful), and still didn't see the Waiting for Approval card. However, I did see it in IE 11 when I created a new account."
After discussion with @mewtaylor, this is actually a non-issue:
> ahh that would explain it – the periodic task runs every 5 minutes, but the waiting period is 0 minutes
so, if you happen to do it right before it runs the task, you won’t see anything
but if you happen to do it right after, you wait 5 minutes before it will approve you again

)

**Comment by chrisgarrity** [comment]
I saw the waiting, confirm email and resources card on chrome. I didn't confirm my email so I could see the confirm email in other browsers, but by the time my other browsers had updated, the waiting period was over. I didn't try the combination of confirmed email, during waiting period.

**Comment by jwzimmer** [comment]
@chrisgarrity Great, thank you! @mewtaylor confirmed he has seen the Waiting for Approval card in Chrome and I just haven't by luck of how the timing is set up.

**Comment by jwzimmer** [comment]
Something weird does seem to going on with when the cards appear/ disappear.

I registered a new account. Immediately after registering I was taken to the waiting room, and there was no Waiting for Approval card, which made me expect that I had already been approved & when I click My Classes, I would be able to see My Classes page:
<img width="589" alt="screen shot 2016-07-07 at 4 25 13 pm" src="https://cloud.githubusercontent.com/assets/1320456/16668574/96535df0-445f-11e6-9b90-d22c703bb4a6.png">
However, when I went to the homepage, clicked My Classes, I got redirected to the waiting room, at which point I saw all 3 cards, including Waiting for Approval:
<img width="598" alt="screen shot 2016-07-07 at 4 25 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/16668626/ccd3dc42-445f-11e6-8fc3-a0c8c7695bb8.png">

**Comment by jwzimmer** [comment]
Repro'd the behaviour from the last comment in Safari: register > get redirected to waiting room > see 2 cards (no waiting for approval) > go to homepage > click on My Classes > get redirected to waiting room > see 3 cards (including waiting for approval).

<img width="797" alt="screen shot 2016-07-07 at 5 18 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/16670161/f0923816-4466-11e6-8396-9b47df3b790c.png">

**Comment by jwzimmer** [comment]
I saw this in Chrome, too - I signed up an educator account, did not see the Wait for Approval card, continued to homepage and created a project, clicked on My Classes, then was redirected to the waiting room and saw the Waiting for Approval card.
