### ISSUE TITLE
Block usernames in forums 2.0

### ISSUE THREAD

**Issue by PPPDUD** [LLK/scratch-www#6997]
My suggestion is to stop Scratchers from posting forum posts that contain their username. 
This will help prevent spam.

Sorry if I did something wrong here, I am still a Github newbie!

**Comment by Bashamega** [comment]
It is a good idea, but I think it is important to mention users in  scratch for communication.

**Comment by PPPDUD** [comment]
> It is a good idea, but I think it is important to mention users in scratch for communication.

Sorry, but I can't quite surely interpret what that means by "communication". My assumption is that you meant to say give away their usernames publicly, which would be Naming and Shaming, or you meant for me to contact the Scratcher individually. Would you please clarify?

**Comment by Bashamega** [comment]
> > It is a good idea, but I think it is important to mention users in scratch for communication.
> 
> Sorry, but I can't quite surely interpret what that means by "communication". My assumption is that you meant to say give away their usernames publicly, which would be Naming and Shaming, or you meant for me to contact the Scratcher individually. Would you please clarify?

I meant that it is okay to past there username on scratch like"Hey @adambasha", because this isn't my real name this is my username for scratch.

**Comment by PPPDUD** [comment]
Look up "naming and shaming".

**Comment by lankybox02** [comment]
How exactly would this prevent spam?
Naming and shaming means "HEY GUYS!! LOOK!!! @USER123 JUST SAID A BAD WORD!!"

**Comment by PPPDUD** [comment]
I guess you're right, but I have seen fourms--- you know what, let's just
say that a Scratcher named BIRDS made a fourm called "BIRDS". In the post,
they said the following: "mcdonaldz nuggetzz!1!". This would help stop
that. I have already seen a few examples of which I will not link.

**Comment by PPPDUD** [comment]
> > > It is a good idea, but I think it is important to mention users in scratch for communication.
> > 
> > 
> > Sorry, but I can't quite surely interpret what that means by "communication". My assumption is that you meant to say give away their usernames publicly, which would be Naming and Shaming, or you meant for me to contact the Scratcher individually. Would you please clarify?
> 
> I meant that it is okay to past there username on scratch like"Hey @adambasha", because this isn't my real name this is my username for scratch.

BTW, I got confused by what you meant. Whoops!
