### ISSUE TITLE
`general.monthDecember` message is duplicated in `src/l10n.json`

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-www#7006]
### Expected Behavior

JSON files would not contain duplicate keys.

### Actual Behavior

In `src/l10n.json`, `general.monthDecember` is listed twice: on line 10 and on line 61. The duplicate was added in #4901.

**Comment by benjiwheeler** [comment]
Thanks for catching this, @mxmou. Marking it as a good first issue, if any new contributors want to submit a fix!

**Comment by SeansC12** [comment]
Hi @benjiwheeler, is there anyone working on the issue currently? If not, I would like to work on this.

**Comment by SeansC12** [comment]
Hi @benjiwheeler, I would like to work on this.
