### ISSUE TITLE
More comfortable way to contact the ST.

### ISSUE THREAD

**Issue by PPPDUD** [LLK/scratch-www#7021]
Because I lost my Scratch account, PPPDUDE. The email doesn't seem to work, password resetting is not possible, and my dad doesn't want me to use Contact Us right now.

By the way, ST, think you could send me a password reset email? My current main on Scratch is PPPDUD, and the account I want recovered is PPPDUDE. That's all I know (other than the email, which I will not say).

**Comment by Quantum-Codes** [comment]
> The email doesn't seem to work
ST may take a long time to respond. I got my response after 1 year (that too they rejected)

> password resetting is not possible
It is! Log out or go to an incognito tab and go here https://scratch.mit.edu/accounts/password_reset/

**Comment by PPPDUD** [comment]
Ok, trying it now. Thanks.

**Comment by PPPDUD** [comment]
You are forgiven. However, nobody in my family has yet received an email.

**Comment by Quantum-Codes** [comment]
Did you get an auto response? Wait for 5 mins for it
In my case, I didn't and had to use another email account which also caused troubles

**Comment by PPPDUD** [comment]
Nope. Probably waited an hour by now.
