### ISSUE TITLE
CE-149 Source is no longer uploaded to Transifex

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-www#7031]
### Expected Behavior
Translation source file is uploaded to Transifex

### Actual Behavior
Translation source file is no longer uploaded to Transifex. Here's the screenshot of Scratch Website (Japanese) project, that says the last update was in July (see sort order). However, multiple source changes have occurred as part of #7000, and they are not reflected.

![image](https://user-images.githubusercontent.com/33279053/187963355-4552d0dc-51ef-4062-85da-2e7e10378569.png

### CircleCI logs
The CircleCI log at https://app.circleci.com/pipelines/github/LLK/scratch-www/9859/workflows/c7c6b4c9-87c4-4b62-96eb-11876f044efa/jobs/12270 failed with the following error:

```
Transifex Error 400: Only maintainers are allowed to update the source file.
```

This is likely the cause; presumably as part of developer retirement, their maintainer access to the project was revoked (as they should), but the token is not replaced on CircleCI causing push failure. This also explains why pull is working, since I don't think they require maintainer permissions.

**Comment by benjiwheeler** [comment]
Thanks for noticing this, @apple502j. We are aware of it, and I'll try to give it attention soon.

**Comment by apple502j** [comment]
Seems like this is fixed now.

**Comment by corihudson** [comment]
This is fixed now, thanks for bringing this to our attention!
