### ISSUE TITLE
The project creator should not be counted in project view count

### ISSUE THREAD

**Issue by Bashamega** [LLK/scratch-www#7032]
Expected Behavior

The scratch view count should be 0 when first  uploaded.
Actual Behavior
But the scratch view count starts from 1 because the first user to see it is the user that shared the project

![Untitled](https://user-images.githubusercontent.com/110662505/188053999-f388ec9b-fb48-48a0-b860-733faefbf043.png)

**Comment by derter-menter** [comment]
and? This system makes sense and has always been the norm.

**Comment by Bashamega** [comment]
> and? This system makes sense and has always been the norm.

I think we should change is to the better. And I think this group is about bugs and new features

**Comment by benjiwheeler** [comment]
Thanks for noticing this, @Bashamega ! We're going to consider this behavior desired, although I know it's a bit confusing.

One note -- please try to be more descriptive in the issue summaries you write. If someone asked you what the problem is, what's the short sentence you would say?
