### ISSUE TITLE
Type of Organization validation should be triggered at the same time as other validations on the same page - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#705]
Chrome, ON PRODUCTION : )

It wasn't required at all before the fix to https://github.com/LLK/scratch-www/issues/695 but I could not get past that step in Chrome without submitting an answer to Type of Organization, so that is functionally fixed, but you don't see the validation if you click "Next" with other empty required fields... you see the validation if you click "Next" and it's the only empty required field...

Click "Next" without filling anything in this step out - you see validations for the top two fields but not for Type of Organization:
<img width="502" alt="screen shot 2016-07-08 at 10 15 13 am" src="https://cloud.githubusercontent.com/assets/1320456/16690330/590ab600-44f5-11e6-932c-6d2d52fcd33f.png">

Click "Next" after you have filled out the other two fields but haven't answered type of organization:
<img width="511" alt="screen shot 2016-07-08 at 10 15 27 am" src="https://cloud.githubusercontent.com/assets/1320456/16690329/5909e770-44f5-11e6-8b46-0d04000bdf17.png">

**Comment by kaschm** [comment]
Related: https://github.com/LLK/scratch-www/issues/683, https://github.com/LLK/scratch-www/issues/712

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/803
