### ISSUE TITLE
Error after trying to register for teacher account - on production

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#707]
I am not sure what caused this - possibly triggering a validation for Type of Organization by trying to proceed to the next step without answering it first? (It didn't let me move to the next step without filling it out.) I didn't intentionally put in any "bad" data.

/cc @mewtaylor 

<img width="885" alt="screen shot 2016-07-08 at 4 57 16 pm" src="https://cloud.githubusercontent.com/assets/1320456/16701340/1c7c8fc8-452d-11e6-9cbe-715d531c3389.png">

**Comment by jwzimmer** [comment]
I will restart my browser & clear cache & cookies then try to repro.

**Comment by jwzimmer** [comment]
Tried twice in Chrome and once in IE11, could not repro this issue after restarting browser, clearing scratch cookies, and hard refresh (in Chrome). So closing for lack of repro, but obviously if I see it again I will re-open.

**Comment by jwzimmer** [comment]
I got this again, @mewtaylor! Is there any reason I should have encountered this again that would be attributable to cookies or anything?
<img width="942" alt="screen shot 2016-07-09 at 6 52 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/16710702/5c056cc6-4606-11e6-8798-fb7474796a37.png">

**Comment by jwzimmer** [comment]
@mewtaylor Just got this again, did not enter any intentionally incorrect data... (Chrome, production)
<img width="859" alt="screen shot 2016-07-11 at 10 32 50 am" src="https://cloud.githubusercontent.com/assets/1320456/16734260/dfef865a-4752-11e6-97b3-324018e77b9c.png">

**Comment by thisandagain** [comment]
@rschamp @mewtaylor If a user hits this, are we logging the error to Sentry?

**Comment by mewtaylor** [comment]
@thisandagain we should be, though it's not clear from this what the error would be yet. I'll continue to take a look, but didn't see anything yet as of yesterday afternoon

**Comment by rschamp** [comment]
I don't think this would show up anywhere. It's just an invalid form so the error would only be displayed to the user. We should begin logging invalid registration requests to catch this issue.

**Comment by mewtaylor** [comment]
Moving this to https://github.com/LLK/scratchr2/issues/3852
