### ISSUE TITLE
Search bar on Help page doesn't work

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#709]
Production, Chrome

- Go to homepage
- Click on Help icon in navbar
- Use the search bar on the help page
- Note lack of results

The query in the URL looks like the "old" style, for example: https://scratch.mit.edu/search/google_results/?q=hi&date=anytime&sort_by=datetime_shared

![out](https://cloud.githubusercontent.com/assets/1320456/16702894/0eae5b42-4537-11e6-9d6d-b1bedfd8e7eb.gif)
<img width="1097" alt="screen shot 2016-07-08 at 6 03 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/16702895/0eb48710-4537-11e6-9446-02128da9d02b.png">

**Comment by jwzimmer** [comment]
Same story with the "For Parents" page:
<img width="1056" alt="screen shot 2016-07-08 at 6 16 10 pm" src="https://cloud.githubusercontent.com/assets/1320456/16703022/29409050-4538-11e6-9a2b-6aaba1313efb.png">

**Comment by jwzimmer** [comment]
This is what happens if you search from the Press page - could be the intended behaviour, I am not sure:
https://wiki.scratch.mit.edu/wiki/Scratch_Press
<img width="1071" alt="screen shot 2016-07-08 at 6 22 50 pm" src="https://cloud.githubusercontent.com/assets/1320456/16703140/093183f4-4539-11e6-863a-3efdb1ba7c71.png">

**Comment by jwzimmer** [comment]
@mewtaylor - I checked all the pages linked to from the nav bar and from the footers; the ones that had search bars relevant to scratch (I ignored things like the "Scratch day" site) that returned results differently than the kind of results expected from the search bar on the homepage are noted in the prior two comments above.
<img width="936" alt="screen shot 2016-07-08 at 6 29 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/16703283/0376bcbc-453a-11e6-84b8-8c1d1342d4af.png">

**Comment by mewtaylor** [comment]
@jwzimmer @thisandagain I think this may have been varnish caching. I have not been able to repro this issue, and it appears to be going to the search page correctly now.
