### ISSUE TITLE
Language selector on Firefox has strange focus ring placement

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-www#711]
Actually it's probably just built builtin focus ring that isn't being hidden.

![Demo](https://cloud.githubusercontent.com/assets/9948030/16709269/f2a0743e-45e1-11e6-8892-a110662b6d7c.png)

I'm running Firefox 50 on OS X El Capitan 10.11.4. There isn't a browser-specific focus ring on Safari or Chrome.

**Comment by St19Galla** [comment]
What is the design preference for this? Hide it as the mouse moves away? :)

**Comment by coke11** [comment]
This happens with almost, every single menu when I run firefox on my mac...

**Comment by towerofnix** [comment]
Fixed by #1759.
