### ISSUE TITLE
Timing for validation for too-long phone number is confusing - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#712]
I don't see the validation for a longer phone number, on production, in Chrome, until after I click "Next" (which is confusing since you do see the validations for other kinds of incorrect input in the phone field as soon as you enter it).

(This should go along with the other cases relating to when validations should be triggered, which should be considered, as @carljbowman [said](https://github.com/LLK/scratch-www/issues/683).)

Number is invalid:
<img width="639" alt="screen shot 2016-07-09 at 6 36 51 pm" src="https://cloud.githubusercontent.com/assets/1320456/16710654/4e97c0a4-4604-11e6-90f9-4f30e651fdd9.png">

Add a 1, and it appears to be valid:
<img width="506" alt="screen shot 2016-07-09 at 6 36 39 pm" src="https://cloud.githubusercontent.com/assets/1320456/16710653/4e9601c4-4604-11e6-869a-8ac54d064f47.png">

Update:
**No error on Next, I can proceed to next step**
![out](https://cloud.githubusercontent.com/assets/1320456/18144244/b32d873e-6f93-11e6-9963-8c659c170b4b.gif)

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/803

**Comment by mewtaylor** [comment]
The fix from #803 ended up causing some issues with accessibility and international phone numbers (see #816). So, this needs a separate solution

**Comment by mewtaylor** [comment]
We are treating this as no longer an issue, since we no longer have a custom length checker, and the length issue seems to be handled by our validator: https://github.com/LLK/scratch-www/issues/691#issuecomment-243889806
