### ISSUE TITLE
Wait for Approval card has confusing instructions about login information - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#715]
The wait for approval card says:
> Wait for Approval
Your information is being reviewed. Please be patient, the approval process can take up to 24 hours. You will receive an email with your login information once your account has been created.

I think the "receive an email with your login information once your account has been created" part is confusing. You do actually have an account after registering; you can create and share projects, for example. You just don't have full access to the features of a teacher account (e.g. My Classes). I also am not really sure what the receive-an-email-with-your-login-info part is about... is that referring to the confirmation email? Will I eventually get another email (I don't think I ever have yet)? /cc @kaschm 

<img width="704" alt="screen shot 2016-07-11 at 10 43 17 am" src="https://cloud.githubusercontent.com/assets/1320456/16734823/e0836a26-4754-11e6-862a-c19d4989db9f.png">

**Comment by jwzimmer** [comment]
Update: I did get another email welcoming me to Scratch (not the confirmation email), but I think describing it as "an email with your login information" is confusing (and it is still a bit confusing to only mention 1 email when you do actually get 2, confirmation & welcome, neither clearly being the "email with your login information" mentioned in the card).

<img width="576" alt="screen shot 2016-07-12 at 11 32 11 am" src="https://cloud.githubusercontent.com/assets/1320456/16773144/bc8e1db6-4824-11e6-9368-3921ae0f0feb.png">

**Comment by rschamp** [comment]
Whoops! I blanked on implementing the email this is referring to...

**Comment by kaschm** [comment]
Good catch, @jwzimmer . 

Let's update text in the Waiting Room to:

You can log into your Scratch Account now, but the features specific to Teachers are not yet available. Your information is being reviewed. Please be patient, the approval process can take up to 24 hours. You will receive an email indicating your account has been upgraded once your account has been approved. 

@rschamp, as a reminder, the text for the emails can be found here: https://docs.google.com/document/d/1LTrFOSEt20TLkh4bm-3vwgw0XSNIz21xSU0RbLCplWc/edit

[Doc is restricted - ping me if you have issues accessing the page]
