### ISSUE TITLE
Exit icon for Report Project Comment contains other icons

### ISSUE THREAD

**Issue by Airhogs777** [LLK/scratch-www#722]
The close icon is cropped wrong so that I can see other icons:
![](http://i.cubeupload.com/XjSmPB.png)

Steps to repro:

1. navigate to a scratch project
2. hover over a comment
3. click "Report"

I cleared my cache and that didn't resolve the issue.
MacOS Macintosh X 10.8.5, Chrome 49.0.2623.112, Flash 22.0 (release 0)

**Comment by jwzimmer** [comment]
Hello @Airhogs777, thank you for logging & reporting this issue! We are already tracking it elsewhere, so I am closing this case as a duplicate, but I have added the info you provided here to the other case. Thank you! : )
