### ISSUE TITLE
Scratch Conference: arrange sessions ascending by room number

### ISSUE THREAD

**Issue by sleggss** [LLK/scratch-www#723]
Can we re-arrange panel and workshop sessions to be ascending by room number (starting with the rooms on the second floor and ending with the Silverman Room).

Rooms are:
240
244
E15-341
E15-359
4th Floor LLK Space
493
514b
Auditorium 633
Multipurpose Room
Silverman Room

**Comment by mewtaylor** [comment]
Fixed by https://github.com/LLK/scratch-api/pull/152
