### ISSUE TITLE
Country Shows Up Twice - Teacher Registration

### ISSUE THREAD

**Issue by coke11** [LLK/scratch-www#724]
When registering for a teacher account you need to enter your country twice. First you need to enter it on the 2nd slide, with birth information and gender, and then you must enter it on the 7th slide, with address info.

**Comment by jwzimmer** [comment]
@coke11 Thanks for bringing this up!

**Comment by coke11** [comment]
@jwzimmer -- no problem!

**Comment by thisandagain** [comment]
> I thought we had Country twice to allow people to differentiate between demographic info vs. current address/ address of organization if desired, but maybe that is not the best option?

Yes, that is the thinking. We know of many educators who don't necessarily live / work in the same country.

**Comment by coke11** [comment]
ok
