### ISSUE TITLE
Misalignment of dropdown from navbar

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#728]
On Staging, Firefox

The edge of the dropdown is supposed to be aligned with the edge of the username element, but sometimes it's not.

Production, Chrome, aligned, www page:
<img width="279" alt="screen shot 2016-07-16 at 6 24 56 am" src="https://cloud.githubusercontent.com/assets/1320456/16894224/225494bc-4b1e-11e6-85d2-065f521e3f48.png">
Staging, Firefox, not aligned, www page:
<img width="169" alt="screen shot 2016-07-16 at 6 13 13 am" src="https://cloud.githubusercontent.com/assets/1320456/16894228/22695136-4b1e-11e6-9c37-ed7e01b508de.png">

---

Moved from LLK/scratchr2#3837
/cc @jwzimmer @carljbowman

**Comment by thisandagain** [comment]
We should limit this scope to just the navigation bar for `www`.

**Comment by jwzimmer** [comment]
Staging, Safari, not aligned:
<img width="205" alt="screen shot 2016-07-26 at 4 34 16 pm" src="https://cloud.githubusercontent.com/assets/1320456/17154399/e48b18ac-534e-11e6-8d46-f0574057632c.png">

**Comment by jwzimmer** [comment]
Still seeing this, Staging, IE 11 on Win 7 VM:
<img width="295" alt="screen shot 2016-08-17 at 2 55 50 pm" src="https://cloud.githubusercontent.com/assets/1320456/17749317/22fd3bfe-648b-11e6-9240-0a86da3ea548.png">
<img width="582" alt="screen shot 2016-08-17 at 2 55 26 pm" src="https://cloud.githubusercontent.com/assets/1320456/17749316/22fbbbee-648b-11e6-8130-075c6af8e4fe.png">

**Comment by St19Galla** [comment]
I am seeing this on production in Safari
<img width="272" alt="screen shot 2016-08-20 at 11 40 46 am" src="https://cloud.githubusercontent.com/assets/16446551/17832192/0da761fc-66cb-11e6-8127-51a30238f0bf.png">

**Comment by jwzimmer** [comment]
@St19Galla thanks!

**Comment by TheGrits** [comment]
@St19Galla Looks like that causes the problem on my end too. My browser is showing that the account nav is actually `148 x 50`:
![screenshot](https://cloud.githubusercontent.com/assets/12952370/18584315/eccc7eb8-7bdd-11e6-84bc-9e1645112961.png)

**Comment by TheGrits** [comment]
I've cracked the case on this one, it's due to a `min-width: 160px;` set over [here](https://github.com/LLK/scratch-www/blob/develop/src/components/dropdown/dropdown.scss#L11).

**Comment by rschamp** [comment]
@TheGrits All yours! ;)
