### ISSUE TITLE
Tweaks to wording/links on educator page

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#734]
As discussed in the web design meeting, we're hoping to have these changes to the wording and links on the Educators page.

The order would shift:

1) Elementary School
The School at Columbia University 

2) Middle School
Cambridge Public Schools

3) Community-Based Program
Plug-In Studio

4) After-School Program
Ghana Coding Club

Does that sound OK?

**Comment by thisandagain** [comment]
Ok. All set. One minor issue is that "Community-Based Program" doesn't quite fit in the card as a headline. How about "Community Program"?

**Comment by thisandagain** [comment]
![image](https://cloud.githubusercontent.com/assets/747641/17004328/813b6690-4ea2-11e6-8cf5-53b9c8dd430d.png)

**Comment by ntlrsk** [comment]
@thisandagain Thanks - it's helpful to see the revised state! Now thinking I should have done plural "Elementary Schools" "Middle Schools" etc. -

(We can think for the future if we should put in Universities instead of the Community Program, and also also whether it should indicate more clearly that these are examples).

**Comment by thisandagain** [comment]
Not a problem. All set:
![image](https://cloud.githubusercontent.com/assets/747641/17022916/b41387a6-4f1e-11e6-955b-6a4628998bf8.png)
