### ISSUE TITLE
Swap Teacher Account image on Educators page 

### ISSUE THREAD

**Issue by SpeakkVisually** [LLK/scratch-www#737]
Mitch requested a different image to show Teacher accounts on Educator page. I've attached a screenshot to be used...

Screenshot:
![image](https://cloud.githubusercontent.com/assets/5166432/17024916/a68467be-4f27-11e6-820b-32c12a78959d.png)

Asset to be replaced:
![image](https://cloud.githubusercontent.com/assets/5166432/17024987/ea4d7daa-4f27-11e6-9427-7d02c05bc9ef.png)

**Comment by carljbowman** [comment]
New Asset

![teacher-account](https://cloud.githubusercontent.com/assets/3409578/17025754/5b31c92e-4f2b-11e6-8491-054e7898aaa5.png)
