### ISSUE TITLE
Educator Page tweaks

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#740]
@carljbowman , take a look below and let me know your thoughts. 

Changes below:

- [x] Rename anchor link 'In Practice' to 'Who Uses Scratch'
- [x] In-Person Gatherings text is incomplete. It should be:

[Scratch Educator Meetups](http://www.meetup.com/pro/scratched/) are gatherings of Scratch Educators who want to learn with and from each other, sharing their ideas and strategies for supporting computational creativity in all its forms. 

- [x] 'Who Uses Scratch' - we would like to revisit the layout of the four example cards. Because we are working on a tight deadline, for now we'd like to remove all four cards and either leave it like that for this launch, or add four photos (without links to anything or text) in the same horizontal layout. The four photos will be added below once I have them:

**Comment by thisandagain** [comment]
> Rename anchor link 'In Practice' to 'Who Uses Scratch'
Resolved in #734

**Comment by thisandagain** [comment]
"Who Uses Scratch" now looks like:
![image](https://cloud.githubusercontent.com/assets/747641/17032687/974c637a-4f48-11e6-94bb-55237d0d0298.png)
