### ISSUE TITLE
Modify 'Who Uses Scratch' section 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#742]
We need to rethink and possibly redesign the educator example row. This is a placeholder issue since we need to have a larger conversation before we're ready to assign to a developer.

**Comment by ntlrsk** [comment]
Thanks @kaschm Adding @mresmres - He suggested having quotes from educators.

**Comment by thisandagain** [comment]
https://github.com/llk/scratch-www/issues/740
