### ISSUE TITLE
There is no option to log out once logged in as a student with incomplete registration

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#752]
Seems like we need a log out button like "Not you? Log in as another user" on that first step

/cc @carljbowman @kaschm @thisandagain

**Comment by rschamp** [comment]
There's also no indication of who is logged in on that first step. This is mostly relevant to the case of a user who logs in, doesn't complete registration, then walks away from a public computer. Scratch is basically not functional until someone finishes the registration.

**Comment by thisandagain** [comment]
@carljbowman Can we get a design for this before EOD?

**Comment by carljbowman** [comment]
![r3_1by1_student-join](https://cloud.githubusercontent.com/assets/3409578/17156336/4c1def3c-5357-11e6-8213-8c0c5e56d32a.png)

@thisandagain @kaschm @rschamp hows this? Tried a few other options and nothing felt quite right. We could consider losing the [teacher icon] as the page is starting to feel awkward.

**Comment by carljbowman** [comment]
An alternative

## Placeholders 
![r3 2_1by1_student-join](https://cloud.githubusercontent.com/assets/3409578/17170231/24769986-53b9-11e6-91f1-8a65efe08ed7.png)

## Mock Content
![r3 2_1by1_student-join2](https://cloud.githubusercontent.com/assets/3409578/17170236/287e7878-53b9-11e6-9fd5-671685e02a07.png)

**Comment by thisandagain** [comment]
👍  on the alternate version.

**Comment by carljbowman** [comment]
@thisandagain - Agreed. Thanks for review. 

In the Registration Link flow it makes the most sense to highlight the Teacher Username & Class Name as those are the only pieces of information connecting the user to a Classroom. 

Although in the case of CSV & One-by-one the Student Username feels a bit more unique to the individual user joining, while Teacher Username & Class Name become contextual information. This should also help with some concern about username confusion. 

@rschamp - If the Student clicks the Scratch logo or leaves the Join Flow are they put back into a Logged Out state?

**Comment by rschamp** [comment]
@carljbowman No, if they click the Scratch logo or go anywhere on the site, they are forced right back into this flow — hence this issue.  I think it would be unexpected for the logo to log out the user.

**Comment by rschamp** [comment]
Fixed in #765.  @carljbowman Please check out the design live when you have a chance.
