### ISSUE TITLE
Buttons outside password reset dialog box on Safari

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#756]
<img width="650" alt="screen shot 2016-07-25 at 4 45 38 pm" src="https://cloud.githubusercontent.com/assets/399209/17118099/45d162d2-528d-11e6-921a-487d959aa70a.png">

buttons misaligned on student password reset dialog - in Safari

**Comment by mewtaylor** [comment]
moved to https://github.com/LLK/scratchr2/issues/3869
