### ISSUE TITLE
"Empty" waiting room should redirect to "My Classes"

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#757]
Staging, IE 11 on Windows 8.1

This one is a little hard to repro on staging, but the use case is pretty clear: imagine being a teacher who is attempting to create a Teacher Account. You go through the process and verify your email address. You then need to wait the X hours to have your account verified but you are antsy and keep the "Waiting Room" page open in a tab and keep hitting "refresh" from time to time to see if it has gone through yet.

## Repro
- Create new Teacher Account
- Complete email verification and return to "Waiting Room"
- Once waiting period ends, hit "refresh"

## Expected
- Redirected to "My Classes"

## Actual
- See "empty" waiting room with link to resources

## Reference
![image](https://cloud.githubusercontent.com/assets/747641/17145899/48f13daa-532a-11e6-8040-09ef595bd5f8.png)

**Comment by mewtaylor** [comment]
fixed in https://github.com/LLK/scratch-www/pull/761
