### ISSUE TITLE
Teacher & Class Profile Pics not showing up in Student Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#764]
~~I am not sure if this is a real issue... maybe it is caused by caching?~~

I have only seen the default images used for the teacher thumbnail and class thumbnail when I have been using student registration. I changed some of the pictures hours ago, but never saw them show up during registration. I also restarted the browser (Chrome), cleared history (Safari), emptied the cache (Safari), and did a hard refresh (Chrome), but still haven't seen the updated pics (still defaults).

Safari & Chrome, re https://github.com/LLK/scratch-www/pull/744.

**Comment by jwzimmer** [comment]
I'm now seeing the class pic show up, but the teacher icon is still default:
(Staging, Chrome)
<img width="451" alt="screen shot 2016-07-26 at 2 09 27 pm" src="https://cloud.githubusercontent.com/assets/1320456/17185451/21cd19a8-53ff-11e6-85f2-2326aadb125c.png">

**Comment by jwzimmer** [comment]
(Confirmed by @rschamp that the teacher icon not showing up is a bug.)

**Comment by rschamp** [comment]
Class photo showing up because I updated the api-staging `IMAGE_HOST`. Now fixing the issue where the user's _profile_ id is being used to construct the image urls.

**Comment by rschamp** [comment]
The educator thumbnail issue is moot due to #765. But the underlying issue is fixed in LLK/scratch-api#160.
