### ISSUE TITLE
Should password reset actions (by teacher on behalf of student) cancel each other out?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#768]
Re https://github.com/LLK/scratch-www/pull/744.

This is definitely an edge case, but what should happen if a teacher prompts a student to change their password, then manually resets it? Currently, the prompt & the manual reset both take place, so as a student, I use the password my teacher manually reset to log in, then get redirected to the password reset page. I think maybe that one action should cancel out the other, so whatever action the teacher took most recently re the student's password should cancel out previous actions - in this case, I'd log in using the new password and **not** get redirected to the password reset page...? /cc @rschamp & @kaschm

**Comment by kaschm** [comment]
I also think that the most recent action should win. 

@rschamp, thoughts?

**Comment by jwzimmer** [comment]
@kaschm I opened this in the wrong repo, sorry! Moving it to scratchr2.
