### ISSUE TITLE
Fields extending off edge of screen in Edge - Student & Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#769]
Staging, MS Edge Win 10 (scratch-qa)

I was considering putting this in https://github.com/LLK/scratch-www/issues/758 but I think this issue is different enough to be its own case.

Repro:
- Go to staging
- Log in as a student registered via + New Student button
- Go through registration

![screenshot from 2016-07-27 15-15-26](https://cloud.githubusercontent.com/assets/1320456/17192073/f1328aa0-541a-11e6-948e-8ff130b08bf8.png)
![screenshot from 2016-07-27 15-15-12](https://cloud.githubusercontent.com/assets/1320456/17192069/f12df6ac-541a-11e6-9534-437022f49130.png)

Teacher registration -
![screenshot from 2016-07-27 14-41-54](https://cloud.githubusercontent.com/assets/1320456/17192070/f12e47d8-541a-11e6-8ff0-e72a9a9b7e8b.png)
![screenshot from 2016-07-27 14-41-08](https://cloud.githubusercontent.com/assets/1320456/17192074/f1366148-541a-11e6-875e-f218bdf1d3e4.png)

**Comment by jwzimmer** [comment]
I'm also seeing this with the join-from-link workflow, e.g. https://staging.scratch.mit.edu/classes/80/register/50c71e56fafa49a783bcf93f4b3fde04

**Comment by rschamp** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/780
