### ISSUE TITLE
Wrong card used for register link

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#770]
This context should use the old card. /cc @rschamp 

Repro:
- Go to https://staging.scratch.mit.edu/classes/80/register/50c71e56fafa49a783bcf93f4b3fde04

<img width="455" alt="screen shot 2016-07-27 at 5 17 14 pm" src="https://cloud.githubusercontent.com/assets/1320456/17192835/3b88d1ba-541e-11e6-98e5-f6e102407624.png">

From https://github.com/LLK/scratch-www/pull/765

**Comment by rschamp** [comment]
fixed in #777

**Comment by jwzimmer** [comment]
@rschamp I thought we did get rid of the teacher photo in the first student registration card... was that only for CSV/ +NewStudent students?

http://scratch.mit.edu/classes/294/register/f6e80f9dd2a0478a9c9023df8763f52b
<img width="475" alt="screen shot 2016-08-01 at 2 31 14 pm" src="https://cloud.githubusercontent.com/assets/1320456/17304669/abf16924-57f4-11e6-906c-29c9c7e7fd03.png">

**Comment by rschamp** [comment]
The teacher photo should be displayed when registering for a class as a new user. If you are completing your registration as a teacher-created student, then you will see the other card.
