### ISSUE TITLE
Validations misaligned - student registration & teacher registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#771]
I think something happened to make the alignment worse. There were some alignment issues last release, but @mewtaylor fixed some of them, and a lot of the fields were aligned properly. Now a lot of them are not.

<img width="759" alt="screen shot 2016-07-27 at 5 43 39 pm" src="https://cloud.githubusercontent.com/assets/1320456/17193691/36ee908c-5422-11e6-9b82-25c038da80df.png">
<img width="613" alt="screen shot 2016-07-27 at 5 43 01 pm" src="https://cloud.githubusercontent.com/assets/1320456/17193692/36f2a9ba-5422-11e6-856d-766e17897d98.png">

Misaligned validations in student registration from https://github.com/LLK/scratch-www/issues/758:

Password field validation is misaligned:
<img width="613" alt="screen shot 2016-07-26 at 2 15 17 pm" src="https://cloud.githubusercontent.com/assets/1320456/17149925/701af838-533b-11e6-9ca4-b386aeba2351.png">

Misaligned gender validation:
<img width="483" alt="screen shot 2016-07-26 at 2 17 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/17149985/b05e0ab6-533b-11e6-83a2-3455a83187f1.png">

**Comment by jwzimmer** [comment]
<img width="542" alt="screen shot 2016-07-27 at 5 54 25 pm" src="https://cloud.githubusercontent.com/assets/1320456/17193913/3c48dcc6-5423-11e6-9d10-c1702ea598f9.png">
<img width="535" alt="screen shot 2016-07-27 at 5 54 13 pm" src="https://cloud.githubusercontent.com/assets/1320456/17193914/3c4e816c-5423-11e6-9dbe-fa9a4be07f4b.png">

**Comment by jwzimmer** [comment]
<img width="586" alt="screen shot 2016-07-27 at 5 56 35 pm" src="https://cloud.githubusercontent.com/assets/1320456/17193986/7ec8dcc2-5423-11e6-994e-413bb60384c4.png">

**Comment by jwzimmer** [comment]
Validation for "type of organization":
<img width="518" alt="screen shot 2016-07-27 at 5 59 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/17194105/5b2c0d9c-5424-11e6-9994-c014956e7b65.png">

**Comment by jwzimmer** [comment]
(Talking with @rschamp about this - if it's not a real bug I'll close it, if it is a real bug, it's a blocker.)

**Comment by jwzimmer** [comment]
@rschamp looked in sauce, and this seems to be caused by Chrome 51 vs. 52.

I'm using Chrome Version 52.0.2743.82 (64-bit) & Mac 10.11.5 (15F34).

**Comment by rschamp** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/778
