### ISSUE TITLE
Country dropdown defaults to United States for student & teacher registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#772]
In the spec it defaults to "select country" everywhere, I think. (See https://github.com/LLK/scratchr2/issues/3679.)

In Address in Teacher Registration, it defaults to "select country", but in the demographic info for students & teachers, it defaulted to United States.
<img width="521" alt="screen shot 2016-07-27 at 6 28 33 pm" src="https://cloud.githubusercontent.com/assets/1320456/17194795/12e79d4a-5428-11e6-9ff2-ef4f5cd4ef34.png">

/cc @carljbowman

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/779
