### ISSUE TITLE
Type of Organization includes "afterscool" typo - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#773]
<img width="224" alt="screen shot 2016-07-27 at 6 25 26 pm" src="https://cloud.githubusercontent.com/assets/1320456/17194733/9830cc48-5427-11e6-9d1e-541966971d2c.png">
<img width="481" alt="screen shot 2016-07-27 at 6 25 48 pm" src="https://cloud.githubusercontent.com/assets/1320456/17194732/982a5f2a-5427-11e6-9c96-39b0e0c32876.png">

**Comment by mewtaylor** [comment]
fixed in https://github.com/LLK/scratch-www/pull/779
