### ISSUE TITLE
Differences in join-by-link student workflow on staging vs. spec

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#774]
I can't access @kaschm's word doc, so apologies if some of this stuff is obsolete. Found while testing https://github.com/LLK/scratch-www/pull/730 & https://github.com/LLK/scratchr2/issues/3679.

Chrome 52, Staging
- The blue info speech bubble is 2 lines in the spec vs. 3 on staging
- There is a line above the username field saying not to use your real name on staging vs. in the spec
  <img width="808" alt="screen shot 2016-07-27 at 6 37 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/17195019/790c8fee-5429-11e6-8e94-65835a007904.png">
- Country dropdown: https://github.com/LLK/scratch-www/issues/772
- All of the same issues mentioned here: https://github.com/LLK/scratch-www/issues/758
- Exclamation point on staging vs. in spec:
  <img width="549" alt="screen shot 2016-07-27 at 6 47 22 pm" src="https://cloud.githubusercontent.com/assets/1320456/17195224/a1b65690-542a-11e6-82e5-c74087c3cdd5.png">

**Comment by kaschm** [comment]
Shared the document with you, @jwzimmer. Sorry about that. 

Regarding text:
- 'Create a Username' **should** have helper text 
- 'Hurray! Welcome to Scratch!' - I'm not concerned about the extra exclamation point, I kind of like it. Let's keep it.
