### ISSUE TITLE
Misaligned validations in student join flow in IE11

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#775]
I put this in a separate issue from the Chrome validations, but we can combine them if that's preferred.

IE11, Win7 VM, Staging

For example:
- Repro by following steps at https://staging.scratch.mit.edu/classes/80/register/50c71e56fafa49a783bcf93f4b3fde04
<img width="276" alt="screen shot 2016-07-27 at 6 55 27 pm" src="https://cloud.githubusercontent.com/assets/1320456/17195441/b90499c8-542b-11e6-9d9b-05a30149ac0f.png">

**Comment by jwzimmer** [comment]
Teacher registration:
<img width="610" alt="screen shot 2016-07-27 at 7 28 30 pm" src="https://cloud.githubusercontent.com/assets/1320456/17196160/8255ce2e-5430-11e6-9714-33cccfd0fc0d.png">
<img width="634" alt="screen shot 2016-07-27 at 7 28 16 pm" src="https://cloud.githubusercontent.com/assets/1320456/17196159/825469e4-5430-11e6-9949-a8ddae35ef65.png">

**Comment by jwzimmer** [comment]
After clearing all my browser history, I'm still seeing misalignments in the student join flow in IE 11 (on Win7 VM), on production:
(Using the link to join class 294 from teachertest123)
<img width="486" alt="screen shot 2016-08-01 at 3 16 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/17305906/14f6850c-57fb-11e6-8c37-e9f35e80c113.png">

**Comment by jwzimmer** [comment]
Misaligned gender validation in the X direction (from saucelabs):
<img width="604" alt="screen shot 2016-08-01 at 4 28 59 pm" src="https://cloud.githubusercontent.com/assets/1320456/17307856/1feef2be-5805-11e6-891b-d788d32c5806.png">

This is the only issue we're (@mewtaylor & I) are seeing on staging, so not a blocker!

**Comment by jwzimmer** [comment]
(Note that not everything in this case has been fixed in https://github.com/LLK/scratch-www/pull/786; the x alignment for the Other fields still exists. See that PR for more context.)

**Comment by mewtaylor** [comment]
The last part of this issue is fixed in https://github.com/LLK/scratch-www/pull/858
