### ISSUE TITLE
Misaligned validations with student & teacher registration in Edge (Win 10 VM)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#776]
Repro:
- Go to staging
- Log in as a student registered via + New Student button
- Go through registration

![screenshot from 2016-07-27 15-15-26](https://cloud.githubusercontent.com/assets/1320456/17192073/f1328aa0-541a-11e6-948e-8ff130b08bf8.png)
![screenshot from 2016-07-27 15-15-12](https://cloud.githubusercontent.com/assets/1320456/17192069/f12df6ac-541a-11e6-9534-437022f49130.png)

![screenshot from 2016-07-27 14-41-54](https://cloud.githubusercontent.com/assets/1320456/17192070/f12e47d8-541a-11e6-8ff0-e72a9a9b7e8b.png)
![screenshot from 2016-07-27 14-41-08](https://cloud.githubusercontent.com/assets/1320456/17192074/f1366148-541a-11e6-875e-f218bdf1d3e4.png)

**Comment by thisandagain** [comment]
The same approach that we took with IE 11 (using the responsive style of validation error display) should also be applied to Edge.

**Comment by rschamp** [comment]
This misalignment was fixed by the same thing that fixed Chrome 52 #778
