### ISSUE TITLE
Oversized Image on Jobs page - MOBILE

### ISSUE THREAD

**Issue by St19Galla** [LLK/scratch-www#781]
On the jobs page, when completely zoomed out, the image stretches a bit too far to the right causing the page to display unnecessary blue-space. This occurs on my iPhone 5s on Safari. This could easily be fixed (if desired) by simply cropping and/or shrinking the image. However, I'm not sure of the design preference. See here: 
![image](https://cloud.githubusercontent.com/assets/16446551/17218161/d50e62c8-54b4-11e6-8ff5-43a8a2478763.png)

**Comment by St19Galla** [comment]
@technoboy10 if it would help you, I could take this one :) I would just need to know whether you guys would prefer cropping or resizing the image. 

If you view the page on a normal computer, you can see that the image stretches ~40px too far to the right of the paragraph text. Changing the width (while maintaining the height ration) from 980px to 940px realigns the image and should fix the extra blue space. I have not tested this on mobile, though.

**Comment by technoboy10** [comment]
@St19Galla No worries, seems like it's gonna be a quick fix (just setting the img element's width to 100% seems to produce the desired behavior). Thanks for your help though! :D
