### ISSUE TITLE
Type of Organization > Other is not a required field but Type of Organization is - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#797]
Chrome 52, Mac

If you choose the "Other" option for Type of Organization during Teacher Registration, you don't have to fill out the Other field. Since Type of Organization is required and Other is a field within it rather than just the option "Other" (text), I think this is a little bit inconsistent, but not the worst behaviour... Is it supposed to be required, @carljbowman & @kaschm?

<img width="441" alt="screen shot 2016-08-01 at 3 42 25 pm" src="https://cloud.githubusercontent.com/assets/1320456/17306632/0fa94e8c-57ff-11e6-826e-5814d1c3a951.png">

**Comment by kaschm** [comment]
I think it should be required. @carljbowman ?

**Comment by carljbowman** [comment]
I agree. If the user selects 'Other', then the field should be required and if they attempt to go to the next step having not entered anything a tooltip should prompt them to enter something. 

Long term, we should create a type style ( italic ), for form fields that are pre-populated with a action. For example: 'Select Country' or 'Other'. Something to distinguish the content is temporary.

**Comment by rschamp** [comment]
This used to work — it's a regression.

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/803
