### ISSUE TITLE
Messages/My Stuff icon error - MOBILE

### ISSUE THREAD

**Issue by St19Galla** [LLK/scratch-www#804]
The Messages and My Stuff icons appear white - they are still clickable.
![img_9152](https://cloud.githubusercontent.com/assets/16446551/17350355/13ef4afa-58f4-11e6-93d8-22215260ded5.PNG)

However, I believe this could be because I just updated to the iOS 10 Public Beta. I have not noticed this error before updating to it today. 

The iPhone main update isn't scheduled to be released until the Fall, however, I think it would be a good idea to get ahead - whatever's causing it.

**Comment by St19Galla** [comment]
Hmmm. The My Stuff icon seems to have been fixed, but I am still experiencing the problem with the Messages icon.

**Comment by thisandagain** [comment]
This appears to be a documented issue with SVG rendering in iOS 10 that Apple is tracking. Will re-open should this bug appear in the release.
