### ISSUE TITLE
Add link to TA YT video in TA FAQ 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#805]
Add link to YouTube video that shows details of Teacher Accounts in the following first paragraph of the TA FAQ (scratch.mit.edu/educators/faq):

**What are teacher accounts?**
A Scratch Teacher Account provides teachers and other educators with additional features to manage student participation on Scratch, including the ability to create student accounts, organize student projects into studios, and monitor student comments. Learn more about Teacher Accounts in [this video](https://www.youtube.com/watch?v=7Hl9GxA1zwQ).

**Comment by rschamp** [comment]
Fixed in #807
