### ISSUE TITLE
Can't register a new account

### ISSUE THREAD

**Issue by St19Galla** [LLK/scratch-www#813]
Scratch will not let me register a new account. This seems to happen on Safari and Chrome on my Mac. I have confirmed that this problem does happen with 3 other Scratch users. When clicking "Join Scratch", the page dims and the exit button appears, but nothing else. The page looks like this: 
<img width="1277" alt="screen shot 2016-08-05 at 2 44 56 pm" src="https://cloud.githubusercontent.com/assets/16446551/17447215/38f6ef82-5b1b-11e6-9321-c6ce35722966.png">

It is still possible to register at https://scratch.mit.edu/accounts/standalone-registration/ . Should the "Join Scratch" button be linked to there until this problem is resolved?

**Comment by technoboy10** [comment]
Just reproduced on Chrome 51.

Getting this error in the console:
`Refused to display 'https://scratch.mit.edu/accounts/standalone-registration/' in a frame because it set 'X-Frame-Options' to 'DENY'.`

**Comment by technoboy10** [comment]
@colbygk

**Comment by colbygk** [comment]
Currently fixed by adjusting X-Frame-Options to SAMEORIGIN from DENY in scratch-www-production.

**Comment by St19Galla** [comment]
Can confirm it is now working. :) Thanks Codubee!

**Comment by ToonTalk** [comment]
Why restrict iframes to SAMEORIGIN? I'm getting

Refused to display 'https://scratch.mit.edu/projects/143083246/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

from https://sites.google.com/site/modelling4allproject/misc/sandpit/scratch-embed

by trying embed a Scratch project in a Google Site.

**Comment by thisandagain** [comment]
@ToonTalk We do not support running Scratch in iframes due to security. If you would like to embed a Scratch project, you can do so using the "embed" link:
`//scratch.mit.edu/projects/embed/143083246/?autostart=false`

**Comment by ToonTalk** [comment]
But the embed link is an iframe.

![image](https://cloud.githubusercontent.com/assets/2138696/22575460/8b26985c-e9f0-11e6-9804-30104d0c441e.png)

When I click on Embed at https://scratch.mit.edu/projects/143294979/

**Comment by mewtaylor** [comment]
@ToonTalk yes the embed link is an iframe. As @thisandagain mentioned, we have designated a specific url type – the "embed" link – to be available in the way you're describing. The `src` link in the `iframe` example you share above seems to be using that embed link too (see how it says `/projects/embed/<id>` rather than `/projects/<id>`).

**Comment by ToonTalk** [comment]
Thanks. All is clear now and working.

I wonder if the Share page needs to be enhanced to make this clearer to those embedding by using a site like Google Sites that asks for the URL to embed as an iframe.

Out of curiousity is there somewhere that explains what the security issue is that this addresses? Snap! for example doesn't seem to restrict the use of project URLs in embeddings.

**Comment by TheGrits** [comment]
@ToonTalk If I may chip in here, Same-origin policies are actually a web standard for security, preventing malicious XSS or injected script attacks. MDN has documentation on Same-origin policy here: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy Wikipedia also has an example of why Same-origin policies are important here: https://en.wikipedia.org/wiki/Same-origin_policy#Security_Concerns

**Comment by ToonTalk** [comment]
Thanks but this isn't a general CORS issue. See

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

which only refers to the danger of [clickjacking](https://en.wikipedia.org/wiki/Clickjacking). I don't see how clickjacking is a danger when Scratch projects are embedded in an iframe.
