### ISSUE TITLE
International phone number parsing

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-www#816]
![teacheraccountbug](https://cloud.githubusercontent.com/assets/192393/17460047/41b4d96a-5c22-11e6-9aca-ca1ac2e90360.png)

As reported by @LiFaytheGoblin  the format above should be valid, no?

**Comment by jwzimmer** [comment]
A user reported this issue via freshdesk no. 54399. His phone number from Ghana was coming up as invalid even though it is his real number (see the ticket for the phone number).

**Comment by thisandagain** [comment]
@mewtaylor Do you have time to take a look at this?

**Comment by mewtaylor** [comment]
@thisandagain @rschamp I'd like to remove the `phoneLength` validation that we have. There are two issues here:
1. Not all country codes have a format included with them
2. It seems like the format might not be correct in all instances. For instance, the format for Germany – `"+.. ... ......."` – does not match the number provided on the embassy website

If it were just 1 as an issue, a code fix would be more than sufficient – but given 2, I think it's best to err on the side of trusting `isPhone` for now.

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/826

**Comment by LiFaytheGoblin** [comment]
@colbygk Ow, I'm glad this was fixed but the reason why I posted this on Slack and not here was because I didn't want my number to be on the Internet... Could that picture be removed please?

**Comment by rschamp** [comment]
Removed @LiFaytheGoblin!

**Comment by colbygk** [comment]
Sorry!
