### ISSUE TITLE
Terms of Use page missing a link

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#822]
Section 2.5 seems to be missing a link to Contact Us of help@scratch.mit.edu (I'm not sure which we want)

![image](https://cloud.githubusercontent.com/assets/3766964/17463421/e6074820-5c92-11e6-9919-87d69aca1c1e.png)

---
Moved from LLK/scratchr2#3920
/cc @Paddle2See

**Comment by thisandagain** [comment]
Yes, this should include a link to `help@scratch.mit.edu`.

**Comment by TheGrits** [comment]
It appears that I was the one who introduced this bug in the first place, when I initially migrated the page. Sorry about that!

**Comment by thisandagain** [comment]
@TheGrits It's ok! Bugs happen. 🐞  We really appreciate all the support!

**Comment by mewtaylor** [comment]
Yeah no worries at all @TheGrits! And thanks for submitting such a quick fix!

**Comment by coke11** [comment]
I noticed this the other day when reading on paper

BTW - Is Paddle in charge of the Terms of Use?

**Comment by mewtaylor** [comment]
@coke11 the reason Paddle was cc'd was because he opened the original issue in a different repo. And thanks for noticing – the fix for this will be in the next release thanks to TheGrits!

**Comment by coke11** [comment]
@mewtaylor Ah ok. I was going to report it as an issue, and then I saw this ;)
