### ISSUE TITLE
Fatal javascript error on Splash page when the width of the page is small

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#831]
`Uncaught TypeError: Cannot read property 'offsetWidth' of undefined`

**Comment by mewtaylor** [comment]
This appears to be an upstream bug in react-slick: https://github.com/akiran/react-slick/issues/357. There is a patch open for it: https://github.com/akiran/react-slick/pull/359, though it's failing tests.

**Comment by mewtaylor** [comment]
@rschamp I'm actually no longer seeing this issue on staging – are you?

**Comment by mewtaylor** [comment]
nvm – was able to finally repro again

**Comment by mewtaylor** [comment]
Though I see this on staging, I do not see this in production currently, just fyi.

**Comment by jwzimmer** [comment]
I haven't repro'd this yet, but it took @mewtaylor a while to repro it, so it might be good to keep trying.

**Comment by jwzimmer** [comment]
Closing for lack of repro.

Staging, Chrome Version 53.0.2785.143 (64-bit), Mac OS X 10.11.6 (15G1004)

I clicked around the website on Staging using all the settings in Chrome's device emulator menu. I also tried clicking around the site and changing the browser width manually.
<img width="143" alt="screen shot 2016-10-13 at 11 52 09 am" src="https://cloud.githubusercontent.com/assets/1320456/19356659/885fe158-913c-11e6-866e-c5d2144b374b.png">

 Staging, IE 11 on Win 7 VM

I can't access Staging on IE 11 on Win 7 VM.
I did see the error `SCRIPT5007: Unable to get property 'style' of undefined or null reference`, but I haven't seen `Uncaught TypeError: Cannot read property 'offsetWidth' of undefined`.

Staging, Firefox 49.0.1 on Win 7 VM

I clicked around the site and changed the browser width to different widths manually, did not see the error.
