### ISSUE TITLE
Teacher Registration - "Something went wrong: Ensure this value has at most 50 chars (it has 51)"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#837]
Reported via freshdesk no. 54811:
> I have attempted to register as a Scratch Educator twice. However, on each occasion, there has been an error on the last stage. The error message informs that there cannot be more than 50 characters in an email address.
> I’ve taken a screenshot of the error message. I have tried it in different browsers, and still have the same error message.

<img width="429" alt="screen shot 2016-08-12 at 10 51 33 am" src="https://cloud.githubusercontent.com/assets/1320456/17626378/127523a0-607b-11e6-85b4-23609916cf57.png">

Metadata: 
- User: None 
- Operating System: Windows NT 10.0 
- Browser: Microsoft Internet Explorer 11.0 
- Flash Version: Flash 21.0 (release 0)

I tried to repro this a bit in **Chrome 52 on Mac OS X El Capitan on Staging**, without success. The email address the user used to contact us has 41 chars (I asked them if that is the email they were using to register, and they did not answer that question, but they did respond to the email, so for now I'm taking that as "yes"). 
- I used (myemail)+ffffffffffffffffff@gmail.com which also has 41 chars to register,  and did not see any error, created jdfhkfjsdff.
- I tried (myemail)+fffffffffffffffffffffffffff@gmail.com which has 50 chars, no error.
- Used (myemail)+ffffffffffffffffffffffffffff@gmail.com which has 51 chars, no error, created osidfg.

I tried to repro this in **IE 11 on Win 7 VM on Production**, also without success.
- I used my email + enough f's to make it 51 chars, did not see any errors, created testteacher1990.

(Could be a field other than email caused this, started with email field b/c the user reported seeing an error message about the email field.)

**Comment by rschamp** [comment]
Related: https://github.com/LLK/scratch-www/issues/835

**Comment by jwzimmer** [comment]
(As discussed with @rschamp and @thisandagain, no longer needs repro by QA.)

**Comment by thisandagain** [comment]
Tracking in #835
