### ISSUE TITLE
ELIFECYCLE error on `make start`

### ISSUE THREAD

**Issue by TheGrits** [LLK/scratch-www#838]
Running node and npm on a Raspberry Pi 2b, git is installed as well.
When I was scanning through the terminal it found an unexpected `=>` for something. I got the debugging log but it doesn't have a reference to the unexpected characters.
Here's the log:
![screenshot 2016-08-12 at 12 30 51 pm](https://cloud.githubusercontent.com/assets/12952370/17629496/a7b3513c-6088-11e6-803f-391702116068.png)

Just a heads up, there are a bunch of deprecated things that the terminal was warning me about. (But I'm pretty sure y'all know about them already)

**Comment by TheGrits** [comment]
Turns out that to fix the problem above, you just need to do rebuild `node-sass`.

Now I have this problem on `npm start`:
![screenshot 2016-08-13 at 1 49 40 pm](https://cloud.githubusercontent.com/assets/12952370/17644747/090832ca-615d-11e6-9264-748f85821b53.png)
(screenshot of copy-pasted terminal return)

**Comment by rschamp** [comment]
@TheGrits You are running Node v0.12.6 but we require Node v4.2.  The error is due to ES6 syntax that the old version of Node doesn't support.

This brings to attention the fact that we don't list this requirement anywhere, so I'll file a bug for that!

**Comment by rschamp** [comment]
@TheGrits I'll close this for now, but please reopen if that doesn't fix your issue

**Comment by TheGrits** [comment]
@rschamp Ah, that makes sense. I'll try updating it later today and see if it helps. Thanks!

**Comment by TheGrits** [comment]
@rschamp Please reopen, updating Node didn't work. 
![screenshot](https://cloud.githubusercontent.com/assets/12952370/17771689/66ea8826-6512-11e6-9367-fc5bab39ce03.png)

**Comment by TheGrits** [comment]
@rschamp Here's the `npm-debug.log` file:
[error.txt](https://github.com/LLK/scratch-www/files/424750/error.txt)

**Comment by rschamp** [comment]
This looks like the original error you had in this report, which you said you resolved by rebuilding node-sass.  Does that still resolve the issue?

**Comment by TheGrits** [comment]
@rschamp Ah, thanks for the gotcha. I had forgotten that I cleared the npm cache to install the new version of node, I didn't think that I would need to rebuild `node-sass`.

Now the terminal is returning errors on `npm install` because I've maxed out my storage on the SD card. I'll figure out what I can get off the card and see if it goes through.

Many thanks!

**Comment by mewtaylor** [comment]
@TheGrits glad to hear it's improving! Should we close this issue now, or are you still running into issues with the repo?

**Comment by TheGrits** [comment]
@mewtaylor No issues besides the SD card issue atm, I'll close it for now. If I bump into anything more I'll let you guys know. Thanks!
