### ISSUE TITLE
Teacher FAQ page: Add link to request a teacher account

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#843]
I wonder if it may be helpful to add the link to register for a Teacher Account on the Teacher FAQ page (https://scratch.mit.edu/educators/faq)?

Perhaps adding a question early on: "How do I request a teacher account?"

And answering something like this:
"To request a Teacher Account, please visit: https://scratch.mit.edu/educators/register"

@kaschm What do you think?

**Comment by kaschm** [comment]
:+1: I'll add this to the next iteration. Thanks!

**Comment by kaschm** [comment]
@mewtaylor - do you have time to get this done for this iteration? If not, feel free to move it to sept. Thanks!

**Comment by mewtaylor** [comment]
@kaschm doing it now!

**Comment by mewtaylor** [comment]
@ntlrsk @kaschm thoughts?
<img width="732" alt="screen shot 2016-08-17 at 7 57 11 am" src="https://cloud.githubusercontent.com/assets/1815772/17735463/4b07170e-6450-11e6-889f-e081ae5e439e.png">

**Comment by kaschm** [comment]
:+1:

**Comment by ntlrsk** [comment]
Thanks for working on this @mewtaylor 

 I think that the info on how to register should come as the first question. I would make the link on something more descriptive than "page".

Perhaps move down the questions email to the last - basically if the other answers haven't addressed the problem.

**Comment by ntlrsk** [comment]
"To request a teacher account, go to the [teacher account request form]().

**Comment by ntlrsk** [comment]
Another minor wording suggestion:  the one about Scratch Ed accounts, I'd suggest wording this question: "Are Scratch Teacher accounts linked to ScratchEd accounts?"  "No, Scratch Teacher accounts are not linked to ScratchEd accounts."

**Comment by ntlrsk** [comment]
My suggested ordering would be to move the last 3 questions first.

**Comment by mewtaylor** [comment]
@ntlrsk @kaschm how about this?
<img width="784" alt="screen shot 2016-08-17 at 9 46 23 am" src="https://cloud.githubusercontent.com/assets/1815772/17738518/888594fc-645f-11e6-879f-f10a1297ed58.png">

**Comment by ntlrsk** [comment]
Looks great to me!
