### ISSUE TITLE
make resource icons clickable on Educators page

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#850]
I wonder if the icons could be clickable to get to each of the three resources on the Educators page:
![image](https://cloud.githubusercontent.com/assets/4721032/17702582/856fafc8-639c-11e6-84c3-b138da2fbd0f.png)

**Comment by St19Galla** [comment]
I can take this one if it helps :)

**Comment by mewtaylor** [comment]
@St19Galla go for it! feel free to tag me in the PR when you've finished.
