### ISSUE TITLE
Revise Community Guidelines to mention personally identifying social media sites

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#853]
#### Keep personal info private
For safety reasons, don't give out any information that could be used for private communication - such as real last names, phone numbers, addresses, email address, links to social media sites or chat rooms.

---
Moved from LLK/scratchr2#3923
/cc @ntlrsk @paddle2see

**Comment by Paddle2See** [comment]
Probably should be plural: email addresses

**Comment by Paddle2See** [comment]
The version approved in the last Community meeting:

For safety reasons, don't give out any information that could be used for private communication - such as real last names, phone numbers, addresses, email addresses, links to social media sites or websites with unmoderated chat.

**Comment by TheGrits** [comment]
@mewtaylor I can take this one for you if you'd like.

**Comment by mewtaylor** [comment]
@TheGrits thanks for the help :). Go for it!
