### ISSUE TITLE
Add 10 new cards to /cards page

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#856]
New resources! 

We have ten new cards to be added to the /cards page on Scratch. Follow current design pattern (name of theme / img of card / link to PDF). 

Currently blocked on final content from @ntlrsk, including any potential call-out to No Starch Press

**Comment by ntlrsk** [comment]
Here's the suggested order for revising the cards page (they will go across):

Starter Cards [current link OK]
Animate Your Name [current link OK]
Race to the Finish    RaceGameCards.pdf
Make Music    MusicCards.pdf
Hide and Seek [current link OK]
Pong Game    PongCards.pdf
Let’s Dance   [<--- note change in that title, current link OK] 
Catch Game    CatchCards.pdf
Virtual Pet    PetCards.pdf

**Comment by ntlrsk** [comment]
We'll wait on Story and Dress-Up since we don't have the online tutorials in the Tips window yet.

**Comment by ntlrsk** [comment]
The new thumbnail images for all the cards are here: 
https://www.dropbox.com/sh/j6lwfpifspicl3m/AADZUC4NnhpN7skHk7HJ4C44a?dl=0

**Comment by mewtaylor** [comment]
@ntlrsk I'm seeing "Hide and Seek" have a title of "Hide and Show" in the pdf – should I change the name here too?

**Comment by ntlrsk** [comment]
@mewtaylor Thanks for checking. "Hide and Show" is the name of that first card. We actually changed that card in the new versions to "Disappear" because of that confusion.  (I haven't put up the new Hide cards yet because the tutorial still shows the We Bare Bear version and the new one will be Gobo-based.).

**Comment by mewtaylor** [comment]
@ntlrsk thanks! Will the gobo-based one be part of this before the freeze?
