### ISSUE TITLE
Update FAQ page

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#860]
Currently, the FAQ says here 

https://scratch.mit.edu/info/faq/#permissions

"Where can I find the source code for Scratch?
The source code for Scratch 2 (website and editor) is not yet available. The source code for Scratch 1.4, written in Squeak, is available on GitHub. The source code for the first version of the Scratch website - ScratchR - is available on Assembla."

However, the source code for the Scratch 2 editor is now available here

https://github.com/LLK/scratch-flash

---
Moved from LLK/scratchr2#3969
/cc @Paddle2See

**Comment by St19Galla** [comment]
"The source code for Scratch 2 ([website](https://github.com/LLK/scratch-www) and [editor](https://github.com/LLK/scratch-flash)) is currently available on Github. For more information on Scratch open source Projects see the [Developers](https://scratch.mit.edu/developers) page. The source code for Scratch 1.4, written in Squeak, is available on GitHub. The source code for the first version of the Scratch website - ScratchR - is available on Assembla."

@thisandagain Does this look good^? :)

**Comment by thisandagain** [comment]
Let's do (via @kaschm ):

**Where can I find the source code for Scratch?**
The source code for the Scratch 2 editor can be found on [Github](https://github.com/LLK/scratch-flash). The source code for Scratch 1.4, written in Squeak, is also available on GitHub. For updated information on development projects relating to the Scratch website, please visit our [Developer Page](scratch.mit.edu/developers).

**Comment by St19Galla** [comment]
Okay! Working on it now :)
