### ISSUE TITLE
Remove "X-Frame-Options" from meta tags

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#862]
### To Reproduce
- Go to `https://scratch.mit.edu/` with the inspector open

### Expected
- No console errors

### Actual
`scratch.mit.edu/:9 X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.`

**Comment by TheGrits** [comment]
Was mentioned in #809 but I'm not sure that it was actually done? (Perhaps it's just not on production yet?)

**Comment by thisandagain** [comment]
Resolved in #809
