### ISSUE TITLE
Update Scratch Conference homepage

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#864]
Current homepage reads:
“Watch the keynote live”

Change text to:
“Watch videos of the keynote sessions”

[link is the same]

**Comment by St19Galla** [comment]
I can quickly fix this :)

**Comment by mewtaylor** [comment]
@St19Galla go for it :). Thanks!

**Comment by sleggss** [comment]
Thanks for the text changes! Can we update the link to:

https://youtu.be/alsfSTVn2es?list=PLpfxVARjkP-8chnTrjtDeo88Pcz6-xf_B

**Comment by sleggss** [comment]
Moving the link change to a [new issue](https://github.com/LLK/scratch-www/issues/918).
