### ISSUE TITLE
Dismiss "What's Happening" Content from Homepage?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#866]
I'm not sure what I did, but I got the homepage into a state where there was a little X icon ("dismiss" tool tip text) in the corner of "What's Happening", and when I clicked it, the content was cleared. However, when I view the What's Happening box on staging and production now, I'm not seeing the X... (for a teacher account or my admin account jwzimmer1990).

<img width="577" alt="screen shot 2016-08-22 at 11 21 17 am" src="https://cloud.githubusercontent.com/assets/1320456/17861260/52908b42-685e-11e6-926e-dbd74d70f50f.png">
<img width="580" alt="screen shot 2016-08-22 at 11 21 30 am" src="https://cloud.githubusercontent.com/assets/1320456/17861259/5285a86c-685e-11e6-8f88-345f28863075.png">

**Comment by jwzimmer** [comment]
Actually, I'm not sure if this is a bug or if you're supposed to be able to do that... looking at more things...

**Comment by TheGrits** [comment]
@jwzimmer This is the new Scratcher state of the 'What's Happening' box. If you need to repro, try making a new account and seeing if it shows up.

**Comment by jwzimmer** [comment]
@TheGrits Yeah, I figured out what happened, thanks - my bad. : )
