### ISSUE TITLE
"Oops something went wrong" error with blank username field - Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#872]
**Staging**

If you fill out the fields after getting this error, you can continue to the next page, and it doesn't seem to cause an error at the end of registration.

**Safari Version 9.1.2 (11601.7.7), Mac OS X El Capitan**
- Just from typing in a few known usernames to test out the validation (I didn't click next, just clicked in between username and password fields, I got this error:
  (404 error)
  (URL in the error was https://[staging]/accounts/check_username//)

<img width="584" alt="screen shot 2016-08-22 at 5 57 02 pm" src="https://cloud.githubusercontent.com/assets/1320456/17873260/8740418c-6892-11e6-89ba-85e28cf7f252.png">
- Repro'd by trying different names, typing in password field, going back and forth between the two fields (did not click Next):

<img width="259" alt="screen shot 2016-08-22 at 6 08 25 pm" src="https://cloud.githubusercontent.com/assets/1320456/17873421/7ab49084-6893-11e6-970b-79a86947da1c.png">
<img width="350" alt="screen shot 2016-08-22 at 6 08 16 pm" src="https://cloud.githubusercontent.com/assets/1320456/17873420/7ab35020-6893-11e6-91e6-d068352f49f0.png">

In Safari on Mac (see comment above), I'm still seeing this error after clearing cache and history. I see it in **Chrome 52**, too. The repro steps are: go to `educators/register`, click Next, put your cursor in username field, click Next again.
<img width="554" alt="screen shot 2016-08-23 at 1 30 44 pm" src="https://cloud.githubusercontent.com/assets/1320456/17902662/193f7df2-6936-11e6-8793-9f76f6e4330d.png">

**Comment by jwzimmer** [comment]
@kaschm, I moved this case to September + prio-medium based on [this discussion](https://github.com/LLK/scratch-www/pull/803#issuecomment-241819345) with @mewtaylor. If you don't think that prioritization is appropriate, please feel free to change it. : )

**Comment by kaschm** [comment]
Thanks @jwzimmer , looks right to me.
