### ISSUE TITLE
Do we want to keep double search bars on new Search page?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#875]
From discussion with @carljbowman re https://github.com/LLK/scratch-www/pull/871, once we have implemented https://github.com/LLK/scratch-www/issues/678, there will be two search bars with the search term displayed on the new Search page. Do we like that design?

![out](https://cloud.githubusercontent.com/assets/1320456/17909935/abc6b636-6954-11e6-880b-5c0c6771a645.gif)

**Comment by thisandagain** [comment]
@carljbowman I'll leave this one up to you. Putting in backlog.

**Comment by rschamp** [comment]
@carljbowman said "no".

**Comment by TheGrits** [comment]
@rschamp Wait, so we want to remove the search bar on the search page itself or on the nav-bar?

**Comment by carljbowman** [comment]
@TheGrits - @rschamp took some liberty with the paraphrasing. 

Let's go ahead and remove the search bar lower on the page itself, but keep the search bar on the nav-bar. We are going to do some work next month to open the nav-bar up. 

Thanks for the help!

**Comment by TheGrits** [comment]
@carljbowman Sounds like a plan. Thanks!
