### ISSUE TITLE
Studio thumbnails not loading on new Search page in IE 11

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#878]
IE 11 on Win 7 VM, from https://github.com/LLK/scratch-www/pull/871#issuecomment-241848166

Studio thumbnails that are loading in other browsers are not loading (I searched for cats on the new Search page):
<img width="905" alt="screen shot 2016-08-23 at 5 25 34 pm" src="https://cloud.githubusercontent.com/assets/1320456/17910446/e7871150-6956-11e6-9d44-ce0055e79520.png">

Comment from @mewtaylor:

> as for the studio thumbnails – considering the code that touched that part of this system has not changed as a part of this PR [#871], I'm inclined to think it's a staging-only issue at the moment.

**Comment by mewtaylor** [comment]
@jwzimmer just looked on production, and it appears to be working correctly, so confirmed that this is a staging-only issue
