### ISSUE TITLE
New search page not showing up well in Safari

### ISSUE THREAD

**Issue by coke11** [LLK/scratch-www#886]
I am trying to search for "hi" on Safari. Much to my surprise each project has it's own row unlike in Firefox or Chrome

Safari screenshot:
![screen shot 2016-08-26 at 7 08 54 am](https://cloud.githubusercontent.com/assets/18141280/18004884/58f2f8a2-6b5c-11e6-9da4-f353c028687d.png)

Firefox Screenshot:
![screen shot 2016-08-26 at 7 09 31 am](https://cloud.githubusercontent.com/assets/18141280/18004890/649a11c2-6b5c-11e6-9d91-93676a12b840.png)

Chrome screenshot:
![screen shot 2016-08-26 at 7 09 35 am](https://cloud.githubusercontent.com/assets/18141280/18004897/740e21ca-6b5c-11e6-87c2-0cc2b8d9901e.png)

**Comment by coke11** [comment]
This is also happing with the new explore page. Screenshots on the way

**Comment by St19Galla** [comment]
@coke11 I am not able to repro this on MacOS Safari:
<img width="1280" alt="screen shot 2016-08-26 at 9 07 48 am" src="https://cloud.githubusercontent.com/assets/16446551/18006247/ac4c0416-6b6c-11e6-9337-5da4de04864d.png">
The Explore page also looks fine to me:
<img width="1280" alt="screen shot 2016-08-26 at 9 08 50 am" src="https://cloud.githubusercontent.com/assets/16446551/18006261/b98eeb0c-6b6c-11e6-80c2-7e58c043e410.png">

Have you tried clearing your cache and doing a hard refresh? That normally fixes problems after an update :)

**Comment by coke11** [comment]
@St19Galla OK. How do I do a hard refresh?

**Comment by jwzimmer** [comment]
@coke11 You can clear your cache in Safari with Develop > Empty Cache
<img width="331" alt="screen shot 2016-08-26 at 9 44 17 pm" src="https://cloud.githubusercontent.com/assets/1320456/18024389/d09f1578-6bd6-11e6-9d7f-29fd2fa04eff.png">

**Comment by coke11** [comment]
@St19Galla Didn't work

**Comment by TheGrits** [comment]
@coke11 It's probably your version of Safari.

**Comment by thisandagain** [comment]
@coke11 What version of Safari are you using? Please include Operating System and Browser version information when filing issues.

**Comment by coke11** [comment]
@thisandagain Staging: Safari Version 8.0.5, Mac 10.10.3
