### ISSUE TITLE
Scratch Conference Page is off in Safari

### ISSUE THREAD

**Issue by coke11** [LLK/scratch-www#887]
I am looking at the Conference page in Safari. It looks off, by a lot. Here is a gif of it

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/18141280/18005059/3ef7f55a-6b5d-11e6-9c07-a5a9e28f31c3.gif)
It seems fine in chrome and firefox. Here are screenshots:
 
![screen shot 2016-08-26 at 7 15 04 am](https://cloud.githubusercontent.com/assets/18141280/18005075/5a66ca96-6b5d-11e6-901d-48eca6ffb284.png)
![screen shot 2016-08-26 at 7 15 08 am](https://cloud.githubusercontent.com/assets/18141280/18005078/628a00a8-6b5d-11e6-9598-2694ff069ce7.png)

**Comment by thisandagain** [comment]
@coke11 What version of Safari are you using? Please include Operating System and Browser version information when filing issues. For example:

Operating System: Mac OS 10.11.5
Browser: Version 9.1.1 (11601.6.17)

**Comment by coke11** [comment]
@Staging: Safari Version 8.0.5, Mac 10.10.3
