### ISSUE TITLE
Educators Page in Safari

### ISSUE THREAD

**Issue by coke11** [LLK/scratch-www#888]
In Safari the educators page seems to be vertically aligning page elements
![screen shot 2016-08-26 at 7 21 54 am](https://cloud.githubusercontent.com/assets/18141280/18005168/da2fc0fc-6b5d-11e6-859f-4adf0687948f.png)
Compared to this in Chrome
![screen shot 2016-08-26 at 7 22 41 am](https://cloud.githubusercontent.com/assets/18141280/18005180/eea67634-6b5d-11e6-9b2f-f0b1b163cb9d.png)
(As you move down the page more, it gets even more off. Repro by going to the educator page in Safari)
Staging: Safari Version 8.0.5, Mac 10.10.3

**Comment by mewtaylor** [comment]
thanks @coke11 – do you mind including the version of Safari you're using in these issues? It will be super helpful as we try to repro :).

**Comment by coke11** [comment]
@mewtaylor Well do!

**Comment by jwzimmer** [comment]
I think this may be due to the issue in Safari 8.0. Will see if I can get an old version of Safari to test.
