### ISSUE TITLE
Menu icons in diffrent places on the old & new menu bars

### ISSUE THREAD

**Issue by coke11** [LLK/scratch-www#889]
The buttons are in different places depending on if the page has the new menu. 
On home page:
![screen shot 2016-08-26 at 7 26 19 am](https://cloud.githubusercontent.com/assets/18141280/18005411/72051b60-6b5f-11e6-961e-7f3509789bd2.png)
On my stuff page:
![screen shot 2016-08-26 at 7 26 36 am](https://cloud.githubusercontent.com/assets/18141280/18005417/7ab516ca-6b5f-11e6-84c3-7fb1a1141264.png)
On about page
![screen shot 2016-08-26 at 7 27 01 am](https://cloud.githubusercontent.com/assets/18141280/18005425/8424e82a-6b5f-11e6-9f1e-f58f21d0cea7.png)
It is annoying because you have memorized one location, so you click the wrong button on one page. If you can't tell the my stuff, and messages buttons switch around depending on if the page has the new menu

Edit: I just realized that the username does too!

Staging: Safari Version 8.0.5, Mac 10.10.3

**Comment by TheGrits** [comment]
@coke11 I don't seem to be able to reproduce this, what is your browser/OS?
![screenshot 2016-08-26 at 8 39 43 am](https://cloud.githubusercontent.com/assets/12952370/18005560/a75e764a-6b68-11e6-9cb4-4b4622e75ea5.png)
I'm using Chrome 52 on ChromeOS.

**Comment by coke11** [comment]
@TheGrits Staging: Safari Version 8.0.5, Mac 10.10.3

**Comment by St19Galla** [comment]
@coke11 Not able to reproduce on production MacOS Safari. 
<img width="251" alt="screen shot 2016-08-26 at 9 11 33 am" src="https://cloud.githubusercontent.com/assets/16446551/18006340/1e166910-6b6d-11e6-8f33-77f2e05deb10.png">

By "staging" do you mean the staging site, because I think only Scratch Team members have access to that. :)

**Comment by coke11** [comment]
@St19Galla No. I mean that is my browser

**Comment by thisandagain** [comment]
This bug is specific to Safari 8.X and is not present in Safari 9.

/cc @jwzimmer @mewtaylor

**Comment by coke11** [comment]
@thisandagain Ok - Should this be closed then? There might still be some people using 8 though...
