### ISSUE TITLE
FAQ on Developers page in Safari

### ISSUE THREAD

**Issue by coke11** [LLK/scratch-www#890]
The developers page looks good in Safari, except the FAQ. It has each question in it's own line:
![screen shot 2016-08-26 at 7 32 55 am](https://cloud.githubusercontent.com/assets/18141280/18005497/f134d6be-6b5f-11e6-8ffc-be36d44f3821.png)
However in chrome it has 3 questions in a line:
![screen shot 2016-08-26 at 7 32 49 am](https://cloud.githubusercontent.com/assets/18141280/18005508/fc74ab30-6b5f-11e6-964f-c2ddad8f1473.png)
Staging: Safari Version 8.0.5, Mac 10.10.3

**Comment by jwzimmer** [comment]
@coke11 Thanks for reporting this. In Safari Version 9.1.2 (11601.7.7), I'm seeing the correct formatting, so if you can upgrade Safari, might be worth trying?
<img width="990" alt="screen shot 2016-08-26 at 9 30 43 am" src="https://cloud.githubusercontent.com/assets/1320456/18006922/eb6345e4-6b6f-11e6-9e39-22bbcd1e430d.png">

**Comment by coke11** [comment]
@jwzimmer Hm. seems to be a problem with the older versions of safari. I will upgrade soon, but there still may be people with the oldest version, so they would get the same issue

**Comment by thisandagain** [comment]
@jwzimmer @mewtaylor Safari 8 has limited support for Flexbox which I think is what is causing all of these problems.

**Comment by coke11** [comment]
@thisandagain I see... So  - Should these be closed?

**Comment by TheGrits** [comment]
@thisandagain Perhaps a separate issue for making an alternative for Flexbox for Safari 8 users should be made?

**Comment by thisandagain** [comment]
Our support matrix is for the latest 2 releases of Safari, Chrome, and Firefox. This unfortunately means that we no longer support Safari 8.
