### ISSUE TITLE
Mobile About Page Video Bug

### ISSUE THREAD

**Issue by St19Galla** [LLK/scratch-www#891]
The video on the About page does not seem to be responsive on my iPhone 5s Safari creating a bad background issue:
<img src="https://cloud.githubusercontent.com/assets/16446551/17989366/c83e9732-6afa-11e6-8abd-bdc605741260.PNG" width=300px>

Something to consider is whether it would be better to have the video shrink size to fit or move to beneath/above the intro text when the screen size is small.

Also, ignore the white box as messages, that's a known bug on my phone :) Sorry!

**Comment by TheGrits** [comment]
Very similar to #469.

**Comment by St19Galla** [comment]
@TheGrits Indeed, I was just thinking about that. Thanks for linking to it!
