### ISSUE TITLE
Mobile Community Guidelines Image Error

### ISSUE THREAD

**Issue by St19Galla** [LLK/scratch-www#894]
On the Community Guidelines page, the bottom image is not responsive in changing size with the rest of the page, causing a background issue:
<img src="https://cloud.githubusercontent.com/assets/16446551/17989512/d79cce28-6afb-11e6-8895-1d8cf66af848.PNG" width=300px>

Also, ignore the white square over the messages icon - that's a known bug with my phone. Sorry!

**Comment by TheGrits** [comment]
I'm thinking that keeping the image on mobile doesn't make sense. It doesn't carry any important information, so I don't think it is absolutely needed.

**Comment by coke11** [comment]
Staging?

**Comment by coke11** [comment]
@St19Galla Staging?

**Comment by TheGrits** [comment]
@coke11 Nope: 
![screenshot 2016-08-29 at 7 47 20 am](https://cloud.githubusercontent.com/assets/12952370/18050496/ea758fbc-6dbc-11e6-85bb-8e112ae31151.png)

**Comment by coke11** [comment]
@TheGrits 

> Nope

?
