### ISSUE TITLE
Re-searching for same term or no term with Enter causes term to be replaced by "undefined"

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#899]
On the new Search page, Production, Chrome Version 52.0.2743.82 (64-bit) on Mac OS X El Capitan 10.11.6 

Steps to repro:
- Go to the search page by searching for "anything" in the nav bar
- Results returned will be relevant to "anything"
- Put your cursor in the search bar on the search page and hit the enter key
- Page will refresh with "undefined" as the search term in the query string (URL) and in the search bar on the search page
- Results returned will be relevant to "undefined"

![out](https://cloud.githubusercontent.com/assets/1320456/18100836/67f7902c-6eba-11e6-8ddc-76af0093cf9c.gif)

/cc @mewtaylor

**Comment by St19Galla** [comment]
Could this also fix the error that when you search something with no content (i.e. just hitting then search icon) it returns the same undefined? :)
