### ISSUE TITLE
Update Credits Page

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#900]
Edits for the Credits Page
[https://scratch.mit.edu/info/credits/](https://scratch.mit.edu/info/credits/)

**For the Scratch Team section:**
- Add Sarah Otts ([scmb1](https://scratch.mit.edu/users/scmb1/) on Scratch) 
- Add Connor Hudson ([technoboy10](https://scratch.mit.edu/users/technoboy10/) on Scratch) 
- Add Hanako Tjia ([hanakoala](https://scratch.mit.edu/users/hanakoala/) on Scratch) 
- Remove Ben Berg
- Remove Hannah Cole

**For the Moderator Section:**
- Add Tauntaun Kim ([thetaun](https://scratch.mit.edu/users/thetaun/) on Scratch)
- Remove Sarah Otts (she is being moved up to ST section)
- Remove Andrea Saxman

**For the "Previous MIT Scratch Team Members" section:**
- Add Ben Berg
- Add Hannah Cole
- Add Andrea Saxman

**Comment by St19Galla** [comment]
I can take this :)

**Comment by mewtaylor** [comment]
@St19Galla go for it :)
