### ISSUE TITLE
Update /hoc to include new tutorials

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#903]
In time for the EU and Africa Code Weeks (early Oct), we should update the current scratch.mit.edu/hoc to the three tutorials we will highlight this year. This page will then be redirected to the activities page in advance of the US Code Week. 

Hide-and-Seek Game --> Make it Fly
Dance, Dance, Dance --> Make Music
Animate Your Name --> [No Change] 

For the two tutorials being updated, the following information needs to be changed:
- Top Section: Thumbnail, Name of tutorial, Link to tutorial, *remove graphical backgrounds*
- 'Activity and Guides' section: new links to cards, facilitator guides, and updated name
- 'Studios' section: new links, update to text

Updated links:

*Make Music* 
- Name of Tutorial: Make Music 
- Link to Tutorial: https://scratch.mit.edu/projects/editor/?tip_bar=music
- Studio link: https://scratch.mit.edu/studios/1999784/
- Thumbnail: grab from studio, above 
- Cards: @ntlrsk please update
- Facilitator Guide: REMOVE THIS LINK AND TEXT

*Make it Fly* 
- Name of Tutorial: Make it Fly 
- Link to Tutorial: https://scratch.mit.edu/projects/editor/?tip_bar=fly
- Studio link: https://scratch.mit.edu/studios/2050750/
- Thumbnail: use thumbnail from above (not animated) 
- Cards: @ntlrsk please update
- Facilitator Guide: REMOVE THIS LINK AND TEXT

**Comment by thisandagain** [comment]
@ntlrsk When do you think we could expect the content (cards & facilitator guides) for this?

**Comment by kaschm** [comment]
updated to remove links to guides, as per @ntlrsk they won't be ready for this push. thanks.

**Comment by mewtaylor** [comment]
@kaschm @ntlrsk this is what it looks like with guides removed and such. The studio image for Make it Fly is a bit low res, so if we have another one available anywhere let me know!
![screencapture-localhost-8333-hoc-1473941482389](https://cloud.githubusercontent.com/assets/1815772/18549402/41191c32-7b1c-11e6-97f3-902d604bb6e8.png)

**Comment by ntlrsk** [comment]
Thanks for working on this! I would like to make the cards available for all three activities - and will give you the cards by early tomorrow morning.

**Comment by ntlrsk** [comment]
I see a couple more things that would be good to change if possible:
1) For "Want More Activities", can you replace the "Bearstack Story" and "B-Ball Hoops" with the two that you removed from the top: "Dance, Dance, Dance" and "Hide and Seek"
2) Replace "We Bear Bears Studio" link with "Make It Fly" studio link: https://scratch.mit.edu/studios/2050750/

**Comment by ntlrsk** [comment]
@mewtaylor Here are the links for the new cards - I pushed them to the dev server scratchr2/static/pdfs/help/FlyCards.pdf
scratchr2/static/pdfs/help/MusicCards.pdf

Also, the file I named "NameCards.pdf" should be renamed "AnimateYourNameCards.pdf" and should replace the older file with that name.
Thanks!

**Comment by mewtaylor** [comment]
Closed in https://github.com/LLK/scratch-www/issues/921
