### ISSUE TITLE
Create “Scratch Activities Page” to display ten new activities

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#904]
This new page will contain ten themed activity packs for Scratch. Each activity pack will include:
- Tutorial
- Cards
- Facilitator Guide

We will be pointing to this from the Educator Page and possibly from the homepage during CSEdWeek (tbd). 

This needs to render acceptably on mobile because we will be pointing here from the homepage (on mobile devices).

**Comment by ntlrsk** [comment]
@carljbowman Excited about your design for this page. About wording: after getting feedback from some others with kids, decided to go back to the phrase "Activity Cards" rather than "Tips Cards" (to be more appealing to kids and fit with the NoStarchPress release). Thanks!

**Comment by thisandagain** [comment]
Tracking in #979
