### ISSUE TITLE
Redirect /hoc to Activity Page

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#906]
Before CSEdWeek begins, we should redirect the /hoc page to the new Activities Page https://github.com/LLK/scratch-www/issues/904

**Comment by ntlrsk** [comment]
Will this HOC page still show up anywhere? If so, is it possible to add links to the two educator guides: **Make It Fly** https://scratch.mit.edu/fly/guide and **Make Music** https://scratch.mit.edu/music/guide ?

**Comment by kaschm** [comment]
@ntlrsk we had planned to redirect this page entirely; it won't be available after the redirect. Does this sound ok?

**Comment by ntlrsk** [comment]
@kaschm Yes that is OK with me. Hopefully translators will work on translation for the TTT page - thanks to @chrisgarrity for emailing them.

**Comment by mewtaylor** [comment]
@ntlrsk @kaschm can we get rid of the current hoc page? Or is the plan to try to archive it?

**Comment by kaschm** [comment]
@mewtaylor might be nice to have it in case we want to reuse it for something in the future (for example, Lemann uses a translated version on their site).

**Comment by mewtaylor** [comment]
@kaschm deleting it would mean we’d still have the code for it in github, so if the thought was to keep it to reuse it, we could still find it again even after removing it. Is that okay?

**Comment by kaschm** [comment]
yup, that's fine! thanks. @mewtaylor

**Comment by ntlrsk** [comment]
OK with me too. Thanks for checking.
