### ISSUE TITLE
How can we run scratch on localhost?

### ISSUE THREAD

**Issue by aytac** [LLK/scratch-www#914]
When I clone and run the GitHub repository, it works but I am not able to see the editor and the current projects. It gives me below error message.

How can I run on local and on my own server?

http://localhost:8333/projects/editor/?tip_bar=home
Cannot GET /projects/editor/?tip_bar=home

**Comment by rschamp** [comment]
Currently only some of the pages from Scratch are built using this repository, while most are still using our (closed source) legacy front-end.  Until we migrate the project page to this repository, you cannot run it locally.

**Comment by kuilab** [comment]
well, when would u do this ? 
and wich version ? 2.x or 3 ?

**Comment by rschamp** [comment]
If I had to guess, the project page will be migrated over as part of the roll-out of Scratch 3.0.
