### ISSUE TITLE
Outdated project thumbnails in Search & Explore

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#915]
Steps to repro:
- Go to project 114909489 and note the image displayed on the project page. This is also the image displayed in My Stuff as the project thumbnail.

<img width="316" alt="screen shot 2016-09-12 at 9 13 26 am" src="https://cloud.githubusercontent.com/assets/1320456/18437074/4588dc62-78c9-11e6-8456-04d271ae8e56.png">
- Search for the creator's name in the search bar.
- Note that the project thumbnail returned here is different, showing a typing kitten instead of pink text.

<img width="236" alt="screen shot 2016-09-12 at 9 13 42 am" src="https://cloud.githubusercontent.com/assets/1320456/18437108/69f2bd66-78c9-11e6-8d60-daba82bf4a21.png">

You can also do this with e.g. project 104066581.

Reported via freshdesk no. 56478:
> When I look myself up in the explorer tab, all the thumbnails my projects are outdated! But in every other part of scratch my thumbnails look like they're supposed to!

Recently we added purging studio thumbnails when they were changed (https://github.com/LLK/scratchr2/pull/3716), so maybe the same kind of treatment should happen here, if it isn't already?

**Comment by kaschm** [comment]
Moved to LLK/scratch-search#21
