### ISSUE TITLE
Idea for providing forum search until it is implemented

### ISSUE THREAD

**Issue by demesos** [LLK/scratch-www#917]
Currently, the "search" link at https://scratch.mit.edu/discuss/ points to a page https://scratch.mit.edu/discuss/search that has no search functionality. A temporary fix would be to point it to a google costum search box with site:scratch.mit.edu/discuss limit

**Comment by coke11** [comment]
When did this page go away?

**Comment by demesos** [comment]
I think that was when the new search was implemented. But the current search only supports searching for projects and studios atm.

**Comment by mewtaylor** [comment]
Thanks for the suggestion @demesos! I think this is an interesting interim idea – not sure we'll have the capacity to consider this right now, but when we revisit the idea, this will be a great suggestion to consider.

I'll make sure to drop another comment here with updates when we have them.
