### ISSUE TITLE
Update Scratch conference homepage video link

### ISSUE THREAD

**Issue by sleggss** [LLK/scratch-www#918]
Current homepage reads:
“Watch the keynote live”

[Which will change to:](https://github.com/LLK/scratch-www/issues/864)
“Watch videos of the keynote sessions”

Can we update the link to:
https://youtu.be/alsfSTVn2es?list=PLpfxVARjkP-8chnTrjtDeo88Pcz6-xf_B

/cc @kaschm

**Comment by coke11** [comment]
@TheGrits Ninja! I was going to take this one ;)
