### ISSUE TITLE
[android] can't login from homepage

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-www#92]
os android 5.1.1 Nexus 4
Browser: chrome
Server 2.2.2 staging

When I try to login using nexus phone android from home page,  the sign in  dialog seems to lose focus and not appear on the screen when I type. 

Expected: sign in should appear on screen when you type credentials

If u can't repro please close. It may be my phone.

**Comment by TheGrits** [comment]
@thisandagain I have signed into the homepage without any issues recently, I'm not sure that this bug still exists.
I'm on a Galaxy Note 3 running Android 5.0.

**Comment by thisandagain** [comment]
Thanks for the heads-up @TheGrits . We'll attempt to repro.

**Comment by jwzimmer** [comment]
I can sign in on production on an Android (Samsung Galaxy S5) phone. 
It looks like the bug was reported on staging, but I am having trouble connecting via VPN on the phone (I followed a modified version of the [steps from necsys](http://www.media.mit.edu/insider/NeCSys)... they're out of date so the process was a bit different but still pretty straight forward... but for some reason the connection still failed... so for now I can't check if this works on staging).

**Comment by jwzimmer** [comment]
Note from bug triage: don't spend too much time on this, try with a couple versions of android.

**Comment by jwzimmer** [comment]
**No repro on Production**
- I can sign in (to a teacher account) on a Samsung Android tablet using Google Chrome 52.0.2743.98. The tablet has no name on the back but it's a white Samsung with a pleather back & a barcode tag saying MFD2392 (Refurb). Model SM-T520; Android version 4.4.2.
- I can sign in (to jwzimmer1990) on a Nexus Android tablet using Google Chrome. Model Number Nexus 9; Android Version 6.0.1. The tablet has no name on the back but it is a black Nexus with a barcode tag on the back that says S/ N: HT4AKJT01664 and P/ N: 99HZF003-00.
- @chrisgarrity logged in from the homepage on her Android phone, which has version 6.0.1. She was able to log in, the only issue she encountered was room on the screen for getting to the password field when the keyboard is active and the orientation is landscape (you have to turn the phone to portrait mode to expose the password field).
- I can sign in (to jwzimmer1990) on Samsung tablet "Oats". Android Version 5.0.2; Model Number SM-T530NU.

**Comment by jwzimmer** [comment]
Closing for lack of repro.
