### ISSUE TITLE
add shortcuts to new cards and guides PDFs

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#922]
scratch.mit.edu/fly/cards -> /pdfs/help/FlyCards.pdf
scratch.mit.edu/dressup/cards  -> /pdfs/help/DressupCards.pdf
scratch.mit.edu/racegame/cards -> /pdfs/help/RaceGameCards.pdf
scratch.mit.edu/music/cards -> /pdfs/help/MusicCards.pdf
scratch.mit.edu/catch/cards  -> /pdfs/help/CatchCards.pdf
scratch.mit.edu/pong/cards  -> /pdfs/help/PongCards.pdf
scratch.mit.edu/pet/cards  -> /pdfs/help/PetCards.pdf

scratch.mit.edu/name/guide ->  scratch.mit.edu/scratchr2/static/pdfs/help/AnimateYourNameGuide.pdf

scratch.mit.edu/fly/guide ->  scratch.mit.edu/scratchr2/static/pdfs/help/FlyGuide.pdf
scratch.mit.edu/music/guide ->  scratch.mit.edu/scratchr2/static/pdfs/help/MusicGuide.pdf
scratch.mit.edu/pong/guide ->  scratch.mit.edu/scratchr2/static/pdfs/help/PongGuide.pdf
scratch.mit.edu/racegame/guide ->  scratch.mit.edu/scratchr2/static/pdfs/help/RaceGameGuide.pdf
scratch.mit.edu/dressup/guide ->  scratch.mit.edu/scratchr2/static/pdfs/help/DressupGuide.pdf
scratch.mit.edu/catch/cards  -> scratch.mit.edu/scratchr2/static/pdfs/help/CatchGuide.pdf
scratch.mit.edu/pet/cards  ->  scratch.mit.edu/scratchr2/static/pdfs/help/PetGuide.pdf

**Comment by St19Galla** [comment]
I can take this if that's okay :)

**Comment by ntlrsk** [comment]
Most of these cards aren't up yet, but will be.

**Comment by kaschm** [comment]
@ntlrsk thanks for making the issue! I've blocked it and thrown it into the Oct milestone; feel free to edit if and when this information changes.

**Comment by ntlrsk** [comment]
I think it can be unblocked now (even though not all the cards are there, they will be soon and it will be good to have the URLs ready).  thanks!

**Comment by mewtaylor** [comment]
@ntlrsk while we're here, do we want to keep last year's tutorial shortcuts? i.e. we still have shortcuts for:
* `/odetocode/`
* `/codeweekeu/`
* `/valentines/`
* `/hoops/`
* `/soccer/`
* `/bearstack/`

**Comment by ntlrsk** [comment]
Hi @mewtaylor Keeping all of them would be good since they exist on various studios and projects, as well as some outside past promotion. /odetocode and /codeweekeu are going to be promoted again for the upcoming EU code week. Thanks for checking!

**Comment by mewtaylor** [comment]
Done in https://github.com/LLK/scratchr2/pull/4130
