### ISSUE TITLE
Should the Developers page be translated?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#924]
Chrome Version 53.0.2785.116 (64-bit), Mac OS X El Capitan 10.11.6 (15G1004)

https://scratch.mit.edu/developers

@chrisgarrity and I were wondering about this when we were looking at https://github.com/LLK/scratchr2/issues/4066. Currently, the Developers page remains in English when you choose a 100% translated language like Italian. We weren't sure if perhaps it remained untranslated intentionally since we may only really be able to work with Developers comfortable communicating in English?

**Comment by liam4** [comment]
> we may only really be able to work with Developers comfortable communicating in English

Perhaps a (translated) alert on the page mentioning this?

**Comment by kaschm** [comment]
Yes we should translate this page!
