### ISSUE TITLE
Set up how to run automated integration tests

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#925]
Continuing initial set-up started in https://github.com/LLK/scratch-www/issues/590. The first test is checked in, but we need to figure out how we'll be running it as part of the development process.
- [ ] Change driver URL to a variable so it isn't hardcoded.
  Re [this line](https://github.com/LLK/scratch-www/blob/develop/test/integration/check_navbar_links.js#L13)
  @rschamp said:
  
  > Maybe it should come from an environment var || "scratch.mit.edu"?
  > and then when we run the tests we'll run it with that var = scratch.ly
- [ ] Set up running with travis/ sauce: https://github.com/LLK/scratch-www/pull/920#discussion_r78991538
- [ ] Maybe set up running with multiple browser drivers: https://github.com/LLK/scratch-www/pull/920#discussion_r78994506

**Comment by jwzimmer** [comment]
**Questions/ to do**

- Running on multiple browsers
- What about varying the size of the browser window? e.g. `browser.manage().window().setSize(1280, 720)`
- Benefit to running on proxy?

**Comment by jwzimmer** [comment]
Decide on dependency arrangement (re https://github.com/LLK/scratch-www/pull/1185#issuecomment-294882644):
@rschamp said: > I think we might want to do something so that there's a separate package.json for the smoke tests, and then it can be installed from there

**Comment by jwzimmer** [comment]
Next steps:
- Work with @colbygk to set up post, so that saucelabs/ browserstack can use a tunnel so it can hit Staging from the media lab
- Env variable (for Travis) for running smoketests or not on Staging and figure out how often we want to run them (at night, at end / beginning of a freeze?)
- Document process for running tests

**Comment by jwzimmer** [comment]
* Generated ssh keys and put them in password manager (shared folder)

**Comment by jwzimmer** [comment]
I removed the private key env variable I had added to travis b/c I think it broke travis' ability to build. I'll figure out which characters I should have escaped or whatever and re-instate it later. Sorry. : (

**Comment by rschamp** [comment]
We did it!
