### ISSUE TITLE
Update wedo page to include Windows 10 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#930]
scratch.mit.edu/wedo should now include language around compatibility with Win 10: 

The LEGO WeDo 2.0 extension is currently only available for Mac OSX. We plan to release a Windows version later in 2016.

update to:

The LEGO WeDo 2.0 extension is available for Mac OSX and Windows 10+

also update the download text and link:

1. Install Device Manager

The Device Manager lets you connect WeDo 2.0 to Scratch using Bluetooth 

**Download for Mac OSX** [existing link]
**Download for Win 10+** [needs link @cwillisf ]

**Comment by mewtaylor** [comment]
@cwillisf and @kaschm moving this back too, fyi.

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/issues/1080
