### ISSUE TITLE
Match text format/ location for "Not Required" on different steps of Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#933]
Staging, Safari Version 9.1.3 (11601.7.8), Mac OS X El Capitan

From https://github.com/LLK/scratch-www/pull/896:

We added "Not Required" by the Zip Code field since we stopped requiring Zip Codes for non-USA countries. We added it in a different location/ format than we did on other steps (e.g. Website field). We should be consistent.

<img width="303" alt="screen shot 2016-09-30 at 2 05 54 pm" src="https://cloud.githubusercontent.com/assets/1320456/19001971/d98c469a-8717-11e6-8c2f-3053ef075637.png">
<img width="303" alt="screen shot 2016-09-30 at 2 04 54 pm" src="https://cloud.githubusercontent.com/assets/1320456/19001972/d98ed19e-8717-11e6-96f2-cb20c751cd12.png">

/cc @carljbowman

**Comment by mewtaylor** [comment]
Fixed in https://github.com/LLK/scratch-www/issues/935
