### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#940]
Several languages are 100% translated on pootle (e.g. Catalan and Italian), but there are still strings in English on the site, so they are missing from the po files.

- [ ] **About page**

'Who uses Scratch' and 'Scratch in Schools' from the italian translation:

<img width="444" alt="screen shot 2016-09-20 at 11 01 52 am" src="https://cloud.githubusercontent.com/assets/1320456/18675882/cab23d08-7f21-11e6-8dfd-d04415cf4674.png">
<img width="438" alt="screen shot 2016-09-20 at 11 01 22 am" src="https://cloud.githubusercontent.com/assets/1320456/18675883/cab2e5fa-7f21-11e6-9ab4-87f1b15eae4a.png">

- [ ] **"Projects curated by" on the splash page**

<img width="978" alt="screen shot 2016-09-20 at 11 28 35 am" src="https://cloud.githubusercontent.com/assets/1320456/18676973/74475382-7f25-11e6-9e52-a24eed48c555.png">

- [ ] **The words in the graphics on the statistics page?**

<img width="958" alt="screen shot 2016-09-20 at 11 30 07 am" src="https://cloud.githubusercontent.com/assets/1320456/18677083/b0c98910-7f25-11e6-91c7-954b01d6cc4d.png">
<img width="1009" alt="screen shot 2016-09-20 at 11 29 45 am" src="https://cloud.githubusercontent.com/assets/1320456/18677084/b0ccfe38-7f25-11e6-9355-3fc327d1b703.png">

- [ ] **The Credits page?**
https://scratch.mit.edu/info/credits/

<img width="780" alt="screen shot 2016-09-20 at 11 38 52 am" src="https://cloud.githubusercontent.com/assets/1320456/18677469/e67c5528-7f26-11e6-8fce-e3ef28dc6c4f.png">

/ cc @kaschm

**Comment by jwzimmer** [comment]
From @ntlrsk:
> In preparation for EU Code Week (Oct. 15), noting that a couple of the strings are not included in the translation on the HOC page in Italian, even though Italian showing as 100% translated in all projects. 
> Animate Your Name, ANIMATE YOUR NAME (in two places), and Dance, Dance, Dance are showing up in English on the HOC page. 
> (Those phrases are already available in Pootle for Scratch Website for the cards page.)
> Thanks for investigating.

![image](https://cloud.githubusercontent.com/assets/4721032/19213194/97385966-8d19-11e6-923e-7118f76158c0.png)

![image](https://cloud.githubusercontent.com/assets/4721032/19213165/97a8816a-8d18-11e6-9eff-cd0f0a47d610.png)

> Just noting same in Norwegian...

> @jwzimmer @mewtaylor It would be good to fix this by this Friday if possible because it's for EU Code Week. Thanks!

**Comment by chrisgarrity** [comment]
On closer inspection the statistics page has not yet moved to www, so can't fix missing translations for that here. I'm going to move the credits page to it's own issue because none of it is translated so we should confirm that we do want to translate it.

**Comment by jwzimmer** [comment]
@chrisgarrity Noticed this with Portuguese + Teacher Registration. The validation string seems to be translated sometimes but not always:
<img width="603" alt="screen shot 2016-10-12 at 11 55 30 am" src="https://cloud.githubusercontent.com/assets/1320456/19317436/01b85faa-9073-11e6-9925-814d7d17028d.png">
