### ISSUE TITLE
Should we translate privacy policy

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#941]
Originally reported in llk/scratchr2#4066

We don't translate the pages that are legal policies. However, the Terms do say that we may provide translations for informational purposes, and the English terms/policies are the legal ones. Should we provide translations, and if so which pages?

**The terms of use page is not translated**
https://scratch.mit.edu/terms_of_use/

<img width="638" alt="screen shot 2016-09-20 at 11 42 54 am" src="https://cloud.githubusercontent.com/assets/1320456/18677637/6862b67c-7f27-11e6-82c4-35d2abb164fd.png">

**The privacy policy is not translated**
https://scratch.mit.edu/privacy_policy/

<img width="720" alt="screen shot 2016-09-20 at 11 43 27 am" src="https://cloud.githubusercontent.com/assets/1320456/18677653/7fd5cb0a-7f27-11e6-8ede-621b7319aed0.png">

**Comment by TheGrits** [comment]
@chrisgarrity I'm willing to localize the page(s) once it's confirmed that it(they) should be.

**Comment by chrisgarrity** [comment]
@TheGrits Thanks, I'll make sure it gets a prio and remove the needs-discussion if we do decide to translate it.

**Comment by TheGrits** [comment]
@chrisgarrity Any updates?

**Comment by chrisgarrity** [comment]
@TheGrits Things kind of got put on hold over the holidays - I've added it to the list of topics to get discussed in the next couple of weeks.

**Comment by TheGrits** [comment]
@chrisgarrity Don't worry about it. :) Thanks

**Comment by rschamp** [comment]
We've decided not to translate the privacy policy.
