### ISSUE TITLE
Clarify Compatibility & Support Info in FAQ

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#942]
Currently we don't make it clear whether we're discussing requirements for the website or the editor (including online editor), so we should clarify that. We don't support the online editor with Linux with any browser except Chrome (latest two versions **for linux** which are generally a bit behind latest two versions for mac).

https://scratch.mit.edu/info/faq/

https://scratch.mit.edu/scratch2download/ (mentions Linux)

(Also, internally, we should clarify the wiki: https://github.com/LLK/scratch-ops/wiki/Compatibility-&-Support)

/cc @thisandagain

**Comment by jwzimmer** [comment]
I updated the wiki to include a note about Scratch website vs. online editor.

My understanding is we support the same things for Scratch website & online editor, except we don't support online editor with Linux.

Current information on website:
> **What are the system requirements for Scratch?**
> To run Scratch 2, you need to be using (1) a Mac, Linux, or Windows computer; (2) a version of Adobe Flash Player released on or after June 15, 2016; (3) a relatively recent web browser: one of the latest two versions of Chrome, Firefox, Safari (Mac or Windows only), Edge (Windows only), or Internet Explorer 10+ (Windows only). If your computer doesn’t meet these requirements, you can try downloading and installing Scratch 1.4, which you can still use to share projects to the Scratch 2 website.

Proposed change:
> > **What are the system requirements for Scratch?**
> To run Scratch 2, you need to be using (1) a Mac or Windows computer; (2) a version of Adobe Flash Player released on or after June 15, 2016; (3) a relatively recent web browser: one of the latest two versions of Chrome, Firefox, Safari (Mac or Windows only), Edge (Windows only), or Internet Explorer 10+ (Windows only). If your computer doesn’t meet these requirements, you can try downloading and installing Scratch 1.4, which you can still use to share projects to the Scratch 2 website. The Scratch website, other than the online editor, can be used on a Linux computer.

Alternately, we could probably just leave out the last sentence to make it less confusing, and just not mention Linux at all. People browsing the website are probably not usually thinking about compatibility like they would w.r.t. a piece of software like the editor, so I'm not sure how relevant or useful that info would be to users.

@kaschm - thoughts on this copy?

**Comment by TheGrits** [comment]
@jwzimmer If I may put my two cents in, I don't think the edit is completely accurate. My computer is a Linux machine, and yet the online editor does work. (It's just the offline editor that doesn't work) Mind you, I am using ChromeOS, so perhaps ChromeOS should be mentioned?

**Comment by jwzimmer** [comment]
@TheGrits You're definitely welcome to put your two cents in! : ) I could be wrong about what we support (it's confusing, which is why we're clarifying it!), but I think the confusion here is around what we mean by "support"/ "system requirements", etc. Just because the online editor currently works on X, that doesn't mean we actively support X, since that means we would put resources into fixing bugs & developing new features to work on X - that's what we mean by "what we support". E.g. if you wrote in with a bug that was specific to Scratch on your ChromeOS, we might not fix it, since we don't support ChromeOS.

**Comment by kaschm** [comment]
Ahh. tricky. @jwzimmer thanks for thinking more about this. The first point "1) a Mac or Windows computer" clarifies that we do not support Linux. I think that the last line ("The Scratch website, other than the online editor, can be used on a Linux computer.") is pretty confusing, and I'm not sure it's worth saying that everything *except* the editor works on Linux ... most people think of the editor when they think of Scratch. So I'm inclined to remove that last line and go with what we currently have. 

Happy to hear others' thoughts too, @thisandagain @ntlrsk

**Comment by jwzimmer** [comment]
New proposed changes:
> **What are the system requirements for Scratch?**
> To run Scratch 2, you need to be using (1) a Mac, Linux, or Windows computer; (2) a version of Adobe Flash Player released on or after June 15, 2016; (3) a relatively recent web browser: one of the latest two versions of Chrome (Mac, Windows, or Linux), Firefox (Mac or Windows only), Safari (Mac or Windows only), Edge (Windows only), or Internet Explorer 10+ (Windows only). If your computer doesn’t meet these requirements, you can try downloading and installing Scratch 1.4, which you can still use to share projects to the Scratch 2 website. We do not support Chromium.

**Comment by mewtaylor** [comment]
We should also update our [`bowser`](https://github.com/LLK/scratchr2/blob/develop/scratchr2/settings/base.py#L874-L881) settings when we do that change

**Comment by jwzimmer** [comment]
Fixed in https://github.com/LLK/scratch-www/pull/1012.
