### ISSUE TITLE
Can't sign up from homepage on mobile (iOS) - can't zoom out to click Next button

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#945]
Using Chrome 53.0.2785.109 on my iPhone 6, Production

I could not create a new account / join Scratch from the www pages (About, homepage) linked to on the mobile homepage. I didn't try all the pages linked to, but I would guess the www pages all have the same issue. I could not zoom out to see the Next button to proceed past the username/ password step in the Join Flow.

I manually went to the URL ending in `/discuss` to get a scratchr2 page and the old navbar in order to create an account. From there, I was able to zoom out enough to get to the Next button and complete the Join Flow.

I would like to see if this happens on other devices/ to other people, just in case it's something unique to my phone. (I wouldn't expect it to be, though.)

To repro:
- On an iPhone, open Chrome
- Go to Scratch homepage
- Click Join Scratch
- In pop-up window (Join Flow), fill out username/ password fields
- Try to click Next button (lower right corner of pop-up)
- Scroll out/ zoom out to try to make Next button visible

![img_1250](https://cloud.githubusercontent.com/assets/1320456/19118056/271822a6-8ae9-11e6-861d-bf262873b050.PNG)

**Comment by St19Galla** [comment]
Can confirm on Safari iPhone 5s. In addition, the navbar/sign-in bar is squished:
![img_9726](https://cloud.githubusercontent.com/assets/16446551/19127973/46c7376a-8b0f-11e6-9b76-701876d1c665.PNG)
![img_9725](https://cloud.githubusercontent.com/assets/16446551/19127970/46b136d6-8b0f-11e6-8bee-ee2305537470.PNG)
![img_9727](https://cloud.githubusercontent.com/assets/16446551/19127972/46c67c58-8b0f-11e6-9d30-c05ecadd8bd9.PNG)

**Comment by coke11** [comment]
I noticed that the entire menu bar does not show either...

**Comment by jwzimmer** [comment]
@mewtaylor I can click on the "Sign in" link on the homepage now, but I still can't get to the Next button for the "Join" flow. (Staging, Mobile iPhone 6s, Chrome 54)

![img_2246](https://cloud.githubusercontent.com/assets/1320456/20439836/7c6c7a1c-ad8b-11e6-9072-eea6f1592e72.PNG)
