### ISSUE TITLE
Add coverage display to ReadMe like scratch-vm has

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#947]
The scratch-vm repo added a display for unit test coverage in their ReadMe in https://github.com/LLK/scratch-vm/pull/233.

<img width="989" alt="screen shot 2016-10-05 at 11 39 19 am" src="https://cloud.githubusercontent.com/assets/1320456/19120354/8218679a-8af0-11e6-9804-545c4c62b4b0.png">
<img width="960" alt="screen shot 2016-10-05 at 11 43 10 am" src="https://cloud.githubusercontent.com/assets/1320456/19120507/f6a00550-8af0-11e6-969b-de039cfd7430.png">

Since scratch-www is open source as well, I think we could do the same [for free](https://coveralls.io/pricing) if we wanted to.

<img width="173" alt="screen shot 2016-10-05 at 11 41 07 am" src="https://cloud.githubusercontent.com/assets/1320456/19120465/ce725b0a-8af0-11e6-99fb-63c4c69a47b2.png">

**Comment by thisandagain** [comment]
Resolved in #991 and #986 
Thanks to @jzoldak
