### ISSUE TITLE
Missing strings from translation on HOC page

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#956]
In preparation for EU Code Week (Oct. 15), noting that a couple of the strings are not included in the translation on the HOC page in Italian, even though Italian showing as 100% translated in all projects. 

Animate Your Name, ANIMATE YOUR NAME (in two places), and Dance, Dance, Dance are showing up in English on the HOC page. 

(Those phrases are already available in Pootle for Scratch Website for the cards page.)

Thanks for investigating.

![image](https://cloud.githubusercontent.com/assets/4721032/19213194/97385966-8d19-11e6-923e-7118f76158c0.png)

![image](https://cloud.githubusercontent.com/assets/4721032/19213165/97a8816a-8d18-11e6-9eff-cd0f0a47d610.png)

**Comment by ntlrsk** [comment]
Just noting same in Norwegian...

**Comment by jwzimmer** [comment]
@chrisgarrity Seems similar to https://github.com/LLK/scratch-www/issues/940 - maybe they could be fixed at the same time/ consolidated?

**Comment by ntlrsk** [comment]
@jwzimmer @mewtaylor  It would be good to fix this by this Friday if possible because it's for EU Code Week. Thanks!

**Comment by chrisgarrity** [comment]
@ntlrsk @jwzimmer @mewtaylor This is definitely the same bug as #940.  It happens when the same string (e.g., Animate Your Name) shows up in multiple places.

**Comment by jwzimmer** [comment]
@chrisgarrity @ntlrsk @mewtaylor since it's the same issue as #940, I'm going to close this case and move the info to the other case.

**Comment by mewtaylor** [comment]
@jwzimmer @chrisgarrity I think we might want to keep this one open just because it looks like we need to hotfix these, but the other ones are not pressing. @chrisgarrity I would propose that we keep this one open, and do a quick fix of moving the strings into the `general` l10n file for a hotfix, but then also keep #940 open so we can work on the more long term fix for this. Thoughts?

**Comment by chrisgarrity** [comment]
@mewtaylor @jwzimmer I may be close with a fix for #940 but would you have time to review? Let's hot fix this change if getting it reviewed in time would be a problem for Friday.

**Comment by mewtaylor** [comment]
@chrisgarrity I'd definitely have time to review, that's awesome! Thanks!

**Comment by jwzimmer** [comment]
@mewtaylor & @chrisgarrity however you want to handle this is fine with me : )
