### ISSUE TITLE
Student account - issue logging in and finishing account creation

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#958]
Reported via freshdesk no. 58802:

> I have set up a teacher account and added some students.
>  When some of the students tried to login to their accounts, they were able to login but then it wouldn’t take them to the page to enter their personal details, birth month etc.
>  The cookies had then remembered their login details and so wouldn’t let them get to the homepage to sign in with a different account or navigate away from the error page.
> I can’t remember what the page said but it was a purple page and something along the lines of
> Sorry, something has gone wrong.
>  It seems to be a sort of interim page between logging in and accessing the personal details page of their student account.
>  Do you know of any reason why this might be happening? Is something being blocked that we need to get unblocked?
> 
> When I set up all the accounts I did it via CSV. The problem isn’t in creating the accounts, it is when they have to login for the first time and input their personal details. 

I logged in as two of the students that I guessed were created by CSV by looking at the usernames of the students associated with this teacher account, and it looks like they were blocked. The usernames I logged in as were SFAPHPS and LMAPHPS. @christanbalch do you have any theories on why they got blocked?

<img width="617" alt="screen shot 2016-10-11 at 11 49 12 am" src="https://cloud.githubusercontent.com/assets/1320456/19277745/d442323c-8fa8-11e6-986f-b17853e8d887.png">

I asked the user for more information about 6 days ago (have not yet heard back).

**Comment by christanbalch** [comment]
It looks like both accounts were deleted by themselves. Not sure why it is showing they are banned. 
![image](https://cloud.githubusercontent.com/assets/11506947/19278073/fd8c9b36-8fa9-11e6-85c7-12d6d0b35b92.png)

![image](https://cloud.githubusercontent.com/assets/11506947/19278104/20d33c4e-8faa-11e6-913a-90681ade231e.png)

**Comment by thisandagain** [comment]
@jwzimmer and @rschamp do you two mind looking into this together?
