### ISSUE TITLE
Should credits page be translated?

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#959]
**The Credits page**
https://scratch.mit.edu/info/credits/

<img width="780" alt="screen shot 2016-09-20 at 11 38 52 am" src="https://cloud.githubusercontent.com/assets/1320456/18677469/e67c5528-7f26-11e6-8fce-e3ef28dc6c4f.png">

Currently it is untranslated, and the strings are not part of the pootle database. Should it be translated?

**Comment by liam4** [comment]
Yes.

**Comment by TheGrits** [comment]
@chrisgarrity This will actually be really tricky to localize. Here's an example:

> The following people have also contributed to the development and support of Scratch over the years: Susan Abend, [a bucket load of names], Vladimir Vuksan, Han Xu, and the many volunteer [Scratch Translators](http://wiki.scratch.mit.edu/wiki/Translators) from around the world.

It doesn't help that the link is in the body of the paragraph, and not at the start or end. What would the preferred way of formatting the localization be? (The whole paragraph, or separate the link from the rest of the paragraph?

**Comment by chrisgarrity** [comment]
@TheGrits It is possible technically to localize text with the link in it, so we could just do the whole paragraph. However, actually coming up with something reasonable in other languages may be a challenge. @thisandagain Would it be ok to split this paragraph into two sentences. The original ending with 'and Han Xu.' Followed by something like:

> Scratch is available in many different languages thanks to the many volunteer [Scratch Translators](http://wiki.scratch.mit.edu/wiki/Translators) from around the world.

**Comment by thisandagain** [comment]
@chrisgarrity That sounds good. Thanks!
