### ISSUE TITLE
Student Registration - No "Male" option, cannot type in "Other" field, can proceed with blank "Other" field in several languages

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#962]
I noticed this while trying to repro freshdesk no. 58511. If you set the language to Portuguese or Brazilian Portuguese, and follow a student sign-up link, on the demographics step, there is no "male" gender option, and if you choose "other", you cannot type in it, and you can proceed to the next step while it is blank.

I used the link http://scratch.mit.edu/classes/295/register/9490a7eb39b24c99ba6a27d60d5e6e6c.

I registered portu_test_2 (Production, Chrome 53, Mac OS X El Capitan) with no gender (blank "other" option). I wonder if this shows up as 0 in the database @rschamp (like the countries)?

<img width="337" alt="screen shot 2016-10-11 at 3 31 53 pm" src="https://cloud.githubusercontent.com/assets/1320456/19285490/16001b70-8fc8-11e6-897d-934c1556187a.png">
<img width="338" alt="screen shot 2016-10-11 at 3 31 17 pm" src="https://cloud.githubusercontent.com/assets/1320456/19285491/16054294-8fc8-11e6-9459-4df326bb0174.png">

**Comment by liam4** [comment]
That link's there for anyone to mess with..

**Comment by mewtaylor** [comment]
@liam4 it's a link to register as a student in a teacher account – given that it's a test teacher account that a teacher can close, and given that it's still subject to all of the other registration checks we have in place, it shouldn't be too much of a concern :).

**Comment by carljbowman** [comment]
This issues is appearing in while in French as well. While QAing for https://github.com/LLK/scratchr2/pull/4244 this issue appeared.

<img width="1022" alt="screen shot 2016-11-15 at 5 13 51 pm" src="https://cloud.githubusercontent.com/assets/3409578/20326551/4a482134-ab57-11e6-97fc-2645fe17dbf2.png">

As documented, there is no 'male' option or ability to type in the addtional field.

**Comment by jwzimmer** [comment]
This occurs in Spanish as well:
<img width="299" alt="captura de pantalla 2016-11-17 a las 10 27 24 am" src="https://cloud.githubusercontent.com/assets/1320456/20395313/740081f6-acb0-11e6-991e-ee26725ef84f.png">
