### ISSUE TITLE
add more shortcuts for cards and guides PDFs

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#972]
Additional shortcuts to PDFs add:

scratch.mit.edu/story/cards -> /pdfs/help/StoryCards.pdf
scratch.mit.edu/fashion/cards ->  /pdfs/help/FashionCards.pdf
scratch.mit.edu/story/guide -> /pdfs/help/StoryGuide.pdf
scratch.mit.edu/hide/guide -> /pdfs/help/Hide-and-Seek-Guide.pdf
scratch.mit.edu/fashion/guide ->  /pdfs/help/FashionGuide.pdf
scratch/dance/guide -> /pdfs/help/DanceGuide.pdf

**Comment by kaschm** [comment]
These are just the short links, not the actual PDFs. @ntlrsk will upload the PDFs on her own.

**Comment by ntlrsk** [comment]
@mewtaylor Just noting that I've been updating that list of URLs above. Thanks.

**Comment by mewtaylor** [comment]
Done in https://github.com/LLK/scratchr2/pull/4283. Assigning to @ntlrsk for confirmation that the links are correct!

**Comment by jwzimmer** [comment]
Story & Fashion guide shortcuts 403. These tutorials are excluded for now from the TTT page, but we should still look into why it's 403'ing, as discussed with @mewtaylor. See https://github.com/LLK/scratch-www/pull/1006#issuecomment-261662764.

**Comment by jwzimmer** [comment]
Removed blocked label and added QA-OK.
