### ISSUE TITLE
User reported students unable to join class, stuck on intermediate registration step after using link - Student Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#974]
@kaschm received this via helpdesk a few days ago from user [see original case]: 

> Are teachers limited to a number of classrooms/students? I was doing fine today until my last 2 classes and now the computers won't let at least 4 students to join my class. The site just quits and won't move past the age and sex step. We tried restarting and moving computers but the same happens. 

---

Moved from LLK/scratchr2#4019
/cc @jwzimmer @kaschm

**Comment by jwzimmer** [comment]
Initially this was in scratchr2 since we did not know if the user was using the student account join flow (www) or the regular join flow (scratchr2).

However, we now know the user was using a shareable link (Freshdesk no. 56288):
> The issue seems to have passed. It was a sharable link that I used in my google classroom. I did have all of my students try and sign up early in my class. The first 4 classes went well on that day. After that though only a hand full of students could sign in and no one by my 6th class could sign in. Since then I have been teaching other content and sporadically trying to get the others to sign in and it seems to work. I won't have another time until the semester change to see if it happens again when I have all of my new students sign up. 

Another user reported students getting stuck on a step with the sign-up link (57529):
> However my students were using the link to add them to my class.  When they got to the screen where they entered their birth month and year and country.  They were not able to go any further.  It was like the website wasn’t working.  I even had them try to create accounts on their own and they were able to.  I also tried adding them and still didn’t have any success.

- Operating System: Windows 7 
- Browser: Firefox 48.0 
- Flash Version: Flash 23.0 (release 0)

Re the difference between these reports and those in issue #3961: https://github.com/LLK/scratchr2/issues/3961#issuecomment-249209059

**Comment by rschamp** [comment]
Will look at the stuck step to see how one can be stuck on said step

**Comment by rschamp** [comment]
The step they were stuck at is the one that actually does the registration.  We have logging set up already that should log to Sentry if there is an issue with the registration data, however we have never received any logs for this, possibly due to a low rate of occurrence combined with us being extremely rate limited by Sentry.  I verified that they should see an error message if the issue was something to do with their registration data.

I could not find any other way for someone to get stuck on this step. The required field validation seems to be working fine in Firefox 48 on Windows 7.  If we can avoid the rate limit for Sentry, a good way to catch what's going on here would be Javascript error reporting on this page.

**Comment by rschamp** [comment]
Assigning to @jwzimmer for repro or to close until we have better logging.

**Comment by jwzimmer** [comment]
**Attempting to repro**
Firefox 48 + Win 7 VM

- Using teacher3831
- (Made new account teacher3832; waiting for approval)
- Created new class 174 (as teacher3831)
- Got student sign-up link
- In same window+tab as teacher is signed in to, used sign-up link (tab A)
- Noticed https://github.com/LLK/scratch-www/issues/1103
- Registered a new account for student k-skdahuer_
- Tried to sign in as student k-skdahuer_
- Noticed https://github.com/LLK/scratch-www/issues/1104
- In same tab (tab B) as I was able to log in as teacher3831
- Created new student j-skhdar_
- In tab B, logged in successfully as j-skhdar_

**Comment by jwzimmer** [comment]
https://github.com/LLK/scratch-www/issues/1107 could help us figure out this kind of case!
