### ISSUE TITLE
Inconsistent display of waiting room - teacher may have been able to access other parts of site, then seen the waiting room, then been able to do things on the site again?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#975]
A teacher reported an issue with adding students to a studio. When I logged in as that teacher, I saw the waiting room. When I logged in two days later, I saw the homepage and in My Stuff I saw a studio, presumably (?) the one she wrote in to freshdesk about. At any rate, it sounds like she was doing something with some studio **before** I saw the waiting room when logged in as her, which shouldn't be possible. She should have gotten redirected to the waiting room consistently until her teacher account was approved.

I don't see any classes associated with the teacher, so I think she may have created regular accounts for her students? I'm not sure what happened.

Reported via freshdesk no. 60180:
> User name: [see scratchr2 case or freshdesk ticket]
Good morning. I am attempting to assign my students as curators and I get an error saying I don't have permission for that. Please advise.

On 10/17/16, I saw the waiting room when I login as this teacher. If she created student accounts, I'm not sure how. I'm also not sure how she created a studio since when she logs in she would get redirected to the waiting room?
<img width="678" alt="screen shot 2016-10-19 at 1 05 36 pm" src="https://cloud.githubusercontent.com/assets/1320456/19529145/c6567840-95fc-11e6-8b27-01d2afd50146.png">

On 10/19/16, I saw the teacher banner/ homepage when I logged in, I do not see any classes. I do see a studio, https://scratch.mit.edu/studios/3493165/, with her as the only curator. I am guessing this is the studio she was trying to invite her students to? She should be able to invite students to curate a non-class studio IIRC. So I'm not sure why she was seeing an error. I invited myself as a curator and saw "Curator successfully invited". I saw the invitation when I logged in as jwzimmer1990 (I didn't accept it).

I asked her:
> What studio are you adding the students to? How did you create the student accounts your students are using? Can you send me some of their usernames?

I will update if I hear back.

**Comment by jwzimmer** [comment]
Tracking the error when inviting students/ regular Scratch account users (I think?) to curate a non-class (I think?) studio: https://github.com/LLK/scratchr2/issues/4169.

**Comment by rschamp** [comment]
Does this user have any student accounts/ classes?

**Comment by jwzimmer** [comment]
I checked, this user has not created any student accounts, so I think this and scratch-www no. 975 are probably safe to close pending other suspicious reports. It sounds like the teacher was not using her teacher account to do these actions.
