### ISSUE TITLE
Student accounts showing as "Ungrouped" rank in forums

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-www#977]
![image](https://cloud.githubusercontent.com/assets/3766964/19540959/0d2633bc-9631-11e6-8bb6-cb97754ee3a5.png)

Link to post https://scratch.mit.edu/discuss/post/2252695/

https://scratch.mit.edu/users/4G1/

Not a big thing - but confusing.

**Comment by jwzimmer** [comment]
Thanks @Paddle2See! I think this case should probably be in scratchr2, so I'm going to move it there.

**Comment by jwzimmer** [comment]
Moved to LLK/scratchr2#4172

**Comment by coke11** [comment]
@Paddle2See the second I heard about teacher accounts, I was wondering how this would show up on the forums
