### ISSUE TITLE
Add Traditional Chinese (zh_TW) versions of activity cards

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#978]
From a translator:
We have translated the HOC Guides and Cards of Hide-and-Seek game and Animate Your Name into Traditional Chinese. 

Please feel free to make great use of these TC derivatives. 
Also, we have translated the corresponding Tips Windows into TC. It may take some time till the tips updated. 

Hide and Seek Game 
Guide: https://drive.google.com/file/d/0BxGSeFLcAOM5b2lNQ2NEME1ueEE/view 
Cards: https://drive.google.com/file/d/0BxGSeFLcAOM5TjE4Sm1xTlM4TVE/view 

Animate Your Name 
Guide: https://drive.google.com/file/d/0BxGSeFLcAOM5YWoxcE45SU5IOG8/view 
Cards: https://drive.google.com/file/d/0BxGSeFLcAOM5b0NBMEJIclF5b28/view 

Thank You! 

Best, 
YuHsien @ Scratch-TW (http://scratch-tw.strikingly.com/)

**Comment by chrisgarrity** [comment]
They've also translated the general scratch Cards:
https://drive.google.com/file/d/0BxGSeFLcAOM5T0NsWHJhYXRvYjQ/view

**Comment by chrisgarrity** [comment]
And today they added the new TTT cards:
https://drive.google.com/drive/folders/0BxGSeFLcAOM5T1lfaExlWllkamM

**Comment by chrisgarrity** [comment]
Postponing to January so we can discuss where to put translated resource materials in www

**Comment by Kenny2github** [comment]
Will this ever be fixed?

**Comment by chrisgarrity** [comment]
@Kenny2github the Hour of Code versions of these activities have been replaced by the ones on the  Tips page (https://scratch.mit.edu/tips). If you go to that page with your language set to zh_TW, you'll see the traditional Chinese versions of the activity cards. I guess we just forgot to close this issue.
