### ISSUE TITLE
Create New Modal Component

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#980]
We currently use `react-modal` to handle some of our modal elements, however it would be nice to have our own modal that can be a bit more customizable to the use cases we need it for. See #979 for a specific, new modal use case. The design for this modal needs to include the following elements:
- An "x" in the top right corner to close the modal (or top left, for rtl)
- Use `onclickoutside` so that clicking the opaque background closes the modal
- Rounded corners
- A blue opacity for the page behind

Needs a mobile design as well

**Comment by carljbowman** [comment]
![r2 0_modal](https://cloud.githubusercontent.com/assets/3409578/19689513/a65ad6fa-9a9b-11e6-96f9-fac56008be24.png)

![r2 0_modal grid](https://cloud.githubusercontent.com/assets/3409578/19689512/a653d076-9a9b-11e6-8c69-0a473ad985d6.png)

**Comment by kaschm** [comment]
Global content for modal:

Tutorial:
Make your own project using this step-by-step guide. 

Activity Cards:
Explore new coding ideas using this set of illustrated cards you can print out.

Educator Guide: 
Use this guide to plan and lead a one-hour Scratch workshop.

**Comment by ntlrsk** [comment]
(Note: we updated the text above.)

**Comment by carljbowman** [comment]
@ntlrsk - What do you think of the banner images?

Animate Your Name
![animate-your-name-banner](https://cloud.githubusercontent.com/assets/3409578/20073117/f51e3dd8-a4f8-11e6-9f50-128d9b90bd93.jpg)

Make it Fly
![make-it-fly-banner](https://cloud.githubusercontent.com/assets/3409578/20073132/fff2e22c-a4f8-11e6-94ff-df9db38d649c.jpg)

Make Music
![make-music-banner](https://cloud.githubusercontent.com/assets/3409578/20073139/092d57f0-a4f9-11e6-9da5-d37ab153060d.jpg)

Race to the Finish
![race-to-the-finish-banner](https://cloud.githubusercontent.com/assets/3409578/20073156/1c27fc48-a4f9-11e6-83e9-957844a7d044.jpg)

Hide and Seek
![hide-and-seek-banner](https://cloud.githubusercontent.com/assets/3409578/20073166/223c7db6-a4f9-11e6-8b49-3545d319ed6f.jpg)

Create a Story
![create-a-story-banner](https://cloud.githubusercontent.com/assets/3409578/20073174/293e1106-a4f9-11e6-8480-21888bad42e8.jpg)

Fashion Game
![fashion-game-banner](https://cloud.githubusercontent.com/assets/3409578/20073181/31c927fc-a4f9-11e6-9c80-bfacf23cb254.jpg)

Pong Game
![pong-game-banner](https://cloud.githubusercontent.com/assets/3409578/20073183/3705f024-a4f9-11e6-828a-00cec12f6f7b.jpg)

Let's Dance
![lets-dance-banner](https://cloud.githubusercontent.com/assets/3409578/20073191/3cdca3da-a4f9-11e6-962c-be55442d3424.jpg)

Catch Game
![catch-game-banner](https://cloud.githubusercontent.com/assets/3409578/20073200/4121dd02-a4f9-11e6-850c-b0058c31ec9f.jpg)

Virtual Pet
![virtual-pet-banner](https://cloud.githubusercontent.com/assets/3409578/20073208/4a52f488-a4f9-11e6-9e92-665fbd8403b2.jpg)

**Comment by ntlrsk** [comment]
Those look great! The two I had questions about are Let's Dance and the Story one. (1) For dance I wonder if it would be good to show different poses of the same dancers (like how Pong has animation)? (2) And for story either totally different characters each time, or more of a story progression? I can provide if that's helpful!

**Comment by carljbowman** [comment]
@ntlrsk - Thanks for the notes. 

1) Let's Dance - Did you have particular dance poses or sequence in mind? 
2) Create a Story - Awesome! Would you mind providing the 3 frames?

**Comment by ntlrsk** [comment]
Here's a possibility for dance as one big image - Champ99 in four dance positions across (right now one is hidden in this project): https://scratch.mit.edu/projects/129601771/#editor

**Comment by ntlrsk** [comment]
Or if we want the Dance project to look more like the sample project, a similar idea but with our other character  ( like this https://scratch.mit.edu/projects/129516330/#editor )

![image](https://cloud.githubusercontent.com/assets/4721032/20086185/530eda22-a53c-11e6-963c-af5c5bf4650b.png)

**Comment by ntlrsk** [comment]
For Story how about these three (which we use on the cards):
<img width="481" alt="story1" src="https://cloud.githubusercontent.com/assets/4721032/20086546/2a554d8e-a53f-11e6-8180-9c776f7cb222.png"> 
<img width="484" alt="story3" src="https://cloud.githubusercontent.com/assets/4721032/20086549/34716a5a-a53f-11e6-8aaa-07610a43924a.png">
<img width="479" alt="story4" src="https://cloud.githubusercontent.com/assets/4721032/20086554/42c61a4c-a53f-11e6-8137-766167878165.png">

**Comment by carljbowman** [comment]
@ntlrsk - I updated my [previous comment](https://github.com/LLK/scratch-www/issues/980#issuecomment-258942434)

1) Let's Dance - There are two versions V1 with Champ & V2 with Jo. Let me know if you have a preference.
2) Create a Story - We tried to avoid using text in the images for translation purposes, so I did not include the speech bubble.
3) Animate Your Name - As we discussed yesterday, I changed the name from 'Scratch' back to 'Ana'.

**Comment by ntlrsk** [comment]
@carljbowman 
Let's go with Jouvi for the dancer 
They all look good!

**Comment by ntlrsk** [comment]
One more minor question -was wondering whether to have the medium haircut for the Fashion Game. Excited to see these on the site!

**Comment by mewtaylor** [comment]
Implemented in https://github.com/LLK/scratch-www/pull/1008
