### ISSUE TITLE
Create HOC Homepage Banner

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#981]
New banner at the top of the homepage that will be present for the two weeks around Hour of Code. This will contain links to the new T3 page, as well as specific resources to get started with (in the form of new tiles, as specified in #979).

Components to use:
- Homepage banner element
- New resource tile (see #979)
- New event row (see #982)

**Comment by carljbowman** [comment]
# Logged-in State
* Includes 'Get Creative with Coding' Banner 
* Includes 'Design a Character' Event Row 

## Desktop - 12col

#### 'Get Creative with Coding' Banner
* 'More things to try' points to the Things to Try page (see #979)
* Resource tiles (everything above dotted line) point to their associated Tutorial
* 'See Cards and Guides' will open a modal with associated resources

#### 'Design a Character' Event Row
* Call to action & copy still being worked on - @kaschm 
* 'See the studio' will point at the studio - @kaschm 
* Video embed URL - @kaschm 

![r2 0_splash-logged-in](https://cloud.githubusercontent.com/assets/3409578/19686543/9285edec-9a8f-11e6-9e16-37689e43a1d5.jpg)

![r2 0_splash-logged-in grid](https://cloud.githubusercontent.com/assets/3409578/19686754/9469edba-9a90-11e6-83b7-d4e1eeaecd0c.jpg)


## Tablet to Desktop - 8col

#### 'Get Creative with Coding' Banner
* Tutorial tiles hidden
* Center align and stack text / 'See things to try' button

#### 'Design a Character' Event Row
* Hidden

![r2 0_splash-logged-in 8col](https://cloud.githubusercontent.com/assets/3409578/19687601/1a16e302-9a94-11e6-9f8b-3d8c5eabb09a.jpg)

![r2 0_splash-logged-in 8col-grid](https://cloud.githubusercontent.com/assets/3409578/19687603/1cb891f0-9a94-11e6-83ae-78099d7f5168.jpg)

## Mobile to Tablet - 6col

#### 'Get Creative with Coding' Banner
* Tutorial tiles hidden
* Center align and stack text / 'See things to try' button

#### 'Design a Character' Event Row
* Hidden
  
![r2 0_splash-logged-in 6col](https://cloud.githubusercontent.com/assets/3409578/19687916/756ddcd2-9a95-11e6-9ca0-1ce7f455cf06.jpg)

![r2 0_splash-logged-in 6col-grid](https://cloud.githubusercontent.com/assets/3409578/19687921/78e6b2a8-9a95-11e6-8566-f0adc3fa5770.jpg)


## Mobile - 4col

#### 'Get Creative with Coding' Banner
* Tutorial tiles hidden
* Center align and stack text / 'See things to try' button

#### 'Design a Character' Event Row
* Hidden

![r2 0_splash-logged-in 4col](https://cloud.githubusercontent.com/assets/3409578/19688072/10023964-9a96-11e6-830d-df029bc36fa9.jpg)

![r2 0_splash-logged-in 4col-gird](https://cloud.githubusercontent.com/assets/3409578/19688070/0bf07124-9a96-11e6-95f3-4cb8f973ab16.jpg)

---

# Non-logged-in State
* Includes 'Get Creative with Coding' Banner 

## Desktop
* Same behavior as 'Logged-in State' 

![r2 0_splash-logged-out](https://cloud.githubusercontent.com/assets/3409578/19688212/c32844ca-9a96-11e6-8afd-204008154032.jpg)

**Comment by jwzimmer** [comment]
### Testing

- The "see things to try" button has more padding in copy than on Staging
- Font is slightly less bold/ more spaced-out kerning in copy than on Staging (I know this is probably unavoidable as per previous discussions with @carljbowman but just want to verify)

**Comment by carljbowman** [comment]
@jwzimmer - Thanks for logging the diffs. Both are okay.

- Re Button: Totally fine, for consistency on the site we are using the button component which dictates the padding. That being said at some point we should update the styling to have more padding and remove the drop-shadow. 
- Re Font: Certainly falls in the case where there is not much we can do about how fonts will be rendered across browsers. What is on staging looks fine to me.

**Comment by jwzimmer** [comment]
How should the HOC banner work with the teacher banner?

**Comment by mewtaylor** [comment]
Added in https://github.com/LLK/scratch-www/issues/1073

**Comment by chrisgarrity** [comment]
On Mobile checked with Nexus 5X (Android 7.0):
* Portrait mode:
  * banner text is centered
  * See things to try link goes to /go (TTT page)
* Landscape mode:
  * banner text is centered within view
  * but page scrolls sideways, and the banner does not fill the page width
![screenshot_20161130-093414](https://cloud.githubusercontent.com/assets/399209/20756546/1097b5ea-b6e1-11e6-8ca3-7c5ea790380f.png)
  * See things to try link goes to /go (TTT page)
* Switching between portrait and landscape:
  * page does not scroll (fills view), but banner is off center
![screenshot_20161130-093720](https://cloud.githubusercontent.com/assets/399209/20756604/4d0c3adc-b6e1-11e6-9531-30755f4a0ccc.png)

**Comment by mewtaylor** [comment]
@chrisgarrity cool thanks – looks like this is a splash page problem (see the news box), which probably merits its own issue. Unless we want to just say it'll be addressed in the homepage redesign?

**Comment by chrisgarrity** [comment]
@mewtaylor Yes, I don't think this is really an hoc issue, just figured I'd log it. I think we should postpone to homepage redesign.

**Comment by jwzimmer** [comment]
@carljbowman confirmed the title/ button alignment is good as-is.
