### ISSUE TITLE
Create HOC Homepage Event Row

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-www#982]
For Hour of Code this year, we will include a new row on the homepage that will link to a new studio, and include some video content. The row will be:
- After the Featured Studios row
- Dismissable
- Only visible to logged in users

**Comment by carljbowman** [comment]
### Event Row

![r2 0_event-row](https://cloud.githubusercontent.com/assets/3409578/19689359/1f876b52-9a9b-11e6-9365-f75d8bd4df74.jpg)

![r2 0_event-row grid](https://cloud.githubusercontent.com/assets/3409578/19689358/1f78f194-9a9b-11e6-8258-e76387075c5e.jpg)

**Comment by coke11** [comment]
@mewtaylor Anyway I could help out with this?

**Comment by mewtaylor** [comment]
@coke11 thanks so much for the offer but I think @carljbowman and I are all set!

**Comment by carljbowman** [comment]
@mewtaylor - Here are those specs and assets

## Desktop - 12col
Banner is 12col
Text is 5col 
Video is 5col

![r2 0_event-banner 12col-nogrid](https://cloud.githubusercontent.com/assets/3409578/20491852/b874691e-afe0-11e6-99b6-edbde01e0e78.jpg)

![r2 0_event-banner 12col](https://cloud.githubusercontent.com/assets/3409578/20491856/bdf03df0-afe0-11e6-897a-7a44f727068e.jpg)

## Tablet to Desktop - 8col
Banner is 8col
Text is 3col 
Video is 4col

![r2 0_event-banner 8col](https://cloud.githubusercontent.com/assets/3409578/20491870/cb402c04-afe0-11e6-88aa-204161ee8a64.jpg)

## Mobile to Tablet - 6col
Banner is 6col 
Text is 5col
Video is 5col

![r2 0_studio-banner 6col](https://cloud.githubusercontent.com/assets/3409578/20491921/f3074060-afe0-11e6-9e17-e53bd098e71d.jpg)

## Mobile - 4col
Banner is 4col 
Text is 3col
Video is 3col

![r2 0_studio-banner 4col](https://cloud.githubusercontent.com/assets/3409578/20491974/1504f0f4-afe1-11e6-93f5-659e6f1c3fc0.jpg)

## Background Asset
![character-studio-bg](https://cloud.githubusercontent.com/assets/3409578/20492284/21748114-afe2-11e6-8b77-8d18b28fca5b.jpg)

**Comment by mewtaylor** [comment]
@carljbowman @kaschm do we have the video link too?

**Comment by jwzimmer** [comment]
### Testing

- Event row is on Staging with placeholder video
- The row doesn't dismiss, @mewtaylor is fixing

**Comment by jwzimmer** [comment]
Testing continued in https://github.com/LLK/scratch-www/pull/1081 (to be consistent with where the test cases @mewtaylor wrote are).

**Comment by mewtaylor** [comment]
Implemented in https://github.com/LLK/scratch-www/issues/1081
