### ISSUE TITLE
Homepage rows loading blank thumbnails with title "Project", Project ID is position in row - Staging

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#983]
Currently on staging I am seeing most of the homepage rows loading blank white thumbnails that say "Project" where the title would normally be. The "Projects by Scratchers I'm Following" row is loading projects, but none of the others are. (Staging, Chrome Version 54.0.2840.59 (64-bit), Mac OS X El Capitan, using throttling feature in Chrome set to DSL.)

When I click on the projects, I am redirected to https://`staging`/projects/1/, then https://`staging`/projects/2/, etc., according to their position in the row (1 was left-most, 2 was to the right of 1, etc.).

(I asked @rschamp if he knew of any reason to expect to see these rows behaving this way, and he didn't know of any.)

In the console I am seeing:
<img width="1280" alt="screen shot 2016-10-24 at 5 38 41 pm" src="https://cloud.githubusercontent.com/assets/1320456/19664978/d6266aec-9a10-11e6-8d10-fcb6fe23b29c.png">

(As well as the 404 error for missing thumbnails which has been around for a while (I think it's the same as https://github.com/LLK/scratchr2/issues/3767):
<img width="433" alt="screen shot 2016-10-24 at 5 39 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/19664990/e3c044b6-9a10-11e6-8f17-55424762b0ed.png"> )

<img width="1037" alt="screen shot 2016-10-24 at 5 33 15 pm" src="https://cloud.githubusercontent.com/assets/1320456/19664921/a8449a04-9a10-11e6-9a64-2057bfb69ec1.png">

**Comment by mewtaylor** [comment]
@jwzimmer I'm no longer seeing this – are you?

**Comment by jwzimmer** [comment]
@mewtaylor Nope, all the project rows are loading as usual and the project IDs are real project IDs.

**Comment by mewtaylor** [comment]
@jwzimmer should we close then?

**Comment by mewtaylor** [comment]
Talked w/ @jwzimmer offline – this appears to have been transient, so closing.

**Comment by jwzimmer** [comment]
@morantsur also encountered this on Production today during DDoS issues. So it seems like a failure state when Scratch is having connectivity problems? (@mewtaylor please correct if that's not an accurate description.)

**Comment by mewtaylor** [comment]
yup that's correct @jwzimmer thanks!
