### ISSUE TITLE
Missing space on "Projects curated by" row

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-www#984]
![image](https://cloud.githubusercontent.com/assets/3766964/19725505/c32449e8-9b53-11e6-9f14-101cf4709594.png)

Highly visible...

**Comment by rschamp** [comment]
Dupe of https://github.com/LLK/scratch-www/issues/965 (fixed for this release)

**Comment by coke11** [comment]
@rschamp There were three issues about this...
