### ISSUE TITLE
Interactive debug page that runs the common tests we ask people to run when they write in for help?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#990]
@colbygk & I were wondering if this might be helpful with increasing how often we are able to get all the relevant info we ask for back from users when they write in to freshdesk/ help with questions about connectivity/ server issues that are often fleeting, vague, and hard to diagnose or reproduce. 

We have trouble helping with these issues in part because it is hard to get enough information about them. Generally we respond in freshdesk with a list of requests for more info, including fastly-debug and some commandline tests. At least in some cases (see freshdesk no. 60744), the reporting user was confused by how to carry out the tests. If we could lower the barrier to gathering the necessary info and sending it back to us, maybe we would have a higher success rate with addressing these kinds of user-reported issues.

@colbygk suggested the page could involve:

> have https://scratch.mit.edu/debug redirect to fastly-debug.com
> it could even try to do a javascript ping and host name lookups.  And if they can't get that far, they fall back to the ping/nslookup command line

Maybe they could submit the info to us (help@scratch email) on the same page (although we would need to require they submit their email as well so we could respond), similar to the contact us form. Or they could copy-paste or download the results from the page.

If we had a page like this, we could potentially also try to run more tests/ gather more info than we would be willing to ask them to do manually, because we try to ask for the minimum needed usually so as to increase how likely we are to get a complete response. That wouldn't be a concern with a page that ran the tests for them.

We would need to make it clear that they should run the page on one of the affected computers, if at all possible while experiencing the issues, but we already have to try to communicate that and don't have a good way to know for sure if it happened (so that's not a new concern).

**Here's more or less what we generally ask for via freshdesk tickets:**

```
If you continue to experience this issue, please take the following steps, which will provide us with diagnostic information. If possible, please try to perform these actions while you are experiencing the issue, from one of the affected computers.

 - Open a browser and go to http://fastly-debug.com and copy-paste all of the information on that page in a response email to us. This will provide more information for us to understand the connection from your local environment and our servers.

- Please use a terminal or command window to run these 3 tests and email the results back to us:
  (a) On Windows, Mac OS X and/or Linux:
  nslookup scratch.mit.edu
  (b) On Mac OS X or Linux:
  ping -c 5 scratch.mit.edu
  On Windows:
  ping -n 5 scratch.mit.edu
  (c) On Mac OS X and Linux:
  traceroute scratch.mit.edu
  On Windows:
  tracert scratch.mit.edu

Please send us any errors from the JavaScript console as well.
```

**Comment by jwzimmer** [comment]
We were talking today in the IPM about making the contact us page more informative (like having dropdowns to choose from with different choices of category, etc.). Maybe this could be part of the contact us page if you choose "connectivity issues", or something like that, or maybe it should be it's own page.

**Comment by jwzimmer** [comment]
Suggestion from @rschamp: https://github.com/LLK/scratchr2/issues/4236#issuecomment-258854055

**Comment by jwzimmer** [comment]
Suggestion from @cwillisf:
> ...a checkbox (default checked) for "attach event logs" or something when reporting a bug / requesting support...

**Comment by kaschm** [comment]
Moved to LLK/scratch-ops#235
