### ISSUE TITLE
microworlds (embed editor) no longer appearing

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#994]
The microworlds are no longer appearing.

For example, see:
http://scratch.mit.edu/pathways/hiphop
and
https://scratch.mit.edu/projects/embed-editor/114804408/?isMicroworld=true

I looked on Chrome and Firefox. Mitchel let me know. 

Do you know what change may have caused this? They were working the previous week. Thanks.

**Comment by mewtaylor** [comment]
@rschamp @ntlrsk this is a bug on the legacy code, going to move this there
