### ISSUE TITLE
minor edits on cards page

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#995]
- Update thumbnail for Hide and Seek 
(@mewtaylor the yellow thumbnail I had sent via Slack that shows Gobo on it: cards-hide.jpg )

- Rename "Dress-Up Game" to "Fashion Game"

- Rename "Create a Pong Game" to simply "Pong Game"

Looking good!

**Comment by coke11** [comment]
@mewtaylor @ntlrsk I can take this one if I can access the image

**Comment by ntlrsk** [comment]
Thanks for looking into this! For updating the Hide-and-Seek thumbnail, the image's name and URL should stay the same as before ( https://scratch.mit.edu/images/cards/cards-hide.jpg ).That image needs to be replace with this version of the image: https://www.dropbox.com/s/2g5722njayc6zx2/cards-hide.jpg?dl=0

**Comment by mewtaylor** [comment]
@coke11 I have this on my to-do list for today, so I can take it. Thanks for the offer though!

**Comment by coke11** [comment]
@mewtaylor Thanks :D
