### ISSUE TITLE
Updates to Privacy Policy

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#996]
Under "How does the Scratch Team use my Information?" add a bullet at the bottom of the list:

- Scratch reserves the right to share user information with the appropriate authorities (including schools, school districts, and law enforcement, when necessary) for the purposes of protecting the safety of users, other individuals, or the security of the site.

Typo in the list:

- If we detect repeated abusive behavior from your account, IP address, or email address, we may share your account name, IP address, and the time and content of the abusive behavior with the IP address owner (such as a school or internet service provide**d**). 

should be:

- If we detect repeated abusive behavior from your account, IP address, or email address, we may share your account name, IP address, and the time and content of the abusive behavior with the IP address owner (such as a school or internet service provide**r**).

**Comment by TheGrits** [comment]
I'm willing to take this one!
