### ISSUE TITLE
Changes to General FAQ and Teacher FAQ 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#997]
Add to general [Scratch FAQ](https://scratch.mit.edu/info/faq), “Scratch in Schools” Section

**Is Scratch 2.0 (online version) compliant with local and federal data privacy laws?** 
Scratch cares deeply about the privacy of students and of all individuals who use our platform. We have in place physical and electronic procedures to protect the information we collect on the Scratch website. Although we are not in a position to offer contractual guarantees with each entity that uses our free educational product, we are in compliance with all federal laws that are applicable to MIT, a 501(c)(3) organization and the entity that created and maintains Scratch. We encourage you to read the Scratch Privacy Policy for more information. 

Add to [Teacher Account FAQ](scratch.mit.edu/educators/faq), “Student Accounts” section

**What data does Scratch collect about students?**
When a student first signs up on Scratch, we ask for basic demographic data including gender, age (birth month and year), country, and an email address for verification. This data is used (in aggregated form) in research studies intended to improve our understanding of how people learn with Scratch. When an educator uses a Scratch Teacher Account to create student accounts in bulk, no student demographic data is required for account setup.

**Is Scratch 2.0 (online version) compliant with local and federal data privacy laws?** 
Scratch cares deeply about the privacy of students and of all individuals who use our platform. We have in place physical and electronic procedures to protect the information we collect on the Scratch website. Although we are not in a position to offer contractual guarantees with each entity that uses our free educational product, we are in compliance with all federal laws that are applicable to MIT, a 501(c)(3) organization and the entity that created and maintains Scratch. We encourage you to read the Scratch Privacy Policy for more information.

**Comment by TheGrits** [comment]
I'm willing to take this one as well!
