### ISSUE TITLE
Broken video thumbnail on HipHop microworlds page in IE 11

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#998]
Thumbnail for the video is broken/ missing in IE 11 on Win 7 VM, Production, but if you click the video thumbnail it brings up the video as expected.

<img width="933" alt="screen shot 2016-11-03 at 5 02 51 pm" src="https://cloud.githubusercontent.com/assets/1320456/19985132/9c305a94-a1e7-11e6-85b5-642e504aa6f4.png">

It looks fine in Firefox 49 and Chrome 54 on Mac OS 10.11, Production.

<img width="1042" alt="screen shot 2016-11-04 at 9 42 17 am" src="https://cloud.githubusercontent.com/assets/1320456/20007530/136065ba-a273-11e6-8c3a-aea24c0a9fcb.png">

**Comment by TheGrits** [comment]
Can confirm using Internet Explorer on a Windows 7 machine. What's strange is that the built in project player isn't even showing up:
![scratchmicroworldbug](https://cloud.githubusercontent.com/assets/12952370/20035082/4f290310-a3ac-11e6-8ae2-c23eea5172b0.PNG)

**Comment by TheGrits** [comment]
I don't know if this is causing the bug, but there's something strange going on with the link for the hiphop video. The link video id is different from the thumbnail video id:

Fashion microworld:
https://github.com/LLK/scratch-www/blob/develop/src/views/microworld/fashion/fashion.json#L9-L14

Hiphop microworld:
https://github.com/LLK/scratch-www/blob/develop/src/views/microworld/hiphop/hiphop.json#L9-L14

**Comment by chrisgarrity** [comment]
@theGrits Thanks for helping us repro these IE bugs

**Comment by sehgalvibhor** [comment]
I can replicate the same issue in Mozilla Firefox 62.0 and Microsoft Edge. Potentially because these browsers don't support WebP images.

![image](https://user-images.githubusercontent.com/10993808/46914914-d8ef4f80-cfc1-11e8-9995-b4a5103fb18a.png)
